### ISSUE TITLE
After breaking changes i can't use where clause with relation that is null

### ISSUE THREAD

**Issue by peturgeorgievv** [typeorm/typeorm#8816] opened 2022-03-27 10:47 UTC
## Issue Description
Before the breaking changes i had a query(find) which was giving me results based if the relation is null. Meaning i have a Workout which is possible to be attached to a WorkoutPlan, but i want to query only those that don't have attached workoutPlan to the Workout

### Expected Behavior
To be able to get them same as before with null

### Actual Behavior
I receive all, or none of the workouts

Before ->
```
let where= {
        workoutPlan: null,
      };
      if (!!input?.workoutPlanId) {
        where.workoutPlan = input.workoutPlanId;
      }

      // Something like below
      const workouts = await this.workoutRepository.find({
      select = [
      "id",
      "title",
    ],
    where,
relations: ["workoutPlan"]
      });
      return workouts;
```
And now with new syntax it doesn't work
```
let where= {
        workoutPlan: Not(IsNull()), // or just null
      };
      if (!!input?.workoutPlanId) {
        where.workoutPlan = { id: input.workoutPlanId};
      }

      // Something like below
      const workouts = await this.workoutRepository.find({
      select = {id: true, title: true},
    where,
relations: { workoutPlan: true }
      });
      return workouts;
```

I am using postgre
### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment] 2022-03-27 14:11
create a PR with a failing test and I'll take a look

**Comment by peturgeorgievv** [comment] 2022-03-27 15:39
I can't seem to run the tests in the repository. I do clone, npm install, npm run compile, npm run tests? Are there any different steps i am missing?

**Comment by pleerock** [comment] 2022-04-05 10:04
Please follow the contribution guides and checkout other PRs as an example.

**Comment by pleerock** [comment] 2022-08-25 14:08
duplicate of #8890

**Closed by pleerock** 2022-08-25 14:08 UTC
Labels: bug, needs more info, requires triage
