### ISSUE TITLE
Issue with schema creation in 0.3.16

### ISSUE THREAD

**Issue by N-Andronopoulos** [typeorm/typeorm#10090] opened 2023-05-30 09:24 UTC
### Issue description

Syncronise: true messes up stuff after first run (tries to recreate db and fails)

### Expected Behavior

To work after restarts.
Should be obvious, aka not to recreate the schema since nothing's changed.

Note: I think should happen in migrations as well....

### Actual Behavior

query: ALTER TABLE `orders` ADD `id` varchar(36) NOT NULL PRIMARY KEY
query failed: ALTER TABLE `orders` ADD `id` varchar(36) NOT NULL PRIMARY KEY
error: Error: Duplicate entry '' for key 'orders.PRIMARY'
query: ROLLBACK
[Nest] 651697  - 05/30/2023, 11:04:50 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
QueryFailedError: Duplicate entry '' for key 'orders.PRIMARY'

### Steps to reproduce

See sample project.
But in general start app with synchronize: true and restart it.
(It also happens when you start the app with sync: true an then try doing a migration, see migrations/ on sample repo)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    linux / win    |
| Node.js version     | v18.16.0  |
| Typescript version  | ^5.0.0  |
| TypeORM version     | 0.3.16  |

### Additional Context

====> [Sample Project](
https://github.com/N-Andronopoulos/typeorm-issue-schema-creation)

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by N-Andronopoulos** [comment] 2023-05-30 11:46
I think there a fix for it maybe? If it is please close this one :)
#10041

**Comment by peter-rybar** [comment] 2023-06-08 21:26
Still no fix? It is a critical issue!

**Comment by Mateozmaldonado17** [comment] 2023-06-09 03:51
Omg, i had this issue for long time, so i was thinking that was something wrong with my code

**Comment by peter-rybar** [comment] 2023-06-11 10:49
OK guys, no fix still? Really?

**Comment by slyk** [comment] 2023-06-12 11:27
> OK guys, no fix still? Really?

For me this helps right now (I got UUID generated in code, but maybe even without it it would work)
```typescript
  //@PrimaryGeneratedColumn('uuid')
  @PrimaryColumn({type:"varchar", generated:"uuid",length:36})
  uuid?: string;
```

**Comment by Mateozmaldonado17** [comment] 2023-06-13 00:36
@slyk nice! but now the synchronize: true its not working :(

**Comment by N-Andronopoulos** [comment] 2023-06-13 05:58
You can stay in version 0.3.10 with mysql2 2.3.x ....

**Comment by slyk** [comment] 2023-06-13 06:54
> @slyk nice! but now the synchronize: true its not working :(
just do not sync without any errors? this should not do this, its just other column settings.

**Comment by Mateozmaldonado17** [comment] 2023-06-14 01:51
I'm using nestjs 9 with @nestjs/typeorm 9.0.1 :/

**Comment by hox** [comment] 2023-06-17 18:19
> You can stay in version 0.3.10 with mysql2 2.3.x ....

Can reproduce on mysql2@^3.3.5 typeorm@^0.3.16, was able to confirm that downgrading to typeorm@0.3.10 and mysql2@2.3 fixed the issue.

**Comment by Mateozmaldonado17** [comment] 2023-06-20 13:17
but i use nestjs with nestjs/typeorm how can downgrade it?

**Comment by imatheus-lucas** [comment] 2023-06-20 18:23
> ### Issue description
> Syncronise: true messes up stuff after first run (tries to recreate db and fails)
> 
> ### Expected Behavior
> To work after restarts. Should be obvious, aka not to recreate the schema since nothing's changed.
> 
> Note: I think should happen in migrations as well....
> 
> ### Actual Behavior
> query: ALTER TABLE `orders` ADD `id` varchar(36) NOT NULL PRIMARY KEY query failed: ALTER TABLE `orders` ADD `id` varchar(36) NOT NULL PRIMARY KEY error: Error: Duplicate entry '' for key 'orders.PRIMARY' query: ROLLBACK [Nest] 651697 - 05/30/2023, 11:04:50 AM ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)... QueryFailedError: Duplicate entry '' for key 'orders.PRIMARY'
> 
> ### Steps to reproduce
> See sample project. But in general start app with synchronize: true and restart it. (It also happens when you start the app with sync: true an then try doing a migration, see migrations/ on sample repo)
> 
> ### My Environment
> Dependency	Version
> Operating System	linux / win
> Node.js version	v18.16.0
> Typescript version	^5.0.0
> TypeORM version	0.3.16
> ### Additional Context
> ====> [Sample Project](https://github.com/N-Andronopoulos/typeorm-issue-schema-creation)
> 
> ### Relevant Database Driver(s)
> * [ ]  aurora-mysql
> * [ ]  aurora-postgres
> * [ ]  better-sqlite3
> * [ ]  cockroachdb
> * [ ]  cordova
> * [ ]  expo
> * [ ]  mongodb
> * [x]  mysql
> * [ ]  nativescript
> * [ ]  oracle
> * [ ]  postgres
> * [ ]  react-native
> * [ ]  sap
> * [ ]  spanner
> * [ ]  sqlite
> * [ ]  sqlite-abstract
> * [ ]  sqljs
> * [ ]  sqlserver
> 
> ### Are you willing to resolve this issue by submitting a Pull Request?
> Yes, I have the time, but I don't know how to start. I would need guidance.

Friend, this error is possibly caused because your table has data and you are trying to add a primary key column, possibly you will have to delete data and then run the migration or try another approach to create that primary column you want. Hope this helps.

**Comment by N-Andronopoulos** [comment] 2023-06-20 19:32
@imatheus-lucas What are you talking about? So if I start this project with no schema then I generate one, then if I change nothing and start it again, it tries to change the schema and fail. 
Therefore you think this is correct behavior? 
Please elaborate because until version 0.3.10 and in other frameworks (like spring data) this is not the case.

**Comment by pleerock** [comment] 2023-06-20 19:47
thanks @N-Andronopoulos for the fix. `0.3.17` was released with the fix.

**Closed by pleerock** 2023-06-20 19:47 UTC
Labels: bug, requires triage

**Comment by N-Andronopoulos** [comment] 2023-06-21 18:52
Thank you!
I can confirm that both sync and migrations are working like butter!
Good job!

**Comment by aosatinskyzengo** [comment] 2023-08-17 10:06
0.3.17 did the job. Also working with NestJS. Thanks!
