### ISSUE TITLE
Error running migration script for oracle 11g

### ISSUE THREAD

**Issue by damistry10090** [typeorm/typeorm#7088] opened 2020-11-19 09:34 UTC
Hello,

I am trying to create a new table (based on entity) in my oracle 11g database using typeorm. 
For this I have generated a migration script using **npm run typeorm migration:generate -- -n migrationNameHere**.
On trying to run the script, I get the error 
`CREATE TABLE "custom_migration_table" ("id" number GENERATED BY DEFAULT AS IDENTITY, "timestamp" number NOT NULL, "name" varchar2(255) NOT NULL, CONSTRAINT "PK_0ee8d1a09834605db454c13a49e" PRIMARY KEY ("id"))
error: [Error: ORA-02000: missing ALWAYS keyword] {
  errorNum: 2000,
  offset: 61
}`

While trying to create the table custom_migration_table, it is trying to generate an identity column which is not supported by oracle 11g.
Is there any way through which I can fix it?

**Comment by nebkat** [comment] 2020-11-19 13:24
This is where this query is made:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/driver/oracle/OracleQueryRunner.ts#L1565

If you figure out what the expected behavior should be, both for your version 11g and later versions, you can maybe add a flag somewhere to fix this, shouldn't be too hard. Unfortunately my search about the syntax on Google didn't reveal any good explanation as to why it is necessary.

**Comment by imnotjames** [comment] 2020-11-22 01:21
Pretty sure we only officially support Oracle 12+

**Comment by nebkat** [comment] 2020-11-22 01:27
Are there any intentions to add driver version specific functionality (even set by the user as a connection param)? The query builders especially are already full of driver specific code so a few extra ifs for versions wouldn't be too much of a problem.

**Comment by imnotjames** [comment] 2020-11-22 03:18
We do that already for some drivers (postgres, I think?)

Usually on connection the driver will query the server what version they are and enable / disable features for that version as needed

**Comment by nebkat** [comment] 2020-11-23 03:25
> We do that already for some drivers (postgres, I think?)

Ah I see, found one for MySQL, didn't notice before since it's not defined in QueryRunner.

Oracle 11g extended support is ending at the end of 2020 so probably not worth supporting unless the differences are very minor.

**Comment by imnotjames** [comment] 2021-07-03 05:22
Given that oracle 11 is out of support & we don't have any path forward I'm closing this.

**Closed by imnotjames** 2021-07-03 05:22 UTC
