### ISSUE TITLE
postgres - count query fails for some tables

### ISSUE THREAD

**Issue by adnan-kamili** [typeorm/typeorm#752] opened 2017-08-09 03:09 UTC
**Typeorm version: 0.1.0-alpha.33**

If `mysql` adapter is used following query returns 0 for empty table as expected:

`const customFieldCount = await this.customFieldRepository.count({ productVersionId: productVersion.id });`

But if `postgres` adapter is user it crashes with the following error:

```javascript
name:"QueryFailedError"
parameters:Array(1) [1]
position:"93"
query:"SELECT COUNT(DISTINCT("CustomField"."id")) as "cnt" FROM "custom_field" "CustomField" WHERE CustomField.productVersionId=$1"
routine:"errorMissingRTE"
schema:undefined
severity:"ERROR"
stack:"QueryFailedError: missing FROM-clause entry for table "customfield"\n    at new QueryFailedError (/Volumes/Data/Web/test/test-web-api-2/node_modules/typeorm/error/QueryFailedError.js:27:28)\n    at Query.callback (/Volumes/Data/Web/test/test-web-api-2/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:214:38)\n    at Query.handleError (/Volumes/Data/Web/test/test-web-api-2/node_modules/pg/lib/query.js:143:17)\n    at Connection.connectedErrorHandler (/Volumes/Data/Web/test/test-web-api-2/node_modules/pg/lib/client.js:135:26)\n    at emitOne (events.js:115:13)\n    at Connection.emit (events.js:210:7)\n    at Socket.<anonymous> (/Volumes/Data/Web/test/test-web-api-2/node_modules/pg/lib/connection.js:118:12)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:250:12)\n    at readableAddChunk (_stream_readable.js:237:11)\n    at Socket.Readable.push (_stream_readable.js:195:10)\n    at TCP.onread (net.js:588:20)"
table:undefined
where:undefined
__proto__:Error {constructor: }
```

**Comment by pleerock** [comment] 2017-08-10 09:49
I cannot reproduce your issue. Can you check again this issue in  0.1.0-alpha.34 and if you still have a problem provide minimal problem reproduction code.

**Comment by adnan-kamili** [comment] 2017-08-12 07:37
I updated to latest version and checked sql log generated for two tables, one for which the count query failed with above error and the other for which it worked:

Failed query:

`SELECT COUNT(DISTINCT("CustomField"."id")) as "cnt" FROM "custom_field" "CustomField" WHERE CustomField.productVersionId=$1`

Working query:

`SELECT COUNT(DISTINCT("ProductVersion"."id")) as "cnt" FROM "product_version" "ProductVersion" WHERE "ProductVersion"."productId"=$1`

As you can see in the first query no quotes were added in `CustomField.productVersionId=$1` but they were added in `"ProductVersion"."productId"=$1`

I added the missing quotes in first query and executed it in pgAdmin 4 and it worked. So, the issue seems to be related to missing quotes

**Comment by pleerock** [comment] 2017-08-12 19:26
right the issue in missing quotes however I could not reproduce your issue in my tests (see link above). Please create a minimal reproduction git repo which I can debug.

**Comment by adnan-kamili** [comment] 2017-08-15 08:23
I have created a branch wherein it can be replicated:

https://github.com/adnan-kamili/koa-web-api/tree/typeorm

After `npm start` hit the following url:

http://localhost:4000/v1/custom-fields

**Comment by pleerock** [comment] 2017-09-08 07:56
Please never ever again provide people big repositories for their exploration. If you really want others to spend their time please provide a small examples with one-two reproduction files. Closing it.

**Closed by pleerock** 2017-09-08 07:56 UTC
Labels: needs more info

**Comment by adnan-kamili** [comment] 2017-09-08 09:48
Sorry for that, it replicates for following model:

https://github.com/adnan-kamili/koa-web-api/blob/typeorm/src/models/CustomField.ts
 and `GetCount()` function in following file:

https://github.com/adnan-kamili/koa-web-api/blob/typeorm/src/controllers/CustomFieldsController.ts
