### ISSUE TITLE
JoinColumn names conflict

### ISSUE THREAD

**Issue by clovis-maniguet** [typeorm/typeorm#4324] opened 2019-06-19 14:28 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17`

**Steps to reproduce the problem**

It seems impossible to use a field as a foreign key for more than one relation.

Consider 3 tables: `person`, `competitorPerson`, `personTranslation`.

The relations are the following:
- A person has many personTranslation (One-to-Many) ✔
- A person has many competitorPerson (One-to-Many) ✔
- A competitorPerson has many personTranslation (Many-to-One) ❌

```
----------         ---------------------
| person | 1 --- N | personTranslation |
----------         ---------------------
      1                N
      |                |
      N                1
     --------------------
     | competitorPerson |
     --------------------
```

### person
```js
export class PersonEntity {
  @PrimaryColumn()
  id: number;
  
  @OneToMany(type => PersonTranslationEntity, translation => translation.person)
  @JoinColumn([
    {name: 'id', referencedColumnName: 'personId'}
  ])
  translations?: PersonTranslationEntity[];
}
```

### competitorPerson
```js
export class CompetitorPersonEntity {
  @PrimaryColumn()
  personId: number;
  
  @OneToMany(() => PersonTranslationEntity, translation => translation.competitorPerson)
  @JoinColumn([
    {name: 'personId', referencedColumnName: 'personId'}
  ])
  translations?: PersonTranslationEntity[];
}
```

### personTranslation
```js
export class PersonTranslationEntity {
  @PrimaryColumn()
  personId: number;

  @ManyToOne(() => PersonEntity, person => person.translations)
  @JoinColumn([
    {name: 'personId', referencedColumnName: 'id'}
  ])
  person?: PersonEntity;

  @ManyToOne(() => CompetitorPersonEntity, competitorPerson => competitorPerson.translations)
  @JoinColumn([
    {name: 'personId', referencedColumnName: 'personId'}
  ])
  competitorPerson?: CompetitorPersonEntity; 
}
```

As you can see, `personTranslation.personId` is used as a foreign key for 2 relations.

### Error
```sh
QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'person.personId' in 'on clause'
```

The SQL query logged is not using the good relation name
```sql
LEFT JOIN `person_translation` `personTranslations`
ON `personTranslations`.`personId`=person.personId # should be person.id
AND (`personTranslations`.`locale` = ?)
```

The error seems to come from the fact that 2 `JoinColumn` have the same name passed as param in `personTranslation`, which is relevant since both relations use the same field. Indeed `personTranslation` has 2 Many-to-One relations using the foreign key `personTranslation.personId`. One references the field `person.id`, but in the SQL shown above you can see the referenced table's foreign key is not `id` as it should, but `personId`, which is an unexpected behaviour and causes the query to fail since `person.personId` doesn't exist.

### Workaround

Instead of using the same foreign key for 2 relations, I created another foreign key with a different name. Each relation uses its own foreign key. This way, the query works fine (though it's just a workaround).

### personTranslation
```js
export class PersonTranslationEntity {
  @PrimaryColumn()
  id: number; // new foreign key

  @PrimaryColumn()
  personId: number;

  @ManyToOne(() => PersonEntity, person => person.translations)
  @JoinColumn([
    {name: 'id', referencedColumnName: 'id'}
  ])
  person?: PersonEntity;

  @ManyToOne(() => CompetitorPersonEntity, competitorPerson => competitorPerson.translations)
  @JoinColumn([
    {name: 'personId', referencedColumnName: 'personId'}
  ])
  competitorPerson?: CompetitorPersonEntity; 
}
```

You may note that since `translationPerson.id` and `translationPerson.personId` are duplicates, it is not required to update the referenced column name in `person`: whether it is `id` or `personId` won't change anything (except coherence on reading).

**Comment by LuisAngelMoralesRomo** [comment] 2019-07-17 22:33
`@JoinColumn` goes with the `@ManyToOne` side only.

BTW, you don't need `@JoinColumn` on `@ManyToOne`/`@OneToMany` relations, see 
[Many-to-one / one-to-many relations](https://typeorm.io/#/many-to-one-one-to-many-relations)

**Comment by PierreTurnbull** [comment] 2019-07-24 14:15
> `@JoinColumn` goes with the `@ManyToOne` side only.
> 
> BTW, you don't need `@JoinColumn` on `@ManyToOne`/`@OneToMany` relations, see
> [Many-to-one / one-to-many relations](https://typeorm.io/#/many-to-one-one-to-many-relations)

Removing @JoinColumn doesn't solve the problem (though it's a good thing to remove them when they are useless, ty for the information).

**Comment by imnotjames** [comment] 2020-10-10 09:48
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 09:48 UTC
Labels: bug, driver: mariadb, driver: mysql
