### ISSUE TITLE
Initialize the query builder to include some custom functions

### ISSUE THREAD

**Issue by apiel** [typeorm/typeorm#6757] opened 2020-09-22 06:27 UTC
**Issue type:**

[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ x] `mongodb`
[ x] `mssql`
[ x] `mysql` / `mariadb`
[ x] `oracle`
[ x] `postgres`
[ x] `cockroachdb`
[ x] `sqlite`
[ x] `sqljs`
[ x] `react-native`
[ x] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, would be great to be able to create a custom query builder to re-use a functions.
Right now I have this function that I want to use multiple time in different queries:
```
function whereSucess<Entity = any>(qb: SelectQueryBuilder<Entity>): SelectQueryBuilder<Entity> {
    return qb.andWhere(`u.u_last_error IS NULL`);
}
```
and then I apply to my qb like this:
```
const qb = getManager()
        .createQueryBuilder()
        .from(Url, 'u')
        .select()
        .addSelect('COUNT(u.id)', 'stat');
const { stat } = await whereSuccess(qb).getRawOne();
```
When it is only one function to re-use it is not so cumbersome but as soon as I start to encapsulate multiple of them, it start to be very hard to read/maintain, e.g.: `await groupByHost(whereInLast24h(whereSuccess(qb))).getRawOne();`

So it would great to initialize the query builder to include some custom functions to be able to do: 
```
const { stat } = await qb.whereSuccess()
                         .whereInLast24h()
                         .groupByHost()
                         .getRawOne();
```

**Comment by imnotjames** [comment] 2020-09-25 21:57
Maybe something like https://mikro-orm.io/docs/filters/ ?

**Comment by apiel** [comment] 2020-09-29 09:50
@imnotjames this library seem really cool but just be amazing to do `await qb.whereSuccess().getOne();`

**Comment by imnotjames** [comment] 2020-09-29 14:06
I'm not sure that it would be simple to type that - you'd effectively be monkey patching the types - and you could technically do that anyway.

Using string identifiers for the where filter would be easier on typing and the API - but would it accomplish what you're looking for there?

**Comment by imnotjames** [comment] 2020-10-10 12:29
I think this is a duplicate of https://github.com/typeorm/typeorm/issues/1601

**Comment by imnotjames** [comment] 2020-10-10 12:29
Duplicate of #1601

**Closed by imnotjames** 2020-10-10 12:29 UTC
Labels: driver: cockroachdb, driver: cordova, driver: expo, driver: mongodb, driver: mssql, driver: mysql, driver: oracle, driver: postgres, driver: sqlite, driver: sqljs, new feature
