### ISSUE TITLE
How can I sort relations loaded with find's "relations" option?

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#2620] opened 2018-08-04 16:36 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm loading an entity with a one-to-many relationship. So, that relationship is an array of entities associated with the entity I'm querying. I'd like to specify an order for that array of entities.

Example (Users and their Photos): I'd like to query a user, load their photos as a relation, and the photos should be loaded by their createdAt date:

```javascript
const users = await this.usersRepository.findOne(conditions, {
      relations: ['photos'],
      order: {
        // Just getting one user, but  the photos should be ordered in 'DESC' by 'photos.createdAt'
      },
    });
```

Is there a way to do this?

**Comment by pvaidhya** [comment] 2018-08-06 19:10
I don't think currently its supported, lets take this as a new feature request.

**Comment by serranoarevalo** [comment] 2018-08-22 17:05
Can't you do this?

```js
const users = await this.usersRepository.findOne(conditions, {
      relations: ['photos'],
      order: {
       photos: {
            id: "ASC"
      },
    });
```

**Comment by kodayashi** [comment] 2018-08-23 18:35
Hey @serranoarevalo - Let me check and get back to ya, I believe that didn't work. Thanks for the follow up!

**Comment by serranoarevalo** [comment] 2018-08-23 19:57
@kodayashi It actually did not work, I ended up with a pretty simple query builder.

**Comment by kodayashi** [comment] 2018-08-24 00:58
cool @pvaidhya a feature request sounds like a plan ;)

**Comment by nicolespicymayoo** [comment] 2018-08-30 18:18
+1 vote for feature request

**Comment by iljab** [comment] 2018-09-02 14:29
@serranoarevalo Can you tell me how did you manage to order the relations?

**Comment by nicolespicymayoo** [comment] 2018-09-02 22:54
@iljab here is a solution using the sort method. 
Both the photos will be displayed in ascending order by id

```javascript
const users = await connection.manager.find(Users, { order: { id: "ASC" }, relations: ["tasks"] })
users.forEach((user) => {
  user.photos.sort((a, b) => {
    if (a.id < b.id) {
      return -1
    }
    if (a.id > b.id) {
      return 1
    }
    return 0
  })
})
```

**Comment by nicolespicymayoo** [comment] 2018-09-02 22:56
@iljab here is a solution using the sort method.
The photos will be displayed in ascending order by id

```javascript
const users = await connection.manager.find(Users, { order: { id: "ASC" }, relations: ["photos"] })
users.forEach((user) => {
  user.photos.sort((a, b) => {
    if (a.id < b.id) {
      return -1
    }
    if (a.id > b.id) {
      return 1
    }
    return 0
  })
})```

**Comment by iljab** [comment] 2018-09-03 18:51
Thank you for your suggestions. The following looks like it does the job for me too:

```javascript
return this.departmentsRepository.createQueryBuilder('departments')
            .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
            .where("departments.deleted_at IS NULL AND departments.is_active = 1")
            .orderBy({
                'departments.name': 'ASC',
                'locations.name': 'ASC'
            })
            .getMany();
``` 

The departments and locations are ordered by name.

**Comment by mazyvan** [comment] 2019-02-22 17:26
any update on this? I haven't take a look at the road map. But this seems like a really good feature

**Comment by jvandenaardweg** [comment] 2019-03-11 07:23
Would also vote for this as a feature request. The suggestion of @serranoarevalo seems good!

**Comment by Jamie452** [comment] 2019-06-20 10:15
It would also be useful if `take` worked with this too.

To allow for only returning X number of the ordered related entities.

**Comment by vpaul08** [comment] 2019-10-09 17:45
> Can't you do this?
> 
> ```js
> const users = await this.usersRepository.findOne(conditions, {
>       relations: ['photos'],
>       order: {
>        photos: {
>             id: "ASC"
>       },
>     });
> ```

Nope

**Comment by RossLote** [comment] 2019-12-30 17:57
@anton-bot This isn't a duplicate of #3508 
This ticket is concerned with the sorting **_OF_** embedded relations.
Ticket #3508 is concerned with sorting **_BY_** embedded relations.

**Comment by LinBoLen** [comment] 2020-02-01 05:31
currently, relation have eager and lazy.
the lazy relation property is defined as Promise type.

can typeorm support relation with `SelectQueryBuilder` type in lazy mode or give a `query` mode ?

maybe the define like following:
```
import {Entity, PrimaryGeneratedColumn, Column, ManyToMany} from "typeorm";
import {Question} from "./Question";

@Entity()
export class Category {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    name: string;
    
    @ManyToMany(type => Question, question => question.categories)
    questions: SelectQueryBuilder<Question[]>;
}
```

**Comment by nizulzaim** [comment] 2020-02-13 17:04
> currently, relation have eager and lazy.
> the lazy relation property is defined as Promise type.
> 
> can typeorm support relation with `SelectQueryBuilder` type in lazy mode or give a `query` mode ?
> 
> maybe the define like following:
> 
> ```
> import {Entity, PrimaryGeneratedColumn, Column, ManyToMany} from "typeorm";
> import {Question} from "./Question";
> 
> @Entity()
> export class Category {
>     
>     @PrimaryGeneratedColumn()
>     id: number;
>     
>     @Column()
>     name: string;
>     
>     @ManyToMany(type => Question, question => question.categories)
>     questions: SelectQueryBuilder<Question[]>;
> }
> ```

Wanted to have this feature also. Lazy relation currently cant set the order by. Problem happen when updating the record, related data will auto sort by UpdatedAt

**Comment by jtushman** [comment] 2020-05-13 15:59
Would adding a default sort order on the related table -- work or help

**Comment by ekifox** [comment] 2020-09-07 09:52
Update

**Comment by pqt** [comment] 2020-09-23 22:54
> Would adding a default sort order on the related table -- work or help

@jtushman how would I go about doing that? Is that possible?

**Comment by peresbruno** [comment] 2020-10-26 17:26
Any update about this?

**Comment by ananta** [comment] 2020-10-27 05:21
> Any update about this?

Had a similar case with my workflow, I wanted to sort with the latest created post using find options! Using the `order` option did the job for me.

  const submissions = await Submissions.find({
                where: {
                    challengeId,
                },
                order: {
                    createdAt: 'DESC',
                },
            });

You can find more at: https://typeorm.io/#/find-options

**Comment by svorcan** [comment] 2020-12-11 13:30
> Can't you do this?
> 
> ```js
> const users = await this.usersRepository.findOne(conditions, {
>       relations: ['photos'],
>       order: {
>        photos: {
>             id: "ASC"
>       },
>     });
> ```

It would be great if TypeORM would offer sorting of related entities in this way. 
Following this thread as well, since I needed this behaviour several times. :)

**Comment by nouman-mpayg** [comment] 2020-12-21 12:09
Any updates on this?

**Comment by Alan-Fisher** [comment] 2020-12-21 13:59
@nouman-mpayg @svorcan I end up using smth like this

`  const tagCategories = await this.repo.createQueryBuilder('category')
      .leftJoinAndSelect("category.tags", "tags", `tags.state != 'archive' AND tags.owner.id = ${id}`)
      .where(`category.isArchived = FALSE AND category.owner.id = ${id}`)
      .orderBy({
        'category.name': 'ASC',
        'tags.name': 'ASC'
      })
      .getMany()`

**Comment by dzcpy** [comment] 2021-01-19 03:13
You could do it with a workaround with entity hooks if the result is not too large:
```js
  @AfterLoad()
  sortAttributes() {
    if (this?.attributes?.length) {
      this.attributes.sort((a, b) => (a.weight < b.weight ? -1 : a.weight === b.weight ? 0 : 1));
    }
  }
```

**Comment by Elithsar** [comment] 2021-02-26 13:11
https://github.com/typeorm/typeorm/issues/5215#issuecomment-566253819
Based on what @alpharder proposed for filtering on multiple relations. I found out that you can also sort like this.

You will have to leave the "order" property in your repository options and use a queryBuilder in the "where" option.

```
async sortWithRelations(entityRepository) {
    // Assuming repository classname is RepoX
    let repoOptions = {
      relations: ['relationA', 'relationB'],
      where: qb => {
        // Filter if required
        qb.where('RepoX__relationA.fieldY = :val', {val: 'searchedValue'});
        // Then sort
        qb.orderBy({
          'RepoX__relationA.fieldYYY': 'DESC',
          'RepoX__relationB.fieldZZZ': 'DESC'
          // '{repositoryClassName}__{relationName}.fieldName
          //                                       [+ __{childRelations} for every child relations]
        });
      }
    };


    return await entityRepository.find(repoOptions);
  }
```

**Comment by bratanon** [comment] 2021-05-21 12:30
> You could do it with a workaround with entity hooks if the result is not too large:
> 
> ```js
>   @AfterLoad()
>   sortAttributes() {
>     if (this?.attributes?.length) {
>       this.attributes.sort((a, b) => (a.weight < b.weight ? -1 : a.weight === b.weight ? 0 : 1));
>     }
>   }
> ```

Beaware of the issue when using AfterLoad and save.
#3966

**Comment by puneetverma05** [comment] 2021-06-15 11:05
any updates?

**Comment by sandesh-bhoir** [comment] 2021-06-18 10:26
> Thank you for your suggestions. The following looks like it does the job for me too:
> 
> ```js
> return this.departmentsRepository.createQueryBuilder('departments')
>             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
>             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
>             .orderBy({
>                 'departments.name': 'ASC',
>                 'locations.name': 'ASC'
>             })
>             .getMany();
> ```
> 
> The departments and locations are ordered by name.

The pagination gets affected here, gives improper results

**Comment by Adil93** [comment] 2021-07-30 09:02
> @nouman-mpayg @svorcan I ended up using smth like this
> 
> ```
> const tagCategories = await this.repo.createQueryBuilder('category')
>       .leftJoinAndSelect("category.tags", "tags", `tags.state != 'archive' AND tags.owner.id = ${id}`)
>       .where(`category.isArchived = FALSE AND category.owner.id = ${id}`)
>       .orderBy({
>         'category.name': 'ASC',
>         'tags.name': 'ASC'
>       })
>       .getMany()
> ```

Pagination is getting affected here

**Comment by Adil93** [comment] 2021-07-30 09:21
> Thank you for your suggestions. The following looks like it does the job for me too:
> 
> ```js
> return this.departmentsRepository.createQueryBuilder('departments')
>             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
>             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
>             .orderBy({
>                 'departments.name': 'ASC',
>                 'locations.name': 'ASC'
>             })
>             .getMany();
> ```
> 
> The departments and locations are ordered by name.

This one has pagination (limit,offset) issues, Below code works for me

.orderBy({ 'locations.name': 'ASC' })
.addOrderBy(`departments.name`, 'ASC')

**Comment by sandesh-bhoir** [comment] 2021-07-30 09:27
> > Thank you for your suggestions. The following looks like it does the job for me too:
> > ```js
> > return this.departmentsRepository.createQueryBuilder('departments')
> >             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
> >             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
> >             .orderBy({
> >                 'departments.name': 'ASC',
> >                 'locations.name': 'ASC'
> >             })
> >             .getMany();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The departments and locations are ordered by name.
> 
> This one has pagination (limit,offset) issues, Below code works for me
> 
> .orderBy({ 'locations.name': 'ASC' })
> .addOrderBy(`departments.name`, 'ASC')

use skip and take instead of limit and offset when we have relations to avoid pagination issues

**Comment by Adil93** [comment] 2021-07-30 09:37
> > > Thank you for your suggestions. The following looks like it does the job for me too:
> > > ```js
> > > return this.departmentsRepository.createQueryBuilder('departments')
> > >             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
> > >             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
> > >             .orderBy({
> > >                 'departments.name': 'ASC',
> > >                 'locations.name': 'ASC'
> > >             })
> > >             .getMany();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The departments and locations are ordered by name.
> > 
> > 
> > This one has pagination (limit,offset) issues, Below code works for me
> > .orderBy({ 'locations.name': 'ASC' })
> > .addOrderBy(`departments.name`, 'ASC')
> 
> use skip and take instead of limit and offset when we have relations to avoid pagination issues

I am using skip and take itself still facing the issue

**Comment by sandesh-bhoir** [comment] 2021-07-30 09:54
> > > > Thank you for your suggestions. The following looks like it does the job for me too:
> > > > ```js
> > > > return this.departmentsRepository.createQueryBuilder('departments')
> > > >             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
> > > >             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
> > > >             .orderBy({
> > > >                 'departments.name': 'ASC',
> > > >                 'locations.name': 'ASC'
> > > >             })
> > > >             .getMany();
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The departments and locations are ordered by name.
> > > 
> > > 
> > > This one has pagination (limit,offset) issues, Below code works for me
> > > .orderBy({ 'locations.name': 'ASC' })
> > > .addOrderBy(`departments.name`, 'ASC')
> > 
> > 
> > use skip and take instead of limit and offset when we have relations to avoid pagination issues
> 
> I am using skip and take itself still facing the issue

 

> > > > Thank you for your suggestions. The following looks like it does the job for me too:
> > > > ```js
> > > > return this.departmentsRepository.createQueryBuilder('departments')
> > > >             .leftJoinAndSelect("departments.locations", "locations", "locations.deleted_at IS NULL AND locations.is_active = 1")
> > > >             .where("departments.deleted_at IS NULL AND departments.is_active = 1")
> > > >             .orderBy({
> > > >                 'departments.name': 'ASC',
> > > >                 'locations.name': 'ASC'
> > > >             })
> > > >             .getMany();
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The departments and locations are ordered by name.
> > > 
> > > 
> > > This one has pagination (limit,offset) issues, Below code works for me
> > > .orderBy({ 'locations.name': 'ASC' })
> > > .addOrderBy(`departments.name`, 'ASC')
> > 
> > 
> > use skip and take instead of limit and offset when we have relations to avoid pagination issues
> 
> I am using skip and take itself still facing the issue

Me too struggled a lot on this, order by on relation won't work as expected. If you could just try with getRawMany() instead and let me know if that worked

**Comment by Adil93** [comment] 2021-07-30 12:28
@sandesh-bhoir  I finally go with @AfterLoad listener

**Comment by wiatrM** [comment] 2021-07-31 09:12
This feature is opened for like 3 years. It is crucial for our project as we use repository-like DDD pattern, also with pagination and ordering. But we faced a problem with ordering by relation field.

TypeORM team, do you plan to add this functionality or we need to rewrite our design to support massive queryBuilder for sorting/filtering/paginating results?

**Comment by imnotjames** [comment] 2021-07-31 15:21
We're always accepting pull requests so you can make a proposal & a pull request.

**Comment by pleerock** [comment] 2021-08-04 16:52
I think it's time to implement this feature 🙌

**Comment by marcellobc** [comment] 2021-08-11 13:36
is anyone working on this? Really thinking about challenge myself on develop this feature

**Comment by felipe-augusto** [comment] 2021-08-11 22:20
@marcellobc @pleerock if you guys are interested I had to patch typeorm to make this work. Changed here:

https://github.com/typeorm/typeorm/blob/65cbcc79bceac4cf8d15dec8c558dcbc9a037220/src/find-options/FindOptionsUtils.ts#L193

Changes:

```ts
Object.keys(options.order).forEach(function (key) {
  var order = options.order[key];
  var nulls = undefined;
  
  if (!metadata.findColumnWithPropertyPath(key))
      throw new Error(key + " column was not found in the " + metadata.name + " entity.");
  
  // check if we are dealing with OrderByCondition interface
  if (order instanceof Object) {
      nulls = order.nulls;
      order = order.order;
  }

  // support ordering using numbers
  if (order === 1) {
      order = 'ASC'
  } else if (order === -1)(
      order = 'DESC'
  )

  if (order !== undefined && order !== "ASC" && order !== "DESC")
      throw new Error(`"order" can accept only "ASC" and "DESC" values.`);
  if (nulls !== undefined && nulls !== "NULLS FIRST" && nulls !== "NULLS LAST")
      throw new Error(`"nulls" can accept only "NULLS FIRST" and "NULLS LAST" values.`);

  qb.addOrderBy(qb.alias + "." + key, order, nulls);
});
```

**Comment by wiatrM** [comment] 2021-09-09 19:37
> I think it's time to implement this feature 🙌

@pleerock what is the progres in this feature? Did you manage to develop something? 
Thanks

**Comment by LinPoLen** [comment] 2021-11-03 14:54
you can try to use [`@gradii/fedaco`](https://www.npmjs.com/package/@gradii/fedaco) orm. but currently is still in wip. fullly taste of laravel eloquent

**Comment by anthowm** [comment] 2022-01-23 19:16
Any advance of this one ?

**Comment by Besmerch123** [comment] 2022-01-23 19:18
> Any advance of this one ?

I just used query builder. And run a RAW SQL.

**Comment by gfernandescs** [comment] 2022-02-08 17:33
Nothing new?

**Comment by adham-123** [comment] 2022-02-09 13:48
> Nothing new?

doesn't seem so :(

**Comment by bmccann36** [comment] 2022-02-09 14:38
is there anything wrong with [serranoarevalo](https://github.com/serranoarevalo) 's answer?
just use queryBuilder instead you can do exactly what you want

> @iljab I did something like this:
> 
> ```js
> makers = await getRepository(User)
>               .createQueryBuilder("user")
>               .innerJoinAndSelect(
>                 "user.products",
>                 "products",
>                 "products.isLaunched = :isLaunched",
>                 {
>                   isLaunched: true
>                 }
>               )
>               .orderBy("products", "DESC")
>               .getMany();
> ```
> 
> This just orders the users by the ones with more products.

**Comment by Mojy0715** [comment] 2022-02-24 17:36
> [#5215 (comment)](https://github.com/typeorm/typeorm/issues/5215#issuecomment-566253819) Based on what @alpharder proposed for filtering on multiple relations. I found out that you can also sort like this.
> 
> You will have to leave the "order" property in your repository options and use a queryBuilder in the "where" option.
> 
> ```
> async sortWithRelations(entityRepository) {
>     // Assuming repository classname is RepoX
>     let repoOptions = {
>       relations: ['relationA', 'relationB'],
>       where: qb => {
>         // Filter if required
>         qb.where('RepoX__relationA.fieldY = :val', {val: 'searchedValue'});
>         // Then sort
>         qb.orderBy({
>           'RepoX__relationA.fieldYYY': 'DESC',
>           'RepoX__relationB.fieldZZZ': 'DESC'
>           // '{repositoryClassName}__{relationName}.fieldName
>           //                                       [+ __{childRelations} for every child relations]
>         });
>       }
>     };
> 
> 
>     return await entityRepository.find(repoOptions);
>   }
> ```

@Elithsar, could you explain more about the `{repositoryClassName}__` or point me to the reference for it? I am puzzled about the double underscore.

**Comment by khiner** [comment] 2022-03-10 21:13
A big +1 here. [Sorting by number of 👍 s](https://github.com/typeorm/typeorm/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), this is currently the 6th highest voted issue, and the ones above it are mostly huge projects. Seems like a great pick for impact vs effort!

**Comment by sapabg** [comment] 2022-03-17 10:03
Bigger +1

**Comment by pleerock** [comment] 2022-03-17 10:19
Implemented in #8616 - will be merged into the master very soon.

**Comment by pleerock** [comment] 2022-03-17 16:19
Released in `0.3.0`.

**Closed by pleerock** 2022-03-17 16:19 UTC
Labels: question, comp: relations, driver: postgres, comp: find options

**Comment by khiner** [comment] 2022-03-17 17:51
I woke up to the release notification this morning and read all about it, thanks! 0.3.0 looks very exciting!

**Comment by tecorraltd** [comment] 2022-08-17 13:12
I found this did not work:

```
this.repository.find({
   //...
   order: {
       [query.sort]: query.sortDirection || 'ASC'
    },
})
```

where `query = { sort: 'entity.subentity.id', sortDirection: 'ASC' }` (sort is provided from UI and not known compile time)

However this did:

```
    const order: FindOptionsOrder<Entity> = {};
    let level = obj;
    const sortLevels = query.sort?.split('.') || [];

    for (let i = 0; i < sortLevels.length; i++) {
        const prop = sortLevels[i];
            
        if (i === sortLevels.length -1) {
            level[prop] = query.sortDirection || 'ASC';
        }
        else {
            level[prop] = {};
            level = level[prop];
        }
    }

this.repository.find({
   //...
    order,
})
```

While it works, it would be great to offer this built-in (with column validation, which is our next step).

**Comment by CarlosSLoureiro** [comment] 2022-12-23 14:15
There's a way to sort by the loaded relations count?

**Comment by Vn-ChemGio** [comment] 2024-12-17 13:11
> Bạn không thể làm điều này?
> 
> ```js
> const users = await this.usersRepository.findOne(conditions, {
>       relations: ['photos'],
>       order: {
>        photos: {
>             id: "ASC"
>       },
>     });
> ```

That working from my side
