### ISSUE TITLE
0.2.0-alpha.23 oracledb dependency + seemingly broken skip/take

### ISSUE THREAD

**Issue by vados-p7e** [typeorm/typeorm#1681] opened 2018-03-01 03:54 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0-alpha.23` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. `npm install`
2. run tests/use the db

I made the mistake of setting typeorm's version to `next` (which previously resolved to `0.2.0-alpha.21`), and when it updated for `0.2.0-alpha.23`, a project that has been using `postgres` the whole time decided to download `oracledb`, `skip` and `take` seem to be broken as well. 

It was my fault to not pin to a version in my `package.json`, but thought you should know about the `oracledb` dependency introduction (for a project that doesn't use it) as well as the `skip/take` related tests breaking.

**Comment by vados-p7e** [comment] 2018-03-01 03:59
Also one more thing -- it looks like a change to `QueryRunner.CreateTable` (it only takes one argument now?) broke my migrations in test environment. 

Migrations that were written with `queryRunner.CreateTable(...)` instead of `queryRunner.query(...)` failed. While in production/long-lasting environments this wouldn't be a problem (since old migrations before upgrade have already been run), my testing environment failed because it rebuilds the database fresh, also build failed because `tsc` fails (rightfully) dues to the changed contract.

Just wanted to alert you to this possibly common usecase

**Comment by pleerock** [comment] 2018-03-01 08:02
oracle was added to dependency accidentally, thanks to latest node that automatically save dependencies in package.json without --save flag...

Thanks for the report this is fixed in `typeorm@0.2.0-alpha.24`

> it looks like a change to QueryRunner.CreateTable

QueryRunner has been completely reworked. In typeorm@0.2.0-alpha.23 we merged changes that we did for 6 month, all changes are related to schema synchronization, drivers and query runners. Its a breaking change, we know about it, but query runners were not public ever and even were not documented. Now their APIs are developed and they will be.

btw there is a `migrations:generate` command you can use now.

> skip and take seem to be broken as well. 

can you provide more details what exactly is broken?

**Comment by vados-p7e** [comment] 2018-03-01 08:30
> btw there is a migrations:generate command you can use now.

Oh I didn't know, I'll certainly give that a try

> QueryRunner has been completely reworked. In typeorm@0.2.0-alpha.23 we merged changes that we did for 6 month, all changes are related to schema synchronization, drivers and query runners. Its a breaking change, we know about it, but query runners were not public ever and even were not documented. Now their APIs are developed and they will be.

Ahh, got it, I didn't know that -- makes sense, I had to go find the class to figure out what methods to call on it, I will be careful to avoid using the QueryRunner like that in the future (well until the `next` code is released)

> can you provide more details what exactly is broken?

Sorry I didn't actually take too much time to double-check, the symptom was that all the places where I specified how much to take were wrong (inside the test, a count that was supposed to be `6` was `10`, which is the default), a bunch of other counts were off by ~10. I think it might not have had anything to do with `typeorm`. 

I will run again with `0.2.0-alpha.24` and report back

**Comment by pleerock** [comment] 2018-03-01 09:09
> I will be careful to avoid using the QueryRunner like that in the future

now it will be better for us if you'll use it since we want to finalize this API and want to collection all user feedback as much as possible.

**Comment by pleerock** [comment] 2018-03-01 09:09
I'll close this issue, please create a new one if you'll able to reproduce issue with skip/take.

**Closed by pleerock** 2018-03-01 09:09 UTC

**Comment by vados-p7e** [comment] 2018-03-01 09:19
Ah got it -- I guess I will use it then! Thanks for the help as always
