### ISSUE TITLE
Typeorm wrong generate field name for relations field in embedded entity

### ISSUE THREAD

**Issue by dimensi** [typeorm/typeorm#3226] opened 2018-12-10 16:42 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create relations in embedded entity and look into database.
```ts
// File.ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'

@Entity()
export class File {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  path: string

  @Column()
  filename: string

  @Column()
  mimetype: string
}

// Test.ts
import { Column, Entity, JoinColumn, OneToOne, PrimaryGeneratedColumn } from 'typeorm'
import { File } from './File'

class AdditionalInfoTest {
  @OneToOne(type => File, { onDelete: 'CASCADE' })
  @JoinColumn()
  logo?: File
}

@Entity()
export class Test {
  @PrimaryGeneratedColumn()
  id: number

  @Column(type => AdditionalInfoTest)
  info: AdditionalInfoTest = new AdditionalInfoTest()
}
```

![screenshot 2018-12-10 at 19 48 04](https://user-images.githubusercontent.com/11390039/49747464-8aee8380-fcb4-11e8-9f53-a8befc6bcb3a.png)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment] 2018-12-13 08:01
it doesn't look like a duplicate of #3132 but both saying that generated name is wrong. In this particular case it should be `infoLogoId`. @dimensi can you please create a failing test for this issue, and maybe even research a fix?

**Comment by dimensi** [comment] 2018-12-13 20:08
@pleerock i create [pr](https://github.com/typeorm/typeorm/pull/3248/files) with tests for this bug. I can't research a fix, because this project too hard for my skill. 
In logs i can see wrong behaviour typeorm.
```
query: BEGIN TRANSACTION
query: INSERT INTO "user"("name") VALUES (?) -- PARAMETERS: ["User Test"]
query: COMMIT
query: BEGIN TRANSACTION
query: INSERT INTO "post"("id", "name", "authorId", "infoAuthorid") VALUES (NULL, ?, ?, NULL) -- PARAMETERS: ["Test post",1]
query: COMMIT
```

**Comment by rustamwin** [comment] 2018-12-15 10:03
see https://github.com/typeorm/typeorm/blob/dd0b37fbae5156be43e35497738ba0f7f8e29b43/src/decorator/options/ColumnEmbeddedOptions.ts#L6-L11

**Comment by rustamwin** [comment] 2018-12-15 10:05
@pleerock I see in functional tests, test `without prefix` does't exists

**Comment by imnotjames** [comment] 2020-10-04 03:43
Looks like this was fixed!

**Closed by imnotjames** 2020-10-04 03:43 UTC
Labels: bug, needs more info

**Comment by nebkat** [comment] 2020-10-26 15:53
@imnotjames from what I can tell this has not been fixed. #3226 (this), #3132 and #2254 are all related, and are probably wrongly marked as being driver dependent. Parts of pull request #3025 seem to fix it but that was originally not merged as it was related to lazy loading.

**Comment by imnotjames** [comment] 2020-10-26 15:59
Can you open a new issue on this?
