### ISSUE TITLE
QueryFailedError in case Not(In([])) is used

### ISSUE THREAD

**Issue by yorickdevries** [typeorm/typeorm#6309] opened 2020-06-25 15:21 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using mysql, when checking for `Not(In([]))` with an empty array results in an invalid query:

`
QueryFailedError: You have 
an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) ORDER BY `Course`.`id` ASC' at line 1
`

```ts 
await Course.find({
      where: {
        id: Not(In([])),
      },
      order: { id: "ASC" },
    });
 ```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by PaperPlane01** [comment] 2020-06-26 11:47
I've also encountered this problem. It's not only with MySQL and not only `Not(In([])` that fails. In fact, all `In` queries will fail if you pass an empty array there. As a workaround, you can check whether array is empty before passing it to `In`, and do not include `In` condition to your query if array is empty.

**Comment by zstiu** [comment] 2020-06-29 07:21
#6235 
same issue here.

**Comment by imnotjames** [comment] 2020-10-07 06:47
Duplicate of #2195

**Closed by imnotjames** 2020-10-07 06:47 UTC
Labels: bug, driver: mariadb, driver: mysql
