### ISSUE TITLE
How to get all of the relations of a particular user that match a certain condition?

### ISSUE THREAD

**Issue by rohanbhide** [typeorm/typeorm#4059] opened 2019-04-28 23:20 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`

Hey guys, awesome project here!

I was wondering what the best way to get the relations of an entity that match some condition.
Say our models look like this (sorry if I am missing some decorators) -
```
export class User {
  @PrimaryColumn()
  id: bigint;

  @Column()
  name: string;

}

export class Photo {
  @PrimaryGeneratedColumn()
  id: bigint;

  @Column()
  url: string;

}
 For example say we have a Many to One relation from photos to users, and we want to get all the photos of users whose url starts with some prefix, what is the best way to go about this? A simple approach would be to
```
return photoRepo.createQueryBuilder('photo')
  .where('photo.user = :user', { user })
  .andWhere('photo.url like :prefix', { prefix })
  .getMany();
```
However, this doesn't work if I pass the user entity as the param and not it's pk because it is matching on the primary key of the country. I was wondering if there was a primary-key knowledge agnostic way of doing this. I looked at the relational query builder, but that doesn't seem to let you do db filtering.

**Comment by vlapo** [comment] 2019-04-29 10:22
Hi, please provide description with simple example of your entities. thnx

**Comment by imnotjames** [comment] 2020-10-04 02:05
Without the information to replicate there's not much we can do to help.  Unfortunately, it's been about a year since this was updated so I'm gonna close it out.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Closed by imnotjames** 2020-10-04 02:05 UTC
Labels: needs more info, question
