### ISSUE TITLE
The migration runner seems to have an issue between version 0.2.29 and 0.2.33 it also persists in 0.2.34

### ISSUE THREAD

**Issue by nicolae536** [typeorm/typeorm#7734] opened 2021-06-10 13:22 UTC
## Issue Description
When having this code 

```
@Entity()
Class RealEstateComponentMaterialCode {
    @ManyToMany(() => IndustrySector, (obj) => obj.componentMaterialCodes)
    @JoinTable({ name: 'real_estate_component_material_code_industry_sector' })
    industrySectors: IndustrySector[];
}
```

and 

```
@Entity()
export class IndustrySector {
    @ManyToMany((type) => RealEstateComponentMaterialCode, (componentMaterialCodes) => componentMaterialCodes.industrySectors)
    componentMaterialCodes: RealEstateComponentMaterialCode[];
}
```

The migration generator on 0.2.29 generates no changes on the db. After update to 0.2.34 he tries to change the cascade on relations setting the relation for realEstateComponentMaterialCodeId to be ON DELETE CASCADE ON UPDATE CASCADE. But for industry sector it doesn't change it. It seems the defaults were changed ? From what I see this pr added the posibility to specify cascade on each component of the relation https://github.com/typeorm/typeorm/pull/5714/commits/7e00cccf815f7b96cfc10816bf7a74817f4329f2
### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. Add the entities using the version 0.2.29 
2. Update to 0.2.34 and generate a migration.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows       |
| Node.js version     | v16.2.0| 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by H6LS1S** [comment] 2021-06-11 18:45
duplicate https://github.com/typeorm/typeorm/issues/7714

**Comment by imnotjames** [comment] 2021-06-19 00:11
Duplicate of #7745 - very likely intended, though

**Closed by imnotjames** 2021-06-19 00:11 UTC
Labels: bug, requires triage
