### ISSUE TITLE
Issue with delete Entity that has ManyToMany relation that is also an Entity

### ISSUE THREAD

**Issue by jeffreyschultz** [typeorm/typeorm#6138] opened 2020-05-26 19:04 UTC
**Issue type:**

[ ] question
**[X] bug report**
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
**[X] `postgres`**
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

**[X] `latest`**
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am having an issue with a TypeORM generated query dealing with a ManyToMany relationship between my Documents and Groups. The issue seems to be caused by having a DocumentGroupXref entity defined and registered with TypeORM that maps to document_group_xref, which is the joining table between Document and Group.

```ts
@Entity('document_group_xref')
export class DocumentGroupXref {
  @PrimaryColumn({ name: 'document_id' })
  documentId: number;

  @PrimaryColumn({ name: 'group_id' })
  groupId: number;

  @Column({ name: 'assigned_dt' })
  assignedDate: Date;

  @ManyToOne(() => Group)
  @JoinColumn({ name: 'group_id' })
  group: Group;
}
```

However, in my Document entity, I don't use the `DocumentGroupXref` entity directly, and just reference the document_group_xref table directly in the JoinTable decorator. The reason for the `DocumentGroupXref` entity is so that I can directly manipulate the `Group`s for a specific `Document` in a nested controller under the `Document` controller using `@nestjsx/crud`.

```ts
@Entity('document')
export class Document {
  @PrimaryGeneratedColumn({ name: 'id' })
  id: number;

  @ManyToMany(() => Group)
  @JoinTable({
    name: 'document_group_xref',
    joinColumn: { name: 'document_id' },
    inverseJoinColumn: { name: 'group_id' }
  })
  groups: Group[];
}
```

When I try to delete an entire Document I get an error saying that document_groups_rid is missing from the query. Obviously, this is a quoting issue with Postgres, but the query is being generated without quotes, while the rest of the query is quoted properly. As soon as I remove DocumentGroupXref from the @Module import (NestJS), the deletion works fine and the query is generated properly with quotes.

![image](https://user-images.githubusercontent.com/479560/82939908-048a3800-9f62-11ea-96c7-480e7520820a.png)

This issue also pops up when I am updating the Document. This seems to be thrown in calling `repo.save`.

![image](https://user-images.githubusercontent.com/479560/82940238-8d08d880-9f62-11ea-93d1-46973dae0a21.png)

**Comment by jeffreyschultz** [comment] 2020-05-27 14:53
Here is a screen shot of the SelectQueryBuilder not properly quoting the select statement.

![image](https://user-images.githubusercontent.com/479560/83036189-4e2d5e00-a008-11ea-9e1c-86fb9c6ddec0.png)

**Comment by jeffreyschultz** [comment] 2020-05-27 23:18
When I remove the `DocumentGroupXref` from the module registration, and only the `Documen` entity is referencing `document_group_xref`, then it works fine. Here you can see that it generates a properly quoted query.

![image](https://user-images.githubusercontent.com/479560/83081484-ce76b200-a04e-11ea-8beb-01b8c58bff28.png)

**Comment by jeffreyschultz** [comment] 2020-05-28 02:43
It seems part of the issue is that `buildEscapedEntityColumnSelects` is looking for a `Document_groups_rid.documentId` in `this.expressionMap.selects` instead of `Document_groups_rid.document_id`? Why is it doing that?

![image](https://user-images.githubusercontent.com/479560/83092520-7ac69180-a06b-11ea-8d96-30059eb66325.png)

**Comment by jeffreyschultz** [comment] 2020-05-28 02:55
It seems that when I took advantage of the fact that TypeORM is looking for the property name in the `expressionMap.selects` and renamed the property to be the actual column name it got past that issue. I don't know if this is just going to cause other issues, but it didn't throw an exception when I was trying to update my `Document` entity.

![image](https://user-images.githubusercontent.com/479560/83093239-0a207480-a06d-11ea-986f-e011bf2fdd43.png)

**Comment by PachowStudios** [comment] 2020-06-18 20:16
Also experiencing this issue.

Very frustrating especially considering I have `persistence: false` set on the `@ManyToMany()`. Typeorm shouldn't even be trying to do a cascade delete in the first place. Maybe I should open a separate issue?

**Comment by PachowStudios** [comment] 2020-06-18 20:31
I believe this is the same issue as https://github.com/typeorm/typeorm/issues/4951

@pleerock Any word on this? This is a major issue. Basically means you can't delete an entity with a many-to-many relationship.

**Comment by imnotjames** [comment] 2020-10-10 05:05
Duplicate of #1668

**Closed** 2020-10-10 05:05 UTC
