### ISSUE TITLE
Entity can't find correct connection when using multiple connections

### ISSUE THREAD

**Issue by luizfelipelaviola** [typeorm/typeorm#7199] opened 2020-12-16 23:38 UTC
## Issue Description

I'm using 3 databases in my application: mysql (external server), pg (internal server) and mongo (internal server).
I did make the ormconfig.json file using Typeorm docs.
Each connection have his own entity file pattern, to avoid problems.
But when i give a name for each connection, the non-default mysql connection can't be used in application.
Looks like the ORM is forcing to use the default connection.

### Expected Behavior

I'm expecting each connection works with a unique name without problems.

### Actual Behavior

To avoid the problem, i found a workaround: using createConnections instead of ormconfig.json, using SQL databases without names.
Even using createConnections, if i put a name in SQL connections, the same error given in ormconfig.json happens.

```
No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?
```

### Steps to Reproduce

1. Create 3 connections: mysql, pg and mongo in ormconfig.json
2. Give a name to each connection
3. Code a entity for each connection
4. See what happens

***Database init file***
```typescript
import { createConnections } from 'typeorm';

createConnections([
  {
    name: 'default'
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'postgres',
    password: 'docker',
    database: 'card',
    entities: ['./src/modules/**/infra/typeorm/entities/*.local.ts'],
  },
  {
    name: 'gb',
    type: 'mysql',
    host: '192.168.0.141',
    port: 3306,
    username: 'root',
    password: 'XXX',
    database: 'gb',
    entities: ['./src/modules/**/infra/typeorm/entities/*.gb.ts'],
  },
  {
    name: 'mongo',
    type: 'mongodb',
    host: 'localhost',
    port: 27017,
    database: 'card',
    useUnifiedTopology: true,
    entities: ['./src/modules/**/infra/typeorm/schemas/*.mongo.ts'],
  },
]);
```

***Mysql model***
```typescript
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('adm_pessoa')
class User {
  @PrimaryGeneratedColumn({
    type: 'int',
  })
  id: number;
  ...
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 10 with WSL (Ubuntu 20.04 LTS)          |
| Node.js version     | v12.20.0 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by ErnestoBorio** [comment] 2021-04-15 02:12
Same problem here, if the `entities` parameter is not there to tell TypeORM to know what connection an entity belongs to, what is it there for?
Also, this could be added as a parameter to the `@Entity()` decorator

**Comment by imnotjames** [comment] 2021-07-09 15:01
That's exactly what it does. 

How is it that you're using the entities?  It's not clear in either comment.

Given we have tests that confirm this behavior & I'm having trouble replicating - can you create a test that confirms this bug or a repository which does so?

**Comment by luizfelipelaviola** [comment] 2021-07-09 15:13
The repository itself cannot get other connection than "default" on ormconfig.js.
That is a problem if we need to ran migrations in other connection instead of "default" connection.

WORKAROUND
In my project, i make a workaround, making the only migration-needed connection as default.
At ormconfig.json, there is only one connection, the default connection.
It works on migrations.

So, the others connections, i creating each connection manually using createConnection.

But i spend a lot of time facing this issue, a think the correct term is using ormconfig.js and the application can reach each database by the name.

The problem is: if i put all connections only in ormconfig.js, all repositories try to action on the "default" connection, instead of using the desired connection on getRepository(Entity, "notDefaultConnection");

**Comment by imnotjames** [comment] 2021-07-09 18:27
If you're calling `getRepository(Entity, "notDefaultConnection")` it pulls the connection named `notDefaultConnection` and I can confirm that here.  I am able to operate on the entities registered to that connection without an issue.

I am still unable to replicate this issue, so either a repository that exhibits the issue or a test that exhibits the issue is needed.

**Comment by imnotjames** [comment] 2021-07-31 05:58
Without a way to replicate this issue I'll be closing it out.

**Closed by imnotjames** 2021-07-31 05:58 UTC
Labels: bug, driver: mongodb, driver: mysql, driver: postgres, needs more info
