### ISSUE TITLE
Transaction support for MongoDB 4.0

### ISSUE THREAD

**Issue by chengjia0807** [typeorm/typeorm#4056] opened 2019-04-28 12:06 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Do we have any plan to support transaction for MongoDB 4.0?

**Comment by rustamwin** [comment] 2019-04-29 06:00
Duplicate of #3051

**Closed by rustamwin** 2019-04-29 06:00 UTC
