### ISSUE TITLE
Documentation of Errors

### ISSUE THREAD

**Issue by isthisnagee** [typeorm/typeorm#5538] opened 2020-02-17 06:25 UTC
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22`

I couldn't find in the documentation a list of errors that could be thrown and which methods throw them. If this does not exist I'm willing to help in writing that stuff down :)

**Comment by isthisnagee** [comment] 2020-02-17 06:27
There's also https://github.com/typeorm/typeorm/issues/5287

**Comment by isthisnagee** [comment] 2020-02-21 13:41
I spent a few minutes searching. The [error directory] seems to have all of the typeorm errors that are thrown. It seems like `QueryFailedError` is the default thrown when a query fails. Has implementing more detailed errors been considered? 


[error directory]: https://github.com/typeorm/typeorm/tree/master/src/error

**Comment by imnotjames** [comment] 2021-06-30 04:59
Duplicate of #5287

**Closed by imnotjames** 2021-06-30 04:59 UTC
Labels: documentation
