### ISSUE TITLE
Parameter name in where clause cannot contain a period (after 0.2.36 upgrade)

### ISSUE THREAD

**Issue by ebelyaev** [typeorm/typeorm#8041] opened 2021-08-05 18:01 UTC
## Issue Description

I'm not sure if this changed in 0.2.35 or 0.2.36 release, but we can no longer use periods in the parameter name in the where clause.  Previously we could do:

```
queryBuilder.where("account.hcl = :account.hcl", { accounts.hcl: 'ACCOUNT.SYSTEM' })
```
and this would work as expected.

### Expected Behavior

Previous behavior to work.

### Actual Behavior

The parameter value does not get substituted in and the query doesn't work.  Typeorm tries to run the query below against the DB:

```
select
	"accounts"."id" as "accounts_id",
	"accounts"."hcl" as "accounts_hcl",
	"accounts"."dateCreated" as "accounts_dateCreated",
	"accounts"."dateUpdated" as "accounts_dateUpdated",
	"accounts"."name" as "accounts_name",
	"accounts"."subdomain" as "accounts_subdomain",
	"accounts"."active" as "accounts_active",
	"accounts"."resync" as "accounts_resync",
	"accounts"."createdById" as "accounts_createdById",
	"accounts"."configJSON" as "accounts_configJSON",
	"accounts"."interviewScheduling" as "accounts_interviewScheduling",
	"accounts"."lockedAlgorithmVersion" as "accounts_lockedAlgorithmVersion"
from
	"accounts" "accounts"
where
	"accounts"."hcl" = :accounts.hcl
```

### Steps to Reproduce

The following does not work anymore:
```
createQueryBuilder()
    .select("user")
    .from(User, "user")
    .where("user.name = :user.name", { user.name: "Timber" })
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macos big sur      |
| Node.js version     | 14.17.4  | 
| Typescript version  | 4.3.3  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment] 2021-08-06 03:05
> Previously we could do:
> 
> queryBuilder.where("account.hcl = :account.hcl", { accounts.hcl: 'ACCOUNT.SYSTEM' })

Surprising because that's invalid JavaScript.

**Comment by imnotjames** [comment] 2021-08-06 03:06
Duplicate of #8015

**Closed by imnotjames** 2021-08-06 03:06 UTC
Labels: bug, requires triage
