### ISSUE TITLE
Filter all requests for certain entities?

### ISSUE THREAD

**Issue by florianmartens** [typeorm/typeorm#6301] opened 2020-06-24 08:15 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

There are certain cases where it would be very advantageous to be able to annotate all queries for a certain entity (or maybe all queries in the app) with certain conditions. E. g. if I use a user model and I want queries like `findOne` and `find` to not return the password and salt of a user. Or if I always want to filter for a specific tenant in my application.

As of now, I haven't seen this functionality with TypeORM. Does it exist? Was the implementation of such a feature discussed at some point?

Thanks!

**Comment by marines** [comment] 2020-06-24 10:37
```@Column({ select: false })```

**Comment by florianmartens** [comment] 2020-06-24 11:06
> `@Column({ select: false })`

Thanks. This helps - but my question was more aiming for the general functionality of annotating queries for a specific entity or the entire app. My main problem really is the tenant separation - but I thought the user model example would be a bit more tangible.

**Comment by UnsolvedCypher** [comment] 2020-06-27 17:19
Perhaps you are looking for [custom repositories](https://typeorm.io/#/custom-repository)? This would allow you to create queries that you can call directly without having to rewrite them every time, and you could specify in the query what you want or do not want to select. If this isn't what you need, could you clarify what you are asking exactly?

**Comment by florianmartens** [comment] 2020-06-27 18:20
hey, @UnsolvedCypher - custom repositories are unfortunately not the API I'm looking for. I'm looking for a API that is a little closer to the DB level. Overwriting Repository Methods leaves too many possibilities to query without checking for tenant data.

**Comment by imnotjames** [comment] 2020-10-11 10:46
This sounds closer to scopes and filters.

**Comment by imnotjames** [comment] 2020-10-11 10:47
Duplicate of #1601

**Closed by imnotjames** 2020-10-11 10:47 UTC
Labels: driver: postgres, question
