### ISSUE TITLE
Custom ORM Database driver to support other Database

### ISSUE THREAD

**Issue by ganeshkbhat** [typeorm/typeorm#7765] opened 2021-06-19 02:57 UTC
## Feature Description
Custom ORM Database driver to support other Databases (SQL or NoSQL)

### The Problem
Custom ORM Database driver to support other Databases. Especially databases that are not supported. I am working with microservices. Let me take 2 examples:

- REST API driver . Alternate example:  https://loopback.io/doc/en/lb4/Creating-crud-rest-apis.html
- Cassandra driver

### The Solution
- Allow Interface for common functions of CRUD and allow extending the ORM. 

### Considered Alternatives
https://loopback.io/doc/en/lb4/Creating-crud-rest-apis.html

### Additional Context
REST API and Custom DB Driver CRUD is a desired feature. Please consider. If this is already there please help me find the feature. I was not able to find it.

### Relevant Database Driver(s)
Not Applicable

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
I am unable to contribute at the moment. Apologies

Unsure
- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-06-19 03:57
Duplicate of https://github.com/typeorm/typeorm/issues/2479

**Closed by imnotjames** 2021-06-19 03:57 UTC
Labels: new feature, requires triage
