### ISSUE TITLE
No connection options were found in any of configurations file

### ISSUE THREAD

**Issue by krivochenko** [typeorm/typeorm#3258] opened 2018-12-15 12:57 UTC
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[*] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Add `"typeorm": "ts-node ./node_modules/typeorm/cli.js --config .env"` to `scripts` in package.json. 
2. Run `npm run typeorm -- migration:generate -n MigrationName`. On 0.2.8 it works, but on 0.2.9 it causes error: `Error: No connection options were found in any of configurations file.`

**Comment by vlapo** [comment] 2018-12-16 22:58
I think your problem is caused by this change https://github.com/typeorm/typeorm/commit/3271ce57971384cd9f076129604ecaa713db92f4#diff-dc3f0fa4dfd1d42b636f6d95a19dc19a

As workaround you can run your command without config argument. (Please let me know if it is working)

But I think this may be changed as bugfix or some change request.

**Comment by krivochenko** [comment] 2018-12-17 23:34
@vlapo what do you mean? Is it not allowed to store settings of connection in file `.env`?

**Comment by pleerock** [comment] 2018-12-18 06:53
@steevsachs can you please elaborate?

**Comment by steevsachs** [comment] 2018-12-18 12:55
Definitely. I’m traveling today but will work on this tonight or tomorrow.

**Comment by vlapo** [comment] 2018-12-19 19:37
It is allowed @krivochenko, I just saw that connection options reader is using `.env` file if exists and config path is not provided . Sry for misunderstanding.

**Comment by krivochenko** [comment] 2018-12-21 09:01
@vlapo without `config` argument it works. 

Thank you!

**Comment by pleerock** [comment] 2018-12-21 09:08
Think we can close this one.

**Closed by pleerock** 2018-12-21 09:08 UTC
Labels: comp: cli tools
