### ISSUE TITLE
Can't bind more than 65536 parameters with pg-connection by Many-To-Many-Releations

### ISSUE THREAD

**Issue by Bjo-Frei** [typeorm/typeorm#9172] opened 2022-07-04 06:26 UTC
## Issue Description

Using the postgresql database, try to insert enough lines so that there are 65536 parameters to bind.
The maximum count of bind parameters are also available in other database systems.

### Expected Behavior

No issue with large amount bind parameters, automatic split /manuell split in seperate statements.
The chunk parameter works only by a list of objects and not by the sublist of the objects.

### Actual Behavior

A exception will be thrown from the underlined driver that the amount of bind parameters are to high.

### Steps to Reproduce

From the example code generated with ```typeorm init --name project --database postgres```, update index.js:

```typescript
createConnection().then(async connection => {
    console.log("Inserting a new user into the database...");
    let users = [];
    let numUsers = (65535/3) | 0; // works (3 features per user => numUsers*3 <= 65535)
    numUsers += 1; // doesn't work anymore! More than 65535 features.
    for (let i = 0; i < numUsers; i++) {
        const user = new User();
        user.firstName = "Timber";
        user.lastName = "Saw";
        user.age = 25;
        users.push(user);
    }
    await connection.manager.save({name: "Group", users: users}, { chunk: 100});
    console.log("saved new group");

    console.log("Loading users from the database...");
    users = await connection.manager.find(Group);
    console.log("Loaded group: ", group.length);

    console.log("Here you can setup and run express/koa/any other framework.");

}).catch(error => console.log(error));
```
then start the program and see the failure.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 10 64 bit        |
| Node.js version     |  v16.15.0  | 
| Typescript version  | 4.6.4  | 
| TypeORM version    | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment] 2022-09-03 16:52
Duplicate of #7565

**Closed by AlexMesser** 2022-09-03 16:52 UTC
Labels: bug, requires triage
