### ISSUE TITLE
leftJoinAndSelect nested property returns null if all fields except primary key are null

### ISSUE THREAD

**Issue by VictorCurean** [typeorm/typeorm#7476] opened 2021-03-18 09:43 UTC
Issue type:

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] sqlite
[ ] sqljs
[ ] websql

TypeORM version:

[ ] latest
[ ] @next
[x] 0.2.31 (or put your version here)

I have a nested entity structure like follows: 

```
@Entity()
export class TeamMember {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  name: string;

  @OneToOne(() => TeamMemberContact, (contact) => contact.teamMember)
  contact: TeamMemberContact;
}
```

```
@Entity()
export class TeamMemberContact {
  @OneToOne(() => TeamMember, (teamMember) => teamMember.contact, { primary: true })
  @JoinColumn({ name: 'team_member_id' })
  teamMember: TeamMember;

  @Column({ name: 'phone_number', nullable: true })
  phoneNumber: string;

  @Column({ name: 'private_email', nullable: true })
  privateEmail: string;

  @Column({ nullable: true })
  address: string;
}
```

I'm trying to get a list of **TeamMember**, that have a one-to-one relation to a **TeamMemberContact** entity which (in some cases) has all non primary-key fields null. Im using the following query:

`getRepository(TeamMemberContact)
      .createQueryBuilder('team_member')
      .leftJoinAndSelect('team_member.contact', 'contact')
      .getMany()`
      
The problem is that when TypeOrm maps the result to a list of TeamMembers, the attribute _contact_ is not an object with _phoneNumber, privateEmai, address == null_ . It is mapped simply as a _null_. 

I have tested the generated SQL query directly in the database and it works as intended, meaning all fields are returned as null. I should also note that this ONLY happens when all non primary key fields are null, if one or more actually have a value the contact object is mapped correctly in the parent object, and contains the rest of the null value fields as well.

Is this the intended behaviour?

**Comment by imnotjames** [comment] 2021-07-12 09:15
Duplicate of #4299

**Closed by imnotjames** 2021-07-12 09:15 UTC
Labels: bug, driver: postgres
