### ISSUE TITLE
Changing column type from "text" to "longtext" deletes all data in the column

### ISSUE THREAD

**Issue by dbramwell** [typeorm/typeorm#6011] opened 2020-05-05 08:53 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (0.2.24)

Using AWS aurora serverless and using the "synchronise" functionality I created a table with a text column:

```
    @Column("text")
    text: string;
```
Then I wanted to update that column type to long text:
```
    @Column("longtext")
    text: string;
```

All data in the "text" column was lost. Is this expected? I expected it to do a `MODIFY COLUMN` and keep all data in there...

**Comment by univerze** [comment] 2020-05-07 13:42
Same here with migrations. queryRunner.changeColumn actually drops the column first and adds a new one. Expected to run mysql ALTER TABLE [table] MODIFY [column] command. Very dangerous for production data.

**Comment by imnotjames** [comment] 2020-10-14 06:30
Duplicate of #3357

**Closed by imnotjames** 2020-10-14 06:30 UTC
Labels: bug, comp: migrations, driver: mariadb, driver: mysql
