### ISSUE TITLE
A View Entity without @PrimaryColumn breaks count method in repository

### ISSUE THREAD

**Issue by Mikkal24** [typeorm/typeorm#4699] opened 2019-09-05 20:24 UTC
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a view entity that looks like this as suggested by the documentation here: https://github.com/typeorm/typeorm/blob/master/docs/view-entities.md
```ts 
@ViewEntity({
    expression: `
    SELECT ROW_NUMBER() OVER (ORDER BY created_at) AS "id", * FROM (SELECT id AS "query_id", created_at, updated_at, "userId", 'table_one' AS type FROM table_one
    UNION ALL
    SELECT   id AS "query_id",created_at, updated_at, "userId", 'table_two' AS type FROM table_two
    UNION ALL
    SELECT   id AS "query_id",created_at, updated_at, "userId", 'table_three' AS type FROM table_three
    UNION ALL
    SELECT   id AS "query_id",created_at, updated_at, "userId", 'table_four' AS type FROM table_four
    UNION ALL
    SELECT  id AS "query_id",created_at, updated_at, "userId", 'table_five' AS type FROM table_five) x
      `
  })
  export class QueryView {
    @ViewColumn()
    id: number;
  
    @ViewColumn()
    query_id: number;
  
    @ViewColumn()
    type: string;
  
    @ViewColumn()
    updated_at: Date;
  
    @ViewColumn()
    created_at: Date;
  
    @ViewColumn()
    userId: number;
  }
```

And I wanted to count the number of rows so I can paginate results like so: 

```ts
    const queryViewRepository = connection.getRepository(QueryView)
    const count = await queryViewRepository.count();
```

ended up getting this error: 
```query:
   'SELECT COUNT(DISTINCT()) as "cnt" FROM "query_view" "QueryView"',
  parameters: [] } QueryFailedError: syntax error at or near ")"
```

because `DISTINCT()` needs a value. 

I saw in the `executCountQuery` Method in the `SelectQueryBuilder` [link](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts)

That it tries to fit in a primary column. 

So I solved the issue by simply adding @PrimaryColumn to the id field of my original ViewEntity. I have PR open to add this to the docs https://github.com/typeorm/typeorm/pull/4698

But as mentioned, it should be added to the Design first.

**Comment by Mikkal24** [comment] 2019-10-23 22:22
I realize now that this is the same issue as this https://github.com/typeorm/typeorm/issues/4479

So it can be closed I think. Not sure if it's a bug though or just lack of documentation.

**Comment by imnotjames** [comment] 2020-10-08 19:52
Duplicate of #4479

**Closed by imnotjames** 2020-10-08 19:52 UTC
Labels: comp: view, documentation, driver: postgres
