### ISSUE TITLE
Ionic migration class names get replaced by "a" or 's' when using --prod

### ISSUE THREAD

**Issue by praveenraji2i** [typeorm/typeorm#2187] opened 2018-05-21 15:35 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Steps to reproduce or a small repository showing the problem:
Can't make Ionic work using the --prod flag.
Everything works perfectly when using ionic cordova run android or ionic cordova run android --release but as soon as we add the --prod flag, things start to break.

The file names are changed to 'a','s' like that.

Error: 
n migration name is wrong. Migration class name should have a UNIX timestamp appended.

**Comment by pleerock** [comment] 2018-05-22 12:09
try to disable mangling in your uglify options

**Comment by daniel-lang** [comment] 2018-05-24 08:42
duplicate of #2164

**Closed by daniel-lang** 2018-05-24 08:42 UTC
