### ISSUE TITLE
Generate DDL Files

### ISSUE THREAD

**Issue by gerwinbrunner** [typeorm/typeorm#4551] opened 2019-08-07 15:28 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there a way to generate a DDL file from the source code / or the database?
I'm not able to find anything like it.

Our goal is to generate the schema from the source code for a specific database. 
Then pass those files to our DBs for creating the schema + tables on the production db. (there is no other way for us to do it :( )

Any ideas on how this can be done?

**Comment by nvander1** [comment] 2019-08-14 14:50
Our team would also love to see this feature. We have been using a workaround by launching our application and telling TypeOrm to synchronize the database. But this is clunky for us, and would also love the ability to generate the DDLs.

@pleerock @AlexMesser @daniel-lang @rustamwin @iz-iznogood

**Comment by meltzwho** [comment] 2019-08-14 15:28
@gerwinbrunner Great idea, would love to see this added.

**Comment by ethanhoman** [comment] 2019-08-14 17:16
@gerwinbrunner Great idea. Managing schemas and entities across teams is hard, and converting entities in code to a common definition like DDL would help a lot.

@pleerock @AlexMesser

**Comment by gerwinbrunner** [comment] 2019-09-02 09:11
Is anybody looking into this? Is there a way that we could get this done?

**Comment by imnotjames** [comment] 2020-10-07 04:39
> Is anybody looking into this? Is there a way that we could get this done?

We're always accepting pull requests :)

**Comment by imnotjames** [comment] 2020-10-13 18:04
duplicate of #1316

**Closed by imnotjames** 2020-10-13 18:04 UTC
Labels: comp: cli tools, comp: migrations, enhancement, question
