### ISSUE TITLE
generate migration on unchanged column every time

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3561] opened 2019-02-02 09:15 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
// user.entity.ts

  @Column({
    default: () => 'CURRENT_TIMESTAMP',
  })
  lastChangedAt: Date;
```

```ts
// 1549098402796-Init.ts

export class Init1549098402796 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `lastChangedAt` `lastChangedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `lastChangedAt` `lastChangedAt` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP");
    }

}
```

```sql
-- database dump DDL

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isEnabled` tinyint(4) NOT NULL DEFAULT '1',
  `lastChangedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_78a916df40e02a9deb1c4b75ed` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by pleerock** [comment] 2019-02-03 18:17
More details and investigations are always welcomed from your side! ;)

**Comment by vlapo** [comment] 2019-02-07 21:24
This is our general problem with migrations right now. We have old or wrong definitions for default precisions/lengths/... of DB data types and our checks for identify changes are false positive.

I think we have to figure out how to proper test this functionality and fix this problem globally for all drivers and data types.

Workaround for this specific issue is define precision:
```typescript
@Column({
    default: () => 'CURRENT_TIMESTAMP',
    precision: 0
})
lastChangedAt: Date;
```
or use `UpdateDateColumn` created for this purpose:
```typescript
@UpdateDateColumn()
lastChangedAt2: Date;
```

**Comment by Kononnable** [comment] 2019-02-09 22:52
I think this is a duplicate of #2737. PR with fix already made, but it will be merged to next since it's breaking support for older mysql versions.

**Comment by Diluka** [comment] 2019-02-11 02:18
Additional, mysql will auto translate `NOW()` into `CURRENT_TIMESTAMP`.

**Closed** 2021-04-01 13:19 UTC
Labels: bug, comp: migrations, driver: mariadb, driver: mysql
