### ISSUE TITLE
using enumName with synchronize: true leads to re-creation of columns and indices

### ISSUE THREAD

**Issue by egorovli** [typeorm/typeorm#5421] opened 2020-01-26 19:14 UTC
#### Issue type:
[x] bug report (I guess?)

#### Database system/driver:
[x] `postgres`

#### TypeORM version:
[x] `latest`

#### Steps to reproduce or a small repository showing the problem:
Consider the following entity:

```ts
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, Index } from 'typeorm'

enum ContractType {
  COMMISSION = 'commission',
  SALE = 'sale',
  BUYOUT = 'buyout'
}

@Entity()
export class Contract extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string

  @Index()
  @Column('enum', {
    enum: ContractType,
    enumName: 'contract_type'
  })
  type: ContractType

  // ...
}
```

Running a `NestJS` application with debug logs yields the following:

```bash
$ DEBUG=typeorm:* yarn start:dev
  ...
  typeorm:schema columns changed in "contracts". updating: type +13ms
  typeorm:query:log DROP INDEX "contracts_idx_type"; +4ms
  typeorm:query:log ALTER TABLE "contracts" DROP COLUMN "type"; +2ms
  typeorm:query:log SELECT "n"."nspname", "t"."typname" FROM "pg_type" "t" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "t"."typnamespace" WHERE "n"."nspname" = current_schema() AND "t"."typname" = 'contract_type'; +3ms
  typeorm:query:log ALTER TABLE "contracts" ADD "type" "contract_type" NOT NULL; +2ms
  ...
  typeorm:schema adding new indices "contracts_idx_type" in table "contracts" +7ms
  typeorm:query:log CREATE INDEX "contracts_idx_type" ON "contracts" ("type") ; +7ms
  ...
```

And it happens for all entities with enums with custom `enumName` property. If this property is removed, and the type name becomes something like `contract_type_enum`, the columns and indices do not get re-created.

I've `console.log`'ed inside of [`node_modules/typeorm` here](https://github.com/typeorm/typeorm/blob/231dadfb0ac7098501e5d1097e5c197048004727/src/schema-builder/RdbmsSchemaBuilder.ts#L531), and the difference of new and old columns specs looks like this (with differences highlighted):

![image](https://user-images.githubusercontent.com/5165202/73140366-25f91700-4089-11ea-822f-f00f0d05063e.png)

**Comment by imnotjames** [comment] 2020-10-15 06:41
Duplicate of #5000

**Closed by imnotjames** 2020-10-15 06:41 UTC
Labels: comp: schema sync, driver: postgres
