### ISSUE TITLE
Entity ids are all overridden by the latest inserted id when using queryBuilder.insert to save multiples items

### ISSUE THREAD

**Issue by lucashfreitas** [typeorm/typeorm#4682] opened 2019-09-03 01:24 UTC
**Issue type:**
[x] bug report
**Database system/driver:**
[x] `mysql` / `mariadb`
**TypeORM version:**
[x] `latest`

Sorry in advance if this is duplicated, but I did not find any open issue regarding that.

If we save multiples items using `queryBuilder.insert()` method, all the items will have the id overridden by latest id item inserted. Let's suppose you are inserting three Cats in the database, they will have the id 1, 2 and 3 respectively. 

After queryBuilder.insert(),  all of three entities id will be overridden with the latest insertedId, so all entity items will have the id 3. 

I am not sure if this behavior is normal, but I got my self to struggle to understand why my entities id were all the same and after debugging, I found out that is because of queryBuilder insert method.

Lets supose that we have a CatEntity. We want to insert three cats, so we have: 

`catsItems: Cats[] = [
{
name: 'Cat1'
},
{
name:'Cat2'
},
{
name: 'Cat3'
}
]`

`const catRepository = connection.getRepository(Cat);`

Now, lets save the cats: 

    `await catRepository
            .createQueryBuilder('cat')
            .insert()
            .values(catsItems)
            .execute();`

After we execute this statement, a single and latest insertedId will be populated for both Cats, so typeorm will return the following entities from insert statement: 

`[{id:3,name:'Cat1',id:3,name:'Cat2'}. {id:3,name:'Cat3']`

Note that even if we insert multiples items, the query runner returns only a **single latest id**  `insertResult.raw = await queryRunner.query(sql, parameters);`, which will be used later on 
ReturningResultsEntityUpdator.insert to replace all entities ids. 

![image](https://user-images.githubusercontent.com/11416392/64136689-9b005180-ce47-11e9-88fa-dc53adc04679.png)

In the database Cat1 was inserted with id  1 and Cat2 was inserted with id 2, ..... But query runner seems to return all entities with the latest inserted id., then ReturningResultsEntityUpdator.insert method will change all entities id to the latest one. 

The **line 113 of ReturningResultsEntityUpdator** is responsible to set entity id to the latest inserted id: 

`  this.queryRunner.manager.merge(metadata.target as any, entity, generatedMap); // todo: this should not be here, but problem with below line`.

**Summary:**

If you insert an array of items using queryBuilder.Insert, after that, all of them will have the same id, which will be the latest **insertedId**.

I would be more than happy to provide more information/create a repository to reproduce or open a pull request if this behavior is not normal.

Thanks in advance!

**Comment by mollyalger** [comment] 2019-09-09 18:59
I believe this is the same as https://github.com/typeorm/typeorm/issues/2131

**Comment by Kononnable** [comment] 2019-10-16 07:51
Duplicate of #4682

**Closed by Kononnable** 2019-10-16 07:51 UTC
