### ISSUE TITLE
Calculate (multiply, plus, minus, ...) in select statement in QueryBuilder?

### ISSUE THREAD

**Issue by MeMeMax** [typeorm/typeorm#5024] opened 2019-11-02 10:55 UTC
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to calculate in select statements with column names?

I tried it with this line: .addSelect('brokerStockData.purchaseAmount*brokerStockData.purchaseAmount', 'test')

But there is not property "test" in the data property.

```
const [data, amount] = await this.brokerStockDataRepo
      .createQueryBuilder('brokerStockData')
      .leftJoinAndMapOne('brokerStockData.symbol', StockData, 'stockData', 'brokerStockData.symbol = stockData.symbol')
      .innerJoin('brokerStockData.broker', 'broker')
      .innerJoin('broker.user', 'user')
      .innerJoin('brokerStockData.webApiConfig', 'webApiConfig')
      .select('brokerStockData.id')
      .addSelect('brokerStockData.addDate')
      .addSelect('brokerStockData.modifyDate')
      .addSelect('brokerStockData.name')
      .addSelect('brokerStockData.symbol')
      .addSelect('brokerStockData.purchasePrice')
      .addSelect('brokerStockData.purchaseAmount')
      .addSelect('brokerStockData.purchaseAmount*brokerStockData.purchaseAmount', 'test')
      .addSelect('brokerStockData.purchaseDate')
      .addSelect('webApiConfig.id')
      .addSelect('webApiConfig.name')
      .addSelect('stockData.date')
      .addSelect('stockData.close')
      .addSelect('stockData.symbol')
      .addSelect('stockData.webApiConfigId')
      .where('user.id = :userId', { userId })
      .andWhere('broker.id = :brokerId', { brokerId })
      .andWhere(qb => {
        const subQuery = qb
          .subQuery()
          .select('MAX(stockData.date)')
          .from(StockData, 'stockData')
          .getQuery();
        return 'stockData.date = ' + subQuery;
      })
      .take(queryParams.pageSize)
      .skip(queryParams.pageSize * queryParams.pageIndex)
      .orderBy(queryParams.active, queryParams.direction)
      .getManyAndCount();
```

Anyone has an idea how this may work?

**Comment by imnotjames** [comment] 2020-10-17 05:29
You'll need to use `getRawMany` here

**Comment by imnotjames** [comment] 2020-10-17 05:30
If you want it to end up in the model itself then this is a duplicate of #296

**Closed by imnotjames** 2020-10-17 05:30 UTC
Labels: comp: query builder, driver: mariadb, driver: mysql, question
