### ISSUE TITLE
Repository cannot be found when using existing connection

### ISSUE THREAD

**Issue by bwermes** [typeorm/typeorm#5587] opened 2020-02-28 22:53 UTC
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm encountering an issue where a getRepository(<repo name>) call is providing the repository after the SQL connection is initially made. However, after a subsequent call to the database, where I'm reusing the existing connection, the repository is not found.

Response: 
```
{
    "error": "No repository for \"Store\" was found. Looks like this entity is not registered in current \"default\" connection?"
}
```

Here is a screen shot of the initial call followed by a second call a moment later. The function being triggered in both calls is the same.
![typeorm-repo-not-found](https://user-images.githubusercontent.com/22311634/75593294-c3a18680-5a39-11ea-9a9f-fbb6025aec35.png)

[StorePack.zip](https://github.com/typeorm/typeorm/files/4269451/StorePack.zip)

**Comment by millsmcilroy** [comment] 2020-03-01 13:06
Related to this issue https://github.com/typeorm/typeorm/issues/3427? If you're using sls-offline, invoke it with `--skipCacheInvalidation`.

**Comment by rmolinamir** [comment] 2020-03-02 21:36
@millsmcilroy thanks for the response. I'm not sure if it might be related to that. I was using a singleton for my connections in order to never lose it. I had no problems w/ `0.2.22` but after updating to `0.2.24` I started having issues w/ this. There's another open issue regarding this same problem, #5592.

**Comment by pleerock** [comment] 2020-03-03 10:02
can you please provide a reproduction repo?

**Comment by jukra** [comment] 2020-03-03 13:25
Same thing happening here, and I also verified that it is due to this change https://github.com/typeorm/typeorm/commit/e3be9e34e00768af3304b238389fb80ce13bb567.

With serverless offline using  `--skipCacheInvalidation` kind of solves the issue, but with that you are not able to hot reload any changes. What I have done for now as temp fix is to disable the connection reusing with serverless offline as I don't mind it creating new connections when developing locally.

**Comment by phong-innomizetech** [comment] 2020-03-06 11:03
Look at my commented at #5592

**Comment by didac-wh** [comment] 2020-03-12 13:35
Fails for me too. Worked in 0.2.22, stopped working in 0.2.23 and 0.2.24.

**Comment by imnotjames** [comment] 2020-10-02 16:41
I think this is the same as #5676 - given there's more discussion happening there I'm going to close this as a duplicate of #5676

If you believe that's not the case - let me know and ideally provide a way to replicate this behavior.

**Closed by imnotjames** 2020-10-02 16:41 UTC

**Comment by filipw01** [comment] 2020-12-09 08:37
Please note, that in new version of serverless-offline `--skipCacheInvalidation` does not exist use  `--allowCache` instead
