### ISSUE TITLE
Error: Entity metadata was not found

### ISSUE THREAD

**Issue by zxr90** [typeorm/typeorm#420] opened 2017-04-23 11:06 UTC
```Typescript
// conversation_pairs.ts

@Entity()
export class ConversationPairs {

  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(type => Users, user_id => user_id.conversation_pairs, {
    cascadeRemove: true,
    nullable: false
  })
  user_id: Users;

  @ManyToOne(type => Agents, agent_id => agent_id.conversation_pairs, {
    cascadeRemove: true,
    nullable: false
  })
  agent_id: Agents;
}

// user.ts

@Entity()
export class Users {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => ConversationPairs, conversation_pairs => conversation_pairs.user_id)
  conversation_pairs: ConversationPairs[];
}

// agent.ts

@Entity()
export class Agents {

  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => ConversationPairs, conversation_pairs => conversation_pairs.agent_id)
  conversation_pairs: ConversationPairs[];
}

```

I have these 3 files and getting this error when I start my app.
```
Error: Entity metadata for ConversationPairs#user_id was not found.
    at /Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:272:27
    at Array.forEach (native)
    at /Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:269:38
    at Array.forEach (native)
    at EntityMetadataBuilder.build (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:268:25)
    at EntityMetadataBuilder.buildFromMetadataArgsStorage (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:152:21)
    at Connection.buildMetadatas (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/connection/Connection.js:552:18)
    at Connection.<anonymous> (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/connection/Connection.js:174:30)
    at step (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/Users/xuanrong/Sites/calllevels/dbs-chat/node_modules/typeorm/connection/Connection.js:13:53)
```

Not sure what to do, need some help on this.

**Comment by tomkroening** [comment] 2017-04-29 19:38
I ran into the same issue.

TypeORM is very difficult to debug with args and meta data classes/collections all over the place. After many hours I was able to figure it out.

So this relationship is failing because EntityMetadataBuilder.ts is trying to tie the type of the ManyToOne column with a known entity type using "===".

` var inverseEntityMetadata = entityMetadatas.find(function (m) { return m.target === relation.type || (typeof relation.type === "string" && m.targetName === relation.type); });`

Looking at relation.type I could see that it is the same "type" as m.target however they were not pointing to the same reference of the defined type. It seemed to me as if my related class was being loaded by node more than once. After reading about [how node caches modules](https://nodejs.org/api/modules.html) I was able to fix my problem by making sure all of my import statements were referencing the same file including uppercase/lowercase letters in the string.

In one file I had

`import { Category } from "./models/category";`

and the other I had

` import { Category } from "./Category";`

Notice the uppercase "C". After replacing with a lowercase "c" everything worked as expected.

**Comment by pleerock** [comment] 2017-05-02 19:07
@zxr90 you should not have this error. Most probably something is wrong on your side. Please provide a minimal reproduction git repo for this issue, so I can debug.

**Comment by NoNameProvided** [comment] 2017-06-08 20:33
I can confirm @tomkroening solution. Importing the same Entity from a different path will cause the following error: 

```
Error: Entity metadata for Category#users was not found. Check if you specified a correct entity object, check its really entity and its connected in the connection options.
```

This error is somewhat misleading as it suggests that you haven't imported your entities. While that can be a valid reason for this, the other can be above mentioned import path issue pointed out by  @tomkroening. 

How solve this error most effectively? You can do the following steps:

First lets understand from where the error is coming from. TypeORM says that it cannot find the `Category#users` relation. So the problem is with the `User` entity in this case. `Category` was found successfully but TypeORM was not able to find the related `User` entity.

So what you have to search for is the `import { User` code snippet, and check if all the import paths point to the same location. 

Ok so now we can ask what is exactly a same location? Two path is exactly the same if they point to the same location when resolved by the filesystem.

A few example:

Lets assume we have the following tree structure:

```
 src
├─ services
│   └── folderx
│      └── foldery
│         └── xy.service.ts
└─ entities
│   ├── index.ts
│   └─ user.entity.ts
└─ xy.ts

```
Where `index.ts` re-export `user.entity.ts` (aka it's a barell file.)

Then importing `user.entity.ts` from `xy.service.ts` as `../../../entities` is resolved as the same as importing the `user.entity.ts` from `xy.ts` as `./entities`, while importing it as `./entities/user.entity` would not resolve as the same because it's points to `./entities/user.entity.ts` file instead of `./entities/index.ts` file.

**Comment by pleerock** [comment] 2017-06-17 07:56
Conclusion: this error happening when you have misspelled your entity name, misspelled import paths or did not include your entity in connection configuration.

**Closed by pleerock** 2017-06-17 07:56 UTC

**Comment by j-slvr** [comment] 2017-09-08 13:59
@tomkroening thank you so much for this! i would have never guessed this.

**Comment by michaelonubogugauge** [comment] 2017-09-20 14:24
@NoNameProvided Thank you so much. Your thorough explanation helped me to resolve my issue. For me, it was basically changing an import reference from:

`import {Entity} from './'  \\via index.ts` 

to

`import {Entity} from './Entity'`

Basically setting an explicit reference to the entity. Thanks again.

**Comment by amitport** [comment] 2018-03-27 10:33
for future reference:

I got this error when my typescript was configured to compile files in-folder (e.g., `src/entity.ts` to `src/entity.js`)

**Comment by ADongre1** [comment] 2018-03-28 15:29
@amitport 
Did you ever resolve your issue? I am transpiling to js so I can use in iisnode. I am getting the same issue you are experiencing.

**Comment by amitport** [comment] 2018-03-28 16:30
@ADongre1, not a real resolution -- I just configured typescript to not generate js in the same folder.

**Comment by ADongre1** [comment] 2018-03-28 18:51
Hmm, I have it transpiling to build folder, but still the same issue.

**Comment by pleerock** [comment] 2018-03-28 20:44
you simply need to point a proper paths to js files

**Comment by Razzwan** [comment] 2018-05-30 20:56
I have the same problem, but my conclusins is different:

I have such structure for my two entities:
```ts
import { Entity, ManyToMany, JoinTable } from 'typeorm';
import { Role } from '../role';

@Entity()
export class User {
  @ManyToMany(type => Role, role => role.users)
  @JoinTable({ name: 'user_roles' })
  roles: Role[];
}
```
```ts
import { ManyToMany } from 'typeorm';
import { User } from '../user/user.entity';

@Entity()
export class Role {
  @ManyToMany(type => User, user => user.roles)
  users: User[];
}
```
This two entites does not work together, but if I remove any of relation from Role (`role.users`) or from User (`user.roles`) entity - all works correctly. Perhaps, something wrong not only with filesistem paths, but also with circular dependecies

**Comment by ADongre1** [comment] 2018-05-30 22:23
I ended up putting the main app.js file at the root with the config file and it worked for me.

**Comment by koffmoff** [comment] 2018-06-29 09:31
For the record, I experienced the same problem. Went through all imports to ensure they were correct. Problem remained. Turned out it was because I used `ts-node` to launch the app. Worked fine after a `tsc` build and normal `node` start.

**Comment by jackswiggett** [comment] 2018-07-19 00:44
I had the same issue. I was importing and re-exporting all my entities in `src/entity/index.ts`, e.g.

```javascript
// src/entity/index.ts
export { Task } from './Task';
export { Unit } from './Unit';
export { User } from './User';
```

and then importing them from that index file to reference them in other entities, e.g.

```javascript
// src/entity/User.ts
import {
  Task,
  Unit,
} from '.';
```

Rather than changing my import references like @michaelonubogugauge suggested, I just changed my ormconfig file from

`entities: [ 'src/entity/**/*.ts' ]`

to

`entities: [ 'src/entity/index.ts' ]`

which solved the problem for me.

**Comment by blacksourcez** [comment] 2018-08-06 18:46
In this case, I solved by change the `ormconfig.json` content

```json
.
.
  "entities": [
     "dist/entity/**/*.ts"
  ],
```

to

```json
.
.
  "entities": [
     "dist/entity/**/*.js"
  ],
```

**Comment by anztrax** [comment] 2018-08-27 16:49
or you had wrong entity when get repository

for examples : 
right one :
```
class TemplateAccessor{
  static getRepo(){
    return getConnection().getRepository(Template);
  }
}
```

wrong one : 
```
class TemplateAccessor{
  static getRepo(){
    return getConnection().getRepository(TemplateGroup);
  }
}
```

**Comment by jtushman** [comment] 2018-08-30 13:53
@blacksourcez that worked for me too.  But it feels like the wrong solution.  I'd like to know why it doesn't work with the ts files.  (are they looking fore the js or map files right next to the ts -- my tsc is putting compiled files to a dist folder)

**Comment by NSExceptional** [comment] 2018-10-23 17:07
I get this error for a specific class when I add a static function to it. Can't figure out why.

**Comment by NSExceptional** [comment] 2018-10-30 19:19
I figured it out. Circular references between entities break types passed directly to decorators. This is why TypeORM uses futures (`type => MyClass`)

**Comment by havenchyk** [comment] 2018-11-21 12:10
@PapsOu could you please open another issue and provide a minimal example repo to reproduce the problem? It will help, might be your problem is not exactly the same as topic starter had

**Comment by AhmadDeel** [comment] 2019-01-05 08:31
> @ADongre1, not a real resolution -- I just configured typescript to not generate js in the same folder.

How ?

**Comment by AhmadDeel** [comment] 2019-01-05 08:54
> I had the same issue. I was importing and re-exporting all my entities in `src/entity/index.ts`, e.g.
> 
> ```js
> // src/entity/index.ts
> export { Task } from './Task';
> export { Unit } from './Unit';
> export { User } from './User';
> ```
> 
> and then importing them from that index file to reference them in other entities, e.g.
> 
> ```js
> // src/entity/User.ts
> import {
>   Task,
>   Unit,
> } from '.';
> ```
> 
> Rather than changing my import references like @michaelonubogugauge suggested, I just changed my ormconfig file from
> 
> `entities: [ 'src/entity/**/*.ts' ]`
> 
> to
> 
> `entities: [ 'src/entity/index.ts' ]`
> 
> which solved the problem for me.

thanks a lot.
I exported all my entities from database.entites.ts file and edited ormconfig.json as follows
`"entities": [
      "src/database.entities.ts"
   ],`

**Comment by geabenitez** [comment] 2019-02-26 02:47
Hello For me it was to forget to add the () at the end of @Entity()

**Comment by rpires** [comment] 2019-03-06 22:13
I had this one bugging me for a while, a bit like @geabenitez I had forgot the **@entity()** annotation.

**Comment by geabenitez** [comment] 2019-03-06 22:21
> I had this one bugging me for a while, a bit like @geabenitez I had forgot the **@entity()** annotation.

Most likely you're newbie like me. Once you get used to it, it becomes easier.

**Comment by asselstine** [comment] 2019-04-09 17:46
@tomkroening Thanks for the tip, you fixed our build.

We had some imports as:

```javascript
import { UserEntity } from '../users/UserEntity'
```

or

```javascript
// this will load from the index file
import { UserEntity } from '../users'
```

But once we made *all* of the imports consistent TypeORM started playing nice again.

**Comment by Kaperskyguru** [comment] 2019-07-25 12:56
> In this case, I solved by change the `ormconfig.json` content
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.ts"
>   ],
> ```
> 
> to
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.js"
>   ],
> ```

This solves my problem, Changing TS to JS

**Comment by MarzaLwm** [comment] 2019-08-02 16:43
> In this case, I solved by change the `ormconfig.json` content
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.ts"
>   ],
> ```
> 
> to
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.js"
>   ],
> ```

Thanks! thats was works for me.

**Comment by DigaoParceiro** [comment] 2019-08-05 12:09
to me I forgot to add @Entity("myEntityName") in my class

**Comment by sachinhf** [comment] 2019-08-10 12:36
It works for me when I change **["_dirname + /..//*.entity.ts"]** to **[ "_dirname + /..//*.entity.js"]** now it works with **npm run start:dev**

**Comment by bel7aG** [comment] 2019-11-30 02:32
../anyFolder/AnyFileEndingWith .entity.ts
sometimes **./** is important

 entities: [__dirname + '../**/*.entity.ts'], 

to

entities: [__dirname + '**./**../**/*.entity.ts'],

**Comment by kvalium** [comment] 2020-01-07 13:27
I stick to this error again and again on projects losing so much time looking for typos or paths that not exactly match from one file to another... plus the fact that the error message provides poor information, that's quite BS...

**Comment by rustamwin** [comment] 2020-01-07 13:47
@kvalium see https://github.com/typeorm/typeorm/issues/420#issuecomment-515032082

**Comment by JZLeung** [comment] 2020-01-28 12:32
> In this case, I solved by change the `ormconfig.json` content
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.ts"
>   ],
> ```
> 
> to
> 
> ```json
> .
> .
>   "entities": [
>      "dist/entity/**/*.js"
>   ],
> ```

thx.

**Comment by renjithspace** [comment] 2020-02-03 05:20
> Conclusion: this error happening when you have misspelled your entity name, misspelled import paths or did not include your entity in connection configuration.

@pleerock  Thanks! 👍

**Comment by jboucly** [comment] 2020-02-05 10:57
> Hello For me it was to forget to add the () at the end of @entity()

Thanks !!!!!!!

**Comment by brense** [comment] 2020-02-12 16:14
> I had the same issue. I was importing and re-exporting all my entities in `src/entity/index.ts`, e.g.
> 
> ```js
> // src/entity/index.ts
> export { Task } from './Task';
> export { Unit } from './Unit';
> export { User } from './User';
> ```
> 
> and then importing them from that index file to reference them in other entities, e.g.
> 
> ```js
> // src/entity/User.ts
> import {
>   Task,
>   Unit,
> } from '.';
> ```
> 
> Rather than changing my import references like @michaelonubogugauge suggested, I just changed my ormconfig file from
> 
> `entities: [ 'src/entity/**/*.ts' ]`
> 
> to
> 
> `entities: [ 'src/entity/index.ts' ]`
> 
> which solved the problem for me.

This guy deserves a medal

**Comment by awHamer** [comment] 2020-03-13 14:58
Ran into the same issue, try to keep all your imports to be consistent and import from the same file as mentioned above.

**Comment by awHamer** [comment] 2020-03-13 15:17
I importing models from entities/index.ts file like:
`import {Entity} from './index'` 

so In my case I fixed this issue simply to change  ormconfig.ts 
from:
```
  entities: [
        'src/entities/*.ts',
    ],
```

to 
```
  entities: [
        'src/entities/index.ts',
    ],
```

**Comment by masakiando** [comment] 2020-03-29 02:05
`entities: [__dirname + '/../**/*.entity.{js,ts}'],`

**Comment by jrmatos** [comment] 2020-03-29 19:26
My problem was actually with VSCode auto import. It was wrongly importing  using the absolute paths instead of relative ones. I updated this configuration on:

VScode File>Preferences>Settings>User Settings

"typescript.preferences.importModuleSpecifier": "relative"

**Comment by ngocketit** [comment] 2020-04-09 11:18
If you're using NestJS, you may have forgotten to add the entity to the `TypeOrmModule.forFeature()`

**Comment by ovichowdhury** [comment] 2020-04-16 10:38
I also got that same error when i accidentally forgot to decorate the entity class with @Entity() decorator.

**Comment by shellac85** [comment] 2020-04-27 12:30
I am getting this error now. The code runs fine. But when I tried to merge with a testing branch, a lot of test fails saying 'Error: Entity metadata for Customer#nominations was not found. Check if you specified a correct entity object and if it's connected in the connection options.'

Anyone got any suggestions. The Import paths all seem fine.

**Comment by shellac85** [comment] 2020-04-27 13:02
The only thing I can think of is that a few days ago I mispelled nomination when creating the entity. When I changed the spelling to the correct version, there were 2 tables in the db, the correct spelling and the wrong spelling. I deleted the wrong one manually from the db? Could this be it?

**Comment by ChenxiiCheng** [comment] 2020-04-30 19:14
> `entities: [__dirname + '/../**/*.entity.{js,ts}'],`

Thanks! This works for me.

**Comment by dutch3883** [comment] 2020-05-01 19:32
I got error when using relation in Entity like `@ManyToOne` `@OneToMany`.
solved by import entity class directly from `entity_name.ts` file not from index or other place.

**Comment by jeanRandria** [comment] 2020-05-02 20:36
Sometimes, you just need to delete dist folder and to retry.
  
- Ctrl+C  
-Yes
-npm run start:dev

:)

**Comment by tmpires** [comment] 2020-05-12 18:25
Hey, I am having a similar issue with IISNODE. The application runs fine via terminal through node comand. But on IISNODE it returns `(node:6232) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (C:\api\node_modules\typeorm\error\RepositoryNotFoundError.js:11:28)`
I use eslint and prettier, that checks file paths for me, but either way, I checked just to be sure, and they are all correct. Does anyone have any insight on what it could be?

**Comment by zachgoll** [comment] 2020-06-15 16:18
As @ngocketit mentioned, this may be unrelated to your entity file or files altogether.  In my case, I have all of my entities in a single file (to avoid circular dependency issues with nx and NestJs), but this problem still happens if I am not importing the entities to the correct feature module.

For example, if you have the following two entities: 

```typescript
@Entity('products')
export class ProductEntity {
  @PrimaryGeneratedColumn()
  public readonly id: number;

  @OneToMany(
     type => OrderEntity,
     order => order.product
  )
  @JoinColumn()
  orders: OrderEntity[]
}

@Entity('orders')
export class OrderEntity {
  @PrimaryGeneratedColumn()
  public readonly id: number;

  @ManyToOne(
     type => ProductEntity,
     product => product.orders
  )
  @JoinColumn()
  product: ProductEntity
}
```

And in your feature module, your import looks like this: 

```typescript
imports: [TypeOrmModule.forFeature([ProductEntity])]
```

Even if you do not use `OrderEntity` explicitly within this feature module, you need to import it for the relationships to resolve correctly: 

```typescript
imports: [TypeOrmModule.forFeature([ProductEntity, OrderEntity])]
```

**Comment by bluerid** [comment] 2020-06-23 18:34
@zachgoll In-fact I was forgetting to create a new module to add the entity to `forFeature` while I was trying to use my entity as a `ManyToMany` relation `joinTable`. When I created a new module and provided the entity to `TypeOrmModule.forFeature([])` it started working again. So everyone should focus on the second line of error if it's not a common problem with import statements or `@entity` decorator.

**Comment by bennyn** [comment] 2020-08-06 19:33
I got the following error:

> Error: Entity metadata for AccountEntity#owner was not found. Check if you specified a correct entity object and if it's connected in the connection options.

And I was very convinced that my setup was correct:

**AccountEntity.ts**

```ts
// ...
@ManyToOne(() => OwnerEntity, owner => owner.accounts, {onDelete: 'CASCADE'})
owner!: OwnerEntity;
// ...
```

**OwnerEntity.ts**

```ts
// ...
@OneToMany(() => AccountEntity, account => account.owner)
accounts!: AccountEntity[];
// ...
```

**initDatabase.ts**

```ts
Object.assign(connectionOptions, {
  entities: [
    AccountEntity,
    OwnerEntity
  ],
  logging: false,
  migrations: [],
  subscribers: [],
  synchronize: true,
});
```

After half an hour of debugging (luckily not hours!) I noticed that I was missing the `@Entity()` annotation in my `OwnerEntity` class. 🙈 So be smarter than me and don't make the same mistake. 😄

**Comment by DadiAnas** [comment] 2020-08-24 00:51
I had same problem, and to solve it I just removed some old folders from ./dist folder.
I was using './src/product' as folder and then I changed it to './src/products', but the folder 'product' in ./dist was cached so it caused this problem.

**Comment by sourisengupta** [comment] 2020-10-21 19:08
In my case I forgot to add the entity to my typeorm.config.ts file.
After adding that in the entities it ran perfectly.

**Comment by drnic** [comment] 2020-10-25 23:41
My version of this issue was I had typed `Entity()` rather than `@Entity()`.

Alas neither `ts-node` nor vs code decided this was a syntax error (`"typescript": "3.3.3333"` currently hardcoded by `typeorm init`)

**Comment by fkirc** [comment] 2020-11-03 12:07
In my case, this error was triggered by WebPack's `TerserPlugin` (JavaScript-minification).
I extended the following blog to make this stuff work with `create-react-app`: https://www.telerik.com/blogs/using-webassembly-with-react, using the following create-react override config:

```JavaScript
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require("path");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const webpack = require("webpack");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const CopyPlugin = require("copy-webpack-plugin");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const getClientEnvironment = require("./config/env");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const paths = require("./config/paths");

module.exports = function override(config, env) {
  /**
   * Add WASM support
   */
  // Make file-loader ignore WASM files
  const wasmExtensionRegExp = /\.wasm$/;
  config.resolve.extensions.push(".wasm");
  config.module.rules.forEach((rule) => {
    (rule.oneOf || []).forEach((oneOf) => {
      if (oneOf.loader && oneOf.loader.indexOf("file-loader") >= 0) {
        oneOf.exclude.push(wasmExtensionRegExp);
      }
    });
  });

  // Add a dedicated loader for WASM
  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, "src"),
    use: [{ loader: require.resolve("wasm-loader"), options: {} }],
  });

  const mangleOptions =
    config.optimization?.minimizer[0]?.options?.terserOptions?.mangle;
  if (!mangleOptions) {
    console.log("Did not find mangle options of TerserPlugin");
  } else {
    const reservedArray = mangleOptions.reserved ?? [];
    reservedArray.push(
      ...[
        "Initial1588635951915",
        "MyEntity1",
        "MyEntity2",
        "MyEntity3",
      ]
    );
    mangleOptions.reserved = reservedArray;
    console.log(
      "Configured reservedArray for TerserPlugin",
      mangleOptions.reserved
    );
  }
  const plugins = config.plugins;
  if (!Array.isArray(plugins) || !plugins.length) {
    throw Error("Did not find plugins");
  }
  const clientEnv = getClientEnvironment(paths.publicUrlOrPath.slice(0, -1));
  if (clientEnv.platforms.isBrowser) {
    // Provide sql.js (wasm version) for TypeORM if not building for mobile
    plugins.push(
      new webpack.ProvidePlugin({
        "window.initSqlJs": "sql.js",
        "window.SQL": "sql.js/dist/sql-wasm.js",
      })
    );
    // Copy wasm file to the output dir
    plugins.push(
      new CopyPlugin([
        { from: "node_modules/sql.js/dist/sql-wasm.wasm", to: "static/js/" },
      ])
    );
    // replace typeorm with typeorm browser implementation
    plugins.push(
      new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
        result.request = result.request.replace(/typeorm/, "typeorm/browser");
      })
    );
  }
  return config;
};
```

**Comment by dozieogbo** [comment] 2020-11-22 17:24
For me, this issue happened because I forgot to add `@Entity` at the top of my class 🤦‍♂️ so don't forget to check if your issue is the same.

**Comment by akashlama1998** [comment] 2020-11-27 09:39
In [NestJS](https://docs.nestjs.com/) adding `.js` along side `.ts` worked for me

`typeorm.config.ts`

Before

```
import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export const TypeORMConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  synchronize: true,
  entities: [__dirname + '/../**/*.entity.ts'],
  migrationsTableName: 'Migrations_History',
};
```

After

```

import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export const TypeORMConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  synchronize: true,
  entities: [__dirname + '/../**/*.entity{.ts,.js}'],
  migrationsTableName: 'Migrations_History',
};
```

**Comment by alinenko** [comment] 2021-01-05 08:18
The issue for me was in `webpack.config` and was only reproducible in production. Setting `optimization.minimize: false` (`true` by default for `production`) solved it

**Comment by in-live-md** [comment] 2021-01-08 07:06
For me it was: rm -fr dist

**Comment by RV8V** [comment] 2021-01-21 14:55
that was a problem in entity name

**Comment by bot101** [comment] 2021-01-29 14:33
If you are using TypeORM with NestJS, do not forget to add the @Entity() decorator. Failure to do so will also trigger this error.

**Comment by flyingonionman** [comment] 2021-03-10 01:55
I removed my dist and fixed the issue... HOWEVER, I must say this solution is very unsatisfying as the original "Entity metadata not found" could be caused by multiple things and it cannot be easily deduced to "some caching error" as many of you have said.

I wish I knew what the "caching error" was and acted accordingly.

**Comment by ninjarogue** [comment] 2021-05-28 06:16
I had this same issue, and it took me almost one full day to solve. I had forgotten to add the "@Entity()" Decorator.
I finally added the missing decorator and executed `tsc -p tsconfig.build.json` on the command line, and problem solved.

`import { Invoice } from '../invoice/invoice.entity';
import { Entity, Column, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';

@Entity() // I simply forgot to add the Entity decorator
export class Item {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Invoice, (invoice) => invoice.id)
  invoiceId: Invoice;

  @Column({ type: 'varchar', length: 50 })
  name: string;
}`

**Comment by erald14** [comment] 2021-07-12 08:08
Can anyone explain why entities have to be uppercase?

**Comment by imnotjames** [comment] 2021-07-12 08:59
> Can anyone explain why entities have to be uppercase?

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
