### ISSUE TITLE
Old related entities are not deleted automatically when the primary entity is saved with the changed data

### ISSUE THREAD

**Issue by DevelAx** [typeorm/typeorm#3809] opened 2019-03-12 11:42 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
`0.2.13` and `0.2.15-rc.2`

**Steps to reproduce or a small repository showing the problem:**

**_Step 1:_**
Create entities and run migration.

```TS
@Entity()
export class Category {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    nextCategoryId: number;

    @OneToMany(type => CategoryTemplate, template => template.category, { cascade: true })
    templates: CategoryTemplate[];
}

@Entity()
export class CategoryTemplate  {
    @PrimaryGeneratedColumn()
    id: number;

    @RelationId((categoryTemplate: CategoryTemplate) => categoryTemplate.category)
    categoryId: number;

    @Column()
    name: string;

    @Column()
    value: string;

    @ManyToOne(type => Category,
        category => category.templates,
        { onDelete: 'CASCADE', onUpdate: 'CASCADE', nullable: false }
    )
    category: Category;
}
```

**_Step 2:_**
Create any category with one or more templates and save it.
```TS
let category = new Category();
category = { ...category, templates: [{ name: "AAA", value: "111" }] };
categoryRepository.save(category);
```

**_Step 3:_**
Change templates in category and save it again with the same `category.id`.
```TS
category = { ...category, templates: [{ name: "BBB", value: "222" }] };
categoryRepository.save(category);
```

**_Expected behaviour:_**
The existing rows (created in step 2) in the `category_template` table will be deleted and new one(s) will be added (in step 3) with data: `{ name "BBB", value "222"}`.

**_Actual behaviour:_**
An error occurs: 
```
query failed: UPDATE `category_template` SET `categoryId` = ? WHERE `id` = ? -- PARAMETERS: [null,1]
error: { Error: ER_BAD_NULL_ERROR: Column 'categoryId' cannot be null
```
----------------------
If you set `nullable = true` there won't be any error but the old records won't be deleted anyway: they will stay in DB with `categoryId = null` which is quite unxpected anyway (what logic could be behind it to keep these unrelated records?).

This issue was already raised here #2121, but has been closed for some reason.

**Comment by vlapo** [comment] 2019-03-12 15:26
Duplicate of https://github.com/typeorm/typeorm/issues/1351

**Comment by chadgarlandscg** [comment] 2019-03-17 23:01
This also seems to be happening to me with typeorm 0.2.8 using postgres.

**Comment by Kononnable** [comment] 2019-03-19 21:18
Since it's a duplicate let's close that issue and keep discussion in one thread.

**Closed by Kononnable** 2019-03-19 21:18 UTC
Labels: duplicate
