### ISSUE TITLE
Method save does not return the entire model

### ISSUE THREAD

**Issue by grin0c** [typeorm/typeorm#3490] opened 2019-01-23 06:20 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.8] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
class Post {
  @PrimaryGeneratedColumn()
  id: number

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date

  @Column({ type: 'varchar' })
  title: string

  @Column({ type: 'text' })
  description: string
}

const connection = await createConnection(connectionOptions)
const repository = connection.getRepository(Post)

const p = await repository.save(repository.create({ title: 'D' }))
console.log(p)
#----------------------------------------
Post {
  title: 'D',
  id: 1,
  updatedAt: 2019-01-23T06:07:18.769Z,
  createdAt: 2019-01-23T06:07:18.769Z }
#----------------------------------------

const p1 = await repository.save(repository.create({ id: p.id, title: 'F' }))
console.log(p1)
#----------------------------------------
Post { id: 1, title: 'F', updatedAt: 2019-01-23T06:07:18.800Z }
#----------------------------------------
```

Using the PUT method, a part of the model comes to us. The save method accepts `DeepPartial<Entity>`, but in this case it does not return the entire model.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment] 2019-01-23 16:23
its not supposed to return entire model. It returns same model + adds properties that were generated by database (used by database's `DEFAULT`). If you need entire model you need to query model again.

**Comment by grin0c** [comment] 2019-01-23 16:34
The save method makes the find method to get the model and if we make another find request, we get suboptimal work with the data.

**Comment by pleerock** [comment] 2019-01-23 16:56
save method does a find but does it for a different purpose. What you are requesting isn't by design of `save` method.

**Comment by grin0c** [comment] 2019-01-23 17:17
Do you think this is the right behavior? To make an update to a record, you need to run the select query twice?

**Comment by pleerock** [comment] 2019-01-23 19:06
forget about that query, its internally used query, you should't care about that. Tomorrow orm can change its behaviour and do not execute that query, or maybe execute that query, but select only specific properties.

**Comment by grin0c** [comment] 2019-01-24 07:31
You're wrong. It bothers me, I have to understand how a particular function works. You can add an additional 'returning' option to SaveOptoins. This option will match the QueryBuilder returning method.

**Comment by pleerock** [comment] 2019-01-25 08:03
> Tomorrow orm can change its behaviour and do not execute that query, or maybe execute that query, but select only specific properties.

this is what I actually was planning to do, so in this case original query won't be same and it will break your "returning flag".

I don't see a perspective to continue this discussion, since I provided all answers above ^

**Comment by grin0c** [comment] 2019-01-25 08:12
One question. Why did you decide to return only part of the data? Is it best practice? Which I don't know about it.

**Comment by pleerock** [comment] 2019-01-25 08:22
Its a specifics of `UpdateDateColumn` decorator, since its generated by database user needs this value to understand what data was generated. If you don't like this behaviour - don't use this decorator - use regular column and customize behaviour how you need.

**Comment by grin0c** [comment] 2019-01-25 08:40
If `UpdateDateColumn` is removed, the behavior will not change. Did you ever explain why part of the data came back? For example: http://docs.sequelizejs.com, after updating the model returns the full model.

**Comment by pleerock** [comment] 2019-01-25 14:09
TypeORM differs from sequelizejs a lot, so there is no point to compare them.

> If UpdateDateColumn is removed, the behavior will not change.

then wha it returned if there is no such column?

**Comment by Veetaha** [comment] 2019-04-16 20:26
@pleerock Stumbled with this issue too. Why would you define non-partial entity type as a return type for `Repository.save()` if you cannot guarantee that it will return the entire entity data? And what is the point in returning a different set of entity's properties without even documenting the cases? This behavior is counter-intuitive and contradicts `TypeScript`s typing which I think must be considered a bug. So can I ask you to fix the inconsistency between `TypeScript` return type annotation and runtime behavior by returning the whole anticipated entity or changing the return type to be `Partial<>`?.

And as I've noticed the problem arises only when you run `save()` method for an existing entity (in database), so that the `UPDATE` query is run and you get the property decorated with `CreateDateColumn` missing.

**Comment by Ericnr** [comment] 2019-09-04 06:54
Read the entire issue and it is still unclear the reason why the entire entity isn't returned when it could return everything. Feels like a major inconvenience.

**Comment by ejose19** [comment] 2019-12-17 16:16
@pleerock Also another use case for this (may be implementing .returning() to .save()) is when you have a trigger that modifies the values, so the data is different in the DB and in the entity.

**Comment by ELI7VH** [comment] 2020-01-16 02:33
upon saving or updating, an orm should return the new updated object. This is how it works in Rails and Django, it should have the same behavior here.

**Comment by andremoniz** [comment] 2020-02-11 10:16
I am using reload() after save() but I would prefer it would work without the need to reload

**Comment by ejose19** [comment] 2020-02-11 15:38
> I am using reload() after save() but I would prefer it would work without the need to reload

Yes that works too, but if you're inside a transaction, transactionalEntityManager doesn't have .reload() method, so you either do a find again or do something like this

```ts
await txEM
  .getRepository(User)
  .createQueryBuilder()
  .insert()
  .values(user)
  .returning('*')
  .execute();
```

@pleerock what we would like is a save option (doesn't even need to be the default) that does insert returning * to avoid doing 2 separate queries.

**Comment by ejose19** [comment] 2020-02-11 21:44
I've made a PR to support this on #5505

now to reload all columns one need to call like this

```ts
await user.save({ updateAllColumns: true });
```

or if running inside a transaction
```ts
await txEM.save(user, { updateAllColumns: true });
```

works on both insert / update reusing the existing RETURNING logic for drivers that support it (so all is done in a single operation)

Reviews are welcome

**Comment by pleerock** [comment] 2020-02-13 09:23
@Veetaha I just saw how much attention your comment got and I would like to provide answer on that.

Since your comment is mostly about type validity, I'll try to explain what I think about it.

Talking about **correct** types is always hard with TypeScript because type system in TypeScript is dynamic and complex and its not always easy to keep a good balance between correct types (what we want), debugging issues (what we have when we complicate types) and easy of usage (what we have when different types mismatch and we are not always have what we expect). I always try to keep a good balance because nobody wants a complexity and at the same time everyone want a correct typing and easy of usage.

Now, let's try to understand why `save` accepts `Partial` but returns full object in type:

1. We cannot return `same Partial`, because we add new properties that have generated values in the database. If we won't return generated values, we won't be able to know what is generated created date for example. Returning default values is a handy feature

2. We cannot return full object (as defined in a type), because I think people won't be happy with additional query executed after save (if we return full object we might need to always execute a separate query for that (for some databases we already do, for some not, depend on database capabilities). We had many people who didn't like this behaviour, that's why we had to add `"reload: false"` option to `SaveOptions`.

3. Theoretically we can return given partial + { inferred properties with "default" defined in entity schema }, but this is complex scenario and many aspects of the current design should be re-thinked including having decorators as primary way of defining a schema (decorators limit us a lot in terms of proper typing)

So, what I can suggest is:

* we keep going as it is if people don't want to have extra query after each save
* we return back a full object if people are okay with extra query
* if somebody can suggest something else, please suggest :)

**Comment by ejose19** [comment] 2020-02-13 10:46
My vote is for n2 (but as an option, so it can be enabled/disabled at will)
> we return back a full object if people are okay with extra query

Better for save method to do it than doing the extra query manually (either by find or queryBuilder). Also for drivers like PostgreSQL, there won't be 2 separate queries so in general it's better performance wise.

**Comment by Veetaha** [comment] 2020-02-13 12:19
@pleerock, thank you for the response! I didn't use `typeorm` lately, though I did like its API very much, I am very grateful for the efforts you put into open-source! I know how hard it is to make compromises when working with contributors and users who always think they know better... But I hope the following will make sense to you.

I may not remember the details, but I do remember that my main concern was about `TypeScript` typing inconsistency. `Repository.save()` claims to return the full entity type, though it doesn't guarantee that at runtime. I do understand that you'd like to avoid additional (maybe unexpected) queries to the database and I agree on that with you! If this is the expected behavior, I just want to make sure that we as users are aware of it at type-level (sorry, I am very passionate about static typing...)

Let me try to propose the following (mostly `TypeScript` typing proposals):

* In order to make the return type of `Repository.save()` sound we need to explicitly make it more general, specifically `Partial<TEntity>` (`TEntity` is covariant to `Partial<TEntity>`), that is a set of types that covers all the possible values returned from `Repository.save()` at runtime. We are not sure which properties will be present, that's why declaring **all** the properties optional (even ones that we always know will be returned) will remove static typing inconsistency. By moving to `Partial<TEntity>` we will ensure that the users check the presence of properties. Or they just do non-null assertions, this way they kinda explicitly sign the contract that "I am as a developer know better!". Otherwise (having runtime value that doesn't satisfy the static type, i.e. `undefined` where the value is declared as non-nullable) the contract becomes implicit and the type-system doesn't work as intended ...
* I suppose after adding `reload: true` you do fetch the entire entity from the database. To simplify typing this, we can just split this to two functions `save(): Promise<Partial<TEntity>>`, and `saveAndReload(): Promise<TEntity>`.

**Comment by pleerock** [comment] 2020-02-17 10:24
IMO `save` returning partial can confuse users even more. 

### `problem #1`

Right now `save` actually mutates the original object and I think it feels weird that in runtime you send the object and you know that object will be changed and you get instance of the same object back, but in compile time you have a different type. So it looks like the most logical is to have same type what you passed, maybe with additional properties in. But we can't type additional properties easily (columns with "primary" and "default").

**suggested solution**: `save` must return a new instance (it shouldn't mutate original object) and type it as T. It will make code consistent (you pass an object, you don't get same object with different type) and it fixes multiple user requests about changing `save` method to return new immutable object.

**alternative solution**: much more complex, require more investigations, but I think is possible if we: deprecate schema definition in decorators, make schema definition in regular typed typescript  object (e.g. current `EntitySchema`), this way we can use power of types and type inference and determine what entity properties are defined as `primary` and with `default` at type-level and use this power to type save to `Repository<Schema extends EntitySchema<Entity> { ... save<T extends Schema["Entity"]>(entity: T): T & PrimaryPropertiesOf<Schema> & DefaultPropertiesOf<Schema> }`. This solution looks cool but I prefer previous one if we go for changes.

### `problem #2`

If we think `problem #1` isn't a problem and still go with returning `Partial<Entity>` it still confuses users, imagine such code:

```ts
const category = new Category()
category.name = "Hello"
const savedCategory = repository.save(category)
if (savedCategory.name) {
    console.log(savedCategory.name)
}
if (savedCategory.order) {
    console.log(savedCategory.order)
}
```

In my opinion `if (savedCategory.name)` check looks stupid, because I certainly know its in there, why do I need to add extra runtime-enabled code? I'm sure most of the users will keep using `category!.name` approach.

### `problem #3`

Suggested solution asks me to show another type inconsistency. Right now we define entity as:

```ts
@Entity()
class Album {
  @PrimaryColumn()
  id: number
  @Column()
  name: string
  @ManyToMany(...)
  photos: Photo[]
```

Now, when we load album with `findOne(id)` it gives us `Album` type. Which isn't right because we actually don't have a `photos` in it.

In `strict` mode we'll have to either put "!" to each property, either put "?" to each property =) 

If we put "!" it means types aren't 100% correct when we load them using `find` operator (because we suppose we won't load all relations, and even if we do there is a problem that they can be cyclic).
If we put "?" I think it will have a more proper typing, because we have a "select" and "relations" property in find conditions that return different results. Now imagine how many useless if statements you'll have in your code (or most probably how many "!" you'll have).

So, if we agree that putting "?" is a right approach, there is no point in returning `Partial` for `save`, since all properties are already "?"-ed. It means we don't have a problem described in your comment. If you go right from the root, you have everything right at this end too. But again, question is, are you really ready to go with all properties "?"-ed? Personally, I don't like this experience (at least until TypeScript won't improve it more).

If we decide to use "!" instead of "?", then **solution** to this problem is to return type based on the passed `FindOptions`. Something I plan to experiment and improve when I'll have a time for it.

------

Again, typing is hard to get it 100% right. I'm a big fun of strong typing too. But I don't really like the situation when tool is too annoying about things that you won't expect (even if they are right to do) and compromises user experience too much. Also, it's super hard for users to understand all those compiler errors for complex types.

Right now I suggest to do following: `save` must return a new instance (it shouldn't mutate original object) and type it as T. Since change is too much breaking, we can only afford to make it against `next` branch in 0.3.0 version of TypeORM. @ejose19 if you are interested in making these changes please let me know in your PR.

@Veetaha thanks for feedback, you don't have to read and understand everything I wrote, since you aren't using TypeORM and I suppose I didn't provide explanation deep enough (I spent an hour to formulate what I wanted to say).

**Comment by Veetaha** [comment] 2020-02-17 21:50
@pleerock wow, thanks for a good investigation on the topic!

Just want to emphasize that rule-of-thumb is that its better to overlook with `if`s or explicit non-null assertions (i.e. postfix `!`, saying that "I as a developer" know that some properties **must** be there) than underlook and get `Cannot read property X of undefined` where the type is declared as non-nullable.

Also, I wish TypeScript and ECMAScript in general, had better support for decorators. As a side note, if such a need appears, there actually is a way to restrict the type and/or name of a property or method the decorator can be applied to (played with it [here](https://github.com/Veetaha/ts-typedefs/blob/a933280d29e64097eef148694b38d55badc7427b/test/types/decorators.test.ts#L69-L74)), but the support for this is not full enough...

So yeah, using schemas via object literals would be the ideal option (from type system perspective), 'cause it gives you more type info, but I think decorators are quite a nice syntax and are one of the distinguishing features of typeorm, or maybe it's just the expression I have after using it.

**Comment by aj-ee** [comment] 2020-04-02 19:57
> its not supposed to return entire model. It returns same model + adds properties that were generated by database (used by database's `DEFAULT`). If you need entire model you need to query model again.

>All schema update and write operations are performed using master server. All simple queries performed by find methods or select query builder are using a random slave instance.

These two statements are problematic.

We are using read replicas.  If I do a save, followed by a findOneOrFail, the new data may not have propagated to the read replica by the time I'm trying to find the inserted row.

**Comment by yorickdevries** [comment] 2020-06-24 19:29
I solved this by overloading the save method like this in a Base model:

`async save(options?: SaveOptions): Promise<this> {
    await super.save(options);
    await this.save();
    await this.reload();
    return this;
  }`

**Comment by imnotjames** [comment] 2020-10-05 06:05
This has been more or less answered a few times throughout the thread.

**Closed** 2020-10-05 06:04 UTC
Labels: question

**Comment by cantoute** [comment] 2020-11-19 03:50
it's the "more or less" that makes the difference... I just spent my time reading threw all this for at the end still no clear answer on how to get method save to return the entire model. Wasn't it the original question ?

**Comment by ranjan-purbey** [comment] 2020-12-31 17:08
> it's the "more or less" that makes the difference... After reading all this it's still not clear to me of how to get method save to return the entire model. Wasn't it the original question ?

I think this answers the how part: https://github.com/typeorm/typeorm/issues/3490#issuecomment-584696428
You can use `reload()` after calling `save()`

**Comment by janmauler** [comment] 2021-01-09 13:47
This is absurd. I mean, thanks for all the great work on this library, but doing multiple redundant queries (where one query would be sufficient) only because your ORM doesn't give a shit about your database load is just wrong.

**Comment by rohan-luthra** [comment] 2021-05-01 14:33
I solved this by using Object.assign() method - 
```
const user = await this.userRepository.findOne(id);
// handle user not found
const updatedUser = await this.userRepository.save({ id, ...updateDto });
return Object.assign(user, updatedUser);
```

**Comment by imnotjames** [comment] 2021-07-06 06:15
> This is absurd. I mean, thanks for all the great work on this library, but doing multiple redundant queries (where one query would be sufficient) only because your ORM doesn't give a shit about your database load is just wrong.

Except the only way to actually get the model back after a save for sure is to load from the database in >50% of cases.

This is because we allow for database-side generation.

Thus, the only way to return the entire model back correctly would be to do a hit against the database to fetch it - or to use `RETURNING` which not every database supports.

**Comment by justmavi** [comment] 2022-01-06 12:40
I stumbled too.
2022 now, still not support...

Alternatively, you can use query builder:

`
const updateResult = await connection.getRepository()
  .createQueryBuilder()
  .update(Post)
  .set({...})
  .where(...)
  .returning('*')
  .execute();

const updatedPost = updateResult.raw[0] as Post;
`

But it's probably clear that the option is so-so. I hope they will really add a flag to SaveOptions for "returning *" soon...

**Comment by conoremclaughlin** [comment] 2022-03-01 02:46
> > This is absurd. I mean, thanks for all the great work on this library, but doing multiple redundant queries (where one query would be sufficient) only because your ORM doesn't give a shit about your database load is just wrong.
> 
> Except the only way to actually get the model back after a save for sure is to load from the database in >50% of cases.
> 
> This is because we allow for database-side column data generation.
> 
> Thus, the only way to return the entire model back correctly would be to do a hit against the database to fetch it - or to use `RETURNING` which not every database supports.

Per the comment on read replicas, hitting the database to fetch it may still return inconsistent results depending on what slave replica you hit. Why not have `returning` for those databases that support it and for those that don't throw an exception if the database driver doesn't support it. Postgres is the go-to for small projects and starting tech companies now so it would cater to the majority. If others want the functionality, they can implement it themselves. I just got burned by this issue since the types never communicate we may not get the full object back on save, and likely every upvote we see here ran into a similar head-scratching moment.

**Comment by nicu-chiciuc** [comment] 2022-05-17 11:59
Would it make sens to at least change the return type of the `.save()` function? Otherwise the interface is misleading.

**Comment by conoremclaughlin** [comment] 2022-05-17 13:39
> Would it make sens to at least change the return type of the `.save()` function? Otherwise the interface is misleading.

It’s also strange given the extra calls .save does in total. It’s already doing findOne, and the db could return the full result even with an update call.

**Comment by cmcnicholas** [comment] 2022-07-02 21:15
3+ years later, the typing for this is still bizarre and I've wasted about 3 hours today trying to figure out why as the documentation on this particular "feature" of `save` is really subpar.

It 100% should be reloading by default, this behaviour is the standard in almost every ORM I've used, the point of an ORM is ease of use and abstraction, performance is a secondary concern that you end up having to work towards anyway. The point is also moot, some of the supported databases already return the data in an optimal way and thus have no overhead.

![image](https://user-images.githubusercontent.com/41394833/177016320-caa80fa1-5382-47fd-bec4-caea673e567b.png)

**Comment by Scalahansolo** [comment] 2022-07-22 19:31
To pile on here, this is still a major issue for TypeORM. I understand that it can't work for all supported DBs, but this should be a config setting at the very least for those that can. Having to remember to use `.returning('*')` everywhere that you need the returned values is absolutely insane. On top of that issue, it's not available to be used at all when not using the `queryBuilder`, which for all basic queries means we have to write more verbose / less readable code to get some functionality that would be assumed for those using the supported DBs.

**Comment by Sebastp** [comment] 2022-08-16 23:01
I've been working with this lib for a month and you have no idea how much I regret choosing it over others

**Comment by arlangalvez** [comment] 2022-08-22 21:04
I hace some issue related! can someone give an understandable explanation? because nothing of this make sense. I'm trying to save an entity but only gives me ok with a weird object,
`{
        "_bitField": 17825792,
        "_fulfillmentHandler0": {}
    }`
 also the `.returning('*')` does not work for mysql.

Any help appreciated!

**Comment by Ginden** [comment] 2022-08-23 12:38
>  only gives me ok with a weird object,

It's Bluebird promise probably. Try `await`ing it.

**Comment by judocode** [comment] 2022-11-03 13:50
@pleerock Can we get an update on this?

My take is that this is an expected behavior for ORMs. I've never worked with an ORM where you save the record and get a partial model back, of which not all fields are correctly representative of their database counterpart. The only way to produce expected, bug-free code is to manually query the record after the save.

For my particular scenario that I'm having issues with, I'm attempting to optionally allow an ID to be passed for idempotent seeds. `@PrimaryGeneratedColumn()` doesn't respect the ID that is passed and if you use `@PrimaryColumn()`, no ID is returned at all, so reload won't even work. (This could potentially be a separate issue, not sure)

I understand it potentially being difficult, or there are considerations for different DBs, but due to my experience with many ORMs in the past, this is expected behavior. I am happy to help out in any way. I attempted to dig into the save code but got a bit lost, so I'm unsure of where this actually occurs.

**Comment by robkuz** [comment] 2023-03-30 15:06
Just started working with TypeORM and I do like the API sofar.
However this behaviour is truely bizarr. 
I just wasted 3 hours to find out that `return *` is not supported. At least there should be a big fat warning on the documentation.

My problem is that the primary column is generated on the DB level (as it should). So I cant even do a `reload` after an insert as I dont have the ID yet.

**Comment by Sebastp** [comment] 2023-04-05 07:35
> Just started working with TypeORM and I do like the API sofar.

@robkuz lmk if you still like it in a week

**Comment by arminhupka** [comment] 2023-06-15 19:57
@Sebastp i hate it after few hours. I prefer mongoose :v

**Comment by Lamarcke** [comment] 2023-06-16 00:54
My 2 cents on this:
TypeORM is not wrong to consider the performance implications of such a feature. For example, if you have 2-3 relations, and you set those entities as cascade in your DB, the save method would also need to re-fetch and update those 2-3 entities.

However, i do think this should be documented. Maybe make use of `Partial<>` or even `Omit<>` if Typescript allows.

People should also keep in mind that the Typescript stuff ends right after the compile phase, and you should never fully trust any type in any non-compiled language (like JS and Python).

**Comment by Sebastp** [comment] 2023-08-10 20:11
> 

try prisma

**Comment by Sebastp** [comment] 2023-08-10 20:11
@arminhupka try prisma

**Comment by depyronick** [comment] 2024-02-07 20:46
what if slave is behind master in a replicated environment...

**Comment by NenadJovicic** [comment] 2024-03-20 21:16
after reading this whole thread, looks like i will switch to some other library for working with DB
I worked with Hibernate and Spring, and I wanted to switch my project to NestJS and TypeORM, and now, after finding this issue, I think I will have to try another library.
I just copy/pasted most of the logic from Spring and Hibernate to NestJS and TypeORM, and now I see most of the things are not working, because ORM is behaving totally differently than others

**Comment by Lamarcke** [comment] 2024-03-20 21:51
> after reading this whole thread, looks like i will switch to some other library for working with DB
> I worked with Hibernate and Spring, and I wanted to switch my project to NestJS and TypeORM, and now, after finding this issue, I think I will have to try another library.
> I just copy/pasted most of the logic from Spring and Hibernate to NestJS and TypeORM, and now I see most of the things are not working, because ORM is behaving totally differently than others 

I personally thing you should not copy-paste logic from other languages and frameworks, but rather try to understand what's happenning under the hood of whay you are currently using.

**Comment by NenadJovicic** [comment] 2024-03-20 22:28
> > after reading this whole thread, looks like i will switch to some other library for working with DB
> > I worked with Hibernate and Spring, and I wanted to switch my project to NestJS and TypeORM, and now, after finding this issue, I think I will have to try another library.
> > I just copy/pasted most of the logic from Spring and Hibernate to NestJS and TypeORM, and now I see most of the things are not working, because ORM is behaving totally differently than others
> 
> I personally thing you should not copy-paste logic from other languages and frameworks, but rather try to understand what's happenning under the hood of whay you are currently using.

Well, I am working with JS for years now, but mostly MongoDB, where I used mongoose. And there also, when you save something, you get full object back. Someone mention `sequelize` library that is also doing the same. Hibernate, same.
So, it is TypeORM that is doing something differently.
And it is not mentioned anywhere in docs as multiple people on this issue pointed that it is returning only partial object. And people are facing this same issue for years (5 years since this issue is opened) and nothing was done to change it. And that is totally fine, it is open source project that owner can develop however he wants, but it is also my choice to switch to other library that offers same/similar behavior that is implemented in other libraries I am familiar with.

**Comment by pccw-avillamor** [comment] 2024-12-13 06:28
This is crazy. I thought the update rendered our data to become nullified. I cannot believe its 2024 and this ORM still does it. why did NestJS recommend this library at all is beyond me. Someone who decided to make this a default response must have 0 idea how the world works
