### ISSUE TITLE
Get number of rows updated

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#1662] opened 2018-02-27 20:32 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When using the various `update` functions on manager / repository, is it possible to get the # of rows updated back from the database?

**Comment by tonyxiao** [comment] 2018-03-01 04:34
Looking at next branch, seems that this will be address there! https://github.com/typeorm/typeorm/pull/1157/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR35

**Comment by pleerock** [comment] 2018-03-01 08:06
yes thats why we have UpdateResult, however currently it does not have such information. I'll left this issue to the community since its easy to implement (but need to implement for all drivers). Feel free to contribute.

**Comment by pleerock** [comment] 2018-03-29 09:02
Closing as duplicate of #1308

**Closed by pleerock** 2018-03-29 09:02 UTC
Labels: accepting PRs, community, help wanted
