### ISSUE TITLE
sqlite: typeorm migration:generate

### ISSUE THREAD

**Issue by cjackson234** [typeorm/typeorm#2393] opened 2018-06-23 20:42 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Running `typeorm migration:generate -n PostRefactoring` just hangs. Is there specific documentation for using generate in sqlite?

**Comment by pleerock** [comment] 2018-06-24 04:46
it should not hang. can you please provide some reproduction so I can closely take a look why it hangs?

**Comment by cjackson234** [comment] 2018-06-25 03:55
I'll work on a repo that shows it.

In the meantime, is there a verbose mode for migrations so I can see what it's attempting to do?

**Comment by cjackson234** [comment] 2018-06-25 04:16
In testing it looks like it's having trouble connecting to the database. The sqlite file is NOT in a relative path  to the application structure. 

For instance, "C:\Test\db.sqlite" wont connect. 

ormconfig:
`{
  "type": "sqlite",
  "synchronize": false,
  "logging": false,
  "database": "C:\Test\db.sqlite",
  "entities": [
    "src/app/entity/*.ts"
  ],
  "migrations": [
    "src/app/migration/*.ts"
  ],
  "subscribers": [
    "src/app/subscriber/**/*.ts"
  ],
  "cli": {
    "entitiesDir": "src/app/entity",
    "migrationsDir": "src/app/migration",
    "subscribersDir": "src/app/subscriber"
  }
}
`

**Comment by cjackson234** [comment] 2018-06-26 15:31
So I have it working doing the following:

In the ormconfig.json add a local copy of the database. Migrations will now be generated against the local copy of the database.
`{
   "type": "sqlite",
  "synchronize": false,
  "logging": false,
   "database": "migrate.sqlite",
   ........
}`

Install ts-node and typescript
`npm install -g ts-node typescript`

Added the following to the package.json
`  "scripts": {
    .....
    "migrate": "ts-node ./node_modules/typeorm/cli.js migration:generate",
  },`

And I can not run migrations with this
`npm run migrate -- n testy`

**Comment by Kononnable** [comment] 2019-02-19 13:09
Closing as no reproduction repo was provided.

**Closed by Kononnable** 2019-02-19 13:09 UTC

**Comment by AdditionAddict** [comment] 2019-07-01 13:38
I had the same issue caused by having incorrect path to database 
`"database": "dist/assets/data/database",` instead of `"database": "dist/assets/data/database.db",` inside ormconfig.json
