### ISSUE TITLE
Fails to connect to remote postgres instance. Fix by bumping pg:^8.0.0

### ISSUE THREAD

**Issue by ticklepoke** [typeorm/typeorm#6748] opened 2020-09-21 08:05 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Postgres driver fails to connect when generating boilerplate with express:

```sh
typeorm init --express --database=postgres
```

```sh
npm start
```

2. Script immediately exits without calling `createConnection()` in `src/index.ts`

**Fix**
Fixed by manually installing `pg: ^8.0.0` instead. It is mentioned in this [stackoverflow question](https://stackoverflow.com/questions/62119498/typeorm-createconnection-return-pending-even-with-await-on-macos-with-pg).

**Comment by imnotjames** [comment] 2020-10-01 06:29
Duplicate of #5949

**Closed by imnotjames** 2020-10-01 06:29 UTC
Labels: bug, driver: postgres
