### ISSUE TITLE
DeleteDateColumn can`t find data where column is 0

### ISSUE THREAD

**Issue by PizzaJu** [typeorm/typeorm#8090] opened 2021-08-16 07:04 UTC
```typescript
@DeleteDateColumn({ name: 'is_del', nullable: true, comment: '1删除，0正常' })
isDel?: number | null;
```

### My Environment

mysql

**Comment by imnotjames** [comment] 2021-08-16 15:40
Duplicate of #8089

**Closed by imnotjames** 2021-08-16 15:40 UTC
Labels: bug, requires triage
