### ISSUE TITLE
Inappropiate migration generated for 'default: null' (2021)

### ISSUE THREAD

**Issue by thefat32** [typeorm/typeorm#7579] opened 2021-04-19 07:07 UTC
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using the option default: null for an entity's column, and generating a migration using typeorm migration:generate, the generated migrations get into a loop. The generated migration is always the same, because 'null' default value is being normalized as null instead of NULL. When typeorm checks default value for the column it finds 'NULL' !==  'null'.

Related to #7356

In order to reproduce with a simple User entity:

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  Unique,
  CreateDateColumn,
  UpdateDateColumn
} from 'typeorm';
import { Length } from 'class-validator';

@Entity()
@Unique(['username'])
export default class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @Length(4, 20)
  username: string;

  @Column()
  @Length(4, 100)
  password: string;

  @Column({ nullable: true, default: null })
  country: string;

  @Column('simple-array')
  @IsNotEmpty()
  roles: string[];

  @Column()
  @CreateDateColumn()
  createdAt!: Date;

  @Column()
  @UpdateDateColumn()
  updatedAt: Date;
}
```

- Sync Schema

```sh
ts-node ./node_modules/typeorm/cli.js schema:sync
```

- Generate Migration

```sh
ts-node ./node_modules/typeorm/cli.js migration:generate -n DefaultNullTest
```

Obtained:

- Up

```sql
ALTER TABLE `user` CHANGE `country` `country` varchar(255) NULL
```

- Down

```sql
ALTER TABLE `user` CHANGE `country` `country` varchar(255) NULL DEFAULT 'NULL'
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by thefat32** [comment] 2021-04-19 07:17
This pull #7356 edits MysqlDriver.ts while it should be only fixing PostgresDriver and it's araising this already fixed bug again

**Comment by thefat32** [comment] 2021-04-19 08:01
When using `nullable: true` or `default: null` tyeorm will generate wrong migrations as normalize function is returning `undefined` for `null` default value. Also MySql/MariaDB sets default value automatically to `null` if the column is marked as nullable so we should return also 'NULL' in normalize function when default value is not set and column is marked as nullable

**Comment by duong-le** [comment] 2021-04-24 10:03
I can confirm the same thing happens to the `Postgres` driver. Dropping the NULL default value when generating migration is extremely dangerous.

```
@Entity()
export class Author {
  @Column()
  name: string;

  @ManyToMany(() => Product, (product) => product.authors)
  products: Product[];

  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @DeleteDateColumn({ nullable: true })
  deletedAt?: Date;
}
```

Current behavior
```
CREATE TABLE "author" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "PK_5a0e79799d372fe56f2f3fa6871" PRIMARY KEY ("id"))
```

Expected behavior
```
CREATE TABLE "author" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP DEFAULT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_5a0e79799d372fe56f2f3fa6871" PRIMARY KEY ("id"))
```

I can confirm that PR https://github.com/typeorm/typeorm/pull/7580 fixes the issue but it is limited to Mysql. 

@AlexMesser can you take a look at this, I think it is somehow related to your recent PR https://github.com/typeorm/typeorm/pull/7356

**Comment by thefat32** [comment] 2021-04-24 23:34
Indeed, it's a pretty dangerous bug!

**Comment by lynk-one-machines** [comment] 2021-05-06 17:28
In my case, without the default value I'm facing the same output. 
Moreover for every new migration I'm generating, I have this alter going on and on ... it's not very handy to work with because it messes up with real new schema changes. Do you think it's going to be fixed rapidly ?

**Comment by AlexMesser** [comment] 2021-05-08 15:54
@thefat32  To merge your PR I need to understand the problem you have.
I'm trying to reproduce your issue, but without success.
Can you please add test for this issue in a separate PR?

**Comment by duong-le** [comment] 2021-05-08 15:59
> @duong-le issue you are reporting seems to be different to OP issue.
> 
> `"deletedAt" TIMESTAMP` and `"deletedAt" TIMESTAMP DEFAULT NULL` are identical for RDBMS, what is the point in adding additional "default null"?

@AlexMesser the issue applies to any type of column, not limited to Date. I just take it for example.

**Comment by AlexMesser** [comment] 2021-05-08 16:39
@duong-le I mean there is no difference between `"deletedAt" TIMESTAMP`, `"deletedAt" TIMESTAMP NULL` and `"deletedAt" TIMESTAMP DEFAULT NULL` at the database level. All these definitions leads to the same result.

```sql
CREATE TABLE "test1" (id INT, name VARCHAR)
CREATE TABLE "test2" (id INT, name VARCHAR NULL)
CREATE TABLE "test3" (id INT, name VARCHAR DEFAULT NULL)

SELECT table_name, column_name, column_default, is_nullable
 FROM information_schema.columns
 WHERE table_name IN ('test1', 'test2', 'test3') and column_name = 'name'
```

![Screen Shot 2021-05-08 at 9 38 38 PM](https://user-images.githubusercontent.com/17142628/117546808-c2101d00-b045-11eb-8d14-30b8a6f4cc68.png)

**Comment by duong-le** [comment] 2021-05-08 16:52
@AlexMesser I get your idea about timestamp but the problem happens to me regardless of column type

```ts
@Entity()
export class Shipping {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ default: null })
  name: string;

  @Column()
  address: string;

  @Column()
  phoneNumber: string;

  @Column({ enum: DeliveryState, default: DeliveryState.PROCESSING })
  state: DeliveryState;

  @Column({ default: null })
  code: string;

  @Column({ default: 0 })
  fee: number;

  @Column({ default: null })
  deliveryDate: Date;

  @Column()
  shippingMethodId: number;

  @ManyToOne(() => ShippingMethod, (shippingMethod) => shippingMethod.shippings)
  shippingMethod: ShippingMethod;
}
```

Current
```sql
CREATE TABLE "shipping" ("id" SERIAL NOT NULL, "name" character varying, "address" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "state" character varying NOT NULL DEFAULT 'PROCESSING', "code" character varying, "fee" integer NOT NULL DEFAULT '0', "deliveryDate" TIMESTAMP, "shippingMethodId" integer NOT NULL, CONSTRAINT "PK_0dc6ac92ee9cbc2c1611d77804c" PRIMARY KEY ("id"))
```

Expect
```sql
CREATE TABLE "shipping" ("id" SERIAL NOT NULL, "name" character varying DEFAULT null, "address" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "state" character varying NOT NULL DEFAULT 'PROCESSING', "code" character varying DEFAULT null, "fee" integer NOT NULL DEFAULT '0', "deliveryDate" TIMESTAMP DEFAULT null, "shippingMethodId" integer NOT NULL, CONSTRAINT "PK_0dc6ac92ee9cbc2c1611d77804c" PRIMARY KEY ("id"))
```

**Comment by pleerock** [comment] 2021-05-08 16:55
@duong-le I don't see a "problem", can you please point to where the problem is? Omitted `DEFAULT NULL` shouldn't be a problems since it's **equal** to not having it.

**Comment by duong-le** [comment] 2021-05-08 17:07
@AlexMesser @pleerock Oh I see. It is the change in behavior in the newer typeorm version that makes me confusing. Sorry for wasting your time.

**Comment by thefat32** [comment] 2021-05-09 23:57
> 
> 
> @thefat32 To merge your PR I need to understand the problem you have.
> I'm trying to reproduce your issue, but without success.
> Can you please add test for this issue in a separate PR?



> 
> 
> @thefat32 To merge your PR I need to understand the problem you have.
> I'm trying to reproduce your issue, but without success.
> Can you please add test for this issue in a separate PR?

Hi, running the example I gave in the description should reproduce the issue. In release 0.2.32 any column with default value set to null or default value not specified will generate wrong migrations on every restart if 'sync' option set to true or when manual generatin migrations. In the given example the column that has this problem is:

```ts
  @Column({ nullable: true, default: null })
  country: string;
```

The migration loop is due to this [line ](https://github.com/typeorm/typeorm/blob/1b8b7f151099b0ba18843cf9a2bedb604e5ae7e1/src/driver/mysql/MysqlDriver.ts#L585) of code, we should return 'NULL' string to compare with database schema.

The same problem happens if default value is not specified as nullable is set to true:

Example:

```ts
  @Column({ nullable: true })
  country: string;
```

This happens because MySQL defaults every nullable column with no specified default value to NULL. In that case this [line](https://github.com/typeorm/typeorm/blob/1b8b7f151099b0ba18843cf9a2bedb604e5ae7e1/src/driver/mysql/MysqlDriver.ts#L608) is returning 'undefined' while the DB schema contains a 'DEFAULT NULL' definition. My proposal to fix this problems in the mysql driver is:

```ts
  if (defaultValue === null) {
    return 'NULL';
  } else if (defaultValue === undefined && columnMetadata.isNullable) {
    return 'NULL';
```

The `return 'NULL';` modification fixes first mentioned issue and the added `else if (defaultValue === undefined && columnMetadata.isNullable)` condition handles the second.

**Comment by thefat32** [comment] 2021-05-10 00:03
i think this should be addressed quickly because it has the potential to harm any user using `  @Column({ nullable: true, default: null })` and mysql driver. Which is a very common usage.

**Comment by AlexMesser** [comment] 2021-05-10 09:43
I spent few hours trying to reproduce your issue - without any success. Please sent a least a minimal reproduction github repository with simple and clear steps of reproduction.

**Comment by thefat32** [comment] 2021-05-10 15:02
Done! https://github.com/thefat32/typeorm-bug

Step by step in readme

**Comment by thefat32** [comment] 2021-05-12 23:08
I'm using 0.2.32 too. Every time you run  `yarn schema:sync` or `ts-node ./node_modules/typeorm/cli.js schema:sync` (whatever you prefer) it executes:

```SQL
ALTER TABLE `buggy` CHANGE `buggyColumn` `buggyColumn` varchar(255) NULL;
ALTER TABLE `buggy` CHANGE `buggyColumn2` `buggyColumn2` varchar(255) NULL;
```
`ts-node ./node_modules/typeorm/cli.js version`
![version](https://user-images.githubusercontent.com/10998637/118054657-07419100-b35d-11eb-9c07-a481dc3dcdfd.png)

`ts-node ./node_modules/typeorm/cli.js schema:sync`

![sync](https://user-images.githubusercontent.com/10998637/118055031-b67e6800-b35d-11eb-86fd-8ba673c4ca2a.png)

**Comment by thefat32** [comment] 2021-05-12 23:11
Btw I'm using MariaDB, but this should happen with every MySQL compliant DB

**Comment by pleerock** [comment] 2021-05-22 15:58
I checked your issue, there are no additional queries from my side as well.

Running first time:

![image](https://user-images.githubusercontent.com/1753397/119232862-1df79d00-bb40-11eb-8398-3c01fa1b8654.png)

Running second time:

![image](https://user-images.githubusercontent.com/1753397/119232870-28b23200-bb40-11eb-9133-c1e7e93183b7.png)

I have to close this issue, because we loosed so much time on it and cannot reproduce it. I'm quite sure something is wrong in your environment. If you don't think so - try to clone your repository on a different machine and check what results will be.

**Closed by pleerock** 2021-05-22 15:58 UTC
Labels: bug, requires triage

**Comment by thefat32** [comment] 2021-05-26 08:58
Tested in clean enviroment. Added `docker-compose.yml` with latest MariaDB version to my repo and updated README with instructions to use the docker image. I have no intention in making you loose your time on this, but can't understand why you can't reproduce this :(

**Comment by pleerock** [comment] 2021-05-26 10:04
@thefat32 please ask somebody in the community to try to reproduce your issue, maybe another mind can help here.

**Comment by yanngit** [comment] 2021-05-26 14:41
I just cloned the repo and I can reproduce ! I'm using ubuntu and faced the same issue on my project ...

**Comment by thefat32** [comment] 2021-05-26 18:15
Thanks! Will wait for @pleerock on this

**Comment by Sebi2020** [comment] 2022-01-30 22:18
@jozsefsallai Nice! This solves the issue!

**Comment by ifreeWorld** [comment] 2022-10-26 08:21
@pleerock thx, you solved my problem. I used mysql as orm type, but my database is mariadb, change into mariadb is OK
