### ISSUE TITLE
Synchronize issue with UUID (MySQL)

### ISSUE THREAD

**Issue by Bipolar** [typeorm/typeorm#3374] opened 2019-01-07 00:51 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am running into issues with synchronize setting on TypeORM with UUID PrimaryGeneratedColumns on MySQL driver. It seems each time application loads it tries to re-index, so it drops the id column and tries to add it again. Issue is that since it's UUID, for MySQL the column type is varchar(36) NOT NULL PRIMARY KEY. So we run into duplicate entry '' for key 'PRIMARY' because UUID is not set.

To recreate issue, you can do it like this:

```typeorm init --name MyProject --database mysql```

Edit your User.ts entity to change primary key to UUID. 

```
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class User {

    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

}
```

Ensure synchronize is set to true in ormconfig.json. Start the app and it will insert sample User. Restart app and synchronize will run and try and drop and re-add the column and give error.

```
  message: 'ER_DUP_ENTRY: Duplicate entry \'\' for key \'PRIMARY\'',
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: 'Duplicate entry \'\' for key \'PRIMARY\'',
  sqlState: '23000',
  index: 0,
  sql:
   'ALTER TABLE `user` ADD `id` varchar(36) NOT NULL PRIMARY KEY',
  name: 'QueryFailedError',
  query:
   'ALTER TABLE `user` ADD `id` varchar(36) NOT NULL PRIMARY KEY',
  parameters: []
```

**Comment by pleerock** [comment] 2019-01-07 07:59
please provide some reproduction

**Comment by Bipolar** [comment] 2019-01-07 08:01
Hi @pleerock , I wrote some steps above to reproduce the issue, did I miss something?

**Comment by pleerock** [comment] 2019-01-07 11:19
do you have records in your database before you change it to uuid?

**Comment by pleerock** [comment] 2019-01-07 11:41
Sounds like uuid isn't being generated

**Comment by Bipolar** [comment] 2019-01-07 11:55
Thanks, how to fix?

**Comment by pleerock** [comment] 2019-01-07 12:12
first we need to write a test that will with this issue, then we need to find a place where its being generated and see why its not generating (if its an issue) then fix it.

**Comment by sangheestyle** [comment] 2019-01-11 13:43
@pleerock Hi! Could you tell me where do I start to fix this problem? I want to spend time to solve this issue.

**Comment by pleerock** [comment] 2019-01-13 17:57
fix in #3234 broke this functionality. I pushed fix and released `0.2.12-rc.2` with this fix.

**Closed** 2019-01-13 17:59 UTC
Labels: needs failing tests

**Comment by tlimp** [comment] 2021-06-15 13:49
The issue is closed, but  ist fixed? I am experiencing the exact same issue with the `aurora-data-api` driver.
Is this a general issue, or some implementation details  in the driver?

**Comment by JakeCover** [comment] 2021-08-02 18:46
Yep experienced the same in the postgres driver, it doesn't seem to be dropping everything in the synchronize.

**Comment by pleerock** [comment] 2021-08-03 07:49
Please create a new issue with the new details if you face problems.

**Comment by N-Andronopoulos** [comment] 2023-06-04 09:38
Regression 0.3.16 related to #10090
