### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by sarink** [typeorm/typeorm#4526] opened 2019-08-01 10:53 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Bi-directional relations are circular by definition. With webpack and typescript on the backend, how can we possibly solve this issue? Are we actually forced into keeping one giant awful `allEntities.ts` file?...

I know it's not a typeorm problem, but ES modules don't support circular dependencies, and here we have a fantastic ORM library which basically requires them? I honestly don't understand how anyone can use this, the problem seems so fundamental...

Can the maintainers of this library offer any help or solution? Thanks :)

**Comment by Ginden** [comment] 2019-08-01 18:40
@sarink You are operating on bad premise. Namely:
>  ES modules don't support circular dependencies,

ES modules do support circular dependencies (not all kinds of circular dependencies, but most of them).

Post your code so we can diagnose what is wrong.

**Comment by sarink** [comment] 2019-08-02 07:49
@Ginden I believe CommonJS modules support circular dependencies (like, via `module.exports = {...}` but we are using typescript and webpack (yes, on the backend) with ES6 modules

**Comment by Ginden** [comment] 2019-08-02 13:17
@sarink ES Modules support circular dependencies. 
https://stackoverflow.com/a/46593566/2446102

See:

>  If you cannot (or don't want to) completely avoid them, restrict the involved modules to only use function declarations with circular dependencies, *never initialise top-level values (constants, variables, classes) by using imported values (that includes extends references)*.

**Comment by sarink** [comment] 2019-08-06 02:52
@Ginden Sorry, I'm abusing the word "support" here. I'm aware that circular dependencies work, as in, you can compile them, and if you carefully use things in the right order, that it's all 💯(that is, until some future day when you use a part of circular-required module before it's fully loaded, which you have absolutely no way to test for or know you're doing, then it blows up at runtime, maybe in production).

As you must be well aware of, this fragile order is very difficult to maintain in a complex codebase. The best way, as pointed out by that link, is to "avoid them completely". So, we can use tools like the [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin) or [madge](https://github.com/pahen/madge) to detect them. But if we do that, then how can we possibly have a many-to-many entity relationship?

How can one feasibly avoid circular dependencies completely and use typeorm entity relationships?

**Comment by marcorinck** [comment] 2019-08-06 11:03
I'm asking this myself too  and haven't understood it completely.

I'm using typeorm in an ionic4/angular CLI project and angular CLI has a circular dependency detection built in and warns about it when building/running the project. When I have these 2 entities in 2 different files, it works without a warning and I can use them perfectly fine in any browser: 

````typescript
@Entity("selectedSanierungspaket")
export class ESelectedSanierungspaket {

	@PrimaryGeneratedColumn()
	id: number;

	@OneToOne("ESanierungspaket")
	@JoinColumn()
	sanierungspaket: ESanierungspaket;

        //this relation points to the entity below 
	@OneToMany("ESelectedLeistungspaket", "selectedSanierungspaket")
	selectedLeistungspakete: ESelectedLeistungspaket[];

	@ManyToOne("EMassnahmeEntwurf", "selectedSanierungspakete")
	entwurf: EMassnahmeEntwurf;

}

@Entity("selectedLeistungspaket")
export class ESelectedLeistungspaket {

	@PrimaryGeneratedColumn()
	id: number;

	@Column({default: ''})
	notiz: string;

	@Column({default: false})
	scrollTo: boolean;

	@Column({default: false})
	isOpen: boolean;

	@OneToMany("ERaum", "selectedLeistungspaket")
	selectedRaeume: ERaum[];

	@OneToMany("EAngebot", "leistungspaket", {cascade: true})
	angebote: EAngebot[];

	@OneToMany("EFoto", "leistungspaket", {cascade: true})
	fotos: EFoto[];

	@OneToOne("ELeistungspaket")
	@JoinColumn()
	leistungspaket: ELeistungspaket;

	@OneToMany("ESelectedLeistungsposition", "selectedLeistungspaket")
	selectedLeistungspositionen: ESelectedLeistungsposition[];

        //this is the counterpart to the marked relation in the entity above
	@ManyToOne("ESelectedSanierungspaket", "selectedLeistungspakete")
	selectedSanierungspaket: ESelectedSanierungspaket;

}
````

Besides other relations these entities have a OneToMany/ManyToOne relation between each other: selectedSanierungspaket.selectedLeistungspakete and selectedLeistungspaket.selectedSanierungspaket. After using strings in the Typeorm decorators to describe the relations (a 0.28 feature) this works fine, despite the still existing circular dependency between them (because of the type definitions of the OneToMany/ManyToOne relation properties) 

When I add another OneToOne relaton to the the same entitiy to the selectedSanierungspaket entity I immediately get a warning by angular CLI and an error message in the browser. Like this:

````typescript
@OneToOne("ESelectedLeistungspaket")
@JoinColumn()
openedSelectedLeistungspaket: ESelectedLeistungspaket;
````

````typescript
@Entity("selectedSanierungspaket")
export class ESelectedSanierungspaket {

	@PrimaryGeneratedColumn()
	id: number;

	@OneToOne("ESanierungspaket")
	@JoinColumn()
	sanierungspaket: ESanierungspaket;

	@OneToMany("ESelectedLeistungspaket", "selectedSanierungspaket")
	selectedLeistungspakete: ESelectedLeistungspaket[];

	@ManyToOne("EMassnahmeEntwurf", "selectedSanierungspakete")
	entwurf: EMassnahmeEntwurf;

	@OneToOne("ESelectedLeistungspaket")
	@JoinColumn()
	openedSelectedLeistungspaket: ESelectedLeistungspaket;

}
````

I only added this property to one entity and despite having used the same type definition ("ESelectedLeistungspaket") on the OneToMany property I now get a circular dependency error in the browser.

I'm OK with the solution to not use circular dependencies at all ... but does this mean, that I can't even use the entities as types? Or do I need to introduce abstract classes or interfaces for every entity? 

One other observation: when I remove the typeorm decorator from the property in my last example the error immediately vanishes and I can use the entity again but of course, its not a typeorm relation anymore. It seems that typeorm is doing something with the classes during initialization which causes circular dependency problems?

**Comment by Ginden** [comment] 2019-08-06 16:28
> It seems that typeorm is doing something with the classes during initialization which causes circular dependency problems?

Actually it's TypeScript that is responsible for this, concretely [decorator metadata](https://www.typescriptlang.org/docs/handbook/decorators.html#metadata). I wanted to report it, but it was already marked as "won't fix" in Microsoft/TypeScript#14971 over 2 years ago. 

> that said, we have no plans to expand the metadata support, nor to serialize structural types. we believe this still outside the scope of the TS project in the time being.

Someone had proposed workaround there:

```
class {
  @Field
  circularField: CircularType | undefined; // add `| undefined` so 'design:type' becomes Object
}
```

**Comment by marcorinck** [comment] 2019-08-07 08:26
> Not sure if it will work.

Doesn't change anything for me. 

But I slowly understand why you want to make entity schemas the "primary way of defining a database schema model" instead of decorators (as described in https://github.com/typeorm/typeorm/issues/3251 ).

But using decorators is looking so nice 😀

**Comment by sarink** [comment] 2019-08-07 09:44
Entity schemas? Why haven't I seen this anywhere...

**Comment by marcorinck** [comment] 2019-08-07 10:14
> Entity schemas? Why haven't I seen this anywhere...

I don't know, but [its documented](https://typeorm.io/#/separating-entity-definition) ... and they should be a solution for circular dependency problems. But readability is inferior to decorators ... in my opinion (which doesn't matter).

**Comment by jalooc** [comment] 2019-10-22 01:15
I heave the precisely same feelings as you @marcorinck. In my project, I chose classes + decorators for their conciseness and ease of use with decorators. But entity schemas are undoubtedly more flexible and less error-prone. I wish they were more readable and concise as well, that would make the choice way simpler.

**Comment by bibobibo** [comment] 2019-11-12 05:49
You can resolve the issue in this way. 
https://github.com/typeorm/typeorm/issues/4190

**Comment by bigLucas** [comment] 2019-11-29 22:03
Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency. 

After switching to 
                repository.createQueryBuilder()
                .insert()
                .into(TABLE_NAME)
                .values(entity)
                .execute(); 
This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**

I was using **serverless and webpack**. Typeorm does not work well with webpack.

**Comment by nbaua** [comment] 2020-01-01 04:51
I've created a minimal repo for this issue: Guys feel free to contribute and lets resolve this in best possible way. (mysql script also included for those who wants to fork/clone and check it further)

https://github.com/nbaua/nest-nx-typeorm-circular-dep

**Comment by JamesDelfini** [comment] 2020-09-09 19:48
> Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency.
> 
> After switching to
> repository.createQueryBuilder()
> .insert()
> .into(TABLE_NAME)
> .values(entity)
> .execute();
> This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**
> 
> I was using **serverless and webpack**. Typeorm does not work well with webpack.

I disregarded using `repository.save()` and uses the [Query Builder as Insert function](https://typeorm.io/#/insert-query-builder) which everything works perfectly. As stated above as reference, confirming many of issues has been posted with exactly the same resolution of the issue. In development this issue would not occur to me, however after post-build(using webpack) running it will show **Circular/Cylic Dependency**. 

TypeORM is designed to use `@Decorator` to wire relation entities together, and it was the exactly the cause of it due to the `repository.save()` are loading up the Relational Entities.. 

The behavior of the Circular Dependencies is due to the ES Module is not supported yet, there are a lot of related blog post explaining it more detailed.

**Comment by bigLucas** [comment] 2020-09-09 20:23
> > Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency.
> > After switching to
> > repository.createQueryBuilder()
> > .insert()
> > .into(TABLE_NAME)
> > .values(entity)
> > .execute();
> > This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**
> > I was using **serverless and webpack**. Typeorm does not work well with webpack.
> 
> I disregarded using `repository.save()` and uses the [Query Builder as Insert function](https://typeorm.io/#/insert-query-builder) which everything works perfectly. [As stated above as reference,](https://github.com/typeorm/typeorm/issues/4526) confirming many of issues has been posted with exactly the same resolution of the issue. In development this issue would not occur to me, however after post-build(using webpack) running it will show **Circular/Cylic Dependency**.
> 
> TypeORM is designed to use `@Decorator` to wire relation entities together, and it was the exactly the cause of it due to the `repository.save()` are loading up the Relational Entities during the insertion. The behavior of the Circular Dependencies is due to the ES Module is not supported yet, there are a lot of related blog post explaining it more detailed.

Guys, **I'm solve this problem between typeORM and webpack, now I'm able to use the save() method, without any problem,** just adding `optimization: { minimize: false },` to module.exports inside webpack.config.js file

```js
const webpack = require('webpack'); 
const path = require('path');
const slsw = require('serverless-webpack');

/**
  TypeOrm does not work well with webpack, we inject a env variable here to be used at .env.ts
  to define how typeorm will receive it's params.
*/
slsw.lib.serverless.service.provider.environment.isWebpacked = true;

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  optimization: { minimize: false },
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  plugins: [
    new webpack.IgnorePlugin(/^pg-native$/)
  ],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
};
``

**Comment by imnotjames** [comment] 2020-10-05 14:53
Looks like this has been resolved in a few different ways.  I'll be closing it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Closed by imnotjames** 2020-10-05 14:53 UTC

**Comment by sarink** [comment] 2020-10-05 15:55
Changing your webpack config does not fix this problem.

Using a solution like https://github.com/typeorm/typeorm/issues/4190 where strings are used instead does indeed fix it, but also defeats the purpose of using a typed orm library?

Using entity schemas works, but these are barely documented, (are they even recommended by typeorm authors?), and wayyyy more inconvenient than the decorator method.

People need an _actual_ solution to this problem, not one of these sad workarounds. It's too bad you're closing it.

**Comment by imnotjames** [comment] 2020-10-05 16:14
> Using entity schemas works, but these are barely documented, (are they even recommended by typeorm authors?), and wayyyy more inconvenient than the decorator method (also unacceptable, imo).

Entity Schemas are recommended by the authors, but yes, the documentation is lacking.

> People need an actual solution to this problem, not one of these sad workarounds. It's too bad you're closing it.

Unfortunately, as I understand it, the problem is "To create typed circular references between models you need to have circular dependencies between the modules they're defined in" - and that's not going to go away.  It's sort of by definition what you're doing here, and isn't a TypeORM specific issue.

Without TypeORM you'd run into this same issue, wouldn't you? As this is a Typescript and Javascript problem.

If you want to forego typing you can prevent circular dependencies, but for circular dependencies between classes in different modules you'll need circular dependencies between modules.  This can be done in a number of ways - including Entity Schemas - which can be done effectively as JSON files if need be.

**Comment by imnotjames** [comment] 2020-10-05 16:20
PS - closing this does not mean we're shutting down any suggestions for improvements - it's just that the question initially posed was answered & other questions / discussions are more suitable to go within the slack than as an issue.  Asking others for assistance & suggestions on a scenario that goes against the normal flows of TypeORM falls within the topics that probably should go to the support channels.

If you have actionable suggestions for features or improvements please open a new issue with the details - we're more than happy to address those!

**Comment by pamls** [comment] 2020-11-03 21:43
> 
> 
> > > Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency.
> > > After switching to
> > > repository.createQueryBuilder()
> > > .insert()
> > > .into(TABLE_NAME)
> > > .values(entity)
> > > .execute();
> > > This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**
> > > I was using **serverless and webpack**. Typeorm does not work well with webpack.
> > 
> > 
> > I disregarded using `repository.save()` and uses the [Query Builder as Insert function](https://typeorm.io/#/insert-query-builder) which everything works perfectly. [As stated above as reference,](https://github.com/typeorm/typeorm/issues/4526) confirming many of issues has been posted with exactly the same resolution of the issue. In development this issue would not occur to me, however after post-build(using webpack) running it will show **Circular/Cylic Dependency**.
> > TypeORM is designed to use `@Decorator` to wire relation entities together, and it was the exactly the cause of it due to the `repository.save()` are loading up the Relational Entities during the insertion. The behavior of the Circular Dependencies is due to the ES Module is not supported yet, there are a lot of related blog post explaining it more detailed.
> 
> Guys, **I solved this problem between typeORM and webpack, now I'm able to use the save() method, without any problem,** just adding `optimization: { minimize: false },` to module.exports inside webpack.config.js file
> 
> ```js
> const webpack = require('webpack'); 
> const path = require('path');
> const slsw = require('serverless-webpack');
> 
> /**
>   TypeOrm does not work well with webpack, we inject a env variable here to be used at .env.ts
>   to define how typeorm will receive it's params.
> */
> slsw.lib.serverless.service.provider.environment.isWebpacked = true;
> 
> module.exports = {
>   mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
>   entry: slsw.lib.entries,
>   optimization: { minimize: false },
>   resolve: {
>     extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
>   },
>   plugins: [
>     new webpack.IgnorePlugin(/^pg-native$/)
>   ],
>   output: {
>     libraryTarget: 'commonjs',
>     path: path.join(__dirname, '.webpack'),
>     filename: '[name].js',
>   },
>   target: 'node',
>   module: {
>     rules: [
>       // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
>       { test: /\.tsx?$/, loader: 'ts-loader' },
>     ],
>   },
> };
> ```

Thank you very much!

**Comment by biels** [comment] 2021-07-10 11:19
A solution (when using typeorm in the browser) is in your tsconfig:
    "module": "commonjs",
    "target": "es2020",
    "esModuleInterop": true,

That way you can continue to use all your esmodules with typeorm (which requires commonjs).

However, as a note to maintainers, I think support for esmodules should be added to typeorm so all of this can be avoided.

**Comment by MarcusHSmith** [comment] 2022-04-26 03:57
> For anyone who comes across this issue in the future. As of version 3.1 you may avoid this issue with webpack entirely when compiling ESM applications by using the following syntax
> 
> ```
> 
> import { Entity, Column, Relation } from 'typeorm'
> 
> @Entity()
> export class Person { 
>   .....
>   @ManyToOne(() => Business, (business) => business.members)
>   business: Relation<Business>;
> }
> ```
> 
> Webpack tries to redefine the Type for Business. By using the `Relation` type here TypeORM is able to define a secondary type to avoid the circular dependency during bundling by webpack.
> 
> Thanks Devs!

Why doesn't this still import `Business`?

**Comment by LouisJULIEN** [comment] 2022-08-19 11:37
You can use typescript `import type` to break circular import. Works well!

```typescript
import { Entity, Column, Relation } from 'typeorm'
import type { Business } from './business'

@Entity()
export class Person { 
  .....
  @ManyToOne('Business', 'members')
  business: Relation<Business>;
}
```

**Comment by Junaid67** [comment] 2022-12-14 18:49
> Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency.
> 
> After switching to repository.createQueryBuilder() .insert() .into(TABLE_NAME) .values(entity) .execute(); This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**
> 
> I was using **serverless and webpack**. Typeorm does not work well with webpack.

Worked for me, thanks

**Comment by troberts-28** [comment] 2023-02-17 21:25
> Changing your webpack config does not fix this problem.
> 
> Using a solution like #4190 where strings are used instead does indeed fix it, but also defeats the purpose of using a typed orm library? I don't know how this is considered acceptable. Perhaps you could generate an enum of strings based on the models, or something? That seems like it could work.
> 
> Using entity schemas works, but these are barely documented, (are they even recommended by typeorm authors?), and wayyyy more inconvenient than the decorator method (also unacceptable, imo).
> 
> @imnotjames People need an _actual_ solution to this problem, not one of these sad workarounds. It's too bad you're closing it.

Big +1 for [Entity Schema](https://typeorm.io/separating-entity-definition) from me. I was struggling to find a solution to this - importing types didn't work and I wasn't satisfied with the querybuilder string insert solution (it makes using an ORM pointless!).

I switched my decorator entities to Entity Schema's pretty easily (the documentation is a bit patchy but the type definitions really help), and now the save function works perfectly in production, with no complaints about cyclic dependencies.

**Comment by jeffkni** [comment] 2023-02-21 13:43
I hit this same problem with circular dependencies with TypeORM. 
- Switching to an `insert()` as suggested above doesn't work for my use case because I am calling `save()` on an entity containing child entities
- Swapping to "Entity Schema" syntax would be too big a change for our codebase
- Using "string" syntax like `@ManyToOne('User', 'photos')` per https://github.com/typeorm/typeorm/issues/4190 looked promising but this caused a new problem to pop up: https://github.com/typeorm/typeorm/issues/4714
- `import type { Business } from './business'` syntax also fails for me with compiler errors
- `minimize: false` is too big a hammer for this problem.
- Tried ` business: Relation<Business>;` syntax but it didn't do the trick for me  

The cleanest fix I've found so far is keeping the original
```javascript
  @OneToMany(type => Photo, photo => photo.user)
```

syntax and using terser to keep classnames in webpack.config.js:

```javascript
const TerserPlugin = require('terser-webpack-plugin');
  return {
    [...]
    optimization: {
      minimize: true,
      minimizer: [
        new TerserPlugin({
          parallel: true,
          terserOptions: {
            keep_classnames: true
          }
        })
      ]
    }
  };
};
```

**Comment by ForeverYoung1208** [comment] 2023-04-19 10:48
@jeffkni, thanx!
I have the same situation. (((
and only  using terser to keep classnames helped me.

For others who will struggle with such an issue, i want to add some tips to mentioned solution: 
In my case, i use `react-app-rewired` to build app, and my entities were stored in a npm package (to avoid cycle dependencies while building npm package, i used string notation syntax like `@ManyToOne('User', 'photos')`, and such a decision always caused minification bug on a main app (not a npm package) production build....

So, in my case i changed my `config-override.js` in the main app by  adding there several lines:

```
const TerserPlugin = require('terser-webpack-plugin');
...

module.exports = function override(config) {
... other config stuff...
  const terserPluginIdx = config.optimization.minimizer.findIndex(
    (minimizer) => minimizer instanceof TerserPlugin
  );  
  
  config.optimization.minimizer[terserPluginIdx] = new TerserPlugin({
    parallel: true,
    terserOptions: {
      keep_classnames: true
    }
  })

... other config stuff...
  return config;
};
```

Pay attention, i completely have overriden TerserPlugin instance at the mimimizer array. I don't konw why, but otherwise options changes were ignored.
Not-so-good-solution (maybe, it can be improved by tuning tereser's options more carefully)... but... thats the best solution i'd found sicne two days of googling and chatGpt-ing))))

**Comment by Volna13** [comment] 2023-06-27 08:18
> Erm, yes, you will need to import Business. :]
But if we add imports again, then we again have a cyclic dependency

**Comment by paolocattani** [comment] 2024-01-19 08:51
> You can use typescript `import type` to break circular import. Works well!
> 
> ```ts
> import { Entity, Column, Relation } from 'typeorm'
> import type { Business } from './business'
> 
> @Entity()
> export class Person { 
>   .....
>   @ManyToOne('Business', 'members')
>   business: Relation<Business>;
> }
> ```

thank @LouisJULIEN you save my day!

Using string relation avoided the circular dependecies!!
From this : 
```js
  @IsOptional()
  @Column({ type: 'uuid', default: '00000000-0000-0000-0000-000000000000' })
  declare updatedBy: string;

  @ManyToOne(()=>User, User=>user.id) 
  @JoinColumn({ name: 'updatedBy' })
  declare updatedByUser?: Relation<User>;
```
To this : 
```js
  @IsOptional()
  @Column({ type: 'uuid', default: '00000000-0000-0000-0000-000000000000' })
  declare updatedBy: string;

  @ManyToOne('Users') // this line did the trick
  @JoinColumn({ name: 'updatedBy' })
  declare updatedByUser?: Relation<User>;
```

**Comment by AleFons** [comment] 2024-03-15 13:17
I have a ManyToMany relation and if I try to declare it with string then it straight up fails to start the database.

`
import { Field } from './../field';
...
@ManyToMany(type => Field, field => field.product_applications, { cascade: true, onDelete: 'CASCADE' })
  @JoinTable()
  fields: Relation<Field>[];
`
To:
`
import type { Field } from './../field';
...
@ManyToMany('Fields', { cascade: true, onDelete: 'CASCADE' })
  @JoinTable()
  fields: Relation<Field>[];
`

Not sure what would be the correct syntax here?

**Comment by biels** [comment] 2024-03-15 23:22
> I have a ManyToMany relation and if I try to declare it with string then it straight up fails to start the database.
> 
> ```
> import { Field } from './../field';
> ...
> @ManyToMany(type => Field, field => field.product_applications, { cascade: true, onDelete: 'CASCADE' })
>   @JoinTable()
>   fields: Relation<Field>[];
> ```
> To:
> ```
> import type { Field } from './../field';
> ...
> @ManyToMany('Fields', { cascade: true, onDelete: 'CASCADE' })
>   @JoinTable()
>   fields: Relation<Field>[];
> ```
> 
> Not sure what would be the correct syntax here?

If your entity class is named Field, you should place 'Field' or () => 'Field', but certainly not 'Fields'. It is the name or reference to the entity class

**Comment by AleFons** [comment] 2024-03-26 16:28
> > I have a ManyToMany relation and if I try to declare it with string then it straight up fails to start the database.
> > ```
> > import { Field } from './../field';
> > ...
> > @ManyToMany(type => Field, field => field.product_applications, { cascade: true, onDelete: 'CASCADE' })
> >   @JoinTable()
> >   fields: Relation<Field>[];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To:
> > ```
> > import type { Field } from './../field';
> > ...
> > @ManyToMany('Fields', { cascade: true, onDelete: 'CASCADE' })
> >   @JoinTable()
> >   fields: Relation<Field>[];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure what would be the correct syntax here?
> 
> If your entity class is named Field, you should place 'Field' or () => 'Field', but certainly not 'Fields'. It is the name or reference to the entity class

Did that; getting errors saying `No metadata for "T" was found`.

```
File: http://localhost/polyfills.01eb0475ac9e2d8a.js - Line 1 - Msg: Unhandled Promise rejection: No metadata for "T" was found. ; Zone: <root> ; Task: Promise.then ; Value: P: No metadata for "T" was found. P: No metadata for "T" was found.
                                                                                                        at Vi.getMetadata (http://localhost/main.67978bc742dcc216.js:1:2001821)
                                                                                                        at get metadata [as metadata] (http://localhost/main.67978bc742dcc216.js:1:1606420)
                                                                                                        at http://localhost/main.67978bc742dcc216.js:1:1608563
                                                                                                        at Generator.next (<anonymous>)
                                                                                                        at t (http://localhost/main.67978bc742dcc216.js:1:2572856)
                                                                                                        at v (http://localhost/main.67978bc742dcc216.js:1:2573058)
                                                                                                        at http://localhost/main.67978bc742dcc216.js:1:2573117
                                                                                                        at new e (http://localhost/polyfills.01eb0475ac9e2d8a.js:1:34067)
                                                                                                        at http://localhost/main.67978bc742dcc216.js:1:2572999
                                                                                                        at Lt.findOne (http://localhost/main.67978bc742dcc216.js:1:1608583)
```

**Comment by saveliyvasilev** [comment] 2024-09-05 01:00
In case you're running with NestJS and are getting this error
```
A circular dependency has been detected inside TypeOrmModule. 
Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".
```
then check if you have an empty line in some `TypeOrmModule.forFeature` statement. I had something like this:

```ts
@Module({
	controllers: [....],
	providers: [...],
	imports: [
		TypeOrmModule.forFeature([
			EntityA,
			EntityB,
			EntityC,

			,
		]),
	],
	exports: [...],
})
```

Note the empty line between commas after `EntityC`. Removing it made it work. This is related to the `<empty item>` in an array when we create, say `const foo = [,,,,]`.

**Comment by harshtarang7** [comment] 2025-04-08 10:34
> Hello guys, I spent a week trying to solve a problem like this. So I solved this problem, just changed my repository method that saves the entity. I used repository.save (entity) and always failed with cyclic dependency.
> 
> After switching to repository.createQueryBuilder() .insert() .into(TABLE_NAME) .values(entity) .execute(); This error has been cleared. I really recommend trying to change the repository method, because the save() method waits for the full entity set and **createQueryBuilder() takes the entity values and turns them into string values, making a normal query.**
> 
> I was using **serverless and webpack**. Typeorm does not work well with webpack.


thanks man, it helped me !!!
