### ISSUE TITLE
Why use findOne to report errors

### ISSUE THREAD

**Issue by nanjingcaiyong** [typeorm/typeorm#4038] opened 2019-04-24 00:11 UTC
`**Issue` type:**

[ ] question

**Database system/driver:**
[ 4.0.4] `mssql`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**
I use SQL Server 2008 r2 database,
find,findbyids can all be used properly，
errors are reported when using findOne.

That's how I use it.

```bash
import "reflect-metadata";
import { createConnection } from "typeorm";
import { PersonalModel } from  './entity/PersonalModel';
const bodyParser = require("koa-bodyparser");
const Koa = require("koa");
const Router = require("koa-router");
import Routes  from "./router";
const app = new Koa();
const router = new Router();
createConnection()
  .then(async connection => {
    Routes.forEach(route => {
      router[route.method](route.route, async (ctx, next) => {
        const result = await new route.controller()[route.action](ctx, next);
        ctx.type = "json";
        ctx.body = result;
      });
    });
    app.use(bodyParser())
    app.use(router.routes()).use(router.allowedMethods());
    app.listen(3000);
    let repository = connection.getRepository(PersonalModel);
    console.log(await repository.findOneOrFail());
  })
  .catch(err => console.log(err));
```

errors：
```bash
{ QueryFailedError: Error: Invalid usage of the option NEXT in the FETCH statement.
    at new QueryFailedError (C:\Users\86186\Documents\GitHub\BlogServerApi\src\error\QueryFailedError.ts:9:9)
    at C:\Users\86186\Documents\GitHub\BlogServerApi\src\driver\sqlserver\SqlServerQueryRunner.ts:221:37
    at _query (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\mssql\lib\base.js:1293:25)
    at Request.tds.Request.err [as userCallback] (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\mssql\lib\tedious.js:661:15)
    at Request._this.callback (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\request.js:61:27)
    at Connection.endOfMessageMarkerReceived (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\connection.js:1944:20)
    at Connection.dispatchEvent (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\connection.js:1012:38)
    at Parser.<anonymous> (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\connection.js:812:18)
    at Parser.emit (events.js:189:13)
    at Parser.EventEmitter.emit (domain.js:441:20)
  message:
   'Error: Invalid usage of the option NEXT in the FETCH statement.',
  code: 'EREQUEST',
  number: 153,
  lineNumber: 1,
  state: 2,
  class: 15,
  serverName: 'iZh5s5gb8yheuqZ',
  procName: '',
  originalError:
   { Error: Invalid usage of the option NEXT in the FETCH statement.
       at handleError (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\mssql\lib\tedious.js:554:19)
       at Connection.emit (events.js:189:13)
       at Connection.EventEmitter.emit (domain.js:441:20)
       at Parser.<anonymous> (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\connection.js:618:16)
       at Parser.emit (events.js:189:13)
       at Parser.EventEmitter.emit (domain.js:441:20)
       at Parser.<anonymous> (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
       at Parser.emit (events.js:189:13)
       at Parser.EventEmitter.emit (domain.js:441:20)
       at addChunk (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\readable-stream\lib\_stream_readable.js:291:12)
     info:
      { number: 153,
        state: 2,
        class: 15,
        message: 'Invalid usage of the option NEXT in the FETCH statement.',
        serverName: 'iZh5s5gb8yheuqZ',
        procName: '',
        lineNumber: 1,
        name: 'ERROR',
        event: 'errorMessage' } },
  name: 'QueryFailedError',
  precedingErrors:
   [ { RequestError: Incorrect syntax near 'OFFSET'.
         at handleError (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\mssql\lib\tedious.js:556:15)
         at Connection.emit (events.js:189:13)
         at Connection.EventEmitter.emit (domain.js:441:20)
         at Parser.<anonymous> (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\connection.js:618:16)
         at Parser.emit (events.js:189:13)
         at Parser.EventEmitter.emit (domain.js:441:20)
         at Parser.<anonymous> (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
         at Parser.emit (events.js:189:13)
         at Parser.EventEmitter.emit (domain.js:441:20)
         at addChunk (C:\Users\86186\Documents\GitHub\BlogServerApi\node_modules\readable-stream\lib\_stream_readable.js:291:12)
       code: 'EREQUEST',
       number: 102,
       lineNumber: 1,
       state: 1,
       class: 15,
       serverName: 'iZh5s5gb8yheuqZ',
       procName: '',
       originalError: [Error],
       name: 'RequestError' } ],
  query:
   'SELECT "PersonalModel"."id" AS "PersonalModel_id", "PersonalModel"."buildTime" AS "PersonalModel_buildTime", "PersonalModel"."updateTime" AS "PersonalModel_updateTime", "PersonalModel"."status" AS "PersonalModel_status", "PersonalModel"."name" AS "PersonalModel_name", "PersonalModel"."age" AS "PersonalModel_age", "PersonalModel"."gender" AS "PersonalModel_gender", "PersonalModel"."education" AS "PersonalModel_education", "PersonalModel"."occupation" AS "PersonalModel_occupation", "PersonalModel"."company" AS "PersonalModel_company", "PersonalModel"."centered" AS "PersonalModel_centered" FROM "Blog_Personal" "PersonalModel" ORDER BY (SELECT NULL) OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY',
  parameters: [] }
```

need help, thanks!

**Comment by vlapo** [comment] 2019-04-24 08:33
Please format your code.

**Comment by nanjingcaiyong** [comment] 2019-04-26 07:53
> Please format your code.

Sorry, it has been revised. I hope you can help me solve this problem.

**Comment by nanjingcaiyong** [comment] 2019-04-28 01:55
> Please format your code.

@vlapo Sorry, it has been revised. I hope you can help me solve this problem.

**Comment by nanjingcaiyong** [comment] 2019-04-28 01:55
> Please format your code.

Sorry, it has been revised. I hope you can help me solve this problem.

**Comment by nanjingcaiyong** [comment] 2019-04-28 01:56
Sorry, it has been revised. I hope you can help me solve this    @vlapo

**Comment by Kononnable** [comment] 2019-05-25 10:13
Sorry for late response. What version of typeorm are you using(please specify by number)? I remember we've got problem with FETCH, NEXT in MSSQL, but it was some time ago.

**Comment by jotamorais** [comment] 2019-06-06 19:00
I'm experiencing the same problem with `find()`, `findOne()` and `findOneOrFail()`.

**MSSQL:** 2008 R2
**TypeORM:** 0.2.18

Stack trace:

```
query: SELECT "location"."Id" AS "location_Id", "location"."Name" AS "location_Name" FROM "MyDB"."dbo"."Locations" "location" ORDER BY "location"."Name" ASC OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY
PlatformTools.ts:220
query failed: SELECT "location"."Id" AS "location_Id", "location"."Name" AS "location_Name" FROM "MyDB"."dbo"."Locations" "location" ORDER BY "location"."Name" ASC OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY
PlatformTools.ts:224
error:
PlatformTools.ts:224
RequestError: Invalid usage of the option NEXT in the FETCH statement.
PlatformTools.ts:224
QueryFailedError: Error: Invalid usage of the option NEXT in the FETCH statement.
    at new QueryFailedError (c:\dev\repos\myproj\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at c:\dev\repos\myproj\node_modules\typeorm\driver\sqlserver\SqlServerQueryRunner.js:232:61
    at c:\dev\repos\myproj\node_modules\mssql\lib\base.js:1346:25
    at Request.userCallback (c:\dev\repos\myproj\node_modules\mssql\lib\tedious.js:671:15)
    at Request.callback (c:\dev\repos\myproj\node_modules\tedious\lib\request.js:37:27)
    at Connection.endOfMessageMarkerReceived (c:\dev\repos\myproj\node_modules\tedious\lib\connection.js:2104:20)
    at Connection.dispatchEvent (c:\dev\repos\myproj\node_modules\tedious\lib\connection.js:1084:36)
    at Parser.<anonymous> (c:\dev\repos\myproj\node_modules\tedious\lib\connection.js:914:14)
    at Parser.emit (events.js:196:13)
    at Parser.<anonymous> (c:\dev\repos\myproj\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
```

**Comment by vlapo** [comment] 2019-06-06 20:00
Sorry boys but SQL Server 2008 is not even supported by Microsoft. I cannot even find documentation but it is possible that `OFFSET/FETCH` functionality was introduced in SQL server 2011. Right now we do not have possibility to generate different SQL syntax for different versions of DB. So I am really sorry but this will not be fixed in any reasonable time. Maybe in 0.4.0 we will introduce some way how to support more DB versions in cases like this.

**Comment by eaverdeja** [comment] 2019-06-07 12:16
@vlapo thank you for communicating this! Opensource is hard and communication is key

**Comment by dmastag** [comment] 2019-11-13 04:49
How about running the following before find(), findOne() and findOneOrFail()in SQL Server sound?
`SELECT @@VERSION AS 'SQL Server Version';  `

Is that something worth to do in a MR?

**Comment by imnotjames** [comment] 2020-10-11 10:00
The problem is that we don't have server specific dialect, so adding that is one thing... Then updating all of our dialect to ensure support is a whole different task.

You're always welcome to open a PR with new functionality but because this isn't very actionable I'll be closing it.

**Closed by imnotjames** 2020-10-11 10:00 UTC
Labels: driver: mssql

**Comment by CristianPumaES6** [comment] 2021-12-08 01:47
2021 same mistake

**Comment by wild-sky** [comment] 2022-04-15 05:30
2022 same mistake

**Comment by xoapit** [comment] 2022-10-12 15:04
Does any workaround?
