### ISSUE TITLE
AfterUpdate is being executed not after update, but during it

### ISSUE THREAD

**Issue by DTX-92** [typeorm/typeorm#6122] opened 2020-05-24 19:26 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` 0.2.25
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
class Test {
   @PrimaryGeneratedColumn()
   id!: number

   @Column({ nullable: true })
   value!: number

   @AfterUpdate()
   onSave2() {
      onSave()
   }
}

async function onSave() {
   let rep = (await db.getConnection()).getRepository(Test)

   let res = await rep.createQueryBuilder('t').select(`t.value`, 'value').getRawMany()

   console.log('On save', res[0].value)
}
export default Test
```

```
router.get('/test', async (req: Request, res: Response) => {
   let rep = (await db.getConnection()).getRepository(Test)
   let t = await rep.findOne({})
   if (!t) t = new Test()
   t.value = Math.round(Math.random() * 1000)
   console.log('New value: ', t.value)
   await rep.save(t)
   console.log('Saved')

   return res.send('OK')
})
```

After 4 requests result is:

![image](https://user-images.githubusercontent.com/20479161/82763048-58cfd380-9e0d-11ea-91fa-ffbf8af172da.png)

2nd request and 4th request  execute AfterUpdate not after it, so it shows old value.

**Comment by chillinski** [comment] 2020-07-27 09:03
We observed this issue in our system as well.
Here is the code we use to react on the update of an entity in the database:
`import { EntitySubscriberInterface, EventSubscriber, UpdateEvent } from "typeorm";
import { Item } from "../models";
import { Publisher } from "./publisher";

@EventSubscriber()
export class ItemSubscriber implements EntitySubscriberInterface<Item> {

  constructor(private _publisher: Publisher) {
  }

  public listenTo() {
    return Item;
  }


  public async afterUpdate(event: UpdateEvent<Item>): Promise<Item> {
    // >>> this is the line where the old data is injected and sent out
    await this._publisher.publish(`item.changed.${event.databaseEntity.id}`, JSON.stringify(event.databaseEntity));
    return event.databaseEntity;
  }

  /*
   ... some more code ...
  */

}
`

**Comment by ahsan-babar** [comment] 2020-10-30 11:06
@DTX-92  @chillinski 
This situation can be avoided for now by committing the running transaction (say "T-1") and starting a new transaction (say "T-2") right after it. The routine/regular execution typeorm will automatically commit "T-2" as it's going to expect a transaction in it's execution flow.
Reference:  [https://stackoverflow.com/questions/62887344/queries-in-afterupdate-are-not-working-as-expected-in-typeorm/62893788#62893788](url)

@pleerock / Typeorm Team
However, there should be some more [entity listeners](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#entity-listeners-and-subscribers) supporting event emission after the transaction 
has been committed. Also it should explicitly be mentioned in the documentation that these events are fired during transaction.

**Comment by tataqwerty** [comment] 2021-04-15 07:38
https://www.npmjs.com/package/typeorm-transactional-cls-hooked

**Comment by Kagu-chan** [comment] 2021-08-05 09:18
This issue is not only related to the `postgres` driver - we can reproduce this using `mysql` as well, especially when we have higher server load.

@pleerock / TypeORM team - can we expect a fix to this or will this be handled in `next`?

**Comment by imnotjames** [comment] 2021-08-05 09:28
This looks like an issue with your code rather than an issue with TypeORM.

Mark `onSave2` to be `async` and `await` the async function you're calling or `return onSave()` so you return the function.

Either of those will prevent this from being out of order because the code you're writing does not attempt to await the asynchronous inner function.

**Comment by imnotjames** [comment] 2021-08-05 09:28
> This issue is not only related to the `postgres` driver - we can reproduce this using `mysql` as well, especially when we have higher server load.
> 
> @pleerock / TypeORM team - can we expect a fix to this or will this be handled in `next`?

I cannot replicate any issue directly in typeorm.

**Closed** 2021-08-05 09:28 UTC
Labels: bug, driver: postgres

**Comment by Kagu-chan** [comment] 2021-08-05 09:55
This code is what we use to mark our entities as subscribers and publish changes to our cluster, where they get picket up and handled (e.g. other process, but same database)
```typescript
export abstract class SubscriberBase<T extends BaseEntity> implements EntitySubscriberInterface<T> {
  abstract cTor: new (...args: any[]) => T;
  abstract typeName: string;
  abstract notifyCreate: boolean;
  abstract notifyUpdate: boolean;
  abstract notifyRemove: boolean;

  public listenTo(): new (...args: any[]) => T {
    return this.cTor;
  }

  public afterUpdate(event: UpdateEvent<T>): void {
    if (this.notifyUpdate) {
      this.notify(event.entity, 'updated');
    }
  }
  // ...

  protected notify(entity: T, event: 'created' | 'updated' | 'removed'): void {
    if (entity) {
      ClusterMessagesService.getInstance().emitToRandomWorker(
        `${this.typeName}-${event}`,
        entity.id,
        entity,
      );
    }
  }
}

@EventSubscriber()
export class InvoicePrintTaskSubscriber extends SubscriberBase<InvoicePrintTask> {
  public cTor = InvoicePrintTask;
  public typeName = 'invoice-print-task';
  public notifyCreate = false;
  public notifyUpdate = true;
  public notifyRemove = false;
}

@Entity('invoicePrintTasks')
export class InvoicePrintTask extends BaseEntity{
  // normal boring columns here[];

  /**
   * Set task status and save record
   *
   * @param status
   * @returns {InvoicePrintTask}
   */
  public async setStatus(status: InvoicePrintTaskStatus): Promise<InvoicePrintTask> {
    this.status = status;

    return this.save();
  }

  public async setFailed(): Promise<InvoicePrintTask> {
    return await this.setStatus(InvoicePrintTaskStatus.FAILED);
  }

  public async setDone(): Promise<InvoicePrintTask> {
    return await this.setStatus(InvoicePrintTaskStatus.DONE);
  }
}
```

When listening to the emitted event, we get the updated entity (last parameter in notify) and the id of this entity.
```typescript
@Injectable()
export class InvoicePrintTaskHandlerService {
  constructor(
    private readonly log: LoggingService,
    private readonly clusterMessages: ClusterMessagesService,
    @InjectRepository(InvoicePrintTask)
    private readonly invoicePrintTaskRepository: Repository<InvoicePrintTask>,
  ) {
    this.clusterMessages.listen('invoice-print-task-updated', this.onTaskUpdated.bind(this));
  }

  private async onTaskUpdated(pid: number, id: number, entity: DeepPartial<InvoicePrintTask>) {
    const task = await this.invoicePrintTaskRepository.findOne(id, {
      relations: ['invoicePackage'],
    });

    if (task.status !== entity.status) {
      // Here the CHANGED value is only updated in entity, but not in the loaded task variable
      // We use and AWAIT entity.setDone() or entity.setFailed()
    }
```

The issue happens under server load, where a `TRANSACTION COMMIT` takes up to two seconds.
We do not manually use transactions in this case, so typeorm does this by its own. But i dare to assume that this long running commit command may cause the issue itself - if the subscriber is executed before the underlying transaction commits, then this should be stated in the docs

**Comment by imnotjames** [comment] 2021-08-05 09:59
The after update happens after the update.  Not after a transaction committing the update.

Where does typeorm implicitly include transactions?

**Comment by imnotjames** [comment] 2021-08-05 11:47
If it only happens under load situations I have a feeling it's not directly a TypeORM issue because the way we handle these listeners is incredibly simple.  We don't do anything special aside from async & await.

This is possibly caused by the fact that we compile typescript down to an old version of javascript & the tslib shim does some magic to make async functions operate.  The more likely case is that something's up with the way you're doing `ClusterMessagesService`.

I'm not 100% ruling out something that TypeORM is doing is causing this.  I've just not seen anything that I could really investigate further that would help determine that.

**Comment by y-nk** [comment] 2021-08-28 11:50
I've similar issues, related to Views. I'm having an Entity A, and a View which is an expression of this entity (to count the number of entities depending on the value of an enum column).

on @AfterUpdate() i'm trying to get the view, but the old view not the new one 😓
