### ISSUE TITLE
Update method always return empty Array

### ISSUE THREAD

**Issue by isaaxite** [typeorm/typeorm#3060] opened 2018-11-07 03:16 UTC
**Issue type:**
·
[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ x ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

hello, typeorm team!

when i use the method( update ) to update my data in the table. i found that this method is always return a empty array, i hope it can return the number of updated rows.

this is the current return:
```js
UpdateResult { generatedMaps: [], raw: undefined }
```
i come here because i want to know how can i get number of updated rows, or tell me why!

thanks~

**Comment by billyjov** [comment] 2019-01-29 15:51
is there some workaround for this issue ?

**Comment by issaxite** [comment] 2019-02-03 03:58
@billyjov use the "save" method!

**Comment by pleerock** [comment] 2019-02-03 17:56
no save won't return number of updated rows. This is a feature request, so feel free to contribute

**Comment by icedir** [comment] 2019-04-03 12:14
still doesn't fix? I'm disconcerted by this 
`await entityManager
                .createQueryBuilder()
                .update(Wallet)
                .set({
                    frozen: () => {
                        return `"frozen" + ` + amount;
                    }
                })
                .where("id = :fromId", { fromId: fromWallet.id })
                .execute();`
Its always return `{"generatedMaps":[],"raw":[]}`

**Comment by egoarka** [comment] 2019-08-28 04:08
I guess you can use `returning` clause to get your newly updated rows.


```
getRepository(YourEntity)
	.update(YourEntity)
	.set(...)
	.where(...)
	.returning('*') 
	.execute();
```

**Comment by kennasoft** [comment] 2020-06-05 12:43
> 	.returning('*')

This does not seem to work for me on typeorm@0.2.24. Update method does not accept 1 argument

**Comment by imnotjames** [comment] 2020-10-17 08:34
Duplicate of #2415

**Closed by imnotjames** 2020-10-17 08:34 UTC
Labels: bug, driver: oracle, enhancement
