### ISSUE TITLE
Pass template to use when generating migrations

### ISSUE THREAD

**Issue by jleck** [typeorm/typeorm#6493] opened 2020-07-30 09:14 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have quite a strict eslint, which requires public/private on all properties, and also the naming of files in kebab case. It would be great if we could set the template and name to use when generating or creating a migration. I would be willing to create PR is this sounds like something useful.

**Comment by rubiin** [comment] 2020-08-05 16:30
sure do.

**Comment by rubiin** [comment] 2020-08-05 16:31
for reference , check this: https://stackoverflow.com/questions/47814537/how-to-perform-a-like-query-typeorm

**Comment by imnotjames** [comment] 2020-10-18 05:03
Duplicate of #1316

**Closed by imnotjames** 2020-10-18 05:03 UTC
Labels: comp: cli tools, comp: migrations, driver: postgres, new feature
