### ISSUE TITLE
@AfterInsert() / @BeforeInsert() can only be invoked once per server re-start

### ISSUE THREAD

**Issue by j-gibweb** [typeorm/typeorm#5134] opened 2019-11-23 22:19 UTC
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm testing this against my local mysql@5.7 db as well as serverless aurora via `typeorm-aurora-data-api-driver` (for what thats worth).

I'm also running this code via `serverless-offline`

The before/after-insert hooks appear to only run if they are the very first invocation made by the DB  runner - all subsequent actions work correctly, selecting / creating / updating / deleting - but they skip these hooks.

Also I've tested this via both ActiveRecord and Data Mapper approaches and the result appears to be the same.

example code

```
@Entity()
export class MyClass extends BaseEntity {
  @PrimaryGeneratedColumn("uuid")
  @Generated("uuid")
  id: string;

  @Column()
  name: string;

  @AfterInsert()
  doSomething() {
    console.log("this only runs on the first invocation", this);
  }
}
```

**Comment by 592da** [comment] 2020-01-03 21:44
Also experiencing this issue, any workaround ???
looks likes this repo is not maintained anymore...

**Comment by 592da** [comment] 2020-01-04 10:06
hope it will help you as well,
when running serverless offline with 
```
serverless offline --skipCacheInvalidation
```

solves the problem locally, not sure about production yet.

**Comment by didac-wh** [comment] 2020-01-10 17:26
@592da It works indeed.
However, for local serverless development through webpack, apparently that option makes the live-reload ignore the changes, forcing you to manually restart the server.

**Comment by 592da** [comment] 2020-01-12 08:59
@didac-wh If you find a solution I will be happy for an update :)
meanwhile, I refactor a lot of code to migrate my service to serverless and call those callbacks manually :(

**Comment by didac-wh** [comment] 2020-01-12 15:59
@592da Haven't tested it much but I replaced @BeforeInsert for the entity constructor, so when I do a "new MyEntity()" the values I wanted were automatically filled (in my case, a createdAt field).

**Comment by 592da** [comment] 2020-01-12 22:23
Thanks @didac-wh but there are other triggers that I am using that cannot use the constructor, unfortunately. 

@pleerock  any thoughts?
entity listeners are not triggered at all... :(

**Comment by imnotjames** [comment] 2020-10-09 21:13
It'd help to have a reproducible example - such as a repository or otherwise - so we can help debug this.

Unfortunately, none of the maintainers use `serverless-offline` and we don't really test against it.  Some of the esoteric mechanisms  for running code have bizarre interactions or load things incorrectly.

It's possible that this is related to #5676 

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2020-10-21 06:45
This has been more than 6 months without an update and no way to reproduce - closing it out.  Probably similar to #5676

**Closed by imnotjames** 2020-10-21 06:45 UTC
Labels: bug, comp: subscribers and listeners, driver: mariadb, driver: mysql, needs more info

**Comment by filipw01** [comment] 2020-12-09 08:37
Please note, that in new version of serverless-offline `--skipCacheInvalidation` does not exist use  `--allowCache` instead
