### ISSUE TITLE
Using FindOperator with QueryBuilder.where and transformer

### ISSUE THREAD

**Issue by fan-tom** [typeorm/typeorm#6470] opened 2020-07-27 09:08 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create an entity with nullable filed with transformer, for example from/to Date:
```
export const dateTransformer = {
  to: (value: Date | null) => {
    return isDefined(value) ? value.toISOString() : null;
  },

  from: (value: string | null) => {
    return isDefined(value) ? new Date(value) : null;
  },
} as const;

class Person {
    @Column({ name: 'expire_at', type: 'timestamp', nullable: true, transformer: dateTransformer })
  birhtDay!: Date | null;
}
```
Try to find persons with undefined birthday, using query builder:
```
const persons = await getRepository(Person).createQueryBuilder()
.select(...)
.where({ birthDay: IsNull() })
.getAll();
```
Get:
```
TypeError: value.toISOString is not a function
```
because transformer is applied to `FindOperator` instance. From code I can see that value from where conditions is extracted before recognizing that it is `FindOprtator`, so transformer is applied to wrong value:
```
QueryBuilder.prototype.computeWhereParameter = function (where) {
...
    var parameterValue = column.getEntityValue(where, true); // here we get value from where condition object, applying transformers, if any
    var parameterName = "where_" + whereIndex + "_" + propertyIndex + "_" + columnIndex;
    var parameterBaseCount = Object.keys(_this.expressionMap.nativeParameters).filter(function (x) { return x.startsWith(parameterName); }).length;
    if (parameterValue === null) {
        return aliasPath + " IS NULL";
    }
    else if (parameterValue instanceof FindOperator_1.FindOperator) { // here we recognize that condition object value was FindOperator, but it is too late
...
```

**Comment by imnotjames** [comment] 2020-10-16 06:29
Shouldn't your transformer handle the fact that it's being passed a `FindOperator`?

**Comment by imnotjames** [comment] 2020-10-16 06:29
Duplicate of #4399

**Closed by imnotjames** 2020-10-16 06:29 UTC
Labels: bug, driver: postgres
