### ISSUE TITLE
Let users worry about dotenv instead of having a dynamic dependency on it

### ISSUE THREAD

**Issue by kwasimensah** [typeorm/typeorm#5884] opened 2020-04-15 22:23 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Why does typeorm have a runtime dependency on dotenv, instead of relying on users to load it into process.env on their own?

For context, I'm trying to bundle my node app with webpack and running into https://github.com/typeorm/typeorm/issues/3152 and was wondering why this was here at all.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by Andreyco** [comment] 2020-05-03 22:44
I can relate with original poster. In real world you usually do not inject env variables thru .env file (or any file versioned in repository). 
Secrets should and are injected via some kinds of services/system higher in a hierarchy.

**Comment by Andreyco** [comment] 2020-05-04 20:20
I hit this issue again

What docs say:
> Note that Typeorm will use the first valid method found and will not load the others. For example, Typeorm will not load the ormconfig.[format] files if the configuration was found in the environment.

Now imaging this is your .env file:
```shell
TYPEORM_CONNECTION=postgres
TYPEORM_URL=postgres://hostname:5432/database
# remaining env declaration but none of TYPEORM_*
```
This is completely valid use case, why would you configure CLI that is not used in prod using env variables?

You would expect Typeorm picks `ormconfig.{ext}` but no. If either `TYPEORM_CONNECTION` or `TYPEORM_URL` is found in environment it just stops. See [source code](https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/connection/ConnectionOptionsReader.ts#L107-L127) 

I strongly believe Typeorm responsibility is not to load environment configuration, rather read available environment and load ormconfig that providing minimal necessary configuration.

I expect:
- system or user to supply partial configuration via environment
- environment configuration will override whatever is specified in ormconfig file
- Typeorm will merge environment configuration into output of ormconfig file

**Comment by bttf** [comment] 2021-02-14 15:00
I agree with the above. Another aspect of this problem has to do with migrations.

Currently I'm utilizing `process.env` at runtime by defining my TypeORM config via `createConnection` function (i.e. in code). This is letting me use environment variables exposed to the node process at run time, which can change based on environment (development vs production).

However it seems that to run migrations I need to have `ormconfig.json` defined at project root, which doesn't seem to have a way of interpolating process-level environment variables in the manner that I'm doing w/ `createConnection`

**Comment by imnotjames** [comment] 2021-07-03 06:58
Duplicate of #3567

**Closed by imnotjames** 2021-07-03 06:58 UTC
Labels: driver: postgres, new feature
