### ISSUE TITLE
Empty string in findOne

### ISSUE THREAD

**Issue by dkirchhof** [typeorm/typeorm#2990] opened 2018-10-25 10:16 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

If i pass an empty string to the findOne method, it will ignore the param and doesn't use a where clause in the query. 

example:
- `repo.findOne("foo")` returns `SELECT ... FROM ... WHERE id = ? -- PARAMETERS: ["foo"]`
- `repo.findOne("")` returns `SELECT ... FROM ...` (here without WHERE and PARAMETERS)

Is it intended? Probably it's not very usefull to set an empty string as a primary key for one of the entities, but in some cases, this behaviour will produce heavy problems (eg. passing an empty string by mistake to the server, typeorm will return the first entity of the table).

**Comment by riadhriadh** [comment] 2018-10-25 11:32
example
```
findOnebyName(name: string): Promise<any> {
    return (await this.footRepository.find({ name }))[0];
  }
```

**Comment by imnotjames** [comment] 2020-10-12 09:30
Duplicate of #3416

**Closed by imnotjames** 2020-10-12 09:30 UTC
Labels: driver: mssql, question
