### ISSUE TITLE
Column not renamed when schema is set in Postgres

### ISSUE THREAD

**Issue by ardyfeb** [typeorm/typeorm#7867] opened 2021-07-08 17:24 UTC
## Issue Description
Automatic syncronization not detect column name or type was renamed or changed

### Expected Behavior
Should detect change and syncronize with database

### Actual Behavior
Typeorm not detecting column name / type was changed. But syncronize work if create new entity (typeorm creating new table)

### Steps to Reproduce
Typeorm Config
```ts
{
  host: process.env.PG_HOST,
  port: process.env.PG_PORT,
  username: process.env.PG_USERNAME,
  password: process.env.PG_PASSWORD,
  database: process.env.PG_DATABASE,
  schema: process.env.PG_SCHEMA
  type: 'postgres',
  logging: ['error', 'migration', 'schema', 'query'],
  namingStrategy: new SnakeNamingStrategy(),
  synchronize: this.configService.isDevelopment(),
  logger: 'advanced-console',
  migrationsTransactionMode: 'each',
  entities: [
    __dirname + '/../**/*.entity.{ts,js}',
  ]
}

```
Entity
```ts
export enum CourierClass {
  SAMEDAY = 'same-day',
  NEXTDAY = 'next-day',
  REGULER = 'reguler',
}

@Entity()
export class Courier {
  @PrimaryColumn()
  code: string

  @Column()
  name: string

  @Column('enum', { enum: CourierClass })
  class: CourierClass

  @Column()
  cashless: boolean

  @Column()
  logistic: string
}
```

Edit:
Minimal repository to reproduce https://github.com/ardyfeb/typeorm-syncronize-bug

- Run `yarn run start` it will syncronize first time
- Then try change some column, `name` -> `name_changed`
- Run `yarn run start` again to syncronize changes
- Updated column will not synced with database

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Linux    |
| Node.js version     | v16.3.0 | 
| Typescript version  | ^0.2.34 | 
| TypeORM version     | ^4.3.5 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by imnotjames** [comment] 2021-07-09 06:11
We have tests that confirm that this does work.  Can you create a more complete example + steps?

I even took your entity & created a local environment for it.

**Comment by ardyfeb** [comment] 2021-07-10 17:41
@imnotjames 
Here minimal repository to reproduce https://github.com/ardyfeb/typeorm-syncronize-bug

Try changing column `name` on `src/entity/user.entity.ts`

**Comment by imnotjames** [comment] 2021-07-11 01:55
I did.  I can't replicate.

I started the application via `npm install`

I also changed it to be `sqlite` instead of `postgres`.

```
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    TypeOrmModule.forRoot(
      {
        database: 'test.db',
        type: 'sqlite',
        synchronize: true,
        logging: ['error', 'migration', 'schema', 'query'],
        logger: 'advanced-console',
        migrationsTransactionMode: 'each',
        entities: [
          __dirname + '/**/*.entity.{ts,js}',
        ]
      }
    )
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Then `npm run start:dev`

The first logs I got were as follows:

```
[9:53:01 PM] Starting compilation in watch mode...

[9:53:04 PM] Found 0 errors. Watching for file changes.

[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [NestFactory] Starting Nest application...
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +55ms
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('user')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
creating a new table: user
query: CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL)
query: COMMIT
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +41ms
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 684072  - 07/10/2021, 9:53:04 PM     LOG [NestApplication] Nest application successfully started +2ms
```

I changed the entity as follows:

```
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name_two: string
}
```

This caused a reload with the following logs

```
[9:54:07 PM] File change detected. Starting incremental compilation...

[9:54:07 PM] Found 0 errors. Watching for file changes.

[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [NestFactory] Starting Nest application...
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +64ms
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('user')
query: PRAGMA table_info("user")
query: PRAGMA index_list("user")
query: PRAGMA foreign_key_list("user")
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
renaming column "name" in to "name_two"
query: CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name_two" varchar NOT NULL)
query: INSERT INTO "temporary_user"("id", "name_two") SELECT "id", "name" FROM "user"
query: DROP TABLE "user"
query: ALTER TABLE "temporary_user" RENAME TO "user"
query: COMMIT
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +50ms
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [RoutesResolver] AppController {/}: +5ms
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 684208  - 07/10/2021, 9:54:08 PM     LOG [NestApplication] Nest application successfully started +2ms
```

As you can see, it reloaded and updated everything as expected.

**Comment by imnotjames** [comment] 2021-07-11 02:00
Let me know if there's something I didn't do correctly - but I can't seem to replicate & everything seems to be working.

For now I'm going to be closing this out but please feel free to re-open if you see something I did that's not quite right.

**Comment by ardyfeb** [comment] 2021-07-12 09:12
@imnotjames 

yes it works on me when sqlite, but not postgres

**Comment by ardyfeb** [comment] 2021-07-12 17:40
Downgrading to `0.2.32` temporary fix the problem. I think the bug caused by driver, which works with another driver but not postgres

**Comment by imnotjames** [comment] 2021-07-12 19:58
Perfect - I am able to replicate this!

It's a change made in https://github.com/typeorm/typeorm/commit/7eb032705912cbf4ee340ed9e49970d0f6e23714

If you omit the schema the sync works as expected.   If you supply it - like in your example repo - it will not run the sync.

**Comment by imnotjames** [comment] 2021-07-12 19:58
* We need to get to the bottom of this for sure.
* We reaaaaally need to create a test that would have caught this under the functional tests somewhere.

**Comment by imnotjames** [comment] 2021-07-13 05:47
Digging more, this is a huge pain.

The way the table name is generated is incredibly inconsistent which is causing this issue.  `table.name` gets set up as `foo` but then it gets compared against `metadata.tablePath` which is `bar.foo`. ):

I'm going to make a consistent `path` on the `Table` class which is always populated with the fully-qualified path name.  This can be used for our internal comparisons.  I think it will also fix a NUMBER of the other synchronization bugs we have.  There's also a few other places where I think this will help.

**Comment by imnotjames** [comment] 2021-07-13 17:33
Heavily related: #5304

**Closed** 2021-08-24 21:49 UTC
Labels: bug, driver: postgres

**Comment by imnotjames** [comment] 2021-08-24 22:41
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
