### ISSUE TITLE
Many to many query wrong column

### ISSUE THREAD

**Issue by zfben** [typeorm/typeorm#5933] opened 2020-04-22 12:31 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 3 tables and 2 entity, like below:
```sql
CREATE TABLE "public"."item_items_sub_categories" (
    "id" varchar NOT NULL,
    "itemId" varchar NOT NULL,
    "subcategoryId" varchar NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."item_items" (
    "id" varchar NOT NULL,
);

CREATE TABLE "public"."item_subcategories" (
    "id" varchar NOT NULL,
);
```
```typescript
@Entity('item_items')
export class ItemItem extends BaseEntity {
  @Column({primary: true})
  id: string;

  @ManyToMany(() => ItemSubcategory, subCategory => subCategory.items)
  @JoinTable({
    name: 'item_items_sub_categories',
    joinColumn: {
      name: 'itemId',
      referencedColumnName: 'id'
    },
    inverseJoinColumn: {
      name: 'subcategoryId',
      referencedColumnName: 'id'
    }
  })
  subCategories: Promise<ItemSubcategory[]> = Promise.resolve([]);
}

@Entity('item_subcategories')
export class ItemSubcategory extends BaseEntity {
  @Column({primary: true})
  id: string;

  @ManyToMany(() => ItemItem, item => item.subCategories)
  items: Promise<ItemItem[]>
}
```

then i query like below:

```typescript
ItemItem.find({
  relations: ['subCategories']
});
```

it throw error: `column ItemItem.itemId does not exist`.

the sql log like `SELECT DISTINCT "distinctAlias"."ItemItem_id" as "ids_ItemItem_id", "distinctAlias"."ItemItem_id" FROM (SELECT "ItemItem"."id" AS "ItemItem_id", "ItemItem__subCategories"."id" AS "ItemItem__subCategories_id", "ItemItem"."itemId" FROM "item_items" "ItemItem" LEFT JOIN "item_items_sub_categories" "ItemItem_ItemItem__subCategories" ON "ItemItem_ItemItem__subCategories"."itemId"="ItemItem"."id" LEFT JOIN "item_subcategories" "ItemItem__subCategories" ON "ItemItem__subCategories"."id"="ItemItem_ItemItem__subCategories"."subcategoryId") "distinctAlias"`

**Comment by ahsanghalib** [comment] 2020-04-22 22:21
Why are you doing this with Promise? 
` subCategories: Promise<ItemSubcategory[]> = Promise.resolve([]);`
instead of 
` subCategories: ItemSubcategory[]`

**Comment by zfben** [comment] 2020-04-23 01:46
@ahsanghalib i need lazy load relations.

**Comment by Vandell63** [comment] 2020-04-23 11:25
Hey,
I try in my side and it work properly. I assume that you do the migration properly.
The only thing that's different is the decorator for the primary column. In typeorm they specified more the `@PrimaryGeneratedColumn()` instead of the `Column({primary: true})`. Can you give a try with it ?

**Comment by imnotjames** [comment] 2020-10-10 09:28
Duplicate of #1668

**Comment by imnotjames** [comment] 2020-10-10 09:28
Sure looks like it at least.  Let me know if not and I can reopen.

**Closed by imnotjames** 2020-10-10 09:28 UTC
Labels: bug, driver: postgres
