### ISSUE TITLE
Unable to resolve module `url` from `node_modules/typeorm/browser/util/OrmUtils.js`: url could not be found within the project.

### ISSUE THREAD

**Issue by FottyM** [typeorm/typeorm#6216] opened 2020-06-06 17:38 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```bash
Unable to resolve module `url` from `node_modules/typeorm/browser/util/OrmUtils.js`: url could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

ABI37_0_0RCTFatal
__37-[ABI37_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

**Comment by Kolisium** [comment] 2020-06-08 12:48
`yarn add url` solves this issue

**Comment by oleksandr-dziuban** [comment] 2020-06-11 20:58
@Kolisium It should be added to typeorm dependencies then..

**Comment by oleksandr-dziuban** [comment] 2020-06-11 20:59
Same issue here from version 0.2.25. Please check it

**Comment by maixuanhan** [comment] 2020-07-29 17:31
I'm facing same issue with version 0.2.25
Version 0.2.0 was working fine

**Comment by Rafatcb** [comment] 2020-08-06 13:31
Same issue as https://github.com/typeorm/typeorm/issues/6142, seems to be fixed in https://github.com/typeorm/typeorm/pull/6145

**Comment by imnotjames** [comment] 2020-09-30 03:15
Closing this as it's a duplicate of #6142

**Closed by imnotjames** 2020-09-30 03:15 UTC
Labels: duplicate
