### ISSUE TITLE
How to delete in Closure table of Tree Entities? 

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#3988] opened 2019-04-13 11:25 UTC
**Issue type:**
[x] question

**Database system/driver:**
[x] `mysql` / `mariadb`

**TypeORM version:**
[x] `@next`

```
@Column({
    length: 500,
    default: '',
  })
  name: string

@TreeParent()
  parent: Comment

  @TreeChildren({
    cascade: true,
  })
  children: Comment[]
```
above code, I want to delete a record, but error report: ` a foreign key constraint fails...`，and how to delete in this case ?

**Comment by Kononnable** [comment] 2019-04-20 16:53
Is this a duplicate of #193? I think you want to achieve the same thing as described there.

**Closed** 2021-05-18 21:47 UTC
Labels: comp: tree tables, driver: mariadb, driver: mysql, question
