### ISSUE TITLE
bigNumberStrings - fails to start with "cannot drop index" error

### ISSUE THREAD

**Issue by 4lki** [typeorm/typeorm#4132] opened 2019-05-13 07:31 UTC
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `mysql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
With synchronize: true and bigNumberStrings : false in ormconfig i get this error on every start after initial db setup. 

QueryFailedError: ER_DROP_INDEX_FK: Cannot drop index 'REL_517fda2a813ace7741c0463239': needed in a foreign key constraint

The relation he moans about is OneToOne, nothing special and no big numbers involved.  
After deleting the Foreign Key by hand it runs once without error. On following starts the error returns. 

When setting bigNumberStrings to true the error is gone. 

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment] 2019-05-26 11:14
Could you provide a reproduction data? Otherwise we won't be able to help.

**Comment by jeffersontpadua** [comment] 2019-07-07 16:01
I have the same issue when using bigNumberStrings and synchronize at the same time. TypeORM tries drop every single Unique Index in the application.

I tried removing them myself, but then it goes on trying to deleting foreign key indexes. 

For me, it happens everytime, so it's just a matter of enabling the two mentioned options.

By having a look at the queries being executed, it seems that TypeORM is looking for something in the "typeorm_metadata" table, which is not populated. Then it begins to drop everything. Here's the query I'm talking about:

SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'my_database' AND `TABLE_NAME` = 'typeorm_metadata'

Any ideas on what to do about this?

**Comment by Kononnable** [comment] 2019-08-31 12:18
Closing as no reproduction data was posted.
We can't just guess what's wrong from thin air. There might be a bug, but there is no way to know that just from description.

**Closed by Kononnable** 2019-08-31 12:18 UTC
Labels: needs failing tests

**Comment by Ami777** [comment] 2019-09-01 10:27
Tested on 0.2.7, 0.2.16-rc.1, 0.2.18. Steps to reproduce are very easy:

`typescript

@Entity()
export class One {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToOne(type => Two, second => second.first)
  @JoinColumn()
  second: Two;
}

@Entity()
export class Two {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToOne(type => One, second => second.second)
  first: One;
}
`

It works everytime. Unless you set `"bigNumberStrings": false` in `ormconfig.json`.

Then, first time this code will work, but then it will fail everytime like that:

> query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'crowdstock' AND `TABLE_NAME` = 'typeorm_metadata'
query: DROP INDEX `REL_53754e277686ad6243121251eb` ON `one`
query failed: DROP INDEX `REL_53754e277686ad6243121251eb` ON `one`
error: { Error: ER_DROP_INDEX_FK: Cannot drop index 'REL_53754e277686ad6243121251eb': needed in a foreign key constraint
    at Query.Sequence._packetToError (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\mysql\lib\Connection.js:200:25)
    at MysqlQueryRunner.<anonymous> (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\src\driver\mysql\MysqlQueryRunner.ts:155:36)
    at step (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\tslib\tslib.js:133:27)
    at Object.next (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\tslib\tslib.js:114:57)
    at fulfilled (C:\Users\Ami777\Desktop\PROJEKTY\Crowdstock\pst-api-be\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sqlMessage:
   'Cannot drop index \'REL_53754e277686ad6243121251eb\': needed in a foreign key constraint',
  sqlState: 'HY000',
  index: 0,
  sql: 'DROP INDEX `REL_53754e277686ad6243121251eb` ON `one`' }
query: ROLLBACK
[Nest] 18096   - 2019-9-1 12:26:48 PM   [TypeOrmModule] Unable to connect to the database. Retrying (8)... +3481ms

**Comment by andy90rus** [comment] 2019-10-16 08:49
I had the same issue, but i found solution for myself. Like in example above of @Ami777 I added @Index('REL_name', ['attribute_name'],{ unique: false }) for all entity like this:

@Entity()
@Index('REL_8f2bb52a4384d2d5f1ff59fb9e', ['second'], { unique: false })
export class One {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToOne(type => Two, second => second.first)
  @JoinColumn()
  second: Two;
}

Maybe it will helpfully for somebody.

**Comment by deeptechuz** [comment] 2019-11-07 10:25
Facing same issue any solution??

**Comment by tiagomnferreira-mzt** [comment] 2021-06-23 13:53
Same issue here

**Comment by imnotjames** [comment] 2021-06-23 18:16
If you have this issue, please open a new issue with a reproducible example.

---
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by NourMaherT** [comment] 2022-04-23 10:21
It worked for me when I removed   "synchronize": true from ormconfig.json file!
