### ISSUE TITLE
TypeOrm relation very slow

### ISSUE THREAD

**Issue by Parilar** [typeorm/typeorm#5040] opened 2019-11-05 14:46 UTC
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello,
i got a recipe database and a user table with saved recipes (30 per User).
Now i try to get data with

```
getRepository(UserRecipes)
                .find({
                    where: { user: userId },
                    relations: [
                        'recipe_morning',
                        'recipe_morning.recipe',
                        'recipe_morning.ingredients',

                        'recipe_noon',
                        'recipe_noon.recipe',
                        'recipe_noon.ingredients',

                        'recipe_evening',
                        'recipe_evening.recipe',
                        'recipe_evening.ingredients',

                        'recipe_snack',
                        'recipe_snack.recipe',
                        'recipe_snack.ingredients'
                    ]
                })
```

The query runs 30 times. it takes over 2.5 seconds to finish.
Is there a better solution to handle this in TypeORM

**Comment by Mando75** [comment] 2019-11-12 07:00
If you have all the user ids up front and would like to make one query, TypeORM provides an `In()` function that allows you to pass an array of ids.
```ts
import { In } from 'typeorm'

getRepository(UserRecipes)
  .find({
    where: { user: In(userIds) },
   relations: [ 
    'recipe_morning',
    // .. etc 
    ]
})
```
You may also want to think about not loading in so many nested relations at once. Executing that many joins can be really slow, especially as you continue to grow the number of recipes. 
Optimizing your database for these kinds of operations is outside of the scope of what TypeORM can really do. If you would like to learn more about how to optimize you database queries, take a look at SQL Performance Explained. It is a great read for any developer who wants to learn the essentials of what they need to do to execute performant database queries without getting bogged down in super technical details and heavy DBA stuff. You can check it out here. https://sql-performance-explained.com/ I've seen pdfs of it floating around the internet, but I am not sure if they are legit or not. I suggest just buying it, as it serves as a great reference for many of the projects I work on.

**Comment by imnotjames** [comment] 2021-07-04 01:20
duplicate of #3857

**Closed by imnotjames** 2021-07-04 01:20 UTC
Labels: driver: mariadb, driver: mysql, question
