### ISSUE TITLE
Insert mssql random code(Chinese version )

### ISSUE THREAD

**Issue by yudaming** [typeorm/typeorm#2319] opened 2018-06-11 11:13 UTC
Issue type:

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[x ] mssql
[] mysql / mariadb
[ ] oracle
[ ] postgres
[ ] sqlite
[ ] sqljs
[ ] websql

TypeORM version:

[] latest
[ ] @next
[x ] 0.1.2 (or put your version here)

In MysqlDriver, if you add'\b'when you use regular expressions, you can't match the word boundary of a Unicode character. Why do you do this here?
插入mssql 中文 乱码
Insert mssql random code
table ：
CREATE TABLE [dbo].[history_bug_info]
(
[id] [int] NOT NULL IDENTITY(244, 1),
[bug_id] [int] NOT NULL,
[title] [nvarchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[customer] [nvarchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[description] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NOT NULL,
[status] [tinyint] NOT NULL CONSTRAINT [DF__history_b__statu__32E0915F] DEFAULT ((0)),
[bug_type] [tinyint] NOT NULL CONSTRAINT [DF__history_b__bug_t__33D4B598] DEFAULT ((0)),
[reason] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[source] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__sourc__34C8D9D1] DEFAULT (NULL),
[register_time] [datetime2] (0) NULL CONSTRAINT [DF__history_b__regis__35BCFE0A] DEFAULT (NULL),
[register_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__regis__36B12243] DEFAULT (NULL),
[register] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__regis__37A5467C] DEFAULT (NULL),
[solved_time] [datetime2] (0) NULL CONSTRAINT [DF__history_b__solve__38996AB5] DEFAULT (NULL),
[developer_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__devel__398D8EEE] DEFAULT (NULL),
[developer] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__devel__3A81B327] DEFAULT (NULL),
[tester_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__teste__3B75D760] DEFAULT (NULL),
[tester] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__teste__3C69FB99] DEFAULT (NULL),
[owner_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__owner__3D5E1FD2] DEFAULT (NULL),
[owner] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__owner__3E52440B] DEFAULT (NULL),
[is_solved] [smallint] NOT NULL CONSTRAINT [DF__history_b__is_so__3F466844] DEFAULT ((0)),
[operate_time] [datetime2] (0) NOT NULL CONSTRAINT [DF__history_b__opera__403A8C7D] DEFAULT (getdate()),
[operator_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__opera__412EB0B6] DEFAULT (NULL),
[operator] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__opera__4222D4EF] DEFAULT (NULL),
[operation_type] [tinyint] NOT NULL CONSTRAINT [DF__history_b__opera__4316F928] DEFAULT ((0)),
[demand_number] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__deman__440B1D61] DEFAULT (NULL)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[history_bug_info] ADD CONSTRAINT [PK_history_bug_info_id] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'bug_system.history_bug_info', 'SCHEMA', N'dbo', 'TABLE', N'history_bug_info', NULL, NULL
GO
![image](https://user-images.githubusercontent.com/10510808/41228428-ec8469dc-6daa-11e8-8b70-a3d4bc703104.png)
--插入语句
```
@Entity('bug_info')
export class BugInfo {
    @PrimaryGeneratedColumn() id: number | undefined;

    @Column({
        name: 'title',
        type: 'varchar',
        length: 255
    })
    title: string | undefined;

    @Column({
        name: 'customer',
        type: 'varchar',
        length: 255
    })
    customer: string | undefined;

    @Column({
        name: 'description',
        type: 'text'
    })
    description: string | undefined;

    @Column({
        name: 'status',
        type: 'tinyint'
    })
    status: number | undefined;

    @Column({
        name: 'bug_type',
        type: 'tinyint'
    })
    bugType: number | undefined;

    @Column({
        name: 'reason',
        type: 'text'
    })
    reason: string | undefined;

    @Column({
        name: 'source',
        type: 'varchar',
        length: 50
    })
    source: string | undefined;

    @Column({
        name: 'register_time',
        type: 'datetime'
    })
    registerTime: Date | undefined;

    @Column({
        name: 'register_code',
        type: 'varchar',
        length: 50
    })
    registerCode: string | undefined;

    @Column({
        name: 'register',
        type: 'varchar',
        length: 50
    })
    register: string | undefined;

    @Column({
        name: 'solved_time',
        type: 'datetime',
        nullable: true
    })
    solvedTime: Date | undefined;

    @Column({
        name: 'developer_code',
        type: 'varchar',
        length: 50
    })
    developerCode: string | undefined;

    @Column({
        name: 'developer',
        type: 'varchar',
        length: 50
    })
    developer: string | undefined;

    @Column({
        name: 'tester_code',
        type: 'varchar',
        length: 50
    })
    testerCode: string | undefined;

    @Column({
        name: 'tester',
        type: 'varchar',
        length: 50
    })
    tester: string | undefined;

    @Column({
        name: 'owner_code',
        type: 'varchar',
        length: 50
    })
    ownerCode: string | undefined;

    @Column({
        name: 'owner',
        type: 'varchar',
        length: 50
    })
    owner: string | undefined;

    @Column({
        name: 'is_solved',
        type: 'tinyint'
    })
    isSolved: boolean | undefined;

    @Column({
        name: 'demand_number',
        type: 'varchar',
        length: 50
    })
    demandNumber: string | undefined;

    @OneToMany((type) => BugAttachment, (bugDetail) => bugDetail.bugInfo)
    @JoinColumn({ name: 'id', referencedColumnName: 'bugId' })
    bugAttachments: BugAttachment | undefined;

    @OneToMany((type) => OperateLog, (operateLog) => operateLog.bugInfo)
    @JoinColumn({ name: 'id', referencedColumnName: 'bugId' })
    operateLog: OperateLog | undefined;
}
```
```
 const conn = MyConnection.myConnection[BugService.key];
            const bugRepository = conn.getRepository(BugInfo);
            const userName = await UserService.getUserName(userCode);
            bugInfo.register = userName;
            const query = bugRepository.save(bugInfo);
            const insertResult = await query
```;

Where can I configure?

**Comment by pleerock** [comment] 2018-06-11 11:39
since its duplicate of #1659 lets keep talk there.

**Closed by pleerock** 2018-06-11 11:39 UTC
