### ISSUE TITLE
Column Index exception using dropDatabase

### ISSUE THREAD

**Issue by muyu66** [typeorm/typeorm#572] opened 2017-06-23 03:25 UTC
Hello, 

This is my code:

```
class User {
    @Column('int', { name: 'user_id' })
    @Index({ unique: true })
    userId: number;
}
```

When i execute dropDatabase(), it throw a exception

    Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'user_id'; check that column/key exists

	query failed: ALTER TABLE `user` DROP INDEX `user_id`

But i try to input raw sql "ALTER TABLE `user` DROP  `user_id`" , it is just successful.

Is this my usage problem ?

addition:
The problem may be that the column create a random name INDEX (eg. ind_7ad3e9ad3b262a0236929bf7024) when using **@Index({ unique: true })**.
So **DROP INDEX 'user_id'** must be not exist.

**Comment by Fokir** [comment] 2017-07-10 06:56
[#221](https://github.com/typeorm/typeorm/issues/221) The problem is also related to this issue

**Comment by pleerock** [comment] 2017-09-14 04:55
@iz-iznogood can you please take a look, maybe you have already fixed this issue?

**Comment by iz-iznogood** [comment] 2017-09-14 11:56
This is related to #549,  #244 and #221. 
We need to discuss this to decide on a behavior.
The workaround in #221 is correct but the problem remains.

**Comment by pleerock** [comment] 2017-09-14 17:41
fixed by @iz-iznogood , fix will be released in next version

**Closed by pleerock** 2017-09-14 17:41 UTC
Labels: bug, comp: schema
