### ISSUE TITLE
Setting a large number of aliases сolumns

### ISSUE THREAD

**Issue by golubvladimir** [typeorm/typeorm#7859] opened 2021-07-07 08:29 UTC
### The Problem

I want to setting a large number of aliases columns.

Now I can add a lot of count select and addSelect.
```
.select('column1', 'column1_al')
.addSelect('column2', 'column2_al')
```

Idea - use object
```
.select({
  'column1': 'column1_al'
  'column2', 'column2_al'
})
```

**Comment by imnotjames** [comment] 2021-07-07 16:54
Duplicate of #7824

**Closed by imnotjames** 2021-07-07 16:54 UTC
Labels: comp: query builder, new feature, requires triage
