### ISSUE TITLE
@RelationId properties are not updated after entity saving

### ISSUE THREAD

**Issue by asvetliakov** [typeorm/typeorm#815] opened 2017-09-03 07:31 UTC
Reproduce:

```ts
@Entity()
class A {
  @PrimaryGeneratedColumn()
  id: number;
}

@Entity()
class B {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(type => A, { nullable: false })
  a: A;

  @RelationId((b: B) => b.a)
  aId: number;
}

const a = await conn.getRepository(A).findOneById(1); // a exist in db
const b = new B();
b.a = a!;
await conn.getRepository(B).save(b);

b.aId; // undefined
```

Since saving entity populates ```b.id``` i'd expect that it automatically assigns ```b.aId```. Same rule must apply when ```a``` declared in ```B``` with ```cascadeInsert: true``` and saving new ```A``` object

**Comment by pleerock** [comment] 2017-09-03 16:54
They are read-only. If you change them nothing will be changed in the database when you save them. Its by design (but may be changed in the deep future).

**Comment by pleerock** [comment] 2017-09-06 10:16
Fix for this bug will be released in next version

**Closed** 2017-09-06 10:16 UTC
Labels: bug
