### ISSUE TITLE
Schema migration support

### ISSUE THREAD

**Issue by thynson** [typeorm/typeorm#63] opened 2016-10-27 06:53 UTC

**Comment by pleerock** [comment] 2016-10-27 07:02
totally needed feature, one of the most complex that is left. Im still thinking what is the best way to organize this process. @19majkel94 do you have experience using migrations in other orms, how they look like and what is the best approach?

**Comment by 19majkel94** [comment] 2016-10-30 11:55
Oh, unfortunately not yet, I'm a beginner with no big experience - I just like new, good languages/frameworks/tools 😉 I even don't get the migration concept well so I'm not able to help you with this feature.

**Comment by dreamersp** [comment] 2016-10-30 16:21
Have you considered using umzug from Sequelize? It allows for a fast integration of up() and down() functions executed consecutively and log which migration ran. Only that as DB it integrates with Sequelize or a JSON file log.

**Comment by pleerock** [comment] 2016-10-30 16:44
its easy to implement something that runs up and down functions... The problem is that users will do inside them... Will they write raw sql code there? Or should orm provide good api to write migrations? Or should orm generate migrations by itself if its possible? Or anything else?

**Comment by dreamersp** [comment] 2016-10-30 18:06
I was thinking more of a first minimum working version that can be used for producing the models and it's changes maybe with a few predefined queries like createColumn(), dropColum(), and or just raw queries.

For me the ideal TS ORM shall resemble and improve what EntityFramework offers in C# world. But that seems like a big endeavour even though you're half the way into it.
What I found lacking in Javascript ORMs is general scaffolding/self migration generation, nice clean models, and annotation based enrichment. As I mentioned I think typeorm is changing this and I found it resemblant to EntityFramework in it's way of creating models and querying.

Never the less, as you already found a way of tracking changes of the models vs DB and writing SQL to reflect those changes, it would be a first step to encapsulate that SQL into a migration/file and run it from command line.

Even EF haven't offered a de-facto way of using their models into it's generated migrations, that's an improvement I would recommend after a working basic scheme migration. It may be straight away to make or not.

**Comment by thynson** [comment] 2016-10-31 02:58
I think Raw SQL is acceptable at first time. While generated migration script is sometimes unreliable.

**Comment by pleerock** [comment] 2016-10-31 03:14
agree. you can use some third party package for example [db-migrate](https://github.com/db-migrate/node-db-migrate) until I implement this. If of course nobody want to contribute :)

**Comment by dreamersp** [comment] 2016-12-08 18:43
Hi there again!
I was wondering how to implement a first self-generated script using your SchemaBuilder @pleerock . Reading the code related to SchemaBuilder, then QueryBuilder and come to think that if we can inject a string writer/array writer class every time query() is called (at least in MysqlQueryRunner) instead of using a native connection to the Database Driver, we could get the SQL statements to insert into an scaffold up() function.
Maybe an extension to the native connection and allowing in MysqlDriver to overwrite it's databaseConnection with a provided connection class in the constructor.

It goes beyond my understanding of the code(and sadly my available time) how to inject such class and discriminate the schema checking queries needed to generate the change queries(use a regex discriminating SELECTs?) and intercept only the later triggered in a cli based tool.

**Comment by pleerock** [comment] 2016-12-09 08:41
You can access driver and its query builder via connection object and via connection manager. If you have complexities with it, I recommend you to use native driver (or easiest for you). Migration support is something that is next in my plan and Im planning to ship it this month.

**Comment by pleerock** [comment] 2016-12-12 12:13
implemented in #120 need your feedback guys

**Comment by pleerock** [comment] 2016-12-12 13:52
added docs [here](https://typeorm.github.io/migrations.html) and updated [example how to use it](https://github.com/typeorm/typescript-example). released in `0.0.5`

**Closed by pleerock** 2016-12-12 13:52 UTC
Labels: enhancement, new feature
