### ISSUE TITLE
Postgres Performance Issue On Persist

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#292] opened 2017-02-16 23:26 UTC
Goal: Write 500 new items to the database from a single Typed Array. 

Result: Items persist correctly

Problem: takes 2.5 second 

Why: Looks like the persist method is issuing multiple TRANSACTION / COMMIT.

Does wrapping it in a transaction help? No.

```
      let documents: DTODocument[] =  ....redacted 
      let start = new Date().getTime();
      let items: DTODocument[] = await this.documentRepo.transaction(() => 
this.documentRepo.persist(documents));
      let end = new Date().getTime();
      
      console.log("Call to persist took " + (end - start) + " milliseconds.");
```

> Call to persist took 2709 milliseconds.

PSQL LOG: https://gist.github.com/anonymous/df653e0a2b4b6c004f9d1725a02ecb78

**Comment by pleerock** [comment] 2017-02-17 03:28
transaction is called per each persist call. Thats expected behaviour.

You are using `.transaction` method wrong way. You should do it this way instead:

```typescript
    let items: DTODocument[] = await this.documentRepo.transaction(repository => 
repository.persist(documents));
```

All operations in the transactions should be done by provided instance of repository!

**Comment by rightisleft** [comment] 2017-02-17 16:13
Thanks! That does seem to have taken care of the TRANSACTION / COMMIT issue. But i'm still seeing pretty slow performance.  

> Call to persist took 2039 milliseconds.

https://gist.github.com/anonymous/9e986bc7c93280379b057b4427cbaea7

**Comment by dcworldwide** [comment] 2017-02-18 11:56
How is performance compared to running the same test without typeorm using just the pg library?

**Comment by pleerock** [comment] 2017-02-18 19:05
Its ORM, it brings lot of convenience for you and takes some of your performance. It does not make sense to compare typeorm with just native pg library because there is happening a really lot of stuff under the hood. Instead I recommend to make a simple entity without any relations, and make same test, and then add lot of performance timers and find out slow parts which can be optimized. There is a room for small optimizations that can be applied to decrease execution time.

**Comment by dcworldwide** [comment] 2017-02-18 22:34
My point was what is the overhead. It is excessive or minimal. If it's excessive then that's something worth understanding.

**Comment by rightisleft** [comment] 2017-02-21 16:26
Overall i agree. My baseline for comparison is i can persist 11.5K rows / 22MB data using pg console in 200ms. I've already broken apart the post into a 500 element arrays to try and make the ORM persist more performant. But 2.5 seconds for 500 is quite painful.

**Comment by MaikelH** [comment] 2017-02-21 19:41
Some performance loss is to be expected when using an ORM. But,

> Overall i agree. My baseline for comparison is i can persist 11.5K rows / 22MB data using pg console in 200ms.

This would mean that using typeorm lead to around a ~200x slowdown in performance. Seems a bit excessive to me. Could be you that are hitting maybe some kind edge case inside typeorm. 

If you have some test code / data, I can run it inside a profiler to see if there are some hotspots in the code.

**Comment by pleerock** [comment] 2017-02-22 06:10
The most expensive part are relations. If you have relations it will add lot of extra queries and operations. So first before saying that its 200x slow make sure to provide an entity without relations. If its that slow then we need to profile and find parts that execute the most slow and rewrite them. @MaikelH just take a dummy post entity and make a profiling if you want to contribute on this question.

**Comment by rightisleft** [comment] 2017-02-22 15:29
It's also comparing apple to oranges. COPY is going to be faster than INSERT. And for clarification, there are no relations on the entity.

**Comment by pleerock** [comment] 2017-11-17 15:37
thanks to @MaikelH we have a performance report and made a good progress in 0.2.0-alpha versions of typeorm. Closing in favour of #1115

**Closed by pleerock** 2017-11-17 15:37 UTC
Labels: needs more info, performance
