### ISSUE TITLE
Count query is not working

### ISSUE THREAD

**Issue by TRoYan4eG** [typeorm/typeorm#4948] opened 2019-10-22 08:00 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18`

``` ts 
const nowDate = new Date().toISOString();
const query = {
	workers : { $elemMatch: {
				workerId: this.id.toString(),
				startDate: {
					$gte: nowDate
				}
			}},
	$where: "function () { return (new Date(new Date(this.requestTime).setMinutes(this.endTime.split(':'[1])).setHours(this.endTime.split(':')[0])) >= new Date().getTime();}"
	}
const currentJobs = await getMongoRepository(Job).count(query);
```
Retuns MongoError: $where is not allowed in this context

But in native Mongo console it is working correctly:
``` js
db.getCollection('job').count({"workers":{"$elemMatch":{"workerId":"5da8d59512dd88474460919d","startDate":{"$gte":"2019-10-22T07:50:13.613Z"}}},"$where":"function () { return (new Date(new Date(this.requestTime).setMinutes(this.endTime.split(':')[1])).setHours(this.endTime.split(':')[0])) >=  new Date().getTime();}"})
```
If try `where` instead `$where` it's always returns 0 because there is now `where` in this collection...

**Comment by danmana** [comment] 2020-08-12 14:26
Looks like [MongoQueryRunner](https://github.com/typeorm/typeorm/blob/0.2.25/src/driver/mongodb/MongoQueryRunner.ts#L147) uses `collection.countDocuments` not `collection.count`.

If I try using `$where` with `countDocuments` in Mongo console it also fails.

Perhaps you can use an aggregate query and $expr, $function to get the same results (in Mongo > 4.4)

**Comment by imnotjames** [comment] 2020-10-08 19:51
duplicate of #4634

**Closed by imnotjames** 2020-10-08 19:51 UTC
Labels: bug, driver: mongodb
