### ISSUE TITLE
Complement shim.js : Is there any problem adding @Unique to shim ?

### ISSUE THREAD

**Issue by Overfacto** [typeorm/typeorm#6288] opened 2020-06-21 13:03 UTC
I've error on Angular 9 with TypeORM shim, and it is resolved with manually @Unique empty patch. 

If when I add @Unique and something decorator empty function, will this be problem?

**Issue type:**
[x] feature request

**TypeORM version:**
[x] `latest`

**Comment by imnotjames** [comment] 2020-10-11 10:49
You'll need to elaborate on your problem and what feature you're looking for - I'm not sure I understand what you'd like as a new behavior.

**Comment by imnotjames** [comment] 2020-10-12 20:20
Duplicate of #5920

**Closed by imnotjames** 2020-10-12 20:20 UTC
Labels: can be closed?, new feature
