### ISSUE TITLE
How to debug CPU performance issues

### ISSUE THREAD

**Issue by daramasala** [typeorm/typeorm#5619] opened 2020-03-05 09:20 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,
I am seeing 100% CPU usage on my nodejs server and most of this time is spent inside typeorm functions that create the query (before executing it).

I created a flame graph and I see that `SelectSqlQueryBuilder.getQuery` is responsible for most of the CPU usage. It causes the server to grind to a halt.

Most of my data is cached in memory so I only use typeorm in a small percentage of the calls and still it causes the server to not be able to handle other requests because it is spending time creating the query.

The problematic queries are those that contain 2 joins.

Is this a known issue (I couldn't find a similar issue)?
Is there anything I can do to make this faster (e.g. cache the query itself - not the results)?
If I want to further troubleshoot this, are there any logs that can be turned on to see what consuming so much CPU?

**Comment by CristianPi** [comment] 2020-05-08 20:38
The same here, i don't have any clue, except what --perf shows me, like 60% of the time spent on QueryBuilder.

Also, a lot of other strange things like:

```
this.connection.getRepository(Order).createQueryBuilder('order'); -> ~2000/3000 RPS
this.connection.getRepository(Order).createQueryBuilder('order').loadAllRelationIds() -> ??800 RPS??
```

Loading relations take the RPS to around 40, with 100% cpu usage.

@daramasala did you find a solution?

**Comment by daramasala** [comment] 2020-05-18 21:02
@CristianPi I replaced all the queries that include joins with hard coded sql queries. This fixed the cpu usage. It seems that calculating joins us very cpu intensive.

**Comment by CristianPi** [comment] 2020-05-18 21:21
> @CristianPi I replaced all the queries that include joins with hard coded sql queries. This fixed the cpu usage. It seems that calculating joins us very cpu intensive.

i ended doing the same, and now i load relations based on ids or the support table (one to many)
it's much much faster, 6x with less cpu for simple objects, for complex one with a lot of query involved i saw peek performance about 14x faster than the original.

hell of a improvements!

ps: i'm using the pg-native client that typeorm supports, i saw performance gains especially around handling dates, as it's a "drop-in" replacement (just need to install) i suggest you to try that also.

**Comment by imnotjames** [comment] 2020-10-09 21:37
I think this was related to #4760 which was just merged in.  This could help a bit here.

For help profiling and finding the cause of the heavy CPU usage, check out our community support channels.  Once you've narrowed it down a bit more (query builder is a wide area to point at) please open a new issue detailing what's not performing as well as it could, and a general suggestion for how it could be improved.

[community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Closed by imnotjames** 2020-10-09 21:37 UTC
Labels: driver: mariadb, driver: mysql, question
