### ISSUE TITLE
[Proposal] cli support migrate to specific revision

### ISSUE THREAD

**Issue by e-cloud** [typeorm/typeorm#4727] opened 2019-09-11 07:45 UTC
**Issue type:**

* [ ] question
* [ ] bug report
* [x] feature request
* [ ] documentation issue

**Database system/driver:**

* [ ] `cordova`
* [ ] `mongodb`
* [ ] `mssql`
* [x] `mysql` / `mariadb`
* [ ] `oracle`
* [ ] `postgres`
* [ ] `cockroachdb`
* [ ] `sqlite`
* [ ] `sqljs`
* [ ] `react-native`
* [ ] `expo`

**TypeORM version:**

* [x] `latest`
* [ ] `@next`
* [ ] `0.x.x` (or put your version here)

### Goals

Allow client to migrate target database to specific pending revision.

### Current state

not available

### Proposal

as mentioned in https://github.com/typeorm/typeorm/issues/3954#issuecomment-482485153 by @izayl, it would be very helpful to have an option like:

```ts
ts-node ./node_modules/typeorm/cli.js migration:run --target-migration <revision-tag>
```

**Comment by e-cloud** [comment] 2019-09-11 07:46
in python community, a similar tool like alembic support the requested feature
```sh
alembic upgrade <target-revision>
```

**Comment by imnotjames** [comment] 2020-10-14 06:25
Duplicate of #3591

**Closed by imnotjames** 2020-10-14 06:25 UTC
Labels: comp: cli tools, comp: migrations, enhancement
