### ISSUE TITLE
Not able to load new migration

### ISSUE THREAD

**Issue by Ash-5** [typeorm/typeorm#9785] opened 2023-02-14 03:21 UTC
### Issue description

When we give paths for new migrations in DataSource migration array and run migration using windows CLI, it return response `No migration pending`

### Expected Behavior

when I give migration as 
```
migrations: ['./dist/migrations/*.js']
```
Ideal behavior while running migration, It should read new migrations files and do the action accordingly.

### Actual Behavior

When I run migration via windows CLI it returns response `No migration are pending`

### Steps to reproduce

Inside DataSource pass migration value as: -
```
migrations: ['./dist/migrations/*.js']
```

run command:-
```
npm run typeorm migration:run -- -d /path-to-data.source.ts```
```

package.json script:-
```json
"typeorm": "npx typeorm-ts-node-commonjs"
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    windows      |
| Node.js version     | 16.14.2 |
| Typescript version  | 4.7.4  |
| TypeORM version     | 0.3.12  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by Ash-5** [comment] 2023-02-14 03:28
My debug says issue is happening inside `DirectoryExportedClassesLoader.js`
where `glob.sync()` is not able to read files in directory when the command is triggered via windows terminal. and returns an empty array. 

**NOTE:- Mentioning it here because I didn't find it anywhere else documented.**

**Comment by cduff** [comment] 2023-02-14 04:37
I'm experiencing the same issue on my Windows 11 Pro machine. To work around it for now I'm executing typeorm migration commands inside a Docker container.

**Comment by cduff** [comment] 2023-02-14 04:47
Duplicate of https://github.com/typeorm/typeorm/issues/9769?

**Comment by alumni** [comment] 2023-02-16 09:26
Duplicate of #9766 which was fixed

**Comment by VasilyVP** [comment] 2023-04-15 03:00
it seems migrations are being found again. I checked after update from 0.3.12 to 0.3.14

**Comment by Ash-5** [comment] 2023-04-17 08:49
> it seems migrations are being found again. I checked after update from 0.3.12 to 0.3.14

I will try from my end.

**Closed** 2023-10-11 03:03 UTC
Labels: bug, requires triage

**Comment by Mnigos** [comment] 2024-02-20 11:04
doesnt work for `0.3.19`
