### ISSUE TITLE
`repository.create` strips values of columns that are both arrays and embedded objects 

### ISSUE THREAD

**Issue by thonythony** [typeorm/typeorm#2342] opened 2018-06-15 07:44 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When using repository.create, TypeORM strips array type column values before returning the object instance.

Given a simple Foo entity, which in turn contains a collection of Bar objects

``` typescript
@Entity()
export class Foo {
  @ObjectIdColumn()
  public id: ObjectID;

  @Column()
  public simple: string;

  @Column(type => Bar)
  public collection: Bar[];
}

export class Bar {
  @Column()
  value: boolean;
}
```

repository.create transforms the raw value

```typescript
{
  "simple": "string",
  "collection": [
    { "value": true },
    { "value": false }
  ]
}
```

into simply

```typescript
{ "simple": "string" }
```

Source : #1980

**Comment by craftball** [comment] 2019-02-21 20:24
Confirmed not working with arrays on 02/21/2019

**Comment by Kononnable** [comment] 2019-04-20 22:32
Duplicate of #1980

**Closed by Kononnable** 2019-04-20 22:32 UTC
