### ISSUE TITLE
'relations' does not exist in type DeepPartial when using .find()

### ISSUE THREAD

**Issue by matheusgrieger** [typeorm/typeorm#2406] opened 2018-06-25 12:00 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using ActiveRecord:

```ts
@Entity()
export class Customer extends BaseEntity {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column({
    length: 11,
    unique: true
  })
  public document: string;

  @OneToMany(() => CustomerAddress, (address) => address.customer)
  public addresses: CustomerAddress[];
}

@Entity()
export class CustomerAddress extends BaseEntity {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  public title: string;

  @ManyToOne(() => Customer, (customer) => customer.addresses)
  public customer: Customer;
}
```

Whenever I use `Customer.find({ relations: ['addresses'] })`, I get a type error saying that `Argument of type '{ id: number; relations: string[]; }' is not assignable to parameter of type 'DeepPartial<Customer> | undefined'. Object literal may only specify known properties, and 'relations' does not exist in type 'DeepPartial<Customer> | undefined'.`

Am I doing something wrong? Because everything works as expected with the query, yet the type error throws when compiling as well.

**Comment by acro5piano** [comment] 2018-10-22 14:03
Exactly, current workaround:

```
await Customer.find({ id, ['relations' as any]: ['addresses'] as any })
```

**Comment by matheusgrieger** [comment] 2018-10-31 20:09
@acro5piano gets a little verbose to do that every time, but it works. Thank you!

**Comment by amaranth** [comment] 2018-11-01 19:18
I can't reproduce this error with TypeScript v2.8.1 (what TypeORM uses) or with v3.1.5 (latest) when using TypeORM from master.

Example code:
```typescript
        const customer = Customer.create({document: "foo"});
        await customer.save();
        const address = CustomerAddress.create({title: "bar", customer: customer});
        await address.save();

        const found = await Customer.find({relations: ["addresses"]});
        console.log(found[0].addresses);
```

**Comment by Kononnable** [comment] 2019-02-19 14:01
Closing because the issue cannot be reproduced.

**Closed by Kononnable** 2019-02-19 14:01 UTC
