### ISSUE TITLE
Cannot cascade deletion along one-to-many relations

### ISSUE THREAD

**Issue by JanKoehnlein** [typeorm/typeorm#1913] opened 2018-04-11 11:25 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I cannot set any deletion cascading on a one to many relation. The typing forbids it (parameter is *not* RelationOptions but some anonymous sub-type lacking the cascade properties).
This is my use case: An EntityA contains multiple EntityBs. These are integral parts, i.e. when I delete EntityA all related EnitityBs have to be removed as well, and an EntityB can only belong to exactly one EntityA.
According to the docs, TypeORM does not allow `@OneToMany` without an opposite `@ManyToOne`, so I define
```
export class EntityA {
    @OneToMany(type => EntityB,
        b => b.a,
        {
            eager: true,
            cascadeInsert: true,
            cascadeUpdate: true
            // , cascadeRemove: true    // In the docs but not the code???
        }
    )
    @JoinColumn()
    bs: EntityB[];
}

export class EntityB {
  @ManyToOne(type => A, a => a.bs)
  a: A;
}
```
When I try to delete an EntityA, I get a foreign key violation on the related EntityBs.

**Comment by pleerock** [comment] 2018-04-11 11:31
cascade removal is not supported due to complexity and too many problems with it. We have plans to support it in the future. Duplicate of #1761 and #1351

**Closed by pleerock** 2018-04-11 11:31 UTC

**Comment by JanKoehnlein** [comment] 2018-04-11 12:05
OK, then how do I programmatically delete such an entry in an atomic operation

```
await entityManager.transaction(async transactionalManager => {
            await transactionalManager.createQueryBuilder()
                .delete()
                .from(B)
                .where('a.id = :id', {id: id})
                .execute();
            await transactionalManager.createQueryBuilder()
                .delete()
                .from(A)
                .where('id = :id', {id: id})
                .execute();
        })
```
fails with a foreign key violation as well. It works only without the transaction.

**Comment by JanKoehnlein** [comment] 2018-04-11 12:13
PS: It doesn't even work without the transaction...

**Comment by pleerock** [comment] 2018-04-11 12:19
with query builder you just create and execute sql queries. How do you achieve what you want to do via SQL?

**Comment by jagabs** [comment] 2019-02-23 02:33
any updates on this still not working

**Comment by Tim-mhn** [comment] 2020-12-11 11:04
Pretty late, but I got this working following [Ben Awad's video](https://www.youtube.com/watch?v=S1pxdAL2Dz8).

You need to specify the cascading delete on the ManyToOne side and not the OneToMany. In your  case, it would have to be in Entity B:

```
export class EntityB {
  @ManyToOne(type => A, a => a.bs, { onDelete: "CASCADE" })
  a: A;
}
```

Now, if you delete an instance of EntityA, all its EntityB will be deleted

**Comment by sherwinwater** [comment] 2021-01-15 14:24
No idea why mine doesn't work.

@Entity()
export class Post {
	@ManyToOne((type) => Group, (group) => group.posts, { onDelete: "CASCADE" })
	group!: Group;
}

@Entity()
export class Group {
	@OneToMany((type) => Post, (post) => post.group, { cascade: true })
	posts!: Post[];
}

**Comment by Tim-mhn** [comment] 2021-01-15 14:54
> No idea why mine doesn't work.
> 
> @entity()
> export class Post {
> @manytoone((type) => Group, (group) => group.posts, { onDelete: "CASCADE" })
> group!: Group;
> }
> 
> @entity()
> export class Group {
> @OneToMany((type) => Post, (post) => post.group, { cascade: true })
> posts!: Post[];
> }

I don't have the { cascade: true } for your Group entity. If i take your entities, I have this: 

```
@Entity()
export class Post {
@ManyToOne((type) => Group, (group) => group.posts, { cascade: true, onDelete: "CASCADE" })
group!: Group;
}

@Entity()
export class Group {
@OneToMany((type) => Post, (post) => post.group)
posts!: Post[];
}
```

**Comment by dgumus** [comment] 2024-05-17 09:39
export class ProfessionFocusIdentifier
  @ManyToOne(() => ProfileInfo, (pi) => pi.professionFocusIdentifiers, { cascade: true, onDelete: "CASCADE" })
  profileInfo!: ProfileInfo;
export class ProfileInfo
@OneToMany(() => ProfessionFocusIdentifier, (pfi) => pfi.profileInfo)
  professionFocusIdentifiers!: ProfessionFocusIdentifier[];

not workingg
