### ISSUE TITLE
manytomany update fails with no such column - sqlite

### ISSUE THREAD

**Issue by ELI7VH** [typeorm/typeorm#5398] opened 2020-01-22 18:10 UTC
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
record is a List record with a many to many relationship to items. The join table is created correctly in my sqlite database

```
const record = seeds.list[0]
record.items = [{ id: 9, name: 'beard trimmed' }]
this.repos.list.update(record.id, record)
```
list definition: https://gitlab.com/beulerplates/ez-mvc/blob/master/server/db/entity/list.ts
item definition: https://gitlab.com/beulerplates/ez-mvc/blob/master/server/db/entity/item.ts
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ELI7VH** [comment] 2020-01-22 18:12
Error Message: 
```
(node:20088) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: no such column: listId
    at new QueryFailedError (D:\programming\express-typeorm-sqlite\src\error\QueryFailedError.ts:9:9)
    at handler (D:\programming\express-typeorm-sqlite\src\driver\sqlite\SqliteQueryRunner.ts:53:26)
    at replacement (D:\programming\express-typeorm-sqlite\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.errBack (D:\programming\express-typeorm-sqlite\node_modules\sqlite3\lib\sqlite3.js:16:21)
(node:20088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by imnotjames** [comment] 2020-10-10 09:33
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 09:33 UTC
