### ISSUE TITLE
insert performance  weird

### ISSUE THREAD

**Issue by mraiguo** [typeorm/typeorm#6454] opened 2020-07-23 08:23 UTC
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
my database like this 
![image](https://user-images.githubusercontent.com/22299421/88265193-9f538880-ccff-11ea-99ea-e1748f980ff7.png)
and I use SQL statements directly
![image](https://user-images.githubusercontent.com/22299421/88265253-bd20ed80-ccff-11ea-9d76-5b249a81ce42.png)
that is correct
![image](https://user-images.githubusercontent.com/22299421/88265422-0f620e80-cd00-11ea-94e5-3caef4a92dc5.png)

but if I use orm query ， or insert，save
![image](https://user-images.githubusercontent.com/22299421/88265356-ec375f00-ccff-11ea-9272-68644ab9ecee.png)
It will be
![image](https://user-images.githubusercontent.com/22299421/88265386-fa857b00-ccff-11ea-997f-e3a610355cc9.png)
 the first and second item disappear
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment] 2020-07-23 21:43
You can [enable the logging feature](https://typeorm.io/#/logging) in TypeORM to see exactly what queries are actually being run.

Perhaps that would help you debug this issue?  It seems to not exactly be a bug with TypeORM per these screenshots.

**Comment by imnotjames** [comment] 2020-10-09 20:09
Without a reproducible example, there's not a lot we can do to find the root cause.  I've tested based on the information you've provided and have not been able to replicate.

As such, I'll be closing this.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Closed by imnotjames** 2020-10-09 20:09 UTC
Labels: bug, driver: mssql, needs more info
