### ISSUE TITLE
Default values support for mongodb

### ISSUE THREAD

**Issue by elie222** [typeorm/typeorm#3914] opened 2019-03-28 19:19 UTC
**Issue type:**

bug report

**Database system/driver:**

`mongodb`

**TypeORM version:**

`latest`

**Steps to reproduce or a small repository showing the problem:**

```ts
  // active, draft, archive
  @Column({ type: 'string', default: 'draft' })
  state: string
```

Upon insert, the document does not receive the default value of `draft`.

**Comment by rustamwin** [comment] 2019-03-29 06:11
Duplicate of #3799

**Closed by rustamwin** 2019-03-29 06:11 UTC
