### ISSUE TITLE
0.2.24 JEST tests suddenly throwing RepositoryNotFound, no changes to code

### ISSUE THREAD

**Issue by seandearnaley** [typeorm/typeorm#5592] opened 2020-02-29 18:08 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Not sure how exactly this started, I ran an dependency update to upgrade to TypeORM 0.2.24, and then suddenly my tests started failing, frustratingly just rolling back to .22 the error still happens, I believe some other dependency was updated with my yarn.lock, in general this issue has been problematic during development, but these tests had been working for 3 months without issue.

tsconfig.json

```
{
  "compilerOptions": {
    "lib": ["es5", "es6", "es2016", "es2017", "dom"],
    "target": "ES2016",
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "outDir": "./build",
    "noImplicitAny": true,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/"],
      "typings/*": ["src/typings/*"]
    }
  },
  "include": ["src/**/*.ts"],
  "exclude": ["src/test/**/*.spec.ts", "node_modules"]
}

```

jest.config.js

```
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  collectCoverage: true,
  collectCoverageFrom: [
    "./src/**/*.{ts,tsx,js,jsx}",
    "!**/node_modules/**",
    "!**/build/**",
    "!./src/generated/**",
    "!./src/migration/**"
  ],
  testPathIgnorePatterns: [
    "/node_modules/",
    "/build/",
    "/__utils",
    "/__testData",
    "/__queries"
  ],
  globalSetup: "./src/jest.globalSetup.ts"
};
```

schema config:
```
export const schemaConfig = {
  entities: ["build/entity/**/*.{js,ts}"],
  migrations: ["build/migration/**/*.{js,ts}"],
  subscribers: ["build/subscriber/**/*.{js,ts}"],
  cli: {
    entitiesDir: "src/entity",
    migrationsDir: "src/migration",
    subscribersDir: "src/subscriber"
  }
};
```

```
 RepositoryNotFoundError: No repository for "Card" was found. Looks like this entity is not registered in current "testConnection" connection?
```

You can see the full repo for these tests here:
https://github.com/seandearnaley/brainstrike-typescript-starter/tree/master/server

**Comment by seandearnaley** [comment] 2020-02-29 18:21
can confirm rolling back to 0.2.22 this error doesnt happen

**Comment by Ginden** [comment] 2020-03-02 16:44
Do you wait for database connection to complete before using database?

**Comment by rmolinamir** [comment] 2020-03-02 21:31
Same here. In my case though, it's not limited to only tests. It would seem like the connection is re-instantiating somewhere and losing the registered entities?

**Comment by seandearnaley** [comment] 2020-03-02 21:58
> Do you wait for database connection to complete before using database?

Yes, here is the relevant code:

```

const createDbConnection = async (
  options: ConnectionOptions
): Promise<Connection> => {
  try {
    const connection: Connection = await createConnection(options);
    console.log(`TypeORM Connected to ${options.database}`);
    return connection;
  } catch (err) {
    console.log("Problem with TypeORM connection, check Postgres docker-up");
    throw err.message;
    process.exit(1);
  }
};

const createTestingConnection = (): Promise<Connection> =>
  createDbConnection({
    name: "testConnection",
    type: "postgres",
    database: "brainstrike_test",
    synchronize: false,
    ...postgresCreds,
    ...schemaConfig,
    logging: ["error"]
  });
```

**Comment by phong-innomizetech** [comment] 2020-03-06 06:27
On the latest version got this issue.

I am sure we need to have below code in findMetadata function at Connection.js file:

```
if (typeof metadata.target === "function" && typeof target === "function" && metadata.target.name === target.name) {
                return true;
}
```
Can anyone make the PR for this?

**Comment by phong-innomizetech** [comment] 2020-03-06 06:49
Added new PR at #5627

**Comment by seandearnaley** [comment] 2020-03-07 20:44
thanks for your pr @phong-innomizetech , it looks like this PR has some disputes... I wonder does anyone have any workarounds, I'm not exactly sure what it happening here, could anyone give a brief explanation and I can have a look at solutions myself.

**Comment by YoonSeongKyeong** [comment] 2020-03-17 13:40
I have solution @seandearnaley 
we can solve this problem with replacing code like this

## **Before**
```typescript
protected findMetadata(target: Function|EntitySchema<any>|string): EntityMetadata|undefined {
        return this.entityMetadatas.find(metadata => {
            if (metadata.target === target)
                return true;
            if (target instanceof EntitySchema) {
                return metadata.name === target.options.name;
            }
            if (typeof target === "string") {
                if (target.indexOf(".") !== -1) {
                    return metadata.tablePath === target;
                } else {
                    return metadata.name === target || metadata.tableName === target;
                }
            }

            return false;
        });
    }
```

## **After**
```typescript
protected findMetadata(target: Function|EntitySchema<any>|string): EntityMetadata|undefined {
        return this.entityMetadatas.find(metadata => {
            if (Object.getPrototypeOf(metadata.target) === Object.getPrototypeOf(target)&&metadata.target.name===target.name)
                // First Check if target is made from same entity constructor as metadata target have. Then check if target name is same as metadata target name
                return true;
            if (target instanceof EntitySchema) {// I don't know if this condition is necessary
                return metadata.name === target.options.name;
            }
            if (typeof target === "string") {// I don't know if this condition is necessary
                if (target.indexOf(".") !== -1) {
                    return metadata.tablePath === target;
                } else {
                    return metadata.name === target || metadata.tableName === target;
                }
            }

            return false;
        });
    }
```
#### Object.getPrototypeOf(metadata.target) === Object.getPrototypeOf(target) will satisfy the problem requirement
1. check if metadata.target is same as target
2. check if target is not only same named function but also created by entity constructor (resolve false positivity)

please add new PR from this patch. it will work well

**Comment by nico-schunke** [comment] 2020-03-27 16:41
Any progress here? Can confirm the issue as well...

**Comment by YoonSeongKyeong** [comment] 2020-03-28 00:01
Actually no PR has been made. I will make new one in 3 days if no one try.

**Comment by seandearnaley** [comment] 2020-03-28 00:08
someone made a PR for this issue but it hasn't been accepted, see here: https://github.com/typeorm/typeorm/pull/5627

**Comment by YoonSeongKyeong** [comment] 2020-03-28 15:40
Oh, I checked the PR and added some comment. I hope the PR to be accepted

**Comment by seandearnaley** [comment] 2020-03-28 15:59
thanks for working on that @YoonSeongKyeong

**Comment by imnotjames** [comment] 2020-10-04 07:16
Is there a repo that exhibits this minimally?

I know jest does some weirdness with rewriting bits of code but I don't think that's the cause exactly...

**Comment by seandearnaley** [comment] 2020-10-04 17:59
@imnotjames I can try to make an even more minimal repo for this but tbh I've kinda been turned off the project, no movement on this in almost 6 months so I have started using other orms.. it'll take me a moment to setup but I will get that for you.

**Comment by imnotjames** [comment] 2020-10-04 18:05
Alrighty - if you can, it'd be very helpful.

Unfortunately, this issue is a bit more difficult than it seems on face value as the change that allowed this to work as expected broke a variety of other use cases.

**Comment by seandearnaley** [comment] 2020-10-04 18:30
thanks for getting back to us @imnotjames I do really appreciate it, I think this issue is somehow related also and has a higher user impact https://github.com/typeorm/typeorm/issues/5676

**Comment by imnotjames** [comment] 2020-10-04 18:31
Yea - I'm looking at both.  Because jest is involved here I have a feeling it could be similar but slightly different. :)

**Comment by imnotjames** [comment] 2020-10-12 06:09
After looking through this some I'm now pretty certain the issues are duplicates.  Given that #5676 has more activity I'll be closing this one.

**Comment by imnotjames** [comment] 2020-10-12 06:09
Duplicate of #5676

**Closed by imnotjames** 2020-10-12 06:09 UTC
Labels: bug, driver: postgres
