### ISSUE TITLE
synchronize drops (and then re-adds) column with large string

### ISSUE THREAD

**Issue by hrueger** [typeorm/typeorm#5695] opened 2020-03-16 02:36 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I have a column with a large length, the `synchronize` method drops and then re-adds my column which causes data to be lost.
It's only happening when my entity has a big column length: With `1 000` or `10 000` I don't have this issue, but with `100 000` I do...

My DB Config:
```
    Server: localhost via TCP/IP
    Server-Type: MariaDB
    Server-Connection: SSL is not used
    Server-Version: 10.1.38-MariaDB - mariadb.org binary distribution
    Protocoll-Version: 10
    User: root@localhost
    Server-Encoding: UTF-8 Unicode (utf8)
```
My Entity:
```typescript
import { Column, Entity, PrimaryColumn} from "typeorm";

@Entity()
export class Config {
  @PrimaryColumn()
  public key: string;

  @Column({length: 1000000000})
  public value: string;
}
```
The log:
```
[2020-03-05T18:05:09.117Z][QUERY]: SET NAMES utf8mb4;
[2020-03-05T18:05:09.122Z][QUERY]: START TRANSACTION
[2020-03-05T18:05:09.124Z][QUERY]: SELECT DATABASE() AS `db_name`
[2020-03-05T18:05:09.127Z][QUERY]: SELECT * FROM `INFORMATION_SCHEMA`.`TABLES` WHERE (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'ticket') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'user') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'config')
[2020-03-05T18:05:09.129Z][QUERY]: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'ticket') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'user') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'config')
[2020-03-05T18:05:09.131Z][QUERY]: SELECT * FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` WHERE `CONSTRAINT_NAME` = 'PRIMARY' AND ((`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'ticket') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'user') OR (`TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'config'))
[2020-03-05T18:05:09.133Z][QUERY]: SELECT `SCHEMA_NAME`, `DEFAULT_CHARACTER_SET_NAME` as `CHARSET`, `DEFAULT_COLLATION_NAME` AS `COLLATION` FROM `INFORMATION_SCHEMA`.`SCHEMATA`
[2020-03-05T18:05:09.134Z][QUERY]: SELECT `s`.* FROM `INFORMATION_SCHEMA`.`STATISTICS` `s` LEFT JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `s`.`INDEX_NAME` = `rc`.`CONSTRAINT_NAME` WHERE ((`s`.`TABLE_SCHEMA` = 'testagtickets' AND `s`.`TABLE_NAME` = 'ticket') OR (`s`.`TABLE_SCHEMA` = 'testagtickets' AND `s`.`TABLE_NAME` = 'user') OR (`s`.`TABLE_SCHEMA` = 'testagtickets' AND `s`.`TABLE_NAME` = 'config')) AND `s`.`INDEX_NAME` != 'PRIMARY' AND `rc`.`CONSTRAINT_NAME` IS NULL
[2020-03-05T18:05:09.136Z][QUERY]: SELECT `kcu`.`TABLE_SCHEMA`, `kcu`.`TABLE_NAME`, `kcu`.`CONSTRAINT_NAME`, `kcu`.`COLUMN_NAME`, `kcu`.`REFERENCED_TABLE_SCHEMA`, `kcu`.`REFERENCED_TABLE_NAME`, `kcu`.`REFERENCED_COLUMN_NAME`, `rc`.`DELETE_RULE` `ON_DELETE`, `rc`.`UPDATE_RULE` `ON_UPDATE` FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` `kcu` INNER JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `rc`.`constraint_name` = `kcu`.`constraint_name` WHERE (`kcu`.`TABLE_SCHEMA` = 'testagtickets' AND `kcu`.`TABLE_NAME` = 'ticket') OR (`kcu`.`TABLE_SCHEMA` = 'testagtickets' AND `kcu`.`TABLE_NAME` = 'user') OR (`kcu`.`TABLE_SCHEMA` = 'testagtickets' AND `kcu`.`TABLE_NAME` = 'config')
[2020-03-05T18:05:09.552Z][QUERY]: SELECT VERSION() AS `version`
[2020-03-05T18:05:09.556Z][QUERY]: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'typeorm_metadata'
[2020-03-05T18:05:09.569Z]renaming column "value" in to "value"
[2020-03-05T18:05:09.573Z]columns changed in "config". updating: value
[2020-03-05T18:05:09.576Z][QUERY]: ALTER TABLE `config` DROP COLUMN `value`
[2020-03-05T18:05:09.661Z][QUERY]: ALTER TABLE `config` ADD `value` varchar(1000000) NOT NULL
[2020-03-05T18:05:09.786Z][QUERY]: COMMIT
[2020-03-05T18:05:09.790Z][QUERY]: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'testagtickets' AND `TABLE_NAME` = 'migrations'
[2020-03-05T18:05:09.806Z][QUERY]: SELECT * FROM `testagtickets`.`migrations` `migrations` ORDER BY `id` DESC
[2020-03-05T18:05:09.810Z]No migrations are pending
```
As you can see, it's renaming `value` to `value`, then dropping the column and re-adding it. This issue is quite similar to #3636 with the difference, that my column is the `string` type and not `json`.

**Comment by creduo** [comment] 2020-07-17 08:03
MySQL and MariaDB do not support VARCHAR column that long. you should specify 'LONGTEXT' type.

**Comment by imnotjames** [comment] 2020-10-14 06:30
Duplicate of #3357

**Closed by imnotjames** 2020-10-14 06:30 UTC
Labels: bug, comp: migrations, driver: mariadb, driver: mysql
