### ISSUE TITLE
Transformers do not work for the MongoDB driver

### ISSUE THREAD

**Issue by roderik** [typeorm/typeorm#6506] opened 2020-08-03 19:30 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
  @Column('text', {
    transformer: {
      from: (value: string): BigNumber => BigNumber.from(value),
      to: (value: BigNumber): string => value.toString(),
    },
  })
  gasUsed!: BigNumber;
```

gasUsed is stored in the database as the "object", not as the result of the toString() function

The transformer code is correct because the following works correctly in Mongoose

```
  @Prop({  
    get: (value: string): BigNumber => BigNumber.from(value),
    set: (value: BigNumber): string => value.toString() 
  })
  gasUsed!: BigNumber;
```

There was a very old ticket about this mentioning some commented out code, but I could not find it and at first glance, the mongodb driver should execute the transformer code here https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoDriver.ts#L295-L308 triggered by https://github.com/typeorm/typeorm/blob/33041ccde5e46b95e1d10b1a15ad798b3a972651/src/query-builder/UpdateQueryBuilder.ts#L423

**Comment by imnotjames** [comment] 2020-10-07 03:29
Duplicate of #4268

**Closed by imnotjames** 2020-10-07 03:29 UTC
Labels: bug, driver: mongodb
