### ISSUE TITLE
AWS DynamoDB Support

### ISSUE THREAD

**Issue by hassankhan** [typeorm/typeorm#2480] opened 2018-07-07 16:58 UTC
Would love to see support for DynamoDB in a future version 😄

**Comment by netspencer** [comment] 2018-09-27 06:14
i really need this. anyone wanna take on the project of building it out with me ?

**Comment by ThatDevSteve** [comment] 2018-10-08 23:15
@netspencer - yeah

**Comment by johnbendi** [comment] 2018-10-30 08:55
@netspencer  @ThatDevSteve yeah too!

**Comment by byjokese** [comment] 2019-01-08 12:34
Any progress or news about this?

**Comment by pleerock** [comment] 2019-01-13 19:55
Currently, we do not have in plans to support any new database. But you know, you can always contribute or help [financially](https://github.com/typeorm/typeorm/issues/3267) to make it happen!

**Comment by murbanowicz** [comment] 2019-04-01 18:30
@netspencer @hassankhan there is Dynamoose which recently got much better and stable than before. TypeORM is mainly focused on SQL databases so far and there is still so much to do with the limited time of the core members. I would suggest to use Dynamoose at this moment if you really want to work with DynamoDB.

**Comment by yusufcmrt** [comment] 2019-10-07 00:13
I would love that

**Comment by denissabramovs** [comment] 2020-06-01 17:37
bump

**Comment by itsdarrylnorris** [comment] 2020-06-04 09:10
Any process/thoughts on this issue?

**Comment by kumar0** [comment] 2020-06-21 21:27
I would also love to have it

**Comment by dlydiard** [comment] 2020-10-13 01:56
+1

**Comment by moogsG** [comment] 2020-10-15 03:12
Is there progress on this request, or would it still be an open issue?

**Comment by itsdarrylnorris** [comment] 2020-10-18 21:30
How is asking for status of this issue is marked as spam? BTW, I am referring to my last comment that it was marked as SPAM.

That is not cool, this comment most likely will get marked as spam as well. And if so this is very sad.

**Comment by imnotjames** [comment] 2020-10-18 21:58
@moogsG the issue is still open so it's still open.

@itsdarrylnorris I'll refer to https://github.com/kossnocorp/etiquette - in particular - 

> It takes just a few seconds to type "Any updates on this?" but it takes much more time and energy to write a report back to you. First of all, you're not maintainers' boss, and they owe you nothing, not to mention a report.
> 
> These minutes could have been spent on something meaningful, so you not only steal time from the maintainer, but also the whole community.
>
> Don't write like a boss: "Why this isn't merged?" "What's the ETA?" "It blocks us!" "What are the blockers?".

"Any Update on this" does not really constitute as a meaningful addition to the conversation.  If there is an update it will be included.  There are no updates, so none are included.  If you notice, there's a number of others that have asked the same thing and it was also marked as spam.

And no, that's not spam what you've posted - it's off topic.

**Comment by cbullokles** [comment] 2020-10-21 02:54
is any plan to support DynamoDB or is still the idea to use Dynamoose? Can we contribute with code to support DynamoDB?

**Comment by imnotjames** [comment] 2020-10-21 03:13
We are accepting PRs for supporting DynamoDB.

**Comment by ElvenMonky** [comment] 2020-11-26 06:59
As already mentioned in similar feature request to Prisma:
"AWS just announced PantiSQL over dynamodb. I guess this makes DynamoDB support easier.
https://aws.amazon.com/about-aws/whats-new/2020/11/you-now-can-use-a-sql-compatible-query-language-to-query-insert-update-and-delete-table-data-in-amazon-dynamodb/"

**Comment by duongvanba** [comment] 2021-02-25 08:22
I see that now we can use PartiQL (https://partiql.org/) to query DynamoDB, hope that typeorm will support it soon

**Comment by whimzyLive** [comment] 2021-03-01 05:32
@imnotjames  I can start looking into this, but I will need some higher level spec on what/where things are required, I am currently in the process of writing ORM for dynamodb, [TypeDORM](https://github.com/typedorm/typedorm) which closely follows TypeORM but uses document client from aws sdk v2. 

So If you or someone can do a super higher level spec, I can get started onto dynamodb driver straight away.
@netspencer  Let's do it.

**Comment by trivikr** [comment] 2021-04-19 02:15
Hi folks, this is Trivikram - maintainer of AWS SDK for JavaScript.

TypeORM is very popular, and my team is open to recommend TypeDORM from [Amazon DynamoDB DataMapper for JavaScript](https://github.com/awslabs/dynamodb-data-mapper-js).

@whimzyLive - maintainer of TypeDORM - is also open to write DynamoDB driver for TypeORM along with @netspencer as per the comment in https://github.com/typeorm/typeorm/issues/2480#issuecomment-787652081

> I can start looking into this, but I will need some higher level spec on what/where things need to be added.

@imnotjames @pleerock Can you folks provide this higher level spec on what/where things need to be added so that @whimzyLive and @netspencer can start with the implementation?

If you need any additional support in [@aws-sdk/lib-dynamodb](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb), please [create an issue](https://github.com/aws/aws-sdk-js-v3/issues/new/choose) with AWS SDK for JavaScript.

**Comment by cweagans** [comment] 2021-06-14 22:49
I imagine a good starting point would be to go to https://github.com/typeorm/typeorm/find/master and search for `mongo`. That gives you a pretty comprehensive list of where all the MongoDB stuff lives. Implementing support for DynamoDB likely involves creating analogues for those files that target DynamoDB instead.

**Comment by whimzyLive** [comment] 2021-06-23 02:58
Thanks, @cweagans, and @trivikr. I did look into how MongoDB is set up a while ago. But, currently, I am in the middle of migrating TypeDORM to the latest js sdk, once I have that wrapped up, I should be able to find some time for myself to get started on adding DynamoDB driver to TypeORM (expect it to be somewhere around mid-July).

**Comment by tzahush** [comment] 2021-09-02 13:19
What are we looking to see in this?

Are we looking for join support, or just querying?

**Comment by ibqn** [comment] 2022-09-05 13:37
Is this idea abandoned or what is the current status here?

**Comment by kennu** [comment] 2022-09-05 14:26
Seems like https://github.com/awslabs/dynamodb-data-mapper-js was abandoned and this was abandoned, so at least I don't trust anything else than the basic AWS SDK from now on. It's really too bad.

**Comment by whimzyLive** [comment] 2022-09-05 14:31
Hi @ibqn, @kennu

There is a TypeORM-like implementation available for DynamoDB at https://github.com/typedorm/typedorm and I'm actively maintaining it, something you might be interested in.

I was looking to add in similar implementation into TypeORM but it's just not going to happen with the current complexity matrix of TypeORM.

**Comment by blueleader07** [comment] 2022-09-05 14:33
I have code I can contribute.  I have been using Typeorm with DynamoDB in production since April.  I have never contributed to Typeorm before though so bear with me while I merge and get through all the unit tests.  Also, this will be the first commit so I’m sure there are lots of features / enhancements that will need to be made.  Once my code is merged I think we should consider dynamodb support in “beta” for a time while people try it / provide feedback.  I will see about getting it merged asap (hopefully this week) … or perhaps publish my own fork to NPM so people can try it before merging with the rest of Typeorm.

**Comment by blueleader07** [comment] 2022-09-08 23:17
@pleerock This is ready to merge!  Please review and approve.
There are actually 2 PRs because I need to update the docs as well.  
I did not provide Chinese documentation ... sorry I don't know Chinese.  Definitely would appreciate help translating.

PRs:
https://github.com/typeorm/typeorm.github.io/pull/65
https://github.com/typeorm/typeorm/pull/9352

**Comment by blueleader07** [comment] 2022-09-15 14:47
@pleerock has suggested creating an extension rather than merging directly into the Typeorm codebase.

It's going to take me some time to make the adjustments.  In the meantime if anyone wants to "try" my fork of Typeorm (that supports DynamoDB) I've published it to npm.  
https://www.npmjs.com/package/@blueleader07/typeorm

Any feedback I will try to incorporate in the "extension" that I'm hoping to work on in the new few weeks.

I would like the community to own the dynamodb code and feel comfortable contributing just as we all have contributed PRs to Typeorm.  

I suggest we leave this ticket open until I have a new project setup for the extension.  At that point all discussion could move to the extension project.

**Comment by jfojtl** [comment] 2023-01-10 13:01
@blueleader07 can I help you with the project? I need the support as well.

**Comment by blueleader07** [comment] 2023-01-23 15:41
@jfojtl did you happen to try the version that supports dynamodb?  Did it work for you?
https://www.npmjs.com/package/@blueleader07/typeorm

Next steps are to create so sort of plugin since the Typeorm maintainers do not want it merged to the main repo.  I haven't had time to do this ... but it shouldn't be terribly difficult.  I'm not entirely sure how to create a plugin without wrapping it the way we did it at my company.  Perhaps if I post the code others can provide feedback / guidance on what the community thinks would work best.

**Comment by blueleader07** [comment] 2023-04-16 21:28
OK folks.  I've published a separate NPM package that adds DynamoDB support for TypeORM.  This was at the recommendation of the TypeORM developer: @pleerock in the PR I submitted: https://github.com/typeorm/typeorm/pull/9352

Documentation is still pretty light, but I'll be adding to it soon.  If anyone would like to try it I would appreciate feedback.
https://github.com/blueleader07/typeorm-dynamodb

**Comment by kchow1985** [comment] 2023-05-12 23:05
@blueleader07 appreciate your work but it seems that if I use your package, then all the entity managers in all DataSource instances gets pointed to DynamoEntityManger instead. This is only good if the application only needs dynamodb connection. For my use case it doesn't work because I need to use both a mysql and dynamodb DataSource together.

**Comment by blueleader07** [comment] 2023-05-13 01:28
@kchow1985 just published typeorm-dynamodb@3.0.16 which adds back all the other datasource types.  

I usually keep to 1 datasource per service so I don't have that use case.  Please give it a try and let me know if you have any trouble.  Also you can open any issues (or even submit a PR) here:
https://github.com/blueleader07/typeorm-dynamodb/issues

**Comment by ygyg70** [comment] 2024-04-09 06:20
Is this thread still active? Does anyone know whether DynamoDB is supported?
Thanks!

**Comment by blueleader07** [comment] 2024-04-09 06:27
I submitted a PR but the TypeORM maintainers thought it was too big and should be maintained as a separate package.  Check out the package I published (been using in production for over 1 year):

https://www.npmjs.com/package/typeorm-dynamodb

**Closed** 2024-12-14 21:16 UTC
Labels: help wanted, accepting PRs, community, comp: drivers and platforms, new driver
