### ISSUE TITLE
simple-json entity returns SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by 7dobi** [typeorm/typeorm#8901] opened 2022-04-16 14:08 UTC
## Issue Description
The simple-json entity type returns SyntaxError: Unexpected end of JSON input

### Steps to Reproduce

User.ts
```typescript
    @Column("simple-json")
      prices!: {
        daily: number;
        hourly: number;
        weekly: number;
        monthly: number;
      };
```

controller.ts
```typescript
const user_repository= getRepository(User)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.14.0  | 
| Typescript version  | 4.6.2  | 
| TypeORM version     | 0.3.2  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | Yes|
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

**Comment by Ginden** [comment] 2022-04-16 20:43
@7dobi Your code doesn't allow reproduction of issue. Please provide more details, including stack trace.

**Comment by NourMaherT** [comment] 2022-06-12 08:16
I've been struggling with the same issue while working with typeorm for MySQL 
Category.ts:
```
@Column({ type: "simple-json" })
  life_stages: any;
```
And I enter 
```
"life_stages": {
    "male": 1,
    "female":  0,
    "children": 1,
    "pregnant": 1
  }
```
It's cool and goes into the DB but when I try to get it back by any find method I get this error
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.stringToSimpleJson (E:\Hala-projects\offers\backend\src\util\DateUtils.ts:236:49)
    at MysqlDriver.prepareHydratedValue (E:\Hala-projects\offers\backend\src\driver\mysql\MysqlDriver.ts:668:31)
    at E:\Hala-projects\offers\backend\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:244:29
    at Array.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transformColumns (E:\Hala-projects\offers\backend\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:210:26)
    at RawSqlResultsToEntityTransformer.transformRawResultsGroup (E:\Hala-projects\offers\backend\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:158:33)
    at E:\Hala-projects\offers\backend\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:50:33
    at Map.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transform (E:\Hala-projects\offers\backend\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:49:15)
```

**Comment by Ginden** [comment] 2022-06-12 16:23
Closing - no reproducible code was given.

**Closed by Ginden** 2022-06-12 16:23 UTC
Labels: bug, needs more info

**Comment by mrodrigues-fsl** [comment] 2023-03-30 18:58
I don't know why it is happening for @7dobi , but for me, it was because I had this huge value that wasn't fitting on the column, so it ended up truncated and it ends up as an invalid JSON.

**Comment by eulisesquidel** [comment] 2023-07-10 17:55
I got this error, in my case the problem was a JSON column, when I persist de "" string empty as a value, after  when I trying to get retrive de data I got this error. 
I solved  this when I saved {} instead "" in JSON value.
