### ISSUE TITLE
Multiple row insert oracle query using query builder is wrong

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [typeorm/typeorm#2824] opened 2018-09-20 07:23 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using query builder to perform multi row insert into oracle generates query which does not comply with oracle.

```
@Entity('ADM_USER')
export default class User {
    @PrimaryGeneratedColumn({ name: 'ID' })
    id: number;

    @Column({ name: 'NAME' })
    name: string;

    @Column('simple-json', { name: 'PROFILE' })
    profile: { age: number };

    @Column({ name: 'CODE' })
    code: string;

    @CreateDateColumn({ name: 'CREATED_AT', type: 'timestamp with time zone' })
    createdAt: Date;
}

this.connection = await createConnection({
      name: 'oracle',
      type: "oracle",
      host: "****",
      port: 1521,
      username: "admin",
      password: "***",
      extra: { poolMax: 10, poolMin: 1 },
      sid: "ORCL",
      entities: [User],
      logger: 'simple-console',
      logging: true
    });
   const queryBuilder = this.connection.createQueryBuilder();
   await queryBuilder.insert().into(User).values([
     { name: 'Prashant', code: 'usr001122' },
     { name: 'Aniket', code: 'usr099999'}
   ]).execute();
```
query failed: INSERT INTO "ADM_USER"("ID", "NAME", "PROFILE", "CODE", "CREATED_AT") VALUES (DEFAULT, :i0_NAME, DEFAULT, :i0_CODE, DEFAULT), (DEFAULT, :i1_NAME, DEFAULT, :i1_CODE, DEFAULT) RETURNING "ID", "CREATED_AT" INTO :output_ID, :output_CREATED_AT -- PARAMETERS: ["Prashant","usr001122","Aniket","usr099999",{"type":2002,"dir":3003},{"type":2003,"dir":3003}]
error: { [Error: ORA-00933: SQL command not properly ended] errorNum: 933, offset: 124 }
(node:14324) UnhandledPromiseRejectionWarning: QueryFailedError: ORA-00933: SQL command not properly ended

**Comment by Kononnable** [comment] 2018-09-29 21:42
Duplicate of #2434

**Closed by Kononnable** 2018-09-29 21:42 UTC
