### ISSUE TITLE
Future of TypeORM

### ISSUE THREAD

**Issue by dominicdesu** [typeorm/typeorm#2784] opened 2018-09-09 20:10 UTC
Hello,
first of all I would like to say that this is awesome work you've done here. 
As I am considering this library for production use, may I ask what the future plans for TypeORM are?
The docs mention that the 1.0 release is planned for autumn 2018. Is this still valid?
As there doesn't seem to be much activity from the maintainers in the last few weeks, I am wondering if there is some specific reason for this (no time currently, no interest anymore...)?

Please don't get me wrong, I can see that you've put a tremendous amount of effort in creating this library and I really appreciate it! Just curious about the future of this library.

**Comment by pleerock** [comment] 2018-09-10 05:44
Hello, 

> The docs mention that the 1.0 release is planned for autumn 2018. Is this still valid?

Right, we were planning 1.0 release for autumn and before that for summer and before that for spring. But it does not matter. TypeORM is already kinda 1.0 despite current 0.2.x version. Don't look to a number it doesn't really tell anything. You can release library in a first day and say its 1.0 or you can do library for 10 years and never release 1.0. What really important is how its being developed. In my opinion TypeORM is ready enough to be 1.0.

> As there doesn't seem to be much activity from the maintainers in the last few weeks, I am wondering if there is some specific reason for this (no time currently, no interest anymore...)?

no time currently unfortunately. Few weeks or even month isn't that long period actually. Currently due to change of my job I can't spend full time on TypeORM (I did that for over two years and spent all my spendings on doing this interesting, but free job). I would really like to quite my main job and spend full time on TypeORM but unfortunately I can't afford it right now and unfortunately people aren't active in donations. 

Again, TypeORM is quite stable already, it is complex and its maintenance need help from the community. I have lot of cool stuff I want bring to TypeORM, I just need time. The most simple help can be answering questions in the repositories and close people issues. Currently I have 300+ notifications from typeorm repository and they all need my attention. You can't imagine how much of my free time it will take to review and answer them all. So help from the community is really valuable here.

**Comment by elthrasher** [comment] 2018-09-10 11:48
@pleerock The community is here and willing to help. I'm sure you haven't had time to follow the glitter chat, but lots of folks want to help and plenty chime in issues and open PRs to fix them, but we have no way to merge PRs or release new versions. Many of us are still waiting on 0.2.8 which contains some important bug fixes. I am stuck on 0.1.11 until 0.2.8 is released. How can we best help this project move ahead?

**Comment by Kononnable** [comment] 2018-09-10 14:37
If I remember correctly #2531 was blocking release of 0.2.8, so resolving the issue should help. The problem is that solution need to be tested in every driver which uses `typeorm/browser` so knowledge of a few specific technologies is needed.

**Comment by pleerock** [comment] 2018-09-10 17:31
correct #2531 is blocking currently and looks like @daniel-lang is very busy and can't help currently. So we need to fix that without him

**Comment by pleerock** [comment] 2018-09-10 18:03
I never tested and used typeorm on mobiles by myself, so its good if someone can take them all and handle all the cases

**Comment by dominicdesu** [comment] 2018-09-10 20:49
@pleerock thanks for your statement! Of course I know that people get busy and that it is very time consuming to manage an open source project, especially one whose user base is growing fast. This project has two maintainers and probably 1000 people with newbie questions/issues like me, so, as I mentioned before, I have huge respect for what you've built here.

As I think this is an awesome library, of course I want to see it move forward. Most important point is that you haven't lost interest 😃 . Secondly, especially as you're time seems to be limited, maybe there are some ways to encourage the community to help close issues and answer questions? Maybe there are contributers willing to take over some kind of moderation of the tickets if they are asked? They could filter out the questions and mark the important issues.
Also I think it is important that PRs get at least a reply, maybe a thanks and in which time frame they will be considered for review and merging. There are many people willing to contribute, however if I make a PR for an issue which is important for me, it is kind of frustrating if nothing is happening to it for weeks.

Probably I discovered TypeORM at a bad time (about 2 month ago), as it seems to have been much more active before, but I really would love to see it growing and thriving! Even if it is just one ticket/PR a day or even a week (by you or by another moderator), seeing some activity would be awesome.

This post is meant to contain 0% criticism and 100% gratitude and the desire for TypeORM to continue growing. 👍

**Comment by pleerock** [comment] 2018-09-12 15:17
> Most important point is that you haven't lost interest 😃

Of course I haven't. I have spent three years of my life on it, I won't simply loose interest. Working with the database is fundamental in most apps, so this topic forever will be relevant to me. Btw I think you have watched for only master branch and activity in issues and prs but I did some changes on `next` branch recently.

> Also I think it is important that PRs get at least a reply, maybe a thanks and in which time frame they will be considered for review and merging. There are many people willing to contribute, however if I make a PR for an issue which is important for me, it is kind of frustrating if nothing is happening to it for weeks.

Yeah completely agree, in this case I hope for people understanding.

> Probably I discovered TypeORM at a bad time (about 2 month ago)

Unfortunately yes, but I won't call it "bad time". This happens sometimes and its completely fine. 

> Secondly, especially as you're time seems to be limited, maybe there are some ways to encourage the community to help close issues and answer questions? Maybe there are contributers willing to take over some kind of moderation of the tickets if they are asked? They could filter out the questions and mark the important issues.

Yeah sure, lets first see who is going to take such initiative. @Kononnable is one of them as I know. Who else? We can keep traction in this ticket.

Unfortunately reality is that people are really active on what they need and aren't on what they don't. If they use a good product that is being hardly maintained - they don't care, but once it gets some issues they start complaining (Im not talking about you, you are somebody who is new to TypeORM, really appreciate what you did here). Most of open source projects die because of this, maintainers get tired spending their time for free. I won't let TypeORM die, but I do want people to realize on what price open source comes and realize how help is important, its important for both sides.

I'm glad that you have opened this issue, lets see how many people will be interested in. Really appreciate that you have opened this ticket. We see lot of "👍" so lets see if people can suggest something other then just like.

**Comment by feather-jmalone** [comment] 2018-09-15 18:47
i'd just like to show some additional love for typeorm. i've been using it since july of last year, and it's at the core of a production API I built. i really love it.

i'm not able to actively contribute code to the project, but i promise to be more active in this community, responding to questions when i know the answer or can help someone. 

in my mind, what will really take typeorm to the next level is top notch documentation and examples. the docs right now are _pretty_ good... but as someone who has been using typeorm for 15 months, i feel like there's so much more that could be written for newcomers, stuff that would have helped me SO much when i was starting out. a few examples off the top of my head: 1) not just _how_ something works, but _why_, 2) the performance implications of doing something one way vs another, 3) the importance of migrations (granted, this is not a typeorm specific-thing), or 4) the importance of understanding what typeorm is actually doing under the hood by having exhaustive logging enabled during development.

greater adoption and contribution starts with docs that make you think "these people really care about the project and want its users to enjoy working with it." it's a sense i get strongly from this community, but not from the documentation.

so on that point... i'd love to propose documentation edits from time to time. is the best process for doing that simply to open a PR? or is there another preferred way to propose->discuss->document for non 'code' contributions?

anyway, i remain an avid typeorm user and advocate, and i really hope to see this project continue to flourish! (it better, i'm using it pretty heavily in prodution, haha)

**Comment by afurculita** [comment] 2018-09-16 16:54
We'll also need for someone with proper permissions on this repository to properly labeled the issues that have been discussed, but not yet closed.

**Comment by Kononnable** [comment] 2018-09-17 05:37
@feather-jmalone Unless someone wants to rewrite half of documentation at once using just PRs should be fine. It's easier to discuss documentation if you see exact changes.

**Comment by elthrasher** [comment] 2018-09-17 11:42
56 PRs open and many are probably good to go. What's a good process for moving forward here? Understand we don't want to hand merge rights out to everybody. @pleerock do you have enough time to be a 2nd reviewer on things that have already been flagged as ready? Want to have @Kononnable do that?

**Comment by afurculita** [comment] 2018-09-25 08:48
@pleerock did you made any decision regarding a second reviewer on the existing PRs? Some PRs are mergeable, others are easy to review. Do you want @Kononnable to be the second reviewer if he agrees to do it?

**Comment by eddieajau** [comment] 2018-09-26 04:05
@pleerock I'm happy to put my hand up to help out where I can. Perhaps it would be good to organise a hangout or two where you can "train" community helpers on how TypeORM works, where TypeORM is headed, how we can help with support and be supported ourselves, etc.

**Comment by championswimmer** [comment] 2018-09-26 16:01
@pleerock @daniel-lang 
Ok a bit of an update

First I must take responsibility of adding *nativescript* support as that broke the release cycle. It prevented releasing 0.2.8 and the only way to fix it _**properly**_ is by breaking `react-native` support. 

I have a solution for now. 

https://github.com/typeorm/typeorm/pull/2854

**Comment by NoNameProvided** [comment] 2018-09-26 16:12
@pleerock Which amount of monthly support is needed to allow you to work on TypeORM full-time? I already support TypeORM on Open Collective, but as I see you have never taken any money from there. Maybe you can create a Patreon page, so people can support you directly?

**Comment by pleerock** [comment] 2018-09-27 10:58
@NoNameProvided 

> but as I see you have never taken any money from there.

yeah I had plan to get them and split between me and @AlexMesser - main typeorm developers. But current amount isn't significant, besides the fact that I wanted to left some money on typeorm marketing. That's why they are still in there.

> Which amount of monthly support is needed to allow you to work on TypeORM full-time

full time basically means leaving current job, projects, etc. and join full time to TypeORM. At the beginning 100k annually is enough to support two developers full time on TypeORM. But reality is open source... well, we know about it.

> Maybe you can create a Patreon page, so people can support you directly?

opencollective is basically the same.

**Comment by pleerock** [comment] 2018-09-27 11:16
Here is what right now what community can do:

* we need people who can take responsibility over react-native and ionic support in typeorm, this is the most important right now
* there are 500+ opened issues. At least half of them can be closed for sure since some of them are questions, some of them are duplicates. Community can go over each opened issue, review it and see if they can answer or how they can help in that issue
* there are 60+ PRs. TypeORM is very complex and 90% if PR looks a bit complex only I should merge it. Community can review PRs and left feedback on each of them, this will help me to merge PR and speed up additional improvements in PRs
* improve it, improve docs, just what they could do all the time
* donate or ask your company to donate

We can make it effective if I almost don't look at issues, just reviewing and merging PRs, and community working on issues and support.

I opened a slack group for typeorm, [join here](https://join.slack.com/t/typeorm/shared_invite/enQtNDQ1MzA3MDA5MTExLTFiNDEyOGUxZGQyYWIwOTA0NDQxODdkOGQ0OTUxNzFjYjUwY2E0ZmFlODc5OTYyYzAzNGM3MGZjYzhjYTBiZTY) (last time community to migrate to slack from gitter).

**Comment by Kononnable** [comment] 2018-09-27 15:09
@pleerock It would be great if you could close/label issues or give someone rights to do that - going through open issues without closing them/marking as questions, discussion, bugs will be a lot more work. Right now everyone who wants to help with issues have to read through some of them just to find out there is nothing we can do(e.g. they're already resolved).

**Comment by pleerock** [comment] 2018-09-27 18:15
@Kononnable sure, sent you invite. You can write me directly to slack when you need.

**Comment by championswimmer** [comment] 2018-10-03 05:07
@pleerock when can we have a new 0.2.8 release ?

**Comment by pleerock** [comment] 2018-10-20 10:08
0.2.8 is released. I think this can be closed. Both community and maintainers heard each other. Let's see how this is going to work in practice.

**Closed by pleerock** 2018-10-20 10:08 UTC

**Comment by bmax** [comment] 2019-09-30 18:53
@pleerock hi,

I was wondering if there was a new invite to the slack channel the one in the CONTRIBUTING.MD and one above says link is expired.. I can update the docs if you send me a new link.

Thanks!

**Comment by titoOpenDev** [comment] 2020-06-17 04:22
It's the slack channel still active ?

**Comment by eranganovade** [comment] 2021-05-18 05:44
Try this link:
https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g
