### ISSUE TITLE
`npm run start` fails silently (Ubuntu 18.04, TypeORM 0.2.25)

### ISSUE THREAD

**Issue by lx30011** [typeorm/typeorm#6420] opened 2020-07-19 08:54 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm running a Ubuntu 18.04 WSL environment.
postgresql version 10+190ubuntu0.1
node version 14.0.0
npm version 6.14.4

I setup a very basic TypeORM project using the CLI and following command: `typeorm init --name server --database postgres`.

When running the default start script with `npm run start`, the server fails silently. It loads for a few seconds (probably compiling the TypeScript files) and then exits.

```shell
user@DESKTOP-5BR4FQG:~/projects/jwt-project/server$ npm run start

> server@0.0.1 start /home/user/projects/jwt-project/server
> ts-node src/index.ts

user@DESKTOP-5BR4FQG:~/projects/jwt-project/server$ 
```
(screenshot: https://i.imgur.com/h2hIPqX.png)

My `ormconfig.json` file looks like this:
```json
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "dev",
  "password": "test",
  "database": "jwt",
  "synchronize": true,
  "logging": false,
  "entities": ["src/entity/**/*.ts"],
  "migrations": ["src/migration/**/*.ts"],
  "subscribers": ["src/subscriber/**/*.ts"],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
}
```

My `package.json` file looks like this:
```json
{
  "name": "server",
  "version": "0.0.1",
  "description": "Awesome project developed with TypeORM.",
  "devDependencies": {
    "@types/node": "^14.0.23",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.7"
  },
  "dependencies": {
    "pg": "^7.3.0",
    "reflect-metadata": "^0.1.10",
    "typeorm": "^0.2.25"
  },
  "scripts": {
    "start": "ts-node src/index.ts"
  }
}
```

postgresql output
```bash
user@DESKTOP-5BR4FQG:~/projects/jwt-project/server$ sudo -i -u postgres 
postgres@DESKTOP-5BR4FQG:~$ psql
psql (10.12 (Ubuntu 10.12-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 dev       | Superuser                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

postgres=# \l
                              List of databases
   Name    |  Owner   | Encoding | Collate |  Ctype  |   Access privileges   
-----------+----------+----------+---------+---------+-----------------------
 jwt       | postgres | UTF8     | C.UTF-8 | C.UTF-8 | 
 postgres  | postgres | UTF8     | C.UTF-8 | C.UTF-8 | 
 template0 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
           |          |          |         |         | postgres=CTc/postgres
 template1 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
           |          |          |         |         | postgres=CTc/postgres
(4 rows)

postgres=# 
```

What I checked:

- the user dev exists (verified by running `\du` in the psql CLI)
- the database jwt exists (verified by running `\l`)
- the credentials are correct
- the postgresql service is running (verified by running `sudo service postgresql status` with output `10/main (port 5432): online`)
- the user dev has superuser permissions

I used following guides to setup postgresql but I'm pretty sure I setup everything correctly:
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-postgresql
https://www.youtube.com/watch?v=-LwI4HMR_Eg

Thank you for taking the time and helping me fix this. I'm out of ideas.

**Comment by bhavc** [comment] 2020-07-19 19:17
Having the exact same problem on Ubuntu desktop 18.04 lts. Ran the quickstart as described a couple of days ago and it worked as expected but doesn't work anymore.

**Comment by imnotjames** [comment] 2020-09-30 02:40
This is a duplicate of #5949 - If you'd like, please continue the discussion there.  Cheers!

**Closed by imnotjames** 2020-09-30 02:40 UTC
Labels: duplicate
