### ISSUE TITLE
Cannot set property EntityManager of #<Object> which has only a getter

### ISSUE THREAD

**Issue by AuspeXeu** [typeorm/typeorm#6054] opened 2020-05-12 19:58 UTC
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

```
TypeError: Cannot set property EntityManager of #<Object> which has only a getter
    at Object.<anonymous> (/usr/src/app/node_modules/typeorm/index.js:120:23)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/lib/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
```

Somehow getting this random error now and have. Literally tried rolling back my code and everything. Any suggestions where to look?

**Comment by tombh** [comment] 2020-05-12 20:08
Seeing this as well on new CI builds only in the last few hours. Hadn't made any changes at all. So maybe it's a dependency updated somewhere?

**Comment by mgabeler-lee-6rs** [comment] 2020-05-12 20:12
`tslib` updated which is exposing a pre-existing issue with double-exporting symbols:

* https://github.com/typeorm/typeorm/blob/master/src/index.ts#L105
* https://github.com/typeorm/typeorm/blob/master/src/index.ts#L141

TSLib behavior change and other folks having problems with it have been reported there:
* https://github.com/microsoft/tslib/issues/103
* https://github.com/microsoft/tslib/issues/102

**Comment by IncoCode** [comment] 2020-05-12 20:27
Temporary workaround:
`npm i tslib@1.11.2 --save` and remove `^` before version in `package.json`:
```
...
"tslib": "1.11.2",
...
```

**Comment by Wuzi** [comment] 2020-05-12 20:47
Had this problem today when installing dependencies, rolled back to a previous `package-lock.json` and fixed the problem.

**Comment by ggaj** [comment] 2020-05-12 20:56
I have some problem...

some solution?? ... for us in new version...

Thanks

**Comment by leon-developer-br** [comment] 2020-05-12 21:21
I have the same problem.

Any solution? Thx

**Comment by alexeynobody** [comment] 2020-05-12 21:45
I have the same problem. This is fantastic!

**Comment by eddieajau** [comment] 2020-05-12 21:46
Still diagnosing but in case this helps someone, it appears that even locking to `tslib@1.11.2`, a clean `yarn` install will still manifest this error. However a clean `npm` install will allow my app to run fine. Very odd.

**Comment by alexeynobody** [comment] 2020-05-12 22:30
> Temporary workaround:
> `npm i tslib@1.11.2 --save` and remove `^` before the version in `package.json`:
> 
> ```
> ...
> "tslib": "1.11.2",
> ...
> ```

This is work fine or use in CI TypeORM from project (not installed globally)

**Comment by kyleamazza** [comment] 2020-05-12 23:16
Also can confirm that `npm i tslib@1.11.2` and removing the `^` works when installed as a local dependency.

**Comment by felipellrocha** [comment] 2020-05-13 04:23
I am also having the same issue. The workaround, however, is not working for me

**Comment by SevenElement** [comment] 2020-05-13 04:23
I have the same problem.

**Comment by felipellrocha** [comment] 2020-05-13 04:25
Ehr, I can confirm that npm works fine, yarn breaks. Weird.

**Comment by possible819** [comment] 2020-05-13 06:50
Edit your package.json at your project root directory to avoid using latest version of tslib

```
  "resolutions": {
    "tslib": "1.11.2"
  }
```

**Comment by lotstar87** [comment] 2020-05-13 06:51
@possible819 you've saved my time.

**Comment by PodaruDragos** [comment] 2020-05-13 08:21
you can keep typescript 3.9.2
and just add tslib 1.11.2

this seems to work

**Comment by Taerarenai** [comment] 2020-05-13 08:25
Any way to make this work with the CLI tho' ? I wanted to use the typeorm CLI to create the project (installed globally), but then this happened.

**Comment by georgekrax** [comment] 2020-05-13 13:37
Have the same problem. After waking up, re-configuring my computer, because of Ubuntu, and after-hours seeing this error. When of course, the day before I had arranged to code something really special!

**Comment by georgekrax** [comment] 2020-05-13 14:40
Okay, I fixed it and with **yarn**!!! After adding `tslib@1.11.2`, I checked the version and the syntax to be correct in the `package.json` file. Then, as it is stated above I also added, at the end of the `package.json` file, this:

```
...
  "resolutions": {
    "tslib": "1.11.2"
  }
...
```

**Important:** If you install `tslib@1.11.2` with **npm**, make sure to remove the `package-lock.json` file. For some reason, it also asked my to re-install `reflect-metadata`.

Finally, I fixed it and everything works correctly right now! Thank you for the support guys.

**Comment by KikeMendez** [comment] 2020-05-13 15:12
@possible819 Thanks legend!!

**Comment by georgekrax** [comment] 2020-05-13 15:15
Your welcome. Always nice to help, if I have the solution why I do not let others to solve their issues too!

**Comment by sephirothmk** [comment] 2020-05-13 15:30
Is there a way to fix this without using yarn?

**Comment by ivansieder** [comment] 2020-05-13 15:31
> Also can confirm that `npm i tslib@1.11.2` and removing the `^` works when installed as a local dependency.

@sephirothmk you could - in the meantime - install tslib manually and fix it to the 1.11.2 version.

**Comment by rrrix** [comment] 2020-05-13 17:29
Yarn users can also try a semver range that explicitly excludes `tslib@1.12.0` - assuming this gets fixed in `tslib@1.13.0` (if not, reminding you to check again). 

Also, a friendly reminder that it's never really a good idea to pin a version of a core library (like tslib) **forever** until the end of time. You might need those updates eventually! 

```json
  "resolutions": {
    "tslib": "^1 <1.12.0 || ^1.13.0"
  },
```

**Comment by csgruenebe** [comment] 2020-05-13 18:51
Ok came here hours ago and nothing worked. 
Until I realized there was a broken migration which we run automatically during startup with
`await connection.runMigrations()`
And the error is totally not related to the broken migration but it was it. So check for you last migration files and maybe the error lies there. Cost me hours fiddling with all the dependency versions

**Comment by xuemengfei** [comment] 2020-05-14 01:23
ts 3.8 + tslib 1.13.0 works for me

https://github.com/microsoft/tslib/issues/102#issuecomment-628296863

**Comment by drtyh2o** [comment] 2020-05-14 13:32
tsc 3.9.2 + tslib 2.0.0 seems to resolve

**Comment by JuniorTrojilio** [comment] 2020-05-14 13:55
tsc 3.9.2 + tslib 1.11.2 resolved for me for now

**Comment by georgekrax** [comment] 2020-05-14 14:01
**tslib@^2.0.0** works fine for me, with `yarn` & `TypeORM`.

**Comment by ramosht** [comment] 2020-06-04 11:25
> Edit your package.json at your project root directory to avoid using latest version of tslib
> 
> ```
>   "resolutions": {
>     "tslib": "1.11.2"
>   }
> ```

Worked for me!

**Comment by dyatko** [comment] 2020-06-14 14:44
Still reproducible:

```
typescript@3.9.5
tslib@2.0.0
typeorm@0.2.25
```

**Comment by SpencerKaiser** [comment] 2020-07-21 21:28
For what it's worth, I deleted `node_modules` and re-ran `npm i` and the issue resolved itself ¯\\_(ツ)\_/¯

**Comment by imnotjames** [comment] 2020-10-05 05:06
Cannot reproduce this issue.  Closing.

**Closed by imnotjames** 2020-10-05 05:06 UTC

**Comment by degoprisss** [comment] 2022-04-08 01:18
Lo que hice fue regresar mi versión de typeorm a la version 0.2.4. El problema se fue enseguida.

**Comment by ks221197** [comment] 2022-04-11 11:13
> Lo que hice fue regresar mi versión de typeorm a la version 0.2.4. El problema se fue enseguida.

yes me too but did you have any other solution which work with typeorm latest version.

**Comment by Chethana-it** [comment] 2022-04-13 09:24
Same issue is with me. Cannot set property metadata of #<Repository> which has only a getter

**Comment by degoprisss** [comment] 2022-04-13 14:29
> > Lo que hice fue regresar a mi versión de typeorm a la versión 0.2.4. El problema se fue enseguida.
> 
> sí, el mío también, pero ¿tuvo alguna otra solución que funcione con la última versión de typeorm?

Nada amigo, por el momento esa es la unica solución que he podido encontrar.

**Comment by wsr2k2** [comment] 2022-05-14 12:52
> "tslib": "1.11.2"

here too

**Comment by FrouniS** [comment] 2022-05-21 12:29
getting tslib with npm didn't fix it for me , still having the same error

**Comment by a7urag** [comment] 2023-02-08 11:04
Changed import to
import * as typeorm from 'typeorm/globals';

**Comment by sespinoza-dev** [comment] 2023-10-03 11:54
This bug can still be reproduced.

```
typeorm@0.3.17
typescript@5.1.6
tslib@2.6.2
```
