### ISSUE TITLE
sql error - primary key values are not quoted in 'in' operator in queries

### ISSUE THREAD

**Issue by danelkhen** [typeorm/typeorm#275] opened 2017-02-10 14:42 UTC
Happens in v0.0.8, doesn't happen in v0.0.7-alpha.1

I'm using sqlite driver, in my case the primary key is a string that sometimes contains colons.

example sql (summarized):
```
SELECT "t"."key" AS "t_key" FROM "fs_entry" "t" LEFT JOIN "by_filename" "md" ON "t"."basename"="md"."key" WHERE "t"."key" IN (UNQUOTED:STRING:VALUE)
[2] api action error { Error: SQLITE_ERROR: unrecognized token: ":" errno: 1, code: 'SQLITE_ERROR' }
```

**Comment by pleerock** [comment] 2017-02-10 16:43
can you please provide a minimal reproduction code sample?

**Comment by danelkhen** [comment] 2017-02-13 11:51
Sure:


```
@Table()
export class ByFilename  {
    @PrimaryColumn() key: string;
}

@Table()
export class FsEntry implements C.FsEntry {
    @PrimaryColumn() key: string;
    @Column(CT.STRING, { nullable: true }) @Index() basename: string;
}

db.fsEntries.createQueryBuilder("t").leftJoinAndMapOne("t.md", ByFilename, "md", "t.basename=md.key");
```

**Comment by danelkhen** [comment] 2017-02-28 10:20
Actually always happens with sqlite driver whenever primary key is varcahr - keys are not quoted, even on ```repo.find()```

**Comment by pleerock** [comment] 2017-06-30 13:17
Closing it because it was already fixed. Please let me know if it does not work for you in latest versions.

**Closed by pleerock** 2017-06-30 13:17 UTC
