### ISSUE TITLE
Explicit 'null' required to delete foreign key field?

### ISSUE THREAD

**Issue by Ionaru** [typeorm/typeorm#5454] opened 2020-02-01 17:32 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Given these two simple entities:
```ts
@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number;

    @ManyToOne(() => Rank, {
        nullable: true,
    })
    rank?: Rank;
}
```
```ts
@Entity()
export class Rank extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number;

}
```
The following code demonstrates the current behaviour.
```ts
// Assume existing entities:
// rank: {id: 1}
// user: {id: 1, rank: 1}

delete user.rank;
await user.save(); // Does not update the entity.

user.rank = undefined;
await user.save(); // Does not update the entity.

// @ts-ignore
user.rank = null; // TS2322: Type 'null' is not assignable to type 'Rank | undefined'.
await user.save(); // This does update the entity.
```

The means that the `rank` property needs to have its type modified to `Rank | null`. Is this intentional? 

I'd rather not use `null` in my codebase and have been using the [tslint](https://palantir.github.io/tslint/rules/no-null-keyword/) philosophy regarding the `null` keyword.

**Comment by Ionaru** [comment] 2020-02-01 17:47
This also seems to extend to regular column values, `delete entity.attribute` or `entity.attribute = undefined` does nothing.

**Comment by Ionaru** [comment] 2020-02-02 01:22
A model like this:
```ts
@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column({
        nullable: true,
    })
    public name?: string | null;

}
```
Will give the error: `DataTypeNotSupportedError: Data type "Object" in "User.name" is not supported by "mysql" database.`

So how do I make my columns nullable without having to explicitly define the type of the column.

**Comment by ejose19** [comment] 2020-04-29 18:06
@Ionaru Currently, there's no other way. "string | null" gets reflected to Object as [pleerock said](https://github.com/typeorm/typeorm/issues/2567#issuecomment-408599335) so a patch would be needed to ignore null type when nullable is true.

Regarding why entity.attribute = undefined (and delete entity.attribute) does not set the field to null is because .save() methods assumes undefined means no change (since it's working with Partial\<Entity\>), so one needs to explicitly assign to null for it to persist on db.

I agree this makes codebase a bit ugly due to relying on both null | undefined, but since typeorm works that way you can't use that no-null-keyword rule.

**Comment by shusson** [comment] 2020-08-03 07:00
I also just ran into this issue. As https://github.com/typeorm/typeorm/issues/5454#issuecomment-581087022 pointed out, you can't update your entities to use a type like `type Nullable<T> = T | null;` because of `DataTypeNotSupportedError: Data type "Object" ...`. Basically you are stuck to type asserts if you really want to save a null value.

**Comment by JemarJones** [comment] 2021-01-22 02:47
I'm really shocked to discover that something as fundamental as just setting a column value to null seems to be unsupported without some hacky solution. Is Typeorm ready for production?

**Comment by nebkat** [comment] 2021-01-22 14:19
It is supported and the limitations described here are because of the TypeScript reflection system. `null as any` is safer to use than `@ts-ignore`. But also the simple workaround is to just manually set the type of column to "varchar" or similar in the case of a nullable string.

**Comment by imnotjames** [comment] 2021-07-09 17:17
To make the columns nullable you  MUST explicitly define the type.

> I'm really shocked to discover that something as fundamental as just setting a column value to null seems to be unsupported without some hacky solution. Is Typeorm ready for production?

This is entirely a problem with Typescript and not TypeORM directly.  It's not a hacky solution to be explicit in your typing.

However, I do think we should revisit the reflection typing for TypeORM and prevent guesswork in some cases.  Unfortunately, that's orthogonal to this issue.

**Comment by imnotjames** [comment] 2021-07-09 17:18
Also, yes, it is expected that you have to set something to null to remove it.

If you set it to `undefined` we assume that it's because the field was omitted from selection and should be ignored entirely.

**Closed by imnotjames** 2021-07-09 17:18 UTC
Labels: driver: mariadb, driver: mysql, question

**Comment by RIP21** [comment] 2021-08-06 13:21
So it's now impossible to have fields `string | null` etc. as I understood. What's the workaround? To explicitly set the type of the field not relying on reflection info?

**Comment by imnotjames** [comment] 2021-08-06 19:53
> So it's now impossible to have fields `string | null` etc. as I understood. What's the workaround? To explicitly set the type of the field not relying on reflection info?

Yes.  This is because typescript does not expose the information needed to infer nullable types.

**Comment by RIP21** [comment] 2021-08-06 21:53
But if I try to set type explicitly e.g. `@Column({ nullable: true, type: "string"})` it fails as it still uses metadata.
The only workaround I found so far is to use in top of the field with `null` e.g. for `number | null` it will be
`@Reflect.metadata('design:type', Number)` and `String` and `Boolean` for all primitives, for all other types it seems to work fine.
And, indeed, `Nest.js` decorators that are generating GraphQL types also got broken and a similar hack as above is needed.

As I'm pretty unfamiliar with what is getting emitted I may be missing something important, @imnotjames any hints on what problems I may encounter with such an approach?

Thanks!

**Comment by imnotjames** [comment] 2021-08-06 22:11
> But if I try to set type explicitly e.g. @Column({ nullable: true, type: "string"}) 

Sorry, what is the issue you're seeing there?  You're using CockroachDB?

You're welcome to open a new issue if you believe this is actually an issue.


> As I'm pretty unfamiliar with what is getting emitted I may be missing something important, @imnotjames any hints on what problems I may encounter with such an approach?

I have no idea.

**Comment by RIP21** [comment] 2021-08-06 22:33
@imnotjames I'm using MySQL. I'll give more examples tomorrow and then you'll let me know if I'm missing something or if it's unexpected behavior. Now I have to sleep :)
It's related to this issue more or less.

**Comment by imnotjames** [comment] 2021-08-06 22:42
`"string"` is a CockroachDB type, not MySQL.

The original issue here was that they had tried to assign `null` to a type that didn't accept it - which isn't really how TypeORM works.

**Comment by RIP21** [comment] 2021-08-07 22:10
@imnotjames alright, you're correct, if I set `varchar` into `type` instead of `string` and `boolean` or `tinyint` for boolean etc. etc. it all works nicely with  `primitive | null`. So no issues :) No `@Reflect.metadata` hacks needed :)
