### ISSUE TITLE
@Column which type is 'datetime' will be altered everytime when server restart 

### ISSUE THREAD

**Issue by foolseward** [typeorm/typeorm#4664] opened 2019-08-29 15:18 UTC
**Issue type:**

[ ] question
[ * ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ * ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ * ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ] `mysql`
    [x] `postgres`

    Also, please format your code properly (by taking code blocks into 
```ts 
  @Column({
    type: 'datetime',
    nullable: true
  })
  concern_time: Date; 
```)
!>

everytime i restart my app, the sql bellow will excute again
```sql
ALTER TABLE `qc_concern_company` CHANGE `concern_time` `concern_time` datetime NULL
```
the column define in typeorm
```ts

```

**Comment by foolseward** [comment] 2019-08-30 00:03
```ts
  @Column({
    type: 'datetime',
    nullable: true
  })
  concern_time: Date;
```
everytime i restart my app, the sql bellow will excute again
```sql
ALTER TABLE `qc_concern_company` CHANGE `concern_time` `concern_time` datetime NULL
```

**Comment by ardyfeb** [comment] 2019-08-31 05:43
Duplicate #1960

**Comment by Kononnable** [comment] 2019-10-15 13:23
Duplicate of #2333

**Closed by Kononnable** 2019-10-15 13:23 UTC
