### ISSUE TITLE
Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: files.id

### ISSUE THREAD

**Issue by harishajdarevic** [typeorm/typeorm#919] opened 2017-09-20 20:54 UTC
Hello,

We are struggling for this almost whole day and we don't see where is the problem. Everything seems good but we realized that somehow after second connection to database and calling different queries we loose PRIMARY KEY at files table.

Here is what we have and what we call to get error Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: files.id

**user.entity.ts**

```
import { Entity } from 'typeorm/decorator/entity/Entity';
import {Column, OneToMany, PrimaryGeneratedColumn} from 'typeorm';
import {Sources} from './sources.entity';

@Entity()
export class Users {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column("varchar", { nullable: true})
  email: string;

  @OneToMany(type => Sources, source => source.user, {
    cascadeInsert: true,
    cascadeUpdate: true,
    cascadeRemove: true
  })
  source: Sources[];
}

```

**source_type.entity.ts**
```

import {Entity} from 'typeorm/decorator/entity/Entity';
import {Column, OneToOne, PrimaryGeneratedColumn} from 'typeorm';
import { Sources } from './sources.entity';

@Entity()
export class SourceType {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToOne(type => Sources, sourcesType => sourcesType.sourceType, {
    cascadeInsert: true,
    cascadeUpdate: true,
    cascadeRemove: true
  })
  source: Sources;
}

```

**sources.entity.ts**

```
import {Entity} from 'typeorm/decorator/entity/Entity';
import {Column, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn} from 'typeorm';
import { SourceType } from './source_type.entity';
import { Users } from './user.entity';
import {SourcesPaths} from "./sources_paths.entity";
import {Files} from "./files.entity";

@Entity()
export class Sources {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToOne(type => SourceType)
  @JoinColumn()
  sourceType: SourceType;

  @ManyToOne(type => Users, users => users.source)
  @JoinColumn()
  user: Users;

  @OneToMany(type => SourcesPaths, sourcesPaths => sourcesPaths.source)
  sourcePath: SourcesPaths[];

  @OneToMany(type => Files, file => file.source)
  file: Files[];

}

```

**files.entity.ts**

```
import {Entity} from 'typeorm/decorator/entity/Entity';
import { Column, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn } from 'typeorm';
import {Sources} from './sources.entity';
import {FilesTags} from './files_tags.entity';

@Entity()
export class Files {

  @PrimaryGeneratedColumn()
  id: number;

  @Column('varchar', {length: 45})
  name: string;

  @Column('varchar', {length: 45, nullable: true})
  family_name: string;

  @Column('varchar', {length: 45, nullable: true})
  created_at: string;

  @ManyToOne(type => Sources, source => source.file)
  @JoinColumn()
  source: Sources;

  @OneToMany(type => FilesTags, fileTag => fileTag.file)
  fileTag: FilesTags[];
}

```

**insertUser function**
When we call insert function for the first time everything goes well. Data is inserted including data into files entity also. But on second call to insertUser() we are getting error
**Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: files.id**

In SQLite studio we saw that after first insert of files we loose primary key on files.id.
Are we doing something wrong or there is an issue in typeorm?

```
insertUser(): void {

    createConnection({

      type: 'sqlite',
      database: '../user.sqlite',
      entities: [
        Users,
        Sources,
        SourceType,
        Files
      ],
      autoSchemaSync: true,
    }).then( async connection => {

      // Here you can start to work with your entities
      const user = new Users();
      user.name = 'Mezenga1234';

     await connection.manager.save(user);

      const sourcetype = new SourceType();
      sourcetype.name = 'my_library';
     await connection.manager.save(sourcetype);

      const source = new Sources();
      source.name = 'my_source';
      source.sourceType = sourcetype;
      source.user = user;

     await connection.manager.save(source);

      const files = new Files();
      files.name = 'Haris.rvt';
      files.source = source;

      await connection.manager.save(files);

      console.log('Inserted');
      connection.close();

    }).catch(error => console.log(error));

  }
```

**Comment by iz-iznogood** [comment] 2017-09-20 21:56
Hello, what version are you using ?

**Comment by harishajdarevic** [comment] 2017-09-20 22:04
@iz-iznogood hello, I'm using   
  "typeorm": "0.1.0-alpha.38",

**Comment by harishajdarevic** [comment] 2017-09-21 07:29
I removed { length } attribute from all columns and it works. 

Is it possible that there is some issue with length ?

**Comment by iz-iznogood** [comment] 2017-09-21 12:24
Hi, so that I can understand your issue.
If you create a simple project with these 4 entity  classes, and you start the server with 

```ts
createConnection({

      type: 'sqlite',
      database: '../user.sqlite',
      entities: [
        Users,
        Sources,
        SourceType,
        Files
      ],
      autoSchemaSync: true,
    }).then(........)

```
and you do not execute any queries, then your stop and start the server again (so that the schema update runs again) do you still loose the Primary key ?

Can you test this on latest version ? There have been lots of changes regarding length on the last 2 versions

Also if the issue is still there can you upload a very simple project that reproduces it ?

**Comment by harishajdarevic** [comment] 2017-09-21 13:20
@iz-iznogood no, if I create there 4 entity classes start server and do the following:

```
 createConnection({

      type: 'sqlite',
      database: '../user.sqlite',
      entities: [
        Users,
        Sources,
        SourceType,
        Files,
      ],
      autoSchemaSync: true,
    }).then( async connection => {

      const user = new Users();

      user.name = 'Mezenga1234';

     await connection.manager.save(user);

      const sourcetype = new SourceType();
      sourcetype.name = 'my_library';
      await connection.manager.save(sourcetype);

      const source = new Sources();
      source.name = 'my_source';
      source.sourceType = sourcetype;
      source.user = user;
      const sourceInserted = await connection.manager.save(source);

      console.log(sourceInserted);

      const files = new Files();
      files.name = 'Haris.rvt';
      files.source = source;




    const insertedFiles = await connection.manager.save(files);

  }

}
```

for the first time data is inserted but I loose primary key on Files entity.

If I start server again and do above queries I'm getting error: Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: files.id 

because primary key is removed from Files entity.

**Comment by iz-iznogood** [comment] 2017-09-21 14:04
The issue is fixed, i will push it shortly for review

**Comment by pleerock** [comment] 2017-09-22 04:56
@iz-iznogood can you please check is this issue related to #783 ?

**Comment by iz-iznogood** [comment] 2017-09-22 10:20
Hi @pleerock  yes it is the same issue.

**Comment by pleerock** [comment] 2017-09-22 10:27
Will be released in `0.1.0-alpha.46`.

**Closed by pleerock** 2017-09-22 10:27 UTC

**Comment by ldiego08** [comment] 2018-06-19 17:31
Same issue here with 0.2.7. Just updated and I'm getting a `NOT NULL constraint violation` error for autogenerated ID columns. Also, for some reason, the `length` option has to be a string instead of a number.

**Comment by kmphasisinfotech** [comment] 2019-05-13 05:44
ghtkhjk
