### ISSUE TITLE
Missing Rows Affected in Oracle Db Delete

### ISSUE THREAD

**Issue by RobinsonLuiz** [typeorm/typeorm#3546] opened 2019-01-30 19:02 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1- invoke queryRunner.manager.delete
2- the returned DeleteResult does not include any info at all. Expecting to include the number of affected rows.

I'm having trouble with queryRunner.manager.delete: the operation successfully removes the entity from the database, but DeleteResult does not contain count of entities deleted, it's just DeleteResult { raw: undefined }. This occurs with v0.2.9.

Why doesn't DeleteResult specify a property for the number of rows affected in cases of db is oracle?

**Comment by Kononnable** [comment] 2019-02-09 14:31
#3060 - similar issue but about UpdateResult

**Comment by imnotjames** [comment] 2020-10-17 08:33
Duplicate of #2415

**Closed** 2020-10-17 08:34 UTC
Labels: driver: oracle, enhancement, question
