### ISSUE TITLE
listeners/subscribers not working asynchronously

### ISSUE THREAD

**Issue by felipejncc** [typeorm/typeorm#5991] opened 2020-05-02 07:27 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[x ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

According to [this issue](https://github.com/typeorm/typeorm/issues/1212), it is possible to use listeners like ```@BeforeInsert()``` decorator and subscribers asynchronously.

However, this is not working for me.

The code below shows some tests:

```ts
@EventSubscriber()
export class FileModelSubscriber implements EntitySubscriberInterface<FileModel> {

    fileStorage: FileStorageService

    listenTo() {
        return FileModel;
    }

    beforeUpdate(evt: UpdateEvent<FileModel>) {
        evt.entity.updateDate = new Date();
    }

    async beforeInsert(evt: InsertEvent<FileModel>): Promise<void> {
        let resolve;
        const promise = new Promise<void>(r => resolve = r);
        console.log('test', 1)
        setTimeout(() => {
            console.log('test', 3)
            resolve();
        }, 20000);
        console.log('test', 2)
        await promise
        console.log('test', 4)
    }

    async afterInsert(evt: InsertEvent<FileModel>) {
        console.log('test', 5)
    }
}
```
What I expect is, once I execute ```getConection().getRepository(FileModel).save(myFileModel)```, the method ```beforeInsert()``` waits 20 seconds and then the data be inserted. The expected output from the console should be:
test 1
test 2
test 3 (20 seconds later)
test 4
test 5

Of curse, after printing test 4, the entity must be saved. 

But what I obtain is that the entity is inserted whitout waiting the resolution of the promise and the console prints:

test 1
test 2 ---> after printing this, the entity is inserted
test 5 ---> afterInsert()
test 3 (printed 20 seconds later)
test 4

Is there any way to work with subscribers/listeners asynchronously?

By the way, I'm using Ionic 5 with angular 8.

**Comment by bhaimanu** [comment] 2020-08-25 16:47
Is someone working on this?? I have a similar requirement.

**Comment by ViniciusLavrador** [comment] 2021-01-13 06:56
Has there been any new developments or workarounds regarding this ?

**Comment by felipejncc** [comment] 2021-01-14 02:09
I have a workaround for this problem using [rxjs](https://rxjs-dev.firebaseapp.com/guide/overview) because `beforeInsert()` and `afterInsert()` are not asynchronous:

```ts
export class MyEvent {
    static readonly myEvent: Subject<any> = new Subject();
}

@EventSubscriber()
export class MySubscriber implements EntitySubscriberInterface<MyEntity> {
    ......
    afterInsert(event: InsertEvent<MyEntity>) {
        ........
        MyEvent.myEvent.next(theValueToSend)
    }

    afterUpdate(event: UpdateEvent<MyEntity>) {
        ........
        MyEvent.myEvent.next(theValueToSend)
    }
}
```

`MyEvent.myEvent.subscribe(...)` will receive the value after insertion or update and can be placed where is needed.

Hope this is useful for anybody...

**Comment by nebkat** [comment] 2021-01-14 03:39
We could probably await all subscribers to allow async. Someone should open a PR, should be a very easy change to make.

**Comment by chinanderm** [comment] 2021-02-16 19:20
It would be really great if this could be worked on as it would greatly simplify a lot of my code.

**Comment by Yeboster** [comment] 2021-02-20 13:34
Hello,
I have a similar issue: Given a main entity `User` I am changing asynchronously a related entity `Post` on `beforeInsert/Update` of `User` but they're not saved on cascade when calling `save` (I've tried a lot of `cascade/onDelete/onUpdate` combinations). So unfortunately I need to change the related entity `Post` where I use the `User` entity instance, which is bad because you could forget to do it (even if you wrap it in a method call).

Looking at the code it seems that the subscribers (at least the `beforeInsert`) are managing the async case:
https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/subscriber/Broadcaster.ts#L33-L44
And here the promises are awaited:
https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/query-builder/InsertQueryBuilder.ts#L74-L81

So I am a bit confused why it's not working as expected.
Any ideas ?

**Comment by imnotjames** [comment] 2021-07-05 06:23
I am unable to replicate any issues folks are having here.  I've used the following test case:

```
@Entity()
export class Example {
    @PrimaryGeneratedColumn()
    id: number;
}

import {EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent} from "../../../../src/index";
import {Example} from "../entity/Example";

@EventSubscriber()
export class ExampleSubscriber implements EntitySubscriberInterface<Example> {
    public static readonly events: string[] = []

    listenTo() {
        return Example;
    }

    async beforeInsert(event: InsertEvent<Example>) {
        ExampleSubscriber.events.push("start before");

        await new Promise<void>((resolve) => {
            setTimeout(() => {
                ExampleSubscriber.events.push("timeout before");
                resolve();
            }, 1000);
        })

        ExampleSubscriber.events.push("end before");
    }

    async afterInsert(event: UpdateEvent<Example>) {
        ExampleSubscriber.events.push("start after");
    }
}
describe("github issues > #5991 EntitySubscriber not awaiting", () => {
    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [Example],
        subscribers: [ExampleSubscriber],
        enabledDrivers: ["sqlite"],
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("should fire the given event for an abstract entity", () => Promise.all(connections.map(async connection => {
        ExampleSubscriber.events.length = 0;

        const entity = new Example();

        await connection.manager.save(entity);

        expect(ExampleSubscriber.events).to.eql([
            "start before",
            "timeout before",
            "end before",
            "start after",
        ]);
    })));
});
```

See here: https://github.com/imnotjames/typeorm/tree/fix/5991/listeners-not-awaiting

As I cannot replicate it I can only assume it's been resolved.

**Comment by imnotjames** [comment] 2021-07-05 06:24
If it's not been resolved I need a reproducible example that exhibits this issue.  Perhaps a repository?  Or a test case.  Anything.  Until we can find that it's an actual issue I'll be closing this out.

Either re-open or open a new issue with a repex & we'll work to correct it.

**Closed by imnotjames** 2021-07-05 06:24 UTC
Labels: bug, driver: cordova, driver: sqlite, driver: sqljs
