### ISSUE TITLE
Foreign Key Constraint Failed on OneToOne() relation

### ISSUE THREAD

**Issue by mindjuice** [typeorm/typeorm#1548] opened 2018-02-04 04:15 UTC
**Issue type:**
[X] question

**Database system/driver:**
[X] `sqlite`

**TypeORM version:**
[X] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a pretty simple case where a `User` has an `Address`, and I want to be able to fetch a `User` with `leftJoinAndSelect('user.address', 'address')` so that the `address` is populated.

I've tried to setup a `OneToOne()` relation, and I'm able to insert `Addresses` and `Users` (where the `User` includes either a new address or a previously created address), and they show all up in the database.  Whenever I restart the server and try to reconnect to the database I get the following error:

```bash
03:29:37.987Z ERROR Server: Connection error: QueryFailedError: SQLITE_CONSTRAINT: 
FOREIGN KEY constraint failed
```

I checked the data in the database and the `addressId` field in all `User`s is present and populated correctly with the corresponding address ids, and the foreign key constraint for the table is set to `(addressId) REFERENCES address (id)`, which seems correct.

I assume I am just doing something stupid or misunderstanding how relations work.

Here are entity definitions:

```ts
@Entity()
export class User {
  @PrimaryGeneratedColumn() id: number
  @Column() name: string
  // I've tried removing the address => address.user, but get the same error
  @OneToOne(type => Address, address => address.user, { nullable: true, ...cascade })
  @JoinColumn()
  address?: Address
}

@Entity()
export class Address {
  @PrimaryGeneratedColumn() id: number
  @Column() street2: string
  @Column() city: string
  @Column() stateProv: string
  @Column() country: string
  @Column() zipPostal: string
  // I've tried with and without this whole property, and have removed the user => user.address
  // still get the same error.
  @OneToOne(type => User, user => user.address, { nullable: true, ...cascade })
  user: User
}
```

Anyone have any idea what might be wrong here?

**Comment by mindjuice** [comment] 2018-02-04 15:25
Looks like this may be the same as #1530.

I switched to MariaDB and it works properly if I just have one side of the relation like this:

```ts
@Entity()
export class User {
  @PrimaryGeneratedColumn() id: number
  @Column() name: string
  // I've tried removing the address => address.user, but get the same error
  @OneToOne(type => Address, { nullable: true, ...cascade })
  @JoinColumn()
  address?: Address
}

@Entity()
export class Address {
  @PrimaryGeneratedColumn() id: number
  @Column() street2: string
  @Column() city: string
  @Column() stateProv: string
  @Column() country: string
  @Column() zipPostal: string
}
```

I was planning to switch over anyway, so that will resolve the issue for me.

**Comment by pleerock** [comment] 2018-02-05 06:51
If its a duplicate of #1530 then Im going to close this.

**Closed by pleerock** 2018-02-05 06:51 UTC
