### ISSUE TITLE
order of entities breaks code

### ISSUE THREAD

**Issue by oeddyo** [typeorm/typeorm#3788] opened 2019-03-09 16:26 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I'm trying to get this very simple OneToMany example work:

video:
```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, CreateDateColumn, UpdateDateColumn, ManyToOne } from "typeorm";
import { User } from "./user"
@Entity()
export class Video extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column()
  title: string

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date

  @ManyToOne(type => User, user => user.videos)
  user: User
}
```

User.ts
```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, CreateDateColumn, UpdateDateColumn, OneToMany } from "typeorm";
import { Video } from "./video"

@Entity()
export class User extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column()
  firstName: string

  @Column()
  lastName: string

  @Column()
  email: string

  @Column({default: false})
  isEmailVerified: boolean

  @Column({default: false})
  isPhoneVerified: boolean

  @OneToMany(type => Video, video => video.user)
  videos: Video[]

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date
}
```

and in my super simple experss server: 
```
import * as express from 'express';
import { Request, Response } from 'express';
import { User } from "./entity/user"
import { Video } from "./entity/video"
const app = express();
const {
  PORT = 3000,
} = process.env;

import "reflect-metadata";

import {createConnection} from "typeorm";

const p: string = "./entity/*.ts"

createConnection({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "abc",
    password: "123456",
    database: "abc",
    entities: [User, Video],
    synchronize: true,
    logging: false
}).then(connection => {
    // here you can start to work with your entities
    console.log("connected to db")
}).catch(error => console.log(error));

app.get('/', async (req: Request, res: Response) => {

  console.log("trying typeorm")

  try {
    
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.email = "abc@gmail.com"
    await user.save()
  } catch (err) {
    console.log(err)

  }

  res.send({
    message: 'hello world',
  });
});

app.listen(PORT, () => {
  console.log('http server started at http://localhost:' + PORT);
  console.log("haha")
});

```
This throws an error:
```
/Users/exie/workspace/shandianyun-http/dist/http-server.js:293
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "User", function() { return User; });
                                                                                               ^

ReferenceError: User is not defined
    at Module.User (/Users/exie/workspace/shandianyun-http/dist/http-server.js:293:96)
    at Module../src/http-server/entity/video.ts (/Users/exie/workspace/shandianyun-http/dist/http-server.js:400:65)
    at __webpack_require__ (/Users/exie/workspace/shandianyun-http/dist/http-server.js:20:30)
    at Module../src/http-server/entity/user.ts (/Users/exie/workspace/shandianyun-http/dist/http-server.js:296:64)
    at __webpack_require__ (/Users/exie/workspace/shandianyun-http/dist/http-server.js:20:30)
    at Module.<anonymous> (/Users/exie/workspace/shandianyun-http/dist/http-server.js:421:70)
    at Module../src/http-server/index.ts (/Users/exie/workspace/shandianyun-http/dist/http-server.js:478:30)
    at __webpack_require__ (/Users/exie/workspace/shandianyun-http/dist/http-server.js:20:30)
    at __dirname../node_modules/process/browser.js.module.exports (/Users/exie/workspace/shandianyun-http/dist/http-server.js:84:18)
    at Object.<anonymous> (/Users/exie/workspace/shandianyun-http/dist/http-server.js:87:10)
[nodemon] app crashed - waiting for file changes before starting...
```

However as long as I switch the order of import in the express server, it works fine

```
import { Video } from "./entity/video"
import { User } from "./entity/user"
```

I'm wondering what's the reason? Is it circular importing in some way so it breaks my code?

Do I need to check the import order each time I add a new model?

**Comment by oeddyo** [comment] 2019-03-10 16:51
just setup a simple repo. Code in /src is actually copied from sample3 in /typeorm/samples

https://github.com/oeddyo/typeorm-issue

**Comment by ISNIT0** [comment] 2019-03-15 13:42
👍 Also getting this

**Comment by oeddyo** [comment] 2019-03-15 14:40
@ISNIT0 Hi there,

can you paste your tsconfig here? if you try to change "module" in your tsconfig.json to "commonjs", it might work for you

**Comment by ISNIT0** [comment] 2019-03-15 14:42
Hey @oeddyo,
Was already set to `commonjs`. I've re-jigged my imports to fix my immediate issue, so can't really do much more testing.

**Comment by ISNIT0** [comment] 2019-03-15 14:43
My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": false,
    "noImplicitAny": true,
    "sourceMap": false,
    "baseUrl": ".",
    "outDir": "build",
    "resolveJsonModule": true,
    "types": ["reflect-metadata", "node"],
    "typeRoots": [
      "node_modules/@types/",
      "./src/typings/"
    ],
    "lib": ["es7", "dom", "es2017.object"],
    "paths": {
      "src/*": ["./src/*"],
      "test/*": ["./test/*"]
    }
  },
  "include": ["src/**/*", "test/**/*", "e2e/**/*"],
  "exclude": ["node_modules", "dist"]
  // "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
}

```

**Comment by oeddyo** [comment] 2019-03-15 14:55
@ISNIT0 
try this:


```
{
  "compilerOptions": {
    "jsx": "react",
    "module": "commonjs",  // https://stackoverflow.com/questions/48378495/recommended-typescript-config-for-node-8
    "moduleResolution": "node", // choose node instead of classic 
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "dist",
    "target": "es2017",
    "emitDecoratorMetadata": true, // required by typeorm
    "experimentalDecorators": true // required by typeorm
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
      "node_modules"
  ]
}
```

**Comment by ISNIT0** [comment] 2019-03-15 15:37
@oeddyo That would break many things on my system. I've "fixed" the issue on my side, so there's no need to debug, but it seems there's definitely a 🐛 in TypeORM

**Comment by Mindar** [comment] 2019-03-16 16:49
I'm having the same issue. The proposed tsconfig isn't fixing it for me.

**Comment by Kononnable** [comment] 2019-03-17 21:39
Guys, I think we need a reproduction repo to know whats wrong in yours configuration.
Repo provided by @oeddyo is fixed with `"module": "commonjs"` and we don't have anything to reproduce yours issues if that change doesn't help you.

**Comment by ISNIT0** [comment] 2019-03-18 07:28
Okay, if I have time, I'll try to create a repro, but this bug is no longer on my critical path 😄

**Comment by Mindar** [comment] 2019-03-19 00:40
I've created a reproduction repo at https://github.com/Mindar/typeorm-issue 
I'm not sure if this is the most minimal example possible, but it is a simplified version of my use case. Depending on the order of the entity imports the code either works or tells me that it can't find a column on the entity.

**Comment by Kononnable** [comment] 2019-03-23 22:45
@Mindar 
Your code works if you declare primary columns explicitly. This is required in @next version(so your code will be compatible with upcoming changes), in 0.2 it's not required but there might be some errors if you don't do it.

Working code looks like that(notice explicit declaration of primary column and according changes in JoinTable decorator):
```typescript
@Entity()
export class User extends BaseEntity {

	@PrimaryColumn()
	userPartyId!:Number;

	@JoinColumn()
	@OneToOne(type => Party)
	userParty!: Party;

	@Column()
	username!: string;

	@ManyToMany(type => Group)
	groups!: Group[];
}
```
```typescript
@Entity()
export class Group extends BaseEntity {

	@PrimaryColumn()
	groupPartyId!:number;

	@JoinColumn()
	@OneToOne(type => Party)
	groupParty!: Party;
	
	@Column()
	username!: string;

	@ManyToMany(type => User)
	@JoinTable({
		name: "user_group_relation",
		joinColumn: {
			name: "group",
			referencedColumnName: "groupPartyId"
		},
		inverseJoinColumn: {
			name: "user",
			referencedColumnName: "userPartyId"
		}
	})
	members!: User[];
}
```

**Comment by Mindar** [comment] 2019-03-24 15:10
Thank you, that fixed my problem.

**Comment by Kononnable** [comment] 2019-04-01 21:19
Closing since there are no more reproduction repos.
If anyone comes again on this issue just paste reproduction code here and mention me(ofc. if above solutions won't help).

**Closed by Kononnable** 2019-04-01 21:19 UTC
Labels: needs more info

**Comment by triptec** [comment] 2019-04-05 06:16
I've had the same problem but only in webpack mode: production, we "solved" it by setting:
```
// webpack.config.js
module.exports = {
...
  optimization: {
    concatenateModules: false, // This because of circular dependencies ie. ManyToOne, OneToMany
    minimize: false, // This because Entity names are mangled
  },
}
```

**Comment by Knaackee** [comment] 2019-04-26 16:43
Here is a minimal setup:

Putting the following inside a single file throws 
```
Error during migration generation:
ReferenceError: Person is not defined
```
on `migration:generate` 

```
import {
  Column,
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class Car {
  @PrimaryGeneratedColumn()
  id?: number;

  @ManyToOne(() => Person, Person => Person.cars)
  owner?: Person;
}

@Entity()
export class Person {
  @PrimaryGeneratedColumn()
  id?: number;

  @Column({ type: "varchar" })
  name?: string;

  @OneToMany(() => Car, Car => Car.owner)
  cars?: Array<Car>;
}

```

**Comment by mustafahafidi** [comment] 2019-05-18 15:12
@triptec unfortunately  `concatenateModules: false` seems to be not enough to fix circular dependencies in my entities. I'm wondering whether you did something else to solve it

**Comment by Mikkal24** [comment] 2019-08-15 21:26
I was also running into this issue so I started making the changes to my tsconfig.json file and webpack config file. What did the trick for me was setting `"target":"es2017"` instead of `es2015` which is what angular universal defaults to. (Thanks @oeddyo )

I'm still not sure if this will bite me in the ass later but, might help other people wandering around in the digital ocean.
