### ISSUE TITLE
Query using alias instead of actual "name" property configured in model after version 0.2.25

### ISSUE THREAD

**Issue by Hugo01** [typeorm/typeorm#6859] opened 2020-10-06 14:30 UTC
**Issue type:**

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Typeorm builds query using the column alias name instead of the actual "name" of the column configured in the model file.
Here's an example
I have a model configured like this: 

```
return new EntitySchema({
name: 'ModelName',
    tableName: 'tablename',
    columns: {
      objectid: {
        primary: true,
        name: 'OBJECTID',
        type: 'int'
      },
      columnName: {
        type: 'varchar',
        name: 'COLUMN_NAME',
        length: 20
      },
)
```

This started happen after version **0.2.25**
Typeorm will execute a query using "**objectid**" instead of "**OBJECTID**" and **columnName** instead of **COLUMN_NAME**

**Comment by imnotjames** [comment] 2020-10-07 02:34
Can you create a minimally reproducible example?

Our tests seem to be passing so I can't replicate this problem.  I even tried making sure that the `name` field was set and confirmed that the column name matched the name defined in the decorator.

I'll be closing this issue for now as we can't replicate but if you can find a way to replicate we can reopen it!

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Closed by imnotjames** 2020-10-07 02:34 UTC
