### ISSUE TITLE
QueryBuilder's query generation speed is slow

### ISSUE THREAD

**Issue by RyuDoizaki** [typeorm/typeorm#7666] opened 2021-05-18 12:35 UTC
## Issue Description
QueryBuilder's query generation speed is slow.
It tends to be slower as the number of columns increases and the number of select increases.

### Expected Behavior
I hope that even if the number of select increases, the speed will not decrease significantly.

### Actual Behavior

```
EntityColumn100 selectCount 1: 0.218ms
EntityColumn100 selectCount 50: 6.624ms
EntityColumn100 selectCount 100: 10.513ms
EntityColumn200 selectCount 1: 0.655ms
EntityColumn200 selectCount 50: 9.475ms
EntityColumn200 selectCount 100: 19.618ms
```

### Steps to Reproduce

Query generation time output
```typescript
function manySelect<T>(connection: Connection, cls: new () => T, selectCount: number, outLog = true) {

    const qb = connection.getRepository(cls).createQueryBuilder();
    for (let i = 1; i <= selectCount; i++) {
        if (i === 1) {
            qb.select('column1', 'column1');
        } else {
            qb.addSelect('column' + i, 'column' + i);
        }
    }
    if (outLog) {
        console.time(cls.name + ' selectCount ' + selectCount);
    }
    qb.getQuery();
    if(outLog) {
        console.timeEnd(cls.name + ' selectCount ' + selectCount);
    }
}

createConnection().then(async connection => {
    // The first time seems to be slower, so no log output.
    manySelect(connection, EntityColumn100, 1, false);

    manySelect(connection, EntityColumn100, 1);
    manySelect(connection, EntityColumn100, 50);
    manySelect(connection, EntityColumn100, 100);

    manySelect(connection, EntityColumn200, 1);
    manySelect(connection, EntityColumn200, 50);
    manySelect(connection, EntityColumn200, 100);

}).catch(error => console.log(error));
```

Entity
```typescript
@Entity('entity_column100')
export class EntityColumn100 {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: 'int',
        default: 0,
    })
    column1!: number;

// column2 ~ column99

    @Column({
        type: 'int',
        default: 0,
    })
    column100!: number;
}

@Entity('entity_column200')
export class EntityColumn200 {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: 'int',
        default: 0,
    })
    column1!: number;

// column2 ~ column199

    @Column({
        type: 'int',
        default: 0,
    })
    column200!: number;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS Catalina 10.15.7 |
| Node.js version     | v14.16.0 | 
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-06-21 06:41
Seems linear in growth.  Am I missing something aside from it being slow?

**Comment by imnotjames** [comment] 2021-07-03 05:13
Duplicate of #3857

**Closed by imnotjames** 2021-07-03 05:13 UTC
Labels: bug, driver: mysql, requires triage
