### ISSUE TITLE
getOne fetches all rows instead of one

### ISSUE THREAD

**Issue by maruf0011** [typeorm/typeorm#5783] opened 2020-03-30 08:49 UTC
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

getOne function actually pulls all the matching record from table and return one single object. 

if its getting only the single object why its need to pull all the record from db. querying getOne in a large table will pull large amount of data, can resulted into memory exception.

**Comment by imnotjames** [comment] 2021-07-04 00:53
Duplicate of #4852

**Closed by imnotjames** 2021-07-04 00:53 UTC
Labels: new feature, question
