### ISSUE TITLE
Typeorm Postgres missing RequestTimeout option.

### ISSUE THREAD

**Issue by kamzcgcg** [typeorm/typeorm#6650] opened 2020-09-01 00:17 UTC
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**I'm looking to be able to control the following attribute in Typeorm for Postgres:**

**RequestTimeout**

Today the default behavior is for `getManager().query(...)` and `getRepositoty().createQueryBuilder(...).getMany()` to wait for a response indefinitely. Is there a way to introduce a request timeout that I might've missed? If not, can this super useful feature be added?

If this is not possible, does Typeorm expose the connection from its pool so that I can implement a timeout mechanism and close the connection manually?

**Comment by HexMox** [comment] 2021-03-30 11:51
Great jobs:

Not only postgres driver,  mysql too.

https://github.com/mysqljs/mysql#timeouts

mysql2 supports timeout option but `MysqlQueryRunner.ts` 's query method is not support it:

https://github.com/typeorm/typeorm/blob/e1e94236e71c14a4682356ada7774d657eba8936/src/driver/mysql/MysqlQueryRunner.ts#L182

**Comment by imnotjames** [comment] 2021-07-04 04:34
Duplicate of #5429

**Closed by imnotjames** 2021-07-04 04:34 UTC
Labels: driver: postgres, new feature, question
