### ISSUE TITLE
When Ionic build with AOT, the relation between entities will not be recognized.

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2595] opened 2018-07-27 21:10 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When Ionic build with option like --prod or --aot, it'll pass AOT process. But when App is started, it emits not defined reference error at 31 lines like below.

[Versions]
Angular: 5.2.11
ionic-angular: 3.9.2
ionic/app-script: 3.1.9

[Entity: categories.ts]
`
@Entity("Categories")
@Index("fk_Categories_Categories1_idx",["Categories_id",])
export class Categories {

    @PrimaryGeneratedColumn({
        name:"id"
        })
    id:number;
        

    @Column("varchar",{ 
        nullable:false,
        length:45,
        name:"name"
        })
    name:string;
        

    @Column("boolean",{ 
        nullable:true,
        name:"isInactive"
        })
    isInactive:boolean;
        

   
31:   @ManyToOne(type=>Categories, Categories_id=>Categories_id.subCategories)
    @JoinColumn({ name:'Categories_id'})
    Categories_id:Categories;
     

   
    @OneToMany(type=>Categories, categories=>categories.Categories_id)
    subCategories:Categories[];
    

   
    @OneToMany(type=>Products, products=>products.Categories_id)
    products:Products[];
    
}
`

[Error]
ore.js:1449 ERROR Error: Uncaught (in promise): ReferenceError: Categories_1 is not defined
ReferenceError: Categories_1 is not defined
    at Object.ɵ0 [as type] (categories.ts:31)
    at new RelationMetadata (RelationMetadata.js:138)
    at EntityMetadataBuilder.js:338
    at Array.map (<anonymous>)
    at EntityMetadataBuilder.computeEntityMetadataStep1 (EntityMetadataBuilder.js:334)
    at EntityMetadataBuilder.js:68
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (EntityMetadataBuilder.js:68)
    at ConnectionMetadataBuilder.buildEntityMetadatas (ConnectionMetadataBuilder.js:56)
    at Connection.buildMetadatas (Connection.js:509)
    at Object.ɵ0 [as type] (categories.ts:31)
    at new RelationMetadata (RelationMetadata.js:138)
    at EntityMetadataBuilder.js:338
    at Array.map (<anonymous>)
    at EntityMetadataBuilder.computeEntityMetadataStep1 (EntityMetadataBuilder.js:334)
    at EntityMetadataBuilder.js:68
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (EntityMetadataBuilder.js:68)
    at ConnectionMetadataBuilder.buildEntityMetadatas (ConnectionMetadataBuilder.js:56)
    at Connection.buildMetadatas (Connection.js:509)
    at c (polyfills.js:3)
    at polyfills.js:3
    at polyfills.js:3
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)

**Comment by JeongJun-Lee** [comment] 2018-07-28 08:47
When I try to build with --minifyjs --minifycss --optimizejs except for --aot, it also emits circular relations error like this.

ERROR Error: Uncaught (in promise): CircularRelationsError: Circular relations detected: e -> t -> e. To resolve this issue you need to set nullable: false somewhere in this dependency structure.
CircularRelationsError: Circular relations detected: e -> t -> e. To resolve this issue you need to set nullable: false somewhere in this dependency structure.
    at new t (vendor.js:1)
    at e.validateDependencies (vendor.js:1)
    at e.validateMany (vendor.js:1)
    at e.buildMetadatas (vendor.js:1)
    at e.<anonymous> (vendor.js:1)
    at vendor.js:1
    at Object.next (vendor.js:1)
    at s (vendor.js:1)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:1)
    at new t (vendor.js:1)
    at e.validateDependencies (vendor.js:1)
    at e.validateMany (vendor.js:1)
    at e.buildMetadatas (vendor.js:1)
    at e.<anonymous> (vendor.js:1)
    at vendor.js:1
    at Object.next (vendor.js:1)
    at s (vendor.js:1)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:1)
    at c (polyfills.js:3)
    at polyfills.js:3
    at polyfills.js:3
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:1)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:1)

**Comment by pleerock** [comment] 2018-07-28 08:52
Error says on its own, try to set your relations nullable.

**Comment by JeongJun-Lee** [comment] 2018-07-28 09:08
@pleerock Sorry I don't understand exactly where I have to set the nullable.

But, when I build without --minifyjs option, the App works well without emitting any errors.

**Comment by JeongJun-Lee** [comment] 2018-07-28 09:15
And I additionally found that the code is mangled by uglifyjs in the --minifyjs option. So this circulation error's root cause is from the mangling?

**Comment by pleerock** [comment] 2018-07-28 09:15
try to disable mangling

**Comment by JeongJun-Lee** [comment] 2018-07-28 09:21
But the mangling process is important for us to protect our source code from hacking. 
Anyway, this issue should be separated between the AOT and the mangling. This original issue was about ReferenceError from AOT build.

**Comment by pleerock** [comment] 2018-07-28 09:30
mangling isn't important part of uglifing, there is no relation between mangling and hacking. Try to disable mangling, maybe ReferenceError will disappear?

**Comment by JeongJun-Lee** [comment] 2018-07-28 10:16
No. disable mangling doesn't solve this AOT issue. because each the aot and the minifyjs process in Ionic is the separated process. So this issue should be separated as I tell before. I made new issue #2597 about mangling in Ionic.

**Comment by imnotjames** [comment] 2020-10-03 18:05
Duplicate of #2164

**Closed by imnotjames** 2020-10-03 18:05 UTC
