### ISSUE TITLE
Listeners aren't called on .save() for MongoDB

### ISSUE THREAD

**Issue by joemckie** [typeorm/typeorm#5668] opened 2020-03-11 14:37 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Save an entity to MongoDB by calling `save` with a plain object. Listeners won't be called.

**Comment by imnotjames** [comment] 2021-07-10 16:11
Duplicate of #4080

**Closed by imnotjames** 2021-07-10 16:11 UTC
Labels: bug, comp: subscribers and listeners, driver: mongodb
