### ISSUE TITLE
Using with Vite: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by raymondboswel** [typeorm/typeorm#8738] opened 2022-03-11 08:16 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `typeorm@0.2.45` for the project I'm working on.

I'm using TypeORM in a Vite based project, and when building the project in production mode, I get the following error

Uncaught ReferenceError: require is not defined

which is thrown from BrowserPlatformTools:150

I understand that this is not necessarily a common use case, and I'm not sure if this change would break other clients, so if that's the case feel free to close my issue, and I'll just carry on using the patch-package workaround.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/typeorm/browser/platform/BrowserPlatformTools.js b/node_modules/typeorm/browser/platform/BrowserPlatformTools.js
index 7b23ac5..123b61d 100644
--- a/node_modules/typeorm/browser/platform/BrowserPlatformTools.js
+++ b/node_modules/typeorm/browser/platform/BrowserPlatformTools.js
@@ -5,6 +5,8 @@
  * For node.js environment this class is not getting packaged.
  * Don't use methods of this class in the code, use PlatformTools methods instead.
  */
+import Buffer from "buffer";
+
 var PlatformTools = /** @class */ (function () {
     function PlatformTools() {
     }
@@ -147,7 +149,7 @@ var Writable = /** @class */ (function () {
 }());
 export { Writable };
 if (typeof window !== "undefined") {
-    window.Buffer = require("buffer/").Buffer;
+    window.Buffer = Buffer;
 }
 // NativeScript uses global, not window
 if (typeof global !== "undefined") {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Creskendoll** [comment] 2022-06-04 11:02
I've been having this issue for weeks now. I'm using SvelteKit with Vite which shares the Typeorm classes with the backend. Took me a while to identify Typeorm as the culprit. Thank you for this solution @raymondboswel, I can finally stop banging my head on the wall.

**Comment by BracketJohn** [comment] 2022-06-25 14:38
We also have the same issue running nuxt3 + vite setup and importing `typeorm` on the server side!

It took very long to find this issue - after hours of searching I'm thankful that we're not the only ones and a fix exists, thanks @raymondboswel! (:

**Comment by ebess** [comment] 2022-07-02 07:38
I got same problem going further to the query builder. It is loading child classes dynamically to avoid circular deps, eg _QueryBuilder.ts_:
```ts
    insert(): InsertQueryBuilder<Entity> {
        this.expressionMap.queryType = "insert"

        // loading it dynamically because of circular issue
        const InsertQueryBuilderCls =
            require("./InsertQueryBuilder").InsertQueryBuilder
        if (InstanceChecker.isInsertQueryBuilder(this)) return this as any

        return new InsertQueryBuilderCls(this)
    }
```
So Vite strips require completely. You can not just solving this by import it like you did in in browser tools as there will be a circular dependency:
```
Uncaught ReferenceError: Cannot access 'QueryBuilder' before initialization
    at InsertQueryBuilder.js:15:41
(anonymous) @ InsertQueryBuilder.js:15
```
In dev mode it works fine, only production builds are affected. Maybe you have kind of soluation how to make it work.

**Comment by raymondboswel** [comment] 2022-07-06 05:50
I haven't tried this myself, but perhaps something like https://www.npmjs.com/package/vite-plugin-require could work?

**Comment by DawidWetzler** [comment] 2022-09-11 11:37
If you have to use Vite with Typeorm, you could create a new JavaScript file with the same content as QueryBuilder and rename it to e.g. DeleteQueryBuilderBase and replace the QueryBuilder with your new file in according QueryBuilder.

```diff --git a/node_modules/typeorm/browser/query-builder/DeleteQueryBuilder.js b/node_modules/typeorm/browser/query-builder/DeleteQueryBuilder.js
--- a/node_modules/typeorm/browser/query-builder/DeleteQueryBuilder.js
+++ b/node_modules/typeorm/browser/query-builder/DeleteQueryBuilder.js
@@ -1,11 +1,11 @@
-import { QueryBuilder } from "./QueryBuilder";
 import { DeleteResult } from "./result/DeleteResult";
 import { ReturningStatementNotSupportedError } from "../error/ReturningStatementNotSupportedError";
 import { InstanceChecker } from "../util/InstanceChecker";
+import { DeleteQueryBuilderBase } from "./DeleteQueryBuilderBase";
 /**
  * Allows to build complex sql queries in a fashion way and execute those queries.
  */
-export class DeleteQueryBuilder extends QueryBuilder {
+export class DeleteQueryBuilder extends DeleteQueryBuilderBase {
     // -------------------------------------------------------------------------
     // Constructor
     // -------------------------------------------------------------------------
```
Afterwards in your vite.config.js enable following options
```typescript
  esbuild: {
    keepNames: true, // typeorm migrations require timestamp in their names and this way it can be defined with name property
  },
  build: {
    commonjsOptions: {
      transformMixedEsModules: true, // https://github.com/rollup/plugins/tree/master/packages/commonjs#transformmixedesmodules
    },
  },
```

I haven't field-tested this but it looks like it's working for now.

Note: I couldn't post the whole patch in github as it extends the 65k character limit. See: https://pastebin.com/R6xhaFxU
Disclaimer: I know this solution is not good, but you can still use Typeorm with Vite this way.

**Comment by BracketJohn** [comment] 2022-11-22 14:36
fyi @djschilling: we've resolved this issue for sidebase which is a nuxt 3 starter, check it out here: https://github.com/sidebase/sidebase

**Comment by djschilling** [comment] 2022-11-22 14:55
@BracketJohn how did you fix that in sidebase?

**Comment by BracketJohn** [comment] 2022-11-22 17:00
Here is our db-setup: https://github.com/sidebase/sidebase/tree/main/server/database

This is where we configure our data source: https://github.com/sidebase/sidebase/blob/main/server/database/index.ts

We have a plugin that that initializes the data source on startup: https://github.com/sidebase/sidebase/blob/main/server/plugins/initTypeOrmOnServerStartup.ts

Here is an example endpoint that then works with the database via typeorm: https://github.com/sidebase/sidebase/blob/main/server/api/example/%5Bid%5D.patch.ts

I think the key was ??maybe?? to use a specific typeORM version? I cannot clearly remember, but you could try to start with / copy over stuff from sidebase and work with that!

**Comment by SechinAndrey** [comment] 2022-12-02 20:27
Wow, great job @raymondboswel! It took me a while to find this Issue, and figure out what the problem is. 

The patch that you published at the beginning is all the changes? Unfortunately, it did not help me and even the dev mode stopped working and not just the prod build.

**Comment by b4-io** [comment] 2023-02-28 01:47
For future readers that are using solidjs with vite and TypeORM,

Here is the patch (which probably is a variation of that of @DawidWetzler) : https://pastebin.com/hqW2N0vM

Added to this you need to modify your index.html and define the Buffer, should also add dependecy to your project
```html
  <head>
   ....
    <script type="module">
        import { Buffer } from "buffer";
        window.Buffer = Buffer;
    </script> 
    
  </head>
```

**Comment by pleerock** [comment] 2023-02-28 04:32
The issue actually must be resolved in the latest version (`0.3.12`), can you please check it?

**Comment by b4-io** [comment] 2023-02-28 12:48
just tried it and it wasn't fixed, i was indeed using `0.3.11` but just the upgrade of version does not fix the problem

**Comment by b4-io** [comment] 2023-03-16 17:55
Yeah, you need

> Is there a public fork of `typeorm` that fixes this issue, or is everyone just running this git patch on a private fork?
> 
> @b4-io It looks like you replaced the `require` call with a static import at the top of the file. That didn't cause the circular issue mentioned in the comments?

Yeah, you need to create a Base for each one of the query builders. So there are no circular dependencies.

**Comment by jacobg** [comment] 2023-03-16 18:16
I'm not seeing how a git patch is maintainable or readable.

It seems that typeorm should split QueryBuilder into two classes: (1) an AbstractQueryBuilder that the specific query builders derive from; and then (2) a QueryBuilderFactory for the specific query builders. 

Or maybe a less impacting change might be to just define some type of singleton registry for which all of the specify query builders are registered with some sort of string ID, and then the base QueryBuilder looks up the classes that way?

**Comment by jacobg** [comment] 2023-03-16 20:52
Here's a potential pull request that makes typeorm work with application built using vite:
https://github.com/typeorm/typeorm/compare/master...jacobg:vite?expand=1

@pleerock Will you accept such a pull request? Any feedback? Thanks!

**Comment by Liam-Scott-Russell** [comment] 2023-05-16 07:04
@jacobg did you ever end up getting this PR'd into `main`?

**Comment by jacobg** [comment] 2023-05-16 09:17
@Liam-Scott-Russell The fork is here: https://github.com/jacobg/typeorm/tree/vite I didn't create a PR, because I was waiting to hear back from @pleerock whether he would accept it.

**Comment by ibilux** [comment] 2023-05-26 10:23
why this PR didn't merge yet ?

**Comment by Dukezo** [comment] 2023-07-10 09:03
Any news on this?

**Comment by Dukezo** [comment] 2023-07-10 22:07
I created a new pull request #10196 with @jacobg's solution Right now I use [patch-package](https://github.com/ds300/patch-package) to apply the fix, which works fine. Hopefully the fix will get merged at some point.

**Comment by laukaichung** [comment] 2023-08-05 03:50
I just created a react-vite-typeorm-sql.js boilerplate https://github.com/laukaichung/react-vite-typeorm-sqljs. It's worked without any issues so far.

**Closed** 2023-12-29 16:35 UTC
Labels: comp: browser
