### ISSUE TITLE
Mongodb with replicaSet and authSource connect but fail to perform query using a connectionString

### ISSUE THREAD

**Issue by npjonath** [typeorm/typeorm#6209] opened 2020-06-05 18:00 UTC
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi,

I'm running on production with a mongo cluster (4.2) on kubernetes.
I try to setup a project with typeorm and run it in production. (note : It's running fine in local env without a replicaSet)

In production, by using a connectionString as url parameters, I got the following problems : 
 ```
// This typeorm config don't work
{
               type: 'mongodb',
                entities: [__dirname + '/**/*.entity{.ts,.js}'],
                url: 'mongodb://api-scheduler:********@custom-mongodb-replicaset.mongo:27017/api-scheduler?replicaSet=rs-sched',
                useNewUrlParser: true,
                useUnifiedTopology: true,
                synchronize: true,
}
```
`Error : MongoError: not authorized on api-scheduler?authSource=admin&replicaSet=rs-sched to execute command { find: "jobs", filter: { status: { $in: [ "NEW", "WAITING_UPLOAD", "READY_TO_INGEST" ] }, type: "UPDATE", retryCount: { $lt: 3 } }, limit: 1, returnKey: false, showRecordId: false, lsid: { id: UUID("d9b954dc-5d37-4403-8258-2c60bc3cac9a") }, $clusterTime: { clusterTime: Timestamp(1591372379, 38), signature: { hash: BinData(0, 7145026E7D24FD4BB0E0E1EFDA889D51DF4232F4), keyId: 6797378919558283275 } }, $db: "api-scheduler?authSource=admin&replicaSet=rs-sched" }`

The strange things is in the $db name at the end of the error message, right ?

 ```
// This typeorm config is ok
{
               type: 'mongodb',
                entities: [__dirname + '/**/*.entity{.ts,.js}'],
                useUnifiedTopology: true,
                synchronize: true,
                host: 'custom-mongodb-replicaset.mongo',
                port: 27017,
                username: 'api-scheduler',
                password: '******',
                replicaSet: 'rs-sched',
                database: 'api-scheduler',
                authSource: 'admin'
}
```

Is there anyway to make it work properly with connectionString ?

**Comment by ballinette** [comment] 2020-06-18 14:45
I can confirm we have the same issue.
It worked until version 0.2.24

**Comment by ballinette** [comment] 2020-06-18 15:48
should it be a regression introduced by https://github.com/typeorm/typeorm/pull/5640 ?

**Comment by ballinette** [comment] 2020-06-18 15:59
More investigations: I guess the issue is here: https://github.com/typeorm/typeorm/blob/master/src/driver/DriverUtils.ts#L65
Maybe this method should be refactored with some regexp treatments... :thinking:

**Comment by npjonath** [comment] 2020-06-19 08:55
@ballinette this regex don't match my example of connectionString (which is valid).

**Comment by ballinette** [comment] 2020-06-19 10:32
sure, the queryParams should then be parsed to get all the options.
My sample code is only on first one-shot step, and I'm not sure it suits all settings combinations of all database types...

**Comment by npjonath** [comment] 2020-06-29 11:21
Any update of that point ? it make Typeorm not ready for production.

**Comment by danmana** [comment] 2020-07-23 12:38
Related to #6389 

Closed by #6390 (not included in any release yet ...)

Note that this just **fixes the database name parsing**, but does not pick up the query params as options, so `DriverUtils.buildDriverOptions` will not contain the query params.

As far as I can tell, this is not a problem as typeorm does not seem to expect it. 
Typeorm only uses the result to get the database name (and credentials in a couple of places, which worked before). 
The underlying Mongo driver parses the URL again when connecting, so it will pick up correctly the query params.

Though `buildDriverOptions` does not feel complete as it is now, it does seem to work.
As @ruscon mentioned, it would probably be a good idea to use something like https://github.com/vitaly-t/connection-string

**Comment by ismailyenigul** [comment] 2020-07-24 20:22
> I can confirm we have the same issue.
> It worked until version 0.2.24

I had the same issue with the latest version and `0.2.24` also worked me.

**Comment by imnotjames** [comment] 2020-10-14 01:37
Is this still a problem - I think we fixed a lot of the connection string problems

**Closed** 2020-10-16 04:27 UTC
Labels: bug, driver: mongodb
