### ISSUE TITLE
BUG - updateById can not update json columns in mysql

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1105] opened 2017-10-27 08:47 UTC
updateById can not update json columns in mysql

```ts
data={
    contents:[
        {type:1,content:"test"}
    ]
}

repo.updateById(id,data)
```

generated sql shows no any column is updated
```sql
UPDATE `table` SET  WHERE `id`=?  # You have an error in your SQL syntax
```

**Comment by Diluka** [comment] 2017-10-27 09:46
@pleerock https://github.com/Diluka/typeorm-issue-1105
the error only reproduce in production version using `0.1.1`

**Comment by pleerock** [comment] 2017-10-27 10:36
its a known issue and fix will be released in 0.1.2. duplicate of #1042

**Closed by pleerock** 2017-10-27 10:36 UTC
