### ISSUE TITLE
autoSchemaSync sqlite broken

### ISSUE THREAD

**Issue by AntoineABI** [typeorm/typeorm#783] opened 2017-08-20 14:32 UTC
Hello,

seems that when reconnecting to an existing database with autoSchemaSync activated it brokes already created PrimaryGeneratedColumn('increment') by removing UNIQUE CONSTRAINT (Autoincrement one).

So when saving item:
```
query failed: INSERT INTO "content"("type", "text", "userName", "submitDate") VALUES ($1,$2,$3,$4) -- PARAMETERS: ["image","-----","-------","2017-08-20T14:21:47.697Z"]
error: { Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: content.id errno: 19, code: 'SQLITE_CONSTRAINT' }
```

My entity
``` typescript
@Entity()
export class Content {
    @PrimaryGeneratedColumn('increment')
    id: number;
/// ...
```

My database connection parameters:
``` typescript
this.db = await createConnection({
                autoMigrationsRun: false,
                autoSchemaSync: true,
                database: Path.join(Config.WALL_DATABSE_DIR, Config.WALL_DATABSE_PREFIX + this.WallID + '.db'),
                entities: [Content],
                logger: 'advanced-console',
                logging: true,
                name: 'wallConnection',
                type: 'sqlite',
            } as SqliteConnectionOptions);
```

Thanks for the help.
If not any fix I may change for manual generated UIDD with @BeforeInsert decorator I think....

**Comment by AntoineABI** [comment] 2017-08-20 15:29
nevermind seems to work with alpha 35

**Comment by AntoineABI** [comment] 2017-08-20 20:21
Well it's not I just forgot I commented the query for testing purpose...
Something it is creating table with AUTOINCREMENT
``` sql
CREATE TABLE "temporary_content" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, ...
```
And sometimes it does not....
``` sql
CREATE TABLE "temporary_content" ("id" integer NOT NULL, ...
```

**Comment by seanmiddleditch** [comment] 2017-08-23 06:15
I'm seeing the same behavior, and then some.

When synchronizing schemas on SQLite, it appears to alternate between adding primary keys and not. I can open the sqlite DB and inpect it; on initial creation, it has the primary key attributes. Restart the app with `autoSchemaSync` enabled on the attributes go away. Restart again and they show up.

On top of that, once the tables are populated, there are issues with foreign key constraints. Using a `ManyToMany` relationship and populating items, the app fails to start with `autoSchemaSync` and complains about foreign key constraints failing when it attempts to drop one of the tables (in the process of making a new one, copying the rows, dropping the old one, and renaming the new one). I'm not sure how the other DB drivers handle this, but in SQLite at least the foreign key constraint enforcement can just be globally disabled during the schema sync operation.

It's worth noting that it's not technically just `autoSchemaSync`. The exact same issues happen when explicitly calling the `connection.synchronize()` method or when using the CLI's `schema:sync` command. It's the synchronization logic itself, at least for the SQLite driver.

**Comment by AntoineABI** [comment] 2017-08-23 20:30
I've no time to look into it because I started work again and hopefully it's a small database so I juste copy an empty database file to init another one (need to use same database multiple time and retrieve it like file so sqlite was perfect too bad I need to get around this issue)...

**Comment by pleerock** [comment] 2017-09-08 04:55
@AntoineABI how can I reproduce your issue if you say

> seems that when reconnecting to an existing database with

how do I know how your existing database looks like?

**Comment by pleerock** [comment] 2017-09-08 04:55
@seanmiddleditch can you please create a demo git repository with reproduction of these problems? And clear steps how to reproduce them

**Comment by AntoineABI** [comment] 2017-09-08 17:04
I guess it's any database (sqlite 3.x one) you can just test it with a simple schema with increment id, run twice with save/persist new entity and BOOM ! Voilà.
I will try to github this week-end but I feel kinda lazy right now.

**Comment by pleerock** [comment] 2017-09-08 17:56
there are tons of tests that do same and they have no problems. I need clear steps how can I reproduce this problem

**Comment by seanmiddleditch** [comment] 2017-09-20 23:52
@pleerock - i don't have a full standalone repro handy(*) but digging in the old code I can provide some snippets.

- typeorm: 0.1.0-alpha.35
- sqlite3: 3.1.9

Instructions: start the app twice and observe the test.db file both times. The first time, the test.db appears correctly. The second time, it's missing primary key attributes. Then populate the test.db with some data including a note, a label, and a relation between them (most easily done by hand in sqlite cli or gui for this test, imo). Restart app and observe exception thrown on startup.

Relevant snippet of model definitions:

```
// models.ts
@typeorm.Entity()
export class Label
{
    @typeorm.PrimaryGeneratedColumn()
    public id: number;

    @typeorm.Column({length: 32})
    @typeorm.Index({unique: true})
    public slug: string;

    @typeorm.ManyToMany(type => Note, note => note.labels, {
        cascadeInsert: false,
        cascadeUpdate: false
    })
    public notes: Note[];
}

@typeorm.Entity()
export class Note
{
    @typeorm.PrimaryGeneratedColumn({"type": "int"})
    public id: number;

    @typeorm.Column({length: 32})
    @typeorm.Index({unique: true})
    public slug: string;

    @typeorm.Column()
    public title: string;
    
    @typeorm.Column()
    public body: string;

    @typeorm.ManyToMany(type => Label, label => label.notes, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @typeorm.JoinTable()
    public labels: Label[];
}
```

Creation of typeorm connection in server:

```
// server.ts
    const connection = await typeorm.createConnection({
        "type": "sqlite",
        "database": "test.db",
        "entities": [
            models.Note,
            models.Label
        ],
        "autoSchemaSync": false
    });
```

(*) and probably won't ever at this point as I've abandoned typeorm in favor of another library, unfortunately

**Comment by iz-iznogood** [comment] 2017-09-22 10:19
This is the same issue as #919 and it is fixed

**Comment by pleerock** [comment] 2017-09-22 10:26
@iz-iznogood thank you! New changes will be released in next release today or tomorrow

**Closed** 2017-09-22 10:28 UTC
Labels: needs more info
