### ISSUE TITLE
add new condition in the query before query execution

### ISSUE THREAD

**Issue by elgreatly** [typeorm/typeorm#5698] opened 2020-03-16 15:34 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
i need to add where condition before execute the query like mongoose

```
schema.pre('find', function(next)  {
            this.where({testField: {$in: ['test']}});
        next();
    });
```

then this will add new condition to any find query then execute it 

i searched to find something like the in `TypeORM` but i didn't found way to do this

is there any solution to do it

**Comment by elgreatly** [comment] 2020-04-01 21:51
@pleerock do you have any solution for this issue?

**Comment by imnotjames** [comment] 2020-10-10 19:42
Duplicate of #1601

**Closed by imnotjames** 2020-10-10 19:42 UTC
Labels: driver: mariadb, driver: mongodb, driver: mssql, driver: mysql, question
