### ISSUE TITLE
ReferenceError raised in ormconfig.js gets converted to an empty object

### ISSUE THREAD

**Issue by golergka** [typeorm/typeorm#4809] opened 2019-09-25 11:21 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.19` (or put your version here)

**Steps to reproduce:**

1. Use the following `ormconfig.js`:

```js
"use strict";

throw new ReferenceError("test error");
```

2. Use the following `server.ts`:

```ts
createConnection()
.then(async connection => {

    console.log("DB connection created");
    // ...
})
.catch(error => console.log("DB connection error: " + JSON.stringify(error)))
```

**Expected result:**

DB connection error: ReferenceError: test error (with stacktrace)

**Actual result:**

DB connection error: {}

**Comment by imnotjames** [comment] 2021-07-03 19:33
All errors in the ormconfig are silently ignored.

Because the newer issue has more detailed info I'm closing this one as

Duplicate of #6960

**Closed by imnotjames** 2021-07-03 19:33 UTC
Labels: bug, driver: postgres
