### ISSUE TITLE
Code in another Node package doesn't detect open connection

### ISSUE THREAD

**Issue by greg-it** [typeorm/typeorm#3245] opened 2018-12-13 13:35 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9`

**Steps to reproduce or a small repository showing the problem:**

My application opens a TypeORM connection. When it directly issues queries to the database, it works properly. However when it calls a library method, which is in a separate Node package, and this library method sends a query to the database, a `ConnectionNotFoundError: Connection "default" was not found.` error is thrown.

The connection is not passed to the library in arguments. It is simply opened by calling `createConnection` in the application code and `getConnection` in places which require the database access.

This application code (written as test) works fine (no exception is thrown):

```ts
it('tests', async done => {
    await createConnection(connectionOpts);

     await getConnection()
         .createQueryBuilder()
         .select('COUNT(*)', 'count')
         .from(MyEntity, 'myEntity')
         .getRawOne();

    done();
});
```

However if the same query is moved to a separate Node package (a library):
```ts
export class MyService {
  async runQuery(): Promise<void> {
    const count = await getConnection()
      .createQueryBuilder()
      .select('COUNT(*)', 'count')
      .from(MyEntity, 'myEntity')
      .getRawOne();
  }
}
```

and it is called from application code like this:
```ts
it('tests', async done => {
    await createConnection(connectionOpts);

    await MyServices.getMyService().runQuery();

    done();
});
```

Then the following exception is thrown:
```
    ConnectionNotFoundError: Connection "default" was not found.

      at new ConnectionNotFoundError (webpack:/Users/grzegorz/Documents/projects/cloud/core-node/node_modules/typeorm/error/ConnectionNotFoundError.js?:19:28)
      at ConnectionManager.get (webpack:/Users/grzegorz/Documents/projects/cloud/core-node/node_modules/typeorm/connection/ConnectionManager.js?:38:19)
      at Object.getConnection (webpack:/Users/grzegorz/Documents/projects/cloud/core-node/node_modules/typeorm/index.js?:268:35)
      at MyService.eval (webpack:/lib/services/MyService.ts?:22:43)
      at eval (webpack:/lib/services/MyService.ts?:7:71)
      at __awaiter (webpack:/lib/services/MyService.ts?:3:12)
      at MyService.runQuery (webpack:/lib/services/MyService.ts?:20:16)
      at Object.<anonymous> (__tests__/tmp.test.ts:20:60)
```

The TypeScript library is transpiled to JavaScript and then included.

**Comment by havenchyk** [comment] 2018-12-13 16:34
@greg-it we need a small example to reproduce your problem. I would say that ormconfig.js file wasn't used for some reason in a failing test, but need more details.

**Comment by havenchyk** [comment] 2018-12-13 16:38
@greg-it we need a small repo to reproduce the problem. As I see, you use webpack and pass `connectionOptions` directly in tests, do you pass `connectionOptions` in your code as well?

**Comment by pleerock** [comment] 2018-12-13 18:37
also, are you sure your "separate package" doesn't have its own `typeorm` inside its own `node_modules` directory?

**Comment by greg-it** [comment] 2018-12-14 14:15
> As I see, you use webpack and pass `connectionOptions` directly in tests, do you pass `connectionOptions` in your code as well?

I've started this example with writing tests first, I didn't try to run the production code yet. I think that connection will be created by application when it starts or serves a request, not by the library. The library should only call `getConnection` I believe.

> also, are you sure your "separate package" doesn't have its own `typeorm` inside its own `node_modules` directory?

Both packages include `typeorm` package. Application needs it to create a connection, and library needs to consume it, so both depend on `typeorm`. Is it wrong?

> @greg-it we need a small repo to reproduce the problem.

I'll try to create a repo when I find a moment.

**Comment by thomascmurphy** [comment] 2018-12-17 21:10
I'm running into the same issue. The plan was to use a parent class that lives in another repo to create/manage connections (we have to support multi-tenancy and multiple schemas so it would be helpful to have this logic in one spot rather than have it replicated in each microservice). And as greg-it mentioned I have to include typeorm in both packages so that I can create the connection to pass along to the other, which will call getRepository() on that connection. Is there a better pattern for this or do I need to do something like pass the ConnectionManager around?

**Comment by thomascmurphy** [comment] 2018-12-17 21:40
Just tried passing along the ConnectionManager and that didn't work either 🙁

**Comment by thomascmurphy** [comment] 2018-12-17 22:42
Digging deeper into why this isn't working it comes down to this line: https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L790 . For the connection created in an external repo it is skipping past this block (even though when I console out the conditional it returns true) and doesn't get the manager/metadata set. Any ideas on why that's the case?

**Comment by pleerock** [comment] 2018-12-18 06:30
> Both packages include typeorm package. Application needs it to create a connection, and library needs to consume it, so both depend on typeorm. Is it wrong?

yes, of course. When you create a typeorm connection, it lives in memory (`your_package/node_modules/typeorm/index.ts -> const connections` for example). If another your package has its own typeorm then its going to read exist connections for there, e.g. `another_package/node_modules/typeorm/index.ts -> const connections`. Different files = different variables = different memory.

**Comment by greg-it** [comment] 2018-12-19 11:42
Makes sense.

In our case, there were **two separate `node_modules` directories** indeed, because in local development the application was linked to the library via a local path in `package.json` (I believe the effect would be the same if `npm link` was used):

```"@company/my-library": "../my-library",```

It created a symlink to `my-library` repo. Each of these packages had its own `node_modules` directory.

**Our solution** was to get the library directly from our company NPM registry (**not** via `npm link`!):

```"@company/my-library": "0.0.63",```

In that way, all dependencies of `my_library` were added into the application `node_modules`, so there was only one modules directory.

I think it could be solved in TypeORM itself if it stored the connection in global variables.

The issue can be closed from my side.

**Comment by pleerock** [comment] 2018-12-19 11:48
> I think it could be solved in TypeORM itself if it stored the connection in global variables.

In the future versions we are planning not to store connections in typeorm itself at all :)

I'll close this issue.

Answering people questions takes time and lot of efforts. Contribute to the [future of TypeORM](https://github.com/typeorm/typeorm/issues/3267) and donate to the project!

**Closed by pleerock** 2018-12-19 11:48 UTC
Labels: needs more info, question

**Comment by Choem** [comment] 2020-02-16 14:32
Any news regarding this issue? For my team it's still impossible to get this to work in a flexible way.

**Comment by PraveenMp** [comment] 2021-03-16 05:16
> I think I found an explanation and a solution (at least for now). Since each library is importing its own typeorm, I think (not a typescript expert) that it's failing this check because it's a different instance of Repository. What seems to be working for me is to re-export typeorm from my repo.

Can you provide what solution you found?

**Comment by tbf-siteimprove** [comment] 2021-05-20 14:16
> In the future versions we are planning not to store connections in typeorm itself at all :)

Is this part of https://github.com/typeorm/typeorm/issues/3251?

I would like to use typeorm in a lib, which my main app is using, which also uses typeorm (similar as @greg-it is mentioning it). Currently this results into 2 typeorm node_modules (same versions), which causes the issue that connections are not shared.

I would like to extract some db connection logic into a shared library, which is currently not possible, leading to a lot of code duplication :(

**Comment by tbf-siteimprove** [comment] 2021-05-21 06:51
> 
> 
> > Both packages include typeorm package. Application needs it to create a connection, and library needs to consume it, so both depend on typeorm. Is it wrong?
> 
> yes, of course. When you create a typeorm connection, it lives in memory (`your_package/node_modules/typeorm/index.ts -> const connections` for example). If another your package has its own typeorm then its going to read exist connections for there, e.g. `another_package/node_modules/typeorm/index.ts -> const connections`. Different files = different variables = different memory.

It seems that `npm dedupe` might help here. If both packages use the same typeorm version, `npm dedupe` will create one node_module for typeorm instead of duplicate node_modules for typeorm. But `npm dedupe` might have other side effects on the rest of the dependencies.
