### ISSUE TITLE
Migrations not working with SAP HANA

### ISSUE THREAD

**Issue by lucasheim** [typeorm/typeorm#8069] opened 2021-08-11 21:42 UTC
## Issue Description
I created a small repository running SAP HANA in a docker container, created a User entity with the following code:

```typescript
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @Column()
  age: number;
}
```

I then generated a migration with: `yarn typeorm migration:generate -n first_change`

The generated migration looks like this:

```typescript
import { MigrationInterface, QueryRunner } from "typeorm";

export class firstChange1628714311876 implements MigrationInterface {
  name = "firstChange1628714311876";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user" ("id" integer GENERATED ALWAYS AS IDENTITY, "firstName" nvarchar(255) NOT NULL, "lastName" nvarchar(255) NOT NULL, "age" integer NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user"`);
  }
}
```

When I try to run the migration with `yarn typeorm migration:run`

An error shows up:
<details>
<summary>Migration log</summary>

```
query: SELECT CURRENT_SCHEMA AS "schema_name" FROM "SYS"."DUMMY"
query: SELECT * FROM "SYS"."TABLES" WHERE "SCHEMA_NAME" = 'SYSTEM' AND "TABLE_NAME" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: CREATE TABLE "user" ("id" integer GENERATED ALWAYS AS IDENTITY, "firstName" nvarchar(255) NOT NULL, "lastName" nvarchar(255) NOT NULL, "age" integer NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))
query: INSERT INTO "migrations"("timestamp", "name") VALUES (?, ?) -- PARAMETERS: [1628714311876,"firstChange1628714311876"]
query: SELECT CURRENT_IDENTITY_VALUE() FROM "SYS"."DUMMY"
query failed: INSERT INTO "migrations"("timestamp", "name") VALUES (?, ?) -- PARAMETERS: [1628714311876,"firstChange1628714311876"]
error: QueryFailedError: Invalid parameter for function 'exec[ute](sql[, params][, options][, callback])'
    at QueryFailedError.TypeORMError [as constructor] (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at SapQueryRunner.<anonymous> (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/driver/sap/SapQueryRunner.js:252:50)
    at step (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:124:57)
    at /Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:113:16)
    at ArgParser.cbfunc (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/driver/sap/SapQueryRunner.js:249:108)
    at ConnectionExecCallback (/Users/i866817/dev/petro/typeorm_bug/node_modules/@sap/hana-client/lib/index.js:489:22) {
  query: 'SELECT CURRENT_IDENTITY_VALUE() FROM "SYS"."DUMMY"',
  parameters: [],
  driverError: Error: Invalid parameter for function 'exec[ute](sql[, params][, options][, callback])'
      at Socket.<anonymous> (/Users/i866817/dev/petro/typeorm_bug/node_modules/@sap/hana-client/lib/index.js:53:13)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Socket.Readable.push (internal/streams/readable.js:204:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: -20002,
    sqlState: 'HY000'
  },
  code: -20002,
  sqlState: 'HY000'
}
query: ROLLBACK
Error during migration run:
QueryFailedError: Invalid parameter for function 'exec[ute](sql[, params][, options][, callback])'
    at QueryFailedError.TypeORMError [as constructor] (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at SapQueryRunner.<anonymous> (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/driver/sap/SapQueryRunner.js:252:50)
    at step (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:124:57)
    at /Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/i866817/dev/petro/typeorm_bug/node_modules/tslib/tslib.js:113:16)
    at ArgParser.cbfunc (/Users/i866817/dev/petro/typeorm_bug/node_modules/typeorm/driver/sap/SapQueryRunner.js:249:108)
    at ConnectionExecCallback (/Users/i866817/dev/petro/typeorm_bug/node_modules/@sap/hana-client/lib/index.js:489:22) {
  query: 'SELECT CURRENT_IDENTITY_VALUE() FROM "SYS"."DUMMY"',
  parameters: [],
  driverError: Error: Invalid parameter for function 'exec[ute](sql[, params][, options][, callback])'
      at Socket.<anonymous> (/Users/i866817/dev/petro/typeorm_bug/node_modules/@sap/hana-client/lib/index.js:53:13)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Socket.Readable.push (internal/streams/readable.js:204:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: -20002,
    sqlState: 'HY000'
  },
  code: -20002,
  sqlState: 'HY000'
}
error Command failed with exit code 1.
```

</details>

I'm not sure it's this, but I saw that the following query could actually fail:

`INSERT INTO "migrations"("timestamp", "name") VALUES (?, ?) -- PARAMETERS: [1628714311876,"firstChange1628714311876"]`

If it's translated to:

`INSERT INTO "migrations"("timestamp", "name") VALUES (1628714311876, "firstChange1628714311876")`

Because for HANA, the values should use simple quotes `'` instead of double quotes.

### Expected Behavior

Migration succeeds.

### Actual Behavior

Error is shown above.

### Steps to Reproduce

I've compiled the example here: https://github.com/lucasheim/typeorm_hana_bug

I did some small debugging and I thought the problem might be from the @sap/hana-client package, but I added an example in the same repository that it shows if I try to run the INSERT into "migrations" command, it works properly, no errors.

Also good to notice that Rollback also fails, so it leaves the database in a weird state and you have to clean up the tables which were actually created and not dropped.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS     |
| Node.js version     | 14.17.4  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | yes            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment] 2021-08-11 22:20
Duplicate of #8007

**Closed by imnotjames** 2021-08-11 22:20 UTC
Labels: bug, requires triage
