### ISSUE TITLE
How can I use my Oracle Cloud wallet in TypeOrm.io?

### ISSUE THREAD

**Issue by EdissonG** [typeorm/typeorm#8373] opened 2021-11-16 22:38 UTC
I created my connection in `TypeScript ` and it worked and it is the following:

```
import oracledb from "oracledb";
import dbConnection from "./dbconfig";

oracledb.initOracleClient({ libDir: 'D:\\MaterialSkywork\\Oracle\\instantclient_21_3' });


async function Open(sql:any, binds:any, autoCommit:any) {
    let cnn = await oracledb.getConnection(dbConnection);
    let result = await cnn.execute(sql, binds, { autoCommit });
    cnn.release();
    return result;
}

exports.Open = Open;

```

This was the connection I made from TypeOrm to oracle:

```
import oracledb from "oracledb";
​import​ ​{​ createConnection  ​}​ ​from​ ​"typeorm"​; 

oracledb.initOracleClient({ libDir: 'D:\\MaterialSkywork\\Oracle\\instantclient_21_3' });

createConnection({
    type: "oracle",
    username: "admin",
    password: "password",
    database: "DB_high",
    ​   ​synchronize​: ​true​, 
}).then(connection => {
    console.log(connection)
}).catch(error => console.log(error));
     

​export​ ​default​ createConnection;
```

And migrating my connection with my Oracle wallet in TypeOrm, I fail to deploy my wallet and it returns TNS error:

![image](https://user-images.githubusercontent.com/64019193/142077078-b96bdd50-a9e5-413e-8444-7867ac4f4517.png)

**Comment by cjbj** [comment] 2022-01-28 05:46
This is  duplicate of https://github.com/typeorm/typeorm/issues/8376

**Comment by Ginden** [comment] 2022-01-28 09:41
Closing as duplicate.

**Closed by Ginden** 2022-01-28 09:41 UTC
Labels: documentation, requires triage
