### ISSUE TITLE
Entity .find() running out of memory with nested eager relations

### ISSUE THREAD

**Issue by adamlong5** [typeorm/typeorm#5829] opened 2020-04-08 14:45 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. I have an entity ("Entity A") that has 4 eager-loaded relations.
2. One of those four eager-loaded relations ("Entity B") in turn has 3 eager-loaded relations.
3. I'm querying multiple of Entity A via `[Entity A].find()` using the ActiveRecord pattern
4. When I do, I get a heap out of memory error when TypeORM is constructing the query string (full stack trace/error below)
5. If I toggle Entity A to no longer eager-load Entity B, I no longer get the error and the query works. If I then add `relations` to the `.find()` to bring back in Entity B and its sub-relations, everything works as well.

**Heap Error**
```console
<--- Last few GCs --->

[15498:0x110000000]    80987 ms: Mark-sweep 1355.1 (1439.8) -> 1355.0 (1439.8) MB, 302.9 / 0.0 ms  (average mu = 0.122, current mu = 0.000) last resort GC in old space requested
[15498:0x110000000]    81318 ms: Mark-sweep 1355.0 (1439.8) -> 1355.0 (1439.8) MB, 331.1 / 0.0 ms  (average mu = 0.062, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x29fb9595be3d]
    1: StubFrame [pc: 0x29fb9591059d]
Security context: 0x269d6c79e6e9 <JSObject>
    2: /* anonymous */ [0x269d5fa6e5a1] [[redacted]/node_modules/typeorm/query-builder/QueryBuilderUtils.js:~14] [pc=0x29fb9646a072](this=0x269d0932c559 <JSFunction QueryBuilderUtils (sfi = 0x269d5fa6e329)>,str=0x269d22c6ac89 <Very long string[77269]>)
    3: getValue [0x269d22c6ad89] [/User...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003c597 node::Abort() [/usr/local/bin/node]
 2: 0x10003c7a1 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001ad575 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100579242 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100582744 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 6: 0x100553ff5 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: 0x100686168 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x1006a5513 v8::internal::String::IndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, int) [/usr/local/bin/node]
 9: 0x10082b0af v8::internal::Runtime_StringIndexOfUnchecked(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x29fb9595be3d
```

**Comment by PaddingtonTheBear** [comment] 2020-04-13 08:36
The issue is that every eager loading adds an additional LEFT JOIN to the query that gets built. When you have nested eagers, the number of rows that gets generated becomes exponential in nature since every unique value in each column will require a new row. 

The "fix" is that TypeORM needs to allow an option for performing individual queries for each eager relationship. Sequelize has a flag for this called "seperate," and TypeORM needs this too.

I actually ran into this recently with a similar use case where I expected TypeORM to return my nested JSON easily, but it killed my NodeJS server with only 50~ rows of relational data as it would generate 500k+ rows for 5-7 eager queries. Instead, if TypeORM had the seperate option, it would simply query each relational table which would generate 5-10 rows, and then join the relational tables in Typescript. You can manually do this with the .find() API, where you have an array of relationships defined and then iterate over each relationship to do a .find() with just that relationship then manually add it into your base entity. This will increase your performance _massively_.

See below for more information and a "fix" that I came up with in the mean time:
https://github.com/typeorm/typeorm/issues/3857#issuecomment-609863113

**Comment by pleerock** [comment] 2021-11-02 17:11
closing in favour of #3857

**Closed by pleerock** 2021-11-02 17:11 UTC
Labels: bug, performance, driver: postgres
