### ISSUE TITLE
HAVING does not work

### ISSUE THREAD

**Issue by codekeyz** [typeorm/typeorm#5450] opened 2020-01-31 18:56 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by likern** [comment] 2020-02-24 16:03
I can confirm that.

**Database:** `sqlite`
**TypeORM version:** `0.2.21`

I have two tables: **tasks** and **tags**, which have **ManyToMany** _relationship_ (one task might have multiple tags and one tag might be assigned to multiple tasks).

**Query:** select all tasks which contains all tags ["Travel", "Birthdays", "Family"]

For doing this I use this TypeORM query:
```ts
taskRepository
      .createQueryBuilder('task')
      .where(queryBuilder => {
        const subQuery = queryBuilder
          .subQuery()
          .select(['task.id'])
          .from(db.Task, 'task')
          .innerJoin('task.tags', 'tag')
          .where('tag.label IN (:...filttags)')
          .groupBy('task.id')
          .having('COUNT(task.id) = :count')
          .getQuery();

        return 'task.id IN ' + subQuery;
      })
      .setParameter('filttags', filterTags)
      .setParameter('count', filterTags.length)
      .getMany()
      .then(result => {
        console.log(`result: [${JSON.stringify(result)}]`);
      });
```
where `filterTags` is `["Tag1Label" ,"Tag2Label", ...]`

**SQLite** generates the following query:
```sql
SELECT "task"."id" AS "task_id", "task"."author" AS "task_author", "task"."title" AS "task_title", "task"."createdAt" AS "task_createdAt", "task"."completedAt" AS "task_completedAt", "task"."isCompleted" AS "task_isCompleted", "task"."isTracked" AS "task_isTracked", "task"."trackedSeconds" AS "task_trackedSeconds" FROM "tasks" "task" WHERE "task"."id" IN (SELECT "task"."id" AS "task_id" FROM "tasks" "task" INNER JOIN "tasks_tags_tags" "task_tag" ON "task_tag"."tasksId"="task"."id" INNER JOIN "tags" "tag" ON "tag"."id"="task_tag"."tagsId" WHERE "tag"."label" IN (?) GROUP BY "task"."id" HAVING COUNT("task"."id") = ?) -- PARAMETERS: ["Birthdays",1]
```
which returns correct results.
![Снимок экрана от 2020-02-24 15-54-37](https://user-images.githubusercontent.com/842306/75154181-3949e180-571e-11ea-9a56-e78f6567f54c.png)

So the problem not in actual query, but in mapping back to entity.

**Problem:**  `result` never contains actual entities, _it is always a empty array_.

I've tried multiple equivalent sql queries, but as soon as I add `.having('COUNT(task.id) = :count')` I stop receiving any task entities, only empty array.

**Entities:**
```
@Entity({ name: 'tasks' })
export class Task {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  author: string;

  @Column('text')
  title: string;

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  @ManyToMany(type => Tag, { eager: true })
  @JoinTable()
  tags: Tag[];

  @Column('datetime')
  createdAt: Date;

  @Column({ type: 'datetime', nullable: true })
  completedAt: Date | null;

  @Column('boolean')
  isCompleted: boolean;

  @Column('boolean')
  isTracked: boolean;

  @Column({ type: 'real', nullable: true })
  trackedSeconds: number | null;
}

@Entity({ name: 'tags' })
export class Tag {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  label: string;

  @Column('text')
  iconName: IconName;

  @Column('text')
  iconColor: string;
}
```

**Comment by imnotjames** [comment] 2020-10-07 05:50
Closing as duplicate of #5564

**Closed by imnotjames** 2020-10-07 05:50 UTC
Labels: bug, driver: postgres
