### ISSUE TITLE
How can we organize a full jest testing project with express and typeorm

### ISSUE THREAD

**Issue by tainbgo1** [typeorm/typeorm#5098] opened 2019-11-18 04:44 UTC
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm adding unit testing by jest for express and typeorm but it's seem many things to handle from` mocking server, app and connection from typeorm`. 
If somebody have already build the example and share it. that would be great.

**Comment by d337** [comment] 2019-11-18 06:55
[TypeORM Jest testing by vlapo](https://github.com/vlapo/typeorm-jest)
Have you seen this?

**Comment by tainbgo1** [comment] 2019-11-18 07:16
> [TypeORM Jest testing by vlapo](https://github.com/vlapo/typeorm-jest)
> Have you seen this?

tks @d337 , It's a good resource. I am stuck on getting the express router which is defined on `createConnection` func. You can understand my question in this repo: https://github.com/typeorm/typescript-express-example

**Comment by imnotjames** [comment] 2020-10-06 06:14
I think this question is a duplicate of #5308 , closing

**Closed by imnotjames** 2020-10-06 06:14 UTC
Labels: driver: mariadb, driver: mysql, question
