### ISSUE TITLE
The save method returns undefined for default values

### ISSUE THREAD

**Issue by laukaichung** [typeorm/typeorm#3440] opened 2019-01-17 06:14 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Older issue: https://github.com/typeorm/typeorm/issues/1869

````
@Entity()
export class Article {

    @PrimaryGeneratedColumn()
    id: string;

    @Column({type:'varchar',length:255})
    title:string;

    @Index()
    @Column({type: 'enum',enum:EntryStatus, default: EntryStatus[EntryStatus.Pending]})
    status: EntryStatus;

}


````

When you save a new record or update an old record , it would return undefined in the status field. 

````
const newArticle = this.repository.save(article);
// newArticle.status is undefined
````

Update: Better example:

````
export class ArticleResolver{

    public constructor(
        @OrmRepository(Article) private readonly repository: Repository<Article>
    ) {}

    public async updateArticle(id, title, text):Promise<Article> {
        let article = await this.repository.findOneOrFail(id);
        article.title = title;
        article.text = text;
        // Up to this point, article.status is defined
        const newArticle = await this.repository.save(article);
        //  newArticle.status is undefined!
        return newArticle;
    }

}
````

I am using type-graphql, so it would throw an error if  the new article is returned with undefined default values.
I have also tried ^0.3.0-alpha.22. The problem is still there.

**Comment by vlapo** [comment] 2019-01-17 09:22
I do not understand this:
```typescript
default: EntryStatus[EntryStatus.Pending]
```
try
```typescript
default: EntryStatus.Pending
```

**Comment by laukaichung** [comment] 2019-01-17 14:32
@vlapo 
My enum object is like this:
````
export enum EntryStatus {
    Approved = "Approved",
    Pending = "Pending",
    Rejected = "Rejected"
}
````
So I have to use `EntryStatus[EntryStatus.Pending]` to save the string value to the status field.

I checked the table and was confirmed that the record was saved successfully. The default Pending value has been saved.

My issue is that `repository.save()` method has a strange behaviour of leaving out values in fields that  are defined with default values. 
@pleerock said in https://github.com/typeorm/typeorm/issues/1869 the @next version would fix it, but that has never happened.

**Comment by vlapo** [comment] 2019-01-17 15:05
I tried reproduce on latest codebase and still got status set to default value.

From your first post:
> ```
> const newArticle = this.repository.save(article);
> // newArticle.status is undefined
> ```
`this.repository.save(article);` return promise. `const newArticle = await this.repository.save(article);` await is missing.

> So I have to use EntryStatus[EntryStatus.Pending] to save the string value to the status field.

No do not have to.`EntryStatus[EntryStatus.Pending]` will get same result as `EntryStatus.Pending` for your case of enum.

**Comment by Wintereise** [comment] 2019-01-18 01:15
While this isn't a fix for this issue, instead of `default: EntryStatus[EntryStatus.Pending]`, set the default value in code directly. Less magic is always good.

`status: EntryStatus = EntryStatus[EntryStatus.Pending]`

**Comment by pleerock** [comment] 2019-01-18 06:16
@Wintereise its not magic since its how ORM works out of the box - it should set all DEFAULT values defined in SQL to return after you call `save`. We need a failing test for this issue to check if issue really exists.

**Comment by Wintereise** [comment] 2019-01-18 08:41
@pleerock Then this is probably nothing but a case of the schema (default definition) not being in sync with the Entity definition.

Since the hydration of the default value is done in the DB itself and not code.

**Comment by laukaichung** [comment] 2019-01-18 14:53
This only occurs when you don't do anything with default values when the row is updated/ created. I have tested it with int or enum type columns, and the issue is still the same.

**Comment by vlapo** [comment] 2019-01-18 20:08
@laukaichung please create PR with failing test and we will check the problem.

**Comment by Kononnable** [comment] 2019-04-20 22:13
Closing as no response from the author.

**Closed by Kononnable** 2019-04-20 22:13 UTC
Labels: needs failing tests

**Comment by quanbrew** [comment] 2019-09-10 15:07
cc https://github.com/typeorm/typeorm/issues/1869
