### ISSUE TITLE
Bug when trying to use FindOperator

### ISSUE THREAD

**Issue by feihan** [typeorm/typeorm#5373] opened 2020-01-17 20:06 UTC
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I created a select statement according to the documentation. This code is pretty old and i think it worked some while ago. 
But suddenly i get an Error:
'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \' `_value` = \'%s%\', `_useParameter` = true, `_multipleParameters` = false, `usePa\' at line 1',

I also tried with the other FindOperators.

`
return this.categoryRepository.find({
            where: { name: Like('%' + searchString + '%') },
        });
`

The Problem is in the QueryBuilder:
`
parameterValue instanceof FindOperator
`

He always returns false, even if in debug mode, it shows that is a FindOperator.
if i create a FindOperator object in my service and make the instanceof check, it returns correctly true.
Anyone an idea how this could happen? I tried to downgrade typeorm to 2.2.0, but it didnt change. 
I use typescript 3.7.5.
Any other ideas what i can try?

**Comment by imnotjames** [comment] 2020-10-07 07:01
Duplicate of https://github.com/typeorm/typeorm/issues/3959

**Closed by imnotjames** 2020-10-07 07:01 UTC
Labels: bug, driver: mariadb, driver: mysql
