### ISSUE TITLE
Migration should either read .ts or deliver a .js

### ISSUE THREAD

**Issue by GitBalou** [typeorm/typeorm#1675] opened 2018-02-28 10:34 UTC
This is either a bug or a new feature

[ ] question
[ x] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
`typeorm migrations:generate -n test` this create typecript file test.ts
`typeorm migrations:run` this fails with `Unexpected token import`

**What solves the issue**
Either call typeorm using ts-node, as explained here : https://github.com/typeorm/typeorm/issues/1561
Either transpile .ts file .js using typescript

**Expected behaviour**
Typeorm should be able to read the file it generated, which means : reading ts file or providing .js file

**Comment by pleerock** [comment] 2018-02-28 15:58
any application you write in typescript you need to compile and run. So its quite normal that you need to compile before you run a typescript code.

**Comment by eyelidlessness** [comment] 2018-02-28 18:32
The issue as reported is that **TypeORM** is generating files that it then cannot read. I have seen this behavior as well.

**Comment by pleerock** [comment] 2018-02-28 19:18
what does it mean **it cannot read** ?! TypeORM does not read files, node does. TypeORM generates you a file, you compile it, then your node runs js files.

**Comment by eyelidlessness** [comment] 2018-02-28 19:23
What I mean is:

1. `migrations:generate` generates migrations, in the form of files
2. It is expected that `migrations:run` runs those migrations, by reading those files and running them - but it does not do that

**Comment by eyelidlessness** [comment] 2018-02-28 19:25
If the expectation is that `migrations:run` accepts only JS files, then `migrations:generate` should generate only JS files. It is very confusing for the automatic migration generator to generate migrations that cannot be run.

**Comment by pleerock** [comment] 2018-02-28 19:30
wrong logic. If node can run only js files it does not mean that we need to write js files. are you new in typescript?

**Comment by eyelidlessness** [comment] 2018-02-28 19:30
It's worth noting that nothing in the documentation about migrations indicates that TS migration files (whether written manually or generated by `migrations:generate`) need to be compiled to be run. The assumption based on the documentation is that `migrations:run` handles TS migrations.

**Comment by eyelidlessness** [comment] 2018-02-28 19:33
It's not "wrong logic" to expect that automatically generated migrations can be run by the migrations runner. I'm not "new in typescript" and I know how transpilation works. I don't appreciate being attacked. Is this how you always address feedback?

**Comment by pleerock** [comment] 2018-02-28 19:38
You can take a look any of 1000+ issues and you'll find how I usually address issues.

Asking if you are "new in typescript or not" is not an "attack", it is a question. Question based on your questions, they don't make any sense to me if they are being asked by somebody who knows how typescript works. 

Let me give you another question, what do you think `entity:generate` should generate you? `js` or `ts` file?

**Comment by eyelidlessness** [comment] 2018-02-28 19:43
1. I explained **why** I have the expectation that generated migrations are runnable. It is already clear I know how Typescript works.
2. Questioning someone's experience with Typescript is addressing the person rather than what you suspect is missing knowledge. That is an attack.
3. Even if it wasn't intended as such, when someone expresses that they feel attacked by that approach, consider understanding why the person felt that way.
4. I have no idea what `entity:generate` should do, it isn't something I've looked deeply into because I would never use it. Given #1679, it isn't clear to me how it would matter, as neither TS nor JS entity files appear to work at all.

**Comment by pleerock** [comment] 2018-02-28 20:09
> consider understanding why the person felt that way

do you really think Im going to ask you here why you felt that way? Seriously this place is not for feeling discussion. I know you felt that way simply because you did not like that I told you that you don't understand something. I still think the same. But there is nothing wrong with it - if you don't understand yet how node + typescript works together and how runtime is organized there is nothing wrong with it, you'll learn. You should not treat it as an attack. Thats a problem if you treat such things as attacks.

Do you want to know what I feel? I feel I spend 30 minutes for free trying to answer your question without harming your feelings. My wife is near me and waiting for me when I finish typing answer to you. Do you understand how much resources it took to answer to a simple question? And thats what I do every day.

I'll close this issue, since its not a real issue but more like a question. Consider asking questions to the community in gitter. And once you and community come with some idea or feature how to improve this come back and report a new issue.

**Closed by pleerock** 2018-02-28 20:09 UTC
Labels: invalid

**Comment by kswope** [comment] 2018-04-22 21:10
I'm with @eyelidlessness , 

a CLI that must be run SOMETIMES in a different way is just bizarre, and have it **completely undocumented**?

Look at it from my point of view, I'm 15 minutes into typeORM for the first time and already searching the github issues, its not a friendly welcoming.

The only solution I can think of is just
```
       "scripts": {                                                                                              
          "start": "ts-node src/index.ts",                                                                       
          "typeorm": "ts-node ./node_modules/.bin/typeorm"                                                       
       }
```

And instruct users to run with double dashes
```
npm run typeorm -- query "select * from user"
```

**Comment by pleerock** [comment] 2018-04-23 04:51
> a CLI that must be run SOMETIMES in a different way is just bizarre

you got it wrong, it does not have SOMETIMES in a different way. Simply, if you are using ts-node you must run ts files, if you are using node you must run js files

> its not a friendly welcoming.

Im really sorry about your feelings but sometimes people forget what is open source

**Comment by kswope** [comment] 2018-04-23 05:44
> I'm really sorry about your feelings but sometimes people forget what is open source and don't think before talking something

Feelings has nothing to do with it, we're trying to be helpful and suggest an improvement.

The user of this CLI has no idea what's going on, it may be a bash script that sometimes runs ts-node and sometimes doesn't.  

Just look at the help, nobody would think you have to sometimes run the CLI through a preprocessor after seeing this output.  The actual behavior is not faithful to the implied behavior.  I think if the command typeorm was replaced with something like a bash script that checked for ts-node and used it, it would be more user friendly.

```
(xenial)kevin@localhost:~$ typeorm --help
Usage: typeorm <command> [options]

Commands:
  typeorm schema:sync         Synchronizes your entities with database schema.
                              It runs schema update queries on all connections
                              you have. To run update queries on a concrete
                              connection use -c option.
  typeorm schema:log          Shows sql to be executed by schema:sync command.
                              It shows sql log only for your default connection.
                              To run update queries on a concrete connection use
                              -c option.
  typeorm schema:drop         Drops all tables in the database on your default
                              connection. To drop table of a concrete
                              connection's database use -c option.
  typeorm query               Executes given SQL query on a default connection.
                              Specify connection name to run query on a specific
                              connection.
  typeorm entity:create       Generates a new entity.
  typeorm subscriber:create   Generates a new subscriber.
  typeorm migration:create    Creates a new migration file.
  typeorm migration:generate  Generates a new migration file with sql needs to
                              be executed to update schema.
  typeorm migration:run       Runs all pending migrations.
  typeorm migration:revert    Reverts last executed migration.
  typeorm version             Prints TypeORM version this project uses.
  typeorm cache:clear         Clears all data stored in query runner cache.
  typeorm init                Generates initial TypeORM project structure. If
                              name specified then creates files inside directory
                              called as name. If its not specified then creates
                              files inside current directory.

Options:
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]
```

**Comment by pleerock** [comment] 2018-04-23 05:48
`ts-node` is a third-party tool, and have nothing to do with typeorm. You can use it, and can not to use it. `typeorm` executes in node, and node requires `javascript` files, it means if you want to execute something using CLI you need to use js files. Can you please tell me what exact problem you have and I'll try to explain more.

**Comment by eyelidlessness** [comment] 2018-04-23 06:42
The issue is that certain commands operate on typescript files and others don’t but the documentation doesn’t distinguish that. It’s really that simple. It would be nice if a TS library didn’t require a user to account for that distinction but a documentation change could at least mitigate it

**Comment by eyelidlessness** [comment] 2018-04-23 06:45
> if you want to execute something using CLI you need to use js files

This is not always true, even in the current topic. This is the nature of the problem

**Comment by kswope** [comment] 2018-04-23 17:44
> ts-node is a third-party tool, and have nothing to do with typeorm.


```
$ typeorm init

$ grep -r ts-node .
./package.json:      "ts-node": "3.3.0",
./package.json:      "start": "ts-node src/index.ts"

```

**Comment by pleerock** [comment] 2018-04-24 05:46
> $ typeorm init

it just setups you some tools that can help you during development, just like if you specify express option and will add express as well or if you specify a docker option it create you a docker-compose file. typeorm still is separate and have nothing to do with them.

**Comment by pleerock** [comment] 2018-04-24 05:49
Lets start from the beginning. What is exact issue and how we are suppose to fix it? As I see @eyelidlessness suggests to add notes to the documentation, if yes, then please provide a proposals on what should be added. If there can be better solution other then changing documentation, then please propose them as well.

**Comment by kswope** [comment] 2018-04-24 19:04
@eyelidlessness 
Does this bug equally effect my solution of ts-node always running automatically and the currently recommended way of running like 
```
ts-node ./node_modules/.bin/typeorm migrate
```

Are you suggesting that typeorm CLI always generate js files? (which probably wont look that different from ts files anyway)

**Comment by eyelidlessness** [comment] 2018-04-24 19:12
> Does this bug equally effect my solution of ts-node always running automatically and the currently recommended way of running like

I haven't tested but I believe it would from my experience. I've worked around this in another situation by directly altering the source going into the TypeScript compiler by importing `Date` from another module that exports it. I'm not sure that'd be acceptable for a general solution but it worked in my project.

> Are you suggesting that typeorm CLI always generate js files? (which probably wont look that different from ts files anyway)

IMO that is probably the least worst solution currently.

**Comment by kswope** [comment] 2018-04-24 19:27
No, but for others, like entity:create

**Comment by kswope** [comment] 2018-04-24 19:29
Hmm,  entity:create just spits out anything it wants, probably from a template, is there anything what are the commands that cause typeorm CLI to read a file and that file has to look typescripy?

**Comment by pleerock** [comment] 2018-04-25 05:41
> What about breaking out into a typeorm-cli?

I don't want doing that. At least not now. But maybe in the future it will be.

> I want to add a note that ts-node is not a silver bullet here. 

that's right. I faced some very bad unresolvable issues with ts-node on windows platform that I don't have on my mac. This tool may become useful for somebody and for somebody it may be better not to use it. Its my opinion and its based on my experience working with ts-node.

**Comment by dkfiresky** [comment] 2018-05-20 14:45
Will this ever be fixed? How is that even possible that you can't run migrations out of the box?

**Comment by RDeluxe** [comment] 2018-06-05 18:29
Hello there.

At least we should consider updating the documentation. On the main page we stille have : 

```json
{
   "type": "mysql",
   "host": "localhost",
   "port": 3306,
   "username": "test",
   "password": "test",
   "database": "test",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ]
}
```

But we know that generating migrations using ts files won't work (as referred here => https://github.com/typeorm/typeorm/issues/1561)

**Comment by victorschinaider** [comment] 2018-07-19 00:20
I'm having terrible problems with migrations that do not read Typescript file. =/

**Comment by t3hmrman** [comment] 2018-08-08 04:18
Hey I just ran into this -- a reasonable solution (in my mind) was to just change `migrations` config to point to the output dir that TS uses. 

As others have noted, another decent workaround is to install `ts-node`, in my case I use `yarn` so I installed it as one of the `devDependencies` (along with `typeorm` and `typescript` -- not a huge fan of global installs). Then I can locally alias `typeorm` through `packages.json`'s `scripts` section, or in a `Makefile` or whatever:

`packages.json`
```json
"scripts": {
  "typeorm":
```
`Makefile`
```make
.PHONY: migrate-db

TYPEORM=./node_modules/.bin/ts-node ./node_modules/.bin/typeorm
# TYPEORM=yarn typeorm

migrate-db:
  $(TYPEORM) migration:run
```

Hopefully someone else finds this useful.

Maybe for now the fix is to just update the documentation to include this workaround? I can jump on it, given there's some indication that's what people actually want

**Comment by eliranmal** [comment] 2018-09-03 23:06
hey, @t3hmrman, great suggestions 👍 

i'm currently facing the same issue and realized that the first option won't work if you reuse the *ormconfig* file elsewhere in addition to CLI usage (e.g. importing it in the source and passing it to create a connection); the paths would be wrong in one of the cases.

the second one (using `ts-node`) seem to be the most acceptable solution, as you can have the same paths for `migrations`, `entities` etc. both for CLI and API invocations.

🍻

**Comment by Matzu89** [comment] 2018-09-14 14:44
Ah.. this makes sense.. Thnx for your commitment, everyone..

I got it working doing the following:

Package.json:
`{ 
 "scripts": {
    "typeorm": "ts-node ./node_modules/.bin/typeorm"
  } }`

`npm run typeorm migration:generate -n test` - FAILS due to npm not capturing the -n argument

`yarn typeorm migration:generate -n test` - WORKS

Also, @pleerock, you need to find some balance in life and start being *not* an asshole. Several people have addressed you on your behavior. This means you are affecting them. Instead of attacking them as well, maybe it's time to buy a mirror and take a good look into it.

**Comment by Kononnable** [comment] 2018-09-15 07:38
@Matzu89, I think you(and not only you) expect a little of enterprise support from open source library. Library is build on someone free time and most likely people answering questions will be after work so they might be more tired and jumpy. Because of that there will be no phrases like 'Dear Sir' and more strict questions, which sometimes might sound offensive(if you don't remember about the context).

As for the npm solution I think it might be failing because lack of `--`.
[Sending command line arguments to npm script](https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script)

**Comment by abser** [comment] 2018-11-01 03:44
I am using .ts file and below workaround works for me.

```
"script": {
"typeorm": "ts-node ./node_modules/.bin/typeorm"
}
```
`npm run typeorm migration:run`

**Comment by havenchyk** [comment] 2018-11-01 08:28
Guys, I agree that current behavior is confusing, but still, please consider the next points:

- It's opensource and if you want to contribute, provide a PR, make a donate, make a RFC issue etc
- @pleerock is not a native English speaker, so you can get him wrong

You can always create your own library as a fork of current and try to address feedback, I believe everybody understands that, so just be grateful and polite to all the contributors who spent their free time on a lib that helps you with doing your job.

@pleerock could you please lock this conversation?

**Comment by hkjeffchan** [comment] 2018-12-21 09:13
Created a PR on CLI doc to explain this.
https://github.com/typeorm/typeorm/pull/3305
