### ISSUE TITLE
Updating ManyToOne relationship possibly forwarding wrongly formatted request to tedious

### ISSUE THREAD

**Issue by brokenthorn** [typeorm/typeorm#4955] opened 2019-10-23 06:21 UTC
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[X] `mssql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.19`

I'm using TypeORM and Type-GraphQL, so keep that in mind.

`ArticleRequest ` Entity:

```ts
@ObjectType({ description: "Request for a new article." })
@Entity()
export default class ArticleRequest extends BaseEntity {
  @Field(() => ID, { description: "Article request ID." })
  @PrimaryGeneratedColumn()
  id!: number;

  @Field({ description: "Requested article's name." })
  @Column({ unique: true, length: 100 })
  name!: string;

  @Field(() => Int, {
    nullable: true,
    description:
      "Equivalent article ID in an external database. " +
      "It is null if the request hasn't been processed or has been rejected.",
  })
  @Column({ nullable: true })
  @Index({ unique: true, where: "externalId IS NOT NULL" })
  externalId?: number;

  @Field()
  @ManyToOne(() => ArticleCategory, {
    eager: true,
    nullable: false,
    cascade: ["update"],
  })
  @JoinColumn()
  category!: ArticleCategory;

  @Field()
  @ManyToOne(() => ArticleSubcategory, { eager: true, nullable: false })
  @JoinColumn()
  subcategory!: ArticleSubcategory;

  @Field()
  @ManyToOne(() => Company, { eager: true, nullable: false })
  @JoinColumn()
  producer!: Company;

  @Field(() => Float, { description: "VAT Percent. DECIMAL(6,3)" })
  @Column("decimal", { precision: 6, scale: 3 })
  vatPercent!: number;

  @Field({
    nullable: true,
    description:
      "True if request was accepted. False if not. " +
      "Null if the request hasn't been reviewed yet.",
  })
  @Column({ nullable: true })
  accepted?: boolean;

  @Field()
  @CreateDateColumn()
  createdDate!: Date;

  @Field()
  @UpdateDateColumn()
  updatedDate!: Date;
}
```

`ArticleRequestResolver`:

```ts
@Resolver(ArticleRequest)
export class ArticleRequestResolver {

// some code omitted...

@Mutation(() => ArticleRequest, {
    description: "Update an existing article request in the database.",
  })
  async updateArticleRequest(
    @Arg("articleRequest") updateArticleRequestInput: UpdateArticleRequestInput,
  ): Promise<ArticleRequest> {
    const { id, ...rest } = updateArticleRequestInput;
    await ArticleRequest.update(id, rest).catch(reason => {
      throw reason;
    });

    return await ArticleRequest.findOneOrFail(updateArticleRequestInput.id);
  }
}
```

Mutation request that I'm testing and that fails:

```gql
mutation {
  updateArticleRequest(
    articleRequest: {
      id: 10
      name: "Test article request 1 - updated several times (check updateDate)"
      category: { id: 7 }
    }
  ) {
    updatedDate
    id
    name
    externalId
    accepted
    category {
      id
      name
    }
  }
}
```

From my testing it seem that the problem stems from the fact that `rest.category` (which is the single non-primitive type in the request) is proto-less:

![image](https://user-images.githubusercontent.com/2119004/67363042-28713f80-f575-11e9-9c25-b58b5a0243c0.png)

Here's the error and query that fails:

```sh
query: UPDATE "article_request" SET "name" = @1, "categoryId" = @2, "updatedDate" = CURRENT_TIMESTAMP WHERE "id" IN (@0) -- PARAMETERS: [10,{"value":"Test article request 1 - updated several times (check updateDate)","type":"nvarchar","params":["100"]},{"value":{"id":"7"},"type":"int","params":[]}]
query failed: UPDATE "article_request" SET "name" = @1, "categoryId" = @2, "updatedDate" = CURRENT_TIMESTAMP WHERE "id" IN (@0) -- PARAMETERS: [10,{"value":"Test article request 1 - updated several times (check updateDate)","type":"nvarchar","params":["100"]},{"value":{"id":"7"},"type":"int","params":[]}
]
error: { RequestError: Cannot convert object to primitive value
    at handleError (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\tedious.js:566:15)
    at parent.acquire (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\tedious.js:858:11)
    at _acquire.then.connection (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\base.js:175:42)
  code: 'EREQUEST',
  number: undefined,
  lineNumber: undefined,
  state: undefined,
  class: undefined,
  serverName: undefined,
  procName: undefined,
  originalError:
   { Error: Cannot convert object to primitive value
       at handleError (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\tedious.js:564:19)
       at parent.acquire (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\tedious.js:858:11)
       at _acquire.then.connection (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\base.js:175:42)
     info:
      TypeError: Cannot convert object to primitive value
          at parseInt (<anonymous>)
          at Object.validate (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\tedious\lib\data-types\int.js:29:13)
          at Request.validateParameters (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\tedious\lib\request.js:157:36)
          at Request.transformIntoExecuteSqlRpc (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\tedious\lib\request.js:94:14)
          at Connection.execSql (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\tedious\lib\connection.js:1439:13)
          at parent.acquire (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\tedious.js:856:65)
          at _acquire.then.connection (C:\Users\broke\Code\Projects\ineed-backend-service\node_modules\mssql\lib\base.js:175:42) },
  name: 'RequestError' }
```

It seems it tries to `parseInt` on an argument of `{ id: 7 }` and fails.

If I set the object prototype like this:

```ts
    Object.setPrototypeOf(rest.category, {});
    await ArticleRequest.update(id, rest).catch(reason => {
      throw reason;
    });
```

Then the query works!

```json
{
  "data": {
    "updateArticleRequest": {
      "updatedDate": "2019-10-23T06:13:42.900Z",
      "id": "10",
      "name": "Test article request 1 - updated several times (check updateDate)",
      "externalId": null,
      "accepted": null,
      "category": {
        "id": "7",
        "name": "OTC"
      }
    }
  }
}
```

The query that works, now looks like this:

```sh
query: UPDATE "article_request" SET "name" = @1, "categoryId" = @2, "updatedDate" = CURRENT_TIMESTAMP WHERE "id" IN (@0) -- PARAMETERS: [10,{"value":"Test article request 1 - updated several times (check updateDate)","type":"nvarchar","params":["100"]},{"value":"7","type":"int","params":[]}]
```

Comparing these two queries, the first one that failed and the second one that succeeded, the only difference is in the PARAMETERS:

`PARAMETERS: [10,{"value":"Test article request 1 - updated several times (check updateDate)","type":"nvarchar","params":["100"]},{"value":{"id":"7"},"type":"int","params":[]}]`

`[10,{"value":"Test article request 1 - updated several times (check updateDate)","type":"nvarchar","params":["100"]},{"value":"7","type":"int","params":[]}]`

More specifically, the third argument, `{"value":{"id":"7"},"type":"int","params":[]}` vs `{"value":"7","type":"int","params":[]}`.

Why does the value get set to "7" (the category id) only when the object has a prototype and it gets set to a full representation of the object and its own properties when `rest.category` has no prototype?

**Comment by brokenthorn** [comment] 2019-10-23 06:34
https://github.com/typeorm/typeorm/issues/4218#issuecomment-542073018 :

> Yeah, problem with `Object.create(null)` is global one and it would need one global solution, so let's keep the discussion in one issue.
> 
> Closing in favor of #2065

Seems I may have posted a duplicated of #2065?

**Comment by imnotjames** [comment] 2020-10-10 12:04
Duplicate of #2065

**Closed by imnotjames** 2020-10-10 12:04 UTC
Labels: bug, driver: mssql, question
