### ISSUE TITLE
column "xxx" contains null values

### ISSUE THREAD

**Issue by nicetomeetnode** [typeorm/typeorm#5653] opened 2020-03-10 06:31 UTC
i define a entity as 
```
@Entity()
export class ManyDb {
    //复合主列
    @PrimaryGeneratedColumn()
    id: number;

    @PrimaryGeneratedColumn("uuid")
    name: string;

    @Column()
    age: number;

    @CreateDateColumn()
    createDate: Date;

    @UpdateDateColumn()
    updateDate: Date;

    @VersionColumn()
    versionColumn: number;

}
```
everything is ok when i first start my application and use this entity.
but, when i change my entity just as 
```
    @Column({type:"bigint"})
    age: number;
```

and then i restart my application,it will throw an exception just like this 
```
 [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3128ms
QueryFailedError: column "age" contains null values
    at new QueryFailedError (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Query.callback (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:176:38)
    at Query.handleError (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\query.js:145:17)
    at Connection.connectedErrorMessageHandler (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\client.js:214:17)
    at Connection.emit (events.js:210:5)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\connection.js:134:12)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
    at Socket.Readable.push (_stream_readable.js:235:10)
[Nest] 19996   - 2020/03/10 下午2:19:37   [ExceptionHandler] column "age" contains null values +3ms
QueryFailedError: column "age" contains null values
    at new QueryFailedError (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Query.callback (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:176:38)
    at Query.handleError (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\query.js:145:17)
    at Connection.connectedErrorMessageHandler (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\client.js:214:17)
    at Connection.emit (events.js:210:5)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\projects\nest_study\fz-14-typeorm\node_modules\pg\lib\connection.js:134:12)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
    at Socket.Readable.push (_stream_readable.js:235:10)
```

and my table doesn't contain any record where age is null

**Comment by juzhiyuan** [comment] 2020-03-10 07:52
You could set default value 0 for age.

**Comment by nicetomeetnode** [comment] 2020-03-10 08:40
if i don't want to set "nullable" or "default value"&nbsp; ,do you have anthor way to solve this problem?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "琚致远"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 下午3:52
收件人: "typeorm/typeorm"<typeorm@noreply.github.com&gt;; 
抄送: "18046044960"<18046044960@189.cn&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [typeorm/typeorm] column &quot;xxx&quot; contains null values (#5653)




You could set default value 0 for age.

**Comment by nicetomeetnode** [comment] 2020-03-10 08:43
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"琚致远"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 下午3:52
收件人:&nbsp;"typeorm/typeorm"<typeorm@noreply.github.com&gt;;
抄送:&nbsp;"linxiaowei"<18046044960@189.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [typeorm/typeorm] column "xxx" contains null values (#5653)




You could set default value 0 for age.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







and i am a chinese,my qq is&nbsp;3122628874,if you have qq,please&nbsp;add me as a friend on qq,i have anthor question about "Adjacency list" to&nbsp;Consult you，thank you!

**Comment by juzhiyuan** [comment] 2020-03-10 10:08
那就去把数据库内现存数据清掉。。。

**Comment by jeffysam6** [comment] 2020-05-30 06:26
found a solution for this issue? @nicetomeetnode

**Comment by boan-anbo** [comment] 2020-09-26 14:11
> found a solution for this issue? @nicetomeetnode 
As **SamuelColacchia**'s answer in https://github.com/typeorm/typeorm/issues/4498 suggests, delete the data in your database, since you have made changes to the entity, there will be inconsistency between the old data and the new

**Comment by frodonLD** [comment] 2020-09-28 15:50
Hey, what about this issue please?

**Comment by imnotjames** [comment] 2021-06-25 05:53
What are the queries it's attempting?

I can't replicate this locally.

**Comment by imnotjames** [comment] 2021-06-25 05:53
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2021-06-25 05:53
If you include that information please reopen the issue.

**Closed by imnotjames** 2021-06-25 05:53 UTC
