### ISSUE TITLE
Optionally disallow columns from showing in query 

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#828] opened 2017-09-06 05:44 UTC
I'd like to have a way to prevent a column from showing up in a query if the option is enabled. (for example, blacklisting a password and hash unless explicitly requesting for them)

As part of this feature request, I'd also like a way to explicitly request these blacklisted columns when requested. This is a very similar feature I'm requesting as [`{select: false}`](mongoosejs.com/docs/2.7.x/docs/schematypes.html) in mongoose.

**Comment by pleerock** [comment] 2017-09-06 05:56
There is a possibility to partial only select columns you need, for example:

```ts
const user = await userRepository
     .createQueryBuilder('row')
     .select('row.id')
     .addSelect('row.username')
     .where('row.username = :name', {name: 'username'})
     .getOne();
```

**Comment by crutchcorn** [comment] 2017-09-06 15:57
But is it possible to change this from the model definition? I would like password and hash to ALWAYS be hidden from TypeORM queries unless otherwise explicit calling. This will cut down on the possibility of developer errors and make things easier to secure

**Comment by pleerock** [comment] 2017-09-06 16:21
We can add a new option and/or decorator to support this, however how many use cases it will have? I don't know any other cases other then user passwords in general applications where it can be helpful. Isn't it enough to simply delete property once you load user?:

```ts
const user = await ...;
delete user.password;
```

**Comment by crutchcorn** [comment] 2017-09-06 16:24
`delete` is horribly slow IIRC, and goes back to my "developers managing things they need not always manage". I think that this could have implamentations for anything that might hold private information (SSN, passwords, PII, etc)

**Comment by pleerock** [comment] 2017-09-08 07:18
This feature is implemented and will be released in next (`0.1.0-alpha.38`) version. Usage:

```ts
import {Entity} from "../../../../../src/decorator/entity/Entity";
import {Column} from "../../../../../src/decorator/columns/Column";
import {PrimaryColumn} from "../../../../../src/decorator/columns/PrimaryColumn";

@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;

    @Column()
    text: string;

    @Column({ select: false })
    authorName: string;

}
```

**Closed** 2017-09-08 07:18 UTC
Labels: comp: query builder, new feature

**Comment by crutchcorn** [comment] 2017-09-20 02:46
While I am able to do what you recommended with:
```
 const user = await userRepository
    .createQueryBuilder('row')
    .select('row.id')
    .addSelect('row.email')
    .addSelect('row.password')
    .where('row.email = :name', {name: 'email'})
    .getOne();
```

I would have to continue adding `addSelect` to get a complete user. Would it be possible to have `addSelect` without `select` to add the item again? EG:
```
 const user = await userRepository
    .createQueryBuilder('row')
    .addSelect('row.password')
    .where('row.email = :name', {name: 'email'})
    .getOne();
```

Having return the entire user rather than having it return the item without `password`? @pleerock

**Comment by crutchcorn** [comment] 2017-09-20 03:18
It is also important to note that while using `.save()`, the object from `.save()` is still returning the column that is `select: false`. I think, personally, that these should be excluded when using `save`

**Comment by pleerock** [comment] 2017-09-20 04:56
`save` does not reselect anything. It just returns model you have send to it. I don't think it should remove something from your model. Its unexpected behaviour.

> I would have to continue adding addSelect to get a complete user. Would it be possible to have addSelect without select to add the item again? EG:

I don't understand what you mean. `addSelect` adds a new select, and if you already have a selection and add password select then password will be double selected. I can't get what you want here.

**Comment by crutchcorn** [comment] 2017-09-20 05:46
Doesn't the object from the `save` promise return the object that was saved from the DB? If not, why does it return the `id` of the object from the db? If it does, doesn't it make sense that it would respect the same select rules from the entity definition? 

Let's say I don't use a `select` and just have the code sample with the `addSelect`, it only returns the object without the `{select: false}` attribute. I think that the `addSelect` on a query without a `select` should add that item to the query. 
EG: 
``` 
const user = await userRepository
    .createQueryBuilder('row')
    .addSelect('row.password')
    .where('row.email = :name', {name: 'email'})
    .getOne();
``` 

Currently returns: 
``` 
{ 
  id: 2828, 
  email: "test"
}
``` 

But I believe it SHOULD return: 
``` 
{ 
  id: 2828, 
  email: "test", 
  password: "test"
}
```

**Comment by pleerock** [comment] 2017-09-20 06:31
> Doesn't the object from the save promise return the object that was saved from the DB? If not, why does it return the id of the object from the db? If it does, doesn't it make sense that it would respect the same select rules from the entity definition?

no it does not return object from a database. If we re-load object from the database it will add another additional query to lot of exist queries `save` method does. Ids are inserted into exist object and its expected because how we would get newly generated ids otherwise. And we need them in 99% cases. Its a common practice. However if we remove something from user model its totally unexpected.

**Comment by crutchcorn** [comment] 2017-09-20 06:58
I really appreciate you making the changes to the `addSelect`. This was by far the more important of the two issues I was suggesting/arguing for. As for the attributes returning in the `save` method despite their `select` status in `Column`, I think that the object in the Promise should reflect what it would look like to call the DB. The use case for this would be something like this:
https://github.com/crutchcorn/PET-Template/blob/master/src/modules/Users/config/users.config.ts#L74

I am having to store the object before adding the password field and then adding to ID in later using `Object.assign`. If it respected my `select: false`, I could have avoided this and simply passed my user to be saved. 

I hope my code example helped, but if you feel it's too much of an edge-case or that performance would be impacted too greatly to implament this, I completely understand and respect your decision as the project maintainer here. I really do appreciate all the work you've put into this kickass project and the wonderful support you've provided

**Comment by pleerock** [comment] 2017-09-20 07:09
Yes its too much specific use case. Changed Ive added will be released in next (alpha.46) version

**Comment by crutchcorn** [comment] 2017-09-21 02:39
One last thing of note:
I believe this should be documented [here](https://typeorm.github.io/query-builder.html)

**Comment by sadhakbj** [comment] 2019-12-19 10:15
> This feature is implemented and will be released in next (`0.1.0-alpha.38`) version. Usage:
> 
> ```ts
> @Entity()
> export class Post {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @Column()
>     title: string;
> 
>     @Column()
>     text: string;
> 
>     @Column({ select: false })
>     authorName: string;
> 
> }
> ```

I don't want password to be displayed, so I want to hide it. Adding select false to the field will never allow me to login when I have to make query to fetch the user with provided email and password.

Is there any solution similar to Eloquent ORM's hidden ?

**Comment by danielsss** [comment] 2019-12-23 03:56
> > This feature is implemented and will be released in next (`0.1.0-alpha.38`) version. Usage:
> > ```ts
> > @Entity()
> > export class Post {
> > 
> >     @PrimaryGeneratedColumn()
> >     id: number;
> > 
> >     @Column()
> >     title: string;
> > 
> >     @Column()
> >     text: string;
> > 
> >     @Column({ select: false })
> >     authorName: string;
> > 
> > }
> > ```
> 
> I don't want password to be displayed, so I want to hide it. Adding select false to the field will never allow me to login when I have to make query to fetch the user with provided email and password.
> 
> Is there any solution similar to Eloquent ORM's hidden ?

any updates ?

**Comment by crutchcorn** [comment] 2019-12-23 06:06
As mentioned in the thread, you're able to explicitly query the password field by using `addSelect` to the field, as documented above.

**Comment by 0xCAP** [comment] 2020-05-23 13:48
Hi, outside of "addSelect" is there any way to retrieve "hidden" properties using the AR pattern?

**Comment by antonioGabrielGomes** [comment] 2022-09-17 03:27
I did it this way in the repository creation method:
...
return  { 
  id: entity.id,
  name: entity.name
} as Entity
