### ISSUE TITLE
migration runner refused to create check constraint in mysql 8.0.16

### ISSUE THREAD

**Issue by amjedomar** [typeorm/typeorm#6103] opened 2020-05-20 10:14 UTC
### Issue type:

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

### Database system/driver:

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

### TypeORM version:

[ ] `latest`
[ ] `@next`
[X] `0.2.25` (or put your version here)

### Steps to reproduce the problem

Execute the following  migration

```ts
import {MigrationInterface, QueryRunner, TableCheck} from 'typeorm';

export class AlterSomeTable1589965831962 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createCheckConstraint('some_table', new TableCheck({
      name: 'ck_value',
      expression: "`value` < 5"
    }));
  }

  public async down(queryRunner: QueryRunner): Promise<any> {

  }

}
```

Then you will get the following error
```txt
Error during migration run:
Error: MySql does not support check constraints.
```

However MySQL [8.0.16](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html) support check constriant

**Comment by amjedomar** [comment] 2020-05-31 13:42
@pleerock can you take a look at this issue please

**Comment by imnotjames** [comment] 2020-10-14 06:09
Duplicate of #4148

**Comment by imnotjames** [comment] 2020-10-14 06:09
TLDR: Check constraints on MySQL aren't implemented yet.  Feel free to push along the PR proposed as part of that issue

**Closed by imnotjames** 2020-10-14 06:09 UTC
Labels: bug, comp: migrations, driver: mariadb, driver: mysql

**Comment by JeromeMaquoi** [comment] 2021-04-14 07:05
Are there any news? Are the check constraints still not implemented?
