### ISSUE TITLE
Join on JSONB array results in "relation ... does not exist"

### ISSUE THREAD

**Issue by peacechen** [typeorm/typeorm#8508] opened 2022-01-06 03:57 UTC
## Issue Description

I'm working with a Postgres JSONB column that contains an array of IDs.  In order to join those IDs to the table that contains the items, I use `jsonb_array_elements_text` in a Join to create a temporary table from the array, then join on the actual table.

```
    queryBuilder
      .innerJoin("jsonb_array_elements_text(tableA.fields->'scIds')", "scid", "true")
      .innerJoin(
        tableB,
        "tableB",
        "scid::uuid = tableB.id"
      )
```

I can run the generated SQL in a SQL client and it works. TypeORM complains:
> relation "jsonb_array_elements_text(tableA.fields->'scIds')" does not exist

### Expected Behavior

Execute the generated SQL.

### Actual Behavior

```
relation "jsonb_array_elements_text(tableA.fields->'scIds')" does not exist
```
See above

### Steps to Reproduce

Code snippet referencing PG `tableA` with a JSONB column `fields` and key `scIds` that holds an array of IDs.  `tableB` can be any table with an ID. 
```
    queryBuilder
      .innerJoin("jsonb_array_elements_text(tableA.fields->'scIds')", "scid", "true")
      .innerJoin(
        tableB,
        "tableB",
        "scid::uuid = tableB.id"
      )
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    OSX 10.15      |
| Node.js version     | 15.5.0  | 
| Typescript version  | 4.0.5  | 
| TypeORM version     | 0.2.37 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment] 2022-04-16 20:56
Duplicate of  #8516

**Closed by Ginden** 2022-04-16 20:56 UTC
Labels: bug, requires triage
