### ISSUE TITLE
Slow query when filtering and ordering

### ISSUE THREAD

**Issue by Waldo000000** [typeorm/typeorm#1419] opened 2018-01-08 01:01 UTC
The query builder generates slow queries in some circumstances. I have reproduced the issue with a [minimal example here](https://github.com/Waldo000000/typescript-example/tree/bug-repro), explained below.

In this scenario, the DB models `Post`s that are related to a `Blog`, and each `Blog` has an `author`. The app queries the DB to return the 5 most recent posts by an author, ordered by `post.createdAt`. Imagine in this scenario that there are many posts and the `post.createdAt` field is indexed to ensure the query is performant.

Here is how I implemented that query:
```
const posts = await connection.getRepository(Post)
    .createQueryBuilder('post')
    .innerJoin('post.blog', 'blog')
    .where('blog.author = :author', { author: 'Sharon Mwangi' })
    .orderBy('post.createdAt', 'DESC')
    .take(5)
    .getMany()
```

Unfortunately, with the above usage, TypeORM generates the following two queries, leading to slow performance as the number of `Post`s scales:

1. 
```
SELECT
  DISTINCT "distinctAlias"."post_id" AS "ids_post_id",
  "distinctAlias"."post_createdAt"
FROM (
  SELECT
    "post"."id" AS "post_id",
    "post"."title" AS "post_title",
    "post"."text" AS "post_text",
    "post"."createdAt" AS "post_createdAt",
    "post"."blog_id" AS "post_blog_id"
  FROM
    "post" "post"
  INNER JOIN "blog" "blog" ON "blog"."id" = "post"."blog_id"
  WHERE
    "blog"."author" = $1) "distinctAlias"
ORDER BY
  "distinctAlias"."post_createdAt" DESC, -- Note: ordering by a field from the subquery
  "post_id" ASC
LIMIT 5 -- PARAMETERS: ["Sharon Mwangi"]
```
2.
```
SELECT
  "post"."id" AS "post_id",
  "post"."title" AS "post_title",
  "post"."text" AS "post_text",
  "post"."createdAt" AS "post_createdAt",
  "post"."blog_id" AS "post_blog_id"
FROM
  "post" "post"
  INNER JOIN "blog" "blog" ON "blog"."id" = "post"."blog_id"
  WHERE ("blog"."author" = $1)
  AND "post"."id" IN (4, 3, 2, 1)
ORDER BY
  "post"."createdAt" DESC -- PARAMETERS: ["Sharon Mwangi"]
```

The **expected query** is simply as follows:
```
SELECT
  "post"."id" AS "post_id",
  "post"."title" AS "post_title",
  "post"."text" AS "post_text",
  "post"."createdAt" AS "post_createdAt",
  "post"."blog_id" AS "post_blog_id"
FROM
  "post" "post"
  INNER JOIN "blog" ON "blog"."id" = "post"."blog_id"
  WHERE
    "blog"."author" = 'Sharon Mwangi'
  ORDER BY
    "post"."createdAt" DESC
  LIMIT 5 -- PARAMETERS: ["Sharon Mwangi"]
```

I was able to achieve a compromise with [this workaround](https://github.com/Waldo000000/typescript-example/compare/bug-repro...Waldo000000:bug-workaround), but it would be ideal if the simplest usage of the query builder provided the expected result.

**Comment by pleerock** [comment] 2018-01-08 12:57
QueryBuilder works as expected. It must execute 2 queries to preform **proper limited results**. Standard SQL's LIMIT will not work as you expect when you have data joined. LIMIT only limits rows database return. To ensure just select post's blogs as well and add multiple posts with multiple blogs and try same query - it will not return you 5 posts.

But in your case you don't have anything joined selected so its not really needed in two queries. I suggest you to use `limit` method instead of `take` - it is "dummy" version of pagination which simply uses default SQL's LIMIT without any additional queries applied.

**Comment by Waldo000000** [comment] 2018-01-09 01:58
Thanks @pleerock.:

1. Unfortunately we do need to use `take` rather than `limit` because in our app it is used in conjunction with `skip` immediately prior for pagination (sorry, perhaps I should have included this `skip` statement in [the repro](https://github.com/Waldo000000/typescript-example/tree/bug-repro)). 
2. I couldn't reproduce the behavior you describe where "it will not return you 5 posts", even after adding most posts and blogs.
3. Do you think [this workaround](https://github.com/Waldo000000/typescript-example/compare/bug-repro...Waldo000000:bug-workaround) is reasonable for the use case?

Thanks,
Roy

**Comment by pleerock** [comment] 2018-01-09 04:27
> 1. Unfortunately we do need to use take rather than limit because in our app it is used in conjunction with skip

You can use `limit` and `offset` methods instead of `take` and `skip`

> 2. I couldn't reproduce the behavior you describe where "it will not return you 5 posts", even after adding most posts and blogs.

you probably did something wrong. Did you actually **selected** all blogs of the posts?

> 3. Do you think this workaround is reasonable for the use case?

No, since you can simply use limit/offset methods

**Comment by guscastro** [comment] 2018-01-10 01:39
Hi @pleerock ,

As @Waldo000000 , I am also unable to reproduce the behaviour you describe. I will paste my attempt below (tried on Postgres). Could you please point out where I went wrong? I am quite keen to understand this.

Thanks,
Gus

```
CREATE TABLE blog (
	id uuid NOT NULL PRIMARY KEY,
	author varchar NOT NULL
);

CREATE TABLE post (
	id uuid NOT NULL PRIMARY KEY,
	created_at date NOT NULL,
	blog_id uuid NOT NULL
);

INSERT INTO blog VALUES ('e072b82e-214c-4c29-a681-9de93e78144a', 'author-a');
INSERT INTO blog VALUES ('7b1de423-1713-4a84-94a9-b52fae65bafe', 'author-b');

INSERT INTO post VALUES ('71e14c2d-07cf-44ed-9af8-941af3595d27', '2018-01-01', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('0df24b90-ad36-4fe9-b690-c3cb588b61f3', '2018-01-02', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('f31c4d53-87ee-4bff-a0b6-5d336065744f', '2018-01-03', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('038d65aa-32df-4dc0-854e-8588f361b731', '2018-01-04', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('25d959f8-7f98-4f0b-9f6d-de8d5db54147', '2018-01-05', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('794b904d-a3ca-4c7f-a624-8784f1101565', '2018-01-06', 'e072b82e-214c-4c29-a681-9de93e78144a');
INSERT INTO post VALUES ('00fa9b2f-446d-4dd9-8afd-7670cdeb0099', '2018-01-07', 'e072b82e-214c-4c29-a681-9de93e78144a');


INSERT INTO post VALUES ('4b7f32cf-06d9-4524-926e-b2c60f3b793b', '2018-01-01', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('09a9d4ba-074e-4670-9aa2-14f060d1d469', '2018-01-02', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('b0ccc517-6d4c-403c-b7a9-a1a4be96c2cc', '2018-01-03', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('19f0ddc7-6a84-4d81-8494-56a91970b4cd', '2018-01-04', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('b44cb047-3df9-4b68-b1e8-26bd64de2b18', '2018-01-05', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('37129913-70cb-45fa-a878-959aaad72cd1', '2018-01-06', '7b1de423-1713-4a84-94a9-b52fae65bafe');
INSERT INTO post VALUES ('24992b0b-72cd-499d-8f6e-46471d14342b', '2018-01-07', '7b1de423-1713-4a84-94a9-b52fae65bafe');


SELECT
  "post"."id" AS "post_id",
  "post"."created_at" AS "post_createdAt",
  "post"."blog_id" AS "post_blog_id",
  "blog"."id" AS "blog_blog_id",
  "blog"."author" AS "blog_author"
FROM
  "post" "post"
  INNER JOIN "blog" ON "blog"."id" = "post"."blog_id"
  WHERE
    "blog"."author" = 'author-a'
  ORDER BY
    "post"."created_at" DESC
  LIMIT 5;



SELECT
  DISTINCT "distinctAlias"."post_id" AS "ids_post_id",
  "distinctAlias"."post_createdAt",
  "distinctAlias"."post_blog_id",
  "distinctAlias"."blog_blog_id",
  "distinctAlias"."blog_author"
FROM (
  SELECT
    "post"."id" AS "post_id",
    "post"."created_at" AS "post_createdAt",
    "post"."blog_id" AS "post_blog_id",
    "blog"."id" AS "blog_blog_id",
    "blog"."author" AS "blog_author"
  FROM
    "post" "post"
  INNER JOIN "blog" "blog" ON "blog"."id" = "post"."blog_id"
  WHERE
    "blog"."author" = 'author-a') "distinctAlias"
ORDER BY
  "distinctAlias"."post_createdAt" DESC,
  "post_id" ASC
LIMIT 5;
```

**Comment by pleerock** [comment] 2018-01-10 04:22
@guscastro its easier to reproduce it with many-to-many table. Create a many-to-many relation between post and blog and add multiple blogs to the multiple post and join them with selection and must see

**Comment by pleerock** [comment] 2018-02-20 11:09
Closing as no further discussion from author.

**Closed by pleerock** 2018-02-20 11:09 UTC
Labels: comp: query builder, question
