### ISSUE TITLE
findOneOrFail on undefined

### ISSUE THREAD

**Issue by chungchi300** [typeorm/typeorm#4448] opened 2019-07-17 08:23 UTC
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```javascript
await photoRepository.findOneOrFail(undefined);

//it returns photo element !
```

**Comment by LuisAngelMoralesRomo** [comment] 2019-07-17 17:39
There is already a discussion about this on issue #2500

**Comment by vlapo** [comment] 2019-07-24 06:59
Close as duplicate of #2500

**Closed by vlapo** 2019-07-24 06:59 UTC
