### ISSUE TITLE
Can't connect to MongoDB > this.databaseConnection.collection is not a function

### ISSUE THREAD

**Issue by sagic** [typeorm/typeorm#1606] opened 2018-02-18 10:51 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Seems the connection is fine (isConnected = true).
When running 
```const items = await connection.mongoManager.find(Desk);```
i'm getting an error thrown: 
**this.databaseConnection.collection is not a function**
I can't find any open issue and i'm guessing it must be something I'm missing in here...
thanks for any tip

### package.json
```
[...]
"mongodb": "^3.0.2",
"reflect-metadata": "^0.1.12",
"typeorm": "^0.1.12",
```

### index.ts
```
[...]
createConnection({
      type: 'mongodb',
      host: 'localhost',
      port: 27017,
      database: 'anon-dev',
      entities: [
        __dirname + '/../**/*.entity{.ts,.js}',
      ],
    })
      .then(async (connection) => {
        console.log(connection.isConnected); // true
        const items = await connection.mongoManager.find(Desk);
        console.log('Items:', items); // not getting here...
      })
      .catch((err) => {
        console.log('ERR > ', err.message); // ERR >  this.databaseConnection.collection is not a function
      });
```

### desk.entity.ts
```
@Entity({ name: 'desks' })
export class Desk {
  @ObjectIdColumn()
  id: ObjectID;

  @Column()
  name: string;
}
```

**Comment by sagic** [comment] 2018-02-18 13:40
i think i solved the problem but i'm not exactly sure how.
looks like typeorm is not supporting the latest mongodb release, trying to go deeper and check what is causing this error.

**Comment by pleerock** [comment] 2018-02-19 07:12
correct. duplicate of #1449

**Closed by pleerock** 2018-02-19 07:12 UTC
