### ISSUE TITLE
Unable to set parameters to postgres jsonb query

### ISSUE THREAD

**Issue by karankumarshreds** [typeorm/typeorm#8304] opened 2021-10-26 07:14 UTC
## Issue Description
I am trying to make a postgres jsonb query using the query builder __as well as__ raw sql query, but I am unable to run it. 

Query: 

```ts
return this.usersRepo
      .createQueryBuilder()
      .select('*')
      .where(
        `jsonb_path_exists(experience,'$[*] ? (@.field == "devops" && @.years > :y)')`, // 👈 (tried using : and $)
        { y: 5 }, // 👈 the parameter 
      )
      .limit(5)
      .getRawMany();
```

ALSO, same issue for raw query:

```ts
return this.usersRepo.query(
      `
        SELECT * FROM users
        WHERE
        jsonb_path_exists(experience, '$[*] ? (@.field == "devops" && @.years > :1)') and
        jsonb_path_exists(experience, '$[*] ? (@.field == "backend dev" && @.years > 5)')
        LIMIT 3;
      `,
      [5],
    );
```

### It is showing me the error: 

`bind message supplies 1 parameters, but 
prepared statement "" requires 0`

### Expected Behavior
It should return the valid data from the query by replacing the parameter with the passed value.

### Actual Behavior

_When I run the same queries with HARDCODED values, it runs accurately with no problems._

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 14.15.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.38  | 
| NestJS Typeorm |  8.0.2 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

**Comment by michaelzangl** [comment] 2021-12-08 22:37
This is not a bug in Typeorm. You cannot use parameters inside the string. Parameters are like a separate string, so use string concatination if you need to. Like this:

```js
      .where(
        `jsonb_path_exists(experience,'$[*] ? (@.field == "devops" && @.years > ' || :y || ')')`, // 👈 (tried using : and $)
        { y: 5 }, // 👈 the parameter 
      )
```

Or like this:
```js
      .where(
        `jsonb_path_exists(experience, ;path)`, // 👈 (tried using : and $)
        { path: '$[*] ? (@.field == "devops" && @.years > ' + y + ')' },
      )
```

**Comment by Ginden** [comment] 2022-02-04 10:05
Yeah, that's a case here, closing.

**Closed by Ginden** 2022-02-04 10:05 UTC
Labels: bug, requires triage
