### ISSUE TITLE
column option readonly is not working

### ISSUE THREAD

**Issue by whcarrot** [typeorm/typeorm#2221] opened 2018-05-28 06:34 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I set column's option below, but when updating, below column included.

```ts
	@Column({type: 'varchar', select: false, readonly: true})
	public provider_name: string;
```

So I inserted exception code query-builder/UpdateQueryBuilder.js:359

```ts
                    if(column.isReadonly) {
                        return ;
                    }
```

please fix it.

**Comment by hielkehoeve** [comment] 2018-08-31 09:07
I have created a PR for this issue: https://github.com/typeorm/typeorm/pull/2749

**Comment by vlapo** [comment] 2018-12-22 16:58
Close as duplicate of https://github.com/typeorm/typeorm/issues/2041

**Closed by vlapo** 2018-12-22 16:58 UTC
Labels: bug
