### ISSUE TITLE
QueryBuilder broken on web - Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by Vluf** [typeorm/typeorm#7026] opened 2020-11-06 15:56 UTC
## Issue Description
The QueryBuilder is broken in the new 0.2.29 release due to this change: https://github.com/typeorm/typeorm/pull/4760
Regex lookbehinds are not supported in on a lot of web environments, a fallback should be implemented.
This affects any driver that uses JavascriptCore (Safari, React Native, ...)

### Expected Behavior

I'd expect QueryBuilder to work

### Actual Behavior

QueryBuilder crashes with `Invalid regular expression: invalid group specifier name`

### Steps to Reproduce

I would add an reproducible example, however, I feel the issue is clear enough without?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     React Native, Android     |
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

Relevant:
- https://bugs.webkit.org/show_bug.cgi?id=174931
- https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [x] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2020-11-08 22:15
What version of node does react native provide?

**Comment by imnotjames** [comment] 2020-11-08 22:51
Looking at the react-native issues.. looks like the problem is brought up time and again - but never fixed.

We can work around it, but that sure does make things a bit messier..

**Comment by Vluf** [comment] 2020-11-09 08:56
React Native runs on [JavascriptCore](http://trac.webkit.org/wiki/JavaScriptCore), which still does not support lookbehinds

**Comment by hhunaid** [comment] 2020-11-11 17:06
Is there any older version that works for react native or this has been always the case?

**Comment by Vluf** [comment] 2020-11-11 19:07
@hhunaid See the issue description, this was introduced only in 0.2.29

**Comment by FrankyFrankFrank** [comment] 2020-11-18 20:22
@Vluf is correct, we rolled our project back to `0.2.25` and recovered from the bug.

**Comment by Cendeal** [comment] 2020-11-19 02:17
the root cause is node.js version. I meet the same cause. it is because i forget to change the node version back. this case will occur when I use oneToMany and node version is 8.3.0. i change node.js back to 10.19.0 is ok.

**Comment by Vluf** [comment] 2020-11-19 08:19
@Cendeal Nodejs is a different engine than the one this issue is for, but upgrading Node will also add support for lookbehinds.

**Comment by sandro-salles** [comment] 2020-11-23 00:58
In order to overcome (even if **temporarily**) the **lookbehinds** issue (and the limitations of **JavascriptCore**), i'm using https://github.com/Kudo/react-native-v8

I can confirm it's working on my installation:

react-native@0.63.3
react-native-v8@^0.63.3-patch.0
typeorm@0.2.29
v8-android@~8.84.0

Hope it can help someone else... :)

**Comment by NickDelBen** [comment] 2020-11-28 03:18
@sandro-salles I am having this exact issue and tried to switch to react-native-v8 as suggested, but when the app launches on the emulator it stope responding immediately. Perhaps you could share in more detail how you resolved this

**Comment by douglasndm** [comment] 2020-11-30 03:59
Same problem here on 0.2.29

**Comment by jacobg** [comment] 2020-11-30 17:01
Have same problem when using Cordova on iOS, i.e., uses Safari's web kit WkWebView, same as React Native.

**Comment by bolivir** [comment] 2020-12-01 13:51
Using it on Ionic Capacitor with version 0.2.29 causes this issue for me, reverting back to 0.2.28 solves it. Seems to be something with relationships

**Comment by johnvolkov** [comment] 2020-12-02 08:29
Have same problem on ionic iOS with version 0.2.29.
Command find() without parameters work fine. But findOne or Delete broken with error: "SyntaxError: Invalid regular expression: invalid group specifier name RegExp@[native code]"

**Comment by oleksandr-dziuban** [comment] 2020-12-10 17:08
> Have same problem on ionic iOS with version 0.2.29.
> Command find() without parameters work fine. But findOne or Delete broken with error: "SyntaxError: Invalid regular expression: invalid group specifier name RegExp@[native code]"

Same issue.... Have it on iOS and Android

**Comment by timroes** [comment] 2020-12-11 10:27
This issue was released now since a month and effects most Android/iOS and all Safari usages. It feels this should be critical enough to revert the causing PR and release a 0.2.30 timely?

**Comment by sandro-salles** [comment] 2020-12-16 22:36
Any update on a fixed release guys? thanks so much....

**Comment by anhkieet** [comment] 2020-12-18 14:14
Same issue... I don't see any action on this issue recently?

**Comment by chriswep** [comment] 2020-12-18 14:40
@Vluf i suggest to update the title and labels to reflect that this affects/breaks all web-based platforms and drivers. @imnotjames @pleerock did this issue already came to your attention? i agree with @timroes and others that this issue merits a revert of #4760

**Comment by nebkat** [comment] 2020-12-19 03:36
I think #4760 made more changes than just adding the lookahead/behind, and there have also been some further changes made since then. Someone should look at reimplementing the existing code without using lookbehinds and submit a pull requests that allows either syntax to be used. Hopefully that can then be merged quicker than a revert since it won't affect non-ionic/browser users.

**Comment by Vluf** [comment] 2020-12-19 18:35
@chriswep Updated title & description to reflect this, can't update the labels though.

**Comment by sdserage** [comment] 2020-12-28 10:41
Another duplicate:

https://github.com/typeorm/typeorm/issues/7157

**Comment by sdserage** [comment] 2020-12-28 13:16
Trying to drop to a lower version so I can use this library but I get this error for 0.2.28 and 0.2.25:

`Unable to resolve "./find-options/operator/ILike" from "node_modules/typeorm/browser/index.js"`

Anybody know if there is a work around for this?

**Comment by allandiego** [comment] 2020-12-28 20:42
@sdserage for me version 0.2.27 is working on react native

**Comment by anhkieet** [comment] 2020-12-29 00:16
> @sdserage Im using version 0.2.27 on react native and its working

Which react-native version are you using?

**Comment by douglasndm** [comment] 2020-12-29 01:09
I was able to fix this downgrading to 0.25.5 and removing all URL imports and calls from BrowserUtils inside typeorm module

**Comment by sdserage** [comment] 2021-01-05 11:54
> > @sdserage Im using version 0.2.27 on react native and its working
> 
> Which react-native version are you using?

I'm using 0.63.4

**Comment by Vluf** [comment] 2021-01-12 15:44
FYI the changes have been reverted and a PR has been made: https://github.com/typeorm/typeorm/pull/7269
0.2.31 should fix & close this issue
Thanks pleerock

**Closed** 2021-01-18 15:04 UTC
Labels: bug, driver: react-native

**Comment by LuigiMaestrelli** [comment] 2021-01-20 20:59
Any ideas on when this will be released?
Every single release from 0.2.25 to 0.2.30 has some kind of bug on react-native...

**Comment by f-ricci** [comment] 2021-02-04 15:27
Hi @pleerock , could you give us an estimate when the 0.2.31 version will be released?

**Comment by f-ricci** [comment] 2021-02-05 06:26
For whomever gets here looking for answers, until the release is published, you can build the package locally and use your local build as dependency in your project.


These are the steps I followed:

1. clone the repo on your local machine
2. run `npm install --save-dev`
3. run `npm run compile`
4. run `npm run package`

In your project
1. in your project folder, change the typeorm dependency in `package.json` to use the local build
using yarn is something like this `"typeorm": "file:PATH_TO_CLONED_REPO/build/package",`
2. delete node_modules
3. run `yarn install --dev`
4. restart the simulator / emulator


This worked for me. Comment if you find any trouble.
