### ISSUE TITLE
Entity metadata for xt#estimations was not found. Error in production mode only

### ISSUE THREAD

**Issue by hsharghi** [typeorm/typeorm#6590] opened 2020-08-19 12:54 UTC
**Issue type:**
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
In an electron application, when I'm in development, (using `npm run dev`) everything works fine. But in production (using `npm run build`) I see this error in logs

```
[2020-08-19 16:16:11.382] [error] Error: Entity metadata for xt#estimations was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at /Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:577:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:573:34)
    at /Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:82:74
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:82:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:57:141)
    at Connection.buildMetadatas (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/connection/Connection.js:491:57)
    at Connection.<anonymous> (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/typeorm/connection/Connection.js:128:30)
    at step (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/hadi/Sites/hadid-karan/hadid-karan-chartviewer/build/mac/Chart Viewer.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:112:62)

```

as you can see in simplified codes provided below, `estimations` is name of relation for `Job` entity to `JobMachinertEstimation` model, and I can't see anything wrong with implementation. But I don't know what is `xt#estimations` means?? some times it changes to `xe#estimations`. What's this error? Why it happens in Production only?

```ts

// Job.ts
@Entity('jobs')
export default class Job {
    @PrimaryGeneratedColumn()
    id!: number

    @Column({
        nullable: true
    })
    jobNumber?: number

    @OneToMany(
        'JobMachineryEstimation',
        'job', {
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
        eager: true
    })
    estimations?: JobMachineryEstimation[]



}
```

```ts
//JobMachineryEstimation.ts
@Entity('job_machinery_estimation')
export default class JobMachineryEstimation {
    @PrimaryGeneratedColumn()
    id!: number

    @ManyToOne(
        'Job',
        'job', {
            onDelete: "CASCADE",
            onUpdate: "CASCADE",
        })
    job?: Job

    @Column({
        default: 0,
        type: "bigint"
    })
    cost!: number

}
```

**Comment by imnotjames** [comment] 2020-10-08 20:55
What is "production mode"?

**Comment by imnotjames** [comment] 2020-10-08 20:57
Pretty sure this is the same as #4714

**Comment by imnotjames** [comment] 2020-10-08 21:01
Ah, electron.  Yeah, that uses Terser, similar thing.  Closing as a duplicate of #4714

**Closed by imnotjames** 2020-10-08 21:01 UTC
Labels: bug, driver: mysql
