### ISSUE TITLE
many-to-many-relations with not default join table columns names

### ISSUE THREAD

**Issue by romanszedzielorz** [typeorm/typeorm#1171] opened 2017-11-12 20:20 UTC
Hello,
I have an issue that I can't figure out, how it should be done.

I will explain it on docs example https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md

My JoinTable looks like this:
```
+-------------+--------------+----------------------------+
|                    question_categories                   |
+-------------+--------------+----------------------------+
| question_id  | int(11)      | PRIMARY KEY FOREIGN KEY    |
| category_id  | int(11)      | PRIMARY KEY FOREIGN KEY    |
+-------------+--------------+----------------------------+
```
The difference between default TypeORM schema and my is questionId -> **question_id,** categoryId -> **category_id**

When I'm doing in Question entity:
```
    @ManyToMany(type => Category)
    @JoinTable({
        name: 'question_categories',
        joinColumns: [
            { name: 'question_id' }
        ]
    })
    categories: Category[];
```

part of the query with 'question_id' is correct, but **I can't force TypeORM to use in query 'category_id' instead of 'categoryId'**. This is my question, how to do it?
I was trying different combinations in 'joinColumns' but without success. Can anybody help me?

**Comment by romanszedzielorz** [comment] 2017-11-13 10:52
I have found CustomNamingStrategy example https://github.com/typeorm/typeorm/tree/master/sample/sample12-custom-naming-strategy that I haven't seen before. I will check it later, if this will solve my issues.

**Comment by pleerock** [comment] 2017-11-16 14:00
naming strategies are subject to change in next versions. Lets open this issue we'll investigate this issue when make will come to naming strategies reimplementation.

**Comment by recurrence** [comment] 2017-11-21 16:34
@romanszedzielorz   Check this out https://gist.github.com/recurrence/b6a4cb04a8ddf42eda4e4be520921bd2

I actually really like the current naming strategy implementation but understand that you may want to improve it.

**Comment by romanszedzielorz** [comment] 2017-11-25 21:09
@recurrence 
I'm not sure, if I want or need to improve/change it. CustomNamingStrategy with snakeCase from sample12 this was everything what I needed, because whole my database shema is snake case. Maybe I will have some issues in the future (I hope I won't :) ), so I will be back here.

**Comment by DavidBM** [comment] 2017-11-29 16:37
Hi, and having some extra attribute like this?

```typescript
    @JoinTable({
        name: 'question_categories',
        columnName: 'category_id',
        joinColumns: [
            { name: 'question_id' }
        ]
    })
```

Would it be possible to implement?

**Comment by pleerock** [comment] 2017-12-01 09:11
@DavidBM can you please provide a more detailed description of the issue you have and what you are trying to resolve with following code? You can customize everything with `joinColumns` option of join table and `inverseJoinColumns`.

@romanszedzielorz to fix your original issue you need to do:

```ts
@ManyToMany(type => Category)
    @JoinTable({
        name: 'question_categories',
        joinColumns: [
            { name: 'question_id' }
        ],
        inverseJoinColumns: [
            { name: 'category_id' }
        ]
    })
    categories: Category[];
```

**Comment by DavidBM** [comment] 2017-12-03 18:23
I didn't know about about inverseJoinColumns. In any case, I would like to know how to make a relation in this case. I have 3 tables. A, AB, B. 
A and B have a relation of N-N. AB is the table that implements that relation. 

For this to work there is 4 important columns (I add weird names for better clarification):
A.a_own_id
B.b_own_id
AB.a_id
AB.b_id

the problem that I have is that I have a legacy database that uses totally non normalized names for this columns. 

I would like to know how to indicate this 4 names to Typeorm.

If read correctly, I can try to do this, but I still miss two column for set the 4 column names.

In the A model definition (using the previous names):
```typescript
    @ManyToMany(type => B)
    @JoinTable({
        name: 'AB',
        joinColumns: [
            { name: 'a_id' }
        ],
        inverseJoinColumns: [
            { name: 'b_id' }
        ]
    })
    Bs: B[];
```

I would like to be able to define in the JOIN to use the A.a_own_id and B.b_own_id.

**Comment by pleerock** [comment] 2017-12-04 11:57
> For this to work there is 4 important columns (I add weird names for better clarification):
A.a_own_id
B.b_own_id
AB.a_id
AB.b_id

where do you have those 4 columns? In same table?

**Comment by DavidBM** [comment] 2017-12-04 20:40
A, B and AB are different tables. 

I mean, I'm doing a N to N relationship between two tables. And I'm implementing this relation with a middle table that has references to the ids of the other two tables. In this case, I'm relation A and B with a N-N relationship and the AB table is the one that has this relation to both

**Comment by pleerock** [comment] 2017-12-05 05:46
You described many-to-many table right now, and many-to-many tables are possible using typeorm as we know. I do not understand what is your issue exactly is? I asked you about columns in last message because I didn't understand requirements. Try to describe your table structure in diagram and I'll tell you how to create entities for them or be more specific in your requirement description.

**Comment by DavidBM** [comment] 2017-12-13 16:03
Hi!

Sorry for the delay in answering. I though that I was defined that, thanks for the patience. Let me create a full example.

I have this 3 tables. 

1. Table: Customers
1.2. Column: CustomerId
2. Table: accounts-locations (accounts refers to customers, was a very old design decision and we need to deal with this)
2.1. Column: account-id
2.2. Column: location-id
3. Table: addresses (addresses refers to locations, the same, we need to deal with it)
3.1 address_Id

The join in SQL would be (a typical one we use)
```sql
SELECT * FROM Customers c
JOIN `accounts-locations` al on al.`account-id` = c.CustomerId
JOIN addresses a on a.address_id = al.`location-id`
WHERE c.CustomerId = <CUSTOMER_ID>;
```

How can I define the models of `Customers` and `addresses` for having this JOIN done automatically?

**Comment by captain328** [comment] 2020-05-30 14:04
I have 6 tables with following columns in MySQL.<br>
table name: users, devices, groups (these 3 tables have the same columns)<br>
```
id: number
name: string
```
table name: map_device_group
```
device_id: number;
group_id: number;
```

table name: map_device_user
```
device_id: number;
user_id: number;
```

table name: map_group_user
```
group_id: number;
user_id: number;
```
The tables `map_device_group`, `map_device_user`, `map_group_user` have relations with `devices`, `users`, `groups` and the foreign keys are already defined.<br>
The data is filled automatically by other services.<br>
How can I define the entities for these tables without modifying the database structure? @pleerock 
I tried so many combinations with many-to-many relations but not succeeded.<br>
I have attached the sample database as a dump file.<br>
[xvisiondb.zip](https://github.com/typeorm/typeorm/files/4705728/xvisiondb.zip)

**Comment by imnotjames** [comment] 2020-10-10 10:02
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 10:02 UTC
Labels: comp: naming strategy

**Comment by nandalalainfotech** [comment] 2023-06-08 09:58
> Hi, and having some extra attribute like this?
> 
> ```ts
>     @ManyToMany(type => Category)
>     @JoinTable({
>         name: 'question_categories',
>         columnName: 'category_id',
>         joinColumns: [
>             { name: 'question_id' }
>         ]
>     })
> ```
> 
> Would be it possible to implement?
> 
> Or, for being totally flexible (like sequelize) we should be able to define the 4 involved columns
> 
> ```ts
>     @ManyToMany(type => Category)
>     @JoinTable({
>         name: 'question_categories',
>         ownColumnName: 'id', //(of the question table, the example is id, but it can accept any crazy name)
>         joinColumnNameOut: 'category_id',
>         otherColumnName: 'id', //(of the category table, the example is id, but it can accept any crazy name)
>         joinColumns: [
>             { name: 'question_id' }
>         ]
>     })
> ```

if possible please share us the query

**Comment by Bibek-21** [comment] 2024-05-30 09:26
@ManyToMany(type=>Category)
  @JoinTable({
    name: 'question_categories',
    joinColumn: {
      name: 'category_id',
      referencedColumnName: 'id'
    },
    inverseJoinColumn: {
      name: 'question_id',
      referencedColumnName: 'id'
    }
  })

This worked fine for me
