### ISSUE TITLE
Surround where clauses with parentheses

### ISSUE THREAD

**Issue by diogodomanski** [typeorm/typeorm#6170] opened 2020-05-31 23:50 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

It would be nice if the expression passed to `where()` and `andWhere()` methods of `QueryBuilder` was surrounded by parentheses.

For example, the following code

```ts
qb("User", "user")
  .where("user.deleteDate IS NULL")  // expression (A)
  .andWhere("user.name = 'foo' OR user.birthDate IS NULL"); // expression (B or C) 
```
currently generates the following SQL sentence:

```sql
SELECT `user`.`id`, `user`.`name`, `user`.`birthDate`, `user`.`deleteDate`
FROM `User` `user`
WHERE `user`.`deleteDate` IS NULL
AND `user`.`name` = 'foo'
OR `user`.`birthDate` IS NULL
```

As can be seen, the resulting `WHERE` clause is `A and B or C`. But it would make more sense if it was `(A) and (B or C)` - because `A` was passed to `where()` and `B or C` was passed to `andWhere()`.

I know that I can achieve this result by manually including the parentheses to every where condition. But, in my opinion, adding the parentheses automagically in SQL sentence generation would be better.

**Comment by imnotjames** [comment] 2020-10-17 03:26
This looks more like a bug than a feature - it doesn't correctly handle input.

**Comment by Pablo1107** [comment] 2021-05-05 15:36
For anyone encountering this issue, you can use `Brackets` like this:
```
        qb.where(
          new Brackets(qb => {
            qb.where(...)
            qb.orWhere(...)
          }),
        )
        qb.andWhere()
```

This will add parenthesis to the `where orWhere` inside the brackets, resulting in a SQL like:
```
WHERE (<something> OR <something>) AND <something>
```

**Comment by michaelzangl** [comment] 2021-05-17 18:03
Duplicate of https://github.com/typeorm/typeorm/issues/1568

That bug has been closed as 'works as intended'

**Closed** 2021-06-23 05:41 UTC
Labels: bug, comp: query builder, driver: mariadb, driver: mssql, driver: mysql, driver: oracle, driver: postgres, driver: sqlite

**Comment by Laksh-Koundinya** [comment] 2023-03-21 08:23
@Pablo1107 I am trying to build a query with typeorm but i am not able to write it as required if you could please help me with this then it would be really great 
Here is the typeorm query that am getting
`SELECT "l"."lead_id" AS "l_lead_id", "l"."contact_id" AS "l_contact_id", "l"."campaign_id" AS "l_campaign_id", "l"."lead_stage_id" AS "l_lead_stage_id", "l"."tag_id" AS "l_tag_id", "l"."name" AS "l_name", "l"."phone" AS "l_phone", count("l"."lead_id") OVER() AS total_count FROM "campaign_lead" "l" WHERE ( "l"."org_id" = :org_id AND "l"."deleted_at" IS NULL AND "l"."lead_status" < :leadStatus AND ("l"."lead_stage_id" = ANY (:stageIdList) AND "l"."tag_id" = ANY (:tagIdList)) AND ("l"."lead_stage_id" = ANY (:stageIdList) AND "l"."tag_id" = ANY (:tagIdList)) ) AND ( "l"."deleted_at" IS NULL ) ORDER BY "l"."date_disposed" ASC NULLS FIRST, "l"."insertion_serial_id" ASC LIMIT 10`
And here is the query that i am want to implement in type orm
`SELECT "l"."lead_id" AS "l_lead_id", "l"."contact_id" AS "l_contact_id", "l"."campaign_id" AS "l_campaign_id", "l"."lead_stage_id" AS "l_lead_stage_id", "l"."tag_id" AS "l_tag_id", "l"."name" AS "l_name", "l"."phone" AS "l_phone", count("l"."lead_id") OVER() AS total_count FROM "campaign_lead" "l" WHERE ( "l"."org_id" = :org_id AND "l"."deleted_at" IS NULL AND "l"."lead_status" < :leadStatus AND( ("l"."lead_stage_id" = ANY (:stageIdList) AND "l"."tag_id" = ANY (:tagIdList)) OR ("l"."lead_stage_id" = ANY (:stageIdList) AND "l"."tag_id" = ANY (:tagIdList))) ) AND ( "l"."deleted_at" IS NULL ) ORDER BY "l"."date_disposed" ASC NULLS FIRST, "l"."insertion_serial_id" ASC LIMIT 10`
And  here is the logic which i have implemented for lead stage tags id in code` if (search.lead_stages_and_tags && search.lead_stages_and_tags.length > 0) {
        for (let index = 0; index < search.lead_stages_and_tags.length; index++) {
          if (search.lead_stages_and_tags.length > 1) {
            query = query.andWhere(
              new Brackets((q) => {
                if (search.lead_stages_and_tags[index].ids.length > 0) {
                  q.where('l.lead_stage_id = ANY (:stageIdList)', {
                    stageIdList: search.lead_stages_and_tags[index].ids
                  });
                }
                if (search.lead_stages_and_tags[index].tags.length > 0) {
                  q.andWhere('l.tag_id = ANY (:tagIdList)', {
                    tagIdList: search.lead_stages_and_tags[index].tags
                  })

                }
              })
            )
          }
        }
      }`
