### ISSUE TITLE
Remove missing child objects in a relation

### ISSUE THREAD

**Issue by timothyvanderaerden** [typeorm/typeorm#1351] opened 2017-12-15 08:51 UTC
Hello

I have a question where I cannot find the solution for in the documentation.

My Understanding is that when you use the `.save()` function, the foreign key of all all missing child objects will be set to null. Is there a 'nice' way to remove those objects from the database instead of setting the foreign key to null, using the save methode?

So for example if I have the following books in my database:

| id | name |
| -- | ------ |
| 1  | Book x |
| 2  | Book y |

And save the following object:
```
Author: {
   name: "...",
   books: [
       {
           name: "Book z",
       },
       {
            id: 2
            name: "Book yy",
       }
    ]
}
```
```
const authorRepository = getConnection('database').getRepository(Author);
await authorRepository.save(author);
```
The result should be:

| id | name |
| -- | ------ |
| 2  | Book yy |
| 3  | Book z |

I'm using version: 0.2.0-alpha.12.

Thanks

**Comment by pleerock** [comment] 2017-12-15 09:52
No there is no way to "nicely" remove such related object, I was thinking about cascade remove for such use case, but not sure about its implementation yet. Lets left this issue open for now.

**Comment by wux5** [comment] 2017-12-20 09:44
I have exactly same problem. Wondering why we chose to implement it with the current approach (update the foreign key with null), isn't it make more sense to delete the removed records from db? Maybe make it an option to either delete or null the fk?

My workaround is to delete all records that's not in the books array (based on the example above, delete from books where author_id = 123 and id not in (2);), and then call author.save(), wrapping them in one transaction. (still concerned about the overhead of .save() which tries to NULL the fk though there is not any).

**Comment by mazyvan** [comment] 2019-04-19 06:15
Having the same issue. Any fix. I think it's necessary to fix the internal behavior. 
I have an entity that has a relation with cascades enabled. 
I want to remove the relation entities with just: `primaryEntity.relationsEntities = []` 
It's more clean than the workarounds out there

**Comment by nolazybits** [comment] 2019-05-23 22:38
Hello, it would be nice to add this in the doc that at the moment this is not supported.
Took me a good hour to come to this thread.
Thanks again for this nice library :+1:

**Comment by Kononnable** [comment] 2019-06-02 19:55
@nolazybits 
PRs from the community to the docs are always welcomed.

**Comment by Pimnr47** [comment] 2019-12-16 16:36
Note that this issue also arises when updating an existing entity with children using the repo's save():

Please do tell me if I get this wrong:

The save method seems to delete the children first and then persist the new children (it's similar to setting this.children = [] (even if they are the same, but that's on me, I don't look bother to look up their id on forehand). But in this case deletion means setting the foreign key to null.

I was wondering why my database was growing so fast in size... I have been pulling my hair out until I found the issues on github.

**Comment by tncbbthositg** [comment] 2019-12-17 18:07
@Pimnr47, I think I ran across the same thing.  I've got a not-null constraint on my foreign key (like @steve2507) so fortunately, I caught this in development.  I'm glad you commented on this yesterday so I'd know it's still an active issue. :)

**Comment by sadams** [comment] 2020-01-04 22:15
From a dupe of this issue:

> cascade removal is not supported due to complexity and too many problems with it.

@pleerock would you mind elaborating on some of the reasons this is hard to solve? I’d be tempted to have a go but imagine I’m being naive.

**Comment by Isahara86** [comment] 2020-01-08 19:10
@pleerock any updates about this issue?

**Comment by egervari** [comment] 2020-10-28 23:41
I'm also very excited about this feature. I noticed the PR that addresses this is still not reviewed.

**Comment by Kolobamanacas** [comment] 2021-06-20 11:49
Here I come, to save the day.

If this is not that obvious for you as it was for me (mislooked related merged pull request), here it is directly: the issue is solved. In a child entity (which parentId column nullifies by default), you add additional option { orphanedRowAction: 'delete' } (instead of 'nullify' which is default) and that's it.

Hope this helps.

**Closed** 2021-06-20 15:05 UTC
Labels: comp: persistence

**Comment by ernes128** [comment] 2021-06-28 08:32
> Here I come, to save the day.
> 
> If this is not that obvious for you as it was for me (mislooked related merged pull request), here it is directly: the issue is solved. In a child entity (which parentId column nullifies by default), you add additional option { orphanedRowAction: 'delete' } (instead of 'nullify' which is default) and that's it.
> 
> Hope this helps. I guess the issue could be closed.

This saved my day, thank you so much!!
