### ISSUE TITLE
'typeorm' does not provide an export named 'Column'

### ISSUE THREAD

**Issue by TheMutabor** [typeorm/typeorm#6941] opened 2020-10-20 13:47 UTC
**Issue type:**

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If i initialize my MySQL Connection over typeorm with my Accounts entityi get this error:

```ts
import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
                     ^^^^^^
SyntaxError: The requested module 'typeorm' does not provide an export named 'Column'
```
my Accounts entity
```ts
import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
@Entity({ name: 'accounts' })
export class Accounts extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: 'varchar' })
    username: string;

    @Column({ type: 'varchar' })
    password: string;

    @Column({ type: 'varchar' })
    hardwareID: string;

    @Column({ type: 'int' })
    maxCharacter: number;
} 
```

**Comment by imnotjames** [comment] 2020-10-20 14:47
Can you create a repository that exhibits this? I can't replicate

**Comment by TheMutabor** [comment] 2020-10-20 16:37
> Can you create a repository that exhibits this? I can't replicate

i don´t come that far. I got this error when i`m trying to creat a connection with this function:
```ts
import orm from 'typeorm';
import { Accounts } from './entity/accounts.js';
const SQLConfig = {
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'SectorNext',
    password: '+C4LY5R]y06a=[Bi',
    database: 'SectorNext',
    synchronize: true,
    logging: false,
    entities: [Accounts],
};

var instance = null;

export default class Connection {
    constructor() {

        if (!instance) {
            orm.createConnection(SQLConfig)
                .then((con) => {
                    this.connection = con;
                    instance = this;
                })
                .catch((err) => {
                    throw err;
                });
        }

        return instance;
    }
}
```

And if i call this:
```ts
import SQL from './database/mysql.js';
let db = new SQL();
```

i get the error
```ts
import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
                     ^^^^^^
SyntaxError: The requested module 'typeorm' does not provide an export named 'Column'
```

**Comment by imnotjames** [comment] 2020-10-20 17:14
Ok - I still am unable to replicate.  Can you please create a GitHub repository that includes code which I can `npm install` and then compile which exhibits this issue?

**Comment by TheMutabor** [comment] 2020-10-20 17:22
I can try, but this script i made is a game resource for a Alt:V Server and the js script get executed by the Server

**Comment by imnotjames** [comment] 2020-10-20 17:33
If you can create a minimal repo that reproduces the issue it'd be best but whatever you can get would help with finding the root cause.

**Comment by TheMutabor** [comment] 2020-10-20 17:36
i can provide you the full repo. with alle Server Files it`s allready on Github but private, let me try to give you rights to it

**Comment by TheMutabor** [comment] 2020-10-20 17:46
> If you can create a minimal repo that reproduces the issue it'd be best but whatever you can get would help with finding the root cause.

I inivted you to a Git Repo there with the hole Projekt.
in the "src" folder you will find alle uncompiled .ts files and also all resources
in the "resources" files are the compiled .js files this is what get executed by the altv-server.exe
the relevant files are the config file for typeORM under: "resources\SectorV\server\config\database.js" and the mysql class witch initialize the typeorm here: "resources\SectorV\server\database\mysql.js" here you will also find in a sub folder the entity. The mysql.js get called from the "resources\SectorV\server\startup.js" this file get executed when the altv-server.exe starts

**Comment by TheMutabor** [comment] 2020-10-20 17:51
Sorry, i`m quite new in Node JS/TypeScript things so the Project Structure may be a bit wyred 🙉 I wasn't prepared for visitors

**Comment by imnotjames** [comment] 2020-10-25 21:58
Hey there - sorry for taking a while to get to this:

* I cloned the repo
* I erased `altv-server.exe` & ran `npm run update` to grab the linux version of the server
* I erased `node_modules` & ran `npm install` to refresh dependencies
* I ran `npm run build`

I'm pretty sure this is some wonk that exists between how Typescript handles module resolution & how nodejs does.

You're currently using ESM because `type: "module"` is defined in your `package.json`.

> When importing CommonJS modules, the module.exports object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

- from the [ESM Imports docs](https://nodejs.org/api/esm.html#esm_import_statements)


TypeORM corrently doesn't _exactly_ export ESM - it exports commonjs modules.  And if static analysis can get you to named exports... great!  Except.. when it can't.  Like now.

There are two ways you can work around this:

* Switch your project to have `"type": "commonjs"` in your `package.json` & update your `tsconfig.json` to emit `commonjs` modules
* Use the default export provided by TypeORM - `import TypeORM from "typeorm"; @TypeORM.Entity();class Foo {}`

There's ONE way that TypeORM could change to help with this as well - export ESM as well as commonJS!  I'll think about adding this but there's a lot of other things I think might be more important.. :shrug:

**Comment by imnotjames** [comment] 2020-10-25 21:59
In short - this is an environment issue - and as such, I'll be closing it out.  However, for more support on the matter -

* If you forked this from some other repository I suggest you chat with them
* For general TypeORM support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Closed** 2020-10-25 21:59 UTC
