### ISSUE TITLE
Is this possible ? construct a property class from many fields on an entity

### ISSUE THREAD

**Issue by jhuntoo** [typeorm/typeorm#306] opened 2017-02-23 00:09 UTC
Hi i was wonder if something like this  was supported already ?

Given a table
```sql
CREATE TABLE event (
   id integer,
   duration_minutes integer,
   duration_hours integer,
   duration_days integer
);
```
Some kind of mapping like this.
```typescript
export class Duration {
    @Column({name: 'duration_minutes'}) minutes: number;
    @Column({name: 'duration_hours'}) hours: number;
    @Column({name: 'duration_days'}) days: number;
}

@Entity('event')
export class Event {
    @PrimaryColumn('int', {generated: true}) id: number;
    @Column(Duration) duration: Duration;
}
```

I realise it's easy enough to work around, but it would be nice to do it natively somehow.

**Comment by pleerock** [comment] 2017-02-23 03:15
Probably what you want is embedded functionality. Take a look on [this example](https://github.com/typeorm/typeorm/tree/master/sample/sample26-embedded-tables) how to implement that

**Comment by jhuntoo** [comment] 2017-02-23 10:04
Great !

Just 1 small problem though

The following...
```typescript
@EmbeddableEntity()
export class Duration {
    @Column({name: 'duration_minutes'}) durationMinutes: number;
    @Column({name: 'duration_hours'}) durationHours: number;
    @Column({name: 'duration_days'}) durationDays: number;
}

@Entity('event')
export class Race {


    @Embedded(type => Duration) duration: Duration;
}
```

produces this result `error: column race.durationDurationMinutes does not exist`.

which seems to joining the 2 class property names together, instead of just using the `{ name:}` override.

**Comment by pleerock** [comment] 2017-02-23 10:29
Maybe its a bug. I'll take a look on it. Don't use custom names for now ("duration" prefix will be added anyway)

**Comment by pleerock** [comment] 2017-02-23 12:39
How did you get such error? Im trying to reproduce it but have no success.

**Comment by jhuntoo** [comment] 2017-02-24 15:29
I think i've managed to capture it here - https://github.com/jhuntoo/typeorm-issue
run
```bash
nvm use
npm start
```

It should output the sql query.

**Comment by pleerock** [comment] 2017-11-22 09:37
Closing this issue since this bug was already fixed a long time ago.

**Closed by pleerock** 2017-11-22 09:37 UTC
Labels: question
