### ISSUE TITLE
Possible to use functions/operators (eg SUM, AVG, COUNT, MIN, MAX) in createQueryBuilder.select()

### ISSUE THREAD

**Issue by chriszrc** [typeorm/typeorm#934] opened 2017-09-24 05:25 UTC
If I run this:

```
return this.exposureRepository.createQueryBuilder("exposure")
                 .select(['exposure.year4','round(exposure.exp_mean) as "exposure_exp_mean"'])
                 .getMany();
```

it produces a valid query:

```
SELECT "exposure"."year4" AS "exposure_year4", "exposure"."id" AS "exposure_id", "exposure"."id" AS "exposure_id", round("exposure"."exp_mean") as "exposure_exp_mean" FROM "exposure" "exposure" 
```

but the exp_mean column is missing from the json output (if I remove the round() it also works perfectly). There's nothing in the documentation about whether it's valid to use these functions/operators in select statements, but I've seen at least a few github issues where it seems people are using this. 

Is it valid?  Is there some way to get the value to output in the json response?

**Comment by pleerock** [comment] 2017-09-25 05:16
At the moment what you select is not mapped anywhere, everything you select non-entity related can be used only inside query itself. I have in plans to add `selectAndMap` method to query builder which will select things you need and map them into specific entity property.

**Comment by chriszrc** [comment] 2017-09-25 14:09
This would be an amazing feature and I think make typeorm really stand out from the other options out there. It would also really make it much easier to never have to  digress back to raw sql queries too-

**Comment by chriszrc** [comment] 2017-09-25 15:25
Although I did notice that sequelize does support this now with sequelize.fn - http://docs.sequelizejs.com/manual/tutorial/querying.html

**Comment by pleerock** [comment] 2018-03-29 07:28
Closing because its a duplicate of #296

**Closed by pleerock** 2018-03-29 07:28 UTC
Labels: comp: query builder, new feature
