### ISSUE TITLE
How to get foreign key for instance?

### ISSUE THREAD

**Issue by sotnikov-link** [typeorm/typeorm#586] opened 2017-06-27 07:21 UTC
Hello. I have a project https://github.com/sotnikov-link/experiment-nodejs-backend

Why I can't to get foreign key for instance?

VS Code, Chrome (web-api), pgAdmin:
<img width="1440" alt="2017-06-27 10 17 37" src="https://user-images.githubusercontent.com/10273334/27575332-0c9bc676-5b22-11e7-8d12-a63242c6b6ef.png">

**Comment by NoNameProvided** [comment] 2017-06-27 07:33
In code a relation is a promise. You need to await it to access it.

**Comment by pleerock** [comment] 2017-06-27 07:58
You can't do that because your "group" is relation object, its not a simple number (id of the pricetaggroup). If you want to have this object in your pricetag you must join it. You need to join your relation if you want to have it, but that using query builder instead of `find`, e.g. 

```ts
entityRepository.createQueryBuilder("entity")
      .leftJoinAndSelect("entity.group")
      .getMany();
```

Yeah, that means you cannot have generic api as you did. You cannot avoid this limitation because in more complex entities you may have multiple relations and most of time you wont join them all. Also in most of time relations are bi-directional which means recursion in what you are returning in your web api. Thats why you need to manually load it.

If you simply want to have a number (e.g. group id) instead of the whole group id you can do this:

```ts
@Column("int", { nullable: true })
groupId: number;

@ManyToOne(type => PriceTagGroup, group => group.priceTags)
@JoinColumn({ name: "groupId" })
group: PriceTagGroup;
```

**Comment by pleerock** [comment] 2017-06-30 09:41
I'll close it, please let me know if suggested solution won't work for you.

**Comment by sotnikov-link** [comment] 2017-07-06 21:05
If I execute a SQL query in the `psql` then I receive response with `group`:
```
dev-experiment-nodejs-backend=# SELECT * FROM price_tag;                                                                   id |   name   |  price  | group
----+----------+---------+-------
  1 | sample1  |   21.11 |     1
  2 | sample11 |    25.1 |     1
  3 | sample2  |    98.2 |     2
  4 | sample22 | 2121.21 |     2
(4 rows)
```

I don't understand why `typeorm` doesn't return `group` when I use:
```
entityRepository.find()
```

How can I see SQL queries which `typeorm` generates?

***

Sorry for my long answer 🙂 

Now [I use your solution with query builder](https://github.com/sotnikov-link/experiment-nodejs-backend/blob/master/src/controllers.ts#L26-L30). Thanks.

**Comment by pleerock** [comment] 2017-07-14 18:54
I just saw your email. Did you solve your problem or not?

**Comment by sotnikov-link** [comment] 2017-07-15 07:26
I didn't solve this problem. I tried to solve the problem with other people, we didn't understand why it happens as was written early.

**Comment by pleerock** [comment] 2017-07-15 08:01
I don't understand what is your problem at the moment, can you please write once again?

> I don't understand why typeorm doesn't return group when I use:

Is it your current problem?

**Comment by sotnikov-link** [comment] 2017-07-15 10:11
Yes :)

**Comment by pleerock** [comment] 2017-07-15 17:42
1. do you need `group` as an object? If yes you need to join it.

2. do you need `group` as simple id? If yes then you should add column as I described above.

Please answer which of them you need and provide complete code example what you are doing

**Comment by pleerock** [comment] 2017-07-27 12:19
did I answer your question now?

**Comment by adnan-kamili** [comment] 2017-07-27 17:11
Is it possible to have an `id` as well as `object`, I ran into some issues with that. Suppose `A` has one to many relationship with have many `B` & `C`. 

If `id` of `B` is known and I want `C`, I am forced to do a join - `B-A` just to get `id` of `A` so that I can fetch `C`, which is costly, had `B` contained id of `A` a join was not needed. Or if join is not done at-least `id` of parent  - `productId` could be populated, because foreign key is accessible in select anyways.

**Comment by pleerock** [comment] 2017-07-27 19:56
@adnan-kamili did you try what I wrote [here](https://github.com/typeorm/typeorm/issues/586#issuecomment-311282863) ?

**Comment by adnan-kamili** [comment] 2017-07-28 02:15
Yes, it worked! I didn't set the foreign key id to null as it should not be null in my case.

```javascript
   @Column("int")
    productVersionId: number;

    @ManyToOne(type => ProductVersion, productVersion => productVersion.customFields, {
        cascadeInsert: true,
        cascadeUpdate: true,
        onDelete: "CASCADE"
    })
    @JoinColumn({ name: "productVersionId" })
    productVersion: ProductVersion;
```

Additionally, now to link the entity with it's parent I no more need to assign the entity, just setting the id works, so instead of 

`customField.productVersion = productVersion;
`
I can now simply link the id

`productKey.productVersionId = productVersion.id;`

**Closed** 2017-10-17 13:20 UTC
Labels: question

**Comment by tdnghia98** [comment] 2020-05-28 10:36
@pleerock Could you please explain how this work under the hood? When I tried to insert data using SQL script, I left the referenced column (*associatedSpaceIdentifier*) null and only insert the id to the join column (*spaceId*). The problem is if I query for the referenced object (*Space object*), I only get **null** value as the return.
How should I insert the data to the table?

```typescript
@ObjectType()
@Entity()
export class Sensor extends BaseEntity {
    @Field((_type) => Space, { nullable: true })
    @ManyToOne((_type) => Space, (Space) => Space.sensors, {
        nullable: true,
    })
    @JoinColumn({ name: 'associatedSpaceIdentifier' })
    associatedSpace: Space;

    @Field()
    @Column({ nullable: true })
    spaceId: string;
}
```

![image](https://user-images.githubusercontent.com/26921719/83130706-04fc0d80-a0df-11ea-96a3-3af93ffdac06.png)

Thanks for your help

**Comment by miadabdi** [comment] 2021-09-29 12:48
@pleerock 
Hello there, your solution worked fine. thanks.
but I have an issue with ugly names.
```ts
@Column({ nullable: true, type: 'varchar2' })
  LKP_REQUESTER_REQ: string;

  @ManyToOne(() => User, (user) => user.username, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  })
  @JoinColumn({
    name: 'LKP_REQUESTER_REQ',
    referencedColumnName: 'username', // weird we can't use database column name: NAM_USERNAME_USR
  })
  requester: User;
```
I have above code in an entity and it works, the issue is `LKP_REQUESTER_REQ` is the name of the field in oracle database, and the username (pk of the related table, varchar2) is accessable using `entity.LKP_REQUESTER_REQ` but it would be better to access it with something like `entity.requesterUsername`. Is it possible?

Now, I get a response like:
```json
{
    "id": 13,
    "createdDate": "2021-09-29",
    "type": 1,
    "LKP_REQUESTER_REQ": "user2",
    "isActive": 1
}
```
which is not desirable at all.

**Comment by rafasegat** [comment] 2022-10-14 09:56
Still not working for me.

It's returning the field, however, but I'm trying to save or create it's saving as null on the database :/

**Comment by off-the-az** [comment] 2023-07-21 09:41
> У мене є наведений вище код в сутності, і він працює, проблема полягає в том

I have same error and I IDK how to fix that. I have an Idea how to do that, however it can`t helps me to solve problem( If you have a solution, pls tell me🥺
