### ISSUE TITLE
Reposity.findOne(...) "no such column", bad query (+ sandbox example)

### ISSUE THREAD

**Issue by MarcusCemes** [typeorm/typeorm#4614] opened 2019-08-20 14:14 UTC
## Issue type:

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

## Database system/driver:

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

## TypeORM version:

[x] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

## Problem summary

`Repository.findOne`(...) generates a failing query when providing an `id` for the entity, and a restriction on a relation.

## Steps to reproduce or a small repository showing the problem:

I have created a minimal live working example on [CodeSandbox.io](https://codesandbox.io/s/typeorm-where-bug-du65k?fontsize=14)

[![Edit TypeOrm Reposity.find() "no such column" bug (+ sandbox example)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/typeorm-where-bug-du65k?fontsize=14)

There are two entities, `Film` and `Key`, with a One-To-Many relation.

The following works:
```ts
getRepository(Film).findOne(1, {
  relations: ["keys"]
});

```

The following does not work and yields a Column Not Found error (differs based on the chosen database):

```ts
getRepository(Film).findOne(1, {
  relations: ["keys"],
  where: { keys: { value: "ilovetypeorm" } }
});
```

Example error (using sqlite):

```json
{
  "message": "SQLITE_ERROR: no such column: Film.filmId",
  "errno": 1,
  "code": "SQLITE_ERROR",
  "name": "QueryFailedError",
  "query": "SELECT DISTINCT \"distinctAlias\".\"Film_id\" as \"ids_Film_id\" FROM (SELECT \"Film\".\"id\" AS \"Film_id\", \"Film\".\"name\" AS \"Film_name\", \"Film__keys\".\"id\" AS \"Film__keys_id\", \"Film__keys\".\"value\" AS \"Film__keys_value\" FROM \"film\" \"Film\" LEFT JOIN \"film_keys\" \"Film_Film__keys\" ON \"Film_Film__keys\".\"filmId\"=\"Film\".\"id\" LEFT JOIN \"key\" \"Film__keys\" ON \"Film__keys\".\"id\"=\"Film_Film__keys\".\"keyId\" WHERE \"Film\".\"filmId\" = ? AND \"Film\".\"id\" IN (?)) \"distinctAlias\" ORDER BY \"Film_id\" ASC LIMIT 1",
  "parameters": [
    null,
    1
  ]
}
```

## Anaylsis

I see 2 problems:

- The first parameter is `null`, it should be `"ilovetypeorm"`
- The WHERE clause is using the wrong table, it should be

The generated query is:
```sql
... WHERE "Film"."filmId" = ? AND "Film"."id" IN (?)) ...
```

while it should actually be:

```sql
... WHERE "Key"."filmId" = ? AND "Film"."id" IN (?)) "distinctAlias" ORDER BY "Film_id" ...
```

I'm relatively new to TypeOrm, am I doing something majorly wrong? I can think of some workarounds, but this behaviour does not seem normal.

Is my use-case too complex for the Repository API and requires the `QueryBuilder`?

**Comment by MarcusCemes** [comment] 2019-08-20 16:03
Just to follow up, using the `QueryBuilder` works flawlessly

```ts
getRepository(Film)
    .createQueryBuilder("film")
    .select("film")
    .leftJoinAndSelect("film.keys", "key")
    .where("film.id = :id", { id: film })
    .andWhere("key.value = :key", { key })
    .getOne();
```

**Comment by alvis** [comment] 2019-11-02 17:53
I believe it's the same issue as #4666

However, it's still an issue.

**Comment by kevlud** [comment] 2019-11-04 16:42
+1 

I have this issue too when finding entity in a many-to-many relation. I found in many cases function .findOne() very convenient, but this issue forces me to use a query builder, which is very complex and ruins my well-arranged data mapper that now looks bulky.

**Comment by imnotjames** [comment] 2020-10-10 09:43
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 09:43 UTC
Labels: bug, driver: postgres, driver: sqlite
