### ISSUE TITLE
ionic cordova build android --prod not working

### ISSUE THREAD

**Issue by santu-git** [typeorm/typeorm#1263] opened 2017-11-29 12:28 UTC
My Observation is if there is any relation between 2 entities then this problem happening.

```
TypeError: Cannot read property 'kind' of undefined
    at nodeCanBeDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7805:35)
    at nodeIsDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7825:16)
    at Object.nodeOrChildIsDecorated (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:7829:16)
    at isDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51668:23)
    at isInstanceDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51659:20)
    at Object.filter (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:1645:31)
    at getDecoratedClassElements (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51641:23)
    at generateClassElementDecorationExpressions (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51815:27)
    at addClassElementDecorationStatements (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51804:44)
    at visitClassDeclaration (/Users/santu/MyWorkspace/Ionic/sm3-fresh/node_modules/typescript/lib/typescript.js:51131:13)
```
activity.entity.js
```typescript
import { Result } from './result.entity';
import { Entity, Column, PrimaryColumn, ManyToOne, OneToMany, JoinColumn } from 'typeorm';

@Entity('activity')
export class Activity {
  
  /* Columns */
  @PrimaryColumn()
  id: string;

  @Column()
  name: string;

  @Column({nullable: true})
  note: string;
  ...............
  
  /* :has_many relations */
  @OneToMany(type=> Result, result=>result.activity,{
    cascadeInsert: true,
    cascadeUpdate: true,
  })
  results: Result[] = [];
}
```
result.entity.ts
```typescript
import { Activity } from './activity.entity';
//import { Catalog } from './catalog.entity';
import { Entity, Column, PrimaryColumn, ManyToOne, JoinColumn } from 'typeorm';

@Entity('result')
export class Result {

  @PrimaryColumn()
  id: string;

  @Column()
  name: string;

  @Column({ nullable: true })
  value: string;

  
  
  /* Relations */
  /* :belongs_to relations */
  @ManyToOne(type=>Activity, activity=> activity.results)
  @JoinColumn({name: "activity_id"})
  activity: Activity;
}
```

Framework Versions

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.10 
    Node              : v7.8.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 8.0 Build version 8A218a 

Environment Variables:

    ANDROID_HOME : /usr/local/Cellar/android-sdk/24.4.1_1/

Misc:

    backend : legacy
   typeorm: 0.1.2

**Comment by daniel-lang** [comment] 2017-11-29 15:07
Thank you for opening a new issue, instead of commenting on previous one...

I tried to recreate your issue and created a [repository](https://github.com/daniel-lang/ionic-santu-git) with you provided code, but I don't get your error. Could you please see what the difference between your project and this example is.

**Comment by santu-git** [comment] 2017-11-29 15:18
@daniel-lang Thank you for your response. Let me check and revert.

**Comment by santu-git** [comment] 2017-11-29 16:21
@daniel-lang 
What I found only difference is angular and some ionic component version mismatch. For which I have created a repo. [repo](https://github.com/santu-git/ionic-santu-git/tree/angular-5). Here I am using angular-5. I could reproduce the error.

**Comment by santu-git** [comment] 2017-11-30 06:03
I could not build even. This error is happing during build time
in the project root if I run `ionic cordova build android --prod` I am getting this error.

`Santus-MacBook-Pro:ionic-santu-git-fork santu$ ionic cordova build android --prod
Running app-scripts build: --prod --platform android --target cordova
[11:31:04]  build prod started ... 
[11:31:04]  clean started ... 
[11:31:04]  clean finished in 89 ms 
[11:31:04]  copy started ... 
[11:31:06]  deeplinks started ... 
[11:31:06]  deeplinks finished in 44 ms 
**[11:31:06]  ngc started ...** 
TypeError: Cannot read property 'kind' of undefined
    at nodeCanBeDecorated (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:7805:35)
    at nodeIsDecorated (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:7825:16)
    at Object.nodeOrChildIsDecorated (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:7829:16)
    at isDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51668:23)
    at isInstanceDecoratedClassElement (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51659:20)
    at Object.filter (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:1645:31)
    at getDecoratedClassElements (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51641:23)
    at generateClassElementDecorationExpressions (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51815:27)
    at addClassElementDecorationStatements (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51804:44)
    at visitClassDeclaration (/Users/santu/MyWorkspace/Ionic/ionic-santu-git-fork/node_modules/typescript/lib/typescript.js:51131:13)
[11:31:37]  copy finished in 32.32 s 
Santus-MacBook-Pro:ionic-santu-git-fork santu$ 
`

**Comment by pleerock** [comment] 2017-11-30 06:26
what typescript version are you using? maybe its about typescript since error goes from deep inside of typescript

**Comment by daniel-lang** [comment] 2017-11-30 08:22
@santu-git sorry, I missed the fact, that you are trying to build production. Now I can reproduce your error. This seems to be a problem with typescript (Microsoft/TypeScript#17384 and Microsoft/TypeScript#20314)

**Comment by santu-git** [comment] 2017-12-01 05:29
@pleerock 
"typescript": "2.4.2"

**Comment by pleerock** [comment] 2017-12-01 06:44
try different typescript compiler versions - newer and older versions.

**Comment by daniel-lang** [comment] 2017-12-01 23:01
I'm going to close this as this error will also occurs if typeorm is removed from the project. So the error has nothing to do with TypeORM but rather with TypeScript and Ionic

**Closed by daniel-lang** 2017-12-01 23:01 UTC
Labels: comp: ionic, needs more info

**Comment by nextlevelshit** [comment] 2018-02-08 21:56
Any hints to solve that even it's not related to TypeORM?

**Comment by joshstrange** [comment] 2019-06-06 15:09
@daniel-lang @nextlevelshit Did you ever figure this out? I am running into this issue (TypeError: Cannot read property 'kind' of undefined) and I thought I tracked it down to an entity in typeorm but @daniel-lang seems to indicate that wasn't the real issue?
