### ISSUE TITLE
RepositoryNotFoundError + serverless offline + webpack

### ISSUE THREAD

**Issue by johnEthicalTechnology** [typeorm/typeorm#6332] opened 2020-06-30 08:06 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm using `apollo-server-lambda` with Apollo client. When I make a request to the server it returns with the `RepositoryNotFound` error.

I've read through the other closed issues with this as an problem but none seemed to solve it. Also, there's behaviour that's different to those other issues. 

For instance when I run `serverless offline` for the first time and I make a request the logs show that the connection is being made to the DB, it's querying the DB with the particular entity, and it's found the records. Then it looks like it starts another request which returns the error.

I'm not sure what is going on especially when it was working about a month ago and I've not updated anything.

This is my DB config. The `dev` config is being used.

```
import Recipe from './entities/Recipe'
import RecipeAttribution from './entities/RecipeAttribution'
import UserProfile from './entities/UserProfile'
import Challenge from './entities/Challenge'

import { ConnectionOptions } from 'typeorm'

const entities = [Recipe, RecipeAttribution, UserProfile, Challenge]

export const prod: ConnectionOptions = {
  name: 'default',
  type: 'postgres',
  port: 5432,
  host: process.env.DB_HOST,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  synchronize: false,
  logging: 'all',
  logger: 'advanced-console',
  dropSchema: false,
  entities
}

export const test: ConnectionOptions = {
  name: 'test',
  type: 'postgres',
  host: 'localhost',
  port: 5433,
  username: 'test-no-meat-may',
  password: '',
  database: 'test-no-meat-may',
  synchronize: true,
  logging: false,
  dropSchema: true,
  entities
}

export const dev: ConnectionOptions = {
  name: 'default',
  type: 'postgres',
  port: 5432,
  host: process.env.DB_HOST,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  synchronize: false,
  logging: 'all',
  dropSchema: false,
  entities
}
```

This is how I create a DB connection:
```
import {
  Connection,
  ConnectionManager,
  ConnectionOptions,
  createConnection,
  getConnectionManager
} from 'typeorm'
// Dependency injection
import { injectable, inject } from 'inversify'
import { TYPES } from '../inversifyTypes'

import { prod, test, dev } from './dbConnectionConfig'

import { IDatabase, ILogger } from '../types'
import { LambdaLog } from 'lambda-log'
/**
 * Database manager class
 */
@injectable()
export class Database implements IDatabase {
  private connectionManager: ConnectionManager
  private connection: Connection
  private readonly _logger: LambdaLog

  constructor(@inject(TYPES.Logger) Logger: ILogger) {
    this._logger = Logger.getLogger()
    this.connectionManager = getConnectionManager()
  }

  public async getConnection(): Promise<Connection> {
    this._logger.info('Selecting current environment')
    const currentEnv =
      process.env.ENV == 'prod'
        ? 'prod'
        : process.env.ENV == 'test'
        ? 'test'
        : 'dev'
    const CONNECTION_NAME =
      currentEnv == 'prod' || currentEnv == 'dev' ? 'default' : 'test'

    if (this.connectionManager.has(CONNECTION_NAME)) {
      this._logger.info(`Using existing DB connection for ${currentEnv}`)
      this.connection = await this.connectionManager.get(CONNECTION_NAME)

      if (!this.connection.isConnected)
        this.connection = await this.connection.connect()
    } else {
      this._logger.info(`Creating DB connection for ${currentEnv}`)

      let connectionOptions: ConnectionOptions = dev
      if (currentEnv == 'prod') connectionOptions = prod
      if (currentEnv == 'test') connectionOptions = test

      this.connection = await createConnection(connectionOptions)
    }

    return this.connection
  }
}
```

Thanks in advanced!
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by strelov1** [comment] 2020-07-10 12:44
I have the same trouble

**Comment by metalcamp** [comment] 2020-09-04 10:58
Same here. Any updates?

**Comment by imnotjames** [comment] 2020-10-02 16:02
@johnEthicalTechnology @strelov1 how about y'all?  Is it solved by downgrading?

Is this still an issue with 0.2.28?

If neither of those help can you create a way for me to replicate this issue?

**Comment by imnotjames** [comment] 2020-10-04 07:21
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2020-10-21 06:42
Pretty sure this is a duplicate of #5676 and without information that helps replicate the problem I'm closing this out

**Closed** 2020-10-21 06:42 UTC
Labels: bug, driver: postgres, needs more info
