### ISSUE TITLE
UpdateResult is always empty 

### ISSUE THREAD

**Issue by lianall** [typeorm/typeorm#4426] opened 2019-07-12 01:58 UTC
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
dev environment :  win10(or win7) , node 10

when i call the update function of any Repository ,
the return value UpdateResult is always two empty array,
whether or not the update query is succeed

{
  "generatedMaps": [],
  "raw": []
}

**Comment by ChandruCR** [comment] 2019-09-04 07:32
Any resolution for this.
I have tried with repository update and querybuilder update.
both of them update the table but response is always 
{
"generatedMaps": [],
"raw": []
}

**Comment by ksvirsky** [comment] 2019-10-09 13:28
The same issue for TypeORM+postgres.

**Comment by balintsteinbach** [comment] 2020-07-16 08:27
Same issue here.

- Sqlite db
- typeorm 0.2.22

`advance(dashbordToUpdate: Dashboard, regressStatuses: string[]): Promise<UpdateResult> {
    return this.createQueryBuilder()
      .update(Dashboard)
      .set(dashbordToUpdate)
      .where(
        'id in (:id) AND termination_status_registered = FALSE AND status NOT IN (:regressStatuses)',
        { id: dashbordToUpdate.id, regressStatuses: regressStatuses.toString() }
      )
      .execute();
  }`

The result is always:
 UpdateResult { generatedMaps: [], raw: [] }

**Comment by Jonatan966** [comment] 2020-08-20 04:32
Same issue for TypeORM+sqlite db

**Comment by imnotjames** [comment] 2020-10-17 08:36
Duplicate of #2415

**Closed by imnotjames** 2020-10-17 08:36 UTC
Labels: comp: query builder, driver: sqlite, question
