### ISSUE TITLE
MariaDb updated affected undefined

### ISSUE THREAD

**Issue by cosinus84** [typeorm/typeorm#5849] opened 2020-04-10 10:23 UTC
On MariaDb affected is undefined but there is a value of affectedRows on raw object:
`UpdateResult {
  generatedMaps: [],
  raw: OkPacket {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '(Rows matched: 1  Changed: 1  Warnings: 0',
    protocol41: true,
    changedRows: 1
  }
}`

**Comment by imnotjames** [comment] 2020-10-17 08:35
Duplicate of #2415

**Closed by imnotjames** 2020-10-17 08:35 UTC
