### ISSUE TITLE
Incorrect conversion for Date column

### ISSUE THREAD

**Issue by dschoerk** [typeorm/typeorm#5543] opened 2020-02-18 13:24 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Consider the following snippet where we have an entity with a "Date" type column. Inserting a new item by setting `x.date = new Date()` works for the first insert. However, if we call `save` another time typeorm does not recognize that it should rather update the existing object. 

I read that the Date type is represented by a string and as such the find() method also returns the date as a string. I think for saving, the (new Date()) must be properly converted into the respective string representation, like seen below ('2020-02-18'), because in the case of an update this is not working. Even weirder is that it is possible to set x.date to ANY string and it still saves properly. 

Can you recommend a best practice to get around this issue? Does typeorm somewhere expose the used date to string conversion as a workaround?

Code:
```
let x = new MarketHistory()
  x.mainKey = 1
  x.subKey = 2
  x.date = new Date()
  x.sumCount = 15
  x.totalSumCount = 1
  x.minPrice = 1

  console.log(await r.find())
  await r.save(x)
  console.log(await r.find())
  await r.save(x)
  console.log(await r.find())
```

Output:
```
[]
[
  MarketHistory {
    mainKey: 1,
    subKey: 2,
    date: '2020-02-18',
    sumCount: 15,
    totalSumCount: 1,
    minPrice: 1
  }
]
(node:53920) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: market_history.mainKey, market_history.subKey, market_history.date
    at new QueryFailedError (E:\dev\bdo\web\src\error\QueryFailedError.ts:9:9)
    at Statement.handler (E:\dev\bdo\web\src\driver\sqlite\SqliteQueryRunner.ts:53:26)
```

Entity:
```
@Entity()
export class MarketHistory {

    @PrimaryColumn({type: "int"})
    mainKey // itemid

    @PrimaryColumn({type: "int", default: 0})
    subKey // itemid

    @PrimaryColumn({type: "date"})
    //@CreateDateColumn
    date // itemid

    @Column({type: "int"})
    sumCount

    @Column({type: "int"})
    totalSumCount

    @Column({type: "int"})
    minPrice
}
```

**Comment by iamolegga** [comment] 2020-09-03 09:59
Same, looks like it requires to add transformer, see here: https://github.com/typeorm/typeorm/issues/3666#issuecomment-548873660

**Comment by imnotjames** [comment] 2021-07-09 08:00
I think this is a duplicate of #2286

**Comment by imnotjames** [comment] 2021-07-09 08:01
At the very least this is a duplicate for sure of #3426

**Comment by imnotjames** [comment] 2021-07-09 08:01
Duplicate of #3426

**Closed by imnotjames** 2021-07-09 08:01 UTC
Labels: bug, driver: sqlite
