### ISSUE TITLE
[serverless] Inject connection's property after connected

### ISSUE THREAD

**Issue by pueue** [typeorm/typeorm#2598] opened 2018-07-28 12:36 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I tried to use typeorm for aws lambda functions.
A first query to database worked. But after first query(after connection established), all queries threw an error like AlreadyConnectError.
So, I avoided this error.

```ts
const connectionOptions: ConnectionOptions = {
  entities: ["src/database/entities/**.*.ts"],
  migrations: ["src/database/migrations/**/*.ts"],
  
  ...DatabaseConfig
}

export const connectDatabase = async (callback: Function = () => {}) => {
  try {
    const connectionManager = getConnectionManager()
    let connection: Connection;

    if (connectionManager.has('default')) {
      console.log('use a connection already connected')
      connection = connectionManager.get()
    } else {
      connection = connectionManager.create(connectionOptions)
      await connection.connect()
    }

    await callback();
    return connection;
  } catch (e) {
    console.log(e);
    throw e;
  }
};
```

However, another error `RepositoryNotFoundError` showed.
I found some issues addressing it. https://github.com/typeorm/typeorm/issues/2572 https://github.com/typeorm/typeorm/issues/1540 

Using `connection.getRepository<User>('User')` instead of `connection.getRepository(User)` seemed to work. But that disabled some features like associations in transaction and hooks.

After going through a code in this repository, I found why it does not work.
And here is a solution.

```ts
export const connectDatabase = async (callback: Function = () => {}) => {
  try {
    const connectionManager = getConnectionManager()
    let connection: Connection;

    if (connectionManager.has('default')) {
      console.log('use a connection already connected')
      connection = injectConnectionOptions(connectionManager.get(), connectionOptions)
    } else {
      connection = connectionManager.create(connectionOptions)
      await connection.connect()
    }

    await callback();
    return connection;
  } catch (e) {
    console.log(e);
    throw e;
  }
};

export const injectConnectionOptions = (connection: Connection, connectionOptions: ConnectionOptions) => {
  /**
   * from Connection constructor()
   */

  // @ts-ignore
  connection.options = connectionOptions
  // @ts-ignore
  connection.manager = connection.createEntityManager();
  // @ts-ignore
  connection.namingStrategy = connection.options.namingStrategy || new DefaultNamingStrategy();
  // @ts-ignore
  connection.relationLoader = new RelationLoader(connection);
  // @ts-ignore
  connection.relationIdLoader = new RelationIdLoader(connection);

  /**
   * from Connection connect()
   */
  // @ts-ignore
  connection.buildMetadatas();

  return connection;
}
```

**Comment by pleerock** [comment] 2018-07-28 12:40
I don't understand is lambda caching something? Looks like you are calling "createConnection" twice?

**Comment by MIrinkov** [comment] 2018-08-14 23:32
Hi, @vichyssoise . I just wanted to say thank you. Thank you so much.
I have been battling this issue for some time, but gave up, and was running an API on an Express server.
Just tried this, and everything worked like a charm.

**Comment by Kononnable** [comment] 2018-09-29 11:08
Closing as no answer from the reporter.

**Closed by Kononnable** 2018-09-29 11:08 UTC

**Comment by dstrekelj** [comment] 2018-11-25 12:01
I've had the same problem and the solution @pueue contributed at the end of his [comment](https://github.com/typeorm/typeorm/issues/2598#issue-345445322) seems to have solved it.

I've been toying around with setting up a simple REST API on AWS Lambda with Serverless. I'm using TypeORM to manage a Postgres database, and Serverless plugins **serverless-offline** and **serverless-plugin-typescript** to develop the API.

My understanding is that AWS Lambda functions are run in containerised environments. Under certain circumstances (e.g. several sequential invocations) this enables handlers to make use of data exposed to the environment, and this is achieved by running code outside of handler functions. With that in mind, I set up the TypeORM managed database connection in a similar manner as above in order to reuse it between invocations. Otherwise, I would have to establish a connection every time the handler is invoked, resulting in a connection overhead on every API call, which in turn increases response time.

The first request worked without a problem - the connection was established and I could work with data stored in the Postgres database. The requests that followed correctly determined that an existing connection is available and proceeded to reuse it. However, when the handlers attempted to work with entities (either directly or via repositories) over the reused connection, an exception claiming no entity metadata was found was thrown.

Debugging the connection objects I noticed that both the new and reused connections did have the correct options and knew about the entities, as was expected. But, calling `hasMetadata()` on the reused connection and passing in an entity returned `false`.

I don't believe it's a bug with TypeORM, it's more of a circumstantial thing in my case - an edge case. I'm fairly certain this is happening because of the way my development environment is set up (Serverless, plugins, etc.).

I'll be able to provide you with a reproducible example soon, hopefully. As soon as I boil it down to the essentials.

**Comment by didac-wh** [comment] 2018-12-21 17:59
I fixed it this way:

`let connectionOptions : any = {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "",
        database: "test",
        entities: [
          User
        ],
        synchronize: true,
        logging: false
      }
    
      if (getConnectionManager().has('default')) {
        await getConnectionManager().get().close();
      }

      Globals.connection = await createConnection(connectionOptions);`

**Comment by pleerock** [comment] 2018-12-21 19:21
@didac-wh why not to use same connection instead of closing it in the case if you found it already created ?

**Comment by didac-wh** [comment] 2018-12-24 10:35
@pleerock correct me if I'm wrong please, but as I see in this issue, reusing the same connection gives some problems, first with a RepositoryNotFoundError and then a "no entity metadata was found",

Using a serverless architecture you can't have a living server with an active connection. Every request loads the whole sub-system, therefore, seeing that reusing an old connection under this specific circumstances (serverless AWS lambda, serverless-offline plugin and serverless-plugin-typescript plugin) is giving some trouble I prefer to close&create a connection again and keep it simple. If I notice some lose of performance as my application grows then I may seek for more complex & effective solutions. If you know of a better way (considering OP and @dstrekelj comments) please let us know.

Thank you for your suggestion.

**Comment by pleerock** [comment] 2018-12-25 06:52
@didac-wh sorry Im unexperienced with serverless, it was just my assumption. If you do:

```ts
  if (getConnectionManager().has('default')) {
    await getConnectionManager().get().close();
  }
```

it means there is a connection in *some* memory. I don't know where this memory is in serverless, but if it has default connection in on a second query it means it stores in in some memory. That's why I thought since its stored in memory and there is a connection, its completely same as was used for the first time and it should work.

Just my assumptions, you know better since you can test how it works.

**Comment by PrestonII** [comment] 2020-11-11 18:10
@didac-wh - your comment was a huge help!

One thing I'd ask (two years later) is if this works in production? 

Imagine this, I have 2 users on: 
- User A doing some long running process going on their connection 
- User B, just getting information quickly
- THEN, User C comes on

Does User C, reset the connection for Users A & B? I want to think not, but figured I'd ask
