### ISSUE TITLE
Allow changing type of entity attribute per database configuration

### ISSUE THREAD

**Issue by BrunnerLivio** [typeorm/typeorm#1776] opened 2018-03-17 21:05 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Issue:

My application supports SQLite (for testing) and Postgres (for production). The problem is, I have an entity, which has the attribute `timestamp`, which is supported in Postgresql, but not in SQLite.
Now I can't support both, because when I run my tests, SQLite complains it does not know timestamp. It would be useful, if this could be supported. An option I came up with is, changing the type of `ColumnOptions.type` by allowing to give a function as value.

Example:

```TypeScript
@Entity()
export class Image extends BaseEntity {

  @Column({
    type: () => process.env.NODE_ENV === 'test' ? 'datetime' : 'timestamp'
  })
  uploadedAt: Date;

}
```

**Comment by koliyo** [comment] 2018-03-19 08:48
We got exactly the same problem

**Comment by koliyo** [comment] 2018-03-19 11:55
Actually, for us it is possible to directly evaluate the conditional expression instead of using a callback function.
```
  @Column({
    type: process.env.NODE_ENV === 'test' ? 'datetime' : 'timestamp'
  })
```

**Comment by pleerock** [comment] 2018-03-26 11:20
how we can support a specific database type when its not supported by a database?

**Comment by pleerock** [comment] 2018-03-26 19:15
Some orms does provide an abstraction and they map common types if they are not supported by db into similar types. But they all have limited number of supported types since its not possible to create abstraction for all types.

TypeORM does not restrict you on column types you use - you can use any type your database supports. Having a limited set of types like some ORMs can hurt people who want more flexibility. And mapping each type into something similar from other db is not possible.

So, for now use solution you have. And maybe its easier to setup a non-sqlite db for tests? You can really limit yourself once you'll need some postgres-specific feature.

**Comment by pleerock** [comment] 2018-03-29 10:07
I'll close this issue, feel free to continue discussion.

**Closed by pleerock** 2018-03-29 10:07 UTC

**Comment by eilrix** [comment] 2021-07-31 16:39
A bit too late, but had the same issue..
> And mapping each type into something similar from other db is not possible. 
The issue is not about automatic mapping. We want an ability to return type of columns from functions:
```typescript
@Column({
  type: connectionOptions => connectionOptions.type === 'postgres' ? 'timestamptz' : 'datetime'
})
```
