### ISSUE TITLE
Cannot query for related objects where the relation is NULL. 

### ISSUE THREAD

**Issue by tomasreimers** [typeorm/typeorm#8945] opened 2022-04-29 15:25 UTC
## Issue Description

Cannot query for related objects where the relation is NULL. 

For example, 

prod.manager.find(Book, {
        where: {
          author: IsNull(),
        },
        relations: ["author"],
      })

Will simply query for all books (not adding any where relationship for "authorId IS NULL").

### Expected Behavior

We would add the relationship of "authorId IS NULL".

### Actual Behavior

We do not add the relationship of "authorId IS NULL".

### Steps to Reproduce

1. Create author table
2. Create book table

```typescript
prod.manager.find(Book, {
        where: {
          author: IsNull(),
        },
        relations: ["author"],
      })
```

### My Environment

MacOS, TypeORM 0.35

### Relevant Database Driver(s)

Postgres

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment] 2022-08-25 14:08
duplicate of #8890

**Closed by pleerock** 2022-08-25 14:08 UTC
Labels: bug, requires triage

**Comment by tGeorgiy** [comment] 2022-11-10 00:14
Many-To-Many find where Relation is Null still not working..
