### ISSUE TITLE
Nullable embedded entities 

### ISSUE THREAD

**Issue by thynson** [typeorm/typeorm#5787] opened 2020-03-31 07:19 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I think it would be better to support nullable embedded entity.

```typescript
class Name {
  @Column()
  first: string; // some times we don't want to specify nullable or not here
  @Column()
  last: string;
}

class Person {
  @Column(()=> Name, {nullable: true}) // we may need make the whole name optional here
  name?: Name
}
```

**Comment by imnotjames** [comment] 2021-07-03 21:05
duplicate of #3913

**Closed by imnotjames** 2021-07-03 21:05 UTC
Labels: comp: embeds, new feature

**Comment by holm** [comment] 2022-02-08 09:16
I can't really see how #3913 is a duplicate of this. This is about making columns on embedded columns nullable by setting the embedded column to nullable, the other is about updating all columns for an embed to null, but setting the embed to null.
