### ISSUE TITLE
typeorm 0.2.29 SyntaxError  Invalid regular expression Bug

### ISSUE THREAD

**Issue by mjpcasey** [typeorm/typeorm#7157] opened 2020-12-05 02:41 UTC
更新到0.2.29无论是插入还是保存都报这个错误， 版本用回0.2.19就不会报这个错. 代码是typescript。 是不是没有用new RegExp
 SyntaxError: Invalid regular expression: /(?<=[ =(]|^.{0})RoomModel\.(id|room_id|creator_user_id|game_type|name|create_time|update_time|room_status|room_rule|room_no)(?=[ =),]|.{0}$)/: Invalid group=undefined

@Entity("room")
export class RoomModel {
    @PrimaryGeneratedColumn()
    id: number;
    @Column('bigint')
    @Index("room_id_index")
    room_id : string = "";
    @Column('bigint')
    @Index()
    creator_user_id : string = "";
    @Column("integer")
    @Index()
    game_type: proto.GameType = 0;
    @Column("varchar", {length: 50})
    name : string = ""
    @CreateDateColumn()
    create_time : Date;
    @UpdateDateColumn()
    update_time : Date;
    @Column("integer")
    room_status: proto.RoomStatus = proto.RoomStatus.Idle;
    @Column("integer")
    room_rule: number; 
    @Column("bigint")
    @Index("room_no_index")
    room_no: string = "";
}

**Comment by sdserage** [comment] 2020-12-28 10:42
Duplicate of typeorm/typeorm/issues/7026

**Comment by imnotjames** [comment] 2021-07-02 21:18
closed as duplicate of #7026

**Closed by imnotjames** 2021-07-02 21:18 UTC
Labels: bug, requires triage
