### ISSUE TITLE
Generate uuids in Node.js instead of Database

### ISSUE THREAD

**Issue by tstearn** [typeorm/typeorm#3389] opened 2019-01-08 22:08 UTC
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Suggesting a different method for UUID PrimaryGeneratedColumn, which would be to generate the UUID in TypeScript.

Suggesting this because we recently switched from using PrimaryGeneratedColumn to assigning our keys in a @BeforeInsert method.  We did this because generating UUIDs on Postgres involves installing the "uuid-ossp" module.  This module works fine, but installing it requires superuser permissions in Postgres.  Since we delivering our software to customers, we can't guarantee we'll be granted those permissions for our app, so it was safer to generate these keys in Node.

Now, doing this via a base class that has a @BeforeInsert function is NOT an undue burden.  But I thought others might have these same restrictions, so an alternative UUID generation mechanism might be helpful.  This would also work for databases that don't support UUID generation.

FYI - our method's dependencies are "cypto" and "os" from the Node platform.

**Comment by vlapo** [comment] 2019-01-09 20:52
I think this is duplicate of https://github.com/typeorm/typeorm/issues/1542.

Note: Currently typeorm generate (in code) `uuid` values for databases without support of `uuid`.

**Comment by pleerock** [comment] 2019-01-13 19:58
@tstearn your use case is specific. There is no point for us to implement manual if database supports it. Specific use cases likes yours have to use hooks. Think this one can be closed, but feel free to continue discussion.

**Closed by pleerock** 2019-01-13 19:58 UTC
Labels: can be closed?
