### ISSUE TITLE
datetime not working in sqlite where statement

### ISSUE THREAD

**Issue by ldiego08** [typeorm/typeorm#2694] opened 2018-08-21 23:32 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When passing a `Date` as a parameter to the query builder's `where` function, the query returns empty results. However, when the date is passed as a string it works. I'm wondering if the parameters are not being parsed correctly by the query runner. 

Here's the entity setup:

```ts
@Entity("test_entity")
export class TestEntity {
  @PrimaryGeneratedColumn({ name: "id" })
  public id: number;

  @IsNotEmpty()
  @Length(0, 150)
  @Column({ name: "name" })
  public name: string;

  @IsNotEmpty()
  @CreateDateColumn({ name: "create_time" })
  public createdAt: Date;
}
```

Table configuration:

```ts
{
    name: "test_entity",
    columns: [
        {
            name: "id",
            type: "integer",
            isPrimary: true,
            isGenerated: true,
            generationStrategy: "increment"
        },
        {
            name: "name",
            type: "varchar",
            length: "150",
            isNullable: false
        },
        {
            name: "create_time",
            type: "datetime",
        }
    ]
}
```

And the query code:

```ts
const query = entityManager
    .getRepository(TestEntity)
    .createQueryBuilder("ml");

query.where(
    "ml.createdAt < :createdAtValue OR ml.createdAt = :createdAtValue AND ml.id < :idValue",
    {
        idValue: 4,
        createdAtValue: new Date("2018-07-30 12:00:00") // this works if passed as "2018-07-30 12:00:00"
    }
);

query.orderBy({
    "ml.createdAt": "DESC",
    "ml.id": "ASC"
});


const result = await query.getMany();
```

`result` is empty, but should contain three entities.

Here's a test repository with the code: https://github.com/ldiego08/typeorm-sqlite-test

**Comment by Ciantic** [comment] 2019-04-17 13:28
My observation is that 

Insert is formatted correctly:
```sql
INSERT INTO "my_entity"("date") VALUES (?) -- PARAMETERS: ["2000-01-01 00:00:00.000"]
```

However, with select it uses *wrong format*, see the parameters at the end:

```sql
SELECT "MyEntity"."id" AS "MyEntity_id", "MyEntity"."date" AS "MyEntity_date"
FROM "my_entity" "MyEntity" WHERE "MyEntity"."date" = ? -- PARAMETERS: ["2000-01-01T00:00:00.000Z"]
```

Sqlite assumes the timezone to be UTC, and the string should never contain `Z`. What is important that the typeorm should consistently do a Date to string conversion for sqlite, now it seems like with SELECTs it's using different algorithm than with INSERTs.

Stand alone jest test that fails:
```typescript
import { createConnection, getConnection, Entity, getRepository } from "typeorm";
import { PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class MyEntity {
    @PrimaryGeneratedColumn()
    id?: number;

    @Column({
        type: "datetime"
    })
    date!: Date;
}

beforeEach(() => {
    return createConnection({
        type: "sqlite",
        database: ":memory:",
        dropSchema: true,
        entities: [MyEntity],
        synchronize: true,
        logging: true
    });
});

afterEach(() => {
    let conn = getConnection();
    return conn.close();
});

test("store Date and find it", async () => {
    await getRepository(MyEntity).insert({
        date: new Date("2000-01-01T00:00Z")
    });
    let found = await getRepository(MyEntity).find({
        where: {
            date: new Date("2000-01-01T00:00Z")
        }
    });
    expect(found[0].date).toBe(new Date("2000-01-01T00:00Z"));
});
```

**Comment by daniel-dia** [comment] 2019-04-24 17:50
It happens to me too

**Comment by hansl** [comment] 2019-05-15 19:08
I've had the same problem, and I can confirm it's not `T` and `Z`, somehow. Using the `datetime()` function with a `Raw()` operator does the right thing (change your test):

```typescript
test("store Date and find it", async () => {
    await getRepository(MyEntity).insert({
        date: new Date("2000-01-01T00:00Z")
    });
    let found = await getRepository(MyEntity).find({
        where: {
            date: Raw(alias => `${alias} = datetime("2000-01-01T00:00Z")`)
        }
    });
    expect(found[0].date).toEqual(new Date("2000-01-01T00:00Z"));
});
```

Of course this uses `Raw()` which should not be used, but it's to demonstrate the point. The driver should use the sqlite `datetime()` function to properly format datetimes internally in queries. This is done automatically on INSERTs, so it's not a problem there.

**Comment by mohd-akram** [comment] 2020-08-26 16:22
See also #2286.

**Comment by imnotjames** [comment] 2020-10-11 09:42
Duplicate of #2286

**Closed by imnotjames** 2020-10-11 09:42 UTC
Labels: bug, driver: sqlite
