### ISSUE TITLE
Call custom deserialization function when entity data is loaded from database

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#570] opened 2017-06-22 18:43 UTC
I have some complex entities in my application, which require some tailored deserialization logic in order to populate entity with data correctly.

I now use `@AfterLoad` listener, but the problem with it is that it's called after TypeORM updated the entity with data fetched from the database (and overwrites some properties in my entity which was initialized in it's constructor). What I want is for TypeORM to call my custom function in order to populate entity with data.

There could be several approaches to this problem:

# Serializable/Deserializable Entity Interface

TypeORM would detect if entity implements the special interfaces and will call the serialization methods instead of populating the data manually.

```typescript
class MyEntity implements SerializableEntity, DeserializableEntity {
  @Column()
  ipAddress: IPAddress;

  // Called when entity should be populated with data obtained from database
  deserialize (plainObject: any) {
    this.ipAddress = IPAddress.createFromString(plainObject.ipAddress);
  }

  // Called before persisting the entity to the database in order to obtain data
  serialize (): any {
    return {
      ipAddress: this.ipAddress.toString()
    };
  }

}
```
# Entity Factory

TypeORM could call the custom factory in order to build an entity, the purpose of factory would be to take all data obtained from the database and to return new instance of the entity with populated properties:

```typescript
class MyEntityFactory implements EntityFactory<MyEntity> {
  create (plainObject: any) {
    const myEntity = new MyEntity();
    myEntity.ipAddress = IPAddress.createFromString(plainObject.ipAddress);
    return myEntity;
  }
}
```

I hope it makes sense.

**Comment by pleerock** [comment] 2017-06-23 06:15
isn't entity factory same as serialization in "Serializable/Deserializable Entity" ?

**Comment by pleerock** [comment] 2017-06-23 06:27
this feature request is same as #289 . I think what author suggested is better then this java-style interface based approach. We can do:

```ts
class MyEntity {
  @Column("string")
  @OnRawToEntity((ipAddress: string, entity: MyEntity) => new IpAddress(ipAddress))
  @OnEntityToRaw((ipAddress: IpAddress, entity: MyEntity) => ipAddress.toString())
  ipAddress: IPAddress;
}
```

And we will have full control of column transformation. We can apply same decorators on class:


```ts
@Entity()
@OnRawToEntity((entity: MyEntity) => entity.fromRaw())
@OnEntityToRaw((entity: MyEntity) => entity.toRaw())
class MyEntity {
  @Column("string")
  ipAddress: IPAddress;

  fromRaw() { // can be static as well
      this.ipAddress = new IPAddress(this.ipAddress as string);
      return this;
  }

  toRaw() {  // can be static as well
     return { ... };
  }
}
```

**Comment by slavafomin** [comment] 2017-06-23 16:04
> this feature request is same as #289 

This explains why I had this feeling, that I've already worked on this issue ))

Probably it's a matter of preference, but I think that interfaces are actually more elegant way to handle this, because all serialization logic could be concentrated in one place and you won't be needed to add additional decorators. It's less code to type and to maintain. And the existence of the serialization methods could be easily duck-typed.

Also, I don't really like the idea of adding actual logic to the decorators. I believe the decorators should be as simple as possible and declarative in nature. Otherwise, we will need to test them somehow in our unit tests.

And the interfaces approach introduces conventions, which standardizes things. So the every developer familiar with TypeORM will know, what `serialize/deserialize` methods are for. Otherwise, different projects and even different entities could have methods with different names. This complicated things. I like the idea of standardization.

**Comment by pleerock** [comment] 2017-06-24 05:42
> Probably it's a matter of preference, but I think that interfaces are actually more elegant way to handle this, because all serialization logic could be concentrated in one place and you won't be needed to add additional decorators. It's less code to type and to maintain. And the existence of the serialization methods could be easily duck-typed.

can't agree with any of sentence. 

> Also, I don't really like the idea of adding actual logic to the decorators.

yeah having heavy logic in decorators isnt a good idea, but here I suggest a simple logic - delegation what method of entity it should call

> I believe the decorators should be as simple as possible and declarative in nature

agree decorators should be simple and declarative. And thats what we do. Decorators here provide more declaratively and simplicity then implementing interface 

> And the interfaces approach introduces conventions, which standardizes things. So that every developer familiar with TypeORM will know, what serialize/deserialize methods are for. 

standartization in this particular use case does not matter. Also understand that for new users its always easier to understand and use decorator then implementing interface. 

I won't go this javish way with interfaces, it does not fit good in javascript/typescript world I believe.

**Comment by pleerock** [comment] 2017-06-24 05:45
now this issue also looks like #569 probably alternative we can do:

```ts
@Entity('users')
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column(ColumnTypes.JSONB, { getter: "profile", setter: "profile" })
  private _profile?: any;

  get profile (): any {
    return this._profile;
  }

  set profile (profile: any) {
    this._profile = profile;
  }

}
```

just need to think what to add to `@Entity` decorator, maybe something like 

```ts
@Entity({
   rawToEntity: "someMethodInEntity",
   entityToRaw: "someMethodInEntity"
})
```

**Comment by pleerock** [comment] 2017-06-30 11:35
closing as duplicate of #289

**Closed by pleerock** 2017-06-30 11:35 UTC
