### ISSUE TITLE
Mongodb does not support Relationship (ManyToMany)

### ISSUE THREAD

**Issue by amanganiello90** [typeorm/typeorm#7258] opened 2021-01-08 15:21 UTC
## Issue Description

I have two entities with a ManyToMany relationship in the following way for mongodb. Using **sincronize: true value of typeorm options** runs the error:

```
MongoError: Index keys cannot be empty.
    at MessageStream.messageHandler (C:\Users\amanganiello\Desktop\jhipster-projects\mongo-nhip\server\node_modules\mongodb\lib\cmap\connection.js:268:20)
```

### Expected Behavior

Nothing error.

### Actual Behavior

I Have two entities:

```
@Entity('nhi_user')
export class User extends BaseEntity {

  @ObjectIdColumn({ name: 'id' })
  id?: string;

  @Column({ unique: true })
  login: string;

  @JoinTable()
  @ManyToMany(() => Authority)
  authorities?: any[];
}
```

```
@Entity('nhi_authority')
export class Authority {

   @ObjectIdColumn()
  _id?: string;

  @ApiModelProperty({ example: 'ROLE_USER', description: 'User role' })
  @PrimaryColumn()
  name: string;
}

```

The scope of the **Authory entity** is to have a field name as primary key not autogenerated (so to bypass that I have added an _id field, but it will be good to avoid it).

### Steps to Reproduce

1. Use typeorm with mongodb and syncronize to true

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v10.19.0| 
| Typescript version  | 3.8.3 | 
| TypeORM version     | 0.2.29 | 
| Mongodb npm dependency version     | 3.6.3 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mykone** [comment] 2021-01-20 03:25
I'm having the same issue as well.

**Comment by imnotjames** [comment] 2021-06-25 07:53
duplicate of #655

**Closed by imnotjames** 2021-06-25 07:53 UTC
Labels: bug, driver: mongodb, requires triage
