### ISSUE TITLE
Support for adding SQL comments

### ISSUE THREAD

**Issue by DavisJaunzems** [typeorm/typeorm#6128] opened 2020-05-25 13:36 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I would like to have the option of adding SQL comments to the `QueryBuilder` (`.comment()`) that would then be part of the SQL query, when calling one of the execute methods. One could then add useful comments to queries, like, ID of function calls to be able to trace where SQL query originated from.

Postgesql and MySQL both support adding comment anywhere in the SQL query using multline comments `/* */`, but not sure about other drivers that are used in TypeORM. From what I understand queries are not formated in TypeORM when they are sent to the database, so the multiline comment could be added to the beginning or end of the SQL query.

I'm willing to add this functionality, but would it require adding support for it for all database drivers in TypeORM, or just MySQL and Postgresql would be good enough?

**Comment by imnotjames** [comment] 2020-10-11 10:59
Duplicate of #3643

**Closed by imnotjames** 2020-10-11 10:59 UTC
Labels: driver: mariadb, driver: mysql, driver: postgres, new feature
