### ISSUE TITLE
is there any way to have a model for tables without PK

### ISSUE THREAD

**Issue by saostad** [typeorm/typeorm#5315] opened 2020-01-10 15:12 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a database that some tables don't have PK on it and I have no control on database design, is there any way to create an entity for tables without PK?
I know in typeorm [Each entity must have at least one primary column](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#primary-columns) but it's for save function but in my case, I just want to do SELECT query.
if the answer is NO, please tell me what is the right way to do that.

**Comment by LouBerry** [comment] 2020-01-21 15:30
Supporting this question for Sqlite database.
At least reading/opening the table. I don't mind converting it afterwards in a more standardized manner.

**Comment by imnotjames** [comment] 2021-07-10 16:34
Duplicate of #5317

**Closed by imnotjames** 2021-07-10 16:34 UTC
Labels: driver: mssql, question
