### ISSUE TITLE
Sqlite transaction queue

### ISSUE THREAD

**Issue by Luke265** [typeorm/typeorm#307] opened 2017-02-23 19:25 UTC
Since Sqlite has only one connection, I think that we need some kind of a simple transcation queue to execute transactions one by one, because when executing the following code:

```
entityManager.transaction((transaction) => {
    // long transaction
});
entityManager.transaction((transaction) => {
    // something
});
```

I'm keep getting `TransactionAlreadyStartedError` error.

**Comment by pleerock** [comment] 2017-02-24 08:38
is it possible to do multiple connections in sqlite somehow? Or implement connection pooling manually? What solution are you suggesting?

**Comment by Luke265** [comment] 2017-02-24 10:26
It is possible to do multiple connections, but only one connection can write https://sqlite.org/faq.html#q5 . Here is my approach: https://github.com/Luke265/typeorm/commit/02601609b249bff5a516eefc78b2099808fdfa66

**Comment by pleerock** [comment] 2017-03-01 06:32
What will happen if we comment these lines:

```typescript
       if (this.databaseConnection.isTransactionActive)
            throw new TransactionAlreadyStartedError();
```

It won't throw `TransactionAlreadyStartedError` exception, but what result will be?

**Comment by Luke265** [comment] 2017-03-03 15:54
I get an error `SQLITE_ERROR: cannot start a transaction within a transaction`.

Here is the code for testing:
```
import {createConnection} from "typeorm";
createConnection({
    driver: {
        type: 'sqlite',
        storage: './database.db',
    }
}).then((connection) => {
    console.log('Starting transaction #1');
    connection.entityManager.transaction((t) => {
        console.log('Executing transaction #1');
        return new Promise((resolve) => setTimeout(resolve, 2000));
    }).then(() => console.log('Completed transaction #1'));

    console.log('Starting transaction #2');
    connection.entityManager.transaction((t) => {
        console.log('Executing transaction #2');
        return Promise.resolve();
    }).then(() => console.log('Completed transaction #2'));
});
```

**Comment by pleerock** [comment] 2017-06-30 14:54
I refactored sqlite driver and it simply always creates a single connection now. So no multiple connection support. And probably it won't be there. As I read in sqlite people dont do multiple connections =) So closing this, but if someone have something to say or suggest feel free to do that

**Closed by pleerock** 2017-06-30 14:54 UTC

**Comment by jessehon** [comment] 2018-03-19 01:03
I'm not sure if the issue was resolved but we are still experiencing the same `TransactionAlreadyStartedError` with sqlite on `latest` whenever there are concurrent transactions attempting to run. 

Is the only workaround to avoid the concurrent transactions completely and implement a queue to buffer all queries/transactions?

**Comment by pleerock** [comment] 2018-03-19 08:00
@jessehon  you do something wrong - not awaiting something or something similar. Provide a minimal reproduction code example.

**Comment by jessehon** [comment] 2018-03-20 11:06
There is a lot of concurrent database actions in our codebase that we feel the need to have some library level support for concurrent transaction (e.g. background jobs, async fetching etc). 

I rewrote and tested the first example to verify it indeed throws a `TransactionAlreadyStartedError`

```ts
    console.log(`Starting transaction 1`);
    const transaction1 = getConnection().transaction(async txnEntityManager => {
        console.log(`Started transaction 1`);
        await delay(10000);
      })
      .then(() => console.log(`Completed transaction 1`))
      .catch((err) => console.error(`Failed transaction 1`, err));

    console.log(`Starting transaction 2`);
    const transaction2 = getConnection().transaction(async txnEntityManager => {
        console.log(`Started transaction 2`);
      })
      .then(() => console.log(`Completed transaction 2`))
      .catch((err) => console.error(`Failed transaction 2`, err));
```

**Comment by pleerock** [comment] 2018-03-21 04:12
I think this code is wrong because sqlite has only connection it can have only one transaction at one time. So, you can't start two parallel transactions. To fix your problem you need to await each transaction, e.g. 

```ts
const transaction1 = await getConnection().transaction ...
const transaction2 = await getConnection().transaction ...
```

**Comment by flacidsnake** [comment] 2018-03-26 09:42
@jessehon +1

**Comment by pleerock** [comment] 2018-03-26 09:51
@jessehon I did not get what you mean. We are talking about sqlite and parallel transactions do not work here as you expect.

**Comment by jessehon** [comment] 2018-03-26 13:38
@pleerock I understand this is a limitation of sqlite not supporting parallel reads/writes but I also feel a solution similar to the one @Luke265 proposed may be the best option here.

If every transaction or query is placed in a queue then the transactions can be executed serially avoiding the parallel read/write all together. There could be a performance impact but I feel that is still a better option than having the user avoid parallel transactions completely or having to implement their own queuing layer.

**Comment by pleerock** [comment] 2018-03-26 14:02
queue will not bring any performance benefits if writes aren't parallel. async i/o thats what bring impact, everything else is executed in sequence anyway.

**Comment by jessehon** [comment] 2018-03-26 14:12
Maybe I didn't explain properly. By "performance impact", I meant it will be slower. Also I was trying to explain that instead of just throwing `TransactionAlreadyStartedError`, it may better to implement a queue in typeorm that will automatically wait for each transaction promise to resolve before starting the next one. This is similar to what @Luke265 was trying to do in https://github.com/Luke265/typeorm/commit/02601609b249bff5a516eefc78b2099808fdfa66

**Comment by pleerock** [comment] 2018-03-26 15:02
Yes I completely understand what you meant by "performance impact". My answer is in above - it does not bring any performance impact, async makes sense only for io, your code is not executed in parallel (if you think so) when you have a queue

**Comment by jessehon** [comment] 2018-03-26 18:29
The use case I have is that there are multiple threads that can interact with the database. One example is that I need to implement offline syncing that requires running several tasks in the background separate to the main UI thread (e.g. attempting a re-sync when connectivity is restored). The problem is that both this main and background thread would write to the database, which will sometimes conflict hence why I feel the need for a shared singleton queue. 

Below is an example of what I'm working with.


```ts
// background thread
const transaction1 = await getConnection().transaction(transaction) => {
    // something slow
});
```

```ts
// main thread
const transaction2 = await getConnection().transaction ...
```

I can implement a solution for this in my project but this seems like too common of a use case that I feel it may be better handled within typeorm especially if there are transactions happening frequently or if there a few long running transactions. A solution for this was posted in https://github.com/typeorm/typeorm/issues/1348 that checks every ms for pending executions but that's a bit too much of a "dirty hack".

I am also open to other ideas of how else to solve this or what your thoughts are.

**Comment by pleerock** [comment] 2018-03-26 19:09
what do you call "thread"? If you await something it does not mean it executes in the separate thread, don't use mess parallelism with asynchornity?

**Comment by jessehon** [comment] 2018-03-26 19:33
In this case I really just mean they are part of separate promises

**Comment by keenondrums** [comment] 2018-04-10 12:11
@pleerock according to official docs on transactions they create shared locks on the first read. It means there could be several readers, hence several connections. Would you be willing to accept a PR which brings connection pool for SQLite back?

**Comment by keenondrums** [comment] 2018-04-10 12:19
Anyway we have to handle concurrent transactions appropriately and implement some kind of queue. I moved from my original solution suggested in #1348 to this https://gist.github.com/keenondrums/556f8c61d752eff730841170cd2bc3f1

The idea is that even if we keep a single connection we can still create separate QueryRunners using the same connection. Let's call it virtual query queue. These runners synchronize on the same promise-based mutex to avoid query overlapping.

**Comment by kenberkeley** [comment] 2020-04-25 01:09
@aigoncharov The gist link is dead 😂

**Comment by aigoncharov** [comment] 2020-04-25 06:48
@kenberkeley thnx. I updated the link.

**Comment by Jusonex** [comment] 2020-06-19 11:19
I've been running into the same problem: If another async function that runs database queries is invoked, queries will be mixed up (i.e. non-transactional queries are mixed up with the queries within the transaction).
Since this is a slightly different symptom (but the same reason), I can provide a minimal reproducible example, if necessary.

Apart from that: What's the status of this issue? Is there another open issue that tracks this? If not, what about re-opening the issue?

**Comment by imnotjames** [comment] 2020-10-04 20:13
> Apart from that: What's the status of this issue? Is there another open issue that tracks this? If not, what about re-opening the issue?

#1884
