### ISSUE TITLE
MongoEntityManager find method Cursor undefined

### ISSUE THREAD

**Issue by ReArno** [typeorm/typeorm#8071] opened 2021-08-12 08:24 UTC
## Issue Description
I found an issue with the mongodb typed repository. The MongoEntityManager throws an error, the problem is when the package tries to import the Cursor class from the mongodb package, throws an error, because the mongodb package doesn't contain Cursor class export, I verified. In the current version not presented.
Because of this, the normal `find` doesn't work, instead throws an error.
I have a simple method which throws the error.
```
constructor(
    @InjectRepository(Product)
    private readonly productsRepository: Repository<Product>,
) {}

async getAll() {
    return this.productsRepository.find();
}
```

### Expected Behavior
An array result of the find.

### Actual Behavior

```
[Nest] 37 - 08/12/2021, 7:52:07 AM ERROR [ExceptionsHandler] Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined

at FindCursor.cursor.toArray (/usr/src/app/src/entity-manager/MongoEntityManager.ts:707:37)

at MongoEntityManager.<anonymous> (/usr/src/app/src/entity-manager/MongoEntityManager.ts:97:23)

at step (/usr/src/app/node_modules/tslib/tslib.js:143:27)

at Object.next (/usr/src/app/node_modules/tslib/tslib.js:124:57)

at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:114:62)

at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
### Steps to Reproduce

1. Create a new fresh NestJs project.
2. Add the latest typeorm and mongodb package.
3. Create an entity class.
4. Create a service.
5. Make a normal get request with the related repository (with a find method).

```typescript
// entity
import { Column, Entity, ObjectIdColumn } from 'typeorm';
import { ObjectId } from 'mongodb';

@Entity('products')
export class Product {
  @ObjectIdColumn()
  id: ObjectId;

  @Column()
  name: string;

  constructor(product?: Partial<Product>) {
    Object.assign(this, product);
    this.id = new ObjectId();
  }
}
// service
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { CreateProductDto } from './dto/create-product.dto';
import { Product } from './entities/product.entity';

@Injectable()
export class ProductService {
  constructor(
    @InjectRepository(Product)
    private readonly productsRepository: Repository<Product>,
  ) {}

  async getAll() {
    return this.productsRepository.find();
  }

  async create(createProduct: CreateProductDto) {
    return this.productsRepository.create(new Product(createProduct));
  }
}
// controller
import { Body, Controller, Get, Post } from '@nestjs/common';
import { CreateProductDto } from './dto/create-product.dto';
import { ProductService } from './product.service';

@Controller('products')
export class ProductController {
  constructor(private readonly productService: ProductService) {}

  @Get()
  getAll() {
    return this.productService.getAll();
  }

  @Post()
  create(@Body() createProductDto: CreateProductDto) {
    return this.productService.create(createProductDto);
  }
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows10   |
| Node.js version     | 14.17.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 
| mongodb | 4.1.0 | 

### Additional Context
The application runs in a Docker env. But I think the error is not related.

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | yes            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment] 2021-08-12 19:29
Our peer dependency for mongodb is `^3.6.0` - we don't support `4.x` yet.

**Comment by imnotjames** [comment] 2021-08-12 19:29
Duplicate of #7907

**Closed by imnotjames** 2021-08-12 19:29 UTC
Labels: bug, requires triage
