### ISSUE TITLE
Find options nested where 

### ISSUE THREAD

**Issue by onionhammer** [typeorm/typeorm#3902] opened 2019-03-26 15:55 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

According to the docs [here](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options), 

```
Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined. Example:

userRepository.find({ where: { name: { first: "Timber", last: "Saw" } } });
```

For me the parameters inside of the nested object are simply missing from the query.

My example:

```ts
db.getRepostiory(device)
  .find({
    where: {
      group: { 
        id: groupId,
        account: { id: accountId }
      }
    }
  });
```

Here 'accountid' is left out of the generated query, and only 'groupId' is sent as a parameter.

**Comment by nomadoda** [comment] 2019-03-28 09:50
What does the device schema look like? Is `account` an embedded entity?

**Comment by trixden** [comment] 2019-03-28 10:26
#3890 same problem

**Comment by onionhammer** [comment] 2019-03-28 13:41
@nomadoda device looks like this

```ts

@Entity("devices")
export class Device extends RootEntity {

  @ManyToOne(type => Group, group => group.devices, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: "groupId" })
  group: Group

}

```

**Comment by pie6k** [comment] 2019-04-17 18:30
I have the same issue

My code:
```ts
        const deleteResult = await ListMembership.delete({
          list: { owner: { id: user.id } },
          user: { id: user.id },
        });
```

Resulting query (from console):

```
query: DELETE FROM "list_membership" WHERE "listId" = $1 AND "userId" = $2 -- PARAMETERS: [null,"a12580b9-9e1b-463c-9738-6b5591f97655"]
```

It's quite weird.

**Comment by pie6k** [comment] 2019-04-17 18:35
Even more interesting - it's possible to 'destroy data':

Code: 
```ts
        const deleteResult = await ListMembership.delete({
          list: { id: Not(IsNull()), owner: { id: user.id } },
          user: { id: user.id },
        });
```

Resulted in query:

```
query: DELETE FROM "list_membership" WHERE NOT("listId" IS NULL) AND "userId" = $1 -- PARAMETERS: ["a12580b9-9e1b-463c-9738-6b5591f97655"]
```

Which narrowed criteria and removed data I didnt want to remove here.

**Comment by a7urag** [comment] 2020-04-11 13:42
https://github.com/typeorm/typeorm/issues/3890#issuecomment-612423257

**Comment by imnotjames** [comment] 2020-10-15 21:49
Nested `where` in `find` is currently working.  I had tested it in another issue.  I'll be marking this one as a duplicate of that issue.

**Comment by imnotjames** [comment] 2020-10-15 21:49
Duplicate of #2707

**Closed by imnotjames** 2020-10-15 21:49 UTC
Labels: bug, comp: find options, driver: postgres
