### ISSUE TITLE
Fix(ed?) Mssql Tablename

### ISSUE THREAD

**Issue by Elithsar** [typeorm/typeorm#7860] opened 2021-07-07 09:25 UTC
### Expected Behavior

With Mssql driver, when tableName contains a dotted name with squared brackets, TypeOrm should build a name like this :
e.g.
```
 [foo.bar].dbo.table  should result in  [foo.bar]."dbo"."table"
```

### Actual Behavior

Actual version escapes every dots in the table name.
e.g. 
```
[foo.bar].dbo.table  results in  "[foo"."bar]"."dbo"."table"
```
Similar issue in #3531
### Steps to Reproduce

1. Apply a findAll request on an entity with decorator defined like below

```typescript
@Entity("myEntity", { schema: "[dbo]" , database: "[foo.bar]" })
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     W10/Linux     |
| Node.js version     | v6.14.7 | 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

FYI : I forked the repository and applied a solution on this link https://github.com/Elithsar/typeorm
in this commit : https://github.com/Elithsar/typeorm/commit/1e1e1d399ed53459bf181b08a88175b3e8aca986

This patch cancels escaping for mssql driver when tableName has squared brackets and dots within it.

Tests are ok for personal project use but I don't know if it can be pulled to the main project.

**Comment by imnotjames** [comment] 2021-07-09 07:21
The brackets aren't part of the name, they're a mechanism for escaping, aren't they?

**Comment by imnotjames** [comment] 2021-07-09 07:24
Looking it up that does appear to be the case.  As such, this is a duplicate of #3531

**Closed by imnotjames** 2021-07-09 07:24 UTC
Labels: bug, driver: mssql, requires triage

**Comment by Elithsar** [comment] 2021-07-09 10:01
It is a mechanism for escaping indeed. But our dba uses dotted database names and we can't rename those ones (e.g. foo.bar.etc)

So, if in our db we have the schema "dbo" and table "sample", generated query in actual version will look like this:

`SELECT * FROM "foo"."bar"."etc"."dbo"."sample"`

which will fail

TypeORM should produce this query instead by using the escape mechanism

`SELECT * FROM [foo.bar.etc].[dbo].[sample] -- schema and tablename could contain dots also`

In fact, there is a problem in the QueryBuilder and SqlServerQueryRunner which applies a split(".") on the whole tablename (foo.bar.etc.dbo.sample).
