### ISSUE TITLE
Create query builder with "with" clause in Postgres

### ISSUE THREAD

**Issue by dennbagas** [typeorm/typeorm#5149] opened 2019-11-27 08:19 UTC
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have raw query like this: 
```
WITH w AS (UPDATE foo SET foo_type = 'WOW' WHERE foo_uuid = 17 RETURNING "foo_uuid", "foo_paired_to", "foo_type")
SELECT bar.name, w.foo_uuid, w.foo_type
FROM bar, w
WHERE bar.id = w.foo_paired_to;
```
How to convert that into a query builder with typeorm?

**Comment by Ginden** [comment] 2019-12-04 16:17
Duplicate of #1116

**Comment by fullofcaffeine** [comment] 2020-03-14 00:39
I'm also looking into how to use `with` (recursive) with the `QueryBuilder`.

**Comment by imnotjames** [comment] 2020-10-10 12:05
Duplicate of #1116

**Closed by imnotjames** 2020-10-10 12:05 UTC
Labels: driver: postgres, question
