### ISSUE TITLE
Upgrading 0.2.19 to 0.2.15 causes migrations to be ORDER BY "id" instead of timestamp

### ISSUE THREAD

**Issue by boris-lapouga** [typeorm/typeorm#6245] opened 2020-06-11 16:31 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
`yarn typeorm migration:show`

After running the above command, TypeORM is throwing an error:

> query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
> query failed: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
> error: error: column "id" does not exist

It was never ordered by "id" before, we don't have it in our models or I am missing something.

Is there a way to select and order migrations by their timestamp as [official documentation](https://github.com/typeorm/typeorm/blame/master/docs/migrations.md#L154) states?

**Comment by imnotjames** [comment] 2020-10-12 07:59
Duplicate of #4941

**Closed by imnotjames** 2020-10-12 07:59 UTC
Labels: bug, comp: migrations, driver: postgres
