### ISSUE TITLE
[Question] Pb with custom repository in class-validator custom

### ISSUE THREAD

**Issue by StephenBeg** [typeorm/typeorm#1236] opened 2017-11-26 13:30 UTC
Hi !

Little problème when i add Custom validator to an Entity :

```
@ValidatorConstraint({ async: true })
export class IsProductNotExistConstraint implements ValidatorConstraintInterface {

  public validate = async (productName: any, _args: ValidationArguments): Promise<boolean> => {
    const product: Product | undefined = await RepositoryFactory.getRepository(ProductRepository).findOneByName(productName);
    if (product === undefined) {
      return false;
    } else {
      return true;
    }
  }

}

export function IsProductNotExist(validationOptions?: ValidationOptions): ((object: Object, propertyName: string) => void) {
  return (object: Object, propertyName: string): void => {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: IsProductNotExistConstraint
    });
  };
}

```

The factory use connection.getCustomRepository function.
But if i do this, routing-controller return this response :

`{
    "name": "CustomRepositoryCannotInheritRepositoryError",
    "message": "Custom entity repository ProductRepository  cannot inherit Repository class without entity being set in the @EntityRepository decorator."
}`

Alright, my repository use EntityRepository decorator : 
```
@EntityRepository(Product)
export class ProductRepository extends Repository<Product> {

  public findOneByName = async (name: string): Promise<Product | undefined> => {
    return this.findOne({name: name});
  }

}
```

Have an idea to fix this ?
Thanks ! And great job !

**Comment by pleerock** [comment] 2017-11-27 06:43
Are you able to create a minimal reproduction git repo of this error? Because custom repositories work and there are tests for them, I need to dig into your concrete case to find out a problem.

**Comment by StephenBeg** [comment] 2017-11-27 10:47
https://github.com/StephenBeg/testTypeorm

In this repo, you juste have to execute "yarn" commande to load dependancies, change database in ormconfig.json and launch with "yarn start"

Thanks

**Comment by pleerock** [comment] 2017-11-30 05:17
Try to add console.log before entityrepository decorator:

```ts
console.log("Product", Product);
@EntityRepository(Product)
```

And you'll see `Product undefined` in console.

How this can be possible? It executes Product entity code after it executes this code because someone else is executing something else that has dependency in product and somewhere else, hard to say, you have a bad files organization and circular references which cannot be resolved by language. I suggest you to start from scratch and organize a better project structure.

This issue not related to typeorm somehow so Im closing it.

**Closed by pleerock** 2017-11-30 05:17 UTC
Labels: invalid, needs more info

**Comment by StephenBeg** [comment] 2017-11-30 10:01
Hi,

Thanks for answer.
I see the circular reference : 
Entity -> Validator -> Custom Repository -> Entity ->  ... 

I thinks this pb is unsolvabled and your example in class-validator project doesn't work to  :
```
import {registerDecorator, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface, ValidationArguments} from "class-validator";

@ValidatorConstraint({ async: true })
export class IsUserAlreadyExistConstraint implements ValidatorConstraintInterface {

    validate(userName: any, args: ValidationArguments) {
        return UserRepository.findOneByName(userName).then(user => {
            if (user) return false;
            return true;
        });
    }

}

export function IsUserAlreadyExist(validationOptions?: ValidationOptions) {
   return function (object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            constraints: [],
            validator: IsUserAlreadyExistConstraint
        });
   };
}
```
(UserRepository) create a circular reference.
