### ISSUE TITLE
No foreign key created in simple case

### ISSUE THREAD

**Issue by brucelarasoft** [typeorm/typeorm#8130] opened 2021-08-28 09:17 UTC
## Issue Description

Creating 2 simple related entities should result in a foreign key, but doesn't.

### Expected Behavior

Subarea table should have a Foreign key referencing Area.

### Actual Behavior

Here are the 2 entities:

```
@Entity('Area')
export class Area {
  @PrimaryGeneratedColumn('uuid')
  Id: string;

  @Column({
    unique: true,
  })
  Name: string;

  @CreateDateColumn()
  CreatedAt: Date;

  @UpdateDateColumn()
  UpdatedAt: Date;

  @OneToMany(() => Subarea, (Subarea) => Subarea.Area)
  Subareas: Subarea[];
}
```
and
```
@Entity('Subarea')
export class Subarea {
  @PrimaryGeneratedColumn('uuid')
  Id: string;

  @Column()
  Name: string;

  @CreateDateColumn()
  CreatedAt: Date;

  @UpdateDateColumn()
  UpdatedAt: Date;

  @ManyToOne(() => Area, (Area) => Area.Subareas) 
  @JoinColumn({ name: 'AreaId', referencedColumnName: 'Id' })
  Area: Area;
}
```

### Steps to Reproduce

1. Run these 2 entities (I did on a MySQL AWS RDS DB, not sure if that's relevant)
2. Check the absence of foreign keys

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System   Windows 10|          |
| Node.js version     | v14.16.0 | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 
| NestJS                       | 8.0.0 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ranjan-purbey** [comment] 2021-08-28 11:50
I tried the above two entities and the FK was generated as expected. Can you please share your output for `migration:generate`?

**Comment by brucelarasoft** [comment] 2021-08-28 11:59
@ranjan-purbey thanks so much - I'm using typeorm within nestjs with synchronize: true for now - how could I send you debugging info in this context?

**Comment by ranjan-purbey** [comment] 2021-08-28 12:02
Can you create a minimal reproducible example repo and share it?

**Comment by brucelarasoft** [comment] 2021-08-28 12:05
@ranjan-purbey  ok i'll try thanks so much

**Comment by brucelarasoft** [comment] 2021-08-28 12:47
@ranjan-purbey git@github.com:brucelarasoft/min-nest-proj.git
you'll need to create a `.env.stage.dev` file in the root folder with:
```
DB_HOST=something
DB_PORT=something
DB_USERNAME=something
DB_PASSWORD=something
DB_DATABASE=something
DB_SCHEMA=something
```

Thanks so much for looking!
(I confirmed I still get no foreign key)

**Comment by ranjan-purbey** [comment] 2021-08-28 16:13
Seems like there is an issue with mssql schemas and typeorm. For the time being, you can omit the schema field in your typeorm config

**Comment by ranjan-purbey** [comment] 2021-08-28 16:29
Looks like the bug was introduced in `0.2.35`

**Comment by brucelarasoft** [comment] 2021-08-28 16:49
Oh wow, that works, thanks!

**Comment by ranjan-purbey** [comment] 2021-08-29 00:05
This issue seems to have been fixed in master, most probably by https://github.com/typeorm/typeorm/pull/8038

**Comment by brucelarasoft** [comment] 2021-08-29 06:45
Awesome, thanks so much for your help

**Comment by ranjan-purbey** [comment] 2021-08-29 07:55
You're welcome! Please close the issue if your problem has been resolved

**Closed** 2022-12-29 16:27 UTC
Labels: bug, requires triage
