### ISSUE TITLE
Migrations make meaningful error output

### ISSUE THREAD

**Issue by dknx01** [typeorm/typeorm#4441] opened 2019-07-16 09:31 UTC
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. install typorm
2. try: ./node_modules/.bin/typeorm migration:create
without any parameter

Output:
`typeorm migration:create

Creates a new migration file.

Optionen:
  -h, --help        Hilfe anzeigen                                     [boolean]
  -c, --connection  Name of the connection on which run a query.
                                                           [Standard: "default"]
  -n, --name        Name of the migration class.                  [erforderlich]
  -d, --dir         Directory where migration should be created.
  -f, --config      Name of the file with connection configuration.
                                                         [Standard: "ormconfig"]
  -v, --version     Version anzeigen                                   [boolean]

Fehlendes Argument: n
`
Missing argument : n

Expected for a good user experience:
 Specify which parameter(s) is/are missing. 'n' is very less meaningful and does not help the user in how to solve it.

**Comment by Kononnable** [comment] 2019-08-31 14:16
Could you please elaborate?
It says parameter which can be set by `-n` is missing, and from list of parameters above you can see its description.

**Comment by imnotjames** [comment] 2020-10-07 04:24
Sounds like this was answered, and was not a bug.

I'm gonna be closing it out.

**Closed by imnotjames** 2020-10-07 04:24 UTC
Labels: bug, comp: migrations
