### ISSUE TITLE
afterInsert called with the same entity in batch inserts

### ISSUE THREAD

**Issue by Nosfistis** [typeorm/typeorm#6578] opened 2020-08-18 13:37 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am using TypeORM with NestJS. I have a subscriber implementing the `EntitySubscriberInterface`, specifically the `afterInsert`. When inserting multiple values at once using `repository.insert(values)`, the `afterInsert` is called as many times as the values, but the attached entity is always the first of them. I have not found any other way to retrieve the entities inserted.

**Comment by Nosfistis** [comment] 2020-08-18 14:13
After some investigation, the `InsertResult` from `repository.insert(values)` itself contains an array with the same generated map multiple times. The `SELECT` query performed after the insert uses the first `id` as well, so that's causing the issue.

This does not occur in `repository.save` operations.

This was tested in MariaDB 10.5.

**Comment by dolsup** [comment] 2020-09-04 03:10
related to #6266, #2131

**Comment by imnotjames** [comment] 2020-10-09 21:08
Duplicate of #2131

Closed.

**Closed by imnotjames** 2020-10-09 21:08 UTC
Labels: bug, driver: mysql
