### ISSUE TITLE
Documentation does not mention errors

### ISSUE THREAD

**Issue by aschrijver** [typeorm/typeorm#6302] opened 2020-06-24 11:23 UTC
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

<br/>

Just started with TypeORM and I see there are many types of errors that are defined in the code, such as `EntityNotFoundError` and `MongoError` etcetera. The documentation does not mention what errors exist and can be expected on an API call. While some are related to misconfiguration of TypeORM and need not special mention, others deal with runtime exceptions i.e. `ConnectionNotFoundError` if db is down, which must be handled.

Is there separate reference to errors + error handling, or is it worthwhile to add this to the documentation?

**Comment by imnotjames** [comment] 2021-06-30 05:00
Duplicate of #5287

**Closed by imnotjames** 2021-06-30 05:00 UTC
Labels: documentation
