### ISSUE TITLE
Running migrations on MS SQL db tries to create the migrations table on every run

### ISSUE THREAD

**Issue by PJCAfonso** [typeorm/typeorm#3164] opened 2018-11-27 10:24 UTC
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue
**Database system/driver:**
[X] `mssql`
**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.9` (or put your version here)

Hi all

We are initiate my first step with TypeORM and GraphQL, we came from Django both on MS and CentOS.

We defined a entity User.ts

`import {Entity, Column, BaseEntity, PrimaryColumn, BeforeInsert} from "typeorm";
import { v4 }  from "uuid";

@Entity('Site.Users')
export class User extends BaseEntity {

    @PrimaryColumn("uuid") id: string;
    @Column('varchar', { length: 255 } )
    email: string;
    @Column("text") password: string;
    @Column("bit", { default: false }) confirmed: boolean;
    @Column("datetime2", { precision: 3, default: () => "CURRENT_TIMESTAMP", onUpdate: "CURRENT_TIMESTAMP"})
    lastUpdate: Date;
    @BeforeInsert()
    addId(){
        this.id = v4();
    }  
}`
and after ran a migration:generate for frist time, we got the following file.

`
import {MigrationInterface, QueryRunner} from "typeorm";

export class initialize1543170970746 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "Site"."Users" ("id" uniqueidentifier NOT NULL, "email" varchar(255) NOT NULL, "password" text NOT NULL, "confirmed" bit NOT NULL CONSTRAINT "DF_73213f34d537ab34e7fef69e996" DEFAULT 0, "lastUpdate" datetime2(3) NOT NULL CONSTRAINT "DF_8ee361a626ea3fc24b24b04b388" DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PK_21084ba4d97b75818da72d9314a" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "Site"."Users"`);
    }
}
`

we need to add feature, add two column blocked and retries, to my entity User and change User.ts like this:
`
import {Entity, Column, BaseEntity, PrimaryColumn, BeforeInsert} from "typeorm";
import { v4 }  from 'uuid';

@Entity('Site.Users')
export class User extends BaseEntity {

    @PrimaryColumn("uuid") id: string;
    @Column('varchar', { length: 255 } )
    email: string;
    @Column("text") password: string;
    @Column("bit", { default: false }) confirmed: boolean;
    @Column("bit", { default: false }) blocked: boolean;
    @Column("int", { default: 0 }) retries: number;**
    @Column("datetime2", { precision: 3, default: () => "CURRENT_TIMESTAMP", onUpdate: "CURRENT_TIMESTAMP"})
    lastUpdate: Date;

    @BeforeInsert()
    addId(){
        this.id = v4();
    }  
}
`

and after migration:generate we got this file:
`import {MigrationInterface, QueryRunner} from "typeorm";

export class userBlockedRetries1543251926792 implements MigrationInterface {
        await queryRunner.query(`CREATE TABLE "Site"."Users" ("id" uniqueidentifier NOT NULL, "email" varchar(255) NOT NULL, "password" text NOT NULL, "confirmed" bit NOT NULL CONSTRAINT "DF_73213f34d537ab34e7fef69e996" DEFAULT 0, "blocked" bit NOT NULL CONSTRAINT "DF_a0be8c102f7105d34cf2daef02b" DEFAULT 0, "retries" int NOT NULL CONSTRAINT "DF_995cc9d2d7fd0cba57e3e3e8bd3" DEFAULT 0, "lastUpdate" datetime2(3) NOT NULL CONSTRAINT "DF_8ee361a626ea3fc24b24b04b388" DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PK_21084ba4d97b75818da72d9314a" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "Site"."Users"`);
    }
}`

So was we told we came from django/python and in there this is create and update my schemas as we need, here is look the **TypeORM** try to create all the time all tables.

Of, course we can change manually each migration file, but we prefered to do automatically all **sql files** we need to do that refreash my database.

Also, when we implement on production we have sure all stuff are write done.

Any ideais we can walk to resolve this, or any more information, to help me please just say.

Thks to all.

**Comment by JJesi** [comment] 2019-04-10 07:28
how to add new columns  programmatic because my application on production.

**Comment by osnersanchez** [comment] 2019-05-27 00:59
I am having this same problem when generating a second migration

**Comment by osnersanchez** [comment] 2019-06-12 02:39
Looking more closely at my problem I came to the conclusion that it was caused by the use of CamelCase in the names of my tables, when generating the tables they were all created with mini letters, and in the next migration to create the same tables, solve it Substituting CamelCase for '_' for tables with compound names.

**Comment by imnotjames** [comment] 2021-07-13 08:44
This seems to be fixed at this point.  I can't replicate, at least.  Closing!

**Closed by imnotjames** 2021-07-13 08:44 UTC
Labels: bug, comp: migrations, driver: mssql, question

**Comment by nwinger** [comment] 2021-10-05 11:05
Still experiencing this issue, when generating new migrations it also tries to recreate existing tables in the database.

Initial migration:
`import {MigrationInterface, QueryRunner} from "typeorm";

export class SetupTables1632990676704 implements MigrationInterface {
    name = 'SetupTables1632990676704'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "CommandCenterDB".."tenant" ("id" uniqueidentifier NOT NULL CONSTRAINT "DF_da8c6efd67bb301e810e56ac139" DEFAULT NEWSEQUENTIALID(), "azureTenantId" nvarchar(255) NOT NULL, "azureTenantName" nvarchar(255) NOT NULL, "azureAnalyticsId" nvarchar(255), "createdAt" datetime2 NOT NULL CONSTRAINT "DF_32013feb275f7a0f41c451cd0df" DEFAULT getdate(), "updatedAt" datetime2 NOT NULL CONSTRAINT "DF_f2facb95edfc89041b6ed1fdbf6" DEFAULT getdate(), CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "CommandCenterDB".."action" ("id" uniqueidentifier NOT NULL CONSTRAINT "DF_2d9db9cf5edfbbae74eb56e3a39" DEFAULT NEWSEQUENTIALID(), "tenantId" uniqueidentifier NOT NULL, "azureTenantId" nvarchar(255) NOT NULL, "description" nvarchar(255) NOT NULL, "handledByCustomer" bit NOT NULL, "createdAt" datetime2 NOT NULL CONSTRAINT "DF_e71b65767b8c972fdc972c878fd" DEFAULT getdate(), "updatedAt" datetime2 NOT NULL CONSTRAINT "DF_5b3b6c0dd17aaa4d15741324380" DEFAULT getdate(), CONSTRAINT "PK_2d9db9cf5edfbbae74eb56e3a39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."action" ADD CONSTRAINT "FK_ca0d00bd66ca6bc1376f8823026" FOREIGN KEY ("tenantId") REFERENCES "CommandCenterDB".."tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."action" DROP CONSTRAINT "FK_ca0d00bd66ca6bc1376f8823026"`);
        await queryRunner.query(`DROP TABLE "CommandCenterDB".."action"`);
        await queryRunner.query(`DROP TABLE "CommandCenterDB".."tenant"`);
    }

}
`

Generating a new migration, which adds a table:
`import {MigrationInterface, QueryRunner} from "typeorm";

export class AddAlert1633431056839 implements MigrationInterface {
    name = 'AddAlert1633431056839'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "CommandCenterDB".."alert" ("id" uniqueidentifier NOT NULL CONSTRAINT "DF_ad91cad659a3536465d564a4b2f" DEFAULT NEWSEQUENTIALID(), "azureTenantId" nvarchar(255) NOT NULL, "tenantId" uniqueidentifier, "title" nvarchar(255) NOT NULL, "alert" nvarchar(255) NOT NULL, "alertDescription" nvarchar(255) NOT NULL, "alertType" nvarchar(255) NOT NULL, "severity" int NOT NULL, "customer" nvarchar(255) NOT NULL, "pointOfContact" nvarchar(255) NOT NULL, "email" nvarchar(255) NOT NULL, "phone" nvarchar(255) NOT NULL, "statusValue" nvarchar(255) NOT NULL, CONSTRAINT "PK_ad91cad659a3536465d564a4b2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "CommandCenterDB".."tenant" ("id" uniqueidentifier NOT NULL CONSTRAINT "DF_da8c6efd67bb301e810e56ac139" DEFAULT NEWSEQUENTIALID(), "azureTenantId" nvarchar(255) NOT NULL, "azureTenantName" nvarchar(255) NOT NULL, "azureAnalyticsId" nvarchar(255), "createdAt" datetime2 NOT NULL CONSTRAINT "DF_32013feb275f7a0f41c451cd0df" DEFAULT getdate(), "updatedAt" datetime2 NOT NULL CONSTRAINT "DF_f2facb95edfc89041b6ed1fdbf6" DEFAULT getdate(), CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "CommandCenterDB".."action" ("id" uniqueidentifier NOT NULL CONSTRAINT "DF_2d9db9cf5edfbbae74eb56e3a39" DEFAULT NEWSEQUENTIALID(), "tenantId" uniqueidentifier NOT NULL, "azureTenantId" nvarchar(255) NOT NULL, "description" nvarchar(255) NOT NULL, "handledByCustomer" bit NOT NULL, "createdAt" datetime2 NOT NULL CONSTRAINT "DF_e71b65767b8c972fdc972c878fd" DEFAULT getdate(), "updatedAt" datetime2 NOT NULL CONSTRAINT "DF_5b3b6c0dd17aaa4d15741324380" DEFAULT getdate(), CONSTRAINT "PK_2d9db9cf5edfbbae74eb56e3a39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."alert" ADD CONSTRAINT "FK_fb7bb5dc8fa0b2e5d1459c977be" FOREIGN KEY ("tenantId") REFERENCES "CommandCenterDB".."tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."action" ADD CONSTRAINT "FK_ca0d00bd66ca6bc1376f8823026" FOREIGN KEY ("tenantId") REFERENCES "CommandCenterDB".."tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."action" DROP CONSTRAINT "FK_ca0d00bd66ca6bc1376f8823026"`);
        await queryRunner.query(`ALTER TABLE "CommandCenterDB".."alert" DROP CONSTRAINT "FK_fb7bb5dc8fa0b2e5d1459c977be"`);
        await queryRunner.query(`DROP TABLE "CommandCenterDB".."action"`);
        await queryRunner.query(`DROP TABLE "CommandCenterDB".."tenant"`);
        await queryRunner.query(`DROP TABLE "CommandCenterDB".."alert"`);
    }

}
`

Notice the tables "tenant" and "action" are being recreated with the last migration, which yields this error:
`Error: There is already an object named 'tenant' in the database.`

Currently running typeorm version 0.2.37
