### ISSUE TITLE
Cascade activated when it is not set

### ISSUE THREAD

**Issue by iceCreamParlor** [typeorm/typeorm#7818] opened 2021-06-30 04:59 UTC
## Issue Description
 I made a Order entity, and an OrderItem entity with one-to-many relations without any cascade option (For a web store). 
When I try to save order entity, UPDATE queries are executed on both order and orderItem entity.

### Expected Behavior
```
 Typeorm tries to update an Order entity.
```

### Actual Behavior

```
Typeorm tries to update both Order and OrderItem entities.
```

### Steps to Reproduce

Here are my entities:

```typescript
// Order
@Entity({ database: "Order", schema: "dbo", name: "Order" })
export class Order {
  @PrimaryGeneratedColumn()
  ID!: number;

  @Column()
  OrderName!: string;

  @Column()
  TotalAmount!: number;

  @Column()
  ApprovedDate?: Date;

  @Column()
  ModifiedDate?: Date;

  @Column()
  RegDate!: Date;

  @OneToMany((type) => OrderItem, (t) => t.Order)
  OrderItems?: OrderItem[];

}
```

```typescript
// OrderItem
@Entity({ database: "Order", schema: "dbo", name: "OrderItem" })
export class OrderItem {
  @PrimaryGeneratedColumn()
  ID!: number;

  @Column()
  OrderID!: number;

  @Column()
  ItemID!: number;

  @Column()
  OptionID!: number;

  @Column()
  Quantity!: number;

  @Column()
  Price!: number;

  @Column()
  RegDate!: Date;

  @ManyToOne((type) => Order, (t) => t.OrderItem)
  @JoinColumn({ name: "OrderID" })
  Order?: Order;

}
```

What I wrote in business logic is simply like below.

```typescript
const order = await this.getRepositoryFor(Order).findOneOrFail({
  where: {
      ...
  },
  relations:
    ["OrderItems"],
});

order.OrderItems = order.OrderItems.filter(oi => oi.Price > 0)
await manager.save(order)
```

then UPDATE query executed on OrderItem. 
I thought only order entity should be updated since I didn't set any cascade options.

```
QueryFailedError: Error: Cannot insert the value NULL into column 'OrderID', table 'OrderItem'; column does not allow nulls. UPDATE fails.
```

Why is the save action trying to update OrderItem even though I didn't configure any cascade option on true?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.22.1 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.30 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ x ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ x ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-06-30 07:40
Does this happen with `v0.2.34` as well?

**Comment by iceCreamParlor** [comment] 2021-07-02 00:59
@imnotjames 
Yes. Problem not solved with ```v.0.2.34```  as well.

**Comment by iceCreamParlor** [comment] 2021-07-02 01:02
Is it related to this issue ? 
https://github.com/typeorm/typeorm/issues/2859#issuecomment-425878844

**Comment by imnotjames** [comment] 2021-07-05 01:36
Looks like that's indeed the same issue

**Comment by imnotjames** [comment] 2021-07-05 01:36
Duplicate of #2859

**Closed by imnotjames** 2021-07-05 01:36 UTC
Labels: bug, requires triage
