### ISSUE TITLE
HMR + TypeORM

### ISSUE THREAD

**Issue by plashenkov** [typeorm/typeorm#6241] opened 2020-06-10 21:23 UTC
Hi there! :)

I'm using Next.js with TypeORM and everything works brilliant except the one thing: the server is running in dev (watch) mode, and it recompiles under the hood every time when source files change. And entity objects/classes are changed too, so TypeORM connection doesn't recognize them: we register one entities in `createConnection()`, and later we have other. So, we get:

> RepositoryNotFoundError: No repository for "User" was found.
> Looks like this entity is not registered in current "default" connection?

Is it possible to workaround this somehow? Maybe... a way to register all (current and future) entities for a specific connection? Or maybe to dynamically add new entities to the connection? Or maybe there is even the best solution already exists?

(Next.js server can compile all entities and other code into one or several files, it optimizes everything at its discretion, so we simply do not have any concrete folder with compiled entities which we could add to connection options as a wildcard path.)

Thanks for your attention! And hope this is somehow solvable.

---

**Issue type:**
[x] question

**Database system/driver:**
[x] mysql

**TypeORM version:**
[x] 0.2.25

**Comment by MattPua** [comment] 2020-06-11 03:16
So not sure if this can help solve your issue, but I dealt with something similar while using Webpack (which I presume NextJS also uses as well).

Basically, when running with the webpack:watch, I have my ormconfig.js point the src folder to wherever my output is.

```
  entities: ['dist/entity/index.js'],
  subscribers: ['dist/subscriber/*.js'],
  migrations: ['dist/migration/*.js'],
```

I  also have to do some hacky stuff thats more webpack related to get TypeORM to play okay.

```
    try {
      // A SUPER SKETCHY way to deal wit hot reloading. If no connection exists, will create one, otherwise getConnection wont fail
      getConnection();
    } catch (_error) {
      // NOTE: need to manually set the entities here because of how webpack works
      // https://github.com/typeorm/typeorm/issues/2310
      // https://github.com/typeorm/typeorm/issues/5064
      await createConnection({
        ...getORMConfig(),
        name: 'default', // by default, typeORM calls will use the 'default' connection unless otherwise specifeid
        entities: Object.values(entities),
      } as ConnectionOptions);
    }
```

**Comment by plashenkov** [comment] 2020-06-11 03:25
Hey Matt! Thanks for your answer!
```js
entities: Object.values(entities),
```
Where does the second `entities` come from?

Well, I register all my entities manually, something like:
```
import User from './User';

await createConnection({
  // ...
  entities: [User]
});
```
But it doesn't help.

**Comment by MattPua** [comment] 2020-06-11 03:28
Oh, also looking looking at your typeorm version, I see you're on the latest ones.

I've had problems with versions greater than 0.2.23 and beyond.

I would try downgrading to 0.2.22

**Comment by plashenkov** [comment] 2020-06-13 23:13
For those who face the same challenge and have found this issue, this is my solution.
It looks like it perfectly works with HMR.

```ts
import { Connection, getConnectionManager } from 'typeorm';
import { User } from '../entities/User';

const options = {
  default: {
    type: 'mysql',
    url: process.env.DATABASE_URL,
    synchronize: process.env.NODE_ENV !== 'production',
    entities: [
      User, // etc...
    ]
  },
};

function entitiesChanged(prevEntities: any[], newEntities: any[]): boolean {
  if (prevEntities.length !== newEntities.length) return true;

  for (let i = 0; i < prevEntities.length; i++) {
    if (prevEntities[i] !== newEntities[i]) return true;
  }

  return false;
}

async function updateConnectionEntities(connection: Connection, entities: any[]) {
  if (!entitiesChanged(connection.options.entities, entities)) return;

  // @ts-ignore
  connection.options.entities = entities;

  // @ts-ignore
  connection.buildMetadatas();

  if (connection.options.synchronize) {
    await connection.synchronize();
  }
}

export async function ensureConnection(name: string = 'default'): Promise<Connection> {
  const connectionManager = getConnectionManager();

  if (connectionManager.has(name)) {
    const connection = connectionManager.get(name);

    if (process.env.NODE_ENV !== 'production') {
      await updateConnectionEntities(connection, options[name].entities);
    }

    return connection;
  }

  return await connectionManager.create({ name, ...options[name] }).connect();
}
```

**Comment by plashenkov** [comment] 2020-06-13 23:15
I still believe TypeORM should have `connection.updateEntities()` out of the box, and we would not need to use these `// @ts-ignore` workarounds.

**Comment by deresegetachew** [comment] 2020-06-25 13:32
> ```ts
> connection
> ```

hi @plashenkov i was wondering where exactly can I call ensureConnection() inside my nextjs ; I was also working on nextjs and all examples initialize connection using the project entry file, and I don't think there is an entry file in nextjs

**Comment by plashenkov** [comment] 2020-06-25 13:39
Hi @deresegetachew! Next.js insists developers not to use custom server if possible. See the note here: https://nextjs.org/docs/advanced-features/custom-server In this case `ensureConnection()` has to be in every server-side function (i.e. `pages/api/yourfile.js`).

**Comment by ivawzh** [comment] 2020-06-28 18:09
@plashenkov thanks for sharing the tips with the community. Would you plz set up a public repo or even a NextJS example PR for the way you setup NextJS + TypeOrm?

**Comment by ranjan-purbey** [comment] 2020-07-05 03:38
@deresegetachew you can use the `ensureConnection` function inside your API request handlers. For e.g.,
```
# /pages/api/users.ts

import { ensureConnection } from "/lib/database"
export default async (req, res) => {
    const connection = await ensureConnection();
    ...
}
```

**Comment by trompx** [comment] 2020-07-06 20:13
I'm also having this issue.
@plashenkov I'd be interested too in your setup if you do more than just load `ensureConnection` in each api route.
I was wondering if we could use `ensureConnection` as a middleware with something like [next-connect](https://github.com/hoangvvo/next-connect) instead.

**Comment by plashenkov** [comment] 2020-07-06 22:49
Hi @ivawzh and @trompx

Well, I'm still working on my setup and currently there is not much more, just some optimizations. When it is done, I'll publish it, no problem. Currently I am trying to integrate with NextAuth.js and discuss with NextAuth's developer some issues: https://github.com/iaincollins/next-auth/issues/385

**Comment by trompx** [comment] 2020-07-07 00:00
Hey @plashenkov, this is great news. Looks like we are trying to achieve the same thing. My input from last week on the next-auth issue tracker didn’t get attention, but Iain just referenced it on the one you created so it’s great, things are moving forward.

Concerning ensureConnection, I couldn’t make it work with next-connect, it still fails the second time I load the page. I’d like to setup the database connection as a middleware (ala express), I will maybe have more luck with graphql-middleware.

**Comment by plashenkov** [comment] 2020-07-07 00:14
@trompx Unfortunately I cannot say anything about middlewares yet. I planned to use TypeORM as a DataMapper (which is considered as a better practice over ActiveRecord), and we need a connection object for this. And if you want to use different databases for different entities, for example, you'll need to call `ensureConnection('name')` for those connections you are interested in.

If you use ActiveRecord and just a single database connection, then using middleware makes sense for sure. But I really don't know how to use it in this way yet :)

**Comment by romMidnight** [comment] 2020-07-09 10:10
> For those who face the same challenge and have found this issue, this is my solution.
> It looks like it perfectly works with HMR.
> 
> ```ts
> import { Connection, getConnectionManager } from 'typeorm';
> import { User } from '../entities/User';
> 
> const options = {
>   default: {
>     type: 'mysql',
>     url: process.env.DATABASE_URL,
>     synchronize: process.env.NODE_ENV !== 'production',
>     entities: [
>       User, // etc...
>     ]
>   },
> };
> 
> function entitiesChanged(prevEntities: any[], newEntities: any[]): boolean {
>   if (prevEntities.length !== newEntities.length) return true;
> 
>   for (let i = 0; i < prevEntities.length; i++) {
>     if (prevEntities[i] !== newEntities[i]) return true;
>   }
> 
>   return false;
> }
> 
> async function updateConnectionEntities(connection: Connection, entities: any[]) {
>   if (!entitiesChanged(connection.options.entities, entities)) return;
> 
>   // @ts-ignore
>   connection.options.entities = entities;
> 
>   // @ts-ignore
>   connection.buildMetadatas();
> 
>   if (connection.options.synchronize) {
>     await connection.synchronize();
>   }
> }
> 
> export async function ensureConnection(name: string = 'default'): Promise<Connection> {
>   const connectionManager = getConnectionManager();
> 
>   if (connectionManager.has(name)) {
>     const connection = connectionManager.get(name);
> 
>     if (process.env.NODE_ENV !== 'production') {
>       await updateConnectionEntities(connection, options[name].entities);
>     }
> 
>     return connection;
>   }
> 
>   return await connectionManager.create({ name, ...options[name] }).connect();
> }
> ```
> 
> Then you just use `ensureConnection()` to get and actualize the DB connection.

Thanks for the solution!

I stumbled upon a little problem, if first call to `ensureConnection()` fails to connect(for example typeorm threw error with "QueryFailedError: could not create unique index), connection object still gets created with `.isConnected` set to false, and on second `ensureConnection()` call you get different error as `synchronize()` & `buildMetadatas()` gets called on nonexistent connection, to prevent this I added guard before `updateConnectionEntities()`

`if (!connection.isConnected) {
      return connection.connect();
    }
`

**Comment by plashenkov** [comment] 2020-07-09 13:21
Hi @romMidnight, thank you! I've updated the code above.

**Comment by plashenkov** [comment] 2020-07-25 00:52
@trompx 

> Concerning ensureConnection, I couldn’t make it work with next-connect, it still fails the second time I load the page. I’d like to setup the database connection as a middleware (ala express), I will maybe have more luck with graphql-middleware.

Regarding using with next-connect, it works fine for me. Have you succeeded with it?

Here is my code of how to use ensureConnection() as a middleware:

```ts
import {Connection, getConnectionManager, getConnectionOptions} from 'typeorm'
import * as entities from 'src/entities'

function entitiesChanged(prevEntities: any[], newEntities: any[]): boolean {
  if (prevEntities.length !== newEntities.length) return true

  for (let i = 0; i < prevEntities.length; i++) {
    if (prevEntities[i] !== newEntities[i]) return true
  }

  return false
}

async function updateConnectionEntities(connection: Connection, entities: any[]) {
  if (!entitiesChanged(connection.options.entities, entities)) return

  // @ts-ignore
  connection.options.entities = entities

  // @ts-ignore
  connection.buildMetadatas()

  if (connection.options.synchronize) {
    await connection.synchronize()
  }
}

export async function ensureConnection(req, res, next) {
  const connectionManager = getConnectionManager()

  if (connectionManager.has('default')) {
    req.db = connectionManager.get()
    req.db.isConnected || await req.db.connect()

    if (process.env.NODE_ENV !== 'production') {
      await updateConnectionEntities(req.db, Object.values(entities))
    }
  } else {
    req.db = await connectionManager
      .create({
        ...await getConnectionOptions(),
        entities: Object.values(entities),
        migrations: [],
      })
      .connect()
  }

  return next()
}
```

Then somewhere:

```ts
import {NextApiRequest, NextApiResponse} from 'next'
import nextConnect from 'next-connect'
import {ensureConnection} from 'src/core/database'
import {User} from 'src/entities'

export default nextConnect<NextApiRequest, NextApiResponse>()
  .use(ensureConnection)
  .get(async (req, res) => {
    const allUsers = await User.find()
    res.json({result: 'success', allUsers})
  })

```

I hope this will help.

**Comment by kenperkins** [comment] 2020-10-01 19:31
@plashenkov did you have any success integrating this with Next-Auth or did you give up on that pursuit?

**Comment by plashenkov** [comment] 2020-10-01 19:34
Hi @kenperkins 
Yup, I moved away from next-auth to passport.js

**Comment by imnotjames** [comment] 2020-10-12 08:03
Duplicate of #5676

**Closed by imnotjames** 2020-10-12 08:03 UTC
Labels: question

**Comment by coloradocolby** [comment] 2021-03-14 08:47
I want to believe this is HMR as the methods above worked great when I ran production builds locally, but I was still seeing issues when deploying my NextJS application to Vercel.

Ultimately this is what solved this issue for me! 
https://github.com/typeorm/typeorm/issues/5676#issuecomment-797925238

**Comment by rwieruch** [comment] 2021-05-27 14:49
@plashenkov I had a really troublesome day because of this issue, but your solution seems to fix it! 🎉   At least in development for now, so I am looking forward to the deploy. Anyway, thank you so much!

Two questions though:

1. Do you ever close the connection at some point (e.g. after the request)?
2. Did you see the following warning [0] too?

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Comment by EdwinRies** [comment] 2021-06-03 10:41
I still had this issue even with the entities change hack.

I solved it by passing strings to getRepositories.

```
const getRepositoryWrapper = <Entity>(conn: Connection, entity:EntityTarget<Entity>) => {
  return conn.getRepository(typeof entity === "function" && entity.name || entity);
}
```
