### ISSUE TITLE
Generating migrations on entities with "public" schema explicitly specified fails

### ISSUE THREAD

**Issue by phlickey** [typeorm/typeorm#6343] opened 2020-07-03 11:24 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Repo: https://github.com/phlickey/typeorm-postgress-migration-issue/

1. Run `typeorm init` in a fresh directory.
2. Run `npm install` and `npm install pg`
2. Update `ormconfig.json` with the connection details of a postgres server. Server must have a schema named public, and may have additional schemas.
3. In `/src/entities/User.ts` edit the arguments of the `@Entities` decorator to specify the schema name should be public. ie:
```ts
@Entity("user-table", { schema: "public" })
```
4. Run `npx ts-node ./node_modules/.bin/typeorm migration:generate -n Init` to generate an initial migration.
5. Run `npx ts-node ./node_modules/.bin/typeorm migration:run` to apply the migration to the public schema.
6. Run `npx ts-node ./node_modules/.bin/typeorm migration:generate -n Secondary` to generate an second migration.
7. Despite no changes being made to any of the entities, a migration file is created with CREATE statements for a relation "public"."user-table" which already exists on the public schema.
8. Run `npx ts-node ./node_modules/.bin/typeorm migration:run`. Applying the migration fails trying to create a table which already exists.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment] 2020-10-07 04:52
Duplicate of #3907

**Closed by imnotjames** 2020-10-07 04:52 UTC
Labels: bug, comp: migrations, driver: postgres
