### ISSUE TITLE
`schema` option in postgres driver is not doing anything

### ISSUE THREAD

**Issue by romandecker** [typeorm/typeorm#6734] opened 2020-09-17 08:57 UTC
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.26`

The [documented `schema` parameter for postgres](https://typeorm.io/#/connection-options/postgres--cockroachdb-connection-options) does not seem to be doing anything. There was a [PR for adding a default schema in the past](https://github.com/typeorm/typeorm/pull/160), though under the `schemaName` property, but it seems this feature was removed completely.

All that remains is a `schema` option defined in the postgres driver, which does not have any effect it seems.

**Comment by romandecker** [comment] 2020-09-17 11:46
For anyone wondering, for now I'm working around the issue by doing this right after `createConnection()`:

```ts
if (config.database.schema && config.database.schema !== 'public') {
    await getConnection().query(`SET search_path TO '${config.database.schema}', 'public'`);
}
```

**Comment by chsguitar1** [comment] 2020-09-18 00:23
hi if would you like create other connection 
```
connection(schema: string) {
    return createConnection({
      name: 'name_for_connection',
      type: 'postgres',
      database: 'database',
      host: 'localhost',
      port: 5432,
      username: 'other_user_database',
      password: 'bMmuc%ZJ59G*',
      entities: ['src/entity/client/*.ts"],
      logging: true,
      schema: schema,
    });
  }
```


this works for me

**Comment by romandecker** [comment] 2020-09-18 06:01
@chsguitar1 hm, that's pretty much exactly what I have, only `schema` is defined in `ormconfig`. And it's not working for me.

**Comment by imnotjames** [comment] 2020-09-18 09:39
I'm seeing similar in the `@Entity` decorator

**Comment by romandecker** [comment] 2020-09-18 10:13
@imnotjames I believe those are working as expected. I'm only seeing the problem when I have to resort to raw queries or I'm using the query builder, e.g.

```ts
 // `foo` will always be looked up in `public`, regardless of the `schema` you pass to `createConnection`
getManager().query('SELECT * FROM foo')
```

**Comment by imnotjames** [comment] 2020-09-26 04:50
Ok - spent a bit of time thinking about this and digging through how the Postgres driver & query runner work.

Short version - you're calling a raw query.  What you write is what's sent to Postgres using `node-postgres`.  You don't write the schema?  It doesn't send the schema.  Simple as that.

Long version.

While I swear I was running into weirdness over what schema was being called when passed as an entity a few weeks ago I can't replicate it again so I'll chalk that up to user error!

The schema options used for:

* Entity defaults
* Query Builder defaults
* Automatic migration generation
* Schema synchronization
* Parsing table names

That's about it.  Nothing magical is done with the schema.  `node-postgres` has no option for the default schema.  Nothin.

That's why when you omit the schema when running a query it uses the default search path - `public`.

Perhaps when connecting a new handle we could set the search path when schema is set like in the comment above. Would be a nice quality of life fix & shouldn't negatively impact any existing functionality.  We do similar stuff on sqlite connection to prep it for use.

Pull requests welcome to implement that :)

**Comment by imnotjames** [comment] 2020-09-26 05:02
For some reason this behavior was dropped in
 https://github.com/typeorm/typeorm/commit/5194c7a0a55c833e106622a039770d400146dc16#diff-a2a8f77fc79655011d9d2b94ebc610bd 

Unclear why.

**Comment by imnotjames** [comment] 2020-09-29 02:38
Should be fixed in #6796 :) Test was put in place that checks it.

**Comment by romandecker** [comment] 2020-09-30 13:30
In the meantime, I've found that my workaround doesn't quite fix the problem. Apparently, typeorm will release the connection if an error occurs (such as a failed constraint, or similar). So only setting the `search_path` once after initializing the database is not enough.

We have to set the `search_path` whenever a fresh connection is made, which is very awkward from outside of typeorm:

```
const connection = getConnection();
await setSearchPath(connection);

const pgDriver = connection.driver as any;
for (const pool of [pgDriver.master, ...pgDriver.slaves]) {
    pool.on('connect', setSearchPath);
}

// setSearchPath basically runs connection.query(`SET search_path TO '${options.schema}', 'public'`);
```

**Comment by pleerock** [comment] 2020-09-30 19:13
see my comment [here](https://github.com/typeorm/typeorm/pull/6796#issuecomment-700835178)

**Comment by romandecker** [comment] 2020-10-01 06:26
@pleerock What would you recommend to do to make raw queries use a default schema other than `public`?

Just running it `SET search_path ...` once after calling `createConnection` doesn't seem to be enough because the connection might be released and re-created on-they-fly, resetting the `search_path` back to the original value.

Is there a nicer way to automatically prep a connection after creation (kinda like [what I'm doing in my workaround](https://github.com/typeorm/typeorm/issues/6734#issuecomment-701391807)) or would you just recommend explicitly mentioning the schema in every raw query?

Would be awesome to have a better way, cause hard-coding the schema into each query is a bit error-prone (especially when tables with the same name exist in the target schema and in `public`...).

**Comment by howieweiner** [comment] 2020-10-27 11:57
Hi. I'm seeing an issue when trying to run migrations against a non-default (public) Postgres schema. Up until now, we have been defaulting to public, by not setting the schema property anywhere.

We now want a test schema. So, I added the schema property and set it to 'test' in ormconfig.

When I run the migration it creates the migration table in the test schema.. but then the migrations fails on the first query as the table already exists - clearly using the public schema.

I'm not sure if this is the same issue or not? Seems odd that the migrations table is created ok

**Comment by romandecker** [comment] 2020-10-31 10:11
@howieweiner It's possible that you're running into the same problem. The schema option is picked up if you're using the migration API or the repository API (and also, if you're using the query builder in certain ways).

Things like `queryRunner.addColumn` and similar will work, as the target schema name be interpolated into the generated queries for you.

However, if you're doing stuff like `queryRunner.query('ALTER TABLE foo ADD COLUMN ...')` the `queryRunner` won't touch the raw query you input and will use the default schema search path (which won't include your `test` schema), so this is going to use the `public` schema instead.

Only way around this I've found is to either mention the schema name explicitly in raw queries (e.g. `ALTER TABLE test.foo ADD COLUMN ...`) or to set the search-path at the beginning of each migration that needs raw queries (like suggested in [my previous comment](https://github.com/typeorm/typeorm/issues/6734#issuecomment-694177713)).

**Comment by imnotjames** [comment] 2021-06-18 15:39
`schema` option only affects the query builder.  This is working as intended

**Closed by imnotjames** 2021-06-18 15:39 UTC
Labels: bug, documentation, driver: postgres
