### ISSUE TITLE
Create sequence repeatedly when it already exists

### ISSUE THREAD

**Issue by earllee** [typeorm/typeorm#1751] opened 2018-03-13 11:46 UTC
**Issue type:**
[x] question
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `0.1.16`

**Steps to reproduce or a small repository showing the problem:**
I have a simple User entity like this:
```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class User {
  @PrimaryGeneratedColumn() id = undefined;

  @Column('varchar') email = '';

  @Column('varchar') avatarURL = '';
}
```

The first time I start my server, everything runs fine, but every time the server restarts, I run in to this error:

```
query failed:  CREATE SEQUENCE "public"."user_id_seq" OWNED BY "public"."user"."id"
error:  { error: relation "user_id_seq" already exists
...
```

Here is the full log before the error shows up:
```
[nodemon] starting `babel-node server/app.js`
executing query:  START TRANSACTION
executing query:  SELECT * FROM current_schema()
executing query:  SELECT * FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'user' OR table_schema = 'public' AND table_name = 'category' OR table_schema = 'public' AND table_name = 'post'
executing query:  SELECT * FROM information_schema.columns WHERE table_schema IN ('public')
executing query:  SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name, ix.indisunique AS is_unique, a.attnum, ix.indkey FROM pg_class t, pg_class i, pg_index ix, pg_attribute a, pg_namespace ns
WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ('user', 'category', 'post') AND t.relnamespace = ns.OID AND ns.nspname IN ('public') ORDER BY t.relname, i.relname
executing query:  SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_schema IN ('public') AND constraint_type = 'FOREIGN KEY'
executing query:  SELECT * FROM information_schema.table_constraints WHERE table_schema IN ('public') AND constraint_type = 'UNIQUE'
executing query:  SELECT c.column_name, tc.table_name, tc.constraint_name FROM information_schema.table_constraints tc
JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name)
JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema AND tc.table_name = c.table_name AND ccu.column_name = c.column_name
where constraint_type = 'PRIMARY KEY' AND c.table_schema IN ('public')
executing query:  ALTER TABLE "public"."user" ALTER COLUMN "id" TYPE integer
executing query:  CREATE SEQUENCE "public"."user_id_seq" OWNED BY "public"."user"."id"
executing query:  ALTER TABLE "public"."user" ALTER COLUMN "id" SET DEFAULT nextval('"public.user_id_seq"')
executing query:  ALTER TABLE "public"."user" ALTER COLUMN "id" DROP DEFAULT
query failed:  CREATE SEQUENCE "public"."user_id_seq" OWNED BY "public"."user"."id"
error:  { error: relation "user_id_seq" already exists
...
```

**Comment by earllee** [comment] 2018-03-15 01:54
Looks like it's still occurring. Using `"typeorm": "^0.2.0-alpha.28"`.

**Comment by pleerock** [comment] 2018-03-16 07:53
model is simple and it should work without problems, either you made a mistake somewhere either you do something different way that others don't usually do. Can you please create a minimal reproduction git repo?

**Comment by pleerock** [comment] 2018-03-29 09:53
@AlexMesser added test that confirms that this functionality work. Please check again latest next and let us know if it still does not work for you. I'll close this issue.

**Closed by pleerock** 2018-03-29 09:53 UTC
Labels: needs more info

**Comment by nelsonBlack** [comment] 2018-06-02 14:41
check in your orm config if you have "synchronize": true, should be false,if true this makes application recreate db every time you run application as from the documentation :synchronize - Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production

**Comment by tragico0** [comment] 2021-03-19 22:24
For the record, I was having the same issue multiple times for months as we always set `synchronize: true` for local development, the first time works but sometimes it does not, it was always trying to recreate the sequences because something changed, I was the only one having this problem so always had to drop the schema and create it again losing the test data.

I got really annoyed and start debugging the library to see what was triggering the sequence creation and ended up finding that when getting the columns information from postgresql the value of `column_default` for primary keys was missing the shema but in other tests that my co-workers did the shema was there, so that was triggering the sequence creation as the `column_default` was different from the initial one, certainly I did something that modified that.

Turns out that sometimes when I create the database and schema I execute a command to set the `search_path` for my database to default the one recently created (i.e `ALTER DATABASE <database_name> SET search_path TO <schema>;`) this causes **PostgreSQL** to not include the schema when requesting `column_default` from the "information schema columns view", after that **just removed the schema from the `search_path` and the sync started working again**.
