### ISSUE TITLE
Custom entity repository error

### ISSUE THREAD

**Issue by truewt** [typeorm/typeorm#632] opened 2017-07-09 12:04 UTC
Hi,

I'm working on some application where I'm using the following libraries: class-validator, routing-controllers, typeorm, typedi, typeorm-typedi-extensions. I created example app to showcase the problem - available here: [ts_example_app](https://github.com/truewt/ts_example_app). Another description of the same problem is [here](https://github.com/pleerock/class-validator/issues/103) - sorry to duplicate the issue, but this is more of a typeorm problem I guess, then the class-validator one. I have successfully set up whole application to work as expected (routing, validation, ... works), but the problem is with calling custom repositories. Whenever I call User repository (check example app) I get the following error:
```
{
    "name": "CustomRepositoryCannotInheritRepositoryError",
    "message": "Custom entity repository UserRepository  cannot inherit Repository class without entity being set in the @EntityRepository decorator.",
    "stack": "
      CustomRepositoryCannotInheritRepositoryError: Custom entity repository UserRepository  cannot inherit Repository class without entity being set in the @EntityRepository decorator.
        at new CustomRepositoryCannotInheritRepositoryError (/path/to/ts-example-app/src/error/CustomRepositoryCannotInheritRepositoryError.ts:8:9)
        at EntityManager.getCustomRepository (/path/to/ts-example-app/src/entity-manager/EntityManager.ts:849:23)
        at Connection.getCustomRepository (/path/to/ts-example-app/src/connection/Connection.ts:296:29)
        at Object.value (/path/to/src/decorators/OrmCustomRepository.ts:18:31)
        at /path/to/ts-example-app/src/Container.ts:214:37
        at Array.map (native)
        at Function.Container.initializeParams (/path/to/ts-example-app/src/Container.ts:211:27)
        at Function.Container.get (/path/to/ts-example-app/src/Container.ts:94:47)
        at /path/to/ts-example-app/src/Container.ts:217:34
        at Array.map (native)
    "
}
```

I specified `@EntityRepository` decorator for sure... this is how the UserRepository looks like:
```
import { Repository, EntityRepository } from "typeorm";
import { Service } from "typedi";
import { User } from "../entities";

@Service()
@EntityRepository(User)
export class UserRepository extends Repository<User> {

}
```

I'm also calling `useContainer` for class-validator, typeorm and routing-controllers in the bootstrap class `src/example-app.ts` and in case that only `useContainer` for typeorm is used then there is no any error present for custom repositories, but then the problem is with injection for class-validator and routing-controllers classes. I tried a lot of different things to resolve this problem, but I somehow can't get over it. If it's possible I would prefer to retain repository in that form, so that it extends the Repository class, but if it's not I will appreciate any other recommendation.

So to reproduce this error, please take a look at [ts_example_app](https://github.com/truewt/ts_example_app) repository and check readme, to prepare project for debugging.

Thank you in advance!

**Comment by pleerock** [comment] 2017-07-10 07:20
Custom repositories should not be services! This is by design and there are reasons behind this requirement. You should use `connection.getCustomRepository(TestRepository)` to get custom repository instance. See #624 for details.

**Comment by truewt** [comment] 2017-07-10 15:57
Thanks for reply, but I'm still having more or less the same problem even with changed code based on your suggestion. I created base service which gets custom repository via EntityManager:
```
import { EntityManager } from "typeorm";
import { OrmEntityManager } from "typeorm-typedi-extensions";
import { Service } from "typedi";

@Service()
export class BaseService<T> {

  protected repository: any;

  constructor(
    @OrmEntityManager()
    protected entityManager: EntityManager
  ) {
    this.repository = entityManager.getCustomRepository<T>(() => {});
  }

}
```
And then I'm extending it in UserService like this:
```
import { Service } from "typedi";
import { User } from "../entities";
import { UserRepository } from "../repositories";
import { BaseService } from "./base/base-service";

@Service()
export class UserService extends BaseService<UserRepository> {

  protected repository: any;

  create(item: User): Promise<User> {
    // ...

    return this.repository.save(item);
  }

}
```

But now I'm getting back `CustomRepositoryNotFoundError`:
```
{
    "name": "CustomRepositoryNotFoundError",
    "message": "Custom repository  was not found. Did you forgot to put @EntityRepository decorator on it?",
    "stack": "
      CustomRepositoryNotFoundError: Custom repository  was not found. Did you forgot to put @EntityRepository decorator on it?
        at new CustomRepositoryNotFoundError (/path/to/src/error/CustomRepositoryNotFoundError.ts:8:9)
        at EntityManager.getCustomRepository (/path/to/src/entity-manager/EntityManager.ts:835:19)
        at new BaseService (/path/to/src/services/base/base-service.ts:14:37)
        at Function.Container.get (/path/to/src/Container.ts:115:32)
        at /path/to/src/Container.ts:217:34
        at Array.map (native)
        at Function.Container.initializeParams (/path/to/src/Container.ts:211:27)
        at Function.Container.get (/path/to/src/Container.ts:94:47)
        at Object.getFromContainer (/path/to/src/container.ts:53:44)
        at ControllerMetadata.get [as instance] (/path/to/src/metadata/ControllerMetadata.ts:75:16)
    "
}
```

I also tried to do call `getCustomRepository` method via `connection` from OrmConnection decorator, moved everything from BaseService to UserService's constructor and also called `getCustomRepository` method inside service's create method. In all those cases I'm still getting the error. In order to show you the complete code, I commited fixes to existing repository [ts_example_app](https://github.com/truewt/ts_example_app).

Could you please check again what I'm not doing in the right way. Thanks in advance!

**Comment by truewt** [comment] 2017-07-18 15:58
@pleerock any idea what should I do about the problem described above? Thanks!

**Comment by pleerock** [comment] 2017-07-19 07:50
What is `this.repository = entityManager.getCustomRepository<T>(() => {});` ?! Don't you find `() => {}` weird?! Thats why you have a problem. `getCustomRepository` accepts entity class, e.g. `User` in your case. Result is: `this.repository = entityManager.getCustomRepository<T>(User);`

If you want to create a common base class then something like this should be applied: 

```ts
@Service()
export class BaseService<T> {

  abstract protected model: any;
  protected repository: any;

  constructor(
    @OrmEntityManager()
    protected entityManager: EntityManager
  ) {
    this.repository = entityManager.getCustomRepository<T>(this.model);
  }

}
```

and


```ts
import { Service } from "typedi";
import { User } from "../entities";
import { UserRepository } from "../repositories";
import { BaseService } from "./base/base-service";

@Service()
export class UserService extends BaseService<UserRepository> {

  protected model = User;

  create(item: User): Promise<User> {
    // ...
    return this.repository.save(item);
  }

}
```

**Comment by pleerock** [comment] 2017-07-25 13:42
any updates?

**Comment by pleerock** [comment] 2017-07-27 11:28
Please let me know if you still have questions. Closing it.

**Closed by pleerock** 2017-07-27 11:28 UTC
Labels: question

**Comment by Svoig** [comment] 2017-08-17 18:40
I also ran into this error: 
`Custom entity repository MyCustomEntityRepository  cannot inherit Repository class without entity being set in the @EntityRepository decorator."` when correctly using `@EnityRepository(MyCustomEntity)`

I fixed it by changing my imports from 
`import {MyCustomEntity} from './';`
to
`import {MyCustomEntity} from './my-custom.entity.ts';`

I'm not sure if this is a TypeORM issue or not, but I'm interested if @pleerock has run into this before.

**Comment by pleerock** [comment] 2017-08-19 10:26
no i haven't. You have strange import syntax. Correct is `import {MyCustomEntity} from './my-custom.entity';`

**Comment by Svoig** [comment] 2017-08-21 17:09
You're right, that was a mistake. Apparently I've been relying too much on IDE's autocomplete 😬

**Comment by varHarrie** [comment] 2017-09-06 05:03
@pleerock 
I ran with you code above.

```js
@Service()
export class BaseService<T> {

  abstract protected model: any;
  protected repository: any;

  constructor(
    @OrmEntityManager()
    protected entityManager: EntityManager
  ) {
    console.log(this.model);      <----------------------------------- undefined
    this.repository = entityManager.getCustomRepository<T>(this.model);
  }

}

/////////////////////////////////////////////

import { Service } from "typedi";
import { User } from "../entities";
import { UserRepository } from "../repositories";
import { BaseService } from "./base/base-service";

@Service()
export class UserService extends BaseService<UserRepository> {

  protected model = User;

  create(item: User): Promise<User> {
    // ...
    return this.repository.save(item);
  }

}
```

and got error: 
> TypeError: Cannot read property 'constructor' of undefined
> at new CustomRepositoryNotFoundError
> at EntityManager.getCustomRepository
> at new BaseService
> ...

How can I create a base service class?

**Comment by pleerock** [comment] 2017-09-06 05:25
Of course its undefined if you do `at new BaseService`. You need to work with `UserService` only. Also remove `@Service` from BaseService and make that class abstract to prevent such mistakes further
