### ISSUE TITLE
Support creating relations without foreign key constraints

### ISSUE THREAD

**Issue by shvelo** [typeorm/typeorm#5977] opened 2020-04-30 15:29 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**  

Typeorm always creates a foreign key constraint when declaring relations.  

In contrast, Sequelize supports passing `{ constraints: false }` when declaring relations to disable creating foreign key constraints.  

I think Typeorm should do this too, it's very weird that it always forces constraints.   

https://sequelize.org/master/manual/constraints-and-circularities.html

**Comment by imnotjames** [comment] 2020-10-27 08:40
Duplicate of #3120

**Closed by imnotjames** 2020-10-27 08:40 UTC
Labels: driver: postgres, new feature
