### ISSUE TITLE
Error when saving data to mongodb

### ISSUE THREAD

**Issue by timoftealexandru** [typeorm/typeorm#1498] opened 2018-01-24 15:21 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.2` 

**Steps to reproduce or a small repository showing the problem:**

What I'm trying to do is to save data into mongodb and I'm getting the following error:

![alt tag](https://i.imgur.com/iiJ9FVZ.png) 

I have 2 connections, a mysql one and a mongodb one, as in the typeorm docs:
```
import {createConnections} from "typeorm";
import { ComponentContent } from "./components-content/entity"

const connections = await createConnections([{
    name: "db1Connection",
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "admin",
    database: "db1",
    entities: [__dirname + "/entity/*{.js,.ts}"],
    synchronize: true
}, {
    name: "db2Connection",
    type: "mongodb",
    host: "localhost",
    port: 27017,
    database: "db2",
    entities: [ComponentContent],
}]);
```

the entity class:
```
import {
  Entity, Column, CreateDateColumn,
  UpdateDateColumn, VersionColumn, ObjectIdColumn, ObjectID, BaseEntity
} from 'typeorm'

@Entity('componentsContent')
export class ComponentContent extends BaseEntity {

  @ObjectIdColumn()
  public id: ObjectID

  @Column('json')
  public content: any

  @Column('int')
  public componentId: number

  @CreateDateColumn()
  public createdAt: Date

  @UpdateDateColumn()
  public updatedAt: Date

  @VersionColumn()
  public version: number
}
```

the repository:
```
import { EntityRepository, MongoRepository, Repository } from "typeorm"
import { ComponentContent } from "./entity"

@EntityRepository(ComponentContent)
export class ComponentsContentRepository extends MongoRepository<ComponentContent> {
}
```

and the code which gives me the error:
```
const componentsContentRepository = connection.mongoManager.getCustomRepository(ComponentsContentRepository)
const newContent = new ComponentContent()
newContent.content = "content"
newContent.componentId = 1
await componentsContentRepository.save(newContent)
```
I tried both patterns active record and data mapper to save the data and the error is the same. Regarding the mysql connection, it works good.

Any idea how to solve this error ?

Thanks

**Comment by dotansimha** [comment] 2018-01-25 08:34
Try to use `mongodb@^2.2.33` in your app. 
The latest version (3) of the node mongo driver has a breaking changes to it's connect API.

**Comment by timoftealexandru** [comment] 2018-01-25 14:48
It worked with ```mongodb@^2.2.33```.
Thank you!

**Comment by pleerock** [comment] 2018-02-20 09:48
duplicate of #1449

**Closed by pleerock** 2018-02-20 09:48 UTC
