### ISSUE TITLE
Saving multiple entities with related objects at the same time does not work with cascade = true

### ISSUE THREAD

**Issue by darkbasic** [typeorm/typeorm#1551] opened 2018-02-04 14:36 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repository to reproduce the issue: https://github.com/darkbasic/typeorm-repro2

```
const chat1 = new Chat({
  allTimeMembers: [user1, user5],
  listingMembers: [user1, user5],
});
await connection.manager.save(chat1);

await connection.manager.save([
  new Message({
    chat: chat1,
    sender: user1,
    content: 'I should buy a boat',
    type: MessageType.TEXT,
    holders: [user1, user5],
    recipients: [
      new Recipient({
        user: user5,
      }),
    ],
  }),
  new Message({
    chat: chat1,
    sender: user1,
    content: 'You still there?',
    type: MessageType.TEXT,
    holders: [user1, user5],
    recipients: [
      new Recipient({
        user: user5,
      }),
    ],
  })
]);
```

If I save more entities at the same time (each one with realated objects and cascade set to true) it silently fails to insert them (it inserts only one of them).

The same exact code split into diffent calls works flawlessly:
```
const chat1 = new Chat({
  allTimeMembers: [user1, user5],
  listingMembers: [user1, user5],
});
await connection.manager.save(chat1);

await connection.manager.save(new Message({
  chat: chat1,
  sender: user1,
  content: 'I should buy a boat',
  type: MessageType.TEXT,
  holders: [user1, user5],
  recipients: [
    new Recipient({
      user: user5,
    }),
  ],
}));

await connection.manager.save(new Message({
  chat: chat1,
  sender: user1,
  content: 'You still there?',
  type: MessageType.TEXT,
  holders: [user1, user5],
  recipients: [
    new Recipient({
      user: user5,
    }),
  ],
}));
```

**Comment by darkbasic** [comment] 2018-02-04 14:46
I put a constructor in each class with something like that:
```
if (recipients) {
  this.recipients = recipients.map(recipient => ({...recipient, message: this}));
}
```

So I can load the sample data with a single call, without having to save dozens of variables all over the way:
```
await connection.manager.save(new Chat({
  messages: [
    new Message({
      recipients: [
        new Recipient(),
      ],
    }),
    new Message({
      recipients: [
        new Recipient(),
      ],
    }),
  ],
}));
```

**Comment by pleerock** [comment] 2018-02-05 08:12
Its a bug and fix will be released in `0.2.0-alpha.16`.

Some advances:

You have a data saved by cascades in which you have multiple primary keys which are referenced to another entities one of them is saved another is not, ahh soo complex. I strongly recommend you to keep things simple and avoid confusion for the ORM, yourself and people who is going to work with your code.

Also, be careful with such expression:

```ts
  this.recipients = recipients.map(recipient => ({...recipient, message: this}));
```

resulted object is instance of Object, not Recipient. This may lead to unexpected behaviour. Its much better to simply assign message property of recipient:

```ts
recipients.forEach(recipient => recipient.message = this);
this.recipients = recipients;
```

Also you have several other issues in your code like duplicate interface names and not exported interfaces. Thanks for the good repo, it would be great if you next time create a PR with a failing test like what I did here(5361167) with your code.

**Closed by pleerock** 2018-02-05 08:12 UTC
Labels: bug, comp: persistence

**Comment by darkbasic** [comment] 2018-02-05 09:16
> You have a data saved by cascades in which you have multiple primary keys which are referenced to another entities one of them is saved another is not, ahh soo complex. I strongly recommend you to keep things simple and avoid confusion for the ORM, yourself and people who is going to work with your code.

I know, that repo is part of a very big tutorial which I originally made with nosql in mind. Later we decided to move to postgresql and typeorm so I'm left with a weird db structure to start with. The priority is to get things working first, then make them right. Since I'm not really a sql guy (I mostly use nosqls) I would love if you could share your thoughts once I'll finish porting the whole codebase.

In the meantime I have another issue: if, after the first run, you comment out the insert query in the previous `repro2` repository and try to run it once again you'll get the following error:
```
{ QueryFailedError: column "userId" is in a primary key
    at new QueryFailedError (/home/niko/WebstormProjects/repro/repro2/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/home/niko/WebstormProjects/repro/repro2/src/driver/postgres/PostgresQueryRunner.ts:221:26)
    at Query.handleError (/home/niko/WebstormProjects/repro/repro2/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/niko/WebstormProjects/repro/repro2/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/home/niko/WebstormProjects/repro/repro2/node_modules/pg/lib/connection.js:117:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
  message: 'column "userId" is in a primary key',
  name: 'QueryFailedError',
  length: 101,
  severity: 'ERROR',
  code: '42P16',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '5673',
  routine: 'ATExecDropNotNull',
  query: 'ALTER TABLE "public"."recipient" ALTER COLUMN "userId" DROP NOT NULL',
  parameters: [] }
```

Any idea why?

**Comment by pleerock** [comment] 2018-02-05 09:18
> In the meantime I have another issue: if, after the first run, you comment out the insert query in the previous repro2 repository and try to run it once again you'll get the following error

yeah I saw it too, I fixed this issue as well, thanks for the report :)

**Comment by pleerock** [comment] 2018-02-05 10:23
I published typeorm@0.2.0-alpha.16 with those changes.

**Comment by darkbasic** [comment] 2018-02-05 10:43
I just tried it and it works flawlessly, thank you very much!

**Comment by darkbasic** [comment] 2018-02-05 21:15
How am I supposed to update a manytomany relationship?
```
const chat1 = await connection
  .createQueryBuilder(Chat, "chat")
  .whereInIds(1)
  .innerJoinAndSelect('chat.listingMembers', 'listingMembers')
  .getOne();
chat1!.id = chat.id;
chat1!.name = 'new name';
await connection.getRepository(Chat).update({id: chatId}, <Chat>chat1);
```
```
const chat2 = new Chat({name: 'test', listingMembers: [new User({name: 'test'})]});
await connection.getRepository(Chat).update({id: chat.id}, chat2);
```

Both don't work:
```
QueryFailedError: column "chatId" of relation "chat" does not exist
    at new QueryFailedError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/driver/postgres/PostgresQueryRunner.ts:221:26)
    at Query.handleError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/connection.js:117:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
```

**Comment by pleerock** [comment] 2018-02-06 04:40
you don't need to use `update` method. You load your entity with your relation, let's say chat with members, push new member and send chat entity to `save` method.

**Comment by darkbasic** [comment] 2018-02-06 17:14
I have `cascade` set to `true` in the `Message` entity:

```typescript
@OneToMany(type => Recipient, recipient => recipient.message, {cascade: true, eager: true})
  recipients: Recipient[];
```

Why do I have to manually remove all the related entities to be able to remove a message?

```typescript
await connection.getRepository(Message).remove(message);
```

gives me

```
(node:16117) UnhandledPromiseRejectionWarning: QueryFailedError: update or delete on table "message" violates foreign key constraint "fk_8a4c280bbc4f43cdd180b88cbb9" on table "recipient"
    at new QueryFailedError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/driver/postgres/PostgresQueryRunner.ts:221:26)
    at Query.handleError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/connection.js:117:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
(node:16117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:16117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So I tried to manually remove all related recipients first:

```typescript
const recipients = await connection
  .createQueryBuilder(Recipient, "recipient")
  .innerJoin('recipient.message', 'message', 'message.id = :messageId', {messageId: message.id})
  .getMany();
for (let recipient of recipients) {
  console.log(recipient);
  try {
    await connection.getRepository(Recipient).remove(recipient);
  } catch (e) {
    console.error(e);
  }
}
```

now I get:

```
Recipient { id: 1, receivedAt: null, readAt: null }
{ Error
    at new SubjectWithoutIdentifierError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/error/SubjectWithoutIdentifierError.ts:15:22)
    at /home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/persistence/SubjectExecutor.ts:384:27
    at Array.map (<anonymous>)
    at SubjectExecutor.<anonymous> (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/persistence/SubjectExecutor.ts:382:41)
    at step (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/typeorm/persistence/SubjectExecutor.js:32:23)
    at Object.next (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/typeorm/persistence/SubjectExecutor.js:13:53)
    at /home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/typeorm/persistence/SubjectExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/typeorm/persistence/SubjectExecutor.js:3:12)
    at /home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/persistence/SubjectExecutor.ts:380:83
  name: 'SubjectWithoutIdentifierError',
  message: 'Internal error. Subject Recipient must have an identifier to perform operation. Please report a github issue if you face this error.' }
(node:15587) UnhandledPromiseRejectionWarning: QueryFailedError: update or delete on table "message" violates foreign key constraint "fk_8a4c280bbc4f43cdd180b88cbb9" on table "recipient"
    at new QueryFailedError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/src/driver/postgres/PostgresQueryRunner.ts:221:26)
    at Query.handleError (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/home/niko/WebstormProjects/new-tutorial/whatsapp-server-express/node_modules/pg/lib/connection.js:117:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
(node:15587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:15587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It says `Internal error. Subject Recipient must have an identifier to perform operation. Please report a github issue if you face this error.`

**Comment by darkbasic** [comment] 2018-02-06 20:32
If you need some sample data to reproduce it:
```typescript
async function addSampleData() {
  const user1 = new User({
    username: 'ethan',
    password: '$2a$08$NO9tkFLCoSqX1c5wk3s7z.JfxaVMKA.m7zUDdDwEquo4rvzimQeJm', // 111
    name: 'Ethan Gonzalez',
    picture: 'https://randomuser.me/api/portraits/thumb/men/1.jpg',
    phone: '+391234567890',
  });
  await connection.manager.save(user1);

  const user2 = new User({
    username: 'bryan',
    password: '$2a$08$xE4FuCi/ifxjL2S8CzKAmuKLwv18ktksSN.F3XYEnpmcKtpbpeZgO', // 222
    name: 'Bryan Wallace',
    picture: 'https://randomuser.me/api/portraits/thumb/men/2.jpg',
    phone: '+391234567891',
  });
  await connection.manager.save(user2);

  const user3 = new User({
    username: 'avery',
    password: '$2a$08$UHgH7J8G6z1mGQn2qx2kdeWv0jvgHItyAsL9hpEUI3KJmhVW5Q1d.', // 333
    name: 'Avery Stewart',
    picture: 'https://randomuser.me/api/portraits/thumb/women/1.jpg',
    phone: '+391234567892',
  });
  await connection.manager.save(user3);

  const user4 = new User({
    username: 'katie',
    password: '$2a$08$wR1k5Q3T9FC7fUgB7Gdb9Os/GV7dGBBf4PLlWT7HERMFhmFDt47xi', // 444
    name: 'Katie Peterson',
    picture: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
    phone: '+391234567893',
  });
  await connection.manager.save(user4);

  const user5 = new User({
    username: 'ray',
    password: '$2a$08$6.mbXqsDX82ZZ7q5d8Osb..JrGSsNp4R3IKj7mxgF6YGT0OmMw242', // 555
    name: 'Ray Edwards',
    picture: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
    phone: '+391234567894',
  });
  await connection.manager.save(user5);

  const user6 = new User({
    username: 'niko',
    password: '$2a$08$fL5lZR.Rwf9FWWe8XwwlceiPBBim8n9aFtaem.INQhiKT4.Ux3Uq.', // 666
    name: 'Niccolò Belli',
    picture: 'https://randomuser.me/api/portraits/thumb/men/4.jpg',
    phone: '+391234567895',
  });
  await connection.manager.save(user6);

  const user7 = new User({
    username: 'mario',
    password: '$2a$08$nDHDmWcVxDnH5DDT3HMMC.psqcnu6wBiOgkmJUy9IH..qxa3R6YrO', // 777
    name: 'Mario Rossi',
    picture: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
    phone: '+391234567896',
  });
  await connection.manager.save(user7);




  await connection.manager.save(new Chat({
    allTimeMembers: [user1, user3],
    listingMembers: [user1, user3],
    messages: [
      new Message({
        sender: user1,
        content: 'You on your way?',
        createdAt: moment().subtract(1, 'hours').unix(),
        type: 1,
        holders: [user1, user3],
        recipients: [
          new Recipient({
            user: user3,
          }),
        ],
      }),
      new Message({
        sender: user3,
        content: 'Yep!',
        createdAt: moment().subtract(1, 'hours').add(5, 'minutes').unix(),
        type: 1,
        holders: [user1, user3],
        recipients: [
          new Recipient({
            user: user1,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user1, user4],
    listingMembers: [user1, user4],
    messages: [
      new Message({
        sender: user1,
        content: 'Hey, it\'s me',
        createdAt: moment().subtract(2, 'hours').unix(),
        type: 1,
        holders: [user1, user4],
        recipients: [
          new Recipient({
            user: user4,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user1, user5],
    listingMembers: [user1, user5],
    messages: [
      new Message({
        sender: user1,
        content: 'I should buy a boat',
        createdAt: moment().subtract(1, 'days').unix(),
        type: 1,
        holders: [user1, user5],
        recipients: [
          new Recipient({
            user: user5,
          }),
        ],
      }),
      new Message({
        sender: user1,
        content: 'You still there?',
        createdAt: moment().subtract(1, 'days').add(16, 'hours').unix(),
        type: 1,
        holders: [user1, user5],
        recipients: [
          new Recipient({
            user: user5,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user3, user4],
    listingMembers: [user3, user4],
    messages: [
      new Message({
        sender: user3,
        content: 'Look at my mukluks!',
        createdAt: moment().subtract(4, 'days').unix(),
        type: 1,
        holders: [user3, user4],
        recipients: [
          new Recipient({
            user: user4,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user2, user5],
    listingMembers: [user2, user5],
    messages: [
      new Message({
        sender: user2,
        content: 'This is wicked good ice cream.',
        createdAt: moment().subtract(2, 'weeks').unix(),
        type: 1,
        holders: [user2, user5],
        recipients: [
          new Recipient({
            user: user5,
          }),
        ],
      }),
      new Message({
        sender: user5,
        content: 'Love it!',
        createdAt: moment().subtract(2, 'weeks').add(10, 'minutes').unix(),
        type: 1,
        holders: [user2, user5],
        recipients: [
          new Recipient({
            user: user2,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user1, user6],
    listingMembers: [user1],
  }));

  await connection.manager.save(new Chat({
    allTimeMembers: [user2, user1],
    listingMembers: [user2],
  }));

  await connection.manager.save(new Chat({
    name: 'Ethan\'s group',
    picture: 'https://randomuser.me/api/portraits/thumb/lego/1.jpg',
    allTimeMembers: [user1, user3, user4, user6],
    listingMembers: [user1, user3, user4, user6],
    actualGroupMembers: [user1, user4, user6],
    admins: [user1, user6],
    owner: user1,
    messages: [
      new Message({
        sender: user1,
        content: 'I made a group',
        createdAt: moment().subtract(2, 'weeks').unix(),
        type: 1,
        holders: [user1, user3, user4, user6],
        recipients: [
          new Recipient({
            user: user3,
          }),
          new Recipient({
            user: user4,
          }),
          new Recipient({
            user: user6,
          }),
        ],
      }),
      new Message({
        sender: user1,
        content: 'Ops, Avery was not supposed to be here',
        createdAt: moment().subtract(2, 'weeks').add(2, 'minutes').unix(),
        type: 1,
        holders: [user1, user4, user6],
        recipients: [
          new Recipient({
            user: user4,
          }),
          new Recipient({
            user: user6,
          }),
        ],
      }),
      new Message({
        sender: user4,
        content: 'Awesome!',
        createdAt: moment().subtract(2, 'weeks').add(10, 'minutes').unix(),
        type: 1,
        holders: [user1, user4, user6],
        recipients: [
          new Recipient({
            user: user1,
          }),
          new Recipient({
            user: user6,
          }),
        ],
      }),
    ],
  }));

  await connection.manager.save(new Chat({
    name: 'Ray\'s group',
    allTimeMembers: [user3, user6],
    listingMembers: [user3, user6],
    actualGroupMembers: [user3, user6],
    admins: [user6],
    owner: user6,
  }));
}
await addSampleData();
```

**Comment by darkbasic** [comment] 2018-02-06 22:37
I also pushed a new commit to more easily reproduce the issue:
https://github.com/darkbasic/typeorm-repro2/commit/5a9b274274b1fb8f800e46a279c75bd75558f8c0

**Comment by pleerock** [comment] 2018-02-07 05:48
@darkbasic can you please create a PR with a failing test this time? Also try to provide a minimal as possible reproduction example, so I can faster get into your code and find a problem.

**Comment by darkbasic** [comment] 2018-02-07 08:39
> @darkbasic can you please create a PR with a failing test this time?

Of course, I'll make a PR.

> Also try to provide a minimal as possible reproduction example, so I can faster get into your code and find a problem.

The repro is already pretty minimal, I just included more sample data in case it was needed later. I removed it:
https://github.com/darkbasic/typeorm-repro2/commit/14bfc8d6552850aea68e342556eb1c92882fd45a

**Comment by darkbasic** [comment] 2018-02-12 09:31
Hi @pleerock , any news on this?

**Comment by pleerock** [comment] 2018-02-16 05:33
I checked your tests and skipped them. Reason why they are failing is because cascade remove functionality is not supported. You either need to configure how foreign keys will be removed using `onDelete` flag on relations (SQL's `ON DELETE`) either by calling `remove` on everything that is "bind" to your removal entity.

**Comment by darkbasic** [comment] 2018-02-16 10:25
> Reason why they are failing is because cascade remove functionality is not supported.

`cascade?: boolean | ("insert" | "update" | "remove")[];`

What is this `cascade: ["remove"]` that appears in the types documentation about?

Anyway this was about cascade remove, what about the third test, the one which tries to delete the Recipients themselves? When trying to perform
```
await connection.getRepository(Recipient).remove(recipient);
```
I get:
```
Internal error. Subject Recipient must have an identifier to perform operation. Please report a github issue if you face this error.
```

**Comment by pleerock** [comment] 2018-02-16 11:14
> What is this cascade: ["remove"] that appears in the types documentation about?

Something that needs design and implementation, but currently not supported.

> await connection.getRepository(Recipient).remove(recipient);

can you console.log(recipient) ? I guess it misses one of the primary key. It must contain `user` and `message` to finish operation.

**Comment by darkbasic** [comment] 2018-02-16 11:51
> can you console.log(recipient) ? I guess it misses one of the primary key. It must contain user and message to finish operation.

That was the issue: one of the primary keys was missing from the retrieved object. Thanks.
