### ISSUE TITLE
Duplicate correlation name on self reference

### ISSUE THREAD

**Issue by iamgmd** [typeorm/typeorm#2268] opened 2018-06-04 10:44 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[] `0.x.x` (or put your version here)

I have two entities, Solution and SolutionComponent. All in all, I am struggling to get the correct result whether or not I use queryBuilder or entityManager in 0.2.6 so I have tried to use 0.3.0 using the new typesafe approach but get "Error: The correlation name 'SolutionComponent' is specified multiple times in a FROM clause." on a self referencing entity.

Solution

```
  @OneToMany(() => SolutionComponent, solutionComponent => solutionComponent.solutionid_ref)
  @JoinColumn({ name: "solutionid" })
  solutioncomponent_refs: [SolutionComponent];
```

SolutionComponent

```
  @ManyToOne(() => Solution, solution => solution.solutioncomponent_refs)
  @JoinColumn({ name: "solutionid" })
  solutionid_ref: [Solution];

  @OneToOne(() => SolutionComponent, solutioncomponent => solutioncomponent.rootsolutioncomponentid_ref)
  @JoinColumn({ name: "rootsolutioncomponentid" })
  rootsolutioncomponentid_ref: SolutionComponent;

```

Query

```
      const records = await connection.manager
        .findOne(Solution, {
          select: selection,
          where: { solutionid: `${solutionid}` },
          relations: {
            solutioncomponent_refs: {
              rootsolutioncomponentid_ref: true
            }
          }
        })
        .catch(error => {
          connection.close();
          throw error as Error;
        });
```

Error

Error: The correlation name 'SolutionComponent' is specified multiple times in a FROM clause.

It seems that the correlation name is being set to the entity name, is there a way to specify the alias for the correlation name on the query or have the entityManager automatically create an alternative alias / correlation name?

As another observation, if this query was to run it would create 3 T-SQL commands using ("IN") where in 0.2.6 it would create 1 T-SQL command using ("LEFT-JOIN"). Obviously, the 1 T-SQL command is more performant than 3 and can mean the difference between 1 minute and 1.5 seconds of execution. I know this because I was experiencing the exact same problem using vesper.

**Comment by pleerock** [comment] 2018-06-04 10:59
> Obviously, the 1 T-SQL command is more performant than 3 and can mean the difference between 1 minute and 1.5 seconds of execution

how did you get such results? Actually joins with selections are much much less performant if you have lot of data to fetch. Can you provide some tests or repos which confirm what you are saying? 

> It seems that the correlation name is being set to the entity name, is there a way to specify the alias for the correlation name on the query or have the entityManager automatically create an alternative alias / correlation name?

you don't have to specify aliases with find options - orm generates aliases for you.

0.3.0 find options syntax is new and it may have issues, can you please help us to develop it better, find and resolve issues? If yes then it would be great to have a failing test against next branch that reproduces issue you have (also please use simpler names and minimal reproduction code without something not related to the issue)?

**Comment by Kononnable** [comment] 2018-09-29 07:36
Closing as no answer from the reporter.

**Closed by Kononnable** 2018-09-29 07:36 UTC

**Comment by oskarious** [comment] 2019-06-12 13:15
I have been running into the same issue.

My entity looks like this:
```
@Entity()
export class Organization {
  @PrimaryGeneratedColumn()
  id!: number;

  @ManyToOne(() => Organization, org => org.children)
  @JoinColumn()
  parent!: Organization;

  @OneToMany(() => Organization, org => org.parent, { cascade: true })
  children!: Organization[];
}
```

and then fetching with: 

```
getManager().find(Organization, {
      relations: { parent: true },
    });
```

Yields error: `table name "Organization" specified more than once` since it uses the same alias for the base `Organization` entity and the inner join entity.

I am on version: `0.3.0-alpha.23` and am using postgres
