### ISSUE TITLE
ErrorStack: QueryFailedError: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by woolson** [typeorm/typeorm#6414] opened 2020-07-17 06:51 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.21`

**Steps to reproduce or a small repository showing the problem:**

1. I got this error when some query failed. Is this error handle inside typeorm?
2. This error may cause this connection break. Should I createConnection manually?
3. If this error repeat after 10(connect pool default connections) times. I will disconnect with mysql server until restart my application?

Thank you.

```
ErrorStack: QueryFailedError: Cannot enqueue Query after fatal error.
--
  | Jul 17, 2020 @ 12:06:25.336 | at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
  | Jul 17, 2020 @ 12:06:25.336 | at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
  | Jul 17, 2020 @ 12:06:25.336 | at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
  | Jul 17, 2020 @ 12:06:25.336 | at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
  | Jul 17, 2020 @ 12:06:25.336 | at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
  | Jul 17, 2020 @ 12:06:25.336 | at /app/node_modules/mysql/lib/protocol/Protocol.js:236:14
  | Jul 17, 2020 @ 12:06:25.336 | at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by imnotjames** [comment] 2020-08-10 02:38
1. This is a MySQL node module error, not TypeORM.
2. This error means that the connection must be restarted.
3. Not sure I understand what you're mean here.  Are you trying to reconnect after a fatal error to clear up there error?

**Comment by woolson** [comment] 2020-08-10 03:07
**1. I mean Should it be handled inside TypeORM.**
2. You are right.
3. You can ignore this question. Sorry!

In general, Should TypeORM restart the connection when the error happened？Because of TypeORM manage connections.

@imnotjames Thank you for your replay.😃

**Comment by imnotjames** [comment] 2020-10-08 20:15
Maybe related - #2666

**Comment by imnotjames** [comment] 2021-07-04 17:54
> **1. I mean Should it be handled inside TypeORM.**
> 2. You are right.
> 3. You can ignore this question. Sorry!
> 
> In general, Should TypeORM restart the connection when the error happened？Because of �TypeORM manage connections.
> 
> @imnotjames Thank you for your replay.😃

I believe you just need to release this query runner.

**Comment by imnotjames** [comment] 2021-07-04 17:54
Closing as duplicate of #2666 otherwise

**Closed by imnotjames** 2021-07-04 17:54 UTC
Labels: driver: mariadb, driver: mysql, question
