### ISSUE TITLE
"enum" Column type breaks schema sync when using PostgreSQL

### ISSUE THREAD

**Issue by mdziekon** [typeorm/typeorm#671] opened 2017-07-15 10:47 UTC
TypeORM Version: "0.1.0-alpha.32"

Currently it's not possible to use ``@Column({ type: "enum", ... })`` in PostgreSQL when using schema auto sync, because it will throw this error:
```
Error: type "enum" does not exist
```

Here's the query that generates this error:
```sql
CREATE TABLE "my_table" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "type" enum NOT NULL,
    "myvar" character varying(64) NOT NULL,
    "myvar2" character varying(255) NOT NULL,
    "foreign_id" integer
)
```

Example type definition:
```typescript
@Column({
    type: "enum",
    enum: [
        "typeA",
        "typeB",
        "typeC"
    ]
})
type: "typeA" | "typeB" | "typeC";
```

As far as I know, PostgreSQL does not have "native" ENUM type, but you can create it yourself as a new type.

TypeORM should either use that feature, or it should be documented that ``enum`` type is forbidden when using PostgreSQL. It of course might be a case where I'm misusing this feature, but I think there is no documentation of that at all.

**Comment by pleerock** [comment] 2017-07-15 17:39
enum is supported only on mysql at the moment.

> PostgreSQL does not have "native" ENUM type, but you can create it yourself as a new type.

right, because typeorm only support "native" database types and enum type in postgres is more advanced thing to create. We will implement enums for postgres as well, but in the future (you can try it on your own if you want)

**Comment by mdziekon** [comment] 2017-07-16 05:13
Cool, any chance for some sort of "warning" (even a runtime one would be a good thing, but hey, we have types...) for now, or at least stating that it's "mysql only atm" in documentation?

**Comment by AlexMesser** [comment] 2018-02-28 16:01
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Closed by AlexMesser** 2018-02-28 16:01 UTC
Labels: comp: schema sync, enhancement

**Comment by tonyxiao** [comment] 2018-03-09 15:13
@AlexMesser  where can i find breaking changes in `typeorm@next` (if any)

**Comment by pleerock** [comment] 2018-03-09 17:31
https://github.com/typeorm/typeorm/blob/next/CHANGELOG.md

**Comment by papasconlimon** [comment] 2018-04-04 22:42
can i use a enum instead of a number and indicate the type as small int? like:

`
@Column("smallint")
Estatus: number;
`

this is for internally use a the column like a normal smallint, but using the enum for a more clean code.

**Comment by PavanBahuguni** [comment] 2018-04-22 06:37
I have a column in an entity with type 'enum' as following: Where Action is an enum
`
@Column({name: 'action', type: 'enum', enum: ['add', 'update', 'delete']})
    action: Action;
`
The quarries executed are as follows.
```
CREATE TYPE "test"."datasource_action_action_enum" AS ENUM('add', 'update', 'delete')
ALTER TABLE "test"."datasource_action" ADD "action" "datasource_action_action_enum" NOT NUL
```
and it errors with **type "datasource_action_action_enum" does not exist**

I think the the ALTER query should have been as follows.
ALTER TABLE "test"."datasource_action" ADD "action" "test"."datasource_action_action_enum" NOT NUL

**Comment by pleerock** [comment] 2018-04-23 06:05
@PavanBahuguni  what version are you using? Can you try 0.2.0 ?

**Comment by PavanBahuguni** [comment] 2018-04-23 07:03
@pleerock Having same issue in 0.2.0 as well.

**Comment by pleerock** [comment] 2018-04-23 07:13
then create a separate issue with reproduction example please

**Comment by PavanBahuguni** [comment] 2018-04-23 12:41
Created issue [https://github.com/typeorm/typeorm/issues/1997](1997)
