### ISSUE TITLE
SelectQueryBuilder set properties

### ISSUE THREAD

**Issue by ValiDraganescu** [typeorm/typeorm#5358] opened 2020-01-15 17:57 UTC
**Steps to reproduce or a small repository showing the problem:**

I have an entity that has an `isPublished` boolean property, when I try to do a query to update this value and set it false I get the following compiler error:

```
Argument of type '{ isPublished: false; }' is not assignable to parameter of type 'QueryDeepPartialEntity<Post>'.
  Property 'isPublished' is incompatible with index signature.
    Type 'false' is not assignable to type '(() => string) | QueryDeepPartialEntity<{}>[] | ReadonlyArray<QueryDeepPartialEntity<{}>> | QueryDeepPartialEntity<any> | undefined'.

15       .set({isPublished: false})
```

The executed query is
```
await repo.createQueryBuilder()
      .update(Post)
      .set({isPublished: false})
      .execute();
  };
```

**Comment by swim** [comment] 2020-01-16 01:39
Can you please include the Post model?

**Comment by ValiDraganescu** [comment] 2020-01-16 09:26
Here it is

```
@Entity("post")
export class Post extends TlBaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: "varchar",
    length: 256
  })
  link: string;

  @Column({
    type: "tinyint",
    transformer: new BooleanTransformer()
  })
  isPublished: boolean;

  @OneToMany(type => PostTranslation, postTranslation => postTranslation.post)
  postTranslations: Array<PostTranslation>;

  @OneToMany(type => Business, business => business.post)
  businesses: Array<Business>;
}
```

**Comment by imnotjames** [comment] 2020-10-15 04:56
Cannot replicate with the following:

```
import {Entity} from "../../../../../src/decorator/entity/Entity";
import {Column} from "../../../../../src/decorator/columns/Column";
import {PrimaryGeneratedColumn} from "../../../../../src";

@Entity("post")
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "varchar",
        length: 256
    })
    link: string;

    @Column({
        type: "tinyint",
    })
    isPublished: boolean;
}
```

Had to modify your code to run it.

Can you create a minimally reproducible example?  Something I can run without any other dependencies.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2021-06-19 04:40
Without feedback we can't replicate.  Closing this issue.

**Closed by imnotjames** 2021-06-19 04:40 UTC
Labels: bug, driver: mariadb, driver: mysql, needs more info
