### ISSUE TITLE
ENUM error : synchroize doesn't  check if enumtype already exists in postgres

### ISSUE THREAD

**Issue by jeromeSH26** [typeorm/typeorm#5738] opened 2020-03-22 09:10 UTC
[ ] bug report
[ ] `postgres`

when synchronise is on, typeorm doesn't check if a enum type already exists when using "enumName" .

I guess a IF NO EXISTS is missing somewhere

```

	@Column({
		type: "enum",
		nullable: false,
		enum: ECountry,
		enumName: "ecountry",
		default: ECountry.TODEFINED,
	})
	countryBudget: ECountry;
```

error is the following (type already exists)

```
query failed: CREATE TYPE "ecountry" AS ENUM('FR', 'GR', 'TODEFINED')
error: error: le type « ecountry » existe déjà
    at Connection.parseE (C:\Users\asterix\dev\DWP_BUDGET\node_modules\pg\lib\connection.js:614:13)
    at Connection.parseMessage (C:\Users\asterix\dev\DWP_BUDGET\node_modules\pg\lib\connection.js:413:19)
    at Socket.<anonymous> (C:\Users\asterix\dev\DWP_BUDGET\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 157,
  severity: 'ERREUR',
  code: '42710',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\commands\\typecmds.c',
  line: '1186',
  routine: 'DefineEnum'
}
```

**Comment by imnotjames** [comment] 2020-10-15 06:42
Duplicate of #5748

**Closed by imnotjames** 2020-10-15 06:42 UTC
Labels: bug, comp: schema sync

**Comment by trongrg** [comment] 2020-12-03 08:41
@imnotjames 

I still got this error in 0.2.29, and your linked dupliate issue is "Update dependency mkdirp to 1.x"

**Comment by tpiecora** [comment] 2020-12-12 20:46
Why is this closed?

**Comment by nebkat** [comment] 2020-12-13 21:42
GitHub autocomplete seems to have a strange behavior where it selects a completely different issue number than the one you typed, and I presume that's what has happened here. Correct one is below.

Duplicate of #5648.

**Comment by Distortedlogic** [comment] 2022-01-26 05:11
bump

**Comment by sepiette** [comment] 2022-04-13 20:57
Also running into this issue after squashing migrations. Does anyone have solutions for a workaround?

**Comment by Distortedlogic** [comment] 2022-04-13 21:45
> Does anyone have solutions for a workaround?

I have been manually editing the migrations files after generation

**Comment by sepiette** [comment] 2022-04-14 14:17
> > Does anyone have solutions for a workaround?
> 
> I have been manually editing the migrations files after generation

@Distortedlogic for things like `CREATE TYPE ...` what does your query look like? Any examples would be helpful! Are you just updating the `queryRunner.query(...)` command or doing something else??

**Comment by sepiette** [comment] 2022-04-14 15:36
Thanks @Distortedlogic! I might be dealing with something a little different - I'm currently trying to squash my migrations into 1 file as we're dealing with some performance issues, however the `CREATE TYPE` migrations are saying things like "type "member_cancellation_status_enum" already exists even if only declared once. Totally makes sense why since the enums still exist in the DB, but I basically need a CREATE IF NOT EXISTS (which query runner keeps saying is invalid).

**Comment by jzhao-30** [comment] 2025-02-03 05:24
Same problem today, is the bug still exist? It is really terrible to manually change it everytime
