### ISSUE TITLE
0.2.20 release breaks entity repo resolving mechanism

### ISSUE THREAD

**Issue by sevenryze** [typeorm/typeorm#4967] opened 2019-10-24 13:52 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[*] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Before the 0.2.20 release, e.g. 0.2.19, we could use this kind of code to specify a count column in db:
```ts
  @Index()
  @Column({
    comment: "The count, without setting default option!"
  })
  private count: number = 0;
```

Everything works as expected, until the latest version released.

For now, if you use 0.2.20 version, during the db initialization stage, ORM will give the error like this:
```
The field `count` default value has not been set. 
```

I highly recommend listing this as a breaking warning as it's a big breaks for code.
Or, is it a regression bug introducing by accident?

**Comment by antoine-pous** [comment] 2019-10-24 14:30
I don't find the way you're using to assign default value into the documentation :thinking: 

Then you've probaby misused the defaut value assignation, IMO this is not really a bug/breaking change if it's not used the way it was designed for

**Comment by sevenryze** [comment] 2019-10-24 14:34
So what did you mean that I should rely on the `default` option in the
@column decorator rather than the default JS class field feature to specify
the default value for a field?
Best regards
Seven Ryze

**Comment by pleerock** [comment] 2019-10-24 17:54
We are trying not to introduce a breaking changes. Are you sure this error comes from TypeORM? Can you provide a stack trace of this error? Where exactly this errors comes?

**Comment by sevenryze** [comment] 2019-10-25 01:31
@pleerock yes, I'm sure to say that's typeorm's breaking change.

I dig some, I believe this issue is caused by #4804 PR, which breaks the repository metadata resolving logic. 

```ts
protected findMetadata(target: Function|EntitySchema<any>|string): EntityMetadata|undefined {
        return this.entityMetadatas.find(metadata => {
            if (typeof metadata.target === "function" && typeof target === "function" && metadata.target.name === target.name) {  // <--- See this? Mark 1
                return true;
            }
            if (metadata.target === target) {
                return true;
            }
            if (target instanceof EntitySchema) {
                return metadata.name === target.options.name;
            }
            if (typeof target === "string") {
                if (target.indexOf(".") !== -1) {
                    return metadata.tablePath === target;
                } else {
                    return metadata.name === target || metadata.tableName === target;
                }
            }

            return false;
        });
    }
```

This logic is too open to resolve, e.g., if we have two different entities defined with the same class name - User. Then the `metadata.target.name === target.name` will be true even when comparing the first User with the second User, which is totally different. So every time we need the second User, this logic is gonna give us the first User, which is definitely wrong.

Could you check that? I think we at least shouldn't use name as the comparing anchor as it's too easy to collide.

If you agree with me, I could give a PR to fix that, but i'm not sure what's the purpose of the #4804 .

**Comment by sevenryze** [comment] 2019-10-25 01:33
@antoine-pous Please check my comment upon, I believe it's a bug.

**Comment by sevenryze** [comment] 2019-10-25 01:35
I changed the title to reflect the real issue.

**Comment by silentroach** [comment] 2019-10-25 07:19
#4940

**Comment by sevenryze** [comment] 2019-10-25 08:19
@silentroch definitely, the object reference should always be respected in the first priority as it’s the strongest anchor symbols in terms of the language level. 

I saw maintainer’s replies for you, that doesn’t make too much sense for me as you cannot introduce a break change only relying on the rare or not. 

We of course have some cases that we define the classes with the same name, same connection and the ORM shouldn’t force users not do that. 

Think about I contributed for this repo several times about binary values as key and column, it’s definitely rare usages but I always think I need to push PRs for that, instead just making a local copy for myself, cause I believe typeORM should be a global and responsible project.

**Comment by josephmulholland** [comment] 2019-10-28 18:16
This is causing problems for me as well.

I've got two "Application" entities, one with schema: "account" and another with schema: "payment"

Due to the above changes references to "Application" always resolve to only one of the entities, regardless of which one is actually supplied.

I don't think it's that uncommon to have entities with the same name across different schemas.

**Comment by sevenryze** [comment] 2019-11-01 01:18
hey, How's the going?

**Comment by silentroach** [comment] 2019-11-01 01:20
#3267

**Comment by sevenryze** [comment] 2019-11-01 01:26
@silentroach I can give the PR, no need from maintainers to do that, but this issue is a little bit controversial so i prefer to get the intention of maintainers to prevent the useless work.

**Comment by leonardofalk** [comment] 2019-11-04 12:15
I can also confirm that this affects minified builds as uglifier try to mangle class names. In react-native all our models are different in name and metadata, but after build release they are not.

**Comment by pleerock** [comment] 2019-11-04 13:28
> #3267 here is a long discussion about package death

@silentroach if you are going to continue to be toxic in every issue then this repository isn't for you.

> for me it is a very strange behavior that you pass some class reference and get repository for another, but they think it is ok 🤷‍♂

> definitely, the object reference should always be respected in the first priority as it’s the strongest anchor symbols in terms of the language level.

unfortunately it's not always true. And its especially sensed once you have serverless / lambda / microservices / monorepo / shared with browser or electron architectures and environments. Yes, in most simple projects you wouldn't have this problem because you have only one node_modules, one representation of your entity and its symbol, one running process. But for those who organizing listed projects this is a big issue.

My suggestion to resolve this issue is to match by table path ("database"."schema"."table_name"). I'm not sure if it won't bring any other problems for other users but from what I see it covers all three listed cases. Feel free to suggest something better.

**Comment by silentroach** [comment] 2019-11-04 18:17
> serverless / lambda / microservices / monorepo / shared with browser or electron architectures and environments

so you break (and it is not so easy to find why) all just to fix these rare cases?

**Comment by pleerock** [comment] 2019-11-05 10:12
> so you break (and it is not so easy to find why) all just to fix these rare cases?

If you still didn't get it nobody wanted to break anything. But yes, it broke use case with multiple schemas, and in my opinion it's more rare case than serverless / lambda / microservices / monorepo / shared with browser or electron architectures and environments. And yes, we still can fix it and make both cases to work.

**Comment by silentroach** [comment] 2019-11-05 10:20
In my case I have two entities with the same name in same schema, just not to fetch extra fields in some cases.

If I pass class reference to the function, I expect that I get repository for it, but not for other. If you want to use function name or key like database + schema + table name, there should be an error on initialization if user have two entities with the same key.

**Comment by Wintereise** [comment] 2019-11-05 10:54
I think PR https://github.com/typeorm/typeorm/pull/4804 may have been misguided.

See my comments at https://github.com/typeorm/typeorm/issues/3427#issuecomment-549770047

**Comment by sevenryze** [comment] 2019-11-08 20:54
@pleerock the `("database"."schema"."table_name")` way should resolve my problem as I always manually set the entity name by hand. But I don't know if that breaks the other areas.

What's your thought? should I make a PR for this method? or we just revert the PR #4804 and try another way to resolve the lambda issue?

**Comment by pleerock** [comment] 2019-11-14 00:23
Go ahead for PR. At least I don't see any problem this solution bring. But we can never predict and I hope if we do and merge this change nobody will yell at me again about merging a breaking changes.
Would be great if you add a check @silentroach asking for

**Comment by EgorGumin** [comment] 2020-01-10 22:21
There is another issue with this method
```ts
protected findMetadata(target: Function|EntitySchema<any>|string): EntityMetadata|undefined {
        return this.entityMetadatas.find(metadata => {
            if (typeof metadata.target === "function" && typeof target === "function" && metadata.target.name === target.name) {  // <--- See this? Mark 1
                return true;
            }
            if (metadata.target === target) {
                return true;
            }
            if (target instanceof EntitySchema) {
                return metadata.name === target.options.name;
            }
            if (typeof target === "string") {
                if (target.indexOf(".") !== -1) {
                    return metadata.tablePath === target;
                } else {
                    return metadata.name === target || metadata.tableName === target;
                }
            }

            return false;
        });
    }
```

This part
```ts
metadata.tableName === target
```

leads to the same issue when you define two Entity Schemas pointing to the same table and one of the schemas has the same name as a db table.
For example, if you have 
**User Schema**
```
...
name: "user",
tableName: "user"
...
```

**Player Schema**
```
...
name: "player",
tableName: "user"
...
```

You can get the wrong type because entityMetadata with a wrong name but the same tableName can appear before entityMetadata with the correct name

**Comment by millsmcilroy** [comment] 2020-02-29 10:24
@sevenryze Can you verify that the latest release 0.2.24 reverting #4804 resolves this issue?

**Comment by imnotjames** [comment] 2020-10-02 16:28
I'm gonna close this as it seems to have been resolved.

**Closed by imnotjames** 2020-10-02 16:28 UTC
