### ISSUE TITLE
Specifying Column Length in Type Results in Column Recreation During Column Change

### ISSUE THREAD

**Issue by adamlarsonlee** [typeorm/typeorm#9254] opened 2022-08-01 20:18 UTC
## Issue Description

In Postgres, when a column type is specified with the length (i.e. character varying(18)), any change to that column that doesn't explicitly specify the length results in a drop/add of the column which incurs data loss. For example, let's say a table was created as follows:

```typescript
import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class testCreateTable implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'test_table',
        columns: [
          {
            name: 'id',
            type: 'int',
            isPrimary: true,
          },
          {
            name: 'something',
            type: 'character varying(18)',
            isNullable: false,
          },
        ],
      })
    );
  }
}
```

Later if we change the column like so (make it nullable):

```typescript
import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class testChangeColumn implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'character varying(18)',
        isNullable: true,
      })
    );
  }
}
```

It will result in the column being dropped and recreated. The reason for this is that [one of the things that triggers column recreation is a change in length](https://github.com/typeorm/typeorm/blob/486f8c582170dbadbd875e00d09d26359b2fd8be/src/driver/postgres/PostgresQueryRunner.ts#L792):

```typescript
if (oldColumn.type !== newColumn.type
            || oldColumn.length !== newColumn.length
            || newColumn.isArray !== oldColumn.isArray
            || (!oldColumn.generatedType && newColumn.generatedType === "STORED")
            || (oldColumn.asExpression !== newColumn.asExpression && newColumn.generatedType === "STORED")) {
            // To avoid data conversion, we just recreate column
            await this.dropColumn(table, oldColumn);
            await this.addColumn(table, newColumn);
```

I think that's fine (and there are other issues to change the behaviour) but in this case we aren't actually changing the length at all. How this happens is the column length is not specified using the length property of the table column, which gives us an undefined length. Then when the table is loaded the column has a length of 18. The lengths are mismatched and the column is recreated.

I believe we should NOT compare the lengths if one isn't provided by the new column definition, i.e.:

```typescript
newColumn.length && oldColumn.length !== newColumn.length
```

### Expected Behavior

The table column is not recreated if the length is not explicitly specified in the migration to change the column.

### Actual Behavior

The table column is dropped and recreated even though we aren't changing the column length, resulting in data loss.

```
query: ALTER TABLE "test_table" DROP COLUMN "something"
query: ALTER TABLE "test_table" ADD "something" character varying(18)
```

### Steps to Reproduce

1. Create a table with a column that specifies the length directly in the type (not nullable)
2. Change the column in a way that should not result in recreation (make it nullable)
3. The second migration will cause the column to be dropped and recreated, resulting in data loss

```typescript
import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class testCreateTable implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'test_table',
        columns: [
          {
            name: 'id',
            type: 'int',
            isPrimary: true,
          },
          {
            name: 'something',
            type: 'character varying(18)',
            isNullable: false,
          },
        ],
      })
    );
  }
}
```

```typescript
import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class testChangeColumn implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'character varying(18)',
        isNullable: true,
      })
    );
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.5.4  | 
| TypeORM version     | 2.4.5 | 

Note: This problem looks to exist in the current version of TypeORM as well.

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment] 2022-09-03 15:00
Duplicate of #3357

**Closed by AlexMesser** 2022-09-03 15:00 UTC
Labels: bug, requires triage
