### ISSUE TITLE
Making TypeORM Drivers extendable/customizable

### ISSUE THREAD

**Issue by codessentials** [typeorm/typeorm#2318] opened 2018-06-11 10:53 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `all`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to propose to "split-out" the TypeORM storage Drivers and make them extendable and/or customisable. 

Steps to implement:
1) Create an ```@Driver``` decorator, which will be added to all existing Driver implementations in /typeorm/tree/master/src/driver   

For example:

```
@Driver('sqlite3')
export class SqliteDriver extends AbstractSqliteDriver { 
```
2) The ```@Driver``` decorator then can register the driver with the DriverFactory.

3) In /typeorm/blob/master/src/driver/DriverFactory.ts at ```create(connection: Connection): Driver``` you can get the driver by name from a registered driver map in DriverFactory.

Anyone could make his own driver, decorate it with ```@Driver('custom-name')``` and use that driver.

We could revive WebSql driver for Ionic in-browser development.
We could easily create a modified version of any of the existing drivers and use that.
We might even create an IndexedDB driver?

**Comment by codessentials** [comment] 2018-06-12 15:03
Hi, I reduced the complexity for this feature request for two reasons (see bottom).

I know it is more than likely that I overlooked some impact but I managed to pull the WebSQL driver from a previous release, add it to my own project as 'custom driver' and get it working with only about 10 lines of code changed in DriverFactory.ts. These changes allow to configure any custom driver to be usable by TypeORM (i guess/hope)

**Can you please have a look at my changes** and tell me if it is possible to incorporate them in one of the next releases? Please look for comments (1), (2) and (3).

```
/**
 * Helps to create drivers.
 */
export class DriverFactory {

    private static readonly driverTypes: { [key: string]: any } = {};  // (1) I added a driverType object

    /**
     * Creates a new driver depend on a given connection's driver type.
     */
    create(connection: Connection): Driver {
        const type = connection.options.type;

        const driverType = DriverFactory.driverTypes[type]; // (2) I do a search for any registered driverType
        if (driverType) {
            return new driverType(connection); // (2) if found, I return a custom driver class instance
        }

        switch (type) {
            case "mysql":
                return new MysqlDriver(connection);
            case "postgres":
                return new PostgresDriver(connection);
            case "mariadb":
                return new MysqlDriver(connection);
            case "sqlite":
                return new SqliteDriver(connection);
            case "cordova":
                return new CordovaDriver(connection);
            case "react-native":
                return new ReactNativeDriver(connection);
            case "sqljs":
                return new SqljsDriver(connection);
            case "oracle":
                return new OracleDriver(connection);
            case "mssql":
                return new SqlServerDriver(connection);
            case "mongodb":
                return new MongoDriver(connection);
            default:
                console.log("Available classes:", DriverFactory.driverTypes);
                throw new MissingDriverError(type);
        }
    }

    public static registerDriver(type: string, driverType: any) { // (3) I added a method to register driverTypes
        DriverFactory.driverTypes[type] = driverType;
    }
}
```
Then in my own project I added the removed code of the WebSQL driver (but could by any driver implementation) and registered it:

```
ngOnInit() {

        DriverFactory.registerDriver('websql', WebsqlDriver); // <= the registration

        const options: WebSqlConnectionOptions = {
            type: 'websql',
            logging: ['error', 'query', 'schema'],
            synchronize: true,
            database: 'test',
            version: '1',
            description: '',
            size: 3 * 1024 * 1024,
            entities: [
                Author,
                Post,
                Category]
        };      
        createConnection(options).then(async connection => {
            // do what is needed...
        }).catch(error => {
            console.error('Connection failed!', error);
        });

    }
```
The approach with ```DriverFactory.registerDriver('name', DriverClass);``` even allows overwriting existing drivers with custom modified ones.

This approach also allows, later, to pull out the different drivers and move them in separate packages.
I saw there are some hard-references to specific driver classes inside the code, but I think that could be changed, eventually, with some enforced (interface) life-cycle methods in the driver classes.

**Remarks:**
- I no longer use a decorator on the (custom) driver class because, when I first did, the custom driver class was removed by the WebPack tree shaking. That's because it was nowhere explicitly referenced. 
Secondly,  the new approach allows overwriting existing driver classes.

- In the code at remark (1) and (3) I declared the variable/parameter as ```any``` because ```Driver``` is an interface and not a class, so I cannot declare the variable/parameter as ```typeof Driver```.

Hoping for your comments...

**Comment by codessentials** [comment] 2018-06-12 15:37
I also noticed this pull request (https://github.com/typeorm/typeorm/pull/2240) that handles about adding a new driver. I think this kind of requests could also be tackled by extracting the different driver classes from the core package and allow adding/customizing them as needed. Though I might not see the complete picture. Still I hope my proposition makes sense :-)

**Comment by daniel-lang** [comment] 2018-06-22 17:15
I like your proposal as it might help developers who want to change bits of the driver or add a custom one.

In the end, @pleerock has to decide if he likes it or not.
But in the meantime you could prepare a PR with a working test to show your proposal in action.

**Comment by pleerock** [comment] 2018-06-23 15:56
I would like to have useful abstractions and allow extension where possible. How are we going to resolve issue with `type` being a string literal type currently, and how to resolve issue with each type having its own connection settings.

**Comment by pleerock** [comment] 2018-06-25 09:43
new decorator and underlying implementation isn't that important as creating a new design of connection options. Currently connection options are specific to each database and they differentiate because of `type` literal type. If we remove `type` we won't have connection specific connection options anymore which is a big downside

**Comment by codessentials** [comment] 2018-06-26 05:56
OK, you 've lost me ;-) I mean, I don't see the issue, and that will be my bad. But, at least in my head, with the proposition I have it is possible to make db specific connection option classes and use the class to determine which driver to load. Can you explain in which way the ```type``` string has more meaning than the Class name of the DriverOptionsClass?

In my head I have (for example to configure MySQL):

```
@Driver({options: MySqlDriverOptions})
MySqlDriver extends OrmDriver {
   ... implementation
}
```

This @Driver decorator registers MySqlDriver and maps it to the MySqlDriverOptions class.
When you call createConection with an instance of MySqlDriverOptions, you can instantiate MySqlDriver and pass it's specific driver options, being the instance of MySqlDriverOptions.

Can you explain where I'm taking the wrong exit?

**Comment by pleerock** [comment] 2018-06-26 19:19
`MySqlDriverOptions` is an interface, it does not have instance. To check how `type` in connection works checkout source, and checkout in editor how autocompletion changes depend on value of the `type`.

**Comment by imnotjames** [comment] 2021-06-20 23:52
I think this is a duplicate of #2479

**Closed by imnotjames** 2021-06-20 23:52 UTC
Labels: comp: drivers and platforms, new feature
