### ISSUE TITLE
How to enforced not to run update,delete query without condition ?

### ISSUE THREAD

**Issue by hong-duc** [typeorm/typeorm#5300] opened 2020-01-08 04:30 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

----
Hi I am new to typeorm, as I learning how to use, I see that I can easily make a mistake (like typo, misunderstand api,...) when I write update or delete query using query builder and it run without where condition and end up with all data getting updated or deleted. So my question is that in typeorm is there any option or a hacky way that when a update or delete query running without a where condition it will throw error to prevent these kind of mistake for newbie ?. Thank you

**Comment by angelvega93** [comment] 2020-01-09 10:36
If you run a delete query without conditions its normal to delete all data.

This is not a TypeORM problem, you need to validate before sending the query.

**Comment by hong-duc** [comment] 2020-01-10 00:29
@angelvega93 yes and that why this is a question, not bug report, thank you very much

**Comment by Destreyf** [comment] 2020-01-11 04:27
@hong-duc To answer your question directly, TypeORM does not have any sort of developer safety functionality built into it, you could probably write your own validation/restriction logic, but this could end up being very cumbersome and ultimately may not make a lot of sense for your use case.

**Comment by hong-duc** [comment] 2020-01-11 13:16
@Destreyf thank you for your answer. 
I know this is a naive question but I have my reason. Right now only me using typeorm, but I want my team to use it too. I can guarantee that some will make the same mistake as me. That is why I ask this question to make sure they fail with an error rather than a database delete

**Comment by imnotjames** [comment] 2020-10-12 09:27
Duplicate of #3416

**Closed by imnotjames** 2020-10-12 09:27 UTC
Labels: driver: postgres, question
