### ISSUE TITLE
0.3 generic findOneBy typescript error

### ISSUE THREAD

**Issue by Scalahansolo** [typeorm/typeorm#8939] opened 2022-04-26 23:19 UTC
## Issue Description

With the upgrade to the new syntax in 0.3 there is a typescript issue with using `findOneBy` on a generic repro.

```typescript
export abstract class BaseEntity {
  abstract readonly id: string
}

export async function checkAuth<T extends BaseEntity>(
  entity: T,
  repo?: Repository<T>,
): Promise<[T, boolean]> {
  let existingEntity: T | null

  let exists = false
  if (repo) {
    existingEntity = await repo.findOneBy({ id: entity.id })

```
### Expected Behavior
The code above should compile fine, no issues

### Actual Behavior
I get the following typescript error.

```
TS2345: Argument of type '{ id: string; }' is not assignable to parameter of type 'FindOptionsWhere<T> | FindOptionsWhere<T>[]'.   Types of property 'id' are incompatible.     Type 'string' is not assignable to type 'FindOptionsWhereProperty<NonNullable<T["id"]>> | undefined'.
```

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by cwkang1998** [comment] 2022-04-28 03:54
Just tried this out, and found something interesting.

It seems that for some reason when using `T extends BaseEntity`, in cases where BaseEntity is a class, it seems that `FindOptionsWhereProperty<NonNullable<T["id"]>>` does not resolve to the equivalent `FindOptionsWhereProperty<NonNullable<string>>`. Not sure why this is the case, and if this is a limitation from typescript.

But this will work:
```typescript
export async function checkAuth<T extends {id: string}>(
  entity: T,
  repo?: Repository<T>,
): Promise<[T, boolean]> {
  let existingEntity: T | null

  let exists = false
  if (repo) {
    existingEntity = await repo.findOneBy({ id: entity.id }) // ok
```

**Comment by Scalahansolo** [comment] 2022-04-28 15:42
Unfortunately, that is not true. Still getting the same error. 

![ScreenShot 04-28 at 09 41](https://user-images.githubusercontent.com/4317253/165791367-f093023f-c019-4f80-b00a-7e50f927f094.png)

**Comment by cwkang1998** [comment] 2022-04-28 17:29
> Unfortunately, that is not true. Still getting the same error.

Ah, my bad, you are right that it doesn't work, seems like I got it wrong.

> It's also worth mentioning, even if this did work, it only gets part of the way there. Im my full implementation of Base Entity has other fields on it, so using this type of polymorphism is key.

I am aware of that, just adding some more context to this issue. Seems that typescript cannot determine type of `T["id"]`.

**Comment by shunkica** [comment] 2022-05-02 09:58
I have this issue as well and can't figure out how to solve it without some nasty casting.
The issues I encountered while using generics even before 0.3 makes me think nobody on the dev team is using TypeORM with generic entities.

**Comment by Kampfmoehre** [comment] 2022-05-06 10:31
I'm having the same issue. I build find options first and then conditionally change it based on some things. Solved it for now by using BaseEntity first and then casting back to FindManyOptions
```ts
  private async getInstalls<T extends MyBaseEntity>(
    entity: new () => T,
    packageName: string,
    period: Period,
    from: Date,
  ): Promise<T[]> {
    const repo = this.manager.getRepository<T>(entity);

    const findOptions: FindManyOptions<MyBaseEntity> = { where: { packageName } };
    switch (period) {
      case Period.Day:
        findOptions.where = Object.assign(findOptions.where, { date: this.toDate(from) });
        break;
      // ...
    }

    return repo.find(findOptions as FindManyOptions<T>);
  }
```

**Comment by Scalahansolo** [comment] 2022-05-06 13:56
@Kampfmoehre This is a good work around for now! Definitely think that this issue should stay open / get fixed at some point.

**Comment by adetoroe787** [comment] 2022-05-08 21:56
I have that same error. But different. Using both FindOneBy() and FineOne()

**findOneBy(id)**
```
export class getOneUsers {
    static getOneAdmin = async (req: Request, res: Response) => {
        const id = req.params.id;
        const admin = await AppDataSource.getRepository(Admin).findOne(id);
        return res.json(admin);
    };

    static getOneUser = async (req: Request, res: Response) => {
        const id = req.params.id;
        const user = await AppDataSource.getRepository(Users).findOne(id);
        return res.json(user);
    };
};
```

**findOneBy**
```
export class updateUsers {
    static updateAdmin = async (req: Request, res: Response) => {
        const admin = await AppDataSource.getRepository(Admin).findOneBy({
            id: req.params.id,
        });
        if (admin) {
            AppDataSource.getRepository(Admin).merge(admin, req.body);
            const result = await AppDataSource.getRepository(Admin).save(admin);
            return res.json(result);
        }
        return res.json({ msg: "Admin Not Found" });
    };

    static updateUser = async (req: Request, res: Response) => {
        const user = await AppDataSource.getRepository(Admin).findOne(req.params.id);
        if (user) {
            AppDataSource.getRepository(Users).merge(user, req.body);
            const result = await AppDataSource.getRepository(Admin).save(user);
            return res.json(result);
        }
        return res.json({ msg: "User Not Found" });
    };
}
```

here is the shot
![github1](https://user-images.githubusercontent.com/39957559/167317290-50041255-9664-4ef2-912a-adbfd8c1cc28.png)
![Screenshot from 2022-05-08 17-52-16](https://user-images.githubusercontent.com/39957559/167317292-ff67adf4-30de-46b9-96ec-a7e675232355.png)

**Comment by adetoroe787** [comment] 2022-05-08 22:04
> I have that same error. But different. Using both FindOneBy() and FineOne()
> 
> **findOneBy(id)**
> 
> ```
> export class getOneUsers {
>     static getOneAdmin = async (req: Request, res: Response) => {
>         const id = req.params.id;
>         const admin = await AppDataSource.getRepository(Admin).findOne(id);
>         return res.json(admin);
>     };
> 
>     static getOneUser = async (req: Request, res: Response) => {
>         const id = req.params.id;
>         const user = await AppDataSource.getRepository(Users).findOne(id);
>         return res.json(user);
>     };
> };
> ```
> 
> **findOneBy**
> 
> ```
> export class updateUsers {
>     static updateAdmin = async (req: Request, res: Response) => {
>         const admin = await AppDataSource.getRepository(Admin).findOneBy({
>             id: req.params.id,
>         });
>         if (admin) {
>             AppDataSource.getRepository(Admin).merge(admin, req.body);
>             const result = await AppDataSource.getRepository(Admin).save(admin);
>             return res.json(result);
>         }
>         return res.json({ msg: "Admin Not Found" });
>     };
> 
>     static updateUser = async (req: Request, res: Response) => {
>         const user = await AppDataSource.getRepository(Admin).findOne(req.params.id);
>         if (user) {
>             AppDataSource.getRepository(Users).merge(user, req.body);
>             const result = await AppDataSource.getRepository(Admin).save(user);
>             return res.json(result);
>         }
>         return res.json({ msg: "User Not Found" });
>     };
> }
> ```
> 
> here is the shot ![github1](https://user-images.githubusercontent.com/39957559/167317290-50041255-9664-4ef2-912a-adbfd8c1cc28.png) ![Screenshot from 2022-05-08 17-52-16](https://user-images.githubusercontent.com/39957559/167317292-ff67adf4-30de-46b9-96ec-a7e675232355.png)

Github Repo: https://github.com/adetoroe787/cei_api_backend/blob/main/src/constroller/userController.ts

**Comment by Syntarex** [comment] 2022-05-23 09:37
> I'm having the same issue. I build find options first and then conditionally change it based on some things. Solved it for now by using BaseEntity first and then casting back to FindManyOptions
> 
> ```ts
>   private async getInstalls<T extends MyBaseEntity>(
>     entity: new () => T,
>     packageName: string,
>     period: Period,
>     from: Date,
>   ): Promise<T[]> {
>     const repo = this.manager.getRepository<T>(entity);
> 
>     const findOptions: FindManyOptions<MyBaseEntity> = { where: { packageName } };
>     switch (period) {
>       case Period.Day:
>         findOptions.where = Object.assign(findOptions.where, { date: this.toDate(from) });
>         break;
>       // ...
>     }
> 
>     return repo.find(findOptions as FindManyOptions<T>);
>   }
> ```

Thanks for the workaround. Hope this will get fixed soon. Wasted almost an hour because I thought the problem is on my end.

**Comment by EliasTouil** [comment] 2022-07-02 03:58
I just changed from 0.2.x to 0.3.x and experiencing the same issue, hope it gets some attention soon!

**Comment by paramsinghvc** [comment] 2022-07-02 21:58
I'm facing the same issue. After some digging I found that it's happening due to the faulty typings

```ts
/**
 * A single property handler for FindOptionsWhere.
 */
export declare type FindOptionsWhereProperty<Property> =
  Property extends Promise<infer I>
    ? FindOptionsWhereProperty<NonNullable<I>>
    : Property extends Array<infer I>
    ? FindOptionsWhereProperty<NonNullable<I>>
    : Property extends Function
    ? never
    : Property extends Buffer
    ? Property | FindOperator<Property>
    : Property extends Date
    ? Property | FindOperator<Property>
    : Property extends ObjectID
    ? Property | FindOperator<Property>
    : Property extends object
    ?
        | FindOptionsWhere<Property>
        | FindOptionsWhere<Property>[]
        | EqualOperator<Property>
        | FindOperator<any>
        | boolean
    : Property | FindOperator<Property>;
/** :
 * Used for find operations.
 */
export declare type FindOptionsWhere<Entity> = {
  [P in keyof Entity]?: FindOptionsWhereProperty<Entity[P]>;
};

```

Error says:

```
(property) id?: string | FindOperator<string>
Argument of type '{ id: string; }' is not assignable to parameter of type 'FindOptionsWhere<User>'.
  Types of property 'toString' are incompatible.
    Type '() => string' is not assignable to type 'never'.ts(2345)
```
which points out the typing done as `Property extends Function  ? never`. If a property is a function type, it shouldn't be assigned to never.

TypeOrm version: ^0.3.7

**Comment by Zikoat** [comment] 2022-07-04 07:19
@paramsinghvc Your error message seems to be different to the one being discussed here, where it is about generic properties.

See this codesandbox with the code from the original issue: https://codesandbox.io/s/typescript-playground-export-forked-hiqfd0

If you copy the code to your own code and edit the types, you will see that the issue still persists with the code in your commit, so that would unfortunately not fix this issue. I also think it's the same with the other issue you mentioned.

You should open a new issue and include the code that you used to encounter the problem you have.

**Comment by paramsinghvc** [comment] 2022-07-04 10:19
I'm resorting to using patch-package anyway for the similar problem. Can't believe the error is still there for such a common operation in typeorm.

**Closed** 2022-07-06 11:44 UTC
Labels: bug, requires triage

**Comment by slaviqueue** [comment] 2022-08-08 15:14
Has this been fixed in the latest typeorm patch? I have the same issue that still reproduces on 0.3.7:
![Screenshot from 2022-08-08 18-13-13](https://user-images.githubusercontent.com/20744231/183451714-451fcd1a-6f29-42fc-853d-e91d68dd12e2.png)

**Comment by lucas-labs** [comment] 2022-08-12 05:17
@pleerock I'm also getting this error with `typeorm@0.3.7`. Maybe this issue should still be open?

![image](https://user-images.githubusercontent.com/12949236/184289331-425f61ea-a7d1-43d9-9a05-d40641a39a43.png)

**Comment by khteh** [comment] 2022-08-13 03:44
https://github.com/typeorm/typeorm/issues/9281

**Comment by pepsi92** [comment] 2022-08-13 18:48
> @pleerock I'm also getting this error with `typeorm@0.3.7`. Maybe this issue should still be open?
> 
> ![image](https://user-images.githubusercontent.com/12949236/184289331-425f61ea-a7d1-43d9-9a05-d40641a39a43.png)

Unfortunately it seems the fix has been merged a few days after 0.3.7 is released. I think we have to wait until 0.3.8 :(

**Comment by dlgoodchild** [comment] 2022-08-29 22:24
@pleerock do you have any idea on when 0.3.8 will be tagged? Cheers

**Comment by azarus** [comment] 2022-09-05 08:51
This is issue seems to be still unresolved. A similar issue occurred here:
https://github.com/typeorm/typeorm/issues/9346

**Comment by jannikac** [comment] 2022-10-05 08:46
This issue still exists on 0.3.10. Reopen?

**Comment by gavrilin-remote** [comment] 2022-10-05 11:35
Still facing on 0.3.9. Let's reopen this issue

**Comment by ammasum** [comment] 2022-10-07 13:25
Same issue with v 0.3.11-dev.cdabaa3. Please reopen this

**Comment by Juuldamen** [comment] 2022-10-07 15:04
I think I'm still facing the same issue on 0.3.10. `T` is just a simple class with a few keys here.

![image](https://user-images.githubusercontent.com/31408341/194507725-12c239a1-bd40-48b3-85b2-1e94870e617a.png)

Type assertion on the return value is a workaround, and the code does work for me. But this doesn't offer any guarantees that the value is actually matching what TypeORM expects since it is just overriding the compiler check.

```ts
return { [filter.where]: In(filter.in) } as FindOptionsWhere<T>;
```

**Comment by Metanart** [comment] 2022-10-07 20:27
This way works fine:

export class BaseController<Entity extends { id: string }> {
    repository: Repository<Entity>;
    query: SelectQueryBuilder<Entity>;

    constructor(entityTarget: EntityTarget<Entity>) {
        this.repository = Database.source.getRepository<Entity>(entityTarget);
        this.query = this.repository.createQueryBuilder();
    }

    async one(request: Request, response: Response, next: NextFunction) {
        return this.repository.findOneBy({ id: request.params.id } as FindOptionsWhere<Entity>);
    }
}

**Comment by phanhuutoan** [comment] 2022-11-26 03:17
I still god this bug when update to typescript 4.9 and typeorm 0.3.10
but the solution from @Metanart work for me, thank you

**Comment by jeromeSH26** [comment] 2023-01-07 16:23
issue remains in 0.3.11 and typescript 4.9.4.
casting `FindWhereOptions` is the workaround but not the solution

**Comment by hugo-aviles-signpost** [comment] 2023-01-13 22:19
Why is this issue closed? Still need to cast `FindWhereOptions ` to solve the issue, btw thx for the solution @Metanart <3

**Comment by kvbutler** [comment] 2023-02-24 19:45
@hugo-aviles-signpost, yeah this issue should be open posted about it in #9709

**Comment by spuxx1701** [comment] 2023-03-16 11:41
Same here, issue is still unresolved

**Comment by UsamaShahzad7** [comment] 2023-03-21 13:03
> You can use the qurey builder instead like this:
> 
> `const result=await this.userRepository.createQueryBuilder("user").select("email").where("user.email=:UserEmail",{UserEmail:email}).getOne();`
> 
> //I am getting the email from the user and using it to find whether the user with email exist or not in the database.



MINOR CHANGES:

const result=await this.userRepository.createQueryBuilder("user").select("user.email").where("user.email=:UserEmail",{UserEmail:email}).getOne();

**Comment by stanukih** [comment] 2023-06-21 15:45
Found a temporary workaround.
In function findOne() specify relations and in block where use them. Example:
servicesLanguage = await servicesLanguagesRepository.findOne({
      relations: {
        languages: true,
        services: true,
      },
      where: {
        languages: {
          id: languageId,
        },
        services: {
          id: serviceId,
        },
      },
    });
This works correctly, but when requested in SQL used join and this adds to the cost of the DB

**Comment by LdDv9** [comment] 2023-09-19 04:20
this is my temporary way :(, hope typeorm will resolve soon

`const findOptions: FindOneOptions<Entity> = {
      where: {
        uuid,
      } as unknown as FindOptionsWhere<Entity>,
      ...(options || {}),
    };
    
    const data = await this.findOne(findOptions);`

**Comment by youwei997** [comment] 2024-04-23 06:46
> this is my temporary way :(, hope typeorm will resolve soon这是我:(的临时方式，希望 typeorm 能尽快解决
> 
> ```
> const findOptions: FindOneOptions<Entity> = {
>       where: {
>         uuid,
>       } as unknown as FindOptionsWhere<Entity>,
>       ...(options || {}),
>     };
>     const data = await this.findOne(findOptions);
> ```

In 2024, I will still use the same solution as you

**Comment by OSA413** [comment] 2025-02-12 17:23
See explanation here: https://github.com/typeorm/typeorm/issues/9281#issuecomment-2654110392
