### ISSUE TITLE
MongoDB relations support ?

### ISSUE THREAD

**Issue by davidquintard** [typeorm/typeorm#4243] opened 2019-06-05 11:20 UTC
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi there,
I'd like to know if typeorm support mongodb relations.
If so, how to define this relation in entities.

I want to do a query like this:
````
 let candidatures = await candidatRepository.find({
            join: {
                alias: "c",
                leftJoinAndSelect: {
                    m: "c.membre"
                }
            },
        });
````
But json objects returned does not contain "membre" entities.

Membre:
````
import {Entity, Column, ObjectIdColumn} from "typeorm";
import {ObjectID} from "mongodb";
import {Membre} from "./Membre";

@Entity("candidats")
export class Candidat
{
    @ObjectIdColumn()
    id: ObjectID;
    ...
    //@ObjectIdColumn()
    @Column(type => Membre)
    membre: Membre;
}
````

**Comment by pairmix** [comment] 2019-06-05 11:22
![image](https://user-images.githubusercontent.com/33130887/58952756-e5185f00-8794-11e9-9724-0d85fa57f992.png)

**Comment by pairmix** [comment] 2019-06-05 11:22
![image](https://user-images.githubusercontent.com/33130887/58952805-0416f100-8795-11e9-8373-5bc0251c3321.png)

**Comment by thonythony** [comment] 2019-06-06 16:34
Hello, mongodb support is very poor compared to other sql-kind database. So, no support of relations. 
Don't hesitate to lookup source code of typeorm.

https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts

**Comment by vlapo** [comment] 2019-06-06 20:18
Right now is mongodb support fully under control of community. If you want to see some functionality for this driver feel free create PR or proposal how you want to implement/integrate this functionality into typeorm.

**Comment by theodorDiaconu** [comment] 2019-11-11 10:36
I'm looking to get this merged: https://www.npmjs.com/package/@kaviar/nova

**Comment by the-nicolas** [comment] 2020-01-31 16:46
> I'm looking to get an integration of this merged: https://www.npmjs.com/package/@kaviar/nova

@vlapo Any success already? Looks very lightweight and is exactly what's missing right now.

**Comment by theodorDiaconu** [comment] 2020-02-03 10:33
@the-nicolas didn't invest in solving this, I have started creating my own framework.

**Comment by sae13** [comment] 2020-03-27 21:30
any upgrade?

**Comment by breitembach** [comment] 2020-06-20 22:00
can be used with aggregate like https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/

**Comment by pairmix** [comment] 2020-06-21 07:32
> 
> 
> can be used with aggregate like https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/

Do you think performances are correct ?
I mean isn't it a sql join like without indexes ?

**Comment by lucas-wade** [comment] 2020-06-24 19:17
> ![image](https://user-images.githubusercontent.com/33130887/58952805-0416f100-8795-11e9-8373-5bc0251c3321.png)

HI, i am very curious how you were able to store the membre field as ObjectID type. I am not able to and i am only able to get it to store the id as a string in mongodb.
I am trying to store a reference id like you have done with the ObjectID on the membre field in the db. However i am only able to store it as a field.. Would you mind showing your resolver and input types?
thanks

**Comment by imnotjames** [comment] 2021-06-25 07:54
duplicate of #655

**Closed by imnotjames** 2021-06-25 07:54 UTC
Labels: driver: mongodb, question

**Comment by levarberry** [comment] 2023-07-12 21:17
For mongo  or any other NoSQL database.   Relations are not inherit to the DB.

Therefore you need to use the `$lookup`.   Or make a second call(s) to the server.     If your system is heavily relational, perhaps Mongo is not the best choice or your data needs to be more streamlined into a single document or less documents.  The ORM would essential end up doing this ($lookup)  for you in the background anyways.

I know it would be nice if this worked like SQL.  However, freedom from schema bound design has its price.
