### ISSUE TITLE
Running a migration that attempts to create a database results in an Unknown Database error

### ISSUE THREAD

**Issue by AkashAryal** [typeorm/typeorm#6351] opened 2020-07-04 16:41 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I was looking at https://github.com/typeorm/typeorm/issues/2961 where it recommends using migrations to set up initial database:

> you should create an initial migration when your database is empty. This way you will be able to initialize new databases using typeorm migration:run

I used the cli tool to generate the migration file:

```
import { MigrationInterface, QueryRunner } from "typeorm";
import { DB_NAME } from '../../servConsts'

export class InitialCreateDB1593832999021 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.createDatabase(DB_NAME, true).then(() => {
            console.log("migration ran");
        }).catch(e => {
            console.log(e);
        });
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.dropDatabase(DB_NAME, true).then(() => {
            console.log("migration ran");
        }).catch(e => {
            console.log(e);
        });
    }

}
```
After running the migration I was hoping it would create a database locally and then I was planning on creating another migration to insert the tables. 

After running the migration, however, I got a `Error: Unknown database 'DBNAME HERE'`
Naturally, the database is unknown (since it hasn't been create yet). Is it not possible to use a migration to create the initial db? Do i have to do this manually?

**Comment by imnotjames** [comment] 2020-10-07 04:39
Duplicate of #6135

**Closed by imnotjames** 2020-10-07 04:39 UTC
Labels: comp: migrations, driver: mariadb, driver: mysql, question

**Comment by momadthenomad** [comment] 2023-09-25 13:00
@AkashAryal how did you solve this?
