### ISSUE TITLE
How does one link several entities together, when every child entity has all of the parents primary columns plus an index itself as its primary key?

### ISSUE THREAD

**Issue by Bernd-L** [typeorm/typeorm#3701] opened 2019-02-23 20:31 UTC
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `latest`

# The question
How does one link several entities together, when every child entity has all of the parents primary columns plus an index itself as its primary key?

# The data model

I want to keep track of the `stocks` of the type of a `thing` which is part of an `inventory`.

## The relations
- An `inventory` can have multiple `thing`s
- Every `thing` is part of one `inventory`

- Every `thing` can have multiple `stock`s
- Every `stock` is of the type of one `thing`

### `inventory`

**PK:**
- `id`

**FKs:**
none

**dependencies:**
none

**dependents:**
- `thing`
- `stock`

### `thing`

**PK:**
- `number` (like an ID, but they start from 1 for every `inventory`)
- `inventoryId`

Notice: This means that there can only be one unique combination of the `number` of `thing` and the `id` of an `inventory`. Thus, two values are required to reference any given `thing` as it doesn't have one unique identifier (the two columns listed above are one composite PK).

**FKs:**
- `inventoryId` (references `id` of `inventory`)

**dependencies:**
- `inventory`

**dependents:**
- `stock`

### `stock`

**PK:**
- `number` (like an ID, but they start from 1 for every `inventory` and `thing`)
- `thingNumber`
- `inventoryId`

Notice: This means that there can only be one unique combination of the `number` of `stock`, the `number` of `thing` and the `id` of an `inventory`. Thus, three values are required to reference any given `stock` as it doesn't have one unique identifier (the three columns listed above are one composite PK).

**FKs:**
- `inventoryId` (references `id` of `inventory`)
- `thingNumber` (references `number` of `thing`)

**dependencies:**
- `inventory`
- `thing`

**dependents:**
none

# The Code

(omitting imports and non-relevant fields)

## inventoryModel.ts

```TS
@Entity()
export class Inventory {
  constructor(InventoryName: string) {
    this.name = InventoryName;
  }

  @PrimaryGeneratedColumn()
  id: number;

  @Column("text")
  name: string;

  @OneToMany(type => Thing, thing => thing.inventory, {
    cascade: true, onDelete: "CASCADE"
  })
  things: Thing[];
}
```

## thingModel.ts

```TS
@Entity()
export class Thing {
  @Column({
    primary: true,
    unique: false
  })
  number: number;

  @Column()
  name: string;

  @ManyToOne(() => Inventory, inventory => inventory.things, {
    primary: true
  })
  @JoinColumn({
    name: "inventory",
    referencedColumnName: "id"
  })
  inventory: Inventory;

  @OneToMany(() => Stock, stock => stock.thing)
  stocks: Stock[];
}
```

## stockModel.ts

```TS
@Entity()
export class Stock {
  @PrimaryColumn()
  number: number;

  @ManyToOne(type => Inventory, { primary: true })
  inventory: Inventory;

  // @ManyToOne(type => Thing, { primary: true }) // this was my first attempt
  // thing: Thing;

  @ManyToOne(() => Thing, thing => thing.stocks, { primary: true })
  @JoinColumn([
    {
      name: "inventory",
      referencedColumnName: "inventory"
    },
    {
      name: "thingNumber",
      referencedColumnName: "number"
    }
  ])
  thing: Thing;

  @Column()
  quantity: string;
}
```

## The state of the project

Everything works so far (at least on the server-side), except for the `stock` implementation.

Thus, the question arises: How would one go about this?

Thanks for reading,
Greetings,
\- B

---
PS:
If the need for the *exact* code arises, then [here](https://github.com/Bernd-L/exDateMan/tree/q1/server/models) it is (notice how it points to a specific tag `q1`, which is dedicated to this question).

**Comment by Kononnable** [comment] 2019-03-16 10:10
@Bernd-L What exactly doesn't work in stock implementation?
You've described the issue quite precisely, but didn't write what exactly is wrong.

**Comment by Bernd-L** [comment] 2019-03-18 06:26
### Thank you for your response.

I have tried only adding a `thing` object to `stock`, but TypeORM fails to create/execute the queries required for this kind of database schema.

### To put my question in other words:
How can one use a nested hirachical strcture with TypeORM?
As in use one root entity with UIDs and several layers of children, which all each have an ID (or number) of their own, which only makes for a unique PK when combined with all the IDs above and the UID at the root.

**Comment by Kononnable** [comment] 2019-03-24 00:08
Tbh I'm not yet sure what exactly are you doing and what is wrong :)
Ran model pasted here - it's creating db by synchronization. One thing I see which might make troubles is creating primary keys on columns which aren't explicitly declared. It's not required in 0.2(it is required in next branch) but can generate troubles sometimes.
Try changing you're code like that:
```typescript
    @PrimaryColumn()
    inventoryId: number;

    @ManyToOne(type => Inventory)
    inventory: Inventory;
```

If that doesn't help please specify what is required to reproduce your issue and what is error message - maybe it's because you've already got some data in tables etc.

**Comment by Bernd-L** [comment] 2019-06-22 15:32
It's been a while, but I decided to revisit this problem:

# The ERD diagram

I made this using Oracle SQL Developer:

![image](https://user-images.githubusercontent.com/18219148/59965775-ee365980-9512-11e9-9f4f-72fb9b657b38.png)


Perhaps this illustrates the situation a little bit better.

# My question

**How would the TypeORM-model implementation of this ERD look like?**

My current approach can be found here:
https://github.com/Bernd-L/exDateMan/tree/v0.11.0/backend/models

This is the current implementation running both in staging and production.
While the base-functionality appears to be working, the `category`-system couldn't be implemented yet, as I have been using a workaround for the "_Does TypeORM support using parent entity's composite primary keys as part of child entity's composite primary key in foreign key relation?_" issue (see #2976).

Again:

**What is the best-practice approach of implementing this ERD with TypeORM?**

**Comment by imnotjames** [comment] 2020-10-04 04:03
The best practice at this time for building your models is whatever works.  Sounds like you've found that so I'm closing this.

**Closed by imnotjames** 2020-10-04 04:03 UTC
Labels: needs more info
