### ISSUE TITLE
typing of connect.getRepository doesn't match predefinition

### ISSUE THREAD

**Issue by vrachels** [typeorm/typeorm#1753] opened 2018-03-14 02:09 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.16`

I upgraded from an old installed 0.1.0-alpha.49 to 0.1.16, and I'm now getting the following error:

```error TS2719: Type 'Repository<XXX>' is not assignable to type 'Repository<XXX>'. Two different types with this name exist, but they are unrelated.```

for the following code:
```const db: Repository<XXX> = dbConn.getRepository(XXX);```
while
```const db = dbConn.getRepository(XXX);```
works fine

vscode mouseover gives additional message:
```Property 'insert' is missing in type 'Repository<XXX>'.```

(the use case is for the variable 'db' to be defined elsewhere with proper typing, not inline as in this simple example)

obviously the workaround is to remove the typing, but I'd rather be using TS than JS.

**Comment by pleerock** [comment] 2018-03-14 07:20
You do something wrong, I have no other explanations for this issue. And btw you don't really need to specify `: Repository<XXX>` since db already knows its type, you simply ignore basic typescript features. 

If you want me to take a look on this issue please create a **minimal** reproduction git repo.

Also if you are upgrading from quite old `0.1.0-alpha.49` then I really recommend you to upgrade to latest `@next` since 0.2.0 will be released soon.

**Comment by pleerock** [comment] 2018-03-29 09:53
Closing as no answer from reporter.

**Closed by pleerock** 2018-03-29 09:53 UTC

**Comment by vrachels** [comment] 2018-03-29 17:56
sorry, I've been busy, but I do have this open.  Please reopen and I will eventually get a test case to you.

A little put off by 'you do something wrong' - so it's not high on my priority.
