### ISSUE TITLE
CreateDateColumn removes relation

### ISSUE THREAD

**Issue by nehalist** [typeorm/typeorm#1027] opened 2017-10-13 15:59 UTC
Adding a `CreateDateColumn` column to my entity removes my fks:

```
@Entity()
export class Books extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
  
  // ...

  @CreateDateColumn()
  createdAt: Date;

  @ManyToOne(type => Author, author => author.books)
  author: Author;
}
```

Without having a `createdAt` column the foreign key to the authors table is properly set - otherwise the fk is removed.

**Comment by pleerock** [comment] 2017-10-13 16:09
no, it cannot be possible, there are tests with same code and it works. I'll have to ask you to create a test or repo with reproduction of your issue.

**Comment by nehalist** [comment] 2017-10-22 12:28
Is there any way to get the SQL generated by the sync?

**Comment by nehalist** [comment] 2017-10-22 12:55
See the referenced repo; the actual issue is in `Book.ts#22`.

**Comment by nehalist** [comment] 2017-10-31 10:44
@pleerock any idea what the cause of this could be?

**Comment by pleerock** [comment] 2017-11-22 10:53
I cloned your project, remove `@CreateDate` line and made `npm start index.js` - everything is working I have `"done"` message without any errors.

**Comment by nehalist** [comment] 2017-11-22 12:15
My problem is not that I get any error messages, but that the foreign keys are lost.

**Comment by pleerock** [comment] 2017-11-22 12:48
ah okay, then are lost because your entity does not have any relations and all foreign keys are removed from the table, its by design of entity relations

**Comment by nehalist** [comment] 2017-11-22 14:21
This doesn't make any sense, since the foreign keys exist while not utillizing the `@CreatedDateColumn`. Just to be clear:

Without `@CreatedDateColumn` the FKs exist. After adding the `created_at` column the FKs are removed from the database.

**Comment by pleerock** [comment] 2017-11-22 14:47
Ah okay, forgot my answer, I was thinking you are talking about manually-created foreign keys.

So, it should not remove your "author" relation's foreign keys, and it does not do it as I check it:

```
Umeds-MacBook-Pro-2:typeorm-typeorm-1027 pleerock$ node index.js
executing query:  START TRANSACTION
executing query:  SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA IN ('test') AND TABLE_NAME IN ('author', 'book')
executing query:  SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA IN ('test')
executing query:  SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA IN ('test') AND INDEX_NAME != 'PRIMARY' ORDER BY SEQ_IN_INDEX
executing query:  SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA IN ('test') AND REFERENCED_COLUMN_NAME IS NOT NULL
executing query:  CREATE TABLE `author` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL UNIQUE) ENGINE=InnoDB
executing query:  CREATE TABLE `book` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL UNIQUE, `authorId` int(11)) ENGINE=InnoDB
executing query:  ALTER TABLE `book` ADD CONSTRAINT `fk_7f364731a6dc36c02bfc55c850c` FOREIGN KEY (`authorId`) REFERENCES `author`(`id`)
executing query:  COMMIT
done
^C

Umeds-MacBook-Pro-2:typeorm-typeorm-1027 pleerock$ node index.js
executing query:  START TRANSACTION
executing query:  SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA IN ('test') AND TABLE_NAME IN ('author', 'book')
executing query:  SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA IN ('test')
executing query:  SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA IN ('test') AND INDEX_NAME != 'PRIMARY' ORDER BY SEQ_IN_INDEX
executing query:  SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA IN ('test') AND REFERENCED_COLUMN_NAME IS NOT NULL
executing query:  SHOW INDEX FROM `test`.`author` WHERE Key_name = 'PRIMARY'
executing query:  SHOW INDEX FROM `test`.`book` WHERE Key_name = 'PRIMARY'
executing query:  ALTER TABLE `test`.`book` ADD `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
executing query:  COMMIT
done
```

two runs: first without `@CreateDateColumn()`, second with `@CreateDateColumn()`. To enable query logging you just set `logging: true` in connection options.

**Comment by pleerock** [comment] 2018-02-21 07:03
Closing as no answer from reporter.

**Closed by pleerock** 2018-02-21 07:03 UTC
Labels: needs more info
