### ISSUE TITLE
Order By in raw sql dont work with parameter - PostgreSql

### ISSUE THREAD

**Issue by dzatloukal** [typeorm/typeorm#3773] opened 2019-03-07 08:43 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.9` (or put your version here)

Hi,
Iam using entityManager and raw query to get data from Postgre database. I have simple query for select and order by item_id.
If I write full query as:

let query = Select * From item
...
Order By item_id;
and pass it to entityManager -> await this.entityManager.query(query) <- order by is working correctly.

But if I write query with parameter:

let query = Select * From item
...
Order By $1;
and pass columnName for ordering to entityManager -> await this.entityManager.query(query,["item_id"]) <- order by is completely ignored.

I also tried put columName to property and pass that property to entityManager:
let columnName = "item_id"
await this.entityManager.query(query,[columnName])
but with same result.

Does anyone know, where could be the problem? Or is there any workarround to use Order By with parametr in raw sql?

Thanks in advance.

**Comment by Kononnable** [comment] 2019-03-17 17:04
Duplicate of #3740.

**Closed by Kononnable** 2019-03-17 17:04 UTC
