### ISSUE TITLE
QueryRunner failing to retrieve schemas and tables after successfully running runMigrations()

### ISSUE THREAD

**Issue by dcs3spp** [typeorm/typeorm#4813] opened 2019-09-25 15:27 UTC
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.x.x` (0.2.19)

**Steps to reproduce or a small repository showing the problem:**
I am a new user trying to understand QueryRunner and how to run migrations on a PostgreSQL connection using `connection.runMigrations()`. In the code block below, after I successfully issue runMigrations(), why does the `getDatabases()`, `getSchemas()` and `getTables` methods of the queryRunner instance return empty lists? Shouldn't they return the schemas and tables for the database that the connection represents?

The output from running the code block below is:
```bash
[Nest] 14607   - 09/25/2019, 4:21:13 PM   createAConnection() => Connecting with options => {...}
[Nest] 14607   - 09/25/2019, 4:21:13 PM   createAConnection() => Dropping database... +146ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   createAConnection() => Database successfully dropped +26ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   createAConnection() => connected +0ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Running migrations with connection status true +0ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Migrations successfully ran, these are... +20ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Migration => InitialMigration1568198782367 +1ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Creating QueryRunner +1ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   QueryRunner connected +1ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Retrieved databases using queryRunner.getDatabases() :: [] +0ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Retrieved schemas using queryRunner.getSchemas() :: [] +1ms
[Nest] 14607   - 09/25/2019, 4:21:13 PM   Retrieved expected tables using queryRunner.getTables => [] +16ms
```

```ts
import { Logger } from '@nestjs/common';
import { createConnection, Connection, QueryRunner, Table } from 'typeorm';

import { ConfigOptions } from './config/models/config.options';
import { ConfigServiceFactory } from './config/factories/configservice.factory';
import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
import { Migration } from 'typeorm/migration/Migration';

async function dispose(connection: Connection) {
  if (connection && connection.isConnected) {
    await connection.close();
  }
}

async function createAConnection(): Promise<Connection> {
  let connection: Connection;

  // override default connections to avoid dropping schema and running migrations
  // we are doing this manually
  const config: ConfigOptions = ConfigServiceFactory.loadDbConfigSync();
  const dbConfig: PostgresConnectionOptions = config.db as PostgresConnectionOptions;
  const connect: PostgresConnectionOptions = {
    ...dbConfig,
    dropSchema: false,
    logging: false,
    migrationsRun: false,
  };

  try {
    Logger.log(
      `createAConnection() => Connecting with options => ${JSON.stringify(
        connect,
        null,
        2,
      )}`,
    );
    connection = await createConnection(connect);
    Logger.log('createAConnection() => Dropping database...');
    await connection.dropDatabase();
    Logger.log('createAConnection() => Database successfully dropped');
  } catch (err) {
    Logger.error(`createAConnection() => Failed to connect => ${err}`);
    await dispose(connection);
    throw err;
  }
  Logger.log('createAConnection() => connected');

  return connection;
}

async function driver(connection: Connection) {
  Logger.log(
    `Running migrations with connection status ${connection.isConnected}`,
  );
  const migrations: Migration[] = await connection.runMigrations();
  Logger.log('Migrations successfully ran, these are...');
  migrations.forEach(element => {
    Logger.log(`Migration => ${element.name}`);
  });

  Logger.log('Creating QueryRunner');
  let queryRunner: QueryRunner = connection.createQueryRunner('master');
  await queryRunner.connect();
  Logger.log('QueryRunner connected');

  const databases: string[] = await queryRunner.getDatabases();
  Logger.log(
    `Retrieved databases using queryRunner.getDatabases() :: ${JSON.stringify(
      databases,
    )}`,
  );
  const schemas: string[] = await queryRunner.getSchemas();
  Logger.log(
    `Retrieved schemas using queryRunner.getSchemas() :: ${JSON.stringify(
      schemas,
    )}`,
  );
  const tables: Table[] = await queryRunner.getTables([
    'coursemanagement.Course',
    'coursemanagement.Migrations',
  ]);
  Logger.log(
    `Retrieved expected tables using queryRunner.getTables => ${JSON.stringify(
      tables,
    )}`,
  );
}

async function main() {
  const myConnection: Connection = await createAConnection();
  await driver(myConnection);
}

main();
```

**Comment by imnotjames** [comment] 2020-10-07 05:34
This is a duplicate of #4489 - It's not because of the migration, it just was never implemented.

**Closed by imnotjames** 2020-10-07 05:34 UTC
Labels: bug, comp: migrations, driver: postgres, question
