### ISSUE TITLE
ER_CANT_DROP_FIELD_OR_KEY: Can't DROP '<field_name>'; check that column/key exists

### ISSUE THREAD

**Issue by AmirTugi** [typeorm/typeorm#77] opened 2016-11-06 10:24 UTC
I'm getting an error every other change I do (using nodemon) which prompts me this error:

```
{ Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'nameHebrew'; check that column/key exists
    at Query.Sequence._packetToError (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\sequences\Sequence.js:51:14)
    at Query.ErrorPacket (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\sequences\Query.js:83:18)
    at Protocol._parsePacket (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\Projects\ArihavAPI\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (D:\Projects\ArihavAPI\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (D:\Projects\ArihavAPI\node_modules\mysql\lib\Connection.js:214:25)
    at Promise (D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:123:48)
    at MysqlQueryRunner.query (D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:122:16)
    at MysqlQueryRunner.<anonymous> (D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:319:32)
    at next (native)
    at D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:7:65
    at __awaiter (D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:3:12)
    at changedColumns.map (D:\Projects\ArihavAPI\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:316:74)
    at Array.map (native)
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlState: '42000',
  index: 0 }
```

I see this happens in other ORMs, so I think this is somehow related to the `mysql` node module.

Could you take a look at my model and tell me if anything's amiss?

```
@Table()
@Index("index_name_hebrew", ['nameHebrew'], { unique: true })
@Index("index_name_english", ['nameEnglish'], { unique: true })
export class Customer {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    nameHebrew: string;
    @Column()
    nameEnglish: string;
    @Column()
    phone1: string = '';
    @Column()
    phone2: string = '';
    @Column()
    email: string = '';
    @Column()
    contact1Name: string = '';
    @Column()
    contact1Phone: string = '';
    @Column()
    contact2Name: string = '';
    @Column()
    contact2Phone: string = '';
    @Column()
    fax: string = '';
    @Column()
    address: string = '';
    @Column()
    city: string = '';
    @Column()
    zip: string = '';
    @Column()
    deliveryAddress: string = '';
    @Column()
    deliveryCity: string = '';
    @Column()
    deliveryZip: string = '';
    @Column()
    paymentMethod: string = '';
    @Column()
    comments: string = '';
    @Column()
    type: string = 'customer';
    @Column()
    isActive: boolean = true;
    @CreateDateColumn()
    createdAt: string;
    @UpdateDateColumn()
    updatedAt: string;
}
```

Oh, the weird part is that I actually meant every other time. When I get this error, and reload nodemon (with a change in a file, for example) it works.

**Comment by pleerock** [comment] 2016-11-06 10:47
no idea, maybe its somehow related to transactions or something is blocking, or maybe after nodemon restarts the app it forcefully closes app which causes such problems

**Comment by AmirTugi** [comment] 2016-11-06 11:08
I see this in the query log this:
```
2016-11-06T10:58:11.849074Z	  400 Query	ALTER TABLE `customer` DROP INDEX `index_name_hebrew`
2016-11-06T10:58:11.858579Z	  400 Query	ALTER TABLE `customer` DROP INDEX `index_name_english`
2016-11-06T10:58:11.867758Z	  400 Query	ALTER TABLE `customer` DROP INDEX `nameHebrew`
2016-11-06T10:58:11.869293Z	  400 Query	ALTER TABLE `customer` DROP INDEX `nameEnglish
```

I think it's a bug in the indices drop. I checked in decorator/index.ts, and it's passing alright.
Tried to understand where you actually drop the indices. I think it'll take less time for you :)

**Comment by pleerock** [comment] 2016-11-06 11:15
everything schema build related is [here](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts). Also make sure that you don't have renamed/removed js files left in the project, because lets say your customer was named "client.ts" and you renamed it to "customer.ts", and if client.js is left in the output folder, it will cause a problem because orm is reading all files from directory, and you'll have two entities: client and customer, one may try to override another

**Comment by AmirTugi** [comment] 2016-11-06 14:28
The problem is [here](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L344)
Something is calling this `changeColumns` even though there is no change.
How can we investigate it further?

**Comment by pleerock** [comment] 2016-11-06 14:35
> The problem is here
 it was obvious that you have such error from this line, but it does not mean that problem is there. 

To understand your problem better and investigate it further I need a minimal reproduction example. Please create a repo with minimal reproduction example to show the error and describe what is expected error. Also exclude any third party dependency including nodemon

**Comment by AmirTugi** [comment] 2016-11-06 17:36
[There you go](https://github.com/AmirTugi/TypeOrmIndexIssue)

I isolated it, and it occurs even with 1 index.

**Comment by pleerock** [comment] 2016-11-09 11:26
when first time I checkout this repo and tried to run it - it gave me this error. But once i stop it and re-run - it works okay, and I re-run it hundred of times - no error. I don't know how to reproduce this issue. Here is my log:

```shell
Umeds-MBP-2:clonned pleerock$ rm -rf TypeOrmIndexIssue/
Umeds-MBP-2:clonned pleerock$ git clone https://github.com/AmirTugi/TypeOrmIndexIssue
Cloning into 'TypeOrmIndexIssue'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 0), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
Umeds-MBP-2:clonned pleerock$ cd TypeOrmIndexIssue/
Umeds-MBP-2:TypeOrmIndexIssue pleerock$ npm i
arihav-api@1.0.0 /Users/pleerock/www/clonned/TypeOrmIndexIssue
├── @types/body-parser@0.0.33
├─┬ @types/express@4.0.33
│ ├── @types/express-serve-static-core@4.0.39
│ └─┬ @types/serve-static@1.7.31
│   └── @types/mime@0.0.29
├── @types/node@6.0.46
├─┬ body-parser@1.15.2
│ ├── bytes@2.4.0
│ ├── content-type@1.0.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├─┬ http-errors@1.5.0
│ │ ├── inherits@2.0.1
│ │ ├── setprototypeof@1.0.1
│ │ └── statuses@1.3.0
│ ├── iconv-lite@0.4.13
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.2.0
│ ├─┬ raw-body@2.1.7
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.13
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.12
│     └── mime-db@1.24.0
├─┬ express@4.14.0
│ ├─┬ accepts@1.3.3
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├── finalhandler@0.5.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.2
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.1.1
│ ├── range-parser@1.2.0
│ ├─┬ send@0.14.1
│ │ ├── destroy@1.0.4
│ │ └── mime@1.3.4
│ ├── serve-static@1.11.1
│ ├── utils-merge@1.0.0
│ └── vary@1.1.0
├─┬ mysql@2.12.0
│ ├── bignumber.js@2.4.0
│ ├─┬ readable-stream@1.1.14
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@0.0.1
│ │ └── string_decoder@0.10.31
│ └── sqlstring@2.2.0
├── reflect-metadata@0.1.8
├─┬ typeorm@0.0.2-alpha.69
│ ├── @types/lodash@4.14.35
│ ├── app-root-path@2.0.1
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├─┬ minimatch@3.0.3
│ │ │ └─┬ brace-expansion@1.1.6
│ │ │   ├── balanced-match@0.4.2
│ │ │   └── concat-map@0.0.1
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ ├── lodash@4.16.6
│ ├── moment@2.15.2
│ ├─┬ path@0.12.7
│ │ ├── process@0.11.9
│ │ └── util@0.10.3
│ ├── require-all@2.0.0
│ ├─┬ sha1@1.1.1
│ │ ├── charenc@0.0.1
│ │ └── crypt@0.0.1
│ ├─┬ url@0.11.0
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0
│ ├─┬ yargonaut@1.1.2
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├── figlet@1.2.0
│ │ └── parent-require@1.0.0
│ └─┬ yargs@5.0.0
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.0.0
│   ├── decamelize@1.2.0
│   ├── get-caller-file@1.0.2
│   ├── lodash.assign@4.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ ├── path-exists@2.1.0
│   │ │ └─┬ pinkie-promise@2.0.1
│   │ │   └── pinkie@2.0.4
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├── graceful-fs@4.1.10
│   │   │ ├─┬ parse-json@2.2.0
│   │   │ │ └─┬ error-ex@1.3.0
│   │   │ │   └── is-arrayish@0.2.1
│   │   │ ├── pify@2.3.0
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├─┬ normalize-package-data@2.3.5
│   │   │ ├── hosted-git-info@2.1.5
│   │   │ ├─┬ is-builtin-module@1.0.0
│   │   │ │ └── builtin-modules@1.1.1
│   │   │ ├── semver@5.3.0
│   │   │ └─┬ validate-npm-package-license@3.0.1
│   │   │   ├─┬ spdx-correct@1.0.2
│   │   │   │ └── spdx-license-ids@1.2.2
│   │   │   └── spdx-expression-parse@1.0.4
│   │   └── path-type@1.1.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── set-blocking@2.0.0
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ └─┬ is-fullwidth-code-point@1.0.0
│   │   └── number-is-nan@1.0.1
│   ├── which-module@1.0.0
│   ├── window-size@0.2.0
│   ├── y18n@3.2.1
│   └─┬ yargs-parser@3.2.0
│     └── camelcase@3.0.0
└── typescript@2.0.8

npm WARN arihav-api@1.0.0 No repository field.
Umeds-MBP-2:TypeOrmIndexIssue pleerock$ atom app.ts
Umeds-MBP-2:TypeOrmIndexIssue pleerock$ tsc
Umeds-MBP-2:TypeOrmIndexIssue pleerock$ npm start

> arihav-api@1.0.0 start /Users/pleerock/www/clonned/TypeOrmIndexIssue
> node app.js

executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test2'
executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test2'
executing query: SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'test2' AND INDEX_NAME != 'PRIMARY'
executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'test2' AND REFERENCED_COLUMN_NAME IS NOT NULL
executing query: SHOW INDEX FROM `customer` WHERE Key_name = 'PRIMARY'
executing query: START TRANSACTION
executing query: COMMIT
Server listening on port 3000 in development mode
```

Here is what configuration I put after running `atom app.ts`:
```typescript

    driver: {
        type: "mysql",
        host: "127.0.0.1",
        port: 3306,
        username: "root",
        password: "admin",
        database: "test2"
    },
    // Add all models automatically
    entities: [
        Customer
    ],
    // Keep database synced each run
    autoSchemaSync: true,
    logging: {
      logQueries: true
    }
```

**Comment by pleerock** [comment] 2016-12-02 05:48
I'll close it for now, because I could not reproduce this issue anymore. If someone will face same issue again please free to reopen it

**Closed by pleerock** 2016-12-02 05:48 UTC
Labels: needs more info

**Comment by Fokir** [comment] 2017-03-25 09:30
https://www.youtube.com/watch?v=8Q5ayD1219Y&feature=youtu.be
I recorded a small video showing this bug.
Perhaps the reason is that typeorm removes indexes? But this happens after the restart

**Comment by Fokir** [comment] 2017-03-25 09:33
With other databases everything is in order, only mariaDB and MySQL  deduce this error

**Comment by jossiwolf** [comment] 2017-04-09 17:00
I faced this issue; dropping and re-creating my db has helped:
```
MariaDB [(none)]> drop database menu;
Query OK, 4 rows affected (0.52 sec)
MariaDB [(none)]> create database menu
Query OK, 1 row affected (0.00 sec)
```

**Comment by Fokir** [comment] 2017-04-10 06:50
:D A strange solution to the problem.

**Comment by jossiwolf** [comment] 2017-04-10 14:59
@Fokir Yep, I saw #221 but there was no working solution for me. Good I'm still in development...
