### ISSUE TITLE
migration:run cli command breaks on 0.2.32 and onwards

### ISSUE THREAD

**Issue by laurynas-karvelis** [typeorm/typeorm#7776] opened 2021-06-21 11:15 UTC
## Issue Description
Unable to successfully run `typeorm migration:run` anymore. Running migrations used to work up until typeorm 0.2.32 version. Something has been changed in 0.2.32 version so that from this version and onwards running typeorm migrations run script fails resolving any local imports within defined entities.

### Expected Behavior

Running `ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run` command should run the migrations successfully.

### Actual Behavior

```
$ ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run
Error during migration run:
Error: Column "deviceType" of Entity "Entity2" is defined as enum, but missing "enum" or "enumName" properties.
    at /Users/<path-to-project>/database-service/src/metadata-builder/EntityMetadataValidator.ts:91:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/Users/<path-to-project>/database-service/src/metadata-builder/EntityMetadataValidator.ts:84:36)
    at /Users/<path-to-project>/database-service/src/metadata-builder/EntityMetadataValidator.ts:45:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/<path-to-project>/database-service/src/metadata-builder/EntityMetadataValidator.ts:45:25)
    at Connection.buildMetadatas (/Users/<path-to-project>/database-service/src/connection/Connection.ts:527:33)
    at Connection.<anonymous> (/Users/<path-to-project>/database-service/src/connection/Connection.ts:193:18)
    at step (/Users/<path-to-project>/database-service/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/<path-to-project>/database-service/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)

error Command failed with exit code 1.
```

Note: none of the files such as `src/metadata-builder/EntityMetadataValidator.ts`, `src/connection/Connection.ts` etc live under `/Users/<path-to-project>/database-service` dir.

### Steps to Reproduce

1. Create file `entities/entity-1.ts` with contents such as:
```
import { Entity, PrimaryGeneratedColumn } from 'typeorm';

// this exported enum will be imported by another entity as it is shared between multiple entities.
export enum MY_DEVICES_ENUM {
  DEVICE1 = 'DEVICE1',
  DEVICE2 = 'DEVICE2'
}

@Entity('entity1')
export class Entity1 {
  @PrimaryGeneratedColumn('uuid')
  id: string;

}
```

2. Create file `entities/entity-2.ts` with contents such as:
```
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
import { MY_DEVICES_ENUM } from './entity-1';

// IMPORTANT: console.log below will display `undefined` in the terminal while running `migration:run` cli ONLY.
console.log(MY_DEVICES_ENUM);

// IMPORTANT: imported variables such as Entity would be displayed by console.log as `[Function: Entity]` which is as expected.
console.log(Entity);

@Entity('entity2')
export class Entity2 {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'device_type', type: 'enum', enum: MY_DEVICES_ENUM })
  deviceType: MY_DEVICES_ENUM;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.20.1 | 
| Typescript version  | v4.3.4 | 
| TypeORM version     | v0.2.34 | 

### Additional Context

We have started using typeorm a while ago, have number of entities, number of migration scripts throughout our application's lifetime, every single time running migrations:run command worked like a charm for us. On our end nothing changed, config file, the application itself is unchanged. Simply moving from `typeorm @ 0.2.31` to `typeorm @ 0.2.32` and above breaks migration:run and exits with non-zero error code.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pekunicki** [comment] 2021-07-22 11:10
any update on that?

**Comment by AlexMesser** [comment] 2021-07-24 13:10
Duplicate of #6540

**Closed by AlexMesser** 2021-07-24 13:10 UTC
Labels: bug, comp: configuration, comp: migrations, requires triage
