### ISSUE TITLE
Migration and seed when working with mongodb

### ISSUE THREAD

**Issue by RafrafiDev** [typeorm/typeorm#1424] opened 2018-01-09 16:27 UTC
Hello all,

Please i would like to have some snipets of code that can help me to make migration as well as seeding some user data when working with mongodb.

i changed this in the .env file:
```
DB_TYPE="mongodb"
DB_HOST="localhost"
DB_PORT=27017
DB_DATABASE="mydb"

```
and changed the seed code like this:
```
export class CreateBruce implements SeedsInterface {

    public async seed(factory: FactoryInterface): Promise<any> {
        const em = await factory.getConnection().mongoManager;

        const user = new User();
        user.firstName = 'Bruce';
        user.lastName = 'Wayne';
        user.email = 'bruce.wayne@wayne-enterprises.com';
        return await em.save(user);
    }

}

```

but when i run :
npm run setup
i get : 
```
executing seed:   CreateBruce
Could not run seed TypeError: this.databaseConnection.collection is not a function
The script called "db.seed" which runs "nps banner.seed && nps config && ts-node -F ./src/lib/seeds/cli.ts" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "setup.db" which runs "nps db.seed" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stack-nodejs-fondative@1.0.0 start: `nps "setup.db"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stack-nodejs-fondative@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by angelsanchez** [comment] 2018-01-10 01:39
I have the same issue.

The problem is that the new mongodb version v3.x was recently released with breaking API changes. 
https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md

One of them is:
```
The legacy operation

MongoClient.connect('mongodb://localhost:27017/test', (err, db) => {
  // Database returned
});

is replaced with

MongoClient.connect('mongodb://localhost:27017/test', (err, client) => {
  // Client returned
  var db = client.db('test');
});

```

Using mongodb version `2.2.33` it works correctly.

**Comment by RafrafiDev** [comment] 2018-01-10 09:06
Thanks for the reply, actually when i downgrade the version of mongodb to `2.2.33` i get this error when i try to seed
`Could not connection to database MongoError: Server at localhost:27017 reports wire version 0, but this version of Node.js Driver requires at least 2 (MongoDB2.6).`

**Comment by pleerock** [comment] 2018-01-10 09:21
what is `seed` here?

**Comment by RafrafiDev** [comment] 2018-01-10 09:26
when i run `npm run setup` it should iterate over all files in the `database/seeds` directory and start to insert data in the database.

I just want to use TypeORM with MongoDB

**Closed** 2018-01-10 11:05 UTC

**Comment by snaquaye** [comment] 2018-01-16 15:14
@angelsanchez, what version of mongodb server are you using.
@pleerock are there any hope to fix the mongodb connection issue with version "^3.0.1"

Thanks

**Comment by shalomsam** [comment] 2018-02-14 18:10
@pleerock - I can't seem to find any docs on seeding or running migrations programmatically. So I can do something similar to this - 
```
knex.migrate.rollback()
      .then(() => {
           return knex.migrate.latest();
      })
      .then(() => {
           return knex.seed.run();
      });
```
in my test cases ([ref](https://www.valentinog.com/blog/test-driven-api-koa-2-mocha-chai/)).

Is this currently possible? or are there plans to support such implementation?

**Comment by pleerock** [comment] 2018-02-15 05:07
@shalomsam what exactly you are interested in? There are methods in `connection` which you can use to run your migrations in the case if you don't want to use CLI.

**Comment by shalomsam** [comment] 2018-02-15 06:08
@pleerock - Thanks for the prompt reply. 
 I'm interested in being able to run basic seeding/migration on a test database before running my test cases. Obviously, I want to achieve this programmatically in my test bootstrap code.

you can have look at the test cases mentioned in this tutorial [here](https://www.valentinog.com/blog/test-driven-api-koa-2-mocha-chai/). Specifically, the code snippet mentioned above (in my previous comment). I want to be able to implement something similar.

Also, can you point me to the docs for the connection methods you are talking about?

**Comment by pleerock** [comment] 2018-02-15 06:12
There won't be docs for such specific things, just take a look on a Connection class and what methods it provides and you'll find `runMigrations` method you need.

**Comment by vickyhere** [comment] 2018-11-30 18:22
(node:1555) UnhandledPromiseRejectionWarning: MongoError: Server at localhost:27017 reports wire version 0, but this
 version of Node.js Driver requires at least 2 (MongoDB2.6).

Please help!!

**Comment by havenchyk** [comment] 2018-11-30 20:16
@vickyhere please, create a new issue with a proper explanation and example
