### ISSUE TITLE
Can't use find operators when using transformers

### ISSUE THREAD

**Issue by marines** [typeorm/typeorm#6289] opened 2020-06-21 20:02 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create an entity with a number column having a from/to transformer (in my case it was number to string and string to number conversion)
1. Query the entity with a Find Operator (eg. LessThan, Between)

You'll get the error:
```
SELECT "Entity"."column" AS "Entity_column" 
FROM "Entity" "Entity" 
WHERE "Entity"."column" = $1 -- PARAMETERS: ["[object Object]"]
error: error: invalid input syntax for integer: "[object Object]"
```

The issue lays in `getEntityValue` in `ColumnMetadata.ts`:

```
if (transform && this.transformer)
    value = ApplyValueTransformers.transformTo(this.transformer, value);
```
the transformation occurs for the FindOperator object instead of its values hence the [object Object] in the query.

**Comment by imnotjames** [comment] 2020-10-16 06:27
duplicate of #4399

**Closed by imnotjames** 2020-10-16 06:27 UTC
Labels: bug, driver: postgres
