### ISSUE TITLE
TypeOrm 8 exits while checking for hstore extension on a readonly connection because of CREATE EXTENSION

### ISSUE THREAD

**Issue by pvogel1967** [typeorm/typeorm#7446] opened 2021-03-02 21:29 UTC
## Issue Description

For performance reasons, we have a read-replica, Read Only, of course (RO) as well as a read-write connection to our DB.  One of the columns in that DB is an hstore column.  With typeOrm 7 we got a single warning that it wasn't able to install the hstore extension (which is, of course, already there!) in the RO DB connection.  With type ORM 8 it won't even successfully complete the connection and just constantly throws warnings.

The cause can be seen here in https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts

```
            try {
                await this.executeQuery(connection, `CREATE EXTENSION IF NOT EXISTS "hstore"`);
            } catch (_) {
                logger.log("warn", "At least one of the entities has hstore column, but the 'hstore' extension cannot be installed automatically. Please install it manually using superuser rights");
            }
```

Which is *obviously* going to fail every time on a RO DB since the CREATE call fails due to the DB being RO before it gets along to see that it it exists.

### Expected Behavior

I actually *expected* a way to tell typeOrm "this connection is read only" and have it not attempt any write operations on that connection.  We're careful in our code to not attempt any write ops on the RO Repo but it would be nice to have the protection.  That said, at the very least there needs to be a way to say "this is a production DB, don't try to install anything that isn't already there!"

### Actual Behavior

Lots of warnings of this type:
```
At least one of the entities has hstore column, but the 'hstore' extension cannot be installed automatically. Please install it manually using superuser rights
```
followed by container death.

### Steps to Reproduce

1. Create an entity with an hstore column
2. Create a connection to a read-replica PG DB (or just any PG db with a user that has Read-only permissions on the DB)
3. Create a repo for the given entity that uses the connection from step 2

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.15.5 | 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.20 | 
| PG driver lib version | 8.3.0 |
| NestJS version | 7.6.11 |
| NestJS/typeOrm | 7.1.5 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-07-07 17:08
Duplicate of #7662

**Closed by imnotjames** 2021-07-07 17:08 UTC
Labels: bug, driver: postgres, requires triage
