### ISSUE TITLE
Repository Find with Sort and Relations causes SELECT DISTINCT (of subquery)

### ISSUE THREAD

**Issue by KoenLav** [typeorm/typeorm#8231] opened 2021-09-30 18:38 UTC
## Issue Description
Calling Repository Find on an Entity which has a ManyToOne or ManyToMany relationship (possibly also others), whilst setting the limit to a high value (OR sorting), will produce a Query like:

### Actual Behavior
```
SELECT DISTINCT `distinctAlias`.`Chat_id` as "ids_Chat_id" FROM (SELECT `Chat`.`id` AS `Chat_id`, `Chat`.`type` AS `Chat_type`, `Chat`.`organizerId` AS `Chat_organizerId`, `Chat`.`lastMessageId` AS `Chat_lastMessageId`, `Chat`.`createdAt` AS `Chat_createdAt`, `Chat`.`updatedAt` AS `Chat_updatedAt`, `Chat`.`deletedAt` AS `Chat_deletedAt`, `Chat`.`momentId` AS `Chat_momentId` FROM `chat` `Chat` LEFT JOIN `user_chat` `userChats` ON `userChats`.`chatId`=`Chat`.`id` AND (`userChats`.`deletedAt` IS NULL) WHERE ( ((`userChats`.`read` IS FALSE) AND (`userChats`.`userId` = ?)) ) AND ( `Chat`.`deletedAt` IS NULL )) `distinctAlias` ORDER BY `Chat_id` ASC LIMIT 101
```

After that a similar query to the query below is executed (but selecting based on ID rather than the other WHERE clauses).

The select DISTINCT is an issue for two reasons:
- two Queries are executed instead of one (minor issue);
- the subquery tends to result in the creation of a temporary table for large datasets (major issue);

### Expected Behavior
We expect a 'normal' query instead of a two-stage query where we first get the IDs and then fetch the (sorted) data with relations.

```
SELECT `Chat`.`id` AS `Chat_id`, `Chat`.`type` AS `Chat_type`, `Chat`.`organizerId` AS `Chat_organizerId`, `Chat`.`lastMessageId` AS `Chat_lastMessageId`, `Chat`.`createdAt` AS `Chat_createdAt`, `Chat`.`updatedAt` AS `Chat_updatedAt`, `Chat`.`deletedAt` AS `Chat_deletedAt`, `Chat`.`momentId` AS `Chat_momentId` FROM `chat` `Chat` LEFT JOIN `user_chat` `userChats` ON `userChats`.`chatId`=`Chat`.`id` WHERE (`userChats`.`read` IS FALSE) AND (`userChats`.`userId` = ?) AND (`userChats`.`deletedAt` IS NULL) AND ( `Chat`.`deletedAt` IS NULL ) ORDER BY `Chat`.`Chat_id` ASC

```

### Steps to Reproduce

The easiest way to reproduce for us was simply calling findOne on our User entity with the Roles relation and looking at the query log. findOne limits to 1, and for some reason also sorts by ID. Replacing findOne with find and the problem goes away.

```typescript

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToMany(() => Role, (role) => role.users, {
    onDelete: 'CASCADE',
    nullable: true,
  })
  @JoinTable({
    name: 'user_roles',
  })
  roles: Role[];
}

Entity()
export class Role {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToMany(() => User, (user) => user.roles, {
    onDelete: 'CASCADE',
    nullable: true,
  })
  users: User[];
}

UsersRepository.findOne({ where: { email: 'mail@test.com' } }); // This will trigger SELECT DISTINCT
UsersRepository.find({ where: { email: 'mail@test.com' } })[0]; // This will not trigger SELECT DISTINCT
```

### My Environment

| Dependency          | Version  |
| TypeORM version     | 0.2.37  |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| `mysql`              | yes           |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by KoenLav** [comment] 2021-09-30 20:58
Minimal reproduction: https://github.com/KoenLav/node-typescript-typeorm-starter

**Comment by dvantage** [comment] 2022-01-08 00:06
In my opinion this is a very important problem, will there be any fixes?

**Comment by cduff** [comment] 2022-03-24 11:18
Duplicate of https://github.com/typeorm/typeorm/issues/5694?

**Comment by Ginden** [comment] 2022-03-24 22:45
@cduff Yes, it is. I'm closing.

**Closed by Ginden** 2022-03-24 22:45 UTC
Labels: bug, requires triage
