### ISSUE TITLE
MongoDB: hidden columns are not considered

### ISSUE THREAD

**Issue by glutengo** [typeorm/typeorm#7710] opened 2021-06-04 07:50 UTC
## Issue Description

The hidden columns feature does not seem to work when using MongoDB. I have tried to mark a column as hidden by adding the `select: false` option in the `Column()` annotation, but the associated property is part of the returned data anyways.

From what I have found, this option is interpreted for SQL based connectors [here](https://github.com/typeorm/typeorm/blob/36ceefa710c0994e054c8e267a1fb1bdf4b25c39/src/query-builder/SelectQueryBuilder.ts#L1779) and there seems to be no equivalent in MongoEntityManager.

### Expected Behavior

Property `hidden` is not included in the resultset

### Actual Behavior

Property `hidden` is included in the resultset

### Steps to Reproduce

1. Annotate a field with `@Column({ select: false })`
2. Connect to MongoDB
3. Query the entity via `EntityManager.findOne()`

I have also set up a minimal reproduction of this here: https://github.com/glutengo/typeorm-mongodb-select-false
The simplest way to reproduce this is checking out the repository, running `npm install` and `npm start`.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS 11.3 |
| Node.js version     | v12.15.0 | 
| Typescript version  | v4.3.2 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cyyjs** [comment] 2021-06-15 07:07
Is it resolved?

**Comment by glutengo** [comment] 2021-06-15 07:41
@cyyjs no, and I have not been working on it either, the referenced commits are in another project which now uses a workaround. The workaround is to not use the hidden column feature but remove the password before serializing it for the REST response instead.

**Comment by SnapeEye** [comment] 2021-06-18 08:45
@glutengo
Not a solution, but (maybe) another workaround: you can use [class-transformer](https://www.npmjs.com/package/class-transformer) package to remove some fields of your entity from your response.


`import { Exclude } from 'class-transformer';`
`@Entity('positions')`
`export class User {`
`   ...`
`  @Exclude({ toPlainOnly: true })`
`  password: string;`
`   ...`
`}`

Also, should add this call to your bootstrap function (if using NestJS):
`async function bootstrap() {`
`  ...`
`  app.useGlobalInterceptors(new TransformInterceptor());`
`  ...`
`  await app.listen(PORT);`
`}`

And here is TransformInterceptor class file:
`import {`
`  CallHandler,`
`  ExecutionContext,`
`  Injectable,`
`  NestInterceptor,`
`} from '@nestjs/common';`
`import { Observable } from 'rxjs';`
`import { map } from 'rxjs/operators';`
`import { classToPlain } from 'class-transformer';`
``
`@Injectable()`
`export class TransformInterceptor implements NestInterceptor {`
`  intercept(`
`    context: ExecutionContext,`
`    next: CallHandler<any>,`
`  ): Observable<any> | Promise<Observable<any>> {`
`    return next.handle().pipe(map((data) => classToPlain(data)));`
`  }`
`}`

**Comment by glutengo** [comment] 2021-06-21 06:23
@SnapeEye thanks. Yes, I have used ClassTransformer in my workaround too.

**Comment by imnotjames** [comment] 2021-07-05 01:34
Duplicate of #5537

**Closed by imnotjames** 2021-07-05 01:34 UTC
Labels: bug, driver: mongodb, requires triage
