### ISSUE TITLE
If you are using SnakeNamingStrategy of "typeorm-naming-strategies" library, then you can't use entity classes for getting repositories if their name is not in snake case.

### ISSUE THREAD

**Issue by gtpan77** [typeorm/typeorm#6509] opened 2020-08-04 09:53 UTC
If you are using SnakeNamingStrategy of "typeorm-naming-strategies" library, then you can't use entity classes for getting repositories if their name is not in snake case.
I created a entity class UserLedger.
`import { UserLedger } from "../entity/UserLedger";`
`this.userLedger = getRepository(UserLedger);`
It was failing and throwing error. RepositoryNotFoundError: No Repository for "UserLedger" was found.

changed the entity name to "user_ledger", it fixed the issue.
`this.userLedger = getRepository("user_ledger");`

_Originally posted by @gtpan77 in https://github.com/typeorm/typeorm/issues/5064#issuecomment-668500256_

**Comment by korolariya** [comment] 2020-08-25 16:12
I have same problem

**Comment by imnotjames** [comment] 2020-10-02 14:16
I believe this is a duplicate of #5676 - let me know if you think it's different, though.

**Closed by imnotjames** 2020-10-02 14:16 UTC
