### ISSUE TITLE
[Postgres] Fails to drop indexes when removing fields

### ISSUE THREAD

**Issue by lktvlm** [typeorm/typeorm#197] opened 2017-01-13 13:28 UTC
Version typeorm@0.0.7-alpha.7

I had a class with column
`@Column({type: "text", nullable: true})`
`@Index()`
`text2: string;`
Removing this column leads to error while deleting index:
- <...>
- executing query: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name  FROM pg_class t, pg_class i, pg_index ix, pg_attribute a
- WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
- AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ('type_test_post') ORDER BY t.relname, i.relname
- <...>
> Result - index exists:
> type_test_post	ind_5701659c6d9617e3cb8100b9eb4	likesCount
> type_test_post	ind_9c4cdb13eec7ef29ee990c9dafd	text3
> type_test_post	ind_d8ff91f7221b6df7c5b684ffa9c	title
> type_test_post	ind_ebfa1f9180c7d7b54861cc1afc2	text2
> type_test_post	my_index_with_id_and_title	title
> type_test_post	my_index_with_id_and_title	id
> type_test_post	type_test_post_pkey	id
- columns dropped in type_test_post: text3
- **executing query: ALTER TABLE "type_test_post" DROP "text3"**
- dropping an index: ind_9c4cdb13eec7ef29ee990c9dafd
- executing query: DROP INDEX "ind_9c4cdb13eec7ef29ee990c9dafd"
- **query failed: DROP INDEX "ind_9c4cdb13eec7ef29ee990c9dafd"**
- executing query: ROLLBACK
- Cannot connect:  { error: **index "ind_9c4cdb13eec7ef29ee990c9dafd" does not exist**

It probably should drop indexes **first**, and only then drop the column.

**Comment by lktvlm** [comment] 2017-01-13 13:33
I tried to make a clean test with a new class and a new column, but then the order was correct.
Probably there is a possibility of both a correct order and an incorrect order in the code depending on something.

**Comment by pleerock** [comment] 2017-01-14 05:00
yeah catching bug in schema sync is difficult because process is different each time. I need more clear steps how to reproduce this issue from the beginning, e.g. schema create first time, then "x" change and it works, then "y" change and it breaks.

**Comment by lktvlm** [comment] 2017-01-14 13:15
Here you go.
First create a column, sync:
>@Column({nullable: true})
>text6: string;
then add an index, sync:
> @Column({nullable: true})
> @Index()
> text6: string;
then remove the column, sync, and:
- executing query: START TRANSACTION
- columns dropped in type_test_post: text6
- executing query: ALTER TABLE "type_test_post" DROP "text6"
- dropping an index: ind_29b466931b1cf72c989b508c0f1
- executing query: DROP INDEX "ind_29b466931b1cf72c989b508c0f1"
- executing query: ROLLBACK
- query failed: DROP INDEX "ind_29b466931b1cf72c989b508c0f1"
- Cannot connect:  { error: index "ind_29b466931b1cf72c989b508c0f1" does not exist

**Comment by pleerock** [comment] 2017-09-14 07:25
fixed by @iz-iznogood  and will be released in next version

**Closed by pleerock** 2017-09-14 07:25 UTC
Labels: comp: schema, needs more info
