### ISSUE TITLE
The constraint "PK_a5fe83964f34a57c8b12fe7fda5" dosen't exist in postgres

### ISSUE THREAD

**Issue by matrixcloud** [typeorm/typeorm#6654] opened 2020-09-01 06:47 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Set synchronize = true, then create connection.

> Try to upgrade the legacy table definition.

Checked table definition, got the primary key name is `gw_resource_pkey`.
When Typeform tries to call changeColumn method, it generates a default random primary key name "PK_a5fe83964f34a57c8b12fe7fda5".

Is there a way to disable this?

Thanks.

**Comment by imnotjames** [comment] 2021-07-16 19:08
Duplicate of #4008

**Closed by imnotjames** 2021-07-16 19:08 UTC
Labels: bug, driver: postgres
