### ISSUE TITLE
TypeORM Attempts to create tables that already exist

### ISSUE THREAD

**Issue by pburrows** [typeorm/typeorm#2782] opened 2018-09-09 15:05 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

If I delete all the tables in my database and run my app, all tables are created successfully.
If I then stop the app and restart it, typeorm attempts to create tables that already exist and then fails. 

Here is the output from TypeOrm for the second run:
![image](https://user-images.githubusercontent.com/589029/45265855-c95b7480-b41f-11e8-8c4a-5762884658c5.png)

Here is the beginning of the definition for the EmployeeAvailabilities table (there are more columns than this):

```
@Entity('EmployeeAvailabilities', {schema: 'dbo'})
@Index('IX_EmployeeId', ['employee'])
export class EmployeeAvailability {

    @PrimaryGeneratedColumn({

        name: 'EmployeeAvailabilityId',
    })
    public employeeAvailabilityId: number;

    @ManyToOne(() => Employee, (employee: Employee) => employee.employeeAvailabilitiess, {  nullable: false, onDelete: 'CASCADE' })
    @JoinColumn({ name: 'EmployeeId'})
    public employee: Employee | null;
}
```

At first I thought the issue was because the class name and table name do not match. But if I make the class name and table name match, the issue still occurs.

**Comment by jondediego** [comment] 2018-09-13 13:04
Check if you have synchronize connection option set to true. I think it shouldn't be set to true for the second time

**Comment by Kononnable** [comment] 2018-12-15 18:09
Guys please provide simple schema on which this bug occurs. I will look into it but need complete schema definition. If possible make it as a PR with failing test or paste schema here. 

Example of how to make such test easily in #3257 - just need to change entities and description.

**Comment by pleerock** [comment] 2018-12-21 15:40
Im going close this one. This is most likely not our issue. If someone has this issue please create a new issue and attach reproduction repo.

**Closed by pleerock** 2018-12-21 15:40 UTC
Labels: comp: schema sync, driver: mssql

**Comment by darkyelox** [comment] 2019-02-20 14:37
I had the same problem but using Nativescript-sqlite with a simplem connection:

```typescript
console.log('Creating Connection')

const connection = await createConnection({
    name: 'default',
    database: 'synchrony.db',
    type: 'nativescript',
    driver,
    entities: [
        PushNotification,
        Slide,
        SlideImage,
        UserProgressInfo,
        UserSynchronizationChartData,
        UserPodcastHistory,
        UserRecent,
        Session,
        User,
        Country,
        CountryName,
        Podcast,
        Practice,
        Audio,
        Mentor,
        ProgramType,
        Program,
        ProgramsGroup,
        MentorsGroup,
        Category,
        FAQ,
        Tag,
        Membership,
    ],
    // logging: this.config.debug,
    // synchronize: this.config.debug
})

console.log("Connection Created!")

// setting true will drop tables and recreate
await connection.synchronize(false)

```

The first time the app runs everything goes fine, but the second time this code runs it throws:

```
JS: QueryFailedError: android.database.sqlite.SQLiteException: table "push_notification" already exists (code 1): , while compiling: CREATE TABLE "push_notification" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "body" varchar NOT NULL, "timestamp" datetime NOT NULL, "type" varchar NOT NULL, "action" varchar)
JS:     android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
JS:     android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
JS:     android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
JS:     android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
JS:     android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
JS:     android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
JS:     android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
JS:     android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
JS:     android.database.sqlite.SQL...
```

But the database and the app runs without any problem, is like the driver is not running some query check for know if the tables already exists before running a create query.

I don't know if this is sufficient for creating a new issue like @pleerock points.

**Comment by unluckykc** [comment] 2019-06-26 19:34
It seems to happen when entities make a loop :

- Entity A has a ManyToOne relation to Entity C
- Entity B has a ManyToOne relation to Entity C
- Entity A and B have a direct or indirect relation (via Entity D for example)

Then Entity C table produces the ER_TABLE_EXISTS_ERROR.

I had 3 tables producing the bug on : Windows - libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $ (Wamp 3.1.7 - 64bit).

I used the workaround of dropping the tables before restarting node then putting my data back all the afternoon, but I just figured out it stopped producing the error when removing a relation from the "loop".

Also, I ususally work on a mysql database on a debian 8 server and it doesn't produce the error (I can't access this database from home right now, I worked from home this afternoon). It happens from time to time on the debian dev server but dropping the tables once usually solves the problem.

**Comment by exequielc** [comment] 2019-12-09 11:22
> I had the same problem but using Nativescript-sqlite with a simplem connection:
> 
> ```ts
> console.log('Creating Connection')
> 
> const connection = await createConnection({
>     name: 'default',
>     database: 'synchrony.db',
>     type: 'nativescript',
>     driver,
>     entities: [
>         PushNotification,
>         Slide,
>         SlideImage,
>         UserProgressInfo,
>         UserSynchronizationChartData,
>         UserPodcastHistory,
>         UserRecent,
>         Session,
>         User,
>         Country,
>         CountryName,
>         Podcast,
>         Practice,
>         Audio,
>         Mentor,
>         ProgramType,
>         Program,
>         ProgramsGroup,
>         MentorsGroup,
>         Category,
>         FAQ,
>         Tag,
>         Membership,
>     ],
>     // logging: this.config.debug,
>     // synchronize: this.config.debug
> })
> 
> console.log("Connection Created!")
> 
> // setting true will drop tables and recreate
> await connection.synchronize(false)
> ```
> 
> The first time the app runs everything goes fine, but the second time this code runs it throws:
> 
> ```
> JS: QueryFailedError: android.database.sqlite.SQLiteException: table "push_notification" already exists (code 1): , while compiling: CREATE TABLE "push_notification" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "body" varchar NOT NULL, "timestamp" datetime NOT NULL, "type" varchar NOT NULL, "action" varchar)
> JS:     android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
> JS:     android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
> JS:     android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
> JS:     android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
> JS:     android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
> JS:     android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
> JS:     android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
> JS:     android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
> JS:     android.database.sqlite.SQL...
> ```
> 
> But the database and the app runs without any problem, is like the driver is not running some query check for know if the tables already exists before running a create query.
> 
> I don't know if this is sufficient for creating a new issue like @pleerock points.

Hi, I'm facing the same issue here, and I'm wonder if you already solved this issue?

**Comment by spedy** [comment] 2020-03-28 17:10
I had the same issue, the problem was that the user I was connecting did not have the some rights.

**Comment by mosilver** [comment] 2020-04-09 09:02
I'm trying to use nestJs admin:
[https://github.com/Theodo-UK/nestjs-admin](https://github.com/Theodo-UK/nestjs-admin)

and with second build app I get error:
**QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'adminuser' already exists**

**Comment by kingdevnl** [comment] 2020-05-06 16:08
@mosilver Yep with NestJS TypeORM module its doing the same for me

**Comment by maxmumford** [comment] 2020-06-18 17:43
As mentioned in #4420, using lowercase only in table names fixed this for me.

**Comment by dokodream** [comment] 2020-07-04 07:01
> As mentioned in #4420, using lowercase only in table names fixed this for me.
> 
> edit:
> Oh and I only had this issue on Windows, not mac!

Thank you very much. Your way solves a big problem for me

**Comment by alive2** [comment] 2020-07-30 13:30
I have the same problem as op (same driver), I noticed that typeorm fails to check if the table exists **only** when 'schema' is defined in the @Entity.

**Comment by exequielc** [comment] 2020-07-30 14:17
In my schema can't modify all tables with lowercase name, I'm wonder if there is another solution now?

**Comment by linxiaowu66** [comment] 2020-09-13 14:01
any solution?

**Comment by andy008** [comment] 2020-11-17 02:52
Same problem, running on Windows. Tried lowercase. No @schema. 
"There is already an object named... in the database"

**Comment by kingdevnl** [comment] 2020-11-17 06:13
For me lowercase works uppercase dousn't work

**Comment by verycosy** [comment] 2020-11-21 06:53
> For me lowercase works uppercase dousn't work

me either

**Comment by kingdevnl** [comment] 2020-11-21 12:43
I'm sure this problem was once fixed before...

**Comment by HowToShake** [comment] 2020-11-21 23:07
In my case  I have removed node_modules directory, dist directory, and package.json file from my project. Then I run `npm install` and run using `ts-node -p <path_to_your_project> && ts-node dist/<path_to_main_file(like index.js/server.js)>` i.e. `ts-node -p . && ts-node dist/server.js`. After that everything goes fine!

**Comment by qinghua5453** [comment] 2020-11-27 06:22
数据库的表 不能大写，大写就出现如上报错，改成小写就可以了，亲测有效，折腾了一天，午觉都睡不着。

**Comment by verycosy** [comment] 2020-11-27 06:44
> 数据库的表 不能大写，大写就出现如上报错，改成小写就可以了，亲测有效，折腾了一天，午觉都睡不着。

You mean lower case table naming is convention? Or mandatory?

**Comment by JulianH99** [comment] 2021-01-12 16:37
Setting `lower_case_table_names` to 1 in `my.cnf` doens't help at all. Only fails on mac, by the way, but I cannot name my tables with only lowercase either. Any solution so far?

**Comment by elie222** [comment] 2021-01-17 12:24
Facing same issue on CI. Synchronise is set to false yet first migration fails :(

**Comment by ewrfedf** [comment] 2021-05-07 13:03
`"strictNullChecks": false,`

remove this in tsconfig.js

**Comment by albertoruizmb** [comment] 2021-05-18 23:56
My issue was related to this setting in ormconfig:
- synchronize: true
- migrationsRun: true

You should only set it to true on one of them, but not on both

**Comment by tahir-jamil** [comment] 2021-07-04 22:41
migrationsRun: true
this works for me on windows

**Comment by isaacamehgreg** [comment] 2022-01-01 14:34
I had this problem,
it appears TypeOrm doesn't like table name with any capitalization

solution: USE LOWERCASE name for your table name.
worked for me

**Comment by CGerAJ** [comment] 2022-01-06 07:16
crazy,pls change to name or names, i do it , is run

**Comment by millionkn** [comment] 2022-05-27 03:36
****

```
{
//...
database: 'viewModal',
}
```
to
```
{
//...
database: 'view_modal', //not 'viewModal',
}
```

it works in my project

**Comment by Qwesaqwes** [comment] 2022-06-24 12:30
I had both package @nestjs/typeorm and typeorm installed in my project.

I removed typeorm from it and now is working without a problem

**Comment by vikaskandari** [comment] 2023-01-24 15:04
I am having same issue 

```typescript
@Entity("User") <-- this does not work
```
but

```typescript
@Entity("user") <-- this works
```

with capital case and synchronize on  it throws error table already exists

**Comment by LIyu2001** [comment] 2023-02-27 08:21
我也是这种问题,后来我发现我在定义实体的时候
`import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

/**
 * 健身器材类型实体
 */
@Entity('equType')
export class Equtype {
  @ApiProperty({ description: 'id' })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({ description: '类型名称' })
  @Column({ length: 255 })
  name: string;

  @ApiProperty({ description: '类型描述' })
  @Column({ length: 999 })
  scr: string;

  @ApiProperty({ description: '状态:0-未启用,1-启用' })
  @Column({ type: "enum", enum: [0, 1], default: 1 })
  status: number;

  @CreateDateColumn()
  add_time: Date
}`

@Entity里注册使用了驼峰命名，我后来改成小写，就解决了这个问题:
before:
`@Entity('equType')`

after:
`@Entity('equtype')`

**Comment by CGerAJ** [comment] 2023-04-03 09:35
> crazy,pls change to name or names, i do it , is run

All database table names must be lowercase, this problem is only on the window operating system

**Comment by shenghy** [comment] 2023-04-08 23:59
错误的写法(wrong spelling)
` TypeOrmModule.forRoot({
      type:'mysql',           // 数据库类型
      host:'localhost',       // 数据库的连接地址host
      port:3306,              // 数据库的端口 3306
      username:'root',        // 连接账号
      password:'root123',     // 连接密码
      database:'honglangman', // 连接的表名
      retryDelay:500,         // 重试连接数据库间隔
      retryAttempts:3,       // 允许重连次数
      synchronize:true,       // 是否将实体同步到数据库
      autoLoadEntities:true,  // 自动加载实体配置，forFeature()注册的每个实体都自己动加载
    }),`

**Comment by Vittor-Javidan** [comment] 2023-04-11 14:40
> 

if you notice, syncronize is commented. I'm not using it

**Comment by 1mehdifaraji** [comment] 2023-05-22 04:08
My mistake was I was calling ```initialize``` twice in my express app .
```
import { dataSource } from "@config/db";

dataSource.initialize();
```
Took me an hour but made sure it only ran once and the problem got fixed eventually .

**Comment by esrefatak** [comment] 2023-09-09 22:58
This problem occurs in MySQL. No problem in PostgreSQL.

**Here is the solution. Tested and verified :)**

Specify a physical table name by using name property of Entity in lowercase.

```
@Entity({name: "message_entry"})
export class MessageEntry extends Base
{
...
}
```

Names of columns can be in upper or lowercase.

**Comment by GoGeChang** [comment] 2023-12-15 03:59
问题已解决。

总结：实体或者表名用了驼峰所以报错，统一改成全小写或者下划线连接。

我总结的博客：https://www.cnblogs.com/gogechang/p/17894865.html



The problem has been resolved.
Summary: The entity or table name used a camel hump, so an error was reported. Please change it to all lowercase or use an underline connection.
My summary blog: https://www.cnblogs.com/gogechang/p/17894865.html

**Comment by iamnnort** [comment] 2024-02-29 21:32
Solved the issue by removing special characters from a table name: 

Renaming "db.name" => "db_name" solved the issue in my case.

**Comment by ngvcanh** [comment] 2024-03-27 14:03
In my case the`dataSource.initialize()` function was called twice.

<img width="626" alt="Screenshot 2024-03-27 at 20 59 23" src="https://github.com/typeorm/typeorm/assets/13740899/c113fe06-ca7f-471e-bde8-17338eefbd6a">

And `database.connect()` was called in another global middleware function for NextJS.

I removed the `connect` call inside the `init` method and it fixed the error.

**Comment by Kaabvoo** [comment] 2024-04-30 18:52
I think I'm having the same issue, this is my datasource
``` Typesript
export const options: DataSourceOptions = {
    type: 'sqlite',
    database: 'db/data.db',
    entities: ['dist/**/**/*.entity{.js, .ts}'],
    migrations: ['dist/db/migrations/*.js'],
    synchronize: false
}
```
This is my only Entity "User"

``` TS
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    // @Column()
    // forename: string
}
```

Then I auto-generate the first migration using `migration:generate`, This is the output of the migration 

`await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL)`);`

Which is OK, but the problem happens on the second migration...

now the Entity looks like this

``` TS
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @Column()
    forename: string // Added this new field
}
```

and the migration output become almos the same

`await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "forename" varchar NOT NULL)`);`

It contains the Create Table which it was already created...

this is my folder organization...

![image](https://github.com/typeorm/typeorm/assets/19362583/de2a5755-4908-4761-8596-6a01d9ae14d8)

Thanks in advice! <3

**Comment by awash59** [comment] 2025-02-01 02:21
@Vittor-Javidan https://nodejser.space/questions/secure-access-using-android-and-nodejs

**Comment by neljohncereradeveloper** [comment] 2025-02-04 03:28
> As mentioned in [#4420](https://github.com/typeorm/typeorm/issues/4420), using lowercase only in table names fixed this for me.
> 
> edit: Oh and I only had this issue on Windows, not mac!

this solves for me. thank you
