### ISSUE TITLE
Error: Uncaught (in promise): Error: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by davidmpaz** [typeorm/typeorm#1530] opened 2018-01-30 10:49 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Inside an ionic application I create the connection and populate it with data. My models contains relations from `Product` going down to other models, this mean in `Product` model I set up relation with cascade insert/updates so I only need to hydrate products and save instead saving all models separately.

Connection setup:
```typescript
if (isBrowser(this.platform)) {
    dbOptions = {
        type: 'sqljs',
        autoSave: true,
        location: 'products',
    } as SqljsConnectionOptions;
}

return createConnection(Object.assign(dbOptions, {
    entities: this.getModelsToLoad(),
    synchronize: true,
    logging: true,
}));
```

After I populate database everything works fine, and then after I reload page, i can see queries ran in console, because `synchronize: true`, i assume. Last query is:
```
executing query:  CREATE TABLE "temporary_product" ("identifier" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "id" varchar NOT NULL, ....)
executing query:  INSERT INTO "temporary_product"("identifier", "id", ....) SELECT "identifier", "id", ... FROM "product"
executing query:  DROP TABLE "product"
executing query:  ROLLBACK
```
than I receive the error.

Could you guys help me on how to overcome this. My expected outcome would be that I can use same data after a page reload, since that's happens a lot when developing in browser an ionic app. Foreign keys enabled are not allowing me to re-initialize database again from existent data.

Thanks in advance,
David

**Comment by pleerock** [comment] 2018-01-31 06:07
@daniel-lang do you have something in mind?

**Comment by giorgiofellipe** [comment] 2018-03-01 05:30
Any workaround?

**Comment by AlexMesser** [comment] 2018-03-02 08:05
please check this issue on latest `@next` version, it should be fixed

**Comment by daniel-lang** [comment] 2018-03-02 08:15
so #1536 is no longer needed?

**Comment by davidmpaz** [comment] 2018-03-02 10:36
@daniel-lang, @pleerock, @AlexMesser thanks for taking care of this!

I will be back from holidays next Monday. I will  also take a look under my environment.

Cheers

**Comment by daniel-lang** [comment] 2018-03-02 19:50
I can confirm, that it works with `sql.js` using `typeorm@0.2.0-alpha.25`

**Comment by pleerock** [comment] 2018-03-03 17:14
@giorgiofellipe same you mean works using latest next?

**Comment by giorgiofellipe** [comment] 2018-03-03 17:42
@pleerock sorry, meant that the error occurs with `cordova`.

**Comment by pleerock** [comment] 2018-03-03 17:47
try with latest `next`

**Comment by giorgiofellipe** [comment] 2018-03-03 18:58
I can't do it right now but will asap and tell you.

**Comment by davidmpaz** [comment] 2018-03-05 16:33
Hi,

> I can confirm, that it works with `sql.js` using typeorm@0.2.0-alpha.25

Me too! Developing ionic app in browser is far more smoothly now. As for me this can be closed.

Thanks a lot for taking care of this!

Cheers

**Comment by giorgiofellipe** [comment] 2018-03-05 18:10
I can confirm, it's working properly with `cordova` on `0.2.0-alpha.25`.

**Comment by daniel-lang** [comment] 2018-03-05 18:16
Great, I guess this issue can be closed then.

**Closed by daniel-lang** 2018-03-05 18:16 UTC
Labels: bug, driver: sqlite

**Comment by lanthaler** [comment] 2018-04-07 10:44
@AlexMesser @pleerock any chance to backport this fix to the current release or release a new version which is compatible with typeorm-routing-controllers-extensions? They don't work together at the moment because, e.g., [typeorm-routing-controllers-extensions' Utils.ts](https://github.com/typeorm/typeorm-routing-controllers-extensions/blob/f268a8c2734533f70f57704432dc0c9bfb6b83be/src/util/Utils.ts#L18) calls `findOneById` which doesn't exist anymore.

Thanks

**Comment by pleerock** [comment] 2018-04-11 13:33
@lanthaler make a manual change temporary since 0.2.0 will be released very soon (I expect next week) (or fork, fix and publish your own package if you need it so urgently)

**Comment by samisamsam** [comment] 2018-07-04 15:11
Hi, i can't use typeorm@next my project was a mess because of typescript. I have to use typeorm@2.7. I have this issue "foreign key constraint fail" when i'm trying to insert null value for a foreign key

**Comment by daniel-lang** [comment] 2018-07-07 20:15
@samisamsam What database are you using? Are the queries similar to the original issue? If not please open a new issue and tag me.

**Comment by samisamsam** [comment] 2018-07-12 12:59
I'm using cordova. I solved my problem by using query method, thank you

Le sam. 7 juil. 2018 à 16:15, Daniel Lang <notifications@github.com> a
écrit :

**Comment by rohmanhm** [comment] 2018-07-15 04:01
I solved my problem today by set `synchronize` to false.

**Comment by vitalii12t** [comment] 2020-09-15 20:57
hey, issue still exists in sqlite + typeorm + typescript
![image](https://user-images.githubusercontent.com/32866393/93263984-275d8800-f7af-11ea-9c0f-174a79aa7df2.png)
any solutions?
