### ISSUE TITLE
Entity setters are not called when entity is loaded from database?

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#569] opened 2017-06-22 18:22 UTC
I'm experiencing a strange behavior with my model when setter method is not called during entity loading. I think that TypeORM modifies the underlying property directly somehow without actually calling a setter.

Here's my entity definition:

```typescript
@Entity('users')
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column(ColumnTypes.JSONB)
  private _profile?: any;


  get profile (): any {
    return this._profile;
  }

  set profile (profile: any) {
    this._profile = profile;
  }

}
```

Here's [the test for getters/setters](https://github.com/typeorm/typeorm/blob/master/test/other-issues/column-getters/column-getters.ts), but I think the problem with it is that it's not really checks if getter and setter functions are actually called. To make it more accurate I would suggest to somehow alter the value when it's saved and retrieved, this will make sure that getters and setters are actually called. Or better to just use some testing utilities to check if function was called once.

**Comment by Salimlou** [comment] 2017-06-22 19:29
I think you have to specify the column name in the decorator @Column({ name: "profile" })
see the entity in this [test](https://github.com/typeorm/typeorm/blob/master/test/other-issues/column-getters/column-getters.ts)

**Comment by slavafomin** [comment] 2017-06-22 21:51
@Salimlou thanks, but according to the documentation the `name` property of the `@Column` decorator is used to specify column name in the database, not in the entity. I thought that it's inferred by the `_` prefix. I will need to check it out. @pleerock can you confirm this?

**Comment by pleerock** [comment] 2017-06-23 06:07
right `name` column is a database name. @slavafomin there is no issue in orm, you should understand how setters/getters are working in javascript. When you do:

```ts
  private _profile?: any;
```

it creates a property called "_profile" and your `get profile` and `set profile` are not bind to your "_profile" anyhow in language level. "_profile" does not care if you have getters or setters - those getters and setters are just regular functions. Same if you had `public doSomeWork()` in your class and you expect it somehow affect "_profile". Or if you had `public setProfile`. It does not care about your functions even if they are getter/setters and have almost same name as your _profile property.

**Comment by slavafomin** [comment] 2017-06-23 15:48
@pleerock I understand that. The `_profile` property is just internal variable to store encapsulated (hidden) value, which should be accessible externally by means of calling `entity.profile = {}` and `const profile = entity.profile`. The idea is for TypeORM to call those setters and getters when writing or reading data from/to the entity. If TypeORM ignores the setters/getters and writes to the underlying property directly — this could be considered an incorrect (or at least undesired) behavior.

**Comment by pleerock** [comment] 2017-06-24 05:24
as I already told `_profile` and `profile` setter/getter do not know about each other, so its impossible to handle this scenario without extra code. We can do something like this:

```ts
@Entity('users')
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column(ColumnTypes.JSONB, { getter: "profile", setter: "profile" })
  private _profile?: any;


  get profile (): any {
    return this._profile;
  }

  set profile (profile: any) {
    this._profile = profile;
  }

}
```

And implement corresponding logic in orm.

**Comment by slavafomin** [comment] 2017-06-25 16:56
Yes, I think we can add a property like `columnName` to the `@Column` decorator. Not sure if we need such granularity with separate properties for getters and setters, because most of the time the same name is used for them both. Also, it's possible to define a convention, for example if column name contains prefix (like `_` in the example) then it's removed when property is accessed. That way we will not need to specify additional property. And the prefix could be globally configurable (I think `_` is a very reasonable default value).

**Comment by pleerock** [comment] 2017-06-27 12:15
convention is not an option. Somebody like to have "_", somebody hate it (like I do). Also such convention may bring unexpected behaviour for users. We have no other good option there except for `{ getter: "profile", setter: "profile" }`

**Comment by asvetliakov** [comment] 2017-06-27 23:00
@slavafomin 
I encountered same problem, this trick was worked for mi:
```ts
class PhotoMetadata {
   @PrimaryGeneratedColumn()
   public readonly id;
  
  // Don't decorate these private props
  private _height: number;
  private _photo: Photo;
  
  @Column()
  public get height(): number { return this._height; }
  public set height(h: number) { this._height = h; }

  @OneToOne(type = > Photo, photo => photo.metadata)
  @JoinColumn
  public get photo(): Photo { return this._photo; }
  public set photo(p: Photo) { this._photo = p; }
}
```

Looks like it doesn't matter what had been decorated: getter or setter. The TS decoration transformer emits required ```design:type``` for them:
```
__decorate([
    typeorm_1.Column(),
    __metadata("design:type", Number),
    __metadata("design:paramtypes", [Number])
], Metadata.prototype, "height", null);
```
There is additional ```design:paramtypes``` but i think it's being ignored by typeorm

**Comment by pleerock** [comment] 2017-06-30 11:28
I'll close this issue because everything is working as expected. You can follow @asvetliakov advice to do getters/setters.

**Closed** 2017-06-30 11:29 UTC
Labels: new feature

**Comment by amirh715** [comment] 2020-08-08 13:11
Your solution works. But, the properties returned are also underscored which is not desired. Is there a fix for this? @asvetliakov

**Comment by resistdesign** [comment] 2020-10-06 04:41
@amirh715 Maybe this will help: `toJSON` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

This will change how your object is serialized.

![image](https://user-images.githubusercontent.com/356375/95159125-424a6900-076b-11eb-9732-66310a11b60b.png)
![image](https://user-images.githubusercontent.com/356375/95159306-b8e76680-076b-11eb-99f8-b4da5905be1c.png)

**Comment by JJBocanegra** [comment] 2024-06-27 16:35
@asvetliakov that solution does not work at least in the most recent version of TypeORM.

Is there any other way to do this?

**Comment by resistdesign** [comment] 2024-06-28 03:49
4 thumbs down with no real feedback doesn't help anyone know why the workaround didn't work.
Maybe TypeORM breaks something 🤷‍♀️
But we're not any closer to knowing!
Thank you for your toxic contributions.
Kinda wonder why I took the time 😞
