### ISSUE TITLE
Support react-native-sqlite-storage?

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#1114] opened 2017-10-30 06:41 UTC
I can't go back writing raw query anymore after using typeorm in node.js. I need to use sqlite extensively in a react native app. Has anyone used typeorm with any react native local storages? Do you have plans to support react-native-sqlite-storage? I know that it will support sql.js but the app crashes with sql.js as soon as it starts.

**Comment by shroudedcode** [comment] 2017-10-30 09:18
I don't know @pleerock's stance on this, but I think this is outside of TypeORM's scope. [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage) is a native package partly written in Java. TypeORM is built using TypeScript and just "mashing them together" doesn't work.

**Comment by stonecold123** [comment] 2017-10-30 14:07
Bummer.
The only way I can find to use typeorm on react native is to install `nodejs-mobile`, but I'm not sure if it's worth it.

**Comment by shroudedcode** [comment] 2017-10-30 15:32
@stonecold123 According to the README, TypeORM can also be used without Node.js. Doesn't this mean you can use it with React Native as well, just without [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage)?

**Comment by daniel-lang** [comment] 2017-11-01 16:15
I have never worked with react native or react-native-sqlite-storage, but in the README it says
> Foundation of this library is based on Chris Brody's Cordova SQLite plugin.

TypeORM already supports the cordova sqlite plugin and the api for the react plugin look very similar. So it should be pretty easy to create a new driver for it.

**Comment by stonecold123** [comment] 2017-11-05 20:54
@daniel-lang Great!  Hope it will be supported for react native.

**Comment by santosh-indpro** [comment] 2017-11-14 07:23
@stonecold123 , Are you able to get TypeORM working with react-native-sqlite-storage?
Please let me know if both are working together.

**Comment by daniel-lang** [comment] 2017-11-14 09:29
@santosh-indpro For now they don't but we are planning on supporting react native and the react-native-sqlite-storage plugin

**Comment by stonecold123** [comment] 2018-02-08 17:31
@santosh-indpro @daniel-lang 
No, I've tried realm but I'm still looking forward to typeorm supporting react native. Realm does support some pseudo oneToMany, manyToMany relationship but it's not as straightforward as mysql/mariadb.

**Comment by pleerock** [comment] 2018-02-15 07:27
@daniel-lang Im going to release 0.2.0 beginning of next month and it would be great if we fix all our mobile-related issues and update roadmaps

**Comment by linkereu** [comment] 2018-03-19 19:49
@daniel-lang hello, can you tell me if I can already use typeorm with react native? Because the library is based in Cordova, I believe I will succeed, right?

**Comment by pleerock** [comment] 2018-03-28 11:06
@daniel-lang Im planning to release 0.2.0 next week, please let me know if you'll be able to finish these things, thanks :)

**Comment by daniel-lang** [comment] 2018-04-03 16:19
I'm currently trying to put an example together. Haven't had much luck so far.

**Comment by daniel-lang** [comment] 2018-04-03 18:40
Status for today:
* react-native-example-app compiles and runs
* TypeORM is able to connect to the database and execute statements
* `INSERT INTO` fails because `OrmUtils.mergeDeep()` depend on `Buffer` (node.js native package). This was introduced in `0.2.0` but doesn't pose a problem for Ionic thanks to browserify which injects [feross/buffer](https://github.com/feross/buffer) globally. So far I haven't found a way to do the same for React Native

**Comment by pleerock** [comment] 2018-04-04 05:05
@daniel-lang I think `mergeDeep` already excludes some specific objects, probably buffer can be added somehow into its list of excluded objects.

**Comment by daniel-lang** [comment] 2018-04-04 06:06
The problem is, that Buffer is never required because it is simply available in node. Don't know, if we can export a global node variable in PlatformTools, but I will give it a try

**Comment by pleerock** [comment] 2018-04-04 10:08
But we can do `PlatformTools { bufferClass = Buffer }` and `(platformTools.bufferClass && source[propertyKey] instanceof platformTools.bufferClass)` right?

**Comment by daniel-lang** [comment] 2018-04-09 07:35
PR for React Native is ready (#1899)

**Comment by pleerock** [comment] 2018-04-11 14:00
fixed by #1899 and will be released in `@next.alpha.44` 🙌

**Closed by pleerock** 2018-04-11 14:00 UTC
Labels: comp: ionic, new feature
