### ISSUE TITLE
Passing findOneOrFail(undefined) will not throw an error, it returns the current table's first entry.

### ISSUE THREAD

**Issue by paroczigergo** [typeorm/typeorm#6728] opened 2020-09-16 09:54 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[ x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

Passing undefined value as id will not throw an error, it returns the current table's first entry.
`repository.findOneOrFail(id)`

Expectation:
It should throws an exception, and should not return db value.

**Comment by imnotjames** [comment] 2020-09-19 02:39
This is a breaking change which is ideally gonna happen in the next minor release

**Comment by imnotjames** [comment] 2020-10-07 07:24
Duplicate of #2990

**Closed by imnotjames** 2020-10-07 07:24 UTC
Labels: bug, driver: postgres

**Comment by wanghq** [comment] 2022-06-21 20:58
Seems this problem still exists. Can anyone confirm?

**Comment by ashrafatef** [comment] 2022-07-25 12:40
any updates because it still exist

**Comment by JJBocanegra** [comment] 2024-12-20 11:56
How is this still an issue in nearly 2025 is beyond my mind
