### ISSUE TITLE
WARNING in PlatformTools.js

### ISSUE THREAD

**Issue by tamih** [typeorm/typeorm#1009] opened 2017-10-08 08:50 UTC
what is this warning means and how can I fix this :

> WARNING in ./node_modules/typeorm/platform/PlatformTools.js
26:19-32 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (M:\my-app\node_modules\webpac
k\lib\dependencies\CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (M:\my-app\node_modules\webpa
ck\lib\Compilation.js:694:24)
    at Compilation.finish (M:\my-app\node_modules\webpack\lib\Compilation.js:552:9
)
    at applyPluginsParallel.err (M:\my-app\node_modules\webpack\lib\Compiler.js:51
2:17)
    at M:\my-app\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (M:\my-app\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (M:\my-app\node_modules\webpack\lib\Compilati
on.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by daniel-lang** [comment] 2017-10-08 09:16
Are running TypeORM in the browser or on node.js?

**Comment by tamih** [comment] 2017-10-08 09:27
on node.js with sqlite3
driver: 
      {
        type: "websql",
        database: "test",
        extra: {
            version: 1,
            description: "test database",
            size: 10 * 1024 * 1024
          }
      },

**Comment by daniel-lang** [comment] 2017-10-08 09:33
Is there a specific reason you want to use the websql driver and not the sqlite driver?
Websql is a browser technology and the driver for it is written for the browser.

**Comment by tamih** [comment] 2017-10-08 09:38
I  use the websql driver because I need to run the db on the browser

**Comment by daniel-lang** [comment] 2017-10-08 09:40
So you app has some kind of frontend and you want to run TypeORM there? And your frontend is part of your node app?

**Comment by tamih** [comment] 2017-10-08 09:41
yes

**Comment by daniel-lang** [comment] 2017-10-08 09:44
@pleerock that's a usecase we don't cover right now...

TypeORM has two different `PlatformTools` classes, one for browser and one for node. I'm guessing, that the wrong version is loaded in your usecase.
What system/framework do you use and how is TypeORM loaded?

**Comment by tamih** [comment] 2017-10-08 09:48
I am pretty new with angular so ...
If I understand your question correctly I use angular-cli.json to load evrything...

**Comment by daniel-lang** [comment] 2017-10-08 16:09
I have no experience with the new angular version and how things are loaded there. But it seems like it picked the wrong (node.js) version of TypeORM. We currently leave the decision which version is loaded to the loader of the framework. Which in your case is either Webpack or CommonJS (both appear in the error).
I will put together an idea how this situation can be fixed in #857.

**Comment by pleerock** [comment] 2017-10-09 06:14
first let's clarify what @tamih exactly wants to do. @tamih do you want to store everything IN THE USER BROWSER, and not on the server side? If answers is yes, then websql is what you shall use. But note, that its very experimental and maybe you wanted to use typeorm on the backend side, but not sure what to choose? Sorry for asking this, but I want to be sure you are understand what are you trying to do

**Comment by tamih** [comment] 2017-10-09 06:50
I need to  store everything IN THE USER BROWSER (this is the requirement).
by the way I create basic tables and queries ( no special connections...).

thanks for the help (:

**Comment by pleerock** [comment] 2017-10-09 06:56
Okay, thanks for the clarification. As I already told in #933 there are issues with websql itself:

* not popular. Maybe you are the first one who tried it, Im not sure
* websql is not supported by all browsers and there are no plans to support, because...
* websql is deprecated web standard, unfortunately
* there are really strange things in its implementation, at least in chrome where it works. It looked like modified by google sqlite version just like in android

Also we are planning to integrate sql.js (hope this week) and I think it shall work better then websql.

Regarding to your issue. When do you have this error? During connection? Can you check issue without angular and provide a demo repository which I can pull, reproduce and fix if its an issue?

btw @daniel-lang we need to create websql for webpack example as well

**Comment by tamih** [comment] 2017-10-09 07:01
to make things easier will sql.js  replace typeorm ? 
would it meet my requirments ?
and will it fix the problems you mention ?

**Comment by pleerock** [comment] 2017-10-09 07:11
> to make things easier will sql.js replace typeorm ?

sql.js does not replace typeorm, its a library we will use in typeorm as additional supported way of working with sql databases in the browser.

> would it meet my requirments ?

it should be similar to sqlite.

> and will it fix the problems you mention ?

problems I mention are related to websql itself, its a BROWSER STANDARD. sqljs is an alternative solution for this problematic BROWSER STANDARD

**Comment by Zuzon** [comment] 2017-10-18 19:06
Will be very good if typeorm will support webpack, because we have amazing tool - "nwjs". There are available all native nodejs tools in browser.
websql can't replace sqlite, because websql api don't allow to create database file in any place in file system.

for myself I have done some temporary fix. Im replaced `PlatformTools.load("sqlite3").verbose();` to `require("sqlite3").verbose();` and have successful webpack build.

I hope typeorm will support webpack in future.

**Comment by daniel-lang** [comment] 2017-10-18 20:06
@Zuzon TypeORM supports webpack but only for the browser. And therefore only the drivers (websql, and cordova) indented for the browser will work with webpack.
If you want to use the nodejs version of TypeORM (and all the drivers), you will have to remove the "browser" tag from `package.json`, since that tells webpack where to look in the package

**Comment by pleerock** [comment] 2017-10-19 04:39
@daniel-lang we probably can replace `PlatformTools.load("sqlite3")` methods to `PlatformTools.loadSqlite3()` where inside it will do `require("sqlite3")` explicitly, what do you think?

**Comment by daniel-lang** [comment] 2017-10-19 06:30
I don't know what difference it would make. @Zuzon is trying to use webpack, which will use the BrowserPlatformTools class. And this makes using the node drivers like sqlite impossible.
As far as I know, webpack is only used for frontend projects and not for node projects, so our decision to serve the browser version when webpack is used, is valid.

**Comment by pleerock** [comment] 2017-10-19 06:47
We need to research other tools as well (nwjs, electron, nativescript, etc.) - they may use webpack as well but use node packages (sqlite)

**Comment by daniel-lang** [comment] 2017-11-06 11:58
I guess we will have to remove that preselection and tell users how to change their system to use the correct version (node.js or browser). Looking at #1136 and #1143 we have multiple people using node and webpack.
I will put a config file for ionic together and then create a PR to make webpack work with the node.js version

**Closed** 2017-12-01 06:51 UTC
Labels: comp: browser

**Comment by daniel-lang** [comment] 2017-12-01 08:00
With TypeORM 0.1.8 the preselection of the browser version will be removed. Therefore you will be able use Webpack for Node.js projects
