### ISSUE TITLE
Command line option for migration:generate to output code in console

### ISSUE THREAD

**Issue by golergka** [typeorm/typeorm#5740] opened 2020-03-23 00:44 UTC
**Issue type:**

[x] feature request

**TypeORM version:**

[x] `latest`

I often find it useful to check my changes to schema with migration generation system, so I find myself generating migration named "Test" and then deleting it right after. It would be very useful to just print out generated code to stdout.

**Comment by imnotjames** [comment] 2020-10-14 06:28
Duplicate of #3037

**Closed by imnotjames** 2020-10-14 06:28 UTC
Labels: comp: migrations, new feature
