### ISSUE TITLE
0.2.36 changes types by default

### ISSUE THREAD

**Issue by TyrisDavidLopez** [typeorm/typeorm#8044] opened 2021-08-06 11:25 UTC
## Issue Description
After upgrade to 0.2.36 from 0.2.34, TypeORM dropped PK (uuid) from my table (MySQL) because changed varchar(36) to char(36). Afortunally, testing found this error. (typeorm sync = true)

### Expected Behavior
No changes in DB schema if not needed.

Nothing must be changed

### Actual Behavior
Dropped column because "detected" type changed

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. Create a table with PK UUID (varchar 36, type string) with v0.2.34
2. insert a new value
3. upgrade to v0.2.36
4. value must be there.
 

1.
2.

```typescript
@Entity()
export class Example {
  @PrimaryColumn({ length: 36 })
  @Generated('uuid')
// from 'class-validator';
  @IsString() 
  @IsUUID()
  @MaxLength(36)
  @ValidateIf((v) => v.id != null && v.id != undefined)
  id: string;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| class-validator     |  0.12.2 |
| Node.js version     | 12.16.2 | 
| Typescript version  | 3.9.10  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment] 2021-08-06 19:24
Synchronize is only for development purposes.  It can and will drop columns frequently.

**Comment by imnotjames** [comment] 2021-08-06 19:24
Also this is a duplicate of #8002

**Closed by imnotjames** 2021-08-06 19:24 UTC
Labels: bug, requires triage
