### ISSUE TITLE
QueryFailedError: column cnst.consrc does not exist

### ISSUE THREAD

**Issue by murbanowicz** [typeorm/typeorm#4573] opened 2019-08-12 05:26 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)
**tried both, the same error**

**Steps to reproduce or a small repository showing the problem:**

 When trying to start the app I am getting the following error during the initialization of DB:
`"QueryFailedError: column cnst.consrc does not exist"`
```
 hint: 'Perhaps you meant to reference the column ' +
 '"cnst.conkey" or the column "cnst.conbin".',
```

**Comment by DanielWare** [comment] 2019-08-15 19:28
Duplicate of [issue #4332](https://github.com/typeorm/typeorm/issues/4332)

I was using Postgres 12. After downgrading Postgres to 11.5 it is working now.

**Comment by viktor-ku** [comment] 2019-09-28 15:30
Same issue

**Comment by ogun34** [comment] 2019-10-04 04:51
I am getting the same error in different machines (one Mac and one Linux Mint)

**Comment by ogun34** [comment] 2019-10-04 05:08
@DanielWare I have the 11.5 installed but still getting the same error!

**Comment by maxsitu** [comment] 2019-10-12 06:52
This link is telling you that on postgres version 12, column `consrc` no longer exists in table `pg_constraint`.
https://www.postgresql.org/docs/12/catalog-pg-constraint.html

**Comment by edencorbin** [comment] 2019-10-19 20:16
Just happened to me backed up working db from postgtres 11, restored into same name in 12, now I get this error on launch. I'm confused if this is a known issue or what workaround from comments.

**Comment by maxsitu** [comment] 2019-10-19 20:30
@edencorbin hope this will give you some hope.
https://github.com/typeorm/typeorm/issues/4332#issuecomment-536199657

**Comment by zishe** [comment] 2019-12-09 16:30
Fixed in `0.2.21`, just checked.

**Comment by chanmathew** [comment] 2019-12-11 19:52
> @murbanowicz Fixed in `0.2.21`, just checked.

Just upgraded from 0.2.20 and can confirm I no longer get this issue. Postgres 11.5 as well.

**Comment by tduslost** [comment] 2019-12-24 03:50
0.2.22, Postgres 12, same issue.

**Comment by divyanshu013** [comment] 2020-01-11 13:26
Works after upgrading. I think this issue can be closed.

**Comment by khrukawa** [comment] 2020-08-01 04:43
just update typeorm

**Closed** 2020-10-06 05:46 UTC

**Comment by nabeelsuspg** [comment] 2020-12-20 04:39
I am getting a similar error: 
QueryFailedError: column "month" does not exist
postgresql: 11.10
typeorm: 0.2.18

**Comment by Matheus8174** [comment] 2022-04-26 19:47
I have this issue using typeorm 0.2.45. My postgres version is (PostgreSQL) 14.1 (Debian 14.1-1.pgdg110+1). After change to postgres it works
