### ISSUE TITLE
TypeError: Cannot set property getManager of #<Object> which has only a getter

### ISSUE THREAD

**Issue by juthakiat** [typeorm/typeorm#8091] opened 2021-08-16 13:11 UTC
Issue type:
[x] **Bug Report**

NodeJS
**14.17.3**

Database
**mysql 5.6.10**

TypeORM version:
**^0.2.37**

I got this error while running jest command

```
TypeError: Cannot set property getManager of #<Object> which has only a getter

      at ../node_modules/jest-mock/build/index.js:806:32
          at Set.forEach (<anonymous>)
```

Remark
I have try the workaround from the issue 
[https://github.com/typeorm/typeorm/issues/6054](https://github.com/typeorm/typeorm/issues/6054) 
however, it doesn't work for me.

**Comment by imnotjames** [comment] 2021-08-16 15:39
This is more an issue with how you're using jest rather than a bug in TypeORM

Duplicate of #5308

**Closed by imnotjames** 2021-08-16 15:39 UTC
