### ISSUE TITLE
Dry run or pretend run of migrations?

### ISSUE THREAD

**Issue by zxti** [typeorm/typeorm#5420] opened 2020-01-26 19:06 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Is there any way to try running the migrations to see if there are any errors, and always roll back?  This would be nice for apps where we just want to see if there would be migration errors first (with this dry-run), before stopping the app servers and running the migrations for real.

**Comment by imnotjames** [comment] 2020-10-14 06:28
Duplicate of #3037

**Closed by imnotjames** 2020-10-14 06:28 UTC
Labels: comp: migrations, question
