### ISSUE TITLE
.leftJoinAndMapMany() returns only one instance.

### ISSUE THREAD

**Issue by erickmendesBR** [typeorm/typeorm#2107] opened 2018-05-09 14:28 UTC
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

The method below should return a list of "Componente" but is returning only one instance of "Componente".

{
        return await this.em
        .createQueryBuilder(Op, 'op')
        .leftJoinAndMapMany('op.componentes', Componente, 'comp', '"op"."CODEMP" = "comp"."CODEMP" AND "op"."NUMORP" = "comp"."NUMORP"')
        .where('"op"."NUMORP" = 16314')
        .getMany();
}

JSON:
[
  {
      "empresa": 1,
      "origem": "5",
      "numero": 16314,
      "filial": 2,
      "pedido": 0,
      "dataProducaoInicial": "2018-03-10",
      "dataProducaoFinal": "2018-03-10",
      "dataRealizadaInicial": "2018-03-09",
      "dataRealizadaFinal": "2018-03-09",
      "codigoFamilia": "500",
      "situacao": "F",
      "emissao": "2018-03-12",
      "componentes": [
        {
            "empresa": 1,
            "numeroOp": 16314,
            "codigo": "4000001",
            "quantidadePrevista": 10890,
            "quantidadeUtilizada": 10890
        }
      ]
}
]

**Comment by pleerock** [comment] 2018-05-09 17:39
please provide a PR with a failing test that reproduces this issue.

**Comment by Kononnable** [comment] 2018-09-27 19:44
Closing as no answer from the reporter.

**Closed by Kononnable** 2018-09-27 19:44 UTC

**Comment by Steffen86de** [comment] 2022-01-02 15:17
This issue was reported 3 years ago but I'd like to post my observation here as it might help others who are running into the same pitfall. I was facing a similar issue that leftJoinAndMapMany() returned an array with a single instance only, even though I expected many elements in the list. After hours of debugging I identified the root cause in the TypeORM Mapping itself. The joined entity had a compound PK and I forgot to annotate one of the columns as PK. That's why TypeORM assumed duplicates in the result set and eliminated all elements except one.

**Comment by skliarovartem** [comment] 2023-11-02 06:36
I still have this problem. So I see only one item instead of many...
I also don't really get the answer from Steffen86de, so what I should to do to fix it? Many thanks!

**Comment by dberardo-com** [comment] 2024-12-16 13:55
i can confirm ... any workaround here ?
