### ISSUE TITLE
Could transformer function get the current row as an argument?

### ISSUE THREAD

**Issue by fatihky** [typeorm/typeorm#6305] opened 2020-06-24 20:51 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Sometimes our value transformers fail and I can't see failed row. May the `transformer.from` function get the current row as third argument? What do you think about this?

**Comment by imnotjames** [comment] 2020-10-17 08:18
Duplicate of #3978

**Closed by imnotjames** 2020-10-17 08:18 UTC
Labels: driver: mariadb, driver: mysql, new feature
