### ISSUE TITLE
Cannot assign to read only property 'CQN_OPCODE_ALL_OPS' of object '#<OracleDb>'

### ISSUE THREAD

**Issue by Mahmoud-Sagharjoughi** [typeorm/typeorm#7403] opened 2021-02-21 14:48 UTC
## Issue Description
Hi,
Actually, I have these sections of the simple codes and working without a problem on Typeform version `v0.2.28`
and when I did upgrade it to `v0.2.31` an error occurred.

I have an entity named `Sms` just like this:
```typescript
@Entity()
export class Sms {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn({ type: 'timestamp with time zone' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamp with time zone' })
  updatedAt: Date;

  @Column('simple-json', {
    default: '[]',
  })
  numbers: string[];

  @Column({
    length: 2048,
  })
  text: string;

  @Column()
  isSent: boolean;
}
```

and I want to save(insert) an object:
```typescript
await this.smsRepositoy.save({
      isSent: false,
      numbers: ['test'],
      text: 'simple text',
});
```
but I will get the error:
```
Cannot assign to read only property 'CQN_OPCODE_ALL_OPS' of object '#<OracleDb>'
```
with the call stack:

TypeError: Cannot assign to read only property 'CQN_OPCODE_ALL_OPS' of object '#<OracleDb>'\n    at Function.assign (<anonymous>)\n    at Function.OrmUtils.mergeDeep (/project/src/util/OrmUtils.ts:90:28)\n    at Function.OrmUtils.mergeDeep (/project/src/util/OrmUtils.ts:88:26)\n    at Function.OrmUtils.mergeDeep (/project/src/util/OrmUtils.ts:88:26)\n    at /project/src/driver/oracle/OracleDriver.ts:586:26\n    at Array.reduce (<anonymous>)\n    at OracleDriver.createGeneratedMap (/project/src/driver/oracle/OracleDriver.ts:583:42)\n    at /project/src/query-builder/ReturningResultsEntityUpdator.ts:96:69\n    at Array.map (<anonymous>)\n    at ReturningResultsEntityUpdator.<anonymous> (/project/src/query-builder/ReturningResultsEntityUpdator.ts:87:40)\n    at step (/project/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/project/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)\n    at /project/node_modules/typeorm/node_modules/tslib/tslib.js:115:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/project/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)\n    at ReturningResultsEntityUpdator.insert (/project/node_modules/typeorm/query-builder/ReturningResultsEntityUpdator.js:87:24)\n    at InsertQueryBuilder.<anonymous> (/project/src/query-builder/InsertQueryBuilder.ts:116:53)\n    at step (/project/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)\n    at Object.next (/project/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)\n    at fulfilled (/project/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)

### Expected Behavior

Insert a row without throwing an error just like Typeorm `v0.2.28` :D

### Actual Behavior

Throw ```Cannot assign to read only property 'CQN_OPCODE_ALL_OPS' of object '#<OracleDb>'``` error.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   OSX 10.15.3  |
| Node.js version     | v12.18.3 | 
| Typescript version  | v4.1.5 | 
| TypeORM version     | v0.2.31 | 
| oracledb version     | v5.0.0 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-07-04 06:20
Duplicate of #5487

**Closed by imnotjames** 2021-07-04 06:20 UTC
Labels: bug, driver: oracle, requires triage
