### ISSUE TITLE
how to disable logging in migration

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#5792] opened 2020-04-01 07:06 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I set `logging: false` in `ormconfig.ts` file, but it still print query logs.

**Comment by phatlamhd** [comment] 2020-07-03 06:27
I have same issue

**Comment by Diluka** [comment] 2020-07-07 02:36
@phatlamhd I use the `SimpleLogger`'s code to create my own and it works as expected. I think maybe default logger didn't get the options.

see https://github.com/nestjs/nest/issues/3657 and my simpler one https://gist.github.com/Diluka/110b0e9e07609bce2957fe451d239ad2

**Comment by shiro** [comment] 2020-09-15 20:02
Indeed, passing the options to `SimpleConsoleLogger` manually works.
Apparently the options are not passed otherwise, it's definitely a bug.

**Comment by imnotjames** [comment] 2020-10-14 06:27
Duplicate of #4199

**Closed by imnotjames** 2020-10-14 06:27 UTC
Labels: comp: migrations, question

**Comment by danstarns** [comment] 2025-02-13 01:13
> SimpleConsoleLogger
import { DataSource, SimpleConsoleLogger } from 'typeorm';

```
  logger: new SimpleConsoleLogger(false),
```

Worked.
