### ISSUE TITLE
Extend entity without class inheritance?

### ISSUE THREAD

**Issue by dotansimha** [typeorm/typeorm#1457] opened 2018-01-16 09:50 UTC
Hi,

We are testing this package now, and we wonder if there is a way to extend a entity without using class inheritance.

Our app is separated to modules, and each module can declare entity, without the need to know it's base. 
For example:
Module A: `@Entity() class A { @PrimaryGeneratedColumn() id;   }` 
Module B: `@Entity() class AWithMore { @ Column() id;   }` 

Maybe it possible to use the `@Entity` to distinguish the entity type? something like that:
Module A: `@Entity({ entity: 'A' }) class A { @PrimaryGeneratedColumn() id;   }` 
Module B: `@Entity({ entity: 'A' }) class AWithMore { @Column() name;   }` 

This way, entity `A` will have both `id` and `name` fields on runtime.

**Comment by pleerock** [comment] 2018-01-16 10:37
No, its not possible.

**Comment by dotansimha** [comment] 2018-01-16 11:48
@pleerock I think I can add support for the feature by changing the way this package detects the relations between the `Entity` and `Column`.
https://github.com/typeorm/typeorm/blob/master/src/decorator/entity/Entity.ts#L27
https://github.com/typeorm/typeorm/blob/master/src/decorator/columns/Column.ts#L109

What do you think?

**Comment by pleerock** [comment] 2018-01-16 12:14
its not that easy as you think. when you load your entity from the database (for example using `findOne(id)` - what do you expect it will return you? `A` or `AWithMore` ?

**Comment by dotansimha** [comment] 2018-01-16 12:16
@pleerock , I guess that neither of them. I expect that the return value will be the combination of both.

**Comment by dotansimha** [comment] 2018-01-16 12:18
I guess that the result will be the the same of I just execute [this piece of code](https://github.com/typeorm/typeorm/blob/master/src/decorator/columns/Column.ts#L108-L114) manually and add new columns on runtime.
I expect it to return the columns I declared inside the class, with the column I added manually.

**Comment by dotansimha** [comment] 2018-01-16 13:01
> you might think its a good idea for some specific use case, but its not. It will create a mess and thousand of issues for you.
@pleerock 
I see. can you please elaborate? 
The decorators are also running in runtime, and creating the whole entities map on runtime. How adding a field in runtime might effect it? how it that different from adding a field with `@Column`? they are both running in runtime. 

Currently there is not way to extend an existing entity, right? Inheritance just creates a new entity and not extending an existing one.

**Comment by pleerock** [comment] 2018-01-16 13:07
> The decorators are also running in runtime, and creating the whole entities map on runtime. How adding a field in runtime might effect it? how it that different from adding a field with @Column? they are both running in runtime.

ORM is complex. You are looking on just 1 part of 1000. Try to checkout codebase, implement your idea and run all tests against your idea and you'll see that it may take you half an year to implement this feature and finally you stuck in some place where this idea will not fit with other things.

> Currently there is not way to extend an existing entity, right? Inheritance just creates a new entity and not extending an existing one.

why there is no? What is wrong with `class AWithMore extends A` ?

**Comment by dotansimha** [comment] 2018-01-16 13:16
> ORM is complex. You are looking on just 1 part of 1000. Try to checkout codebase, implement your idea and run all tests against your idea and you'll see that it may take you half an year to implement this feature and finally you stuck in some place where this idea will not fit with other things.

I know ORM is complex, but this does not answer my question. 
Using `Column` as a function is not different from using it as decorator, it's a function, and it behaves the same way. Just like anything that possible doing with decorator, can be done with regular functions calls.

> Because it means the `AWithMore` must know `A`, and the end user of the app must use `AWithMore`.

I would like to do something like `class A`, `class B` and `class C`, and then use ONE of them, and expect the same behavior.
Our goal is to create modular infrastructure, which each type/entity can extend it's base. 

For example: `class User`, `class UserWithProfile` and `class UserWithServices` should result in a single entity, which it's class does not really matter, and it contains the fields from `User`, `UserWithProfile` and `UserWithServices`. 
We want to be able to do something like [mixin](https://en.wikipedia.org/wiki/Mixin), so each developer can pick his own extensions for `User`.

**Comment by dotansimha** [comment] 2018-01-16 13:35
BTW, my question has nothing to do with ORM itself.
It's only effect the TypeScript aspect of the package, and the way you translate the decorators to ORM definition.

**Comment by dotansimha** [comment] 2018-01-16 15:36
@pleerock I created a simple and working example, the tests are passing. I'm sure that the API could be different and much more flexible. 

Please take a look at this changes:
https://github.com/dotansimha/typeorm/commit/27a6675b724bf8b807fdef5a5dd52c446c82be1c

The only change in the creation of the columns it the `target` field. everything works as expected, and the `User` type is extended with `newField`. 

What do you think?

**Comment by pleerock** [comment] 2018-01-17 13:24
I understood your idea, that you want something like "mixins". In the example you created you just solve 1 problem of the 1000, as I already told. To make sure everything works you must cover each case user can do with regular entity with your "mixin". Okay, if you want to go deeper, let's start a discussion and start to solve all problems.

First problem, as I already asked you, what you would return in `QueryBuilder` and `find` methods - instance of `MyUser` or `MyUserExtension` ?

`find(): MyUser[]` or `find(): MyUserExtension[]` ?

**Comment by dotansimha** [comment] 2018-01-21 16:52
@pleerock Thanks for your reply! 

My changes allows the ORM to manage the entity by itself, regardless the defined `class`es.
Which means that the type `User` is the only type, and `MyUserExtension` is just a class that does not belong to a real entity, and it's just extending the `User` entity.

I expect the `find<T>` to return `T[]` just like before, and [I saw in the code](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L618) that I can also allow me to specify the `entityClass`.

So if my code runs in a modules that has only the base `User` type, it should be:

```
const user = entityManager.find<User>(`User`, { ... });
```

And if my code runs in a code that knows about the existence of `MyUserExtension`, then is should use it this way:

```
const user = entityManager.find<MyUserExtension>(`User`, { ... });
```

My approach is to separate the coupling between the TypeScript class and the ORM Entity.

ORM entity is built in runtime according to the class that used `@Entity` and `@Column`, and IMO it should be separated from the way the ORM known about the entity field.

This way we could create a more modular definition of the same `Entity` without the need for a single TypeScript `class`.

**Comment by pleerock** [comment] 2018-01-22 09:17
okay, so let's say we have this:


```ts
@Entity()
export class User {

     @PrimaryGeneratedColumn()
     id: number;

     @Column()
     name: string;

}
```

```ts
@EntityExtension(User)
export class MyUserExtension {

     @Column()
     address: string;

}
```

**First question**. When I call `manager.find(User)` what do I get?:

```ts
{ id: 1, name: "Max", address: "NY" }
```

or

```ts
{ id: 1, name: "Max" }
```

I guess second, because if it was first then type signature `User` is not correct and you'll not be able to use address type-safe. Please confirm this.

**Second question**. When I call `manager.find(MyUserExtension)` what do I get?:

```ts
{ address: string }
```

or something else? I guess this, because otherwise again type system will not work properly. So if we have only such dummy object then I don't see how useful it can be and I do see lot of problems  caused by this. Just two of them:

* `findOneById(MyUserExtension, id)` -> what is "id" here? MyUserExtension does not have primary keys
* `save(myUserExtension)` -> will not be possible because to insert you may also need an id and name. Also with `save(user)` its not possible to save address since missing property inside user object. Then how do you save your address in your user?

**Comment by dotansimha** [comment] 2018-01-22 13:06
So when you're calling `manager.find(User)` you should get the whole object, no matter where you called if from. 
Because calling `manager.find(User)` occurs during runtime of the app, and in runtime you have the full merged entity, so you should get `{ id: 1, name: "Max", address: "NY" }`.
But if you are running the code from a module that only knows about `export class User {`, then you should expect it to return only `id` and `name`. 
If you are executing a code from a module that knows about `export class MyUserExtension {`, then I should expect the module to return `id`, `name` and `address`.
In the end, you are getting the data from the DB as `any`, because you are getting it from an external driver, and you can treat is as `T` (the generic type that used to create the EntityManager).

Regarding the second question, there is no meaning to call use `MyUserExtension` as entity. 
`MyUserExtension` is just a class that used to extend `User`. So in any case, you should always expect to get `User`, and never expect to get `MyUserExtension` because it's just a declaration that used to extend the base entity.

If you are inside a module that has `MyUserExtension` you should use it as `findOneById<MyUserExtension>(User, id)`.  Also if you are using `save`, you should insert a `Users` entity, but with the fields from `Users` AND the fields from `MyUserExtension`.

**Comment by pleerock** [comment] 2018-01-22 13:21
@dotansimha your purpose is runtime and you aren't thinking about compile time which is required to think of. When you do:

```ts
const user = await manager.find(User): Promise<User>
```

How do you get `user.address` here? Do not think about data like just json you are sending to the client. Json is just result of what you are doing with the data. How do I access address in my codebase?

Also, how do I set and save address in my code, of course without dynamic and json stuff:

```ts
const user = new User();
user.address = "..."; // compiler error, but how do I set address and save user's address?
manager.save(user);
```

> If you are inside a module that has MyUserExtension you should use it as findOneById<MyUserExtension>(User, id)

Also I did not understand this part. Also please describe abstract definitions of `you are running the code from a module that only knows about` in terms of our example and real code examples.

**Comment by dotansimha** [comment] 2018-01-22 13:27
Think about it like that:
```
- src /
    - modules/
           - user/ 
                     user.entity.ts
           - user-address
                     user.address.ts
```

Code written under `src/modules/user` should expect it to return `User`.
Code written under `src/modules/user-address` should expect it to return `MyUserExtension`.

Each modules has it's own manager and it's own logic.

`user` modules should manage logic like getUserById, and should **never** know about `address` field during compile time.
`user-address` should handle `getUserByAddress`, but can also access `id` and `name` because it's extends it.
Only the code under `user-address` will do `user.address`!

**Comment by pleerock** [comment] 2018-01-22 13:38
Okay, I got your project structure and how you want to organize things. Now provide a real sample code for this part:

> user-address should handle getUserByAddress, but can also access id and name because it's extends it.

Also, you did not answer my questions. How you can access user.address (even inside `user-address` module) to read or save entity.

**Comment by dotansimha** [comment] 2018-01-22 13:54
@pleerock  I think that eventually each module will have to use it's own `EntityManager<T>`.

Let's add a real-life example, which we are already implemented with another project:

* Module `User`: declares type `User` with `id: string` and `username: string` fields.
* Module `UserProfile: declares type `Profile` with `firstName: string` field, and an extension for `User` entity (`UserWithProfile`) with `profile: Profile` field.
* Module `Items`: declares type `Item` with `id: string` and `name: string`, and an extension for `User` entity  (`UserWithItems`) with `myItems: Items[]`.


Our `User` module provides business logic for dealing with finding a user like that: `getUserById<UserType = User>(id: string): UserType`, and this way the method can be used from the `User` module with `User` class, but also from other modules, by overriding the generic type.

The `UserProfile` modules provides business logic for dealing with the user profile fields, such as setting the user's profile, getting formatted fields, etc.

The `Items` module is doing the actual create, update and delete for `Item` type, but also exposes a function called `getUserItems` that uses the ORM of `User` to get details from the user, in order to fetch the correct items from the db. It also uses the `UserProfile`.

This means that there is a basic `User` entity (which is the only TypeORM entity), but there are 3 classes for `User`: one per each module.

If a developer want's to get the correct compile time types when the code is inside the `items` module, he should actually use `typeof User & typeof UserWithProfile & typeof UserWithItems` as his generic type.

**Comment by pleerock** [comment] 2018-01-22 14:27
> he should actually use typeof User & typeof UserWithProfile & typeof UserWithItems as his generic type.

User should not specify his "own" generic type, its like casting things with `as ...` which makes things dynamic and not really strict. What if your class contains methods? User will try to call `user.doSomethingWithProfile()` and will have runtime errors.

Also you still did not answer how to save such entity, finish this code please:

```ts
const user = new User();
user.address = "..."; // compiler error, but how do I set address and save user's address?
manager.save(user);
```

TBH I see zero reason for such a "fake" module separation. Also, I would really recommend you not to do such separation in models, once your app grow and have lot of relations you'll need to bind models to each other, avoiding coupling between models will bring you more issues then it solves.

**Comment by dotansimha** [comment] 2018-01-22 14:44
Regarding the save issue, I got it now, and I think that you are right, and it might be an issue that requires another solution.

The reason we want to create this separation is to allow logics to be part of an external NPM module, and then load it into the app, and re-use it in other apps. We think that integrating TypeORM in this solution will be very helpful and let us dispatch the ORM along with the schema and models. 

Do you an idea for solving this? (well, you are the TypeORM master..)
I noticed that you're against the modules separation, but we're really want to try to implement a full module solution, and we don't want to miss TypeORM as part of our solution.

**Comment by pleerock** [comment] 2018-01-22 15:43
Save is just a single problem, if we go deeper, we find more problems. I'll need to think more about this idea.

Im not against module separation, just in my kinda rich experience, models separation (not module, managers or other module logic) may bring lot of complexity, duplication and maintenance overhead, thats why I usually recommend to think twice if such separation does not bring more problems then it solves. This may not be related to your particular task, but if you'll have more modules and more **relations** between them you'll face lot of issues trying to resolve such coupling.

**Comment by pleerock** [comment] 2018-02-20 10:54
we can close this issue I believe.

**Closed by pleerock** 2018-02-20 10:54 UTC
Labels: question

**Comment by iamchathu** [comment] 2021-08-17 13:12
I think I also have this issue.
