### ISSUE TITLE
MongoDB MongoServerSelectionError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by barbarbar338** [typeorm/typeorm#7009] opened 2020-11-03 14:31 UTC
## Issue Description
When I try to make a normal mongodb connection with typerom@0.2.29 version I get this error:
```
MongoDB MongoServerSelectionError: getaddrinfo ENOTFOUND [Mongodb Server IP]
```
but when I try to make a normal mongodb connection with typerom@0.2.25 version it works.

### Expected Behavior
Must connect to mongodb server

### Actual Behavior
throws this error: 
```
MongoDB MongoServerSelectionError: getaddrinfo ENOTFOUND [Mongodb Server IP]
```

### Steps to Reproduce
1. install typeorm@0.2.29
2. connect to a mongodb server with default options

```typescript
typeorm.createConnection({
            type: "mongodb",
            url: CONFIG.MONGODB_URI,
            synchronize: true,
            logger: "debug",
            useUnifiedTopology: true,
            useNewUrlParser: true,
            autoLoadEntities: true,
        })
```

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows10     |
| Node.js version     | v15.0.1 | 
| Typescript version  | v3.7.4 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)
- [ ] `mysql`
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by JumpLink** [comment] 2020-11-03 18:44
Same here, works with `v0.2.28` but not with `v0.2.29`, connect url is `mongodb+srv://<hidden>:<hidden>@cluster0.fbbdh.mongodb.net/<hidden>?retryWrites=true&w=majority"`

**Comment by nimoalr** [comment] 2020-11-04 09:14
Hello, I experience the same thing since yesterday. 
Tried from `^0.2.22` to `^0.2.29` , doesn't seems to have any impact. All I did was to build my repository after wiping node_modules and package-lock. 
Tried on another repository, did the same. Works fine before you npm install again.
Noticed it because after a new gitlab-ci build, artifacts were not working as intended. 
I can provide more information if needed. 
Thanks, and have a nice day!

**Comment by CaioRolla** [comment] 2020-11-05 06:05
Same here.

I'm also using MongoDB Atlas. For weeks i've been using the same configuration, but today i had to recreate my node_modules, and it stopped working.


`[Nest] 33020   - 05/11/2020 03:03:18   [TypeOrmModule] Unable to connect to the database. Retrying (6)... +3005ms
MongoNetworkError: failed to connect to server [cluster0-unwqs.mongodb.net:27017] on first connect [Error: getaddrinfo ENOTFOUND cluster0-unwqs.mongodb.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (C:\projetos\rolla-dev\node_modules\mongodb\lib\core\topologies\server.js:438:11)
    at Pool.emit (events.js:314:20)
    at Pool.EventEmitter.emit (domain.js:486:12)
    at C:\projetos\rolla-dev\node_modules\mongodb\lib\core\connection\pool.js:561:14
    at C:\projetos\rolla-dev\node_modules\mongodb\lib\core\connection\pool.js:994:11
    at C:\projetos\rolla-dev\node_modules\mongodb\lib\core\connection\connect.js:31:7
    at callback (C:\projetos\rolla-dev\node_modules\mongodb\lib\core\connection\connect.js:264:5)
    at Socket.<anonymous> (C:\projetos\rolla-dev\node_modules\mongodb\lib\core\connection\connect.js:294:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)`

**Comment by imnotjames** [comment] 2020-11-08 21:00
It sounds like this is only an issue after you update dependencies?  What version of mongodb's node module are you using?

**Comment by imnotjames** [comment] 2020-11-08 21:05
Also, can someone that is able to get it working with any workaround compare what's actually going to mongo between the versions?

I can't replicate this here, so replication instructions would also help.

**Comment by barbarbar338** [comment] 2020-11-09 06:11
i was using mongodb@3.6.3 (latest) for both typeorm@0.2.28 and typeorm@0.2.29 

You can create a 500mb cluster for free on their website https://www.mongodb.com/cloud/atlas
To see what's wrong just setup a normal mongodb environment with typeorm@0.2.28 and compare with typeorm@0.2.29

**Comment by mapsam** [comment] 2020-11-10 00:03
👋 I encountered this issue today while using [next-auth](https://github.com/nextauthjs/next-auth) (which uses typeorm). Here are my versions:

```
$ npm ls typeorm mongodb
├── mongodb@3.6.3 
└─┬ next-auth@3.1.0
  └── typeorm@0.2.29 
```

I was able to replicate directly with typeorm as @barbarbar338 suggested, using the following script and a free mongodb atlas instance.

```node
const {createConnection} = require('typeorm');

const main = async() => {
  const connection = await createConnection({
    type: "mongodb",
    host: "SOMETHING.mongodb.net",
    port: 27017,
    username: "USER",
    password: "PASSWORD",
    database: "test"
  });

  console.log(connection);
}

main();
```

Errors:

```
(node:38953) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

(node:38953) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [SOMETHING.mongodb.net:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND SOMETHING.mongodb.net SOMETHING.mongodb.net:27017]
    at Pool.<anonymous> (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/connection/pool.js:995:11)
    at makeConnection (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/connection/connect.js:32:7)
    at callback (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/connection/connect.js:280:5)
    at Socket.err (/Users/sammatthews/mug/typeorm-debug-example/node_modules/mongodb/lib/core/connection/connect.js:310:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
```

However, I'm unable to successfully run the script above with typeorm@0.2.28. I'm able to successfully connect to the same Mongo Atlas instance _without_ typeorm and the following example script:

```js
const MongoClient = require('mongodb').MongoClient;
const uri = "mongodb+srv://user:pass@something.mongodb.net/test?retryWrites=true&w=majority";
const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });
client.connect(async() => {
  const collection = client.db("test").collection("testtest");
  await collection.insertOne({"waka":"flocka"}) // works!
  client.close();
});
```

**Comment by kamilzielinskidev** [comment] 2020-11-22 17:01
Any news about it? Tried to use typeorm with mongodb atlas and it doesn't work in any way

**Comment by tuxmachine** [comment] 2020-11-23 13:23
I've got the same error on 0.2.29

I tried to trace the error by cloning TypeORM to my local FS, compiling and linking it in my repository... But then it works as normal. Was expecting the error to originate from #6925 

Steps I took (more-or-less):
```bash
git clone git@github.com:typeorm/typeorm.git
cd typeorm
npm install
git checkout 0.2.29
yarn link
cd ../my-project
yarn link typeorm
yarn start
```

**Comment by andrewgwallace** [comment] 2020-11-23 21:08
Same error - Tried reverting back to 0.2.28 as well as doing the "resolutions" hack (you'll need to install packages via yarn instead of npm) where you put the following into your package.json.
`  "resolutions": { "typeorm": "0.2.28" }`
Along with installing the 'reflect-metadata' package and import the following at the top level of your app (In NextJS, at the top of _app.js)
`import "reflect-metadata";`

Still no luck.

**Comment by mnlfischer** [comment] 2020-12-03 20:21
same issue with atlas

**Comment by hadnet** [comment] 2020-12-08 02:44
I'm using Loopback 4 and I got this error too using the official MongoDb connector and Atlas. I did the same as andrewgwallace without success as well.

**Comment by prabinarbadev2020** [comment] 2020-12-09 13:16
same issue here with typeORM v0.2.29 but works fine with  v0.2.28.

**Comment by philiparvidsson** [comment] 2020-12-20 10:44
Another `next-auth` user here. Can't connect because of the same problem:

```[next-auth][error][adapter_connection_error] MongoServerSelectionError: getaddrinfo ENOTFOUND *****.pcich.mongodb.net``` 

How can I downgrade to 0.2.28 when using `next-auth`?

**Comment by RickyMarou** [comment] 2020-12-20 22:19
@philiparvidsson check the [related issue](https://github.com/nextauthjs/next-auth/issues/833) in the `next-auth` repository.

Make sure that `typeorm` resolves to `"0.2.28"` and not the latest version

**Comment by pleerock** [comment] 2020-12-22 07:45
Fix was merged and will be in `v0.2.30` later this week.

**Closed** 2020-12-22 07:45 UTC
Labels: bug, driver: mongodb, needs more info

**Comment by FcoMarcosMAbreu** [comment] 2020-12-26 23:19
@pleerock, I am waiting for the update. I'm trying to use Next-Auth.js. When the update will be released?

**Comment by BenoitPingris** [comment] 2020-12-31 13:10
@FcoMarcosMAbreu  in the meantime, if you still have the issue, you can drop a `npm i typeorm@0.2.28` in your project, it will override the typeorm's version next-auth has installed.
Just did it yesterday as I had the issue and now it works fine !
Good luck!

**Comment by FcoMarcosMAbreu** [comment] 2021-01-02 16:09
> @FcoMarcosMAbreu in the meantime, if you still have the issue, you can drop a `npm i typeorm@0.2.28` in your project, it will override the typeorm's version next-auth has installed.
> Just did it yesterday as I had the issue and now it works fine !
> Good luck!

@BenoitPingris, thank you! I'd tried this but it does work to me. I don't know why. i am think seriously in use SQLite 3 in production in Vercel.

**Comment by abhimanusharma** [comment] 2021-05-20 12:00
I am also getting the same error. I tried to downgrade the version.

Here is my connection code:
```
const config: ConnectionOptions = {
	type: envConfig.DATABASE_TYPE,
	url: `"mongodb+srv://${envConfig.MONGO_USERNAME}:${encodeURIComponent(envConfig.MONGO_PASSWORD)}@project.secret.mongodb.net/${envConfig.MONGO_DBNAME}?retryWrites=true&w=majority"`,
	host: envConfig.MONGO_HOSTNAME,
	port: Number(envConfig.MONGO_PORT),
	username: envConfig.MONGO_USERNAME,
	password: encodeURIComponent(envConfig.MONGO_PASSWORD),
	database: envConfig.MONGO_DBNAME,
	connectTimeoutMS: 80000,
	useUnifiedTopology: true,
    useNewUrlParser: true,
	entities: [entityPath],
	synchronize: false,
	logging: true,
	logger: 'file',
	migrations: ['src/db/migrations/*.ts'],
	cli: {
		migrationsDir: 'src/db/migrations',
	},
```

Here is the error I am getting:
```
[Nest] 11049   - 20/05/2021, 5:26:26 pm   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +30106ms
MongoServerSelectionError: getaddrinfo ENOTFOUND project.secret.mongodb.net
    at Timeout._onTimeout (/var/www/html/project_dev/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```

I tried with latest 0.2.32 and 0.2.28 version, both are giving me error with MongoDB atlas, but it is working fine with localhost.

**Comment by arnabrahman** [comment] 2021-09-15 09:42
Any update on this? I am getting the same error like @abhimanusharma

**Comment by barnabasgre** [comment] 2022-12-22 08:31
all I did was to delete node modules folder from my project and do npm install to re-install the node modules project and the error dissapeared . Hope it works for you too
