### ISSUE TITLE
@PrimaryColumn on Date field SQLite save issue

### ISSUE THREAD

**Issue by darkyelox** [typeorm/typeorm#3426] opened 2019-01-15 21:18 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I create an Entity with a primary column using Date as type, i can save using the save method but the next time the save method cant find the already saved entities with the same date because two problems:

* The search query of the save method uses ISO dates instead of the SQLite format` "YYYY-MM-DD"`, i resolve this creating a custom ValueTransformer and momentjs (but this must be a default behavior)

* The search query don't use the `date` function when searching for primary date column

The output of the save method in a second attempt looks like:

```bash
CONSOLE INFO file:///app/vendor.js:234819:21: query:  SELECT "UserPodcastHistory"."time" AS "UserPodcastHistory_time", "UserPodcastHistory"."userId" AS "UserPodcastHistory_userId" FROM "user_podcast_history" "UserPodcastHistory" WHERE (("UserPodcastHistory"."time" = ?) OR ("UserPodcastHistory"."time" = ?)) -- PARAMETERS: ["2018-10-09","2018-10-08"]
CONSOLE INFO file:///app/vendor.js:234819:21: query:  BEGIN TRANSACTION
CONSOLE INFO file:///app/vendor.js:234819:21: query:  INSERT INTO "user_podcast_history"("time", "userId") VALUES (?, NULL) -- PARAMETERS: ["2018-10-09 00:00:00.000"]
CONSOLE ERROR file:///app/vendor.js:234822:22: query failed:  INSERT INTO "user_podcast_history"("time", "userId") VALUES (?, NULL) -- PARAMETERS: ["2018-10-09 00:00:00.000"]
CONSOLE ERROR file:///app/vendor.js:234822:22: error:  SQLITE.ExecSQL Failed 0
CONSOLE INFO file:///app/vendor.js:234819:21: query:  ROLLBACK
CONSOLE ERROR file:///app/vendor.js:47035:24: ERROR QueryFailedError: SQLITE.ExecSQL Failed 0
```

**Comment by pleerock** [comment] 2019-01-16 07:46
This issue needs a failing test. Do you have this issue without value transformer and momentjs applied?

**Comment by darkyelox** [comment] 2019-01-16 14:03
@pleerock As i said i only use ValueTransformer with momentjs only to try to use the SQLite date format but without it the save method do the same SELECT but using an ISO date format in the -- PARAMETERS array, there is no more differences, the issue is that the SELECT is not wrapping the Date column with the `date()` function and also not using the "YYYY-MM-DD" format in parameters array so nevers founds the already saved rows and attemps to do an INSERT instead of an UPDATE

**Comment by Kononnable** [comment] 2019-01-27 16:43
@darkyelox Would you provide failing test? Your description can be implemented in a few ways, maybe bug is existing on only one(or your implementation is to blame) - nobody knows.
Finding out all possibilities takes time. You know your code so it's much easier for you to write failing test - that way we could skip 'guessing' stage and get to figuring out where the bug is.

**Comment by darkyelox** [comment] 2019-02-01 19:04
Here is some failing test:


```typescript
@Entity()
class SomeEntity {
    
    @PrimaryColumn()
    public date: Date

    @Column()
    public text: string
}

const entity = new SomeEntity()
entity.date = new Date()
entity.text = 'Hello'

await getRepository(SomeEntity).save(entity)

entity.text = 'Good bye'

/* 
 Here the automatic SELECT query don't find the already saved entity,
 i guess is because the property date must be surrounded with the function
 date() in SQLite for search databases so you should use the query:
 SELECT * from some_entity where date(date) = '1998-03-08'
 
 But typeorm is doing:
 SELECT * from some_entity where date(date) = '1998-03-08'

 And not returning results so it proceeds to do an INSERT instead of UPDATE here
 and fails.
*/
await getRepository(SomeEntity).save(entity)
```

**Comment by imnotjames** [comment] 2021-07-09 08:01
I think this is a duplicate of #2286

**Comment by pleerock** [comment] 2021-11-11 14:26
Closing as duplicate of #2286

**Closed by pleerock** 2021-11-11 14:26 UTC
Labels: bug, driver: sqlite
