### ISSUE TITLE
Schema migration generated .sql files

### ISSUE THREAD

**Issue by TylerBrinks** [typeorm/typeorm#3987] opened 2019-04-12 20:23 UTC
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[x ] `mysql` / `mariadb`
[x ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[x ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is a duplicate of [this request](https://github.com/typeorm/typeorm/issues/3037) to add support for generation of .sql files for output of a migration.

Per the contribution guidelines, I'm submitting this request in hopes of implementing it and submitting a pull request.  

**Additional CLI config**
e.g.
```
"cli":{
    "scriptsDir": "/scripts/generated"
}
```

**Expected CLI behavior**
Adds a -s (--script) flag for signaling script output and -n (--name) for specifying the file name.

e.g.
```typeorm migration:run -s -n file_name.sql ```
```typeorm migration:run -s [matches migration name].sql```

**Expected output**
SQL in the dialect of the target server in a runnable script file

e.g.
```
START TRANSACTION
CREATE TABLE "SomeTableName" ("id" SERIAL NOT NULL, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "name" character varying(100) NOT NULL, CONSTRAINT "PK_fdb7139df4ab7684559efc8651b" PRIMARY KEY ("id"))

INSERT INTO "_migrations"("timestamp", "name") VALUES ($1, $2)
COMMIT
```

**Comment by Kononnable** [comment] 2019-04-20 16:57
@TylerBrinks You've got me confused - if you say it's a duplicate why are you creating new issue instead of adding a comment in existing one?

**Comment by TylerBrinks** [comment] 2019-04-20 17:24
Because the docs say an issue must be created first in order for a feature to be under development and there's no context for details or direction under the existing issue. I'm trying to propose a specific use case and output.


On Apr 20, 2019, at 10:57 AM, Kononnable <notifications@github.com<mailto:notifications@github.com>> wrote:


@TylerBrinks<https://github.com/TylerBrinks> You've got me confused - if you say it's a duplicate why are you creating new issue instead of adding a comment in existing one?

**Comment by Kononnable** [comment] 2019-04-20 20:25
If there is no concrete proposal under existing issue you can add one in a comment. No need to create separate (new) issue.

Closing as duplicate of #3037.

We have to keep issues in order and having multiple issues about one thing make it much harder to keep track of.

**Closed by Kononnable** 2019-04-20 20:25 UTC
