### ISSUE TITLE
Query failed - aws lambda + postgres + typeOrm

### ISSUE THREAD

**Issue by AlexSun98** [typeorm/typeorm#6148] opened 2020-05-28 05:43 UTC
**Environment:**
postgres: 7.4.1
typeorm: 0.2.19

**Description**
I set connection pool size to 1 and executed two identical select queries. The first one was okay, but the second one failed.  Does anyone experience this issue? This error doesn't occurs on every call. A bit strange.

**Comment by AlexSun98** [comment] 2020-06-01 01:53
it turned out that's the same error mentioned in https://github.com/typeorm/typeorm/issues/5112

**Comment by AlexSun98** [comment] 2020-06-01 02:08
Error details: "release called on client which has already been released to the pool"
![image](https://user-images.githubusercontent.com/21162558/83369667-79e18700-a400-11ea-870a-19766478b616.png)

Did anyone find a good solution to resolve this problem?

**Comment by imnotjames** [comment] 2020-10-12 08:15
Duplicate of #5112

**Closed by imnotjames** 2020-10-12 08:15 UTC
