### ISSUE TITLE
Is it internally converting the date object to UTC before saving.

### ISSUE THREAD

**Issue by tontonskie** [typeorm/typeorm#976] opened 2017-10-03 10:07 UTC
I have an entity like this:

```
@Entity('jobs')
export class Job {

  @Column(type => DateTimeWithOffset)
  start: DateTimeWithOffset;
}

export class DateTimeWithOffset {

  @Column({ name: '_offset' })
  offset: number;

  @Column('datetime', { name: '_date' })
  date: Date;
}
```

I'm saving it like this:
```
let job = new Job();
job.start = new DateTimeWithOffset()
job.start.offset = offset;
job.start.date = moment('2017-11-22 16:00').toDate();
job.save()
```

But what stored in database is `2017-11-22 08:00:00`. I check the moment object and it is parsed correctly and `toDate()` return is correct.

I'm using mysql 5.7 and my machine is in `Asia/Manila` timezone `+08:00` 

it seems like internally the date object is converted to UTC before saving.

**Comment by pleerock** [comment] 2017-10-03 10:46
Yes, it is., dates should be stored in utc in the database to avoid all kind of issues.

**Comment by tontonskie** [comment] 2017-10-03 11:10
@pleerock thanks for quick response.

Is there a typeorm way to converting this to local time when fetching ?

**Comment by pleerock** [comment] 2017-10-03 11:22
it does it, to be precision javascript itself does it.

**Comment by bartlomiej-korpus** [comment] 2017-10-03 14:03
@tontonskie check out node's TZ env variable, it affects the way dates are parsed.

**Comment by pleerock** [comment] 2017-10-13 13:11
any updates on this issue?

**Comment by Diluka** [comment] 2017-10-28 02:50
mysql `DATETIME` should store as mysql server's localtime using `timezone` config, `SHOW VARIABLES WHERE Variable_name = 'time_zone';` or `SELECT NOW();` to calibrate.

If you want to store UTC time, you should store it into `TIMESTAMP` column.

Do not store UTC time in localtime column(`DATETIME`), you are messing up my database.
If the database is migrated to a different time zone server, it will be disastrous.

**Comment by tontonskie** [comment] 2017-10-29 01:05
@pleerock i’m already okay on this issue

**Comment by dhcmrlchtdj** [comment] 2017-12-01 11:34
@pleerock, I have the same problem.

https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L305
https://github.com/typeorm/typeorm/blob/master/src/util/DateUtils.ts#L48

I think it is a bug with `new Date()` at `DateUtils`.
Maybe we should use `Date.UTC()` instead of `new Date()`.

( [Date.UTC at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC)

**Comment by vesse** [comment] 2018-01-11 12:07
Could you consider adding a parameter to `ColumnMetadata` that would allow user to define if the timestamp should be converted to UTC?

We have a legacy DB that uses `TIMESTAMP WITHOUT TIMEZONE` and all dates are stored in `EET`, but I cannot get past the conversion now as it's [hardcoded at least in Postgres driver](https://github.com/typeorm/typeorm/blob/6d367eaf614c91f3949ca1fd044a41b46aca75eb/src/driver/postgres/PostgresDriver.ts#L307)

**Comment by bartlomiej-korpus** [comment] 2018-01-11 13:12
@vesse your solution for going around postgres driver could be setting TZ env variable to whatever the TZ is in the database, that should make postgres driver parse the dares in this timezone.

**Comment by vesse** [comment] 2018-01-11 13:14
TZ on the DB server is UTC but need to store dates to these legacy tables in EET.

**Comment by AlexMesser** [comment] 2018-03-20 16:58
Dates behavior changed in `typeorm@0.2.0-alpha.29`. Please check it via `npm i typeorm@next`

**Comment by pleerock** [comment] 2018-03-26 11:12
Released in `0.1.18`. Let us know if you still have issues.

**Closed by pleerock** 2018-03-26 11:12 UTC
Labels: needs more info

**Comment by cometta** [comment] 2018-04-20 03:44
May i know if the feature to convert to UTC date before saving to mysql is removed since 0.1.18. It was working fine in 0.1.17. I tried all subsequent version from 0.1.18 onward and none of it is working.

**Comment by ravihugo** [comment] 2018-05-06 23:47
Not sure if this helps anyone - but I had similar issues until I specified the timezone as 'Z' in my connection options:


`    const connectionInfo = ({
        type: 'mysql',
        name: 'mysql',
        port: config.jdbc.port,
        host: config.jdbc.host,
        username: config.jdbc.user,
        password: config.jdbc.password,
        database: config.jdbc.database,
        timezone: 'Z',
        synchronize: false,
        entities: [__dirname + '/sql/*{.js,.ts}']
    } as MysqlConnectionOptions);
`

**Comment by focux** [comment] 2019-10-04 21:34
@Pawelh133 Why not just implementing it yourself adding this to your connection object:
```typescript
{
  ...,
  timezone: process.env.TYPEORM_TIMEZONE
}
```

**Comment by Pawelh133** [comment] 2020-01-02 13:24
I had to use configuration in .env. The reason is that the client wanted to overwrite those values via AWS server maintain panel. I could not use this on js file. It seems that option  does not work in .env file. I exchanged all datetimes values with int timestamps in database, so the problem is not occuring, and its more efficient :)

**Comment by dcworldwide** [comment] 2021-03-08 14:58
If typeorm converts JS dates to UTC before saving, does that mean I should use local dates when creating new/saving new records?

**Comment by guerrato** [comment] 2021-03-31 13:22
> Is it possible to add this property via .env file? i have tried `TYPEORM_TIMEZONE = Z` and it does not work for me.

It worked perfectly for me! PS: 
I'm using mysql

**Comment by atorresbernal** [comment] 2021-07-07 20:38
> Not sure if this helps anyone - but I had similar issues until I specified the timezone as 'Z' in my connection options:
> 
> ` const connectionInfo = ({ type: 'mysql', name: 'mysql', port: config.jdbc.port, host: config.jdbc.host, username: config.jdbc.user, password: config.jdbc.password, database: config.jdbc.database, timezone: 'Z', synchronize: false, entities: [__dirname + '/sql/*{.js,.ts}'] } as MysqlConnectionOptions);`

Now we are in 2021 and after 2 days searching this was the solution for me, thank you so much!

**Comment by migralito** [comment] 2021-08-18 01:46
Time went by and this is incredibly poorly resolved.

I have the following setup:
- typeorm on GMT-03
- server on GMT+02
- an entity with `@CreateDateColumn`
- current datetime is 2021-08-17 22:31:00 GMT -03

Then:
- repo.save({...})
- mysq> select created_at from entity;   >>> 2021-08-17 03:31:00
- console.log(repo.findOne({...}).created_at)  >>>   2021-08-17 03:31:00 GMT-03 :exploding_head:

**Comment by lordjoo** [comment] 2021-08-21 09:20
@migralito  any luck finding a way to fix this issue ?

**Comment by imnotjames** [comment] 2021-08-22 06:44
If you believe you have a different issue to report or more information please open a new issue.
