### ISSUE TITLE
Class Table Inheritance doesn't seem to work.

### ISSUE THREAD

**Issue by jmai00** [typeorm/typeorm#144] opened 2016-12-23 04:29 UTC
Hi,

So far I like this library, but I have problems trying to do class table inheritance. At first I followed the example. I got errors. Then I used your examples and reproduced the same errors. Using your example from https://typeorm.github.io/tables-and-columns.html.

- If I use the Person repository to persist, I get no errors. The Person table gets populated, but the tables in the subclasses (@ClassTableChild) do not get populated with any information.

- If I use the subclass respository or the entityManager to persist, then I get an error "Cannot read property 'propertyName' of undefined". 

I noticed there's no primary key in the subclass tables. So I added a PrimaryGeneratedColumn to the subclasses. Then I got "ER_BAD_NULL_ERROR: Column 'personId' cannot be null"

I hope you I just missed something simple.

**Comment by pleerock** [comment] 2016-12-23 04:38
I'll be honest with you - there are some problems and bugs with class table and single table inheritance that needs to be fixed. They still exist because of huge complexity they bring to ORM. 
But examples should work fine.
I recommend you to use [Concrete table inheritance](https://typeorm.github.io/tables-and-columns.html#concrete-table-inheritance) until all bugs will be fixed, or try to use other inheritance patterns and submit a PRs if you found a bug and can fix it, or submit an issue like this and provide a minimal reproduction code of your issue, so I can test it and run it and once it get more prioritized I'll take a look on it and fix it personally.

**Comment by jmai00** [comment] 2016-12-23 17:33
I thank you for providing a wonderful ORM data-mapper library.

Here is my code repoduction so we are on the same page.
I'm running the example with MySQL DB. Below are the classes

`import {Table, Column, PrimaryGeneratedColumn, TableInheritance, DiscriminatorColumn} from "typeorm";

@Table()
@TableInheritance("class-table")
@DiscriminatorColumn({ name: "type", type: "string"})
export class Person {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;
}`

`import {ClassTableChild, Column, PrimaryGeneratedColumn} from "typeorm";
import {Person} from "./Person";

@ClassTableChild()
export class Student extends Person {
    @Column()
    faculty: string;
}`

`import {ClassTableChild, Column} from "typeorm";
import {Person} from "./Person";

@ClassTableChild()
export class Employee extends Person {
    @Column()
    salary: number;
}`

`import {ClassTableChild, Column} from "typeorm";
import {Person} from "./Person";

@ClassTableChild()
export class Homesitter extends Person {
    @Column()
    numberOfKids: number;
}`

`require("reflect-metadata");
import {createConnection, ConnectionOptions, Connection} from "typeorm";
import {Person} from "./entities/Person";
import {Student} from "./entities/Student";

let dbConnection = {
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "root",
    database: "test_dev",
};

createConnection({
    driver: dbConnection,
    entities: [
        __dirname + "/entities/*.js",
    ],
    dropSchemaOnConnection: true,
    autoSchemaSync: true,
} as ConnectionOptions).then( async (connection: Connection) => {
    let x = connection.getRepository(Person);
    // let x = connection.getRepository(Student);
    // let x = connection.entityManager;

    let student = new Student();
    student.firstName = "Hello";
    student.lastName = "World";
    student.faculty = "University";

    await x.persist(student);
    console.log("Done!");
}).catch( (error) => {
    console.log(`Error: ${error.message}`);
});`

So I get a database creation like this:
![capturedb](https://cloud.githubusercontent.com/assets/6107443/21459033/f32ab964-c8ef-11e6-9980-0a06ddf802af.PNG)

1) Using the getRepository(Person) I get the following output in my DB:
![try1](https://cloud.githubusercontent.com/assets/6107443/21459231/59fde3f4-c8f1-11e6-9994-b08202d755f9.png)

The Student table is missing values of "Univeristy", PersonId

2) Using the getRepository(Student) or entityManager, I get the following error:
> Error: Cannot read property 'propertyName' of undefined

**Closed** 2016-12-23 19:30 UTC

**Comment by pleerock** [comment] 2016-12-23 19:34
that was a bug. Released in `typeorm@next` please try it.

**Comment by erlopezh** [comment] 2017-02-13 14:05
Hi.
Same problem here, "typeorm": "0.0.9-alpha.3"

`saving the employee: 
Error:  TypeError: Cannot read property 'propertyName' of undefined
    at EntityMetadata.getEntityIdMixedMap`
