### ISSUE TITLE
There should be an option to auto generate migration which uses Migrations API

### ISSUE THREAD

**Issue by abhijeet1403** [typeorm/typeorm#4610] opened 2019-08-20 09:11 UTC
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ x ] `cordova`
[ x ] `mongodb`
[ x ] `mssql`
[ x ] `mysql` / `mariadb`
[ x ] `oracle`
[ x ] `postgres`
[ x ] `cockroachdb`
[ x ] `sqlite`
[ x ] `sqljs`
[ x ] `react-native`
[ x ] `expo`

**TypeORM version:**

[ ] `latest`
[ x ] `@next`
[ ] `0.x.x` (or put your version here)

The current migrations when auto generated use hard coded indexes and keys in the table, e.g.
```
await queryRunner.query("CREATE TABLE IF NOT EXISTS `rule` (`created_by` varchar(255) NOT NULL, `last_modified_by` varchar(255) NOT NULL, `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `last_modified_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `description` varchar(1000) NULL, `status` varchar(255) NOT NULL DEFAULT 'ACTIVE', `type` varchar(255) NOT NULL DEFAULT 'SIMPLE', `rule_configuration` text NOT NULL, `rule_expression` text NOT NULL, `organization_id` varchar(255) NULL, UNIQUE INDEX `IDX_e272edd8cbd400c7c29462142f` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
```

I propose to add an option to auto generate the same migration in a migration API syntax.
So it is never tied to the same database.
```
async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.createTable(new Table({
            name: "question",
            columns: [
                {
                    name: "id",
                    type: "int",
                    isPrimary: true
                },
                {
                    name: "name",
                    type: "varchar",
                }
            ]
```

And auto generate the indexes and other constants for each run. If you think the same let me know I'll start working on the design for this behaviour.

Also this can work along with [4611](https://github.com/typeorm/typeorm/issues/4611)

**Comment by Kononnable** [comment] 2019-10-15 06:51
Duplicate of #3607

**Closed** 2019-12-30 13:04 UTC
Labels: comp: migrations, duplicate
