### ISSUE TITLE
CreateDateColumn and UpdateDateColumn error

### ISSUE THREAD

**Issue by aspandolfi** [typeorm/typeorm#1172] opened 2017-11-12 23:52 UTC
CreateDateColumn and UpdateDateColumn are not working in MySQL. The syntax when the tabela is creating is not correct. Therefore, MySQL throws exception.

**Comment by pleerock** [comment] 2017-11-16 06:30
can you show me error you have and code you are running? Also mysql version. There are tests which completely cover this functionality and it cannot be broken.

**Comment by pleerock** [comment] 2018-03-16 07:51
duplicate of #609

**Closed by pleerock** 2018-03-16 07:51 UTC
Labels: driver: mysql, needs more info
