### ISSUE TITLE
Support for functional index

### ISSUE THREAD

**Issue by thellimist** [typeorm/typeorm#3605] opened 2019-02-08 21:05 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

Is there a way to add functional indexes? The example I'm using is below

```
create unique index users_unique_lower_email_idx on users (lower(email));
```

```
\d users
                              Table "public.users"
     Column      |  Type   |                     Modifiers
-----------------+---------+----------------------------------------------------
 id              | integer | not null default nextval('users_id_seq'::regclass)
 email           | text    | not null
 password_digest | text    | not null
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "users_email_key" UNIQUE CONSTRAINT, btree (email)
    "users_unique_lower_email_idx" UNIQUE, btree (lower(email))
```

**Comment by imnotjames** [comment] 2020-10-15 04:28
The only currently supported way to do this is to define the index but turn of synchronization.

```
@Index("users_unique_lower_email_idx", { unique: true, synchronize: false })
```

Then manually define it in the migrations.

**Comment by imnotjames** [comment] 2020-10-15 05:05
Duplicate of #2561

**Closed by imnotjames** 2020-10-15 05:05 UTC
Labels: driver: postgres, new feature, question
