### ISSUE TITLE
[sqlite] Find operation with between filter returns empty array

### ISSUE THREAD

**Issue by meakgoz** [typeorm/typeorm#7675] opened 2021-05-23 08:33 UTC
For following query;

```
let startDate = this.parseDate(request.query.startDate);
let endDate = this.parseDate(request.query.endDate);

const myEntityForTimeInterval = await this.myEntityRepository.find({
	relations: ['related1', 'related2', 'related3'],
	where: {
		date: Between(startDate, endDate),
	},
});
```
where `parseDate` simply returns a Date object.

I get correct results when I am using a postgresql database, but it returns an empty array in case of sqlite.

Here is what I get from `npm list --dept=0`
```
├── @types/cors@2.8.10
├── @types/node@8.10.66
├── body-parser@1.19.0
├── cors@2.8.5
├── express-validator@6.10.1
├── express@4.17.1
├── log4js@6.3.0
├── nodemon@2.0.7
├── pg@8.6.0
├── reflect-metadata@0.1.13
├── sqlite3@5.0.0
├── ts-node@9.1.1
├── typeorm@0.2.32
└── typescript@4.2.4
```

**Comment by AlexMesser** [comment] 2021-05-29 10:18
Duplicate of #2286

**Closed by AlexMesser** 2021-05-29 10:18 UTC
