### ISSUE TITLE
Postgres: The method `output` in insert query builder not working with arrays 

### ISSUE THREAD

**Issue by sudohalt** [typeorm/typeorm#7830] opened 2021-07-02 19:17 UTC
## Issue Description
`output` on for insert query builder not working when an array is used.

### Expected Behavior
```
 const rawResult = (await getConnection()
    .createQueryBuilder()
    .insert()
    .into("test", ["name", "age"])
    .values([
      { name: "John", age: 20 },
      { name: "Smith", age: 50 },
    ])
    .returning(["name", "age"])
    .execute()).raw;
  // Expected: Should return the columns (specified in output) for the rows that were inserted.
  rawResult === [{"name":"John","age":20},{"name":"Smith","age":50}]
```

### Actual Behavior
```
 const rawResult = (await getConnection()
    .createQueryBuilder()
    .insert()
    .into("test", ["name", "age"])
    .values([
      { name: "John", age: 20 },
      { name: "Smith", age: 50 },
    ])
    .returning(["name", "age"])
    .execute()).raw;
    // Actual: When an array is used it returns an empty array instead (this doesn't happen when using a string)
  rawResult === []
```

| Operating System    |      macOS Catalina    |
| Node.js version     | v14.13.0 | 
| Typescript version  | v4.0.3 | 
| TypeORM version     | v0.2.26 | 

### Additional Context

For now I can solve the issue by doing the following:

```
...
.output(["name", "age"].join(",")
...
```

I assume the issue is in QueryBuilder#getReturningColumns, but haven't looked too deep into it

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-07-04 04:37
Duplicate of #2716

**Closed by imnotjames** 2021-07-04 04:37 UTC
Labels: bug, requires triage
