### ISSUE TITLE
Between Operators keep find Operation lasting forever

### ISSUE THREAD

**Issue by jawil003** [typeorm/typeorm#6937] opened 2020-10-19 18:09 UTC
**Issue type:**

[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `github:cuibonobo/typeorm-package`

**Steps to reproduce or a small repository showing the problem:**

1. Create a React-Native App and install this Typeorm, because default one not working with SQLite. Try to search with a where following a Between Statement like this:
```
const result = await repo.findAll(
                  {
                    where: {
                      leaveDate: Between(
                        formValue.from,
                        formValue.to,
                      ),
                    },
                    order: { lastname: "ASC" },
                  },
                );
```

2. Put this in an Async Function and put a statement after it, it will never gets executed.

I use the Custom Version because the default one never worked for me. Just keeped asking for `react-native-sqlite-storage` which was already installed!

**Comment by imnotjames** [comment] 2020-10-19 18:28
Can you create a repository that can be used to reproduce this

**Comment by jawil003** [comment] 2020-10-19 18:45
I will do it tomorrow and add the Link. Should be no Problem, hope I did something wrong because I really need this feature for my App 😬. Thanks for your Reply 👌🏼

**Comment by jawil003** [comment] 2020-10-22 20:38
@imnotjames [Here](https://github.com/jawil003/TypeormBetweenExample) is a working non working example :D. Hope you can help me out ;) Put a Fixme at the Part with the Issue and a working alternative without the where.

**Comment by leonardofalk** [comment] 2020-10-22 20:41
I think the problem is because you're importing from 'typeorm', you should use 'typeorm/browser'.

**Comment by jawil003** [comment] 2020-10-22 20:42
@leonardofalk I check if it is working then, thanks for the Suggestion ;)

**Comment by jawil003** [comment] 2020-10-22 20:49
@leonardofalk I imported Between from typeorm/browser but still hanging while fetching with the Condition. Updated the Example.

**Comment by leonardofalk** [comment] 2020-10-22 20:52
Nope, you must import everything

**Comment by imnotjames** [comment] 2020-10-22 20:53
You shouldn't have to import from `typeorm/browser` if you've set up webpack correctly.

**Comment by jawil003** [comment] 2020-10-22 20:54
> You shouldn't have to import from `typeorm/browser` if you've set up webpack correctly.

It is just the default React Native Config with Babel if there is Webpack only hidden for me.

**Comment by leonardofalk** [comment] 2020-10-22 20:55
From what I know, typeorm uses NodeJS stuff, typeorm/browser is for the browser and ReactNative runtime is more or like it.

@imnotjames RN uses metro bundler instead.

**Comment by jawil003** [comment] 2020-10-22 20:55
> You shouldn't have to import from `typeorm/browser` if you've set up webpack correctly.

Will try it tomorrow, so what is the Reason for that? Is the typeorm import not just a reexport of typeorm/browser files and functions?

**Comment by jawil003** [comment] 2020-10-22 20:56
> Nope, you must import everything

Okay will try that tomorrow.

**Comment by imnotjames** [comment] 2020-10-22 21:01
`typeorm` import will go to different things depending on how you've configured your bundler.  `metro` SHOULD use the browser fields by default.

https://github.com/typeorm/typeorm/issues/6839#issuecomment-706673256

> I replaced all references to `typeorm/browser` with just `typeorm`.  EG `import TypeORM from "typeorm";`
>
> I updated the `metro.config.js` to contain the following:
>
> ```
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>         resolver: {
>             resolverMainFields: ['browser', 'main']
>         },
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: false,
>       },
>     }),
>   },
> };
> ```
>
> Thing is, for the `resolverMainFields` - that's the default.  So it should be using that already.

Not saying this fixes your problem but it might help.  I'll still try to grab the repo down in the next few days if you haven't resolved it by then :)

**Comment by imnotjames** [comment] 2020-10-22 21:02
I'll have to find where in the docs it says to use `typeorm/browser` because that's technically not correct - I think it might actually mess up some of the `browser` mainfield replacements in some cases..

**Comment by leonardofalk** [comment] 2020-10-22 21:26
I think it's not in the docs but the example:

https://github.com/typeorm/react-native-example/blob/master/src/App.tsx#L16

**Comment by jawil003** [comment] 2020-10-27 10:05
@leonardofalk @imnotjames Today I replaced every "typeorm" import with "typeorm/browser" but the between Operator doesn't work still... May I try a manual Query is this supported for SqLite yet? Updated the Example Repo.

**Comment by jawil003** [comment] 2020-10-27 10:15
May the Syntax of the Generated SQL is somehow wrong, can't see a problem but I#m not into SqLite as others: ```SELECT "Contact"."_id" AS "Contact__id", "Contact"."firstname" AS "Contact_firstname", "Contact"."lastname" AS "Contact_lastname", "Contact"."email" AS "Contact_email", "Contact"."phone" AS "Contact_phone", "Contact"."enterDate" AS "Contact_enterDate", "Contact"."leaveDate" AS "Contact_leaveDate", "Contact"."validationCode" AS "Contact_validationCode", "Contact"."enabled" AS "Contact_enabled" FROM "contacts" "Contact" WHERE "Contact"."leaveDate" BETWEEN ? AND ? ORDER BY "Contact"."lastname" ASC -- PARAMETERS: ["2020-10-01T09:11:02.472Z","2020-10-27T10:11:02.472Z"]```

**Comment by leonardofalk** [comment] 2020-10-29 00:59
Did some actual tests using your repository, and it seems a legit bug, Between can't convert the input correctly for SQLite.

[Based on this answer](https://stackoverflow.com/a/29971871), Between should convert params to `["2020-10-01 09:11:02", "2020-10-27 10:11:02"]`. Not sure if Between operator has enough context to check entity metadata, and see if the field is Date/Time and then change accordingly. Another way is to input your params as strings, as expected by SQLite.

**Comment by jawil003** [comment] 2020-10-29 07:40
@leonardofalk So I can convert the Dates to String in the SQL fefault Format and it should be fine?

**Comment by jawil003** [comment] 2020-10-29 07:41
Just need to get this Feature working go complete my App, do this would be really great to have a fast solution for this ☺️

**Comment by leonardofalk** [comment] 2020-10-29 12:07
@jawil003 Yeah, you can also use >= / <= operators, I didn't test it though, but I guess it must behave like between.

I'll link SQLite docs here, as it's a more reliable source.

https://sqlite.org/lang_datefunc.html

**Comment by jawil003** [comment] 2020-10-29 12:40
@leonardofalk So you mean Select all and filter then? I my Javascript Code? This can cause a lot of performance issues because I can have a lot of entries 😬

**Comment by leonardofalk** [comment] 2020-10-29 13:07
@jawil003 Ofc not, I mean SQL:

```sql
select x from y where y.datecolumn >= MIN_DATE and y.datecolumn <= MAX_DATE
```

This is valid in this scenario.

**Comment by jawil003** [comment] 2020-10-29 13:10
> @jawil003 Ofc not, I mean SQL:
> 
> ```sql
> select x from y where y.datecolumn >= MIN_DATE and y.datecolumn <= MAX_DATE
> ```
> 
> This is valid in this scenario.

So there is an issue with the BETWEEN keyword in general or only in the convert of the Date to String to insert in the generated Sql Query?

**Comment by leonardofalk** [comment] 2020-11-06 20:19
I didn't test other operators, but SQLite docs say it does work with ISO standards, so it could be something else.

**Comment by imnotjames** [comment] 2021-06-19 22:44
This looks like everything is working as intended on the typeorm side. 

The react-native side instead seems to be the problem.

Is there anything that points otherwise?

**Comment by imnotjames** [comment] 2021-06-25 02:02
If there's anyone that can create a reproducible example that points at this being an issue on the TypeORM side please re-open a new issue with the related information.

At this point in time it really seems to be an issue with the upstream project.

As such, I'm closing this issue out.

**Closed by imnotjames** 2021-06-25 02:02 UTC
Labels: bug, can be closed?, driver: react-native, needs more info
