### ISSUE TITLE
NJS-018 invalid ResultSet from oracle for typeorm stored procedure using toQueryStream

### ISSUE THREAD

**Issue by nisha1794n** [typeorm/typeorm#9340] opened 2022-09-01 07:07 UTC
The following code i wrote for getting resultset:

```
run(transactionId: string) {

 return result : any = appDataSource.query("BEGIN TXN_GENERATESTANRRN(:txnid,:cur); END;", [
      transactionId,
      { type: oracledb.CURSOR, dir: oracledb.BIND_OUT }
    ]);
  }
```

result I am getting : 
```
 [
  ResultSet {
    _rowCache: [],
    _processingStarted: false,
    _convertedToStream: false,
    _allowGetRowCall: false,
    _isActive: false,
    _parentObj: Connection {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _dbObjectClasses: {},
      _requestQueue: [],
      _inProgress: false,
      _pool: [Pool],
      _newSession: true,
      [Symbol(kCapture)]: false
    }
  }
]
```
I am passing the result[0] to fetchRCFromStream function : 

```
export async function fetchRCFromStream(result[0] : any, transXpedia: TransXpedia) {

  return new Promise((resolved, rejected) => {
    transXpedia.results = [];
    try {
      var stream = cursor.toQueryStream();

    } catch (error: any) {
      console.log("Error: ", error)
    }


    stream.on('error', function (e: any) {
      console.log("error", e);

      return rejected(transXpedia);

    });

    stream.on('metadata', function (metadata: any) {
      // access metadata of query
      //       
    });

    stream.on('data', function (data: any) {
      transXpedia.results.push(data);


    });

    stream.on('end', function () {
      stream.destroy();

    });

    stream.on('close', function () {
      return resolved(transXpedia);

    })
  });
}

```

but  It is throwing following error  : 

```
  Error: NJS-018: invalid ResultSet
    at QueryStream._destroy (/home/nishapatil/Projects/Typescript Projects/LVB/node_modules/oracledb/lib/queryStream.js:51:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:24802) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/home/nishapatil/Projects/Typescript Projects/LVB/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/home/nishapatil/Projects/Typescript Projects/LVB/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/home/nishapatil/Projects/Typescript Projects/LVB/node_modules/express/lib/response.js:278:15)
    at sendToClient (/home/nishapatil/Projects/Typescript Projects/LVB/src/api/utils/misc.utils.ts:61:8)
    at /home/nishapatil/Projects/Typescript Projects/LVB/src/api/controllers/branchEkyc.controller.ts:52:21
    at Generator.throw (<anonymous>)
    at rejected (/home/nishapatil/Projects/Typescript Projects/LVB/src/api/controllers/branchEkyc.controller.ts:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24802) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.




```

**Comment by Ginden** [comment] 2022-09-03 18:07
Duplicate of https://github.com/typeorm/typeorm/issues/8687

I recommend using Oracle driver directly for advanced use cases, though.

**Closed by Ginden** 2022-09-03 18:07 UTC
Labels: bug, requires triage

**Comment by nisha1794n** [comment] 2022-09-11 16:14
Thanks for the help but i am still not able to resolve the issue.
