### ISSUE TITLE
DB is not dropped after all tests are completed

### ISSUE THREAD

**Issue by AndonMitev** [typeorm/typeorm#7200] opened 2020-12-17 08:35 UTC
Having following piece of code:

```
beforeAll(async done => {
    const connectionManager = getConnectionManager();
    const connection = connectionManager.create({
        type: 'mongodb',
        url: 'mongodb://localhost:27017',
        synchronize: true,
        appname: 'test',
        database: 'my-test-db',
        dropSchema: true,
    });
    await connection.connect();
    done();
});

afterAll(async done => {
    await getConnection().dropDatabase();

    done();
});
```

And the DB is not dropped after tests are completed

**Comment by Bloectasy** [comment] 2020-12-17 11:21
Having the a similar maybe even the same issue, after updating typeORM from v0.2.25 to v 0.2.29 i get a timeout error (with the createConnection method from typeORM and using a mongodb cluster instead of localhost) 
`[2020/12/16 21:38:28][BOT][ERROR][UNHANDLED_REJECTION]: getaddrinfo ENOTFOUND bloectasy.5cpkg.mongodb.net
{
"name": "MongoServerSelectionError",
"reason": {
"type": "Single",
"setName": null,
"maxSetVersion": null,
"maxElectionId": null,
"servers": {},
"stale": false,
"compatible": true,
"compatibilityError": null,
logicalSessionTimeoutMinutes": null,
"heartbeatFrequencyMS": 10000,
"localThresholdMS": 15,
"commonWireVersion": null
},
"stack": "MongoServerSelectionError: getaddrinfo ENOTFOUND bloectasy.5cpkg.mongodb.net
    at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)"
}`

**Comment by dhritzkiv** [comment] 2021-06-23 01:08
I don't know if this is the source of your issues, and I don't know which testing framework you're using, but you're likely to run into problems due to your usage of both a Promise (async) and a callback.

**Comment by sebastiantf** [comment] 2022-03-26 11:09
I'm seeing something similar where `dropDatabase()` doesn't seem to actually run the `DROP DATABASE` query, and thus not dropping a FUNCTION

**Comment by pleerock** [comment] 2022-03-26 15:48
Information provided in the issue is not enough to understand why it happens. No information on what queries were executed by calling `dropDatabase` method. Thus I'm going to close it.

**Closed by pleerock** 2022-03-26 15:48 UTC
Labels: bug, requires triage
