### ISSUE TITLE
LessThan and other operators doesn't work

### ISSUE THREAD

**Issue by yogevlahyani** [typeorm/typeorm#3959] opened 2019-04-08 14:13 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using typeorm inside js and it seems like the query parsed incorrectly, here is my example:
```js
const entities = await Entity.count({
      where: {
        name: 'entityName',
        updatedAt: LessThan(new Date()),
      },
    });
```

And here is the sql output:
```sql
SELECT COUNT(DISTINCT("Entity"."id")) as "cnt" FROM "entities" "Entity" WHERE "Entity"."name" = $1 AND "Entity"."updatedAt" = $2 AND "Entity"."deletedAt" IS NULL -- PARAMETERS: ["entityName",{"_type":"lessThan","_value":"2019-04-08T12:11:05.602Z","_useParameter":true,"_multipleParameters":false}]
```

It's working great within Nest.js framework but doesn't work inside a pure node.js file.

Another thing to mention - Methods works just fine like:
Entity.find()
Entity.count()
etc ..
So I don't think it's something with the db connection

**Comment by Kononnable** [comment] 2019-04-20 08:44
@yogevlahyani 
I'm sorry to hear that something is not working for you, but what are we supposed to do about that? There is clearly not enough info to even reproduce the problem. You mention that it works for you in one setup and it doesn't in another one - I can only guess that you've mixed up something and this function in typeorm works well, but you've made some mistakes in your code(probably related to configuration of typeorm).
You've also said that it doesn't work as expected, but didn't mention what it's doing - throwing and error, returning empty result etc.

**Comment by yogevlahyani** [comment] 2019-04-21 07:29
@Kononnable I logged the SQL query and it seems that LessThan stays an object, for example:
```
where: {
  updatedAt: LessThan(new Date()),
}
```

Will be:
```
UPDATE ... updatedAt = { _value: .. ...... }
```

instead 
```
UPDATE ... updatedAt < new Date()
```

It seems that it didn't work as a local npm installed package but when I deployed it and installed the package from github, it worked.

I believe it is something about the shared typeorm package and the connection itself, but it did worked partly in the local way..

**Comment by pkuczynski** [comment] 2019-04-24 13:35
I am experiencing the same problem with postgres:

```
await Device.findOne({ id: Not(Equal(device.id)), name: device.name }))
```

Produces an error:

```
QueryFailedError: invalid input syntax for integer: "{"type":"not","_useParameter":true,"_multipleParameters":false,"_value":{"type":"equal","_useParameter":true,"_multipleParameters":false,"_value":1}}"
```

**Comment by 3llen** [comment] 2020-01-16 16:39
I have the same issue, LessThan does not work with date for me

**Comment by jaakasser** [comment] 2020-02-28 14:42
Seems to be the same issue using [typeorm-store](https://github.com/Mrtenz/typeorm-store).

Using the suggested setup:
```
app.use(session({
   secret: 'secret',
   resave: false,
   saveUninitialized: false,
   store: new TypeormStore({ repository })
}))
```

Produces an error:
```
query failed: DELETE FROM `sessions` WHERE `expiresAt` = ? -- PARAMETERS: [{"_type":"lessThan","_value":1582899907,"_useParameter":true,"_multipleParameters":false}]
```

The relevant source code uses LessThan:

```
clearExpiredSessions = (callback?: (error: any) => void) => {
    const timestamp = Math.round(new Date().getTime() / 1000);

    this.repository
      .delete({ expiresAt: LessThan(timestamp) })
      .then(() => callback && callback(null))
      .catch((error: any) => callback && callback(error));
  };
```

**Comment by CoreParadox** [comment] 2020-05-12 07:10
Same issue here, couldn't get it working with dates, nor numbers (timestamps) using MongoDB

```js
        var date = new Date().getTime();
        return DataService.ReminderService.find({ timestamp: LessThanOrEqual(date) })
```

Timestamp: 1589267238964

Result Empty.

Two DB entries contain the following timestamps:
- 1589265563000.0
- 1589265462000.0

**Comment by matheusalbino** [comment] 2020-07-18 17:07
I have the same issue with `Like `and others operators, the query doesn't change the operator and the parameters contain a JSON structure.

**Comment by tan-dd** [comment] 2020-09-03 05:57
I am also experiencing the same issue with the date field

**Comment by nodeful** [comment] 2020-09-25 13:41
Yeap started to experience this issue out of nowhere 🤔

**Comment by nodeful** [comment] 2020-09-25 13:42
```
QueryFailedError: invalid input syntax for type timestamp: "{"_type":"moreThan","_value":"2020-09-25T13:37:03.393Z","_useParameter":true,"_multipleParameters":false}"
```

**Comment by imnotjames** [comment] 2020-10-05 06:11
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2020-10-16 06:02
I can't replicate this and I've tried a few different approaches.  I used an entity and the code from the first post exactly.

As such, and without a reproducible example, I'll be closing this issue.  Please open a new issue with a way to reproduce the problem if it's still occurring.

I have a feeling that this is more environment related than TypeORM related - similar to #5676

**Closed by imnotjames** 2020-10-16 06:02 UTC
Labels: bug, can be closed?, comp: find options, driver: postgres, needs more info, question

**Comment by SaveYourTime** [comment] 2020-11-03 14:12
> I have the same issue with `Like` and other operators, the query doesn't change the operator and the parameters contain a JSON structure.

Same issue here.

My code is:

```ts
const store = await connection
  .createQueryBuilder<Store>(Store, 'store')
  .where('store.name LIKE :name', { name: Like(`%${name}%`) })
  .getOne();
```


and get an error like this:

```js
FindOperator { _type: 'like', _value: '%WORD%', _useParameter: true, _multipleParameters: false },
```

**Comment by nodeful** [comment] 2020-11-03 14:42
I did a complete nuke of node_modules.
Then did `npm i -S typeorm@latest pg@latest` followed by an `npm i` and the error disappeared for me 🤷🏻‍♂️

**Comment by zacharyvoase** [comment] 2021-04-07 04:52
@SaveYourTime I know it's a bit late, but: you're double-escaping your param. Either do:

```javascript
.where({ name: Like(`%${name}%`) })
```

or:

```javascript
.where('store.name LIKE :name', { name: `%${name}%` })
```

**Comment by ex3ndr** [comment] 2021-06-13 14:30
I also see such an error for just a single field "location" and also get "{_type: 'not' ....}" in my SQL query for some reason.
In my case it is 'Not(IsNull())'.

**Comment by Goldziher** [comment] 2021-11-01 15:56
Same issue...  out of the blue, enterprise project. I have dozens of tests failing - they used to work until today. No clue what changed. It extremely annoying to have such an unstable ORM.

**Comment by galh-cyera** [comment] 2022-01-04 14:48
any updates?
