### ISSUE TITLE
Get an error for repository functions `find` and `findOne` with mongodb driver

### ISSUE THREAD

**Issue by varyanik** [typeorm/typeorm#7929] opened 2021-07-18 14:21 UTC
### Expected Behavior

Repository functions should return expected results (i.e. array of objects for `find` and an object for `findOne`).

### Actual Behavior

Repository functions `find` and `findOne` raise errors.

```
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (app/src/entity-manager/MongoEntityManager.ts:679:37)
    at MongoEntityManager.<anonymous> (app/src/entity-manager/MongoEntityManager.ts:97:23)
    at step (app/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (app/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at fulfilled (app/node_modules/typeorm/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to Reproduce

```typescript
const users = await this.usersRepository.find();

const user = await this.usersRepository.findOne(id);
```

### My Environment

`NestJS`

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Linux Mint 20.2 Cinnamon     |
| Node.js version     | v16.4.1 | 
| Typescript version  | v4.3.5 | 
| TypeORM version     | v0.2.34 | 

### Additional Context

Looks like bugs are in `typeorm/src/entity-manager/MongoEntityManager.ts`.

It can be fixed replacing `ObjectID` with `ObjectId`:
```
PlatformTools.load("mongodb").ObjectID
```

Also there is a hack to replace `Cursor` with `FindCursor`:
```
PlatformTools.load("mongodb").Cursor
```

### Relevant Database Driver(s)

- [x] `mongodb`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by varyanik** [comment] 2021-07-18 18:29
Related to https://github.com/typeorm/typeorm/issues/7907

**Comment by imnotjames** [comment] 2021-07-18 19:53
Duplicate of #7907

**Closed by imnotjames** 2021-07-18 19:53 UTC
Labels: bug, requires triage
