### ISSUE TITLE
Add custom select and map to property of entity

### ISSUE THREAD

**Issue by ToonvanStrijp** [typeorm/typeorm#1822] opened 2018-03-25 13:51 UTC
**Issue type:**

[ ] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[X] `cordova`
[X] `mongodb`
[X] `mssql`
[X] `mysql` / `mariadb`
[X] `oracle`
[X] `postgres`
[X] `sqlite`
[X] `sqljs`
[X] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
What I to accomplish is to add a custom select that maps to a property of my Entity. I've found an work around but would like to know if there is an easier/cleaner way to do this.

So I've my model:

```
@Entity('groups')
export class Group extends BaseEntity{

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToMany(type => User, user => user.groups)
    @JoinTable({
        name: 'groups_users',
        joinColumn: {
            name: 'group_id',
            referencedColumnName: 'id'
        },
        inverseJoinColumn:
            {name: 'user_id',
                referencedColumnName: 'id'
            }
    })
    users: User[];

    active: boolean;
}
```

This entity has a ManyToMany relationship to User. The `JoinTable` `groups_users` has one extra column `active` this `active` indicates if the group that the user is linked to is visible.

When I query the groups to get all the groups for one user (also the inactive groups) I do this:

```
let query = this.groupRepository
            .createQueryBuilder('group')
            .innerJoin('groups_users', 'gu')
            .innerJoin('group.users', 'user', 'user.deleted_at is null AND group_user.user_id = :id',
                {id: userId})
            .orderBy('group.id', 'ASC')
            .andWhere('group.deleted_at IS NULL');
```

As you can see the `Group` entity has a property called active. As for now the `active` property is not seen by `typeorm` so what I did was the following:

I added this to the active property:

```
 @Column('tinyint', {
        nullable: true,
        select: false
    })
    active: boolean;
```

By setting `select` to `false` the other queries won't break (since active isn't a real column inside the `group` table).

Now I added this to the query:

```
.addSelect(s => s.select('active').from('groups_users', 'gu').where('gu.group_id = group.id AND gu.user_id = :id', {id: userId}), 'group_active')
```

By doing this the active property is filled for each user and the `active` is true or false according the 0 or 1 in `JoinTable`.

To query I ended up with is:
```
let query = this.groupRepository
            .createQueryBuilder('group')
            .addSelect(s => s.select('active').from('groups_users', 'gu').where('gu.group_id = group.id AND gu.user_id = :id', {id: userId}), 'group_active')
            .innerJoin('groups_users', 'gu')
            .innerJoin('group.users', 'user', 'user.deleted_at is null AND group_user.user_id = :id',
                {id: userId})
            .orderBy('group.id', 'ASC')
            .andWhere('group.deleted_at IS NULL');
```
which leaves me with the correct output. Now this seems a little bit of a hack or is this the propper way to do this?

**Comment by pleerock** [comment] 2018-03-26 07:19
Correct, its a hack. Official solution named `addSelectAndMap` will come into QueryBuilder in 0.3.0. Closing as duplicate of #296

**Closed by pleerock** 2018-03-26 07:19 UTC

**Comment by ToonvanStrijp** [comment] 2018-04-11 15:06
@pleerock do you have a work around, cause if i want to insert or update a group it failed because the active is not a real column in the database.

Hope there is a temporary fix?

**Comment by pleerock** [comment] 2018-04-11 18:32
create a separate query and map a data into your property

**Comment by ToonvanStrijp** [comment] 2018-04-11 21:47
@pleerock Thanks I'll go for that since there is no other good fix. When wil the 0.3.0 launch? :)

**Comment by pleerock** [comment] 2018-04-12 04:43
Hope in the late summer.

**Comment by stonecold123** [comment] 2018-04-23 09:39
@pleerock 
I'm in need of similar feature to map reply total counts to each post. 
````
this.groupRepository.createQueryBuilder('r')
.addSelectAndMap(`Count(r.*)`,'replyTotal')
````

**Comment by derSoerrn95** [comment] 2018-09-17 13:45
I also need this feature. Do u know when the 0.3.0 launch is?

**Comment by Asarew** [comment] 2019-09-08 08:30
I created a pull request that implements this feature with a simplistic approach: #4703

**Comment by duprez** [comment] 2019-11-11 13:30
Any updates? I need this feature

**Comment by SergeyAlexsandrovich** [comment] 2019-11-21 19:14
Any updates? News?

**Comment by hong-duc** [comment] 2020-01-03 09:52
Hi I do the same but if I add a `select` on top, the `addSelect` result will not map to property, like this:
```
const account = await query
      .select('account._taiKhoan')
      .addSelect(
        s =>
          s
            .select(
              'so_lan_dang_nhap_sai',
              `${query.alias}_so_lan_dang_nhap_sai`,
            )
            .from('r_contact_client', 'r_ct')
            .where(
              'r_ct.contact_id = account.contact_id and r_ct.app_key = :app_key',
              { app_key: accountId.appKey },
            ),
        `${query.alias}_so_lan_dang_nhap_sai`,
      )
      .where('account.tai_khoan ilike :tai_khoan', {
        tai_khoan: accountId.taiKhoan,
      })
      .andWhere('account.app ? 8::text')
      .getOne();
```

The property is like this:

```
@Column({
    nullable: true,
    select: false,
    name: 'so_lan_dang_nhap_sai',
  })
  public _soLanDanhNhapSai: number;
```

Is this hack only with select all property ?

**Comment by noorsheikh** [comment] 2020-01-13 03:02
Hello Guys,

If someone still looking for an answer. Here is a workaround that I did for myself.
My Case: I had a Job entity and a Category entity. I wanted to list all categories with total # of jobs posted for each category something like this:
```
[
    {
        "id": 2,
        "name": "Accounting",
        "total": "1"
    },
    ...
]
```

Here is my DDL for job_categories table:
```
DROP TABLE IF EXISTS `job_category`;
CREATE TABLE `job_category` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(20) NOT NULL
);
```

I do not have the total column stored in my category table. For a workaround I added a total column in my entity with `{ select: false }` as below:
```
@Column('int', { select: false })
 total: number;
```

In my query builder I added an `addSelect()` with first parameter as `COUNT(jobs.id)` and second parameter for an alias as `category_total`.
Note: As you can see I have prepend `category_` to the alias total, this will map the total column to the actual result of category entity. Without `category_` in the alias the total column will not be visible.
My QueryBuilder:
```
return (await this.getRepository(JobCategory))
      .createQueryBuilder('category')
      .addSelect('COUNT(jobs.id)', 'category_total')
      .leftJoin('category.jobs', 'jobs')
      .groupBy('category.id')
      .orderBy('category.name', 'ASC')
      .getMany();
  }
```

Here is a debugging result:
BEFORE the workaround:
```
(34) RowDataPacket {
node_1   |   category_id: 1,
node_1   |   category_name: 'IT/Engineering',
node_1   |   category_description: null,
node_1   |   category_icon: 'dice-d20',
node_1   |   total: '1'
node_1   | }
```
AFTER the workaround:
```
(35) RowDataPacket {
node_1   |   category_id: 2,
node_1   |   category_name: 'Accounting',
node_1   |   category_description: null,
node_1   |   category_icon: 'chart-line',
node_1   |   category_total: '1'
node_1   | }
```

**Comment by wolfejw86** [comment] 2020-02-24 16:40
until this is a feature, the above post with adding a column on the entity with `select: false` seems like a great workaround. probably saved me an hour or two from having to write a raw query and serialize it myself.  it's unfortunate when you go in on something like an orm and then it takes a lot longer to "break out" of it for situations like this. thankfully this time i didn't have to because of the above! 👏

**Comment by haroldo-ok** [comment] 2020-03-12 14:47
That works, but causes a problem when inserting into the database, since the column does not actually exist.

**Comment by Troncoso** [comment] 2020-08-19 16:45
While @noorsheikh 's answer works me, it causes a problem when initializing a new database. If I run `schema:sync`, then these columns that are suppose to be derived get added to the table. I tried simply removing the `@Column` annotation, but then typeorm no longer populates the fields correctly. Does anyone know how I can accomplish this without adding these columns to the database?

**Comment by kmasterycsl** [comment] 2020-09-03 15:20
@noorsheikh solution works 👍 . For anyone faces this issue, please make sure your virtual field is a column ```@Column('int', { select: false })```

**Comment by Troncoso** [comment] 2020-09-03 15:27
@alex88 I ended up allowing the columns to be created, then I created a migration to drop them

**Comment by martinsotirov** [comment] 2020-10-18 15:27
@noorsheikh's workaround works for dynamically populating the entity field but what about using the value in a where clause or for ordering?

When I try to use the field for ordering and searching like this

```
queryBuilder.orderBy('vendor.distance', 'ASC')
queryBuilder.andWhere('vendor.distance < 50')
```

I get the error `QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'vendor.distance' in 'where clause'`

**Comment by talski** [comment] 2021-02-09 22:43
> return (await this.getRepository(JobCategory))
>       .createQueryBuilder('category')
>       .addSelect('COUNT(jobs.id)', 'category_total')
>       .leftJoin('category.jobs', 'jobs')
>       .groupBy('category.id')
>       .orderBy('category.name', 'ASC')
>       .getMany();
>   }

if you try to omit some field in category using a select just before the addSelect, will it work?

`.select(['category.id', 'category.name'])`

when I try something like this, the addSelect gets ignored when using getMany, it only shows when I call getRawMany

**Comment by konstantin-k13** [comment] 2021-02-10 12:06
@talski same problem here, i need to get only a few columns from a table, but it's an entity inside of another entity, so i can't use getRawMany

**Comment by talski** [comment] 2021-02-10 13:04
@konstantin-k13, for now, you can set select false to the columns you don't want, 

```
@Column("text", { select: false })
columnName: String
```
and wherever you need it, add it again using

```
.addSelect('entityName.columnName')
```

or you could only delete the field before sending anywhere

```
getManyResult.map(result => {
  delete result.columnName;
})
```

```
delete getOneResult.columnName;
```

**Comment by ChakirMrabet** [comment] 2021-03-28 23:37
Any news on this issue?

I'm trying to add two columns to my query that are computed as left joins:

 ```javascript
const items: any[] = await this.repo
      .createQueryBuilder('company')
      .addSelect('COUNT(location.id)', 'company_totalLocations')
      .addSelect('COUNT(user.id)', 'company_totalUsers')
      .leftJoin('location', 'location', 'location.companyId = company.id')
      .leftJoin('user', 'user', 'user.locationId = location.id')
      .where(`company.${field} LIKE '%${searchText}%'`)
      .groupBy('company.id')
      .addGroupBy(`company.name`)
      .orderBy(`company.${field}`, order)
      .getMany();

    return plainToClass(CompanyDto, items);
```
I want to map the results to a DTO:

```javascript
@Exclude()
export class CompanyDto {
  @Expose()
  id: string;

  @Expose()
  name: string;

  @Expose()
  description: string;

  @Expose()
  type: string;

  @Expose()
  industry: string;

  @Expose()
  web: string;

  @Expose()
  logo: string;

  @Expose()
  isActive: boolean;

  @Expose()
  created: string;

  @Expose()
  updated: string;

  // Statistics

  @Expose()
  totalLocations: number;

  @Expose()
  totalUsers: number;
}
```

This DTO is derived from my entity:

```javascript
@Entity()
export class Company extends BaseEntity {
  @Column()
  name: string;

  @Column({ type: 'enum', enum: CompanyType, default: CompanyType.CUSTOMER })
  type: CompanyType;

  @Column({
    type: 'enum',
    enum: CompanyIndustry,
    default: CompanyIndustry.OTHER,
  })
  industry: CompanyIndustry;

  @Column({ nullable: true })
  web?: string;

  @Column({ nullable: true })
  logo?: string;

  @OneToMany(() => Location, (location) => location.company)
  locations: Promise<Location[]>;

  // Virtual

  @Column({ select: false, insert: false, readonly: true, nullable: true })
  totalLocations: number;

  @Column({ select: false, insert: false, readonly: true, nullable: true })
  totalUsers: number;
}

```
This works well but I when I try to insert a new record I get this error for each "virtual" column:

**"Field 'totalLocations' doesn't have a default value"**
...

I know that it's not a good practice to add in the results of a DB query columns that are not part of the schema, but in this case the query can be done in one shot saving time for the user's request, compared to what it would take to query first all the entities, and then one by one, get their aggregated data. All can be done in one shot in the MySQL server.

Also, I thought of using `getRawMany`, but the problem is that it aliases all fields with the table name as prefix, which breaks my mapping to the DTO. Also, I don't want to name the properties of my DTO with the prefix `company_`. In other words, `getRawMany` doesn't respect the names of the columns, it aliases them prefixed with the name of the table.

Any ideas on how to achieve this?

Thanks.

**Comment by martinsotirov** [comment] 2021-03-30 06:50
@ChakirMrabet a [solution](https://github.com/typeorm/typeorm/pull/6855) was implemented for MySQL but never merged. @nebkat is working on [another solution](https://github.com/typeorm/typeorm/pull/7010) that will be usable on any provider.

**Comment by talski** [comment] 2021-06-21 18:31
Another workaround:

```ts

// post.entity.ts
// VIRTUAL FIELDS
@Column({ nullable: true, insert: false, update: false, select: false })
categoryDescription: string;

// post.service.ts
import { plainToClass } from 'class-transformer';
import tsObject from 'ts-obj';
import * as camelcaseKeys from 'camelcase-keys';

// you can put this anywhere
const removePrefix = function(str: string, prefix: string) {
  const hasPrefix = str.indexOf(prefix) === 0;
  return hasPrefix ? str.substr(prefix.length) : str.toString();
};

// ...

let queryBuilder = postRepository
  .createQueryBuilder('post')
  .select([
    'post.title',
    'category.description as post_category_description' //virtual, in this case, you can even omit "as" part
  ])
  .innerJoin(Category, 'category', 'category.id = post.categoryId');

const rawData = await queryBuilder.getRawMany();

return plainToClass(
  Post,
  camelcaseKeys(
    rawData.map(record =>
      tsObject.map(record, (key, value) => {
        return { key: removePrefix(key, 'post_'), value };
      })
    )
  )
);
```

**Comment by mkhstar** [comment] 2021-08-12 20:55
@noorsheikh 's reply doesn't work when select is already used. Is there any work around with that? Example below
```ts
this.getRepository(JobCategory))
      .createQueryBuilder('category')
       .select('category.name') // i don't need the other fields
      .addSelect('COUNT(jobs.id)', 'category_total')
      .leftJoin('category.jobs', 'jobs')
      .groupBy('category.id')
      .orderBy('category.id', 'ASC')
      .getMany();

```

**Comment by MarcosRiosC** [comment] 2021-09-13 01:38
> @noorsheikh 's reply doesn't work when select is already used. Is there any work around with that? Example below
> 
> ```ts
> this.getRepository(JobCategory))
>       .createQueryBuilder('category')
>        .select('category.name') // i don't need the other fields
>       .addSelect('COUNT(jobs.id)', 'category_total')
>       .leftJoin('category.jobs', 'jobs')
>       .groupBy('category.id')
>       .orderBy('category.id', 'ASC')
>       .getMany();
> ```
In that case, only getRawMany or GetRawOne because are u using select

**Comment by samimi-electronics** [comment] 2022-01-27 13:06
> @noorsheikh's workaround works for dynamically populating the entity field but what about using the value in a where clause?
> 
> For sorting `queryBuilder.orderBy('vendor_distance', 'ASC')` seems to work but when I try to filter the entries by it neither `vendor.distance` nor `vendor_distance` works.
> 
> ```
> queryBuilder.andWhere('vendor_distance < 50')
> ```
> 
> I keep getting
> 
> ```
> QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'vendor_distance' in 'where clause'`
> ```
> 
> My workaround for now is to duplicate the computation from `addSelect()` to the `andWhere()` call.
> 
> ```
>  queryBuilder.andWhere(`6371 * acos(cos(radians(:lat)) * cos(radians(location.lat))
>                      * cos(radians(location.lng) - radians(:lng)) + sin(radians(:lat))
>                      * sin(radians(location.lat))) < :distance`, filter)
> ```

Use having instead of a where clause

**Comment by scottsymm** [comment] 2022-03-31 02:08
@[toonvanstrijp](https://github.com/toonvanstrijp) i know this post is from a while ago, but thank you, thank you, thank you.

using `leftJoinAndMapOne` and `getManyAndCount` i could not *quite* get your example to work.
i am new to the typeorms, so, there maybe a better way, but using `getRawMany`, i was able to see what typeorm wanted the output to look like.

it is possible the case sensitive table and column names in postgresql caused more issues.

but this worked for me:
```
  @Column('boolean', {
    nullable: true,
    select: false,
  })
  rematchable?: boolean;
```
```
        query = query
          .addSelect(
            'CASE WHEN currentConnection.id IS NULL THEN NULL WHEN currentConnection.explorerMessagingUserId IS NOT NULL THEN FALSE ELSE TRUE END AS "currentConnection_rematchable"',
          )
          .leftJoinAndMapOne('explorers.currentConnection', 'explorers.explorerConnections', 'currentConnection')
          .leftJoinAndSelect('currentConnection.organization', 'currentOrganization')
          .addOrderBy('currentConnection.createdAt', 'DESC');
```

**Comment by ryanhex53** [comment] 2022-05-24 08:43
I ended up using @ViewEntity to resolve this problem.

**Comment by lehaiquantb** [comment] 2022-07-06 05:51
Use virtual column resolve this
https://github.com/typeorm/typeorm/issues/2498#issuecomment-904184219

**Comment by mariuszbeltowski** [comment] 2022-07-22 16:35
Not sure why this has been closed if the problem still persists. VirtualColumn looks also as hacky way. Would be great to have a typed version of `addSelectAndMap<T>`  where `T` extends the base entity.

**Comment by newerton** [comment] 2022-07-26 18:17
> ```js
> @Column({ select: false, insert: false, readonly: true, nullable: true })
> ```

Same problem, any updates?

**Comment by newerton** [comment] 2022-07-26 18:18
> @noorsheikh 's reply doesn't work when select is already used. Is there any work around with that? Example below
> 
> ```ts
> this.getRepository(JobCategory))
>       .createQueryBuilder('category')
>        .select('category.name') // i don't need the other fields
>       .addSelect('COUNT(jobs.id)', 'category_total')
>       .leftJoin('category.jobs', 'jobs')
>       .groupBy('category.id')
>       .orderBy('category.id', 'ASC')
>       .getMany();
> ```

Same problem, any updates?

**Comment by conoremclaughlin** [comment] 2022-10-31 20:15
> Not sure why this has been closed if the problem still persists. VirtualColumn looks also as hacky way. Would be great to have a typed version of `addSelectAndMap<T>` where `T` extends the base entity.

Bumping this since this proposal seems reasonable.

**Comment by drmccue** [comment] 2022-12-22 22:20
> Correct, its a hack. Official solution named `addSelectAndMap` will come into QueryBuilder in 0.3.0. Closing as duplicate of #296

Am I missing something? I searched typeorm.io for addSelectAndMap and did not see it. I am not sure if this feature will solve part of my problem (needing to populate an entity with the results of a UNION of two queries and still have relationships to one or more additional entities) but if I can't find it in the documentation, I'm guessing it didn't get implemented yet.

**Comment by Nabeel-Faheem** [comment] 2023-07-29 11:06
> Hello Guys,
> 
> If someone still looking for an answer. Here is a workaround that I did for myself. My Case: I had a Job entity and a Category entity. I wanted to list all categories with total # of jobs posted for each category something like this:
> 
> ```
> [
>     {
>         "id": 2,
>         "name": "Accounting",
>         "total": "1"
>     },
>     ...
> ]
> ```
> 
> Here is my DDL for job_categories table:
> 
> ```
> DROP TABLE IF EXISTS `job_category`;
> CREATE TABLE `job_category` (
>   `id` INT AUTO_INCREMENT PRIMARY KEY,
>   `name` VARCHAR(20) NOT NULL
> );
> ```
> 
> I do not have the total column stored in my category table. For a workaround I added a total column in my entity with `{ select: false }` as below:
> 
> ```
> @Column('int', { select: false })
>  total: number;
> ```
> 
> In my query builder I added an `addSelect()` with first parameter as `COUNT(jobs.id)` and second parameter for an alias as `category_total`. Note: As you can see I have prepend `category_` to the alias total, this will map the total column to the actual result of category entity. Without `category_` in the alias the total column will not be visible. My QueryBuilder:
> 
> ```
> return (await this.getRepository(JobCategory))
>       .createQueryBuilder('category')
>       .addSelect('COUNT(jobs.id)', 'category_total')
>       .leftJoin('category.jobs', 'jobs')
>       .groupBy('category.id')
>       .orderBy('category.name', 'ASC')
>       .getMany();
>   }
> ```
> 
> Here is a debugging result: BEFORE the workaround:
> 
> ```
> (34) RowDataPacket {
> node_1   |   category_id: 1,
> node_1   |   category_name: 'IT/Engineering',
> node_1   |   category_description: null,
> node_1   |   category_icon: 'dice-d20',
> node_1   |   total: '1'
> node_1   | }
> ```
> 
> AFTER the workaround:
> 
> ```
> (35) RowDataPacket {
> node_1   |   category_id: 2,
> node_1   |   category_name: 'Accounting',
> node_1   |   category_description: null,
> node_1   |   category_icon: 'chart-line',
> node_1   |   category_total: '1'
> node_1   | }
> ```

What if the table name itself contains underscores like "customer_products" etc.?

**Comment by Arnesfield** [comment] 2025-04-30 07:51
> [@noorsheikh](https://github.com/noorsheikh) 's reply doesn't work when select is already used. Is there any work around with that? Example below
> 
> ```javascript
> this.getRepository(JobCategory))
>       .createQueryBuilder('category')
>        .select('category.name') // i don't need the other fields
>       .addSelect('COUNT(jobs.id)', 'category_total')
>       .leftJoin('category.jobs', 'jobs')
>       .groupBy('category.id')
>       .orderBy('category.id', 'ASC')
>       .getMany();
> ```

I know this is a very old issue, but for those still on an old version of TypeORM and want a workaround for the `select()` issue specifically:

It looks like `queryBuilder.expressionMap.selects` includes a selection to the alias by default (in this case: `category`).

```javascript
console.log(queryBuilder.expressionMap.selects);
```

It would look something like this:

```javascript
[
  { selection: 'category', aliasName: undefined }, // <-- the alias is a selection for some reason
  { selection: 'category.id' },
  // ... other default selects here
]
```

Then, calling `queryBuilder.select(selection)` would overwrite the `queryBuilder.expressionMap.selects` array, removing this default alias selection.

Somehow, adding this default alias selection entry back into the array would properly map the computed columns. Something like:

```javascript
this.getRepository(JobCategory)
  .createQueryBuilder('category')
  .select([
    'category', // <-- add the default alias selection
    'category.name',
    // ...
  ])
  .addSelect('COUNT(jobs.id)', 'category_total') // `category.total` should show up now (hopefully)
  .leftJoin('category.jobs', 'jobs')
  // ...
```

Also played around with it a bit more, and it looks like it doesn't matter where this default alias selection is located to make the computed columns work as long as it's present in the `queryBuilder.expressionMap.selects` array before executing the query (well, based on my testing at least).

Hope this helps.
