### ISSUE TITLE
unidirectional ManyToOne embedding whole object instead of setting ObjectId  

### ISSUE THREAD

**Issue by xmlking** [typeorm/typeorm#2524] opened 2018-07-15 06:50 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Project** 
 ```ts
@Entity()
export class Project  {
  @ObjectIdColumn() id: ObjectID;
  @Index() @Column() name: string;
  @Column() description: string;
  @CreateDateColumn()  createdAt?: Date;
  @ManyToOne(type => User, {
    onDelete: 'NO ACTION',
    onUpdate: 'CASCADE',
    nullable: false,
  })
  createdBy: User;
```

**User**
```ts
@Entity()
export class User {
  @ObjectIdColumn() id: ObjectID;
  @Index() @Column() firstName: string;
  @Index() @Column() lastName: string;
  @Index({ unique: true }) @Column() email: string;
}
```
### Mongo CLI commands:

`db.user.find()`
```json
{
  "_id": ObjectId("5b4aecf4dc891a5a4484fa83"),
    "firstName": "sumo",
    "lastName": "demo",
    "email": "sumo@demo.com"
}
```
`db.project.find()`

```json
{
  "_id": ObjectId("5b4aed15dc891a5a4484fa84"),
  "name": "string1",
  "description": "string1",
  "createdBy": {
    "id": ObjectId("5b4aecf4dc891a5a4484fa83"),
    "firstName": "sumo",
    "lastName": "demo",
    "email": "sumo@demo.com"
  },
  "createdAt": ISODate("2018-07-15T06:43:33.738Z"),
}
```

for `db.project.find()`  **I was expecting**
```json
{
  "_id": ObjectId("5b4aed15dc891a5a4484fa84"),
  "name": "string1",
  "description": "string1",
  "createdById": {
    "_id": ObjectId("5b4aecf4dc891a5a4484fa83")
  },
  "createdAt": ISODate("2018-07-15T06:43:33.738Z"),
}
```

**Comment by imnotjames** [comment] 2021-07-04 23:23
Duplicate of #655

**Closed by imnotjames** 2021-07-04 23:23 UTC
Labels: bug, driver: mongodb
