### ISSUE TITLE
migrations:run is replacing my custom environment variables.

### ISSUE THREAD

**Issue by italoiz** [typeorm/typeorm#6213] opened 2020-06-06 08:38 UTC
When running `typeorm migration:run` my custom environment variables in `.env.test` are replaced. I have separated `.env.test` file to run my tests with different variables from production.

See how my environment files are configured.

```typescript
// >>> env.ts
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

const { NODE_ENV } = process.env;

const envPath = path.resolve(__dirname, `../../.env.${NODE_ENV}`);

dotenv.config({
  path: fs.existsSync(envPath)
    ? envPath
    : path.resolve(__dirname, '../../.env'),
});


// >>> ormconfig.ts
import '@config/env';

const { DB_TYPE, DB_USER, DB_PASS, DB_NAME, DB_HOST } = process.env;

module.exports = [
  {
    type: DB_TYPE || 'postgres',
    name: 'default',
    host: DB_HOST,
    username: DB_USER,
    password: DB_PASS,
    database: DB_NAME,
    entities: ['src/modules/**/infra/typeorm/entities/*.ts'],
    migrations: ['src/shared/infra/typeorm/migrations/*.ts'],
    cli: {
      migrationsDir: 'src/shared/infra/typeorm/migrations',
    },
    migrationsTableName: '_migrations',
  },
];
```

Some people have the same problem in issue #3894 .

I believe that what is causing problems is the excerpt below. We should and could have a way to avoid this behavior.

https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/connection/ConnectionOptionsReader.ts#L98-L101

**Comment by rubiin** [comment] 2020-06-06 14:30
can you share the code in a repo so i can try to reproduce the issue

**Comment by rubiin** [comment] 2020-06-06 14:37
https://github.com/MidoAhmed/nestjs-api-boilerplate here is a sample of working code

**Comment by italoiz** [comment] 2020-06-06 16:26
@rubiin [Here](https://github.com/italoiz/ts-express-boilerplate), this is a repository with a problem.

**Comment by viniciusaugutis** [comment] 2020-06-09 20:42
I have the same problem here, The .env is replacing my .env.test when I execute the command of typeorm migration:show or typeorm migration:run

**Comment by imnotjames** [comment] 2021-07-03 05:26
Duplicate of #5884

We load up the .env explicitly as part of the connection loader.

**Closed** 2021-07-03 05:27 UTC
Labels: comp: migrations
