### ISSUE TITLE
type "enum" does not exist

### ISSUE THREAD

**Issue by mkzaker** [typeorm/typeorm#1045] opened 2017-10-18 12:11 UTC
Hi,
my database is postgres and i have this error 
QueryFailedError: type "enum" does not exist

**Comment by pleerock** [comment] 2017-10-18 12:17
enums are only supported in [mysql](https://github.com/typeorm/typeorm/blob/e7c516e7f4f162e1411d65a8aa30c43ef8b9220e/test/functional/database-schema/column-types/mysql/entity/Post.ts#L83). We are planning to add postgres enum support in 0.2.0 . Duplicate of #671

**Comment by pleerock** [comment] 2017-10-18 12:33
I expect it in December

**Comment by RDeluxe** [comment] 2017-12-04 15:08
Hello, any news about this ? i'm currently starting a new project with TypeORM and I would like to avoid hacking around if the new version is not far away

**Comment by pleerock** [comment] 2017-12-04 15:34
Work is in progress, we are expecting to land 0.2.0 in the beginning of January

**Comment by RDeluxe** [comment] 2018-02-02 11:15
Hi,

Any news about this ? :)

**Comment by pleerock** [comment] 2018-02-05 09:16
Hey Ive been very busy last two months, so 0.2.0 milestone is moved to March.

**Comment by AlexMesser** [comment] 2018-02-28 16:02
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Closed by AlexMesser** 2018-02-28 16:02 UTC
Labels: comp: schema sync
