### ISSUE TITLE
Cant install typeorm. 

### ISSUE THREAD

**Issue by NaturesProphet** [typeorm/typeorm#3712] opened 2019-02-25 17:14 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I create a new empty project by using 
```bash
npm init -y
```
and then, i send a 
```bash
npm install typeorm
```
and i got this:

```bash
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN tt@1.0.0 No description
npm WARN tt@1.0.0 No repository field.

npm ERR! path /home/mgarcia/teste/tt/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/mgarcia/teste/tt/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
```bash
node 8.12.0
npm 6.4.1
```
got the same problem on node 10 latest

PLEASE HEEEEELP!

**Comment by vlapo** [comment] 2019-02-25 17:16
Duplicate of https://github.com/typeorm/typeorm/issues/3705.

**Closed by vlapo** 2019-02-25 17:16 UTC
