### ISSUE TITLE
findOne with relations generates suboptimal SQL

### ISSUE THREAD

**Issue by christhegrand** [typeorm/typeorm#8147] opened 2021-08-30 23:01 UTC
## Issue Description

If you have an entity and you call findOne on the entity and pass it some relations, the SQL query that results is rather strange looking and uses both an exact comparison and an in to find the matching row. Here are some sample entities:

```
import {Entity, PrimaryGeneratedColumn, BaseEntity, Column, ManyToMany, JoinTable} from 'typeorm'
import {Permission} from '.'

@Entity({name: 'roles'})
export class Role extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number

  @Column()
  name!: string

  @Column()
  description!: string

  @ManyToMany(() => Permission)
  @JoinTable({name: 'role_permission_mapper'})
  permissions!: Permission[]
}

@Entity({name: 'roles'})
export class Role extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number

  @Column()
  name!: string

  @Column()
  description!: string

  @ManyToMany(() => Permission)
  @JoinTable({name: 'role_permission_mapper'})
  permissions!: Permission[]
}
```

### Expected Behavior

If I call `await Role.findOne({id: 1}, {relations: ['permissions']})`, I expect the ORM to generate fairly efficient SQL here, along the lines of:
 
```
select * from roles 
inner join role_permission_mapper on role_permissions_mapper.roles_id = roles.id
inner join permissions on permissions.id = role_permissions_mapper.permissions_id
where roles.id = 1;
```

### Actual Behavior

If I call `await Role.findOne({id: 1}, {relations: ['permissions']})` in my code, here is the SQL that runs:

```
SELECT DISTINCT "distinctAlias"."Role_id" as "ids_Role_id" FROM 
(SELECT "Role"."id" AS "Role_id", "Role"."name" AS "Role_name", "Role"."description" AS "Role_description", 
"Role__permissions"."id" AS "Role__permissions_id", "Role__permissions"."name" AS "Role__permissions_name", 
"Role__permissions"."description" AS "Role__permissions_description" FROM "roles" "Role" 
LEFT JOIN "role_permission_mapper" "Role_Role__permissions" ON "Role_Role__permissions"."roles_id"="Role"."id" 
LEFT JOIN "permissions" "Role__permissions" ON "Role__permissions"."id"="Role_Role__permissions"."permissions_id"
WHERE "Role"."id" = $1) "distinctAlias" 
ORDER BY "Role_id" ASC 
LIMIT 1 
-- PARAMETERS: [1]

SELECT "Role"."id" AS "Role_id", "Role"."name" AS "Role_name", "Role"."description" AS "Role_description", 
"Role__permissions"."id" AS "Role__permissions_id", "Role__permissions"."name" AS "Role__permissions_name", 
"Role__permissions"."description" AS "Role__permissions_description" FROM "roles" "Role" 
LEFT JOIN "role_permission_mapper" "Role_Role__permissions" ON "Role_Role__permissions"."roles_id"="Role"."id"
LEFT JOIN "permissions" "Role__permissions" ON "Role__permissions"."id"="Role_Role__permissions"."permissions_id" 
WHERE ( "Role"."id" = $1 ) 
AND ( "Role"."id" IN (1) ) 
-- PARAMETERS: [1]
```

Why is the second query doing both an exact comparison (`"Role"."id" = $1`) for the role ID value while also searching for it with an in (`"Role"."id" IN (1)`)? I tried logging the SQL results for different entities in our database with different relation types but saw this behavior every time. 

If instead of using findOne, I do this in my code: 

```
await Role.createQueryBuilder('role')
      .innerJoinAndSelect('role.permissions', 'permissions')
      .where('role.id = :id', {id: 1})
      .getOne()
```

then this SQL is run, which is much closer to what I would expect:

```
SELECT "role"."id" AS "role_id", "role"."name" AS "role_name", "role"."description" AS "role_description", 
"permissions"."id" AS "permissions_id", "permissions"."name" AS "permissions_name", 
"permissions"."description" AS "permissions_description" FROM "roles" "role" 
INNER JOIN "role_permission_mapper" "role_permissions" ON "role_permissions"."roles_id"="role"."id" 
INNER JOIN "permissions" "permissions" ON "permissions"."id"="role_permissions"."permissions_id" 
WHERE "role"."id" = $1 
-- PARAMETERS: [1]
```

Why is the SQL generated by these two queries so different?

### Steps to Reproduce

1. In my testing, this is reproducible with any entity that calls findOne with a relations argument. I provided some sample entities above that you can use to test this.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MaxOS 11.15.1        |
| Node.js version     | 14.17.5  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

✖️ - ✅ Yes, I have the time, and I know how to start.
✅ - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
✖️- ✖️ No, I don’t have the time, but I can support (using donations) development.
✖️ - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by johnplobo** [comment] 2021-12-18 17:10
@christhegrand  are you able to solve this issue? Even I faced the same issue.

**Comment by codetestmg** [comment] 2021-12-18 17:11
@christhegrand  are you able to solve this issue? Even I faced the same issue.

**Comment by christhegrand** [comment] 2021-12-20 18:22
I ended up rewriting some of our queries to follow this pattern:

```
await Role.createQueryBuilder('role')
      .innerJoinAndSelect('role.permissions', 'permissions')
      .where('role.id = :id', {id: 1})
      .getOne()
```

**Comment by codetestmg** [comment] 2021-12-23 14:04
@christhegrand  yes even I did same.I think there is no option using relationship

**Comment by cduff** [comment] 2022-03-24 11:18
Duplicate of https://github.com/typeorm/typeorm/issues/5694?

**Comment by christhegrand** [comment] 2022-03-24 16:18
Ah, yes, looks like it. I didn't see that issue when I opened this.

**Closed** 2022-03-24 16:21 UTC
Labels: bug, requires triage
