### ISSUE TITLE
MongoDB ConnectionManager doesn't select given database, creates new database "test" instead

### ISSUE THREAD

**Issue by C0dekid** [typeorm/typeorm#6900] opened 2020-10-13 16:31 UTC
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `^0.2.28` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This happens when I create a new connection, fill in the options including `database` as key.

```ts
const database = "tsbot";
const connectionManager: ConnectionManager = new ConnectionManager();
connectionManager.create({
    type: "mongodb",
    database: database, // returns "tsbots", gets ignored when you insert a document
    name: database,
    url: "mongo://user:pass@ip:port",
    useUnifiedTopology: true,
    useNewUrlParser: true,
    entities: [
        Warns
    ]
});

export default connectionManager;
```

The key `database` gets ignored when I insert a document. A new database `test` is created automatically instead. I tried using the URL `mongodb://user:pass@ip:port/database`, but that is returning `Authentication Failed` error, leaving that away in the URL establishes a fine connection.

**Comment by imnotjames** [comment] 2020-10-13 17:57
You're definitely using `0.2.28`?  This should have been resolved with that release.

**Comment by C0dekid** [comment] 2020-10-13 18:33
> You're definitely using `0.2.28`? This should have been resolved with that release.

I'm positive. I'm using version `0.2.28`

**Comment by imnotjames** [comment] 2020-10-14 02:08
Related https://github.com/typeorm/typeorm/issues/6157

**Comment by imnotjames** [comment] 2020-10-14 02:57
I can't replicate - I tried to create a test and was unable to - using a few different techniques:

```
import { expect } from "chai";
import {
    closeTestingConnections,
    setupTestingConnections
} from "../../utils/test-utils";
import {MongoDriver} from "../../../src/driver/mongodb/MongoDriver";
import {Connection, ConnectionOptions, createConnection, MongoClient} from "../../../src";

describe("github issues > #6900 MongoDB ConnectionManager doesn't select given database, creates new database \"test\" instead", () => {
    let connections: Connection[] = [];
    afterEach(() => closeTestingConnections(connections));

    it("should connect to the expected database", async () => {
        const options = setupTestingConnections({ enabledDrivers: ["mongodb"] });

        if (options.length === 0) {
            // Skip if we can't grab the mongodb
            return;
        }

        const connection = await createConnection({
            ...options[0],
            database: 'foo'
        } as ConnectionOptions);
        connections.push(connection);

        const mongoDriver = connection.driver as MongoDriver;
        const client = mongoDriver.queryRunner!.databaseConnection as MongoClient

        expect(mongoDriver.database).to.be.equal('foo');
        expect(client.db().databaseName).to.be.equal('foo');
    });
});
```

How are you inserting documents?

Can you create a reproducible example that I can run locally to determine the cause?

**Comment by C0dekid** [comment] 2020-10-15 19:49
Hello James, sorry for the late answer. But this is how I insert a new document into my database:

```js
const warnRepo: Repository<Warns> = this.client.mongodb.getRepository(Warns);

await warnRepo.insert({
    id: Math.floor(Math.random() * 1000000),
    guild: message.guild!.id,
    user: member.id,
    moderator: message.author.id,
    reason: reason,
    createdAt: new Date()
});
```

And this is the `Warns` repository class:

```js
import { Entity, ObjectID, ObjectIdColumn, Column } from 'typeorm';

@Entity("warnings")
export class Warns {
    @ObjectIdColumn()
    id!: ObjectID

    @Column()
    guild!: string;

    @Column()
    user!: string;

    @Column()
    moderator!: string;

    @Column()
    reason!: string;

    @Column()
    createdAt!: Date;
}
```

**Comment by imnotjames** [comment] 2020-10-16 04:24
On version 0.2.28 I created [a test to replicate this issue](https://github.com/typeorm/typeorm/compare/master...imnotjames:test/6900) - however, I _cannot_ replicate this issue.  I've tried also replicating it outside of the testing harness and was unable to.

Not being able to replicate it in a clean environment means either:

* Something is different with your environment
* My replication code wasn't copied down correctly
* The issue is sporadic

The MOST COMMON case is that something's not as expected with your environment.

Something's not working as expected with your environment & you'll need more generalized support to confirm what's going on.

For questions and general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by C0dekid** [comment] 2020-10-16 17:49
Well thanks then.. i'll just manually change everything.

**Comment by imnotjames** [comment] 2020-10-16 17:54
If you have a repository which I can clone and replicate the issue I'm happy to reopen it.  Just without replication it is very hard to tell if there's a bug here.

**Comment by C0dekid** [comment] 2020-10-16 20:34
> If you have a repository which I can clone and replicate the issue I'm happy to reopen it. Just without replication it is very hard to tell if there's a bug here.

Thank you, I have uploaded all files associated with the project and invited you to this repository.

**Comment by imnotjames** [comment] 2020-10-16 22:16
Ok - I think I've found the issue.  Testing & will get a PR open shortly.

**Comment by imnotjames** [comment] 2020-10-16 22:34
Temporary solution: Include the database name in the `url` you're passing:

```
const database = "tsbot";
const connectionManager: ConnectionManager = new ConnectionManager();
connectionManager.create({
    type: "mongodb",
    database: database, // returns "tsbots", gets ignored when you insert a document
    name: database,
    url: "mongo://user:pass@ip:port/" + database,
    useUnifiedTopology: true,
    useNewUrlParser: true,
    entities: [
        Warns
    ]
});

export default connectionManager;
```

**Comment by C0dekid** [comment] 2020-10-17 14:31
Thank you for providing a temporary solution! :)

**Closed** 2020-10-17 16:18 UTC
Labels: bug, driver: mongodb
