### ISSUE TITLE
[PROBLEM] constraint "PRIMARY KEY" of relation "TABLE" does not exist 

### ISSUE THREAD

**Issue by MrJim-06** [typeorm/typeorm#3570] opened 2019-02-04 02:29 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Question**
I want to use repository to find my sample data in postgres but i'm stuck !!

**Example Files** 
User.ts
```typescript 
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  userid: number;

  @Column()
  usermail: string;
}
```

**My Problem**
{ QueryFailedError: constraint "PK_04d500b286ce3e4c4cbc20d97ea" of relation "user" does not exist
    at new QueryFailedError (C:\Users\develop\Desktop\TypeORM\src\error\QueryFailedError.ts:7:9)
    at Query.callback (C:\Users\develop\Desktop\TypeORM\src\driver\postgres\PostgresQueryRunner.ts:175:30)
    at Query.handleError (C:\Users\develop\Desktop\TypeORM\node_modules\pg\lib\query.js:142:17)
    at Connection.connectedErrorMessageHandler (C:\Users\develop\Desktop\TypeORM\node_modules\pg\lib\client.js:160:17)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (C:\Users\develop\Desktop\TypeORM\node_modules\pg\lib\connection.js:125:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
  message:
   'constraint "PK_04d500b286ce3e4c4cbc20d97ea" of relation "app" does not exist',

**I think this is PROBLEM**
ALTER TABLE "user" DROP CONSTRAINT "PK_04d500b286ce3e4c4cbc20d97ea"

**Comment by vlapo** [comment] 2019-02-07 21:01
Hi @MrJim-06. I do not understand. When is this error throwing?

**Comment by MrJim-06** [comment] 2019-02-08 02:58
> Hi @MrJim-06. I do not understand. When is this error throwing?
When I'm used Repository.find to find data in postgres. this error throwing.

**Comment by vlapo** [comment] 2019-02-10 12:07
Sure but you wrote about `ALTER TABLE "user" DROP CONSTRAINT "PK_04d500b286ce3e4c4cbc20d97ea"` and I really dont know where this comming from because find method do not generate such SQL.

Could you please create small reproduction of this problem? Maybe small repository with code or snipped of code with entity definitions?

**Comment by ZoroSC** [comment] 2019-04-04 08:55
I'm also having an issue with this same thing, and it seems to be throwing cause I'm using the synchronize option as seen here. 
```ts 
connectionManager.create({
	name: 'postgres',
	type: 'postgres',
	port: 5432,
	username: 'postgres',
	password: 'password',
        database: 'postgres',
	entities: [GuildSettings],
	synchronize: true
});
```

With my one entity looking like this:
 ```ts 
import {
	Entity,
	Column,
	PrimaryColumn
} from 'typeorm';

@Entity('settings')
export class GuildSettings {

	@PrimaryColumn()
	guild: string;

	@Column({ type: 'jsonb', default: "'{}'"})
	settings: any;
}
```

Versions:
TypeORM: 0.2.16
pg: 7.9.0

**Comment by Kononnable** [comment] 2019-05-01 15:35
@ZoroSC 
I couldn't reproduce your issue. You're sure that you've got exactly the same error?
Running your model threw me an error `error: syntax error at or near "{"` but after removing apostrophes from default value it works fine.

**Comment by charlie-wasp** [comment] 2019-05-07 12:33
Same here as @ZoroSC stated. Disabling `synchronize` option resolved the issue

Versions:
TypeORM: 0.2.17
pg: 9.5.16

**Comment by 1valdis** [comment] 2019-07-19 14:31
Seems like this is not yet fixed, ran into this just now.

**Comment by haohello** [comment] 2019-07-31 13:51
@1valdis how are your entities defined?

**Comment by 1valdis** [comment] 2019-08-01 07:00
@haohello I've changed my entities since then and they're working fine. Unfortunately I'm not able to get to that point in my codebase because I haven't committed or saved it elsewhere.

**Comment by Kononnable** [comment] 2019-08-31 19:23
Closing as no reproduction code was posted - code posted by @ZoroSC was working correctly after fixing syntax error.

**Closed by Kononnable** 2019-08-31 19:23 UTC
Labels: needs more info, question

**Comment by jeffmoss** [comment] 2019-10-27 00:09
@Kononnable  `DROP CONSTRAINT IF EXISTS` instead of just `DROP CONSTRAINT` is one possible solution to this, only for pg 9.0+.

**Comment by Bradleykingz** [comment] 2019-10-27 06:44
If you're like me and added the constraint after the table was first created, you might have to drop it manually.

**Comment by sandeshgb** [comment] 2020-09-29 11:06
I'm getting same error while starting my project using command "yarn start:debug" (using nestjs).
I'm having a many-to-many relation between products and categories.
My product entity is as follows:
`  @ManyToMany(type => Category)
  @JoinTable({
    name: 'products_categories',
    joinColumn: { name: 'productId' },
    inverseJoinColumn: { name: 'categoryId' },
  })
  category: Category[];`

Disabling synchronize isn't an appropriate solution.
I don't understand why is it trying to drop constraint and even if it does then it should use "if exists"

@pleerock @MrJim-06 @Kononnable

**Comment by sandeshgb** [comment] 2020-09-29 11:45
> Sure but you wrote about `ALTER TABLE "user" DROP CONSTRAINT "PK_04d500b286ce3e4c4cbc20d97ea"` and I really dont know where this comming from because find method do not generate such SQL.
> 
> Could you please create small reproduction of this problem? Maybe small repository with code or snipped of code with entity definitions?

Its coming from migrations @vlapo . We need to improvise the queries generated via migrations. Just need to add extra bit of checking drop table / constraints **if exists**

**Comment by dkamorin** [comment] 2021-01-19 18:12
I think I've met similar or same issue.
In my project I have NestJS + Typeorm + Postgres and bunch of migrations. One of these migrations creates a table with a custom PK constraint name.

So, if I run migrations and then `nest start --watch` the app I get an error:
```
[Nest] 40830   - 01/19/2021, 11:51:50 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +106ms
QueryFailedError: constraint "PK_5f3350bd9b6c92a62a2257730b7" of relation "my_table" does not exist
    at new QueryFailedError (myproject/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (myproject/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (myproject/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (myproject/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:483:12)
    at Socket.<anonymous> (myproject/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
```

and this constraint definitely does not exist, because this constraint has custom name `my_table_pk` in migration files. For some unknown reasons typeorm (?) tries to use another name for the constraint.

If I just `nest start` my application with fresh empty DB, it starts without errors and I see DB with tables and so on, although I didn't run migrations. Moreover, the custom constraint in that case has name _PK_5f3350bd9b6c92a62a2257730b7_ which is exactly as it was in the error. But that case is not appropriate for me, because migration with custom name is already in prod, so I can't reverse it, and because there are some other differences with requirements (e.g. wrong column type for other column)

Any ideas how it can be fixed?

**Comment by S-a-k-s-h-i** [comment] 2021-10-11 12:44
I am also getting this error , while running the migrations,. Basically what this error mean and how can i resolve this?
QueryFailedError: constraint "PK_93e05a4c85dad3c995adf2b2c09" of relation "category" does not exist

**Comment by valllentinnaa** [comment] 2021-11-05 18:30
👋 Hi, I have the same problem. I updated my model, generated new migration via cli and once I run the migration it gives me:
`Error during migration run:
QueryFailedError: constraint "PK_5faed84e32fb60fd3d65001c06d" of relation "user_permission_role" does not exist
query: 'ALTER TABLE "user_permission_role" DROP CONSTRAINT "PK_5faed84e32fb60fd3d65001c06d"'`

For me adding manually to the migration `IF EXISTS` after `DROP CONSTRAINT` fixed it, but shouldn't it be generated with the check? 🤔

**Comment by mmaia** [comment] 2022-02-05 20:07
I can confirm this issue but it happens, at least in my case, only if the constraint for a table is created by other means, in my case I use flyway to manage migrations in PRD and then forget to set synchronize to false. i.e - typeorm migrations also tries to run.

**Comment by dberardo-com** [comment] 2023-10-02 15:48
still happening ... any solution ?
