### ISSUE TITLE
'Data type "" is not supported in "sqlite" database.

### ISSUE THREAD

**Issue by mypmj** [typeorm/typeorm#774] opened 2017-08-18 13:40 UTC
Please check this issue and give me a solution to this problem.
This is very urgent. the error is shown during application start

 name: 'DataTypeNotSupportedError',
  message: 'Data type "" is not supported in "sqlite" database.' 

 type: "sqlite",
    database: "db/test.db",
    entities: [
      "build/entities/*"  
      ],
autoSchemaSync: true,
    dropSchemaOnConnection: true
Entity structure is 

export class VG 
{
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    last: string;

    @Column()
    lastTime: Date;

    @Column("simple-array")
    myval: string[]; 
} 
  "sqlite3": "^3.1.9",
    "typeorm": "0.1.0-alpha.33"

**Comment by pleerock** [comment] 2017-08-19 05:27
I don't see reason why I should not work. Everything looks okay and we have tests covered what you provided in your entity. I can only assume you did not import "reflect-metadata" in beginning of your app or you don't enable corresponding settings in your tsconfig.json

**Comment by mypmj** [comment] 2017-08-21 11:57
No that is not the problem . import "reflect-metadata" is already there.
I think that there is some problem with latest  0.1.0-alpha.33 and 0.1.0-alpha.34.
Did you notice the error message?
`message: 'Data type "" is not supported in "sqlite" database`
error message from code

```
import {DatabaseType} from "../driver/types/DatabaseType";

export class DataTypeNotSupportedError extends Error {
 name = "DataTypeNotSupportedError";
this.message = `Data type "${type}" is not supported in "${database}" database.`;
}
 }

```
During the parsing, an empty string is passed to the - type- variable.
This issue has been resolved by providing the type information to the @Column().
I think that in earlier version, it was working fine. 
Latest one ( 0.1.0-alpha.33) shows me some problem.
Working code is shown below.

@Column({ type: "text" })
last: string;

@Column("date")
lastTime: Date;

@Column("simple-array")
myval: string[];

**Comment by pleerock** [comment] 2017-08-21 21:01
Im sure there are tests covered such scenarios. Can you confirm which column exactly brings problem? Also probably I'll need a git repo with reproduction of the problem since what you are saying is strange and if such issue really exist it probably reproduce on certain circumstances.

**Comment by shroudedcode** [comment] 2017-08-30 17:10
@pleerock I'm having the exact same problem with a small forum project I just created to learn TypeORM. I've created [a gist with the entities](https://gist.github.com/shroudedcode/3b03d0bc28d3d112685927d8f3ea16c5) I've created so far. Maybe they help find the source of the bug. If there's anything else wrong with my entities, please tell me. This is my first TypeORM project.

**Comment by pleerock** [comment] 2017-09-06 14:02
Closing as no answer from reporter

**Closed by pleerock** 2017-09-06 14:02 UTC

**Comment by baltoaca** [comment] 2017-12-13 16:59
In case anyone has a message like this even if 'reflect-metadata' is imported, make sure the 'reflect-metadata' is imported before anything else.

**Comment by daslicht** [comment] 2018-01-28 12:28
btw ```import "reflect-metadata";``` is missing in the express tutorial in teh docs as well as ``` "@types/node"```

**Comment by pleerock** [comment] 2018-01-31 06:42
@daslicht PRs with fixes in documentation are very welcomed!

**Comment by jelling** [comment] 2018-02-14 17:22
This issue will also happen if you haven't setup your tsconfig.json properly like so:

```
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
...
```

**Comment by henrique945** [comment] 2020-06-09 19:42
I resolve the problem by adding _type: 'simple-json'_ when declaring the variable in the **entity**
  
```
@Column({ nullable: false, type: 'simple-json'  })
public yourVariable: string[];
```
