### ISSUE TITLE
TypeOrm doesn't give error when quering by a non existing field

### ISSUE THREAD

**Issue by edwinboon** [typeorm/typeorm#5372] opened 2020-01-17 18:24 UTC
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1) Create a database connection.
2) Try to use the findOne option where you query on a field that doesn't exist in the database. In our case I queried for domainName instead of name.

TypeOrm will now return the first record from the database even tho is a completely different record than it should be.

**Comment by ivan-banha** [comment] 2020-05-12 09:30
Hi everyone. I have the same behavior but with Postgres. 

If I'm trying to find a record in a table by id and the record with given id is not exists, instead of error or undefined/null object I received first record from the table.

**Database system/driver:**

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[X] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

**TypeORM version:**

[ ] latest
[ ] @next
[ X] 0.2.24

**Comment by imnotjames** [comment] 2020-10-12 09:27
Duplicate of #3416

**Closed by imnotjames** 2020-10-12 09:27 UTC
Labels: bug, driver: mariadb, driver: mysql
