### ISSUE TITLE
Querying a repository when a null value is passed into the WHERE clause, ignores WHERE

### ISSUE THREAD

**Issue by SrWildman** [typeorm/typeorm#9235] opened 2022-07-22 15:32 UTC
## Issue Description

Querying a repository when a null value is passed into the where clause, returns a random value. The where clause is seemingly omitted from the query. 

### Expected Behavior

I would expect a runtime error to be thrown since we have an invalid value being passed into our query. 

### Actual Behavior

Random value from the DB is returned. 

### Steps to Reproduce

Reproducible with https://github.com/typeorm/typescript-example

Add this snippet to `index.ts` and run

```typescript
    const postRepo = AppDataSource.getRepository(Post);
    let title: string;
      const res = await  postRepo.findOneOrFail({
          where: {title}
          }
      )
    console.log(res)
```

The log shows the executed query as the following, notice the where clause is omitted.

```sql
SELECT "Post"."id" AS "Post_id", "Post"."title" AS "Post_title", "Post"."text" AS "Post_text" FROM "post" "Post" LIMIT 1
```

The post returned. I would expect an error here.
```json
Post { id: 1, title: 'TypeScript', text: 'TypeScript is Awesome!' }
```
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 12.4        |
| Node.js version     | 16.15.1  | 
| Typescript version  | 4.6.4  | 
| TypeORM version     | 0.3.6  | 
| NestJS core version | 8.4.5 |  
| NestJS typeorm version | 8.0.4 |

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment] 2022-07-22 23:57
In your example `title` is `undefined`, not `null`. So this is by design. For more details please refer to [this answer](https://github.com/typeorm/typeorm/issues/9027#issuecomment-1135373351).

Duplicate of #9027.

**Closed by AlexMesser** 2022-07-22 23:57 UTC
Labels: bug, requires triage

**Comment by SrWildman** [comment] 2022-07-23 12:11
> In your example `title` is `undefined`, not `null`. So this is by design. For more details please refer to [this answer](https://github.com/typeorm/typeorm/issues/9027#issuecomment-1135373351).
> 
> 
> 
> Duplicate of #9027.

Apologies for mistyping, correct it is undefined and not actually null. I will go look at the other issue. I appreciate the reply.
