### ISSUE TITLE
querying arbitrary fields of relations not working

### ISSUE THREAD

**Issue by steve2507** [typeorm/typeorm#3539] opened 2019-01-29 12:59 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The documentation for the find(One) commands clearly shows that it should be possible to query related entities;

> Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined. Example:
> 
> ```javascript
> userRepository.find({ where: { name: { first: "Timber", last: "Saw" } } });
> ```

However, on a mssql database I have not been able to do so. No results whatsoever are loaded, _unless_ I query the primary key of the relation. Issue https://github.com/typeorm/typeorm/issues/2872 Seems to be related to the same thing, but no satisfying response is given therein.

Here's an example query which does not return any results;
```javascript
someRepo.find({
  relations: ['createUser'], //with our without this line, the result is the same
  where: {
    createUser: {
      logon: 'something'
    }
  }
});
```

In the above example, `createUser` is setup as a relation in the someRepo orm as such;
```javascript
createUser: {
  eager: true,
  target: 'User',
  type: 'many-to-one',
  joinColumn: {
    name: 'createUserId'
  }
},
```
while target 'User' is setup something like this;
```javascript
new EntitySchema({
  name: 'User',
  target: User,
  tableName: 'users',
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true
    },
    logon: {
      type: 'varchar',
      varchar: {
        length: 100
      }
    }
  }
})
```

Looking at the query this runs against my MSSQL instance, it ends with;
```sql
 WHERE "Project"."createUserId" = @0
```

I do not understand why `createUserId` is assigned a parameter. `createUserId` should be matched against `users.id`, and `createUser.logon` should be assigned a parameter with value 'something'.

What's going on here?

**Comment by nilswxa** [comment] 2019-02-05 14:01
Seconded. I'm seeing more strange behavior with 'relations' at the moment.

Not sure when this started happening.

**Comment by ricardovf** [comment] 2019-02-13 17:33
I also have this problem.
`````
find { take: 25,
  skip: 0,
  order: { id: 'DESC' },
  where:
   { 'userPaymentMethod.user': 'a339ffb5-4f88-4657-98c5-1f7782a1caa1' },
  relations: [ 'place', 'userPaymentMethod', 'userPaymentMethod.user' ] }
````

always return results independent if id on the where condition is valid or not

**Comment by steve2507** [comment] 2019-02-21 14:40
I hooked up the debugger to see what's happening. There I found that there seems to be no codepath to allow for what I'm trying to do here. I'm guessing that the example in the docs only refers to nested documents such as in MongoDB. That should be clarified in the documentation in my opinion.

As a result, I had to change what seemed so simple;
```javascript
    // not supported by typeorm if 'phase' is a relation
    GFG.Project.find({
      where: {
        phase: {
          published: true
        }
      }
    });
```

to a query builder;
```javascript
    GFG.Project.createQueryBuilder('project')
    .leftJoinAndSelect('project.createUser', 'createUser')
    .leftJoinAndSelect('project.roles', 'roles')
    .leftJoinAndSelect('roles.role', 'roles.role')
    .leftJoinAndSelect('roles.users', 'roles.users')
    .leftJoinAndSelect('project.skills', 'skills')
    .leftJoinAndSelect('project.phase', 'phase')
    .where('phase.published = 1');
```

That's a lot more cumbersome to read and write. But in addition, if relations in the schema change, I have to change this block of code as well which is exactly what I'm trying to avoid by using an ORM.

**Comment by SP-SAP** [comment] 2019-04-07 13:45
Having the same requirement and actually expected especially this behaviour when reading the docs and eagerly loading the sub-entities.  +1 vote from me for a feature request!

**Comment by imnotjames** [comment] 2020-10-17 08:52
Duplicate of #2707

**Closed by imnotjames** 2020-10-17 08:52 UTC
Labels: bug, comp: find options, driver: mssql
