### ISSUE TITLE
Feature: CLI option to disable dotenv

### ISSUE THREAD

**Issue by drthoben** [typeorm/typeorm#6304] opened 2020-06-24 19:18 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

Add a CLI option to disable automatic dotenv loading.

**Why?**

In projects using different dotenv packages than `dotenv` automatic loading of `.env` results in unexpected behavior.

**Comment by savolkov** [comment] 2020-06-27 07:24
Faced a similar problem. TypeORM seems to load `.env`-file with higher priority than actual environment variables from `process.env` which led to unexpected behaviour.

**Comment by dbousamra** [comment] 2020-06-28 04:35
Yeah this is causing us issues. Took me forever to track it down to typeorm loading .env.

**Comment by savolkov** [comment] 2020-06-28 07:51
Found out that in `./src/connection/ConnectionOptionsReader.ts` there's even a TODO-line:
`78:     * todo: get in count NODE_ENV somehow`

**Comment by imnotjames** [comment] 2020-10-07 03:00
Closing as a duplicate of #5386

**Closed by imnotjames** 2020-10-07 03:00 UTC
Labels: new feature
