### ISSUE TITLE
how to reconnect after disconnect

### ISSUE THREAD

**Issue by arrebole** [typeorm/typeorm#6116] opened 2020-05-22 10:49 UTC
**Issue type:**
[ x ] question

**Database system/driver:**
[ x ] `mysql`

**TypeORM version:**
[ x ] `0.2.24`

** how to reconnect after disconnect **
Unexpected disconnection

**Comment by FlorianPfisterer** [comment] 2020-05-25 13:18
Adding some info: When the database server goes down, I receive "POOL_NOEXIST" errors each time a `getConnection()` call is done. When it comes back up again, this behavior does not change. The server needs to be manually restarted.
How can one trigger the reconnection try after such errors?

**Comment by jacob87o2** [comment] 2020-09-30 21:41
The same problem occurs with mongodb.

**Comment by imnotjames** [comment] 2020-10-09 20:47
This issue was first but because the other has more information

Closing as Duplicate of #6350

**Closed by imnotjames** 2020-10-09 20:47 UTC
Labels: question
