### ISSUE TITLE
columns are not quote in update mode 

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#921] opened 2017-09-21 10:06 UTC
my database server : Postgres
When excude an update query build
```typescript
 await resp.createQueryBuilder('s')
        .update({
            memo: 'xxxx'
        })
        .where('someField = :v', { v: 'values' })  // dont work need quote  someField
//   .where('s.someField = :v', { v: 'values' })
        .execute();
```
the fields are not been quote by '"'
mybe the framework does not kown if the field is need to quote or not, but I saw the issue #817
why not drop the alias prefix in the typeorm framework instead of remove it by programer.

**Comment by rlopez4** [comment] 2017-10-08 08:41
This might be because postgres does not allow mixed case columns unless you add quotes.

**Comment by xujif** [comment] 2017-10-08 11:10
@rlopez4  "alias" has been ignored  on update query build.
I suggest to  quote the filed on update where condition when it is dot with alias.
```typescript
 await resp.createQueryBuilder('s')
        .update({
            memo: 'xxxx'
        })
         .where('s.someField = :v', { v: 'values' })
        .execute();
```
compile to 
update "table" set "memo" = 'xxxx' where "someField" = 'values'

**Comment by pleerock** [comment] 2017-10-16 13:15
I've tested  your use case and I cannot reproduce it. There are tests confirms that escaping is working when you use it without alias. What typeorm version are you using? If latest, then can you create a test with reproduction of this problem?

**Comment by pleerock** [comment] 2017-11-22 10:27
Closing because of no answer from reportee.

**Closed by pleerock** 2017-11-22 10:27 UTC
Labels: comp: query builder
