### ISSUE TITLE
entityManager.delete() proving to be a big footgun

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#4608] opened 2019-08-19 19:40 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

If you do this, what happens?

```ts
entityManager.delete(User, { where: { name: "Omar" } });
```

Answer: It deletes every `User` in your database, because `delete` doesn't take `FindOptions`, and therefore the `where` key appears to be completely ignored.

This is easily avoidable by using it as the documentation says, and instead doing `delete(User, { name: "Omar" })`; but since TypeScript won't tell you that you're doing anything wrong due to the overly general types, my team is finding this to be a particularly volatile API choice for TypeORM to not warn against.

Better would be stricter types to forbid usage of keys that aren't a part of `User`, but as a general complaint, wish the TypeORM APIs just generally had stricter enforcement of a consistent API invocation syntax.

**Comment by imnotjames** [comment] 2020-10-12 09:26
Duplicate of #3416

**Closed by imnotjames** 2020-10-12 09:26 UTC
Labels: comp: find options, driver: postgres, question
