### ISSUE TITLE
entity relation @where annotation

### ISSUE THREAD

**Issue by ajxs** [typeorm/typeorm#3898] opened 2019-03-26 06:30 UTC
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Are there any plans to support a @where clause annotation in an entity for denoting a relation which is always conditionally joined?
Here's an example of how Hibernate annotates it to show what I'm describing:

```
public class Parent {
  ...
  @ManyToOne(fetch = FetchType.EAGER) // EAGER forces outer join
  @JoinColumn(name = "parent_id")
  @Where(clause = "parent_id = id AND disabled IS NULL")
  // ...
}
```

**Comment by vlapo** [comment] 2019-03-27 09:18
I am sure I see this kind of FR before but cannot find it. But it was discussed and I think it is in 0.3.0 roadmap. But it is not clear when it will be implemented.

**Comment by imnotjames** [comment] 2020-10-17 09:03
Duplicate of #1601

**Closed by imnotjames** 2020-10-17 09:03 UTC
Labels: comp: relations, driver: postgres, new feature, question
