### ISSUE TITLE
MySQL - Add column FIRST | AFTER position

### ISSUE THREAD

**Issue by pc3b3r** [typeorm/typeorm#8503] opened 2022-01-04 14:08 UTC
## Feature Description
There isn't the possibility to alter a table by adding a column `AFTER` a specific one, or as `FIRST`

### The Solution

Add the option to the `TableColumn` class and implement it in the [`MysqlQueryRunner`](https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/driver/mysql/MysqlQueryRunner.ts#L1846)

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `mysql`              | yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment] 2022-04-16 13:33
Duplicate of #541

**Closed by AlexMesser** 2022-04-16 13:33 UTC
Labels: new feature, requires triage
