### ISSUE TITLE
[MYSQL] Cannot set type to timestamp when using CreateDateColumn or UpdateDateColumn decorators

### ISSUE THREAD

**Issue by jdpalumbo** [typeorm/typeorm#1480] opened 2018-01-19 21:24 UTC
It appear that there is no way to set the type of a column when using the CreateDateColumn or UpdateDateColumn decorators to `'timestamp'` is this by design?

```
@Entity()
export class Identity {
    @PrimaryColumn("bigint")
    @Generated()
    public id: number;

    @Column("timestamp")
    public date: Date;

    @CreateDateColumn({ type: "timestamp"})
    public created: Date;

    @UpdateDateColumn()
    public updated: Date;

    @OneToMany(() => Session, session => session.identity)
    public sessions: Session[];
}
```

**Comment by pleerock** [comment] 2018-01-23 06:31
We already have such feature request. Duplicate of #400

**Closed by pleerock** 2018-01-23 06:31 UTC
