### ISSUE TITLE
Data type "undefined" is not supported in "postgres" database

### ISSUE THREAD

**Issue by Tmbao** [typeorm/typeorm#669] opened 2017-07-15 08:46 UTC
Hi,

I'm using node 8.1, tsc 2.3.4, typeorm 0.1.0-alpha.29 on OSX sierra. While trying to create a unit test for my project with mocha, I encountered the following error: 

```
  appointment-service-test
    1) "before all" hook
    2) "after all" hook


  0 passing (51ms)
  2 failing

  1) appointment-service-test "before all" hook:
     DataTypeNotSupportedError: Data type "undefined" is not supported in "postgres" database.
      at new DataTypeNotSupportedError (src/error/DataTypeNotSupportedError.ts:8:9)
      at src/metadata-builder/EntityMetadataValidator.ts:75:27
      at Array.forEach (native)
      at EntityMetadataValidator.validate (src/metadata-builder/EntityMetadataValidator.ts:72:36)
      at src/metadata-builder/EntityMetadataValidator.ts:37:56
      at Array.forEach (native)
      at EntityMetadataValidator.validateMany (src/metadata-builder/EntityMetadataValidator.ts:37:25)
      at Connection.buildMetadatas (src/connection/Connection.ts:451:33)
      at Connection.<anonymous> (src/connection/Connection.ts:145:18)
      at step (node_modules/typeorm/connection/Connection.js:32:23)
      at Object.next (node_modules/typeorm/connection/Connection.js:13:53)
      at fulfilled (node_modules/typeorm/connection/Connection.js:4:58)
      at <anonymous>

  2) appointment-service-test "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.after (server-test/services/appointment.test.ts:21:15)
```

My test is as follow:

```typescript
import {AppointmentService} from '../../server/services/appointment';
import {Appointment} from '../../server/entities/appointment';
import {Connection, createConnection} from 'typeorm';
import {databaseConfig} from '../configs/database-config';
import { expect } from 'chai';
import {logger} from '../../server/utils/logger';
import {Person} from '../../server/entities/person';

const Path = require('path');

describe('appointment-service-test', function() {

  let connection: Connection;
  // Set up testing environment.
  before(async function() {
    connection = await createConnection(Object.assign({
      entities: [Appointment, Person],
    }, databaseConfig));
  });

  after(() => {
    connection.close();
  });

  it('test', () => {
    expect(1).to.equal(1);
  });
});
```

I'm pretty sure that my entity schemas are working ok because there is no errors and the schemas are synced normally when I run npm start. The problem only happens when I run test with 
`mocha -r ts-node/register server-test/**/*.test.ts`

**Comment by dvh312** [comment] 2017-07-15 14:59
Same issue when trying to test my project 👍

**Comment by Tmbao** [comment] 2017-07-15 15:55
Resolved by adding explicit type declarations as mentioned in https://github.com/typeorm/typeorm/issues/666.

**Comment by pleerock** [comment] 2017-07-15 17:36
can someone create a sample repo with reproduction of this problem? If its a bug it should be fixed urgently, but I cannot reproduce it

**Comment by Tmbao** [comment] 2017-07-15 18:39
You can reproduce the error with `npm test`.
[Archive.zip](https://github.com/typeorm/typeorm/files/1150540/Archive.zip)
Hope this helps!

**Comment by pleerock** [comment] 2017-07-17 13:22
can you please take a look on #666 ? People seem to have same problem because of simple mistale they do

**Comment by pleerock** [comment] 2017-07-25 12:23
You forgot to add `import "reflect-metadata";` to your test. You did it in your app main entry point but didn't do it in your test entry point. I did it and checked it, everything is working correctly:

```bash
> typeorm-typescript-example@0.0.1 test /Users/pleerock/www/clonned/Archive (1)
> mocha -r ts-node/register test/**/*.test.ts



  example-test
    ✓ example


  1 passing (47ms)
```

**Closed by pleerock** 2017-07-25 12:23 UTC

**Comment by dvh312** [comment] 2017-07-25 12:29
Hi pleerock,

Thank you very much for that. Really appreciate your help :)

**Comment by pleerock** [comment] 2017-07-25 12:38
no problem riki ;)

**Comment by seungha-kim** [comment] 2017-11-13 15:14
For someone who visits here later:

You should import (or require) `reflect-metadata` **before** loading any entities.
