### ISSUE TITLE
DROP instead MODIFY for models when modify Column options

### ISSUE THREAD

**Issue by kernox** [typeorm/typeorm#6457] opened 2020-07-23 15:12 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create an entity
Add a @Column with options {length: 255}
Add datas in database
Change the column length to 100 and sync the model.

The column is deleted instead a simple modification with MODIFY.
ex: ALTER TABLE contact MODIFY 'email' varchar(50) NOT NULL

It's a big problem if you have to optimize your model after data insertion.

```
//Before
    @Column("varchar", {unique: true, length: 255})
    email: string;

//After
    @Column("varchar", {unique: true, length: 100})
    email: string;
```

**Comment by jazzfog** [comment] 2020-07-23 23:15
I think this is the answer

> Its by design. Let's say you have length equal to `50`. What will happen if you change it to `10`? Right, data loss again. Some databases even don't allow to do it without dropping the column. Some allow however without any warning. We could handle all possible cases, but this is a bit more complex in implementation, that's why decided to make it simple this way.

Source: https://github.com/typeorm/typeorm/issues/3357#issuecomment-451368027

**Comment by kernox** [comment] 2020-07-24 07:39
Hi ! And thank you for your answer.

But i think an ORM do not have rights to destruct datas if the user/admin of the database don't allow it ponctually.
I prefer a violation error instead and think many developpers prefer too.

It's not difficult to transform the data in the database next the violation error of column length.
Other ORM do it like that and it's good.

I can not trust a software how have this destructive operation.

**Comment by PadraigGalvin** [comment] 2020-07-25 12:58
You shouldn't use `synchronize` in production, it's a dev tool. Instead you should use migrations which you can adjust after generation to define how you want to handle potentially destructive changes.

In your case that might mean truncating data before changing the varchar length. Either way with a migration you can replace the `DROP` and `CREATE` with an `ALTER` before it gets applied to production.

> synchronize - Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development. As an alternative to it, you can use CLI and run schema:sync command. Note that for MongoDB database it does not create schema, because MongoDB is schemaless. Instead, it syncs just by creating indices.

Source: https://typeorm.io/#/connection-options/common-connection-options

**Comment by kernox** [comment] 2020-07-30 22:13
@PadraigGalvin Yes I Know that. But when i am in development environnent i dislike to lose my test dataset it'd juste annoying.
Others ORM don't do that. So why this ORM do ? It's a bad thing ever it 's in dev mode.

This answer don't satisfy me. But thanks to try.

**Comment by powersjcb** [comment] 2020-08-12 18:42
As a dev onboarding to this tooling let's think about the user experience.

## synchronize
Oh look, a handy`synchronize` util. Definitely dev only. This will probably be useful for fixing state if my migrations get screwed up from dev branches on my laptop.

## generate:migration

Since `synchronize` is dangerous, `generate:migration` must inversely have safe defaults.

I bet this will prevent me from shooting myself in the foot and will allow there to be one source of truth for my production migrations. (Maybe I can setup a workflow where I drop the database, apply all previous migrations, and then generate the next migration based on the most recent code changes.) 

I'll select use this schemas so I can have only one source of truth for entities. This means, I'll only have to write bespoke migrations when doing backfills or renaming things.

## Some time later...
Why is this generated migration dropping my column when I add a `DEFAULT`?! This change shouldn't affect existing rows. *(Reads open TypeOrm issues on github and promptly replaces `generate:migration` with `create:migration`.)*

Dropping a column by default when alter statements are possible is a *huge* violation of expectations.

Some projects I've used in the past have have equivalent `generate:migration` tooling and we were able to use them for production because they broadly created "safe" migrations by default.
- [Django](https://docs.djangoproject.com/en/3.1/topics/migrations/#backend-suppor): does an `UPDATE COLUMN` operation
- [Gorm](http://gorm.io/docs/migration.html#Auto-Migration): NOOPs and gives a warning to prevent destructive behavior.

All this has me thinking: If `generate:migration` is unsafe by default. Why does it exist?

**Comment by imnotjames** [comment] 2020-10-14 06:30
Duplicate of #3357

**Closed by imnotjames** 2020-10-14 06:30 UTC
Labels: bug, comp: migrations, driver: mariadb, driver: mysql
