### ISSUE TITLE
TypeError: this.connection.hasMetadata is not a function

### ISSUE THREAD

**Issue by SaraKola** [typeorm/typeorm#7690] opened 2021-05-27 14:58 UTC
## Issue Description

When using the connection manager **save** method, it sometimes fails with the error **TypeError: this.connection.hasMetadata is not a function**

While debugging, we noticed that this is caused in **QueryBuilder.ts** line 541 https://github.com/typeorm/typeorm/blob/283413d8460208c68b0362afc2cbf7ebf8e35cc7/src/query-builder/QueryBuilder.ts#L541 where this.connection is not an instance of Connection but instead of SelectQueryBuilder

We are assuming that this is caused by the constructor in **QueryBuilder.ts** line 87 https://github.com/typeorm/typeorm/blob/283413d8460208c68b0362afc2cbf7ebf8e35cc7/src/query-builder/QueryBuilder.ts#L87
Here, in our case, the **connectionOrQueryBuilder** is an instance of SelectQueryBuilder and it has a connection, but it doesn't enter the if statement, therefor it goes into the else https://github.com/typeorm/typeorm/blob/283413d8460208c68b0362afc2cbf7ebf8e35cc7/src/query-builder/QueryBuilder.ts#L94 where this.connection is set to the SelectQueryBuilder instead

### Expected Behavior

Set connection to the actual connection instead of the SelectQueryBuilder

### Actual Behavior

As explained above

```
error: TypeError: this.connection.hasMetadata is not a function
      at InsertQueryBuilder.QueryBuilder.createFromAlias (../src/query-builder/QueryBuilder.ts:542:30)
      at InsertQueryBuilder.into (../src/query-builder/InsertQueryBuilder.ts:171:32)
```

### My Environment

Operating System: macOS Catalina 10.15.7 
Node.js version: 12.18.2
Typescript version: 3.5.2
TypeORM version: 0.2.32

### Additional Context

We already looked into this issue https://github.com/typeorm/typeorm/issues/1318 but we are not using jest's resetModules

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jginorio** [comment] 2021-06-01 15:29
Hi, I was experiencing the same problem, but it was because I was running Nestjs Serverless locally and I was sending two different requests at the same time. As soon as I stopped sending them at the same time I stopped receiving the error. I hope this helps

**Comment by imnotjames** [comment] 2021-06-19 14:49
`SelectQueryBuilder` is an instance of `QueryBuilder`.

This a local environment issue likely caused by some sort of reloading or otherwise.  We can't control that.

**Comment by imnotjames** [comment] 2021-06-20 22:54
Can you create a reproducible example?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2021-07-04 05:51
Without a reproducible example we can't confirm this.  As such, I'll be closing this issue out.

If you add an example please reopen the issue or open a new issue.

**Closed by imnotjames** 2021-07-04 05:51 UTC
Labels: bug, driver: postgres, needs more info

**Comment by hongyuanlei** [comment] 2021-09-29 06:19
I also facing the same issue when I run it in the serverless local.

```
TypeError: this.connection.hasMetadata is not a function
    at InsertQueryBuilder.QueryBuilder.createFromAlias (/code/node_modules/typeorm/query-builder/QueryBuilder.js:407:29)
```

**Comment by jrobichaud** [comment] 2021-10-08 14:32
@wilson208 yes, I am also using `serverless-offline`.
