### ISSUE TITLE
Add Yarn workspaces supports for ormconfig.js location

### ISSUE THREAD

**Issue by gutenye** [typeorm/typeorm#2805] opened 2018-09-16 07:34 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The `ormconfig.js` location is determined by [app-root-path](https://github.com/inxilpro/node-app-root-path#primary-method), when using yarn workspaces, it's not accurate anymore.

Given

```
ROOT/
  package.json     // {"workspaces": ["server"] }
  server1/
    package.json   // {"dependencies": {"typeorm": "latest"}}
    ormconfig.js
```

After `yarn`, it creates

```
ROOT/
  node_modules/{typeorm, app-root-path,...}
  server1/     // no node_modules anymore
```

So it reads `ROOT/ormconfig.js` instead of `ROOT/server1/ormconfig.js`

Possible solution: try `process.cwd()` first

**Comment by TheAifam5** [comment] 2018-11-18 14:15
Any update on this?

**Comment by aaronjensen** [comment] 2019-03-19 16:14
I created a repo reproducing the problem: https://github.com/aaronjensen/typeorm-monorepo-repro

Many projects use https://github.com/davidtheclark/cosmiconfig. Perhaps typeorm could as well?

**Comment by ChristianIvicevic** [comment] 2019-04-03 23:00
A workaround for the time being is the use of a `.env` file in the folder of your package. One of the caveats is that you cannot use multiple connections that way.

Nevertheless I'd appreciate support for `process.cwd() / ormconfig.json` as well.

**Comment by lookapanda** [comment] 2019-06-18 11:30
What is the workaround for this? Just drop the JSON file into the project root?

**Comment by TheAifam5** [comment] 2019-06-25 12:40
If someone is interested in workaround, check out here : https://github.com/inxilpro/node-app-root-path/issues/31#issuecomment-439739607

**Comment by gho1b** [comment] 2019-09-07 19:43
Hi, i got same issue with this config. Then i make a connection helper to read the config file based on server package because i use monorepo in my project.
```
import {join} from 'path';
import { readJson } from 'fs-extra';
import { ConnectionOptions } from 'typeorm';


export const getConnection = async (): Promise<ConnectionOptions> => {
  const configs: ConnectionOptions[] =  await readJson(join(process.cwd(), '/ormconfig.json'));
  const env = process.env.NODE_ENV ? process.env.NODE_ENV : 'default';
  const config = configs.find(config => config.name === env);
  if(!config) {
    throw Error('Connection Not Found');
  }
  return {...config, name: undefined};
}

export default getConnection;
```

Then call the function to initiate connection config
```
const config = await getConnection().then(connection => {
      return { ...connection, entities: [UserSchema] };
    });
    await createConnection(config);
```

**Comment by ramenbroth** [comment] 2020-01-05 12:23
Any update on this?

**Comment by Baterka** [comment] 2020-01-31 17:12
Does anyone have idea how to fix this better than https://github.com/typeorm/typeorm/issues/2805#issuecomment-529141245

**Comment by ramenbroth** [comment] 2020-01-31 19:37
@Baterka my solution was adding [nohoist](https://legacy.yarnpkg.com/blog/2018/02/15/nohoist/) for typeorm in the monorepo package.json
```json
"nohoist": [
  "**/typeorm/**",
  "**/typeorm"
]
```

**Comment by zhangpengchen** [comment] 2020-05-12 14:40
> @Baterka my solution was adding [nohoist](https://legacy.yarnpkg.com/blog/2018/02/15/nohoist/) for typeorm in the monorepo package.json
> 
> ```json
> "nohoist": [
>   "**/typeorm/**",
>   "**/typeorm"
> ]
> ```

Thanks, it took me a hour to find this.

**Comment by octogonz** [comment] 2021-06-25 21:53
> 
> I created a repo reproducing the problem: https://github.com/aaronjensen/typeorm-monorepo-repro

Looks like `app-root-path` 3.x has fixed their algorithm to detect PNPM and Yarn Plug'n'Play installations.  And the latest version version of TypeORM has upgraded to `app-root-path` 3.x.  Simply upgrading the TypeORM dependency fixes @aaronjensen's repro.

Seems like this issue is resolved?

**Comment by imnotjames** [comment] 2021-06-26 05:41
> > I created a repo reproducing the problem: https://github.com/aaronjensen/typeorm-monorepo-repro
> 
> Looks like `app-root-path` 3.x has fixed their algorithm to detect PNPM and Yarn Plug'n'Play installations. And the latest version version of TypeORM has upgraded to `app-root-path` 3.x. Simply upgrading the TypeORM dependency fixes @aaronjensen's repro.
> 
> Seems like this issue is resolved?

we've had that version since 2019 - if it's been a problem since then I think there's other issues.

**Comment by imnotjames** [comment] 2021-07-05 21:28
I take the silence as "it works". 

With that in mind I'm closing it.  Feel free to reopen or open a new issue if I've misunderstood.

**Closed by imnotjames** 2021-07-05 21:28 UTC
Labels: comp: configuration, driver: postgres, enhancement, new feature

**Comment by Karabur** [comment] 2021-08-02 03:52
TypeORM: 0.2.36
app-root-path: 3.0.0

Repo with Yarn PnP
@imnotjames I can confirm problem still here. 

Issue about supporting yarn workspaces in app-root-path still open https://github.com/inxilpro/node-app-root-path/issues/31.
I am not sure why @octogonz have seen it as solved, that module didnt get any update for last 2 years

**Comment by imnotjames** [comment] 2021-08-02 04:16
https://github.com/inxilpro/node-app-root-path/commit/20420ae54ace38128e2b9d9cfeb53c8f979621cf This doesn't add support for pnpm?

**Comment by andreyselin** [comment] 2021-12-03 12:31
Looks like deprecated hoisting does no longer work in my yarn v3.1.0.
`nmHoistingLimits: workspaces` does the thing but it fills additional node_modules folder on nested level.

I found following simple workaround:
```
# package.json scripts section
# Instead of calling this
"migration:create": "ts-node node_modules/typeorm/cli.js --config src/config/ormconfig.ts migration:create -n ${0}",
# I run this:
"migration:create": "ts-node tools/typeOrmCli.ts --config src/config/ormconfig.ts migration:create -n ${0}"
```
Note that I made tools/typeOrmCli.ts wrapper file with following contents:
```
import cli from 'typeorm/cli.js';
void cli;
```
This will call the cli from the folder of application and build correct path string for migration file.
