### ISSUE TITLE
Migration generate drops/creates all constraints

### ISSUE THREAD

**Issue by ProTip** [typeorm/typeorm#1686] opened 2018-03-01 21:44 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

On an existing database in PostgreSQL 9.6.2 migration generation wants to drop all unique constraints and create them again. I ran this migration however it wants to do it on the next generate as well. The only thing I can tell(without digging into the code) is that the order in ```down``` is backwards on the columns in the SQL statement..

**Comment by pleerock** [comment] 2018-03-02 07:19
> On an existing database in PostgreSQL 9.6.2

what is existing database? Database generate from older typeorm version? If yes, then its okay that it drops them since there is a new foreign keys naming strategy in latest next.

**Comment by ProTip** [comment] 2018-03-06 17:55
Database tables were created outside of TypeORM initially. I have let it drop and re-add the constraints multiple times but it always generates the commands again in the migrations as of ```0.2.0-alpha.27```.

I will dive into the code soon and see if I can track down the issue; will open a PR if it's a straightforward fix.

**Comment by pleerock** [comment] 2018-03-09 08:31
no, its okay that typeorm drops and re-create exist keys. To make a proper comparison of exist keys TypeORM uses its own naming strategy for them. So it simply checks that it does not have fks and there are outdated fks - it removes old one a create new ones. Its expected behaviour.

**Comment by ProTip** [comment] 2018-03-09 17:59
Currently it does it for every migration. I've allowed it to drop and recreate the unique constraints, however it wants to do it again for *every* migration.

So, currently, every migration I generate is cluttered with drop/add constraint commands even though I keep letting it run them.

**Comment by pleerock** [comment] 2018-03-09 19:04
hmm I need a reproduction example. Can you reproduce this issue without pre-created database?

**Comment by pleerock** [comment] 2018-03-29 09:05
Closing as no answer from reporter.

**Comment by asvetliakov** [comment] 2018-04-18 00:36
Got the same problem,
Repro:
Entities:

User.ts
```ts
import { PrimaryGeneratedColumn, Column, Entity, PrimaryColumn, OneToOne } from "typeorm";
import { Profile } from "./Profile";

@Entity()
export class User {
    @PrimaryColumn("varchar", { length: 255 })
    public id: string;


    @Column("varchar")
    public name: string;

    @OneToOne(type => Profile, p => p.user, { eager: true })
    public profile: Profile;
}
```

Profile.ts
```ts
import { Entity, OneToOne, JoinColumn, Column } from "typeorm";
import { User } from "./User";

@Entity()
export class Profile {
    @OneToOne(type => User, u => u.profile, { primary: true, onDelete: "CASCADE" })
    @JoinColumn({ name: "uuid" })
    public user: User;

    @Column("varchar")
    public b: string;
}
```


1) Install typeorm 0.1
2) Generate initial migration and perform it
3) Install typeorm 0.2
4) Generate upgrade migration and perform it
5) Generate migration again, expected result - no changes, got this:
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class Test31524011622628 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("DROP INDEX `IDX_fab5f83a1cc8ebe0076c733fd8` ON `profile`");
        await queryRunner.query("ALTER TABLE `profile` DROP FOREIGN KEY `FK_fab5f83a1cc8ebe0076c733fd85`");
        await queryRunner.query("ALTER TABLE `profile` ADD UNIQUE INDEX `IDX_fab5f83a1cc8ebe0076c733fd8` (`uuid`)");
        await queryRunner.query("ALTER TABLE `profile` ADD CONSTRAINT `FK_fab5f83a1cc8ebe0076c733fd85` FOREIGN KEY (`uuid`) REFERENCES `user`(`id`) ON DELETE CASCADE");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `profile` DROP FOREIGN KEY `FK_fab5f83a1cc8ebe0076c733fd85`");
        await queryRunner.query("ALTER TABLE `profile` DROP INDEX `IDX_fab5f83a1cc8ebe0076c733fd8`");
        await queryRunner.query("ALTER TABLE `profile` ADD CONSTRAINT `FK_fab5f83a1cc8ebe0076c733fd85` FOREIGN KEY (`uuid`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT");
        await queryRunner.query("CREATE UNIQUE INDEX `IDX_fab5f83a1cc8ebe0076c733fd8` ON `profile`(`uuid`)");
    }

}
```

**Comment by lukeautry** [comment] 2018-05-18 14:18
Please re-open - we're also seeing this problem. Every time we generate a new migration, the written migration drops all indexes and re-adds them. We have to manually adjust the migration to remove those changes.

**Comment by asvetliakov** [comment] 2018-05-18 14:20
Repro is available here:
https://github.com/asvetliakov/typeorm-bugs/tree/master/1686

**Comment by ValiDraganescu** [comment] 2018-07-25 17:18
yes, having the same issue in typeorm@0.2.7

**Comment by pmd30011991** [comment] 2018-10-09 15:44
Same problem, Please fix this soon Thanks

**Comment by pleerock** [comment] 2018-10-20 11:17
#2918 check it once 0.2.9 is released

**Closed by pleerock** 2018-10-20 11:17 UTC
Labels: comp: migrations

**Comment by AlexFreem** [comment] 2019-01-29 11:15
This problem reproduced on typeorm@0.2.12-rc.2
Still creates advanced migration file with drop indexes

**Comment by nelsonBlack** [comment] 2019-05-20 07:57
still experiencing same problem with version 0.2.17

**Comment by jamesorlakin** [comment] 2019-07-23 09:46
Interestingly running one of the queries TypeORM runs does return multiple constraints for the same foreign key? I'm running MariaDB 10.1.36.

![image](https://user-images.githubusercontent.com/7294642/61702057-10e8a780-ad37-11e9-8def-e7463afd3adc.png)

Both the event and tokens are simple one-to-manys defined with the same constraints, so I'm not sure why it's being stored strangely. It could even be a DB issue and HeidiSQL only sees one key.

**Comment by brinzi** [comment] 2019-08-07 09:47
Still having this issue in 0.2.19, any news?

**Comment by rustamwin** [comment] 2019-08-07 09:59
feel free to create a new issue

**Comment by kazelone** [comment] 2019-10-28 13:56
I am having a similar issue. I deleted my migrations, created a new initial migration from an empty database, then if I generate a new migration, it drop / recreate the constraint, but fail to drop some so on top of doing useless drop/creation, it doesn't even work.

**Comment by jamesorlakin** [comment] 2019-10-28 18:16
I found the problem went away when I moved from MariaDB back to normal MySQL 5.7. There is some difference in the way MariaDB handles table layouts:
![image](https://user-images.githubusercontent.com/7294642/67705441-e69a2c00-f9ae-11e9-9f2e-846e83e9e7e9.png)

This matched the behaviour of TypeORM re-nullifying columns constantly. As for the indexes, I'm guessing there's a difference there too.

**Comment by daweedm** [comment] 2020-03-14 19:17
How to solve this if we have to stay with MariaDB ?

**Comment by arnoldkenaci** [comment] 2020-03-16 12:41
The issue is still occurring with version 0.2.24 and SQL Server DB.

**Comment by ValiDraganescu** [comment] 2020-03-29 12:56
Check my issue here [5407](https://github.com/typeorm/typeorm/issues/5407)
I found that there is a difference between default values for MySQL (Not sure about other databases)

**Comment by kuklei** [comment] 2020-07-16 14:16
The issue is still occurring with version 0.2.25 and MSSQL 5.1.0.

**Comment by kuklei** [comment] 2020-07-16 16:18
I had a situation in one entity that I added a new column and removed an old one. I have found that the issue went away when I moved back to 0.2.20 and modified the entity by just adding the column and not removing the other one. The script being generated was strange as the column being dropped was being renamed to the column that was being added using spRename instead of simply dropp and add. 

This was the red flag that solved it for me but I am not sure why moving away from 0.2.20 will begin scripting the indexes as drop and recreate with the same name

**Comment by m-nikhil** [comment] 2020-09-04 21:18
Any updates for the fix? Facing the same issue

**Comment by issackr** [comment] 2020-09-08 22:31
Same issue here 0.2.25

**Comment by arjunDhanAi** [comment] 2020-10-07 11:00
Hi, we have just started using "typeORM" with "mssql". we created a User entity model as below

`
import * as bcrypt from 'bcrypt';
import { Exclude } from 'class-transformer';
import { IsNotEmpty } from 'class-validator';
import { BeforeInsert, Column, Entity, PrimaryColumn} from 'typeorm';

@Entity()
export default class User {

    public static hashPassword(password: string): Promise<string> {
        return new Promise((resolve, reject) => {
            bcrypt.hash(password, 10, (err, hash) => {
                if (err) {
                    return reject(err);
                }
                resolve(hash);
            });
        });
    }

    public static comparePassword(user: User, password: string): Promise<boolean> {
        return new Promise((resolve, reject) => {
            bcrypt.compare(password, user.password, (err, res) => {
                resolve(res === true);
            });
        });
    }

    @PrimaryColumn('uuid')
    public id: string;

    @IsNotEmpty()
    @Column({ name: 'first_name' })
    public firstName: string;

    @IsNotEmpty()
    @Column({ name: 'last_name' })
    public lastName: string;

    @IsNotEmpty()
    @Column()
    public email: string;

    @IsNotEmpty()
    @Column()
    @Exclude()
    public password: string;

    @IsNotEmpty()
    @Column()
    public username: string;

    @Column({
        default: 'read'
    })
    public role: String;

    public toString(): string {
        return `${this.firstName} ${this.lastName} (${this.email})`;
    }

    @BeforeInsert()
    public async hashPassword(): Promise<void> {
        this.password = await User.hashPassword(this.password);
    }

}

`
The generated migrations file is as follows
`
import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateUserTable1511105183653 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        const table = new Table({
            name: "user",
            columns: [
                {
                    name: "id",
                    type: "varchar",
                    length: "255",
                    isPrimary: true,
                    isNullable: false,
                },
                {
                    name: "first_name",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
                {
                    name: "last_name",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
                {
                    name: "email",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
                {
                    name: "username",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
                {
                    name: "password",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
                {
                    name: "role",
                    type: "varchar",
                    length: "255",
                    isPrimary: false,
                    isNullable: false,
                },
            ],
        });
        await queryRunner.createTable(table);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.dropTable("user");
    }
}
`

After this migration has been run on the DB, we had to add a unique constraint on the DB table
`
@Unique("unique-email-username", ["email", "username"])
export default class User {
`
When we wanted to generate the migrations again, the migration file generated has dropped all the columns and all other constraints and recreated the columns and constraints.

This is not what I was expecting. Is there any way to change this behavior?

**Comment by mkornatz** [comment] 2020-11-18 14:17
I also ran into this issue with SQL Server. The problem appears to be introduced in https://github.com/typeorm/typeorm/commit/7157cb3 in v0.2.23/24.

The `foreignKeysMatch` function compares the table name to the table path. Which, in the case of something like SQL Server is `user` vs. `dbo.user`. I'm not sure if that's the case for other databases.

**Comment by stvvt** [comment] 2020-11-19 08:22
> I also ran into this issue with SQL Server. The problem appears to be introduced in [7157cb3](https://github.com/typeorm/typeorm/commit/7157cb3) in v0.2.23/24.
> 
> The `foreignKeysMatch` function compares the table name to the table path. Which, in the case of something like SQL Server is `user` vs. `dbo.user`. I'm not sure if that's the case for other databases.

I can confirm the same behavior with Postgres 9.6

Function [foreignKeysMatch()](https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/schema-builder/RdbmsSchemaBuilder.ts#L791) compares `tableForeignKey.referencedTableName` ('user') with `metadataForeignKey.referencedTablePath` ('public.user')

**Comment by dariusmb** [comment] 2021-01-12 13:13
@pleerock Can this be reopened? I encounter the same problem with typeorm@0.2.29 and Postgresql 10.6. All the constraints are dropped and created again when generating a new migration.

**Comment by DavideCarvalho** [comment] 2021-02-03 11:25
I'm facing the same issue with MySQL. It's not all of the constraints, tho, it's just a few of them that are being recreated.

Tried changing from mysql2 library to mysql, but still the same problem

**Comment by DavideCarvalho** [comment] 2021-02-03 11:30
On top of that, the constraints for the newly created tables are throwing errors - I use uuid as id.

Error: Error: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
sql: 'ALTER TABLE `role_policies_policy` ADD CONSTRAINT `FK_77a05aab87336e865f79c058745` FOREIGN KEY (`roleId`) REFERENCES `role`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION'

**Comment by nebkat** [comment] 2021-02-04 00:14
If the cause is known perhaps someone could submit a pull request with the fix implemented, it doesn't look too hard.

**Comment by VictorCurean** [comment] 2021-04-07 13:54
@pleerock I have encountered the same problem with Postgresql 12.5 and typeorm 0.2.31

**Comment by lynk-one-machines** [comment] 2021-05-06 17:57
Same for me ... could we do something ?

**Comment by oleurud** [comment] 2021-05-31 10:25
We were facing this error too: TypeORM 0.2.32, Postgres 13.2, and Node.js 16.2. It was happening too in previous versions of TypeORM (0.2.32) and Node.js 14.

I am a newbie with TypeORM, but today, after realizing that different mates have different migrations files after running `migration:generate` command (when no one should be created), locally, I have tried making a new git clone of the project. After starting up the app again (`npm ci`, `docker compose up`, `npx ts-node node_modules/.bin/typeorm migration:run`), the `migration:generate` command is working as expected and it is not creating a new migration file.

Of course, before that, we had already tried stuff like `npm ci`, remove npm cache, etc, and recreating the database with TypeORM or manually.

Right now, I don't know why it works, but maybe this can help someone or rings a bell

**Comment by dominik992** [comment] 2021-07-30 06:13
thanks @oleurud!
I also have no idea why, but the following (as you suggested) fixed the issue.
```
rm -rf project
git clone project
cd project
npm ci
ts-node ./node_modules/typeorm/cli migration:run
```

**Comment by ezzabuzaid** [comment] 2021-07-31 19:31
following @dominik992 answer, I was able to fix it by using ./node_modules/typeorm/cli instead of global installed version typeorm

**Comment by Ponjimon** [comment] 2021-08-10 12:13
> following @dominik992 answer, I was able to fix it by using ./node_modules/typeorm/cli instead of global installed version typeorm

I've always been using the binary from the `node_modules` folder instead of the globally installed one and I'm facing the same issue. So I cannot confirm this to be a workaround.

**Comment by julianmclean** [comment] 2021-08-12 14:11
Was hitting a similar problem with every new generated migration wanting to drop and recreate the same FKs (this is MySQL). Not sure if identical to the above, but my problem was related to a change in field length for the primary ID column. We had a couple of  tables that were modified so they had a auto-generating (UUID) primary key, which I believe normally generates a VARCHAR(36) where the ID columns were originally VARCHAR(255).

This change had NOT auto-generated SQL to alter these columns, and I believe this discrepancy (other tables having columns with FKs to these ID columns) results in the situation where it cannot resolve and just keeps trying to drop/recreate the FKs, without altering the column length.

Fix for me was to manually add SQL in the migration to change the column length between the drop and recreate, such as:

await queryRunner.query("ALTER TABLE `table_with_fk` DROP FOREIGN KEY `FK_2efaa7d126a5201143810f0caaa`");
await queryRunner.query("ALTER TABLE `table_with_pk_that_changed` MODIFY `pk_field` VARCHAR(36) NOT NULL");
await queryRunner.query("ALTER TABLE `table_with_fk` ADD CONSTRAINT `FK_2efaa7d126a5201143810f0caaa` FOREIGN KEY (`fk_field`) REFERENCES `table_with_pk_that_changed`(`pk_field`) ON DELETE NO ACTION ON UPDATE NO ACTION");

Following this fix, further generated migrations were ok. So...worth checking if you have PK/FK columns that have changed length for some reason.

**Comment by serg06** [comment] 2021-11-02 20:51
Thank yoo @dominik992 @ezzabuzaid, that worked.

**Comment by itseramin** [comment] 2022-08-25 13:46
Please fix, I'm using Postgres and it's annoying as hell.

**Comment by kgkg** [comment] 2022-09-22 14:36
I had similar issues but it turned out it were just issues in my code. I'm not saying it's the same in your case but check following
1) custom naming strategy (I had some randomness in FK name generation) - you can spot that by comparing IDs in `up` and `down` methods - if they're different just check your naming strategy.
2) I had incorrectly defined ManyToMany relationship. I needed junction table entity and I've created it, but forgot to change definitions in connected entities to OneToMany into junction table. You can see if this is the case when you get identical migrations diff no matter how many times you run them.

**Comment by patrykpieniak** [comment] 2023-04-15 15:32
I have the same issue on the latest version (0.3.15). TypeORM generates a migration with a large number of unnecessary actions, such as "ALTER".

**Comment by gramsuy** [comment] 2023-06-02 03:12
I have the same issue. TypeORM 0.3.10, mariadb. The problem is with
 
`@PrimaryGeneratedColumn('uuid')`

I solved replacing with
`@PrimaryColumn({ generated: 'uuid', nullable: false, length: 36, type: "varchar" })`

**Comment by mahkassem** [comment] 2023-06-05 07:45
> Thank you! you saved my day.

**Comment by Andriipalamarchuk** [comment] 2023-06-08 14:30
Still having the same issue on 0.3.15

We had automatically generated tables for many to many relations, for the performance side we decided not to save whole entities on cascade but just to write data on the "middle" table. Once entities were created typeorm every time tries to drop and recreate indexes and foreign keys and also alter column setting the same rules (not null, etc.).

If anyone knows how to solve this problem please let me know, because in our case no solution provided in this thread works

**Comment by Number16BusShelter** [comment] 2023-06-12 06:04
Please, take a look at my solution on #10122

**Comment by Andriipalamarchuk** [comment] 2023-06-12 15:19
> 

Solved with this one, thank you very much ;)

**Comment by parkhojeong** [comment] 2023-11-18 06:57
> I have the same issue. TypeORM 0.3.10, mariadb. The problem is with
> 
> `@PrimaryGeneratedColumn('uuid')`
> 
> I solved replacing with `@PrimaryColumn({ generated: 'uuid', nullable: false, length: 36, type: "varchar" })`

i have same issue. 'mysql' TypeORM 0.3.16  `@PrimaryColumn({ generated: 'uuid', nullable: false, length: 36, type: "varchar" })`

The problem is with 'mysql'

i solved replacing with `mariadb`

thanks for comment

**Comment by ctilley83** [comment] 2024-01-20 16:56
> I also had a similar problem where every new generated migration would drop and create my foreign keys. Turned out I had the wrong database type in my typeorm config. I had mysql, but I am using mariadb.

Yeah.... wish I saw this last night lol. I thought that was pointing to the node mysql adapter. That fixed it for me. Thank you.

**Comment by brucruz** [comment] 2024-08-28 21:19
This issue still persists in `typeorm@0.3.20` with Postgres 13

**Comment by khobiziilyes** [comment] 2024-10-15 15:24
Same issue.
TypeORM 0.3.16
Postgres@14

**Comment by tugay-radity** [comment] 2024-12-05 12:33
For the custom-created migrations with custom indexes.

I solved the issue by adding those indexes to the entity with `synchronize: false`

```TypeScript

@Index('idx_quote_number_trgm', { synchronize: false }) // this is custom index, not generated by typeorm
@Index('idx_quote_data_gin', { synchronize: false }) // this is custom index, not generated by typeorm
@Entity({ name: 'quote' })
export class Quote extends AdbrioSoftDeletableEntity {
```

And now when we auto-generate migrations TypeORM doesn't drop custom indexes.
