### ISSUE TITLE
Fix deprecation warnings for highlight.js v10.7

### ISSUE THREAD

**Issue by SerhiiBulakh** [typeorm/typeorm#7489] opened 2021-03-22 13:02 UTC
![typeorm](https://user-images.githubusercontent.com/46135982/111993727-a09fb400-8b1f-11eb-9e3c-97de44327dc2.PNG)

**Comment by loriswit** [comment] 2021-03-23 17:52
This seems to be caused by [cli-highlight](https://github.com/felixfbecker/cli-highlight/blob/d9613c9c5cbe8a0acb29faad2af934114d96d1ba/src/index.ts#L97).

**Comment by SerhiiBulakh** [comment] 2021-03-24 06:33
> This seems to be caused by [cli-highlight](https://github.com/felixfbecker/cli-highlight/blob/d9613c9c5cbe8a0acb29faad2af934114d96d1ba/src/index.ts#L97).

yes, you are right)

**Comment by dylvaz** [comment] 2021-03-28 06:54
So what exactly is the fix for this rn? I saw @loriswit made a PR to fix this, but I'm getting tired of seeing these console log statements 😅

**Comment by loriswit** [comment] 2021-03-28 11:22
@dylvaz Right now, you could temporarily downgrade your local installation of highligh.js as a workaround:
```bash
npm i highlight.js@10.6 --no-save
```
Then once the fix for cli-highlight is released, simply run:
```bash
npm update
```

**Closed** 2021-06-25 07:15 UTC
