### ISSUE TITLE
Joining Same Column with more than one table

### ISSUE THREAD

**Issue by ramk18** [typeorm/typeorm#3901] opened 2019-03-26 14:59 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have got three entities, Contact, EnhancedContact and MappedContact, with a one to one relation between them. The entities are shown below:

```
@Entity()
export class Contact {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ name: 'first_name', type: 'text' })
    firstName: string;

    @Column({ name: 'last_name', type: 'text' })
    lastName: string;

    @Column({ name: 'email', type: 'text' })
    email: string;

}

@Entity()
export class MappedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    contactId: number;

    @OneToOne(type => Contact)
    @JoinColumn({name: 'id_contact'})
    contact: Contact;

    @OneToOne(type => EnhancedContact)
    @JoinColumn({name: 'id_contact'})
    enhancedContact: EnhancedContact;
}


@Entity()
export class EnhancedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    contactId: number;

    @OneToOne(() => Contact)
    @JoinColumn({name: 'id_contact'})
    contact: Contact;

    @Column({name: 'power', type: 'int'})
    power: number;
}
```

I want to left join and select contact from mapped contact. For this, I employ the following command:

```
const mcs = await connection.manager.createQueryBuilder(MappedContact, "entity")
    .leftJoinAndSelect("entity.contact", "contact")
    .getMany();
console.log(mcs);
```

I get a failed Query error: 

```
SELECT "entity"."id_contact" AS "entity_id_contact", "contact"."id" AS "contact_id", "contact"."first_name" AS "contact_first_name", "contact"."last_name" AS "contact_last_name", "contact"."email" AS "contact_email" FROM "mapped_contact" "entit
y" LEFT JOIN "contact" "contact" ON contact.contactId="entity"."id_contact"
```

I don't know why contact.id became contact.contactId.

I also tried referencedColumnName, It still gave me the same error.

```
@Entity()
export class Contact {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ name: 'first_name', type: 'text' })
    firstName: string;

    @Column({ name: 'last_name', type: 'text' })
    lastName: string;

    @Column({ name: 'email', type: 'text' })
    email: string;

}

@Entity()
export class MappedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    contactId: number;

    @OneToOne(type => Contact)
    @JoinColumn({name: 'id_contact', referencedColumnName: 'id'})
    contact: Contact;

    @OneToOne(type => EnhancedContact)
    @JoinColumn({name: 'id_contact', referencedColumnName: 'contactId'})
    enhancedContact: EnhancedContact;
}


@Entity()
export class EnhancedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    contactId: number;

    @OneToOne(() => Contact)
    @JoinColumn({name: 'id_contact', referencedColumnName: 'id'})
    contact: Contact;

    @Column({name: 'power', type: 'int'})
    power: number;
}
```

**Comment by ramk18** [comment] 2019-03-28 07:55
I found a workaround. I used leftJoinAndMapOne which seems to work.

**Comment by alfonsoal1983** [comment] 2019-03-31 10:17
There is another issue with the same error

https://github.com/typeorm/typeorm/issues/3035

It is a column that is a foreign key of two different tables, in these tables the names of the ids are different and that causes a problem. The table that makes the join uses as the reference name the last one that has been declared.

The way to solve is by making the names of the variables equal in the two referenced tables, you should have something like this:

`@Entity()
export class Contact {

    @PrimaryGeneratedColumn()
    contactId: number;`

`@Entity()
export class EnhancedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    contactId: number;`

or this:

`@Entity()
export class Contact {

    @PrimaryGeneratedColumn()
    id: number;`

`@Entity()
export class EnhancedContact{
    @PrimaryColumn({type: 'int', name: 'id_contact'})
    id: number;`

With this change you do not need the referencedColumnName. I do not know if it is a mistake of the library or is a nomenclature to follow.

**Comment by Ericnr** [comment] 2020-01-03 19:35
I'm having problem trying to do something similar, but getting a different error. Would appreciate if anyone could help at #5289

**Comment by mrinvisible0** [comment] 2020-05-05 21:14
Is there any indication that this will be solved? I have same problem.

**Comment by imnotjames** [comment] 2020-10-10 09:53
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 09:53 UTC
Labels: bug, driver: postgres

**Comment by abheypathogenie** [comment] 2022-01-31 10:04
@ramk18 
> I found a workaround. I used leftJoinAndMapOne which seems to work.

i was about to break laptop and found this thanks.

**Comment by Kvikikp** [comment] 2022-08-24 16:10
Are there any updates when this will be fixed?
