### ISSUE TITLE
Supporting neo4j

### ISSUE THREAD

**Issue by AbolfazlHeidarpour** [typeorm/typeorm#7609] opened 2021-05-02 08:11 UTC
## Feature Description
Supporting graph databases and columnar and key-value databases
### The Problem
According to documentation, TypeORM does not support columnar, key-value and graph databases like hbase, neo4j,Redis databases.

TypeORM should support this databases especially neo4j, because graph databases are in high use and demand.

### The Solution

Well, I do not know how to add supporting this databases to TypeORM

### Additional Context

TypeORM is very flexible and easy to understand, but it must support more databases

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-06-14 03:10
Duplicate of #6190

**Closed** 2021-06-14 03:10 UTC
Labels: new feature, requires triage
