### ISSUE TITLE
`pg` < 8 causes node 14+ to crash

### ISSUE THREAD

**Issue by csterritt** [typeorm/typeorm#5949] opened 2020-04-24 19:38 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Today, homebrew updated my Mac to Node 14.  My typeorm code immediately stopped working, and watching Little Snitch (extra firewall), I could see that node was not connecting in any way to the Postgres server.   Dropping back to node 12 solved the issue.

I tried rebuilding the `node_modules` directory.

Anything else I can do to fix this locally?

**Comment by smber1** [comment] 2020-04-26 11:09
I can confirm this too.  Program exits with code 0 during `createConnection`.  Downgrading to Node 12 has fixed it for me too.

**Comment by smber1** [comment] 2020-04-26 11:13
Oh, bumping to `pg@8.0.3` looks like it fixes it!

**Comment by csterritt** [comment] 2020-04-26 13:56
Thanks @smber1!  That's good to know.

**Comment by s-chand** [comment] 2020-04-28 02:32
I recommend a downgrade to Node 12. In my case I was using node:alpine. A reversal to lts-alpine(which is node 12) fixed this for me. Took me 2 full days to find this issue.

Be wary ye typeorm travellers. Heed the words of @smber1 .

Thanks for sharing this.

**Comment by rigelglen** [comment] 2020-05-04 06:10
I have the same issue even though I've upgraded to `pg@8.0.3`. I'm using the latest version of `typeorm@0.2.24` and the official `14.1.0-alpine` node image. Reverting to 13.14.0 fixes the issue. 

Weird thing is that it doesn't exit or throw an exception, its just stuck awaiting the createConnection call to finish.

**Comment by SerhiiHalych** [comment] 2020-05-05 10:25
This is actually what I was looking for. createConnection() was crushing my server without any error before I upgraded pg version to  @8.0.3

**Comment by nudabagana** [comment] 2020-05-07 14:36
Same here. I got really confused when my app suddenly stopped working without throwing any errors. Turns out node updated to v14 and this happened.

**Comment by DLMousey** [comment] 2020-05-10 16:07
Can confirm same issue here, it's completely silent - no error messages, no logs, no amount of try/catch or then/catch ever executes, this has been driving me absolutely mad today.

Will attempt to update `pg` and report back

**Comment by stephanoparaskeva** [comment] 2020-05-10 23:16
Took a while to figure out why my server wasn't starting due to silent failure. Found it was because of upgrading to node 14.2.

**Comment by leoperria** [comment] 2020-05-12 15:42
Same problem here, upgraded node from 13.8.0 to  14.2.0 and createConnection() stopped working. Upgraded pg to version  8.0.3 solved

**Comment by marcpicaud** [comment] 2020-05-27 19:54
Geez ! I wasted so many hours on this. Thanks @smber1 for the solution, bumping to pg@8.0.3 solved it.

That'll teach me a lesson : stop using `node:latest` image, FFS...

I would be interested to have some more details about why this `exit 0` happens. It's the worst way to start a debugging session 😂

**Comment by davidmweber** [comment] 2020-06-03 09:00
Can confirm upgrade to pg 8.0.3 fixed the problem. Completely gobsmacked that there was zero logging or errors. Just a waste of 2 hours. So I got lucky I guess..... Thanks everyone for the helpful comments.

**Comment by gerreth** [comment] 2020-07-02 08:05
Same problem here and I stumbled upon https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L913
Throwing this error finally led me to solving the problem (and finding this issue here).

**Comment by hotdang-ca** [comment] 2020-07-27 17:15
Confirmed downgrade to docker image `12.18.2` (instead of `latest` fixed the issue; db is an elephantsql instance, for which i do not have control over the version.

Very odd that there was no thrown error, this should be another fix that would sure help.

**Comment by imnotjames** [comment] 2020-08-27 09:39
I've bumped the dev dependencies to 8.0.3 - perhaps we should also set peer dependencies for these as well so folks know what versions it's compatible with?

**Comment by PhillipChaffee** [comment] 2020-09-09 14:19
It would be great if the TypeORM init command made sure to use `pg ^8.0.3` if you are on node 14. Not sure if this is possible, but it is very confusing to run the server after init and get nothing.

**Comment by aeremin** [comment] 2020-10-28 15:33
Node 14 just became LTS. So anybody using `node:lts` docker image (or defaulting Node version to "current LTS" will run  into this.

**Comment by alexmacarthur** [comment] 2020-11-16 04:06
Just hit this when upgrading to Node LTS (14.5.0). Upgrading `pg` did the trick! Thanks!!

**Comment by PeHo89** [comment] 2021-01-14 09:39
I just faced the same problem and upgrading `pg` to `8.5.1` with `node 14.15.3` also worked for me! Was searching a few hours for the cause of problem.

**Comment by phivh** [comment] 2021-02-07 16:14
> I just faced the same problem and upgrading `pg` to `8.5.1` with `node 14.15.3` also worked for me! I was searching a few hours already for the cause of the problem. Many thanks!

same here! Thanks

**Comment by alikondie** [comment] 2021-02-08 14:52
Same here, always required to downgrade to node 12 :(

**Comment by pakhuta** [comment] 2021-02-16 12:22
@pleerock, looks like the issue can be closed.
Solution is upgrading `pg` to `^8.0.3`.

**Comment by jcrben** [comment] 2021-06-06 21:03
@AlexMesser close this?

**Closed** 2021-06-06 21:56 UTC
Labels: bug, driver: postgres
