### ISSUE TITLE
No repository for .. was found. Even thou repositories are registered

### ISSUE THREAD

**Issue by mathiasmaerker** [typeorm/typeorm#5813] opened 2020-04-06 11:20 UTC
Issue type:

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[x] mysql / mariadb
[ ] oracle
[ ] postgres
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[x ] latest
[ ] @next
[] 0.2.8 (or put your version here)

Steps to reproduce or a small repository showing the problem:

My repositories are not found even thou they are registered and present

After debugging a lot I found the place where the error happens
https://github.com/typeorm/typeorm/blob/442bff950704443e0b42fd0f950180d062f8389f/src/connection/Connection.ts#L482

I attached a screenshot and I don't understand why `find()` is returning false ..
`metadata.target` seems so equal `target`?? 
Any Ideas?

![image](https://user-images.githubusercontent.com/4051929/78553319-5091e980-7809-11ea-9428-160c2d84c9a6.png)

**Comment by Anthony-Tresallet** [comment] 2020-08-14 13:04
I'm facing the same issue..

**Comment by imnotjames** [comment] 2020-10-06 05:39
Pretty sure this a duplicate of #5676

**Closed by imnotjames** 2020-10-06 05:39 UTC
