### ISSUE TITLE
Doesn't work on first load in angular electron app

### ISSUE THREAD

**Issue by anandsiddharth** [typeorm/typeorm#4542] opened 2019-08-05 16:05 UTC
**Doesn't load when loaded for the first time:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

file : parameter.ts
```
import { Entity, PrimaryGeneratedColumn, Column, Unique } from "typeorm";

@Entity()
@Unique("UQ_NAMES", ["name"])
export class Parameter {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}
```

file : connection.ts
```
import { Parameter } from './entities/Parameter';

import { Connection } from 'typeorm';

const electron = window.require('electron')
const path = electron.remote.require('path')
const { createConnection } = window.require('typeorm')

const sqlitePath = path.join(electron.remote.app.getPath('userData'), '\\data\\app.sqlite')
console.log('sqlite path', sqlitePath);

let connection: Connection;
createConnection(
    {
        type: "sqlite",
        database: sqlitePath,
        entities: [Parameter],
        logging: true
    }
).then((con: Connection) => {
    connection = con
    console.log("connectio success", connection);
    con.synchronize();
}).catch((error) => {
    console.error(error);
})


export function getConnection(): Connection {
    return connection;
}
```

This code is within an angular 7 application. So I have used electron remote require. The problem is when i call for getRepository('Parameter') in first launch the synchronize never completes but when refreshed the page from within the electron app it works seamlessly what could be the reason?

**Comment by moganarangan** [comment] 2020-06-04 16:34
I'm also facing the exact issue.
First time load, db connection is not resolved and no further db save/retrieve is not working.
Need fix for this.

**Comment by imnotjames** [comment] 2020-10-05 04:23
There's unfortunately a lot missing here for us to create a reproducible example.  I'll be closing it as I can't really tell if it's a bug report or a question - for questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support).

I'll also include what can help with a reproducible example below - but if you can help us replicate it without knowing everything about this very very specific environment I'm sure we can at least verify if it's an issue with TypeORM or not.

If you DO include a repository or similar for a reproducible example I'll re-open this.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Closed by imnotjames** 2020-10-05 04:23 UTC
