### ISSUE TITLE
Is there a documentation that explain how to implement a repository

### ISSUE THREAD

**Issue by ericmorand** [typeorm/typeorm#7554] opened 2021-04-09 10:54 UTC
Except if I am wrong, there is no documentation explaining how to implement a repository. The only approach explained in the documentation is to delegate creation of a repository to the connection, passing `getRepository` an entity class.

This approach violates the S of the SOLID principles: it forces developer to put repository-related responsibilities into the entity classes. For example, would one want to add a `beforeInsert` logic, which is a repository logic, they would have to put it in the entity class using the `@BeforeInsert` decorator.

If we consider that an entity is an abstraction of a database record, then everything that is not known by the record should not be in the entity classes. It means for example:

* `@Entity`: this decorator expect the name of the table. A record doesn't know the name of the table that holds it; it doesn't even know that it is contained in a table.
* `@BeforeInsert`: a record doesn't know that it can be inserted. It has no knowledge of it lifecycle. It simply exists. What happened to give it birth is outside of its scope.

On the other hand, a record knows that its `name` column is a `varchar` or that its `id` column is its primary identifier and that it is autogenerated. Making `@Column` or `@PrimaryGeneratedColumn` valid entity decorators.

We'd like to use TypeORM in a SOLID way. And thus we need the documentation on how to implement a repository and how to declare those repositories to the connection, instead of using an entity-centric approach.

**Comment by jbjhjm** [comment] 2021-04-09 11:44
haha, we added two issues tackling the same thing almost parallely! 
You can check out my feature request / concept here: https://github.com/typeorm/typeorm/issues/7555
There is support for a custom repository but it's not very nice to use.

All in all I think TypeOrm is missing an approach to specify custom classes / processing globally.

If your required functionality is very simple, it might be sufficient to create a custom decorator (I think this is mostly undocumented) which can specify a value transformation function when reading / writing from/to database. 
Problem with this kind of decorator is however that it is pretty "blind", it does not know anything else but the value to process and I cannot think of a way to make this work with dependencies like in nestJs or even getting access to the entire entity dataset.

**Comment by ericmorand** [comment] 2021-04-09 13:09
How i missed that documentation is beyond me. 😅 

I'll give custom repo a try. And will follow your issue closely.

**Comment by imnotjames** [comment] 2021-07-04 06:02
Duplicate of #7555

**Closed by imnotjames** 2021-07-04 06:02 UTC
Labels: documentation, requires triage
