### ISSUE TITLE
Allow WHERE clause on joined columns.

### ISSUE THREAD

**Issue by Techniv** [typeorm/typeorm#2707] opened 2018-08-24 17:17 UTC
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

Hi!

As it said in the documentation of `FindManyOptions#where`:
> Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined.

It is possible to extend this capability to the joined columns ?

For exemple with 2 entities:
```TypeScript
@Entity()
class Contact {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  name: string;
  @ManyToOne(type => Address)
  address: Address;
}

class Address {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  street: string;
  @Column()
  city: string;
}
```

Make  a request like this:
```TypeScript
contactRepository.find({
  relations: [ 'address' ],
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```

SQL:
```SQL
SELECT `Contact`.`id` AS `Contact_id`
    `Contact`.`id` AS `Contact_id`
    `Contact`.`name` AS `Contact_name`
    `Contact`.`addressId` AS `Contact_addressId`
    `Contact_address`.`id` AS `Contact_address_id`
    `Contact_address`.`street` AS `Contact_address_street`
    `Contact_address`.`city` AS `Contact_address_city`
  FROM `contact` `Contact`
  LEFT JOIN `address` `Contact_address`
    ON `Contact_address`.`id` = `Contact`.`addressId`
  WHERE `Contact_address`.`city` = "Paris";
```

I don't have seen any other options in TypeORM documentation to apply where clauses on joined columns. If there another way I am interested about it.

Thank you in advance for your help.

**Comment by periman2** [comment] 2018-08-29 21:00
@Techniv  

The way I do it is by using query builder like this:

const findContract = await connection
    .getRepository(Contract)
    .createQueryBuilder("contract")
    .innerJoin("contract.address", "address")
    .where("address.city= :city", { city: "Paris" })
    .getOne();

(innerJoin will NOT select the address entity so it will not be available in the contract.address received object, it will only query through the join, if you want to select it also then use leftJoinAndSelect instead of innerJoin)

Let me know if this works for you.

**Comment by Techniv** [comment] 2018-08-30 16:46
Thanks for your help @periman2.
But my needed is to filter result with a deep where clause by the find (or findMany) method in a generic service (model agnostic) where conditions are given from HTTP query parameters.

So, I don't have any doubt about your solution with the query builder, but if  it's possible, I prefer a solution where I don't need to make an ORM over an ORM. XD

I will remember your proposition in last resort. But if we can integrate this feature in TypeORM, it will be cool.

Thank you again.

**Comment by periman2** [comment] 2018-08-31 08:44
@Techniv 

Well the cool thing about query builder is that it's just an object, you can pass it around and mutate it as  you wish. Which means you can build generic methods that populate conditionally "qb.where" and "qb.andWhere" methods to the queryBuilder object suing a requestDto model (which can have a number of filters and whatnot) . You can also extend this with any specific info you want to pass for specific models. That's how I'm actually using it in production.

I do understand the need for having this somehow ready for us in the typeorm functionality though. It would be awesome!

**Comment by ocknamo-bb** [comment] 2018-09-06 01:43
I am also eager for this function! It's cool.

**Comment by Meg4mi** [comment] 2018-09-14 11:26
Same here, this function would be helpful.

**Comment by jun9358** [comment] 2019-02-13 08:51
+1

**Comment by nadrane** [comment] 2019-06-03 18:32
Would the maintainers be willing to accept a PR to implements this functionality? I personally think it's a pretty common use case. I want to avoid to dropping down to the query builder because it's verbose and isn't type-safe (unless perhaps it can be and I'm missing something?).

**Comment by Calamitizer** [comment] 2019-06-17 15:57
I'm also strongly in support of this feature. I've developed an entire API using `find`, declaratively, instead of a query builder, only to find out that this extremely common use case is mysteriously absent.

I think it's important to recognize that different developers have different styles & are optimizing for different things when they choose one or the other. These are the reasons I prefer not to use query builders (in descending order of importance, why not):

A) It is _extremely_ clunky & illegible to use in functional, declarative programming. My team's _entire webapp_ is written functionally.
B) It's not (as) type-safe. Locking this down is extremely important to me, especially in such an intrinsically type-unsafe process as DB record-fetching.
C) It really can be quite verbose.

Here's an example of query builder used functionally, with just three query parameters compared by basic equals.

```typescript
  private getRecordsByQueryParams = async (queryParams: QueryParams) =>
    Object.keys(queryParams)
      .reduce((qb, param, i) => {
        const queryClause = `${User.ALIAS}.${param} = :${param}`;
        const value = { [param]: queryParams[param] };

        return i === 0
          ? qb.where(queryClause, value)
          : qb.andWhere(queryClause, value);
      }, (await connection).getRepository(User).createQueryBuilder(User.ALIAS))
      .getMany();
```

Here's an actual API node from our app, with ten query parameters:

```typescript
  private createQueryConditions = async ({
    id,
    type,
    name,
    geo,
    segment,
    industry,
    startIndex,
    stopIndex,
    stage,
    moment,
  }: QProps): Promise<FindManyOptions<AccountRecord>> => ({
    where: {
      ...(id === undefined ? {} : { id }),
      ...(type === undefined ? {} : { id: In(await this.getIdsForType(type)) }),
      ...(name === undefined ? {} : { name }),
      ...(geo === undefined ? {} : { geo }),
      ...(segment === undefined ? {} : { segment }),
      ...(industry === undefined ? {} : { industry }),

      ...(stage === undefined && moment === undefined
        ? {}
        : this.createMomentCondition({ stage, moment })),
    },

    ...this.createSliceConditions({ startIndex, stopIndex }),
  });
```

Can you imagine trying to cram the (relatively simple!) conditional logic into the reducer callback, conditioning on the value of `param`? This is really the issue that comes up with method-chaining APIs -- when you need to conditionally call-or-not-call one of those methods. Like d3, which someone reaaally needs to rewrite for modern web.

**Comment by Calamitizer** [comment] 2019-06-17 18:41
Update: I did find a work-around for the issue in question here, although it's really hacky. I had the idea to use the `Raw` find operator to run an arbitrary query, e.g.

```typescript
const condition: FindManyOptions<ParentRecord>  = {
  where: {
    child: Raw(() => `SUBSTRING_INDEX(SUBSTRING_INDEX(${fieldName}, ',', ${i}), ',', -1) = ${moment}`),
  },
};
```

Here, `fieldName` is the name in the join table for the child entity field you want to query on (you can see this by enabling logging and checking the query). But of course, this relies on using the field name directly, which is quite brittle since TypeOrm has its own dynamic naming system. Also, since `child` was a joined field, it turns out TypeOrm straight-up ignored it, so I had to add a dummy field to the parent entity like so:

```typescript
  @Column({
    type: boolean,
    nullable: true,
    select: false,
  })
  dummyField!: null;
```

This is inelegant and error-prone... but it's the only timely alternative to rewriting large chunks of our API.

**Comment by Blacate** [comment] 2019-09-02 08:25
+1

**Comment by vytautas-pranskunas-** [comment] 2019-09-26 06:02
+1

**Comment by saudar82** [comment] 2019-10-07 08:12
+1

**Comment by jd1386** [comment] 2020-01-15 08:24
+1

**Comment by m4kamran** [comment] 2020-01-20 09:58
+1

**Comment by LarsBekhof** [comment] 2020-02-19 16:14
+1

**Comment by mehtamanan** [comment] 2020-03-09 00:10
+1

**Comment by f1mp3r** [comment] 2020-04-10 00:23
Since this is an essential feature, as many people here agree, if I (or someone else) submit a PR, will it be accepted?

**Comment by avin-kavish** [comment] 2020-04-11 08:01
@pleerock please accept

**Comment by leandrodeveng** [comment] 2020-05-05 15:31
+1

**Comment by ganshiqingyuan** [comment] 2020-05-11 16:20
+1

**Comment by glennreyes** [comment] 2020-05-12 12:16
I was just looking at the docs for this, and as a non-sql/orm expert I would find it super helpful if there was at least following:

- A note in the docs that this is currently not supported
- A TS hint that putting joined columns into the where clause.

Instead, I assumed it's supported, because of false positives TS not complaining about it. /cc @pleerock.

> Since this is an essential feature, as many people here agree, if I (or someone else) submit a PR, will it be accepted?

@f1mp3r PRs are always welcomed, feel free to open one. It likely depends on the tradeoffs the PR would introduce wether it will accepted or not.

Anyway, this project is awesome, thanks for the great work of all maintainers & contributors! ❤️

**Comment by felipeseolin** [comment] 2020-06-29 00:36
:+1:

**Comment by felipeseolin** [comment] 2020-06-29 00:36
+1

**Comment by zaro** [comment] 2020-07-27 10:38
The lack of where conditions on relations , greatly diminishes the usefulness of `find` IMO

**Comment by artz** [comment] 2020-08-28 20:10
If it's any motivation to knock this feature out, Sequelize has this. 😁

**Comment by Yasukity** [comment] 2020-10-08 08:55
+1

**Comment by takamukut** [comment] 2020-10-08 08:55
+1

**Comment by makoll** [comment] 2020-10-09 03:12
+1

**Comment by imnotjames** [comment] 2020-10-15 18:01
Per the original request - you missed `@Entity()` on your address but I created a test case:

```typescript
        const addressRepository = connection.getRepository(Address);
        const contactRepository = connection.getRepository(Contact);

        const paris = await addressRepository.save({ city: 'Paris' });
        const london = await addressRepository.save({ city: 'London' });

        await contactRepository.save({ name: "Foo", address: paris });
        await contactRepository.save({ name: "bar", address: paris });
        await contactRepository.save({ name: "Tea", address: london });

        const result = await contactRepository.find({
            relations: [ 'address' ],
            where: {
                address: {
                    city: 'Paris'
                }
            }
        });
        expect(result.length).to.be.equal(2);
```

This returns the results:

```
[
  Contact {
    id: 1,
    name: 'Foo',
    address: Address { id: 1, city: 'Paris' }
  },
  Contact {
    id: 2,
    name: 'bar',
    address: Address { id: 1, city: 'Paris' }
  }
]
```

So I'm pretty sure this is actually implemented and has been for a while.

I'll be closing this issue, but please correct me if I'm misunderstanding and there's other requested features here that I don't understand.

---

Side note:

I'm not sure I understand why everyone is writing `+1` to this - that's not helpful and just fills up the comments with cruft.  If you want this done, either open a PR with info, add a :+1: to reaction, or add a MEANINGFUL COMMENT that adds to the conversation.

**Comment by imnotjames** [comment] 2020-10-15 21:58
PS if anyone disagrees please comment with a reproducible example which shows that it's not working so I can reopen the issue.

**Comment by tchak** [comment] 2020-10-16 13:22
It is not working for me. I am using a `ManyToMany` relation.

I tried with both `relations` and `join` options. I am getting `EntityColumnNotFound: No entity column \"users\" was found.` error in both cases.

```ts
@Entity()
export class Document {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToMany(() => User, ({ documents }) => documents)
  users!: User[];
}

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToMany(() => Document, ({ users }) => users)
  @JoinTable()
  documents!: Document[];
}

await documentRepository.find({
  relations: ['users'],
  where: {
    users: {
      id: '1'
    }
  }
});

await documentRepository.find({
  join: {
    alias: 'document',
    leftJoin: {
      'document.users': 'users',
    }
  },
  where: {
    users: {
      id: '1'
    }
  }
});
```

**Comment by ldiego08** [comment] 2020-10-16 13:40
Also not working for me with the same error as @tchak. TypeORM seems to try to look for a column rather than going into the relationship.

@imnotjames can you provide an exact example of how should this be used? Or when you say [here](https://github.com/typeorm/typeorm/issues/3902#issuecomment-709608808) that this is working, do you mean using the query builder or in a specific version of the library? What code did you use to test this?

**Comment by imnotjames** [comment] 2020-10-16 13:48
In my comment above in this issue I have an example that I included that matches the example included in the first comment - along with the results.

**Comment by imnotjames** [comment] 2020-10-16 14:17
Wonderful, replicated with that example.

**Comment by ggaabe** [comment] 2020-10-30 06:22
So is this on track for getting fixed and implemented anytime soon?

**Comment by etomanon** [comment] 2020-11-11 15:34
@imnotjames 
When I change the string ('Paris') to a find options operator then it does not work:
Error: column was not found in the entity
```
import { IsNull, Not } from 'typeorm'

 relations: [ 'address' ],
  where: {
    address: {
      city: Not(IsNull())
      }
    }
```

**Comment by victiondev** [comment] 2020-11-12 16:37
Is there any update on this?

**Comment by ngoding** [comment] 2020-11-15 15:06
Hey found a solution, not sure if it's best practice. But it works for me.
```
contactRepository.find({
  relations: [ 'address' ],
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```
Change it to:
```
contactRepository.find({
  relations: [ 'address' ],
  where: qb => {
    qb.where('Contact__address.city = :city', {city: 'Paris'})
  }
});
```

**Comment by ldiego08** [comment] 2020-11-15 15:43
@ngoding having to resource to that kind of syntax washes off all the elegance off the find options alternative. I rather use the regular query builder. At least, things would be consistent that way. 😅

**Comment by ngoding** [comment] 2020-11-15 15:51
@ldiego08 Yeah agreed. For my case I was using findAndCount, just want to keep it short. 😄

**Comment by chinanderm** [comment] 2020-11-24 04:27
> Hey, just found a solution. Not sure if it's best practice, but it works for me.
> 
> ```
> contactRepository.find({
>   relations: [ 'address' ],
>   where: {
>     address: {
>       city: 'Paris'
>     }
>   }
> });
> ```
> 
> Change it to:
> 
> ```
> contactRepository.find({
>   relations: [ 'address' ],
>   where: qb => {
>     qb.where('Contact__address.city = :city', {city: 'Paris'})
>   }
> });
> ```

Thanks for this interim solution! Solved my problem. Looking forward to the bug fix.

**Comment by nebkat** [comment] 2020-11-25 00:39
I'd like to implement this but we should probably discuss a more robust proposal first. Here are some questions remaining (and some of my proposed answers):

### Important
**1. Manual/non-relation/sub-query joins: Should there be a mechanism for adding conditions on joins that are not relations?**
Selected relations are converted to joins in the background so currently its just a convenience function in `EntityManager.find()`, but how would the where object refer to a manual/non-relation/sub-query join?

If it is a `joinAndMap` the mapped property could be used, but that seems unnecessary for non-selected joins. Without the property however, there will be a typing issue for `find()`. Using the alias somehow could work but I think the alias should really be kept away from the ORM side of things (ideally it would be computed automatically for all joins).

Perhaps one solution would be to add an extra `where` parameter to `QueryBuilder.join()`, which would solve the typing issue, but then is this any different to just using the `ON` condition with an inner join? Is it then missing the point entirely?

Alternatively we could restrict to real relations only.

**2. Unjoined relations: What should happen if a relation is referenced in the where object but is not joined?**
The logical first step for this would be to make the where parameters be computed at the final step before execution, rather than as soon as they are added, so there is a chance to add the join later. But what if it is never added?*

Should we _a)_ throw an error, _b)_ do a non selecting join on the relation automatically or _c)_ ignore this clause altogether (unless it is an ID only and we have the foreign key columns)?

**3. Find operators: How should find operators act on relation conditions?**
```typescript
qb.where({
    address: In(
        {city: 'Paris'}, {'city: 'Amsterdam'}
    )
})
```
`In` really shouldn't be used here, it's more of an `OR` condition, but technically it makes sense. I know there have been some other issues about `OR` since `Brackets` really isn't the optimal solution but this may just complicate it further. If an array is provided to `qb.where()` all the options are ORed, so should this be the special case if an array is used on a relation property?

This question can actually be extended to embedded columns as well, as it should all feel consistent.

### Less Important
**4. Non-metadata wheres: What is the behavior when `QueryBuilder` is used without entity metadata?**
Currently if there is no metadata tied to the query builder and a where object is passed the keys of the object are just treated as columns. We can't do much about that since we have no info about relations, but there should still be an elegant way to apply conditions to joined columns.

If we use aliases, how do we differentiate between an alias and a column on the object? If we don't use aliases, should whatever alternative is chosen be the preferred method even when metadata is available?

Personally I think the non-metadata queries have caused a lot of unnecessary complication to the query builders and would be better off having their own simpler system (or even use an external library for query building?), but that is a discussion for another day. Until then, this problem remains.

**5. One-to-many/many-to-many relations: What should the default behavior be?**
When there are multiple joined rows per source row, we will simply filter away the joined rows that do not match? Is there a situation where we don't want to join multiple rows, but rather filter the source row by the existence of _some_ matching join row?

These queries are complicated enough as is... the two approaches are running multiple queries or grouping results to aggregate the joined relation into an array, neither of which is pretty.

**6. Nested relations: What happens when there is a condition on a nested relation?**
Are there special considerations needed here? All parent relations presumably must be joined?

**7. Custom relation joins: What happen if a relation is joined differently than designed for a specific query?**
Standard relation joining is done using the join columns only, is there something we should be careful of if the user intentionally performs a join of a relation column using different join direction or conditions or something strange like that? It probably doesn't matter, and I'm not sure why it would ever be done, but the possibility exists anyway.

This question does slightly bring back to the idea proposed in question 1, which is to have an additional `where` parameter to `QueryBuilder.join()`. Then if the user decides to do a strange relation join, the where conditions are set right there and there is no overlap with the "standard" relation join.

We could add a `QueryBuilder.relation()` method which guarantees the relation is joined using the "standard" method, and is assigned the appropriate alias for filtering from the overall `where` object.

### Observations

**8. Relation IDs: What should happen if a relation object is provided that includes the primary keys?**
```typescript
qb.where({
    address: {
        id: 1,
        city: Not('Paris')
    }
});
```
For performance we should definitely short circuit `address.id` to `addressId` in the main entity if it is already present as a foreign key, but we must then still join for the sake of checking that `address.city` is not "Paris"?

**9. Relation IDs: What should happen if an ID value is passed?**
If `address: 1` is passed then we should act like `EntityManager.update()` and treat it as an ID of `Address`? Composite keys would be dealt with by the previous question. If manual/non-relation/sub-query joins are allowed, what happens?

---

Most of these questions probably have some obvious answer but perhaps someone could put together a more concrete spec so we know what to aim for? If you have any input or examples feel free to add them.

_As always, I share the frustration about the slow progress but please avoid spam comments so we can keep the discussion centered around the issue itself. When `@pleerock` and `@imnotjames` do eventually review we can have some useful information here._

**Comment by victiondev** [comment] 2020-12-16 14:51
Is this going anywhere yet??

**Comment by mickaelmesdocteurs** [comment] 2020-12-18 10:34
As I'm really waiting for this feature, I'm gonna try to answer to some of @nebkat questions.
For all code snippet in this answer, I'll use the initial data models defined by @Techniv

## Recap
We are talking about improving the synthetical 'find' function in order to allow where conditions on related data.

##### Things that WORKS

1. Using the QueryBuilder
```js
contactRepository
  .createQueryBuilder()
  .leftJoin('Address', 'address')
  .where('address.city = :city', { city: 'Paris' })
  .get();
```

2. Using the QueryBuilder
```js
contactRepository.find({
  relations: ['address'],
  where: qb => {
    qb.where('Contact__address.city = :city', { city: 'Paris'})
  }
});
```

##### Things that DOESN'T work

```js
contactRepository.find({
  relations: ['address'],
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```

#### 1. Manual/non-relation/sub-query joins: Should there be a mechanism for adding conditions on joins that are not relations?

##### Example
```js
addressRepository.find({
  relations: ['contacts'],
  where: {
    contacts: {
      name: 'John Doe'
    }
  }
});
```

##### Expected Behaviour
As `Address` definition does not contains any information about `Contact`, I think the above statement should raise an error.
Where conditions on relations should throw an error if the relation is not defined.

##### Workaround
To make the above query to work, we should define the bi-directionnal relation as below :

```js
@Entity()
class Contact {
  ...
  @ManyToOne(() => Address)
  address: Address;
}

@Entity()
class Address {
  ...
  @OneToMany(() => Contact, contact => contact.address )
  contacts: Contact[];
}
```
For all other manual/non-relation joins, I think it should just raised an error.


#### 2. Unjoined relations: What should happen if a relation is referenced in the where object but is not joined?

##### Example
```js
contactRepository.find({
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```

##### Expected Behaviour
I think this should produce something like 
```sql
SELECT * FROM contact c 
WHERE address.city = 'Paris'
```
So it will throw an error.
Join/relation should be defined each time we want to add condition on relations. Otherwise, it should throw an error.
User has to specify the relations (`relations: ['address']` or `join: { alias: 'contact', innerJoin: { address: 'contact.address' } },` or ...)




#### 3. Find operators: How should find operators act on relation conditions?

Not sure to fully understand this one. 
But I would have write it this way :
```js
// join/relation is already specified somewhere
qb.where({
  address: In(
    { city: 'Paris' },
    { city: 'Amsterdam' }
  )
})
```

Ideally, it should produce :
```sql
SELECT * FROM contact c
INNER JOIN address a ON a.id = c.addressId
WHERE a.city IN ('Paris', 'Amsterdam')
```

If we take a more advanced example :

```js
// Looking for any contacts of specific country's president
// all join/relation are already specified somewhere
qb.where({
  address: In(
    {
      country: {
        president: {
          name: 'John Doe'
        }
      }
    },
    {
      country: {
        president: {
          name: 'Jane Doe'
        }
      }
    }
  )
})
```
```sql
SELECT * FROM contact c
INNER JOIN address a ON a.id = c.addressId
INNER JOIN country coun ON coun.id = a.countryId
INNER JOIN president p ON p.id = coun.presidentId
WHERE p.name IN ('Jane Doe', 'John Doe')
```

But as this syntax is quite awful, maybe we could restrict operators to final property and throw error otherwise.
Example:
```js
// Looking for any contacts of specific country's president
// all joins/relations are already specified somewhere
qb.where({
  address: {
    country: {
      president: {
        name: In('Jane Doe', 'John Doe')
      }
    }
  }
})
```
I don't see any case which the first syntax is required.

#### 4. Non-metadata wheres: What is the behavior when QueryBuilder is used without entity metadata?

#### 5. One-to-many/many-to-many relations: What should the default behavior be?


#### 6. Nested relations: What happens when there is a condition on a nested relation?

(see point 2 & 3)

#### 7. Custom relation joins: What happen if a relation is joined differently than designed for a specific query?

#### 8. Relation IDs: What should happen if a relation object is provided that includes the primary keys?

##### Example
```js
// join/relation is already specified somewhere
qb.where({
  address: {
    id: 1,
    city: Not('Paris')
  }
});
```

##### Expected Behaviour
This is an AND condition, so it should produce something like :
```sql
SELECT * FROM contact c
INNER JOIN address a ON a.id = c.addressId
WHERE a.id = 1 AND city <> 'Paris'
```

---
Please feel free to complete this answer.
I hope this feature will be implemented soon.

**Comment by FottyM** [comment] 2021-01-01 02:13
@mickaelmesdocteurs I think you meant to say `Using the Repository` in

**Comment by jameskuizon1315** [comment] 2021-01-18 09:34
Has anyone fix or implemented this already? Thank you.

**Comment by mimof9** [comment] 2021-01-28 07:33
> Hey, just found a solution. Not sure if it's best practice, but it works for me.
> 
> ```
> contactRepository.find({
>   relations: [ 'address' ],
>   where: {
>     address: {
>       city: 'Paris'
>     }
>   }
> });
> ```
> 
> Change it to:
> 
> ```
> contactRepository.find({
>   relations: [ 'address' ],
>   where: qb => {
>     qb.where('Contact__address.city = :city', {city: 'Paris'})
>   }
> });
> ```

this looks the same as QueryBuilder

**Comment by mateussilva92** [comment] 2021-01-28 23:55
I do agree with the points provided by @mickaelmesdocteurs, but since this is a big feature I think we should get the involvement of @pleerock so we can get it right the first time.

I'm also open to help on the development of the feature if you guys need some more hands and brains.

**Comment by rpunjwnaixcute** [comment] 2021-02-22 08:44
> contactRepository.find({
>   relations: [ 'address' ],
>   where: qb => {
>     qb.where('Contact__address.city = :city', {city: 'Paris'})
>   }
> });

I'm getting an error using this one in typescript

> Parameter 'qb' implicitly has an 'any' type.

**Comment by micalevisk** [comment] 2021-02-22 16:05
@rpunjwnaixcute to fix that you have to explicity type `qb` parameter as `WhereExpression` (an _interface_ from `typeorm`)

**Comment by VarunAnandK** [comment] 2021-03-26 04:50
User parent_table__joined_table   
account.find({ where: `account.company_id = ${request.headers["companyid"]} AND account__account_sub_type.is_payment_account = 1`,relations: ['account_sub_type', 'currency'] });

**Comment by phil294** [comment] 2021-04-06 03:41
@mickaelmesdocteurs @mtwzim
> #### 5. One-to-many/many-to-many relations: What should the default behavior be?
> ##### Expected Behaviour
> Simply filter away the joined rows that do not match should be good.
> It will returns multiple addresses for every matching contact name
> 
> ```sql
> SELECT * FROM address a
> INNER JOIN contact c ON a.id = c.addressId
> WHERE c.name = 'John'
> ```
> 
> If we need to filter the source row by the existence of some matching join row, we can use `GroupBy` / `Having` or `Distinct` statement.

I am not so sure about that behavior. With FindOperators, this might be counter-intuitive. Consider this example:

```js
@Entity()
class Address {
  @OneToMany(() => Contact, contact => contact.address )
  contacts: Contact[];
}

// Saved:
// homeAdress = new Adress(...);
// john = new Contact({ name: 'John', adress: homeAdress })
// clara = new Contact({ name: 'Clara', adress: homeAdress })

addressRepository.find({
  relations: ['contacts'],
  where: {
    contacts: {
      name: In([ 'John' ])
    }
  }
});
```
With the current proposal, implemented in the open PR, this will return:
```js
[ Adress {
    contacts: [ john ]
} ]
```
The problem: Clara is missing, but we didn't exclude her. From the find query, I would expect the `contacts` array to be complete. In MongoDB for example, this is different: The whole entity is returned (IIRC).

I don't really have a better solution to this, specially given that with QueryBuilder, the situation is already the same. So it is probably best to go with it. But keep in mind, with `.find({})`, `GROUP BY` is not available to solve this. And if you are interesting in actually return all contacts with the same query, group by doesn't help either, you'd need a subquery.

**Comment by mtwzim** [comment] 2021-04-06 11:00
> not so sure about that behavior. With FindOperators, this might be counter-intuitive. Consider this exam

Hey, as I didn't quite understand, could you tell me what the expected query would be and the expected result to behave correctly when using Find operators?

Thanks!

**Comment by phil294** [comment] 2021-04-06 15:30
> Hey, as I didn't quite understand, could you tell me what the expected query would be and the expected result to behave correctly when using Find operators?
@mtwzim
1. Take [this example from MongoDB](https://mongoplayground.net/p/mYLpFX-MBSo) (click "run"). We filter for `"contacts.name": "John"`, but the returned adress **includes John *and* Clara**.
2. With TypeORM (SQL), you would do
    ```js
    addressRepository.find({
    relations: ['contacts'],
    where: {
        contacts: {
        name: In([ 'John' ])
        }
    }
    });
    ```
    but the result is
    ```js
    [{
        "id": 1,
        "contacts": [{
            "id": 10,
            "name": "John"
        }]
    }]
    ```
    **only John**

They are different. As a TypeORM user, I would be confused by **2.** But this is just my opinion, please do not change your pull request because of it.
I hope you can understand me now, sorry if I was not clear enough in my first post.

**Comment by mtwzim** [comment] 2021-04-06 23:02
> > Hey, as I didn't quite understand, could you tell me what the expected query would be and the expected result to behave correctly when using Find operators?
> > @mtwzim
> 
> 1. Take [this example from MongoDB](https://mongoplayground.net/p/mYLpFX-MBSo) (click "run"). We filter for `"contacts.name": "John"`, but the returned adress **includes John _and_ Clara**.
> 2. With TypeORM (SQL), you would do
>    ```js
>    addressRepository.find({
>    relations: ['contacts'],
>    where: {
>        contacts: {
>        name: In([ 'John' ])
>        }
>    }
>    });
>    ```
>    
>    
>    but the result is
>    ```js
>    [{
>        "id": 1,
>        "contacts": [{
>            "id": 10,
>            "name": "John"
>        }]
>    }]
>    ```
>    
>    
>    **only John**
> 
> They are different. As a TypeORM user, I would be confused by **2.** But this is just my opinion, please do not change your pull request because of it.
> I hope you can understand me now, sorry if I was not clear enough in my first post.

Now I get it! I wonder if I should do something about it or not. Somebody else ?

**Comment by beem812** [comment] 2021-04-30 18:55
Would it be possible to leverage the relations prop to do the filtering of related entities?

`
relations: [
    {
        name: 'contacts',
        where: <whatever>
    }
]
`

On one hand it's clear that you're filtering relations, on the other hand it's not the greatest that the `where` functionality is now in multiple places.

**Comment by indieocean** [comment] 2021-06-02 19:29
> Would it be possible to leverage the relations prop to do the filtering of related entities?
> 
> `relations: [ { name: 'contacts', where: <whatever> } ]`
> 
> On one hand it's clear that you're filtering relations, on the other hand it's not the greatest that the `where` functionality is now in multiple places.

Don't know if I like that since if you where to do conditionals andWhere etc.. it could turn ugly.

**Comment by salvationarinze** [comment] 2021-06-23 16:01
Any solution to this yet?

**Comment by akirawinz** [comment] 2021-06-26 03:49
I got a problem like this but my query can use where in relation only id field here is my stackoverflow link : https://stackoverflow.com/questions/68139035/typeorm-search-in-relation-without-using-query-builder-nodejs

**Comment by imnotjames** [comment] 2021-06-27 17:20
> Would it be possible to leverage the relations prop to do the filtering of related entities?
> 
> `relations: [ { name: 'contacts', where: <whatever> } ]`
> 
> On one hand it's clear that you're filtering relations, on the other hand it's not the greatest that the `where` functionality is now in multiple places.

I'd much prefer it to stay in the where section.  You can't have two properties on an entity with the same name so there's no overlap, thus no need for this to live elsewhere.

I also agree that the current query that's being generated is not quite correct.  We should be using some sort of existence check instead of direct `where` clauses.

However, that's one step beyond just getting the dang thing to work, don't you think?

With the way we're doing `WHERE` expressions iteratively in the builder - eg, compiling them as you do `.where()` instead of at the end, it becomes much harder to build a more correct query.

I'll try to take a second pass on my PR to implement something more correct, but I don't want to make perfect the enemy of good enough, y'know?

Perhaps I can add explicit errors to be thrown in the case where we'd be generating an incorrect query?

**Closed** 2021-07-03 18:29 UTC
Labels: comp: find options, comp: query builder, new feature

**Comment by Saniol** [comment] 2021-07-22 07:57
@imnotjames to sum up - case described in feature request is handled, but it doesn't work when we have `*-to-many` relations? 

It would be really useful if current limitations would be documented in https://typeorm.io/#/find-options . It's really frustrating when you need to go through a long discussion under github issue to understand, when option mentioned in docs would work and when it won't.

**Comment by vydayko** [comment] 2021-09-30 07:50
It's still doesn't work with @ManyToOne
I am not getting the error, but I am not getting the correct data either.

`const [nodes, totalCount] = await this.repo.findAndCount({
      where: filter,
      skip: offset,
      take: limit,
    });`
    
 filter = `filter: { enabled: { is: false }, rulesId: {in: [888, 999, 777]} }`

**Comment by wiatrM** [comment] 2021-10-21 08:31
@imnotjames you stated that you will open PR to complete -to-many cases. Is it already opened? 
How can we help here or we need to do it?

**Comment by matigarowel** [comment] 2021-11-22 08:24
Still not working at 0.2.41

@Entity({name: 'Access', schema: 'Users' })
@Unique(['ApplicationRoute', 'UserAccount'])
export class UserAccessEntity {
  @PrimaryGeneratedColumn()
  Id: number;

  @ManyToOne(() => ApplicationRouteEntity, e => e.UserAccess)
  @JoinColumn({ name: 'ApplicationRoute'})
  @IsInt()
  ApplicationRoute: ApplicationRouteEntity;
  
  @ManyToOne(() => UserAccountEntity, e => e.UserAccess)
  @JoinColumn({ name: 'UserAccount'})
  @IsInt()
  UserAccount: UserAccountEntity;
}

@Entity({name: 'Route', schema: 'Application' })
@Unique(['Parent','Sequence'])
export class ApplicationRouteEntity {
  @PrimaryGeneratedColumn()
  Id: number;

  @OneToMany(() => UserAccessEntity, e => e.ApplicationRoute)
  @JoinColumn({ name: 'UserAccess'})
  @IsInt()
  UserAccess: UserAccessEntity[];
}

const entrys = await this.baseRepository.find({
      relations: ["UserAccess"],
      where: { 
            "UserAccess": {  "UserAccount": 1  }
      }
    })
    
    error: Cannot query across one-to-many for property UserAccess

**Comment by WongYueKeung** [comment] 2021-12-02 10:05
> Any updates to add the same functionality to a `one-to-many`/`many-to-one`/`many-to-many` case? It is really frustrating just getting a `Error: Cannot query across one-to-many for property testProp`

For those people who really want this feature there is a temporary way to do it
(i am not sure if it would cause any bad conseuqnse)
just comment out the /node_modules/typeorm/query-builder/QueryBuilder.js  Line:881
like this  //throw new Error("Cannot query across " + relation.relationType + " for property " + path);
there is also a comment explain to us why it stopping us to do it:
 // There's also cases where we don't want to return back all of the properties.
                // These handles the situation where someone passes the model & we don't need to make
                // a HUGE `where` to uniquely look up the entity.
                // In the case of a *-to-one, there's only ever one possible entity on the other side
                // so if the join columns are all defined we can return just the relation itself
                // because it will fetch only the join columns and do the lookup.

it seems working and no side effect was found yet, now I can fillter the relations in one-to-one and many-to-many query

**Comment by PetrShchukin** [comment] 2022-04-22 14:08
I have the same issue but with "OneToMany" when I try to access sub-relation fields.
Let's say I have Persons -> Addresses -> Cities tables.
This code doesn't work
```
const sections = await this.personsRepository.find({
  relations: ['addresses', 'addresses.cities'],
  where: {
    address: { city: { name: 'My City' } },
  },
});
```
In logs I can see it uses "Persons__addresses"."name" instead of `"Persons__addresses__cities"."name"`

**Comment by vixson** [comment] 2022-10-24 07:26
> Any updates to add the same functionality to a `one-to-many`/`many-to-one`/`many-to-many` case? It is really frustrating just getting a `Error: Cannot query across one-to-many for property testProp`

Please in what case are you having this error?
Because this mainly occurs when trying to update a deeply related entity via `update` method.
**Solution**: Use `save` method instead and use the `id` as the updated condition. viola your issues would be solved

**Comment by AndreiSoroka** [comment] 2024-03-20 11:06
I didn't find in the documentation some info. Yesterday I lost the evening to find the solution how make ManyToOne like one of the Primary key.

Thanks for this topic, it is my solution:
```ts
@Entity({ name: "skipped_words" })
export class SkippedWordEntity {
  @ManyToOne(() => UserEntity, (user) => user.id)
  @JoinColumn([
    {
      name: "userId",
      referencedColumnName: "id",
      foreignKeyConstraintName: "FK_skipped_words_user",
    },
  ])
  @PrimaryColumn({
    name: "userId",
    type: "text",
    primaryKeyConstraintName: "PK_skipped_words",
  })
  user!: string;

  @PrimaryColumn({
    type: "varchar",
    primaryKeyConstraintName: "PK_skipped_words",
  })
  word!: string;

  @PrimaryColumn({
    type: "varchar",
    length: 2,
    primaryKeyConstraintName: "PK_skipped_words",
  })
  language!: string;
}
```

But unexpectable, why I don't find it in documentation? It is a part of base functinonality

**Comment by cornzz** [comment] 2024-10-21 16:11
Came here from https://github.com/typeorm/typeorm/issues/4396, any updates?

**Comment by minikdev** [comment] 2024-11-20 23:08
why is this closed? the issue persists. It's almost 2025 guys...

**Comment by LucusWebsites** [comment] 2024-12-17 08:30
Same, I bumped into this issue as well today.
Allowing a where on joining relations would be very helpful in my case.

**Comment by samueljmacedo** [comment] 2025-02-05 11:14
Leaving this comment here to bring attention to this again. Came from https://github.com/typeorm/typeorm/issues/4396 as well.
