### ISSUE TITLE
ManyToMany relation : Cannot read property 'joinColumnName' of undefined

### ISSUE THREAD

**Issue by GreGosPhaTos** [typeorm/typeorm#163] opened 2016-12-31 16:57 UTC
Here are my entities : 

```js
@Table("games")
@Index("name_idx", ["name"], { unique: true })
export class Game {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 80
    })
    name: string;

    @Column({
        name: "search_terms",
        length: 80
    })
    searchTerms: string;

    @Column({
        name: "reviewed"
    })
    isReviewed: boolean;

    @ManyToMany(type => Platform, platform => platform.games, {
        cascadeInsert: true, // allow to insert a new platform on game save
        cascadeUpdate: true, // allow to update a platform on game save
        cascadeRemove: true  // allow to remove a platform on game remove
    })
    @JoinTable()
    platforms: Platform[] = [];
}
```

```js
@Table("platforms")
@Index("name_idx", ["name"], { unique: true })
export class Platform {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 100
    })
    name: string;

    @Column({
        length: 100
    })
    slug: string;

    @ManyToMany(type => Game, game => game.platforms, {
        cascadeInsert: true, // allow to insert a new game on platform save
        cascadeUpdate: true, // allow to update an game on platform save
        cascadeRemove: true  // allow to remove an game on platform remove
    })
    games: Game[] = [];
}
```

And my persisting layer as follow : 

```js
// games is an array of fresh games entities
return aService.retreiveGames().then((games: Array<Game>) => {
                App.ORMConnection().then(async connection => {
                    await connection.getRepository(Game).persist(games).catch(
                        error => console.log("Persist failed : ", error)
                    );
                });
            });
```

And I have this error : 

```
Persist failed : TypeError: Cannot read property 'joinColumnName' of undefined
    at SubjectBuilder.<anonymous> (/code/node_modules/typeorm/persistence/SubjectBuilder.js:505:213)
    at step (/code/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/code/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
    at /code/node_modules/typeorm/persistence/SubjectBuilder.js:7:65
    at __awaiter (/code/node_modules/typeorm/persistence/SubjectBuilder.js:3:12)
    at /code/node_modules/typeorm/persistence/SubjectBuilder.js:337:96
    at Array.map (native)
    at SubjectBuilder.<anonymous> (/code/node_modules/typeorm/persistence/SubjectBuilder.js:337:63)
    at step (/code/node_modules/typeorm/persistence/SubjectBuilder.js:32:23)
    at Object.next (/code/node_modules/typeorm/persistence/SubjectBuilder.js:13:53)
```

Did I miss something ?

**Comment by pleerock** [comment] 2017-01-02 13:17
Please a provide a minimal reproduction code. You have provided entities and I can use them, however you didnt provide the code which creates a basic entities and saves them. Code you provided in "persisting layer" is abstract and does not show what you are saving. I need that to reproduce your issue.

**Comment by errorx666** [comment] 2017-01-03 18:24
My `ManyToMany` decorator was missing the second parameter on one side.  My mistake, but I would expect this to throw a much less cryptic error, and sooner.

**Comment by GreGosPhaTos** [comment] 2017-01-04 01:16
OK here is how the game arrays is built (in the example below ) : 

```js
     let games: Array<Game> = [];
     let platform: Platform = new Platform();
     platform.name = "ps4";
     $('table#softwarelist tr td>i').each(function() {
         const name = $(this).text();
         let game = new Game();
         game.name = name;
         game.searchTerms = name;
         game.platforms.push(platform);
         games.push(game);
    });
    // Resolve Promise here
    resolve(games);
```

**Comment by GreGosPhaTos** [comment] 2017-01-04 02:21
OK, thanks for your help! I won't copy all my code but I think those parts will be significant : 

I changed my persisting layer to be more understandable 
```js
App.ORMConnection().then(connection => {
                            connection.getRepository(Platform).findOne({
                                slug: "myPlatformSlug"
                            }).then((platform: Platform) => {
                                // $ is cheerio (html parser) dependency assume this returns a list of names
                                $('table#softwarelist tr td>i').each(function() {
                                    const name = $(this).text();
                                    let game = new Game();
                                    game.name = name;
                                    game.searchTerms = name;
                                    game.platforms.push(platform);
                                    
                                    let repo = connection.getRepository(Game);
                                    repo.persist(game).catch(error => console.log(error));
                                });
                            });
                        });
```

And the app.ts : 

```js
let cacheObjects: Array<any> = [];
export const App = {

    // DB Connection
    ORMConnection: (): Promise<any> => {
        cacheObjects['ORMConnection'] = cacheObjects['ORMConnection'] || createConnection({
            driver: {
                type: "mysql",
                host: Config.mysql.host,
                port: Config.mysql.port,
                username: Config.mysql.user,
                password: Config.mysql.password,
                database: Config.mysql.database
            },
            entities: [
                __dirname + "/entity/*.js"
            ],
            migrations: [
                __dirname + "/dbmigrations/*.js"
            ],
            cli: {
                migrationsDir: __dirname + "/dbmigrations"
            },
            autoSchemaSync: true
        }).catch(error => winston.log("error", error));

        return cacheObjects['ORMConnection'];
    }
};

```

I just removed the cascadeRemove from my entities, now I don't have the error anymore, but it doesn't save the relations, I randomly have only 3,5 or 10 rows on my join table instead of having all of them (means the same number as the game rows).

**Comment by GreGosPhaTos** [comment] 2017-01-06 19:15
@pleerock any suggestion on this ?

**Comment by GreGosPhaTos** [comment] 2017-01-08 15:35
If it helps here is the log : 
just after inserts there's a couple of deletes queries : 

```sql
INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,98]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,99]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,100]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,101]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,102]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,103]
executing query: INSERT INTO platforms_games(platform_id, game_id) VALUES (?,?) -- PARAMETERS: [1,104]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,87]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,88]
executing query: DELETE FROM platforms_games WHERE platform_id=? AND game_id=? -- PARAMETERS: [1,95]
```

**Comment by pleerock** [comment] 2017-01-09 13:54
Remove initialization from your entities:

`platforms: Platform[] = [];` and `games: Game[] = [];`. Make them just 
`platforms: Platform[];` and `games: Game[]; `

Thats not convenient however that is needed for your logic to work correctly with ORM, especially when you are using cascades.

In your code you are loading `platform` from the database WITHOUT games. At this time games  property in the platform being initialized and set to `[]`. This means that if you'll save this platform you'll loose all bindings to your games. And you actually doing it - when you do `game.platforms.push(platform);` and save `game` it saves your game and saves platform by cascades, and since platform.games now is `[]` ORM thinks that all games in the platform were removed and tries to remove them.

I'll research why you have such error - you should not have it, or have a different error, but I think what you are doing is wrong and what you want is different thing. I have added tests for your use case, take a look how it works.

I hope I could explain you how it works.

**Comment by GreGosPhaTos** [comment] 2017-01-18 03:10
Ok thanks I found a workaround but I ll definitly try that .
I am not sure why I what I am trying to do is wrong ? 

Should I try to attach a game collection to a platform and save the relation like this instead of doing the opposite ?

**Comment by pleerock** [comment] 2017-06-30 14:02
This should already be fixed in latest typeorm versions, please let me know if you will still have such problem.

**Closed by pleerock** 2017-06-30 14:02 UTC
Labels: needs more info
