### ISSUE TITLE
[Feature Request]comment on entity

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3719] opened 2019-02-27 02:55 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Please support this:
```ts
@Entity({comment:'this is a table comment'})
class A{
  // ...
}
```

don't need to support all the databases, just set it into entity metadata is helpful.

**Comment by vlapo** [comment] 2019-02-27 10:47
Duplicate of https://github.com/typeorm/typeorm/issues/3360. Please search before create issue :)

**Closed by vlapo** 2019-02-27 10:47 UTC

**Comment by hirajatv** [comment] 2022-09-29 14:14
> Duplicate of #3360. Please search before create issue :)

HI @vlapo can you please guide
on how to add comment on table or entity?

As i can't find any reference or document supporting the same
:-)
