### ISSUE TITLE
Postgres emitted error goes unhandled (when a connection dies) - app crashes

### ISSUE THREAD

**Issue by azigelman** [typeorm/typeorm#5387] opened 2020-01-21 08:08 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create a connection of type 'Postgres' with pg version > "7.13.0"
Run a query (e.g. `select pg_sleep(8)`)
Terminate the connection unexpectedly (e.g. disconnect from the DB side running the following SQL on your database from a different proccess)
```sql
SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
where query = 'select pg_sleep(8)';
```

The app crashes with error:
```sh
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/typeorm_debug/node_modules/pg/lib/client.js:255:9)
    at Object.onceWrapper (events.js:312:28)
    at Connection.emit (events.js:223:5)
    at Socket.<anonymous> (/typeorm_debug/node_modules/pg/lib/connection.js:133:10)
    at Socket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Client instance at:
    at connectedErrorHandler (/typeorm_debug/node_modules/pg/lib/client.js:202:10)
    at Connection.<anonymous> (/typeorm_debug/node_modules/pg/lib/client.js:272:9)
    at Object.onceWrapper (events.js:312:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

--------------------------------------------------------

I guess that there is an error being emitted and not being caught.
Can a change in Typeorm prevent this?

Thanks

**Comment by smdesmet** [comment] 2020-08-20 17:31
This error is emitted from the databaseConnection in PostgresQueryRunner.ts. If you install an error event listener on that databaseconnection, the application doesn't crash(the transaction is also not rolled back, so the query failed without typeorm knowing about it...).

**Comment by GnanaRaga** [comment] 2020-09-21 10:54
Could you please elaborate on how to install an error event listener on the databaseconnection

**Comment by imnotjames** [comment] 2021-06-23 20:37
Seems to be a Duplicate of #5112

**Closed by imnotjames** 2021-06-23 20:37 UTC
Labels: driver: postgres, question
