### ISSUE TITLE
Column comments are persisted in MySQL but not PostgreSQL

### ISSUE THREAD

**Issue by rmainseas** [typeorm/typeorm#4359] opened 2019-06-25 15:15 UTC
**Issue type:**

- [ ] question
- [X] bug report
- [ ] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [ ] `mysql` / `mariadb`
- [ ] `oracle`
- [X] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [ ] `latest`
- [ ] `@next`
- [x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
import {
  Entity, Column,
} from 'typeorm';

@Entity()
export class User {
  @Column({
    type: 'varchar',
    nullable: false,
    comment: 'The name of the user (i.e Samuel Jenkins)',
  })
  public name: string;
}
```

In MySQL this comment would be persisted to the database when a migration is generated (the migration would contain a SQL statement including the comment). In PostgreSQL.....that's not the case.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    - [x] `mysql`
    - [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Possibly related to #3360, though that seems more related to missing functionality (support for table comments) whereas, this functionality works in MySQL....just not PostgreSQL (hence why I categorized it as a bug)

**Comment by nscarlson** [comment] 2019-09-21 00:20
@nionoku what's the status on this?

**Comment by imnotjames** [comment] 2020-10-11 04:39
There's open issues with the PR that haven't been resolved.  If anyone would like to pick that up we could get that change in.

**Comment by imnotjames** [comment] 2020-10-12 06:01
Duplicate of #3360

**Closed by imnotjames** 2020-10-12 06:01 UTC
Labels: bug, driver: postgres
