### ISSUE TITLE
Inheritance + relations

### ISSUE THREAD

**Issue by oktapodia** [typeorm/typeorm#5124] opened 2019-11-21 13:55 UTC
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, 

I would like to know if their is a possibility to declare a `OneToMany` relation into an [inherited abstract class](https://typeorm.io/#/entity-inheritance)?

E.g:

BaseUser.ts
```ts
import {
    Column,
    OneToMany,
    PrimaryGeneratedColumn,
} from 'typeorm';
import { Token } from './Token';

export abstract class BaseUser {
    @PrimaryGeneratedColumn('uuid')
    public id: string;

    @Column()
    public name?: string;

    @OneToMany(() => Token, (token) => token.user, { onDelete: 'CASCADE' })
    public tokens: Token[];
}
```

User.ts (Also having the `Admin` class very similar to the User one)
```ts
import {
    Column,
    Entity,
} from 'typeorm';
import UserTypeEnum from '../constants/UserTypeEnum';
import { BaseUser } from './BaseUser';

@Entity()
export class User extends BaseUser {
    @Column({ type: 'simple-array' })
    public roles: string[] = [UserTypeEnum.USER];
}
```

Token.ts
```ts
import {
    Entity, ManyToOne,
    PrimaryGeneratedColumn,
} from 'typeorm';
import { BaseUser } from './BaseUser';
@Entity()

export class Token {
    @PrimaryGeneratedColumn('uuid')
    public id: string;

    @ManyToOne(() => BaseUser, (user) => user.tokens)
    public user: BaseUser;
}
```

I'm currently getting that error 
```
(node:36999) UnhandledPromiseRejectionWarning: Error: Entity metadata for Token#user was not found. Check if you specified a correct entity object and if it's connected in the connection options.
```

and I guess this is because I'm using `BaseUser` into the `ManyToOne` relation, do you have an idea of how to achieve this?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by djflex68** [comment] 2020-08-10 12:02
When will this problem be solved ? 
We have to manage each polymorphic association by hand for now, which is bloating and complexifying the code unnecessarily...

**Comment by sebospc** [comment] 2020-08-16 21:13
The same here, we need to inherit relations.

**Comment by vabatta** [comment] 2020-10-16 18:06
I also ran into this issue. The fact is that when you compose this with other libraries (such as `TypeGraphQL`) the only way to have inheritance is through abstract classes.

**Comment by imnotjames** [comment] 2020-10-16 20:28
I'm not sure I understand the issue here - Token is referencing `BaseUser` which is NOT an entity so it cannot find the metadata.

Why not set up the `ManyToOne` to be `User` instead of `BaseUser`?  `User` is an entity where `BaseEntity` is _not_.

```
    @ManyToOne(() => User, (user) => user.tokens)
    public user: User;
```

If you want this to reference either `Admin` or `User` how would that work if you haven't set up single table inheritance?

**Comment by vabatta** [comment] 2020-10-18 18:03
Let's do a more concrete example with inheritance. This is a simplified example, the events type are 10+.

```
Event       - Main type, some info shared
├ Intensity - Custom event with different numbers 
└ Detail    - Custom event with a lot of text fields
```

```ts
export abstract class Event {
    @PrimaryGeneratedColumn('uuid')
    public id: string;

    @Column({ nullable: true })
    public name?: string;

    @Column()
    public type: string;

    @CreateDateColumn()
    public createAt: Date;
}
```

```ts
export class Intensity extends Event {
    @Column()
    public intensity: int;

    @Column()
    public frequency: int;
}
```

```ts
export class Detail extends Event {
    @Column()
    public subject: string;

    @Column()
    public body: string;

    @Column({ nullable: true })
    public notes?: string;
}
```

The idea here is that each event will have its own table but a requirement is to have an "overview" of them by collecting it through the base. So this would be much useful:

```ts
export class Collector {
    @OneToMany(() => Event, (event) => event.id)
    public events: Event;
}
```

Rather than:

```ts
export class Collector {
    @OneToMany(() => Intensity, (event) => event.id)
    public intensityEvents: Intensity;

    @OneToMany(() => Detail, (event) => event.id)
    public detailEvents: Detail;

    // and any more, plus the aggregation needed for counting and so on
}
```

This way, we can still have all benefit of multiple tables but begin able to query / aggregate through an "abstract entity" for the common data. Library such as [TypegraphQL](https://typegraphql.com/) needs abstract classes for the `ObjectType` / `InterfaceType` as well.

**Comment by imnotjames** [comment] 2020-10-18 19:07
We don't support multiple table inheritance, only single table inheritance.

https://typeorm.io/#/entity-inheritance/single-table-inheritance

If you need multiple tables in typeorm you'll need to create a main event entity that can link out to other facets via relations.  That's effectively what we'd have to do under the hood, isn't it?

**Comment by vabatta** [comment] 2020-10-18 19:31
Yes that's right. I suppose that for this use case we need to implement the solution in our codebase.

**Comment by imnotjames** [comment] 2020-10-18 19:33
It sounds like this is already supported by typeorm, just have to put the pieces together in your application.  Closing!

If I've missed something though comment with what and we can reopen.

**Closed by imnotjames** 2020-10-18 19:33 UTC
Labels: driver: postgres, needs more info, question

**Comment by vabatta** [comment] 2020-10-18 19:41
I suppose that this is true, we will need to implements this in our codebase ourselves as this goes beyond the scope of what typeorm does. I will take a deeper look and see if anything else pops up, put it here along with a gist/repo example.

**Comment by imnotjames** [comment] 2020-10-18 19:47
Absolutely.  If there's a more well defined feature request please feel free to open a new issue.

It's just the original feature request is possible with single table inheritance

**Comment by mwaeckerlin** [comment] 2020-10-28 21:35
Single Table Inheritance is not the answer to this question. I have exactly the same problem:

What I want is [Concrete Table Inheritance](https://typeorm.io/#entity-inheritance/concrete-table-inheritance) with relations in the abstract base class.

So at the end, there must be one table with some parts that exist in all three tables, and instead of only simple types, there should be relations.

`@ManyToMany` works fine, but unfortunately not `@OneToMany`, because `@OneToMany` has this useless silly inverse requirement, see also #3233. This is one example, why we rally should have `@OneToMany` without inverse!

**Comment by dawadam** [comment] 2020-11-11 08:46
A solution since last year?

**Comment by bombillazo** [comment] 2021-12-07 21:05
So officially the only way to do table inheritance with relations is with single table inheritance?

**Comment by Ignacio1224** [comment] 2022-11-01 15:33
Nowadays that's true, I find myself in this situation and I'm a bit disappointed because the main concept of Inheritance is to use polymorphic methods and eliminate duplicate code reusing it.
However this tool is an excellent option if you want an ORM.

**Comment by EvilPopS** [comment] 2024-01-07 22:15
I am quite disappointed that TypeORM still doesn't support so called 'Joined Table' inheritance strategy. The point of ORM is to minimize the amount of code that developer writes. Yes I can manually write the code for the given strategy, but why would I have to pollute my code with something that has nothing to do with my app? That's why I am resorting to using the ORM in the first place, to be able to develop things as fast and optimally as I can, and not to develop a feature of a tool I am using. I am really sad and mad, because I really like TypeORM and the way it is made, but it really lacks some fundamental stuff. I hope developers will find some free time to resolve this issue instead of pushing it aside with excuse how it is already available in the tool, however you just need to do some stuff yourself for it to work.

**Comment by IgorArnaut** [comment] 2025-03-24 17:00
> It sounds like this is already supported by typeorm, just have to put the pieces together in your application. Closing!
> 
> If I've missed something though comment with what and we can reopen.

That's... dumb.

**Comment by IgorArnaut** [comment] 2025-04-28 16:39
Here is the problem that is caused by the current implementation of One-To-Many relationships.
https://github.com/typeorm/typeorm/issues/3233#issuecomment-2752815630
