### ISSUE TITLE
Typeorm pool doesn't exist in master, slave replication.

### ISSUE THREAD

**Issue by dev-esakki** [typeorm/typeorm#6951] opened 2020-10-21 07:35 UTC
`typegraphql, typeorm, Mysql with master slave replication.`

I have configured mysql with master and slave databases with separate instances and its working fine. I have encounter an error
that shows connection pool dosen't exist. 

![download](https://user-images.githubusercontent.com/51811510/96686759-90cb4a80-139c-11eb-844a-abd5a8bba7c1.png)

while connecting via typeorm. Here's my **ormconfig.json**

```
 "replication": {
         "master": 
            {
                     "host": "192.168.0.250",
                     "port": 3306,
                     "username": "root",
                     "password": "test#123",
                     "database": "master"       
            },
         "slaves": [
            {
                     "host": "192.168.0.175",
                     "port": 3306,
                     "username": "root",
                     "password": "test#123",
                     "database": "master"             
            }
     ]
   },
```

with **server.ts** I have connected the database
```
await createConnection().then(async(res) => {
        console.log(res)
        console.log("Database Connected")
        const schema = await gqSchema()
        const server = new ApolloServer({ 
            schema,
            context: ({ req }: any) => ({ req })
        })
        await server.listen(4000)
        console.log("Server has started!")
    }).catch(err => {
        console.log("err", err)
    }) 
```

Here I'm using **typegraphql** using **query builder** to fetch the data
```
 const slaveQueryRunner = getConnection().createQueryRunner("slave");
        try {
            const connection = getConnection().getRepository(User);
            const usersList  = await connection.createQueryBuilder()            
            .from(User, "user")
            .setQueryRunner(slaveQueryRunner)
            .where("user.firstName = ", {firstName})
            .getOne();
            console.log(usersList)

        } finally {
            slaveQueryRunner.release();
        }
```

Thanks in advance.

**Comment by imnotjames** [comment] 2020-10-21 08:28
Can you create a minimal reproducible example which can be executed?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by dev-esakki** [comment] 2020-10-21 10:15
I have updated the question with minimal code.

**Comment by pavellishin** [comment] 2021-04-14 16:37
@dev-esakki did you figure out this problem, by any change? I'm seeing something very similar in tests:

`typeorm.ts`
```typeorm.ts
import { ConnectionOptions, createConnection } from 'typeorm';

import entities from '../../entities/index';

export const initializeTypeormConnections = async () => {
  const config: ConnectionOptions = {
    type: 'mysql',
    entities,
    replication: {
      master: {
        host: process.env.MYSQL_HOSTNAME,
        port: 3306,
        username: process.env.MYSQL_USERNAME,
        password: process.env.MYSQL_PASSWORD,
        database: process.env.MYSQL_DATABASE
      },
      slaves: [
        {
          host: process.env.MYSQL_READ_HOSTNAME,
          port: 3306,
          username: process.env.MYSQL_USERNAME_RO,
          password: process.env.MYSQL_PASSWORD_RO,
          database: process.env.MYSQL_DATABASE
        }
      ]
    }
  };

  return createConnection(config);
};
```

`testfile.test.ts`
```
...
  beforeAll(async () => {
    await initializeTypeormConnections();
  });
...
```

`output`
```
    Pool does Not exists.

      at PoolNamespace.getConnection (node_modules/mysql2/lib/pool_cluster.js:34:17)
      at _cluster._getConnection (node_modules/mysql2/lib/pool_cluster.js:41:21)
      at node.pool.getConnection (node_modules/mysql2/lib/pool_cluster.js:185:18)
      at connection.connect.err (node_modules/mysql2/lib/pool.js:59:18)
      at PoolConnection.<anonymous> (node_modules/mysql2/lib/connection.js:716:13)
      at PoolConnection._notifyError (node_modules/mysql2/lib/connection.js:212:12)
      at ClientHandshake.Connection.handshakeCommand.on.err (node_modules/mysql2/lib/connection.js:109:14)
      at ClientHandshake.execute (node_modules/mysql2/lib/commands/command.js:33:14)
      at PoolConnection.handlePacket (node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (node_modules/mysql2/lib/connection.js:77:25)
```
```
    Pool does Not exists.

      at PoolNamespace.getConnection (node_modules/mysql2/lib/pool_cluster.js:34:17)
      at PoolCluster.getConnection (node_modules/mysql2/lib/pool_cluster.js:118:15)
      at src/driver/mysql/MysqlDriver.ts:704:30
      at MysqlDriver.Object.<anonymous>.MysqlDriver.obtainSlaveConnection (src/driver/mysql/MysqlDriver.ts:703:16)
      at MysqlQueryRunner.Object.<anonymous>.MysqlQueryRunner.connect (src/driver/mysql/MysqlQueryRunner.ts:79:58)
      at MysqlQueryRunner.<anonymous> (src/driver/mysql/MysqlQueryRunner.ts:154:55)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
      at node_modules/typeorm/node_modules/tslib/tslib.js:115:75
      at Object.__awaiter (node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
      at src/driver/mysql/MysqlQueryRunner.ts:152:43
      at MysqlQueryRunner.Object.<anonymous>.MysqlQueryRunner.query (src/driver/mysql/MysqlQueryRunner.ts:152:16)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:2014:43)
```

**Comment by pavellishin** [comment] 2021-04-14 19:35
Ah, figured out my issue - I wasn't seeing another relevant error before:

```
  console.warn node_modules/mysql2/lib/pool_cluster.js:184
    [Error] PoolCluster : Error: Access denied for user 'readonly_user'@'localhost' to database 'test_db'
```

Looks like it can't create a connection pool if the user in question can't connect to the *read replica*.

**Comment by imnotjames** [comment] 2021-07-06 02:31
This seems like an unrelated issue to typeorm.  I'll be closing it out.

**Closed by imnotjames** 2021-07-06 02:31 UTC
