### ISSUE TITLE
Entity field with `array: true` and `length` generates a new migration every time

### ISSUE THREAD

**Issue by realyze** [typeorm/typeorm#3088] opened 2018-11-09 23:52 UTC
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When I add an entity field with `array: true` and `length: <n>`, `migration:generate` will drop and re-add the array column every time.

Small reproducible case here: https://github.com/realyze/typescript-example (problematic fields added here: https://github.com/realyze/typescript-example/blob/master/src/entity/Post.ts#L20-L27)

Big props to you for this awesome ORM, @pleerock !

**Comment by xiaoweiColive** [comment] 2019-09-04 10:30
Similar issue here. When I have array set to true and a length, every time I reboot the app, the data of that field will be cleared without being stored.

**Comment by AlexMesser** [comment] 2021-07-31 11:35
I just checked this reproduction on the latest `0.2.36`, everything works as expected:

```sql
% typeorm migration:run
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: ALTER TABLE "public"."post" ADD "myLittleBrokenArray" character varying(25) array
query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1627731077991,"aaa1627731077991"]
Migration aaa1627731077991 has been executed successfully.
query: COMMIT
% typeorm migration:run
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
```

Closing because this issue most probably isn't actual anymore.

**Closed by AlexMesser** 2021-07-31 11:35 UTC
Labels: bug, comp: migrations, driver: postgres
