### ISSUE TITLE
Ability to output SQL migrations?

### ISSUE THREAD

**Issue by stevendesu** [typeorm/typeorm#5964] opened 2020-04-28 15:32 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When you run the `migration:generate` method, it creates a TypeScript file for the migration. However in order to run this migration you need the TypeORM CLI. I don't know if it's **always** the case (maybe this is only true of the MySQL driver, or maybe it's only true because I'm not using certain TypeORM features), but every time I've generated a migration it looks something like this:

```
import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialMigration1587670859452 implements MigrationInterface
{
	name = "InitialMigration1587670859452";

	public async up(queryRunner: QueryRunner): Promise<void>
	{
		await queryRunner.query(`
			CREATE TABLE \`user\` (
				\`id\` int NOT NULL AUTO_INCREMENT,
				\`name\` varchar(255) NOT NULL,
				\`email\` varchar(255) NOT NULL,
				\`passwordHash\` varchar(255) NOT NULL,
				UNIQUE INDEX \`IDX_3641ff83ff7c23b2760b3df56d\` (\`name\`),
				UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`),
				PRIMARY KEY (\`id\`)
			) ENGINE=InnoDB
		`);
	}

	public async down(queryRunner: QueryRunner): Promise<void>
	{
		await queryRunner.query("DROP INDEX `IDX_e12875dfb3b1d92d7d7c5377e2` ON `user`");
		await queryRunner.query("DROP INDEX `IDX_3641ff83ff7c23b2760b3df56d` ON `user`");
		await queryRunner.query("DROP TABLE `user`");
	}

}
```

This is just running raw SQL! If instead of a TypeScript file I were given SQL files (perhaps a `*-up.sql` and a `*-down.sql` in order to handle reverting) then I could run the migration on a database without needing the TypeORM CLI

I can think of two advantages to this:

 1. As I mentioned in https://github.com/typeorm/typeorm/issues/5959, delivering the CLI as a separate module can shave >10 MB off of production images and reduce the number of dependencies in production by over **90**
 2. In production I may not want to SSH into my application server and manually run commands to migrate the database. I may instead want to perform the migration offline on the database directly. Needing to install the TypeORM CLI to do this seem silly

Obviously for backwards compatibility you wouldn't want to make this the default behavior, but perhaps something like `typeorm migration:generate --sql`?

**Comment by moltar** [comment] 2020-05-01 08:53
You can run migrations from the `connection` object method. Although I don't know if it uses any CLI code or not.

**Comment by imnotjames** [comment] 2020-10-07 04:38
Duplicate of #4551

**Closed by imnotjames** 2020-10-07 04:38 UTC
Labels: comp: migrations, new feature
