### ISSUE TITLE
One to one relation saving caused "cannot read property of undefined" error

### ISSUE THREAD

**Issue by RedTailBullet** [typeorm/typeorm#2600] opened 2018-07-29 04:38 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In `buildForSubjectRelation` function, situation of `subject.entity` being undefined is not considered. Thus raising the `cannot read property of undefined` problem.  

Further backtrack shows that the problem might be caused by `SubjectDatabaseEntityLoader` not loading the entity correctly and created a subject with `subject.entity === undefined` and `subject.databaseEntity === undefined`. This subject is the one whose relationship with the entity being saved is going to be terminated.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by RedTailBullet** [comment] 2018-07-31 07:14
Some follow-up information: When trying to delete relations from one side, it also throws this undefined error.  

Example:
A has many B, B has one C.
When updating A and delete some of the Bs in A.Bs, an error of `Cannot read property 'C' of undefined`.

**Comment by rangelfinal** [comment] 2018-09-26 17:16
This is being caused by the [`compare2Objects` function at `util/OrmUtils.ts`](
https://github.com/typeorm/typeorm/blob/d0adc6610d81b3e657f672fe661d31ab73370380/src/util/OrmUtils.ts#L180)
As there's no null or undefined checks, the function throws if any of the compared objects are not initialized.
  
The full stack would be as follows:
```
TypeError: Cannot read property 'equals' of undefined
    at Function.OrmUtils.compare2Objects (src/util/OrmUtils.ts:176:15)
    at Function.OrmUtils.deepCompare (src/util/OrmUtils.ts:114:23)
    at OneToOneInverseSideSubjectBuilder.buildForSubjectRelation (src/persistence/subject-builder/OneToOneInverseSideSubjectBuilder.ts:142:91)
    at src/persistence/subject-builder/OneToOneInverseSideSubjectBuilder.ts:42:22
    at Array.forEach (<anonymous>)
    at src/persistence/subject-builder/OneToOneInverseSideSubjectBuilder.ts:35:48
    at Array.forEach (<anonymous>)
    at OneToOneInverseSideSubjectBuilder.build (src/persistence/subject-builder/OneToOneInverseSideSubjectBuilder.ts:34:23)
    at EntityPersistExecutor.<anonymous> (src/persistence/EntityPersistExecutor.ts:105:73)
    at step (node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
    at Object.next (node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
    at fulfilled (node_modules/typeorm/persistence/EntityPersistExecutor.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

A quick fix would be just adding a undefined check, for example:
```
if (x === undefined && y === undefined) {
  return true;
}
if (x === undefined || y === undefined {
  return false;
}
```

**Comment by cerino-ligutom** [comment] 2019-02-04 07:35
Having this issue as well. In my case, I have optional fields in my input types of GraphQL so when I receive them in the server and the field is not provided, it's undefined by default and if I pass these values directly to TypeORM for saving/updating, I get this error.

**Comment by Kononnable** [comment] 2019-02-09 17:38
Guys, could you make a PR with failing test? I think it will be much easier to understand how to reproduce the issue. And test is necessary if don't want same bug to be introduced in the future.

**Comment by nilswxa** [comment] 2019-02-10 14:52
In my case I was able to fix it by setting 'persistence: false' on the troubling side of my (@OneToOne) relationship. This prevents TypeORM from attempting to do something impossible. 🙂

**Comment by nilswxa** [comment] 2019-02-10 14:58
In my case I was able to fix it by setting `{ persistence: false }` on the troubling side of my `@OneToOne` relationship. This stops TypeORM from attempting to do something impossible and crashing the entire `save()` operation. 🙂 

Was stuck on this `cannot read property of undefined` error for a while.

**Comment by ikatun** [comment] 2019-03-24 12:19
This was fixed for me when I updated to latest typeorm (v0.2.15 at the time of writing this comment).

It turns out (for me at least) that I was trying to break unique constraint on a one-to-one relation and typeorm crashed instead of reporting the error. It now reports the error correctly.

**Comment by Kononnable** [comment] 2019-04-20 22:53
Closing as no reproduction data was provided.

**Closed by Kononnable** 2019-04-20 22:53 UTC
Labels: needs failing tests
