### ISSUE TITLE
Query annotation for multi-tenant applications

### ISSUE THREAD

**Issue by florianmartens** [typeorm/typeorm#6312] opened 2020-06-25 16:25 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Problem:**
Multi-tenant solutions that share one database have become quite popular. However, this requires the ability to enforce strong isolation at the application level. Currently, no node ORM addresses this issue - even though it is quite common. Making this easy and strongly enforced could be a true game-changer for SaaS products.

**Possible Solutions:**
The ability to annotate all queries for a model. The annotated model would become a TenantModel and queries like e. g. findOne() and find() are automatically annotated with an additional where condition e. g. findOne({ where: { tenantId } })

One solution could be the ability to create custom managers and assign them to certain models. These managers could have a method that is invoked before every query.

**Comment by imnotjames** [comment] 2020-10-11 10:42
We probably won't be making business logic annotations a part of TypeORM because everyone is going to be doing this differently.

However, there's an issue requesting scopes and filters which may accomplish this.  I'll mark this feature request as a duplicate.

**Comment by imnotjames** [comment] 2020-10-11 10:42
Duplicate of #1601

**Closed by imnotjames** 2020-10-11 10:42 UTC
Labels: driver: postgres, new feature

**Comment by cottsak** [comment] 2023-01-19 03:14
https://github.com/typeorm/typeorm/issues/1601 doesn't have a good answer for this problem so I think the "duplicate" status is incorrect.

**Comment by cottsak** [comment] 2023-01-19 03:19
something like this:

```js
this.usersRepository.fromTenant(request.headers.tenantId).getMany()
```

would not be an acceptable solution because you want to inject this via some hook and make it implicit to the repository usages. eg, you might have the usage look like this:

```js
this.usersRepository.getMany()
```

but the scope is inserted as a `WHERE` clause anyway:

```js
{ tenantId: req.headers.tenantId }
```

**Comment by ArpanKIIT2017** [comment] 2023-06-28 15:52
> something like this:
> 
> ```js
> this.usersRepository.fromTenant(request.headers.tenantId).getMany()
> ```
> 
> would not be an acceptable solution because you want to inject this via some hook and make it implicit to the repository usages. eg, you might have the usage look like this:
> 
> ```js
> this.usersRepository.getMany()
> ```
> 
> but the scope is inserted as a `WHERE` clause anyway:
> 
> ```js
> { tenantId: req.headers.tenantId }
> ```

Exactly what I am looking for. If anybody knows a way to override the default scope please let me know. In Django ORM we do this so easily using the objects manager.
