### ISSUE TITLE
Jest broken when removing a non-existed entity using `remove()`

### ISSUE THREAD

**Issue by Yaojian** [typeorm/typeorm#1549] opened 2018-02-04 10:36 UTC
Database: mysql
TypeORM version: `0.1.12`

### The `DummyEntity`
```typescript

@Entity({name: 'sys_dummy'})
export class DummyEntity {

    @PrimaryColumn({type: 'varchar'})
    id: string;

    @Column({type: 'varchar'})
    val: string;
}
```
### The unit test using Jest

```typescript
describe('DummyRepository', () => {
    it('TypeORM remove() break Jest when then entity does not exist', async () => {
        const dummy = createDummyEntity();
        const connection = await createConnection(dbOptions);
        try {
            const repository = connection.getCustomRepository(DummyRepository);
            /* remove the entity without saving it breaks Jest with 'ENOENT: no such file or directory...'*/
            await repository.remove(dummy);
        } finally {
            await connection.close();
        }
    });
});
```
### Jest output
```
Test suite failed to run

    ENOENT: no such file or directory, open '/Users/yaojian/Documents/Projects/AppLight/devel/sources/server/src/persistence/Subject.ts'
      
      at exports.formatStackTrace (node_modules/jest-message-util/build/index.js:232:20)
          at Array.map (<anonymous>)
```

**Comment by pleerock** [comment] 2018-02-05 08:13
Duplicate of #1372 please continue discussion there on what other issues jest brings to you.

**Closed by pleerock** 2018-02-05 08:13 UTC
