### ISSUE TITLE
Skip constructor when entity is loaded from database

### ISSUE THREAD

**Issue by pepakriz** [typeorm/typeorm#1772] opened 2018-03-17 09:43 UTC
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[x] `sqljs`
[x] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create some entity with non-empty constructor. For example:

```ts
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    private title: string;

    constructor(title: string) {
        if (title === undefined) {
            throw new Error("Invalid title value");
        }

        this.title = title;
    }

}
```

When entity is loaded from db, `Invalid title value` is thrown, because constructor is invoked without args. I think calling constructor must be skipped somehow in this case.

**Comment by lodemo** [comment] 2018-03-29 08:37
I think just checking the value instead of throwing an error would be a straightforward solution while maintaining the current functionality.


```javascript
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    private title: string;

    constructor(title?: string) {
        if (title !== undefined) {
            this.title = title;
        }
    }

}
```

**Comment by pepakriz** [comment] 2018-03-29 08:57
@lodemo I've already tried your solution, but It leads to error: `error TS2564: Property 'title' has no initializer and is not definitely assigned in the constructor.`

**Comment by lodemo** [comment] 2018-03-29 09:13
This is probably due to the _strictPropertyInitialization_ compile flag, [this](https://www.ryadel.com/en/ts2564-ts-property-has-no-initializer-typescript-error-fix-visual-studio-2017-vs2017/) could help.

You could assign title to a default value if not given, or use the definite assignment assertion modifier(!) like this.

```ts
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    private title!: string;

    constructor(title?: string) {
        if (title !== undefined) {
            this.title = title;
        }
    }

}
```

**Comment by pleerock** [comment] 2018-03-29 09:15
Correct, you should understand what each compile option will bring it, value of it and how you are going to use it. You either need to use @lodemo solution either initialize your property in the constructor.

I'll close this issue since its not related to TypeORM and more related to language itself. Feel free to keep discussion.

**Comment by pepakriz** [comment] 2018-03-29 09:42
Thanks for your answers. I like strict typing and I would like use it with this library. I want correct signatures in constructors - `title?: string` vs `title: string`. So this is reason for my proposal about skipping constructor call. My PR https://github.com/typeorm/typeorm/pull/1773 contains big hack in entity deserialization, but I don't have to write next hacks in entity constructors. Look at Doctrine ORM project. They do the same thing and they have lifecycle event `postLoad` (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events)

**Comment by pleerock** [comment] 2018-03-29 10:26
Sorry, but I think avoiding a constructor and having users to use a listener instead is a bad idea. If you want to keep strictness you should initialize your properties, e.g. `title: string = "";` - that's a proper resolution of the problem.

**Comment by pepakriz** [comment] 2018-03-29 11:02
Why bad idea? In my opinion, deserialization is not the same as creating a new instance. I suggest skipping constructor only when an entity is deserialized from db, because the constructor is called without arguments and correct arguments cannot be estimated. The constructor should validate own consistency, so nobody can create an object in an invalid state. `afterLoad` event was the answer to the question: `What if user wants to have something initialized after load?`. But anyway, I've never used it.

**Comment by kbaryshnikov** [comment] 2019-02-10 11:45
In canonical DDD, you just cannot have a constructor without a required argument (there's ID at least). Of course, there's an obvious workaround: using a named constructor (implemented with a static method) and declaring the constructor private kind of solves the issue. But a good ORM should not put such restrictions on model design.

In Javascript, there is a proper way of creating a new instance without invoking constructor, no hacks required:

```
Object.create(objectClass.prototype);
```

**Comment by pleerock** [comment] 2019-02-22 21:20
Reopening this issue and according PR.

**Comment by dgreene1** [comment] 2019-07-24 20:29
I have an example of you can continue to use `strictPropertyInitialization` but unfortunately it's sorta blocked by this other issue with `migration:generate`: https://github.com/typeorm/typeorm/issues/3835#issuecomment-514787130

I suppose that if you don't use `migration:generate` then you could still use this solution:

```typescript
import {
    Entity,
    PrimaryColumn
} from "typeorm";

@Entity()
export class EntityThatCantBeGenerated  {

    @PrimaryColumn("varchar")
    public readonly id: string;

    constructor(input : { id : string }){
        this.id = input.id;
    }
}
```

**Comment by JulianKowalczuk** [comment] 2019-08-22 00:21
@dgreene1 it's nice to test solution before post it :smile:
_this_ inside static method? I don't think so

I would suggest:
```ts
public static make (input: IJustData){
return Object.assign(new EntityThatCantBeGenerated(), input)
}
```

**Comment by dgreene1** [comment] 2019-08-22 00:25
Yes I found that after I posted it and forgot to update this example. I apologize but I was just trying to be helpful. And I do believe that the rough idea is still gets be going where the want to go.

I’ve updated my example.

**Comment by lucaswxp** [comment] 2021-02-19 18:14
Any way to get past this? @dgreene1 solution is only half the story, I still don't want to make all my fields optional when using `strict: true`.

**Comment by tobloef** [comment] 2021-04-19 07:21
Definitely agree with this issue, you shouldn't have to change your constructor for the sake of your ORM. Could someone tell me why TypeORM calls the constructor in the first place? Seems like an odd design choice to me, since it won't have the required arguments.

**Comment by imnotjames** [comment] 2021-06-19 22:51
This calls the constructor becuase that is how you create an object.  Such as the entity.  

Anyone have suggestions on how we can instantiate the object without calling the constructor?

Hibernate can't bypass this so how are we supposed to?  I think this is expected behavior.

**Comment by dgreene1** [comment] 2021-06-19 23:42
I abandoned TypeORM and went to [Prisma.io](https://www.prisma.io/) and I’ve never been happier.

It’s the most ergonomic and accurate TypeScript experience for SQL databases. I don’t mean to steal energy from this library, but if you’re the type of person who is interested in this issue and any aspect of strong type safety, then Prisma is for you. I don’t think the TypeORM maintainers are interested in the LINQ/fluent approach that Prisma offers.

(Please don’t @ me since I’ll be unsubscribing. Best of luck everyone).

**Comment by kbaryshnikov** [comment] 2021-06-20 02:50
Hibernate does not require a no-parameter constructor. JPA does (unfortunately).

Anyway, I've switched to mikro-orm a long ago, and do not care anymore.

**Comment by imnotjames** [comment] 2021-06-20 14:20
https://docs.jboss.org/hibernate/orm/5.5/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-constructor

> The entity class should have a no-argument constructor. Both Hibernate and JPA require this.

This can be bypassed by creating a separate interceptor and instantiating your objects using weird allocation or otherwise.

**Comment by imnotjames** [comment] 2021-06-20 18:33
> Won't this break the paradigms and promises provided by JavaScript?

After doing a bit more research, the answer is yes.

https://stackoverflow.com/questions/65395454/object-create-and-native-private-fields

Doing this would break private properties & other features.

We won't make this the default, but I'm gonna open a PR soon.

**Comment by imnotjames** [comment] 2021-06-20 22:50
I have a PR up which implements this.

When deserializing from the database it will not call the constructor if you've set the connection option.

In the future, perhaps we can make that the default.  For now, to prevent some pretty severe breakage I think it's best to have it be opt-in.

**Closed** 2021-06-28 08:33 UTC
Labels: bug, driver: cordova, driver: mariadb, driver: mongodb, driver: mssql, driver: mysql, driver: oracle, driver: postgres, driver: sqlite, driver: sqljs, new feature

**Comment by lucaswxp** [comment] 2021-06-28 12:53
@imnotjames That's nice, good work! I little confused as to "properties will not operate as expected" when using this, can you give one example?

**Comment by imnotjames** [comment] 2021-06-28 12:54
> @imnotjames That's nice, good work! I little confused as to "properties will not operate as expected" when using this, can you give one example?

```
class Foo {
  bar = "baz"
}
```

Without the constructor, `bar` does not default to `baz` during testing.

**Comment by lucaswxp** [comment] 2021-06-28 12:56
@imnotjames I think that makes sense. What about private properties?

**Comment by imnotjames** [comment] 2021-06-28 12:58
> @imnotjames I think that makes sense. What about private properties?

Yup.

Also broken without the constructor.

It's the same as you'll see anywhere else when this kind of thing happens.

**Comment by lucaswxp** [comment] 2021-06-28 13:31
@imnotjames I meant I don't understand what is broken in private properties? Should I make all my fields public or else they won't be de-serialized?

**Comment by imnotjames** [comment] 2021-06-28 22:06
Only [native private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#private_field_declarations) will have troubles.

Hope this clarifies:

```
class Example {
  foo = "bar";
  private bar = "baz";
  #baz = "Hello World";
  notPrivate() {
    console.log(this.foo, this.bar);
  }
  
  all() {
    console.log(this.foo, this.bar, this.#baz);
  }
}
```

```
> const example1 = new Example();

> example1.notPrivate();
bar baz

> example1.boop()
bar baz Hello World

> const example2 = Object.create(Example.prototype);

> example2.notPrivate();
undefined undefined

> example2.boop()
                                                                                       ^
Uncaught:
TypeError: Cannot read private member from an object whose class did not declare it
    at __classPrivateFieldGet ([eval].ts:3:94)
    at Example.boop ([eval].ts:1:10)
    at [eval].ts:1:10
    at Script.runInThisContext (node:vm:129:12)
    at exec (node_modules/ts-node/src/repl.ts:226:17)
    at node_modules/ts-node/src/repl.ts:216:27
    at Array.reduce (<anonymous>)
    at _eval (node_modules/ts-node/src/repl.ts:215:18)
    at evalCode (node_modules/ts-node/src/repl.ts:96:12)
    at REPLServer.nodeEval (node_modules/ts-node/src/repl.ts:115:16)
```

**Comment by mcjkwlczk** [comment] 2021-11-15 13:33
How is it supposed to work if `create` method is invoked without options here https://github.com/typeorm/typeorm/blob/master/src/metadata-builder/EntityMetadataValidator.ts#L118 ? Because of that I'm not able to use it
