### ISSUE TITLE
Migration for MongoDB not working

### ISSUE THREAD

**Issue by n-lavrenko** [typeorm/typeorm#2867] opened 2018-09-29 20:32 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

"mongodb": "^3.1.6",
"typeorm": "^0.2.7",

Guys, please, provide a full example of using MongoDB migration. Or this is the bug?
Here is my **code**:

```import { getMongoManager, MigrationInterface, QueryRunner } from 'typeorm';
import { User } from '../../api/models/User';
import { env } from '../../env';

export class Init1538252088164 implements MigrationInterface {
    
    public async up(queryRunner: QueryRunner): Promise<any> {
        const mongoManager = getMongoManager(env.db.connectionName);
        const user = new User();
        user.username = 'niklavr';
        user.email = 'lavrenonik@gmail.com';
        
        user.firstName = 'Nikita';
        user.lastName = 'Lavrenko';
        
        user.password = 'abra';
        
        await mongoManager.save(user);
    }
    
    public async down(queryRunner: QueryRunner): Promise<any> {
        // some code here
    }
}
```

**and log in the console is**:
`Error during migration run:
Error: Check schema queries are not supported by MongoDB driver.
    at MongoQueryRunner.<anonymous> (/projects/rolly/api/src/driver/mongodb/MongoQueryRunner.ts:498:15)
    at step (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:32:23)
    at Object.next (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:13:53)
    at /projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:3:12)
    at MongoQueryRunner.hasTable (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:659:16)
    at MigrationExecutor.<anonymous> (/projects/rolly/api/src/migration/MigrationExecutor.ts:219:46)
    at step (/projects/rolly/api/node_modules/typeorm/migration/MigrationExecutor.js:32:23)
    at Object.next (/projects/rolly/api/node_modules/typeorm/migration/MigrationExecutor.js:13:53)`

**Comment by elthrasher** [comment] 2018-09-30 16:52
Here's the issue. During the migration, there's a check to see if the migration table exists: https://github.com/typeorm/typeorm/blob/master/src/migration/MigrationExecutor.ts#L219
But since you are using mongodb, you don't have tables and have no need to create your collections ahead of time. In fact, trying to do so throws an error:
https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoQueryRunner.ts#L497

For this to work, the behavior will need to change to not do these kinds of checks if the migration target is mongodb.

**Comment by n-lavrenko** [comment] 2018-10-01 10:12
> Here's the issue. During the migration, there's a check to see if the migration table exists: https://github.com/typeorm/typeorm/blob/master/src/migration/MigrationExecutor.ts#L219
> But since you are using mongodb, you don't have tables and have no need to create your collections ahead of time. In fact, trying to do so throws an error:
> https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoQueryRunner.ts#L497
> 
> For this to work, the behavior will need to change to not do these kinds of checks if the migration target is mongodb.

Ok, thanks for reply. Maybe I will do this issue.

**Comment by vip30** [comment] 2018-12-21 03:16
https://github.com/vip30/typeorm/blob/master/src/migration/MigrationExecutor.ts
Can you check if it is work or not?
It works on my side

**Comment by n-lavrenko** [comment] 2018-12-21 08:02
> https://github.com/vip30/typeorm/blob/master/src/migration/MigrationExecutor.ts
> Can you check if it is work or not?
> It works on my side

Sorry @vip30, now I'm very busy for this. But thank you for the your work! 👍🏻

**Comment by pleerock** [comment] 2018-12-21 10:05
@n-lavrenko, @vip30 tries to help you :)

@vip30 PR was merged, I'll release those changes soon. Think we can close this issue now.

**Closed by pleerock** 2018-12-21 10:05 UTC

**Comment by n-lavrenko** [comment] 2018-12-21 10:07
@pleerock, good news that this code was merged. Thank you.

**Comment by mesin** [comment] 2018-12-31 11:58
Hi Guys

Can you please tell me in what release this bug is fixed?
I have the same issue with migrations and mongodb

**Comment by Kononnable** [comment] 2019-01-02 12:17
0.2.10 was released today. PR was made 12 days ago so it's looks like first released version containing these changes.

**Comment by vip30** [comment] 2019-01-03 15:10
I can confirm that 0.2.11 is included this fix
