### ISSUE TITLE
GroupBy and custom Select forces to put PK in GroupBy

### ISSUE THREAD

**Issue by kronodevcom** [typeorm/typeorm#1255] opened 2017-11-28 18:05 UTC
Message: "QueryFailedError: column "data.id" must appear in the GROUP BY clause or be used in an aggregate function"

My QueryBuilder with custom select and groupBy
const list = await this.sensorDataRepository.createQueryBuilder('data')
            **.select('avg(data.value)', 'value')
            .addSelect( 'sensor.name', 'name')**
            .leftJoin('data.sensor', 'sensor')
            **.groupBy("period")
            .addGroupBy("sensor.name")**            .
             .orderBy("period", "ASC")
            .addOrderBy("sensor.name", "ASC").getMany();

This query work within PK in postgre. (Not generated by ORM)
SELECT avg("data"."value") AS "value", "sensor"."name" AS "sensor_name", EXTRACT(hour from  "data"."createdDate") AS period 
FROM "SensorsData" "data" LEFT JOIN "Sensors" "sensor" ON "sensor"."id"="data"."sensorId" 
GROUP BY period, "sensor"."name"
ORDER BY period ASC, "sensor"."name" ASC

Is the same error using leftJoin ot innerJoin.

**Comment by pleerock** [comment] 2017-11-29 06:12
primary columns are mandatory to select if you want to get real entities

**Comment by kronodevcom** [comment] 2017-11-29 14:46
yes, but the custom .select's invalidate the  error into the groupBy with the Pk. for this case. In this example I don't like return an entity.

**Comment by pleerock** [comment] 2017-11-29 15:14
what do you mean? If you don't want to get entity you must use `getRawMany()` instead of `getMany()` method.

**Comment by andresdenis** [comment] 2017-11-30 13:18
Thanks!

**Comment by lightsuner** [comment] 2018-01-29 13:55
@pleerock  Hi. I have same problem.
I use PostgreSQL 9.5.2 .

I want to run this code:
```SQL
select m_exercise.*
from machine_exercises as m_exercise
inner join workout_program_exercises as w_program_exercises on w_program_exercises.machine_exercise_id = m_exercise.id
inner join workout_exercises as w_exercises on w_exercises.workout_program_exercise_id = w_program_exercises.id
inner join workouts as workout on w_exercises.workout_id = workout.id
where workout.status = 2 and workout.user_id = 85
group by m_exercise.id
```
Typeorm code:
```typescript
this.createQueryBuilder('m_exercise')
      .innerJoin('m_exercise.workoutProgramExercises', 'w_program_exercises')
      .innerJoin('w_program_exercises.workoutExercises', 'w_exercises')
      .innerJoin('w_exercises.workout', 'workout')
      .where(`workout.status = ${2}`)
      .andWhere(`workout.user_id = ${userId}`)
      .groupBy("m_exercise.id")
      .getMany();
```

When I try to run this "Typeorm code", it gives me an error: 

> error: column "w_program_exercises.id" must appear in the GROUP BY clause or be used in an aggregate function

Typeorm generates following sql code:
```SQL
SELECT "m_exercise"."id" AS "m_exercise_id", "m_exercise"."name" AS "m_exercise_name", "m_exercise"."key" AS "m_exercise_key", "m_exercise"."sensor" AS "m_exercise_sensor", "m_exercise"."mode" AS "m_exercise_mode", "m_exercise"."machine_type_id" AS "m_exercise_machine_type_id", "m_exercise"."feet_position_id" AS "m_exercise_feet_position_id", "w_program_exercises"."id" AS "w_program_exercises_id", "w_exercises"."id" AS "w_exercises_id", "workout"."id" AS "workout_id" 
FROM "machine_exercises" "m_exercise" 
INNER JOIN "workout_program_exercises" "w_program_exercises" ON "w_program_exercises"."machine_exercise_id"="m_exercise"."id" 
INNER JOIN "workout_exercises" "w_exercises" ON "w_exercises"."workout_program_exercise_id"="w_program_exercises"."id" 
INNER JOIN "workouts" "workout" ON "workout"."id"="w_exercises"."workout_id" 
WHERE "workout"."status" = 2 AND "workout"."user_id" = 85 
GROUP BY "m_exercise"."id"
```

This SQL looks very similar to first sql snippet, except "SELECT" clause.
Typeorm adds additional fields into "SELECT":
- "w_program_exercises"."id" AS "w_program_exercises_id"
- "w_exercises"."id" AS "w_exercises_id"
- "workout"."id" AS "workout_id" 

The question: How can I get rid of these fields? When I use getRawMany() - it generates sql as I expect, but I receive an array of unmapped objects. I want to use getMany() and receive mapped objects.
 
Thanks!

**Comment by pleerock** [comment] 2018-01-31 06:41
@lightsuner the error you have is how sql in strict mode works. You need to add to group by things from joins.

> Typeorm adds additional fields into "SELECT":

it just selects what you need. There is a huge difference between '*' and selecting only needed data. You can try to change `innerJoin` to `innerJoinAndSelect`, this will select data from joined tables as well. But if you don't really need to select this data, its better if you add extra things into group by

**Comment by lightsuner** [comment] 2018-02-01 10:32
@pleerock thanks for your answer. 

My question concerns the work of typeorm, not sql.

So according to you post, there is only one way to make typeorm works as I needed. I have to add all fields form table m_exercise into groupBy, correct?

I still don't understand why **id columns** of joined tables (using **innerJoin**) added into **select** clause.

May be they are rudiments of innerJoinAndSelect method? 

Maybe the problem in this string or around - https://github.com/typeorm/typeorm/blob/bd44b2e371729d65c469059e2c70196fa57a80e4/src/query-builder/SelectQueryBuilder.ts#L1555 ?

Thanks.

**Comment by pleerock** [comment] 2018-02-05 10:34
What typeorm version are you using? I just run following code:

```ts
        await connection.manager
            .createQueryBuilder(Author, "author")
            .innerJoin("author.photos", "photo", "photo.name = :name", { name: "Me and Bears" })
            .getMany();
```

And it generates me following query:

```sql
SELECT "author"."id" AS "author_id", "author"."name" AS "author_name" FROM "author" "author" INNER JOIN "photo" "photo" ON "photo"."authorId"="author"."id" AND ("photo"."name" = $1) -- PARAMETERS: ["Me and Bears"]
```

e.g. no selects of joined data. Can you try latest version? If issue occur on you with the latest version as well, then I'll need a minimal reproduction git repo or PR with a failing test.

**Comment by pleerock** [comment] 2018-02-20 11:57
Closing as no answer from reporter.

**Closed by pleerock** 2018-02-20 11:57 UTC

**Comment by dengue8830** [comment] 2019-09-25 19:17
the issue is not `join`, is `groupby`. I created a more detailed report https://github.com/typeorm/typeorm/issues/4814
