### ISSUE TITLE
Question - entity relations 

### ISSUE THREAD

**Issue by ckalogeropoulos** [typeorm/typeorm#859] opened 2017-09-11 15:08 UTC
What is the expected behavior regarding the update of relations ? Are the inverse relations updated automatically ? What about their RelationId columns (assuming they are explicitly declared on the classes)

For example, assuming I have a master - detail relation as below (please note the Author and AuthorId columns - AuthorId exists on the class declaration)

```ts
@Entity("Persons")
export class Author {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column()
    Name: string;

    @OneToMany(type => Photo, photo => photo.Author) // Note: we will create author property in the Photo class below
    Photos: Photo[];
}

@Entity("Photos")
export class Photo {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column({
        length: 800,
        nullable: false
    })
    Name: string;

    @Column("text")
    Description: string;

    @Column()
    Filename: string;

    @ManyToOne(type => Author, author => author.Photos, {
        onDelete: "CASCADE"
    })
    Author: Author;

    @RelationId((photo: Photo) => photo.Author)
    AuthorId: number;

}
```
Assume that I load an author from DB and a photo using 2 distinct calls from their repositories.
The photo is not related to this author.

If I set the Author property on the photo instance would the AuthorId  contain the Id of the Author instance ? Will this happen automatically or I would have to set it manually ? Also is the Author.Photos updated so that it contains the linked photo ?

Also if I push a Photo instance to the author.Photos array, will the inverse relations be updated automatically (Author instance would contain the author and AuthorId will contain the Author.Id)

Thank you

**Comment by pleerock** [comment] 2017-09-11 16:42
> Are the inverse relations updated automatically

No. This would create a circular dependency which I would like to avoid, because most of the time people return object tree directly to client and circular relationship will bring them problems

> What about their RelationId columns (assuming they are explicitly declared on the classes)

RelationId columns are updated when you change relation, there is a test for this case, I dont remember where someone in `github-issues` directory

**Comment by iz-iznogood** [comment] 2017-09-11 19:05
Hmm, ok I just wanted to be sure what the expected behavior is.
However IMHO it would be best to update it both ways and create a proper toJSON or serialize or wrap method, since this can create inconsistencies on the model graph

For me I am good with how it works, I can handle it in my code, so I close the issue

Thank you

**Comment by pleerock** [comment] 2017-09-12 03:51
> I can handle it in my code

be careful, what you want to do may not fit orm design and you'll just bring problems yourself

> IMHO it would be best to update it both ways and create a proper toJSON or serialize or wrap method, 

Don't think its possible to effectively do it

> since this can create inconsistencies on the model graph

it can't be called graph actually... Keep in mind that orm does not use identity map to store all entities, and each loaded/joined entity is unique object even if it is same object, for example if you load post then join its categories and join same posts of categories, you'll have different instances of post, even if they are same in the database

**Comment by iz-iznogood** [comment] 2017-09-12 08:23
Thanks,

we use a number of extra layers on top of the orm depending on the task and in some cases it is useful to see the entities as a tree other (typeorm, sequelise) times as a graph (EF, Hibernate).

So we are good, you may close the issue

**Closed** 2017-09-12 08:25 UTC
Labels: question
