### ISSUE TITLE
Decorators not working

### ISSUE THREAD

**Issue by wangjiegulu** [typeorm/typeorm#5495] opened 2020-02-08 13:57 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Decorators working👇:

```ts
@Entity()
export class Person{
    @PrimaryGeneratedColumn()
    public id: number;
    @Column()
    public name: string;
}
```

But **NOT** working👇:

```ts
@Entity()
export class Person{
    constructor(
        @PrimaryGeneratedColumn()
        public id: number,
        @Column()
        public name: string
    ) {}
}
```

```
/xxxxxx/src/error/ColumnTypeUndefinedError.ts:9
        super();
        ^
ColumnTypeUndefinedError: Column type for Function#undefined is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
    at new ColumnTypeUndefinedError (/xxxxxx/error/ColumnTypeUndefinedError.ts:9:9)
    at /xxxxxx/src/decorator/columns/Column.ts:139:23
    at /xxxxxx/src/dal/db/entity/account.ts:12:37
    at DecorateConstructor (/xxxxxx/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/xxxxxx/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/xxxxxx/src/dal/db/entity/account.ts:4:92)
    at Object.<anonymous> (/xxxxxx/src/dal/db/entity/account.ts:83:20)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/xxxxxx/src/bll/accountService.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

The second way is more elegant.

**Comment by waynevanson** [comment] 2020-02-09 02:56
Put `super()` in the body and see if that works.

Do you have TSconfig decorator settings on?
Read each line of the error carefully.

**Comment by wangjiegulu** [comment] 2020-02-09 10:51
@waynevanson 
It is not a derived class, why should put the `super` in body?
![image](https://user-images.githubusercontent.com/5423194/74100755-23a8b980-4b6d-11ea-942c-57fcd14a8bd2.png)

My tsconfig:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "./build",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by waynevanson** [comment] 2020-02-10 03:25
Never mind, it wouldn't make sense as you said.

Maybe just manually assign it from the constructor. 
I feel like the docs don't mention doing it this way because it doesn't work.

**Comment by fullc0de** [comment] 2020-02-10 03:47
Have you ever seen any guide about using parameter decorators? I haven't seen yet. If there is no spec about that, this is not a bug. :-)

**Comment by jas777** [comment] 2020-02-12 13:11
Why would you want `@Colum` and `PrimaryGeneratedColumn`  in constructor anyways?

**Comment by fullc0de** [comment] 2020-02-13 02:10
@jas777 
If I may assume that, that feature would be convenience if it's present. Wouldn't that be all and nothing other than it? :-)

**Comment by wangjiegulu** [comment] 2020-02-15 03:47
@waynevanson @fullc0de @jas777 
I would like to be able to support declarations in constructors, which would obviously be more concise. Otherwise I would need to manually generate the constructor and maintain the parameters in the constructor when new property are added.

And the [Typescript Toolbox](https://marketplace.visualstudio.com/items?itemName=DSKWRK.vscode-generate-getter-setter) doesn't work well, it doesn't always generate the right constructor.

![image](https://user-images.githubusercontent.com/5423194/74581302-dbfcb480-4fe8-11ea-81cc-7f25b4991938.png)

![image](https://user-images.githubusercontent.com/5423194/74581305-e61eb300-4fe8-11ea-943b-7e89cc83bc66.png)

**Comment by wangjiegulu** [comment] 2020-02-15 03:51
@waynevanson @fullc0de @jas777 
If I don't generate the constructor. It is painful when generating instance, there is a risk of missing fields.

![image](https://user-images.githubusercontent.com/5423194/74581358-8d9be580-4fe9-11ea-9db6-faab5362adcd.png)

**Comment by fullc0de** [comment] 2020-02-16 14:33
I can understand your point of view. I also agree that it's a good idea to avoid misconfigurations of any instance by using designed constructor as if it's a constraint. I hope that function will be accepted soon. :-)

**Comment by wangjiegulu** [comment] 2020-02-19 01:57
@fullc0de Thanks!

**Comment by imnotjames** [comment] 2020-10-04 03:36
This is not currently possible because of typescript limitations.  The property name is not provided to us.

https://github.com/microsoft/TypeScript/issues/15904

Once this is fixed this feature will automagically start working

**Closed by imnotjames** 2020-10-04 03:36 UTC
