### ISSUE TITLE
findOneOrFail(null) or findOneOrFail(undefined) should throw error

### ISSUE THREAD

**Issue by lleohao** [typeorm/typeorm#4373] opened 2019-06-29 09:18 UTC
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
// category entity
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class CategoryEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        unique: true,
    })
    name: string;
}

// create one category
const  categryEntity = new CategoryEntity()
categryEntity.name = 'first';

await getRepository(CategoryEntity).save(categryEntity);

// findOneOrFail
const result = getRepository(CategoryEntity).findOneOrFail(null);
// expect throw error but result.toEqual(categryEntity)

```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by likyh** [comment] 2019-07-21 18:12
+1

**Comment by jelling** [comment] 2019-08-06 17:33
This needs to be fixed asap imo. If a null value is passed into a query TypeORM is retrieving a random record. This could cause serious data issues for someone.

**Comment by btorresbrandcoders** [comment] 2019-08-21 17:49
Can verify that the same issue is occurring with PostgreSQL as well. This is a serious bug and should be getting more attention. The fact that a random record is returned is very concerning.

**Comment by dtmzr** [comment] 2019-08-22 15:40
I recognized the same behavior on postgres.
I passed a parameter `id` straight to the method, whenever the id was undefined I had the same behavior. 
However, passing an object works.

```js
// This doesn't throw
function getCategoryById(id) {
  return getRepository(CategoryEntity).findOneOrFail(id);
}
```

```js
// This throws
function getCategoryById(id) {
  return getRepository(CategoryEntity).findOneOrFail({ id });
}
```

I think this is related to the method overloading [here](https://github.com/typeorm/typeorm/blob/d1594f5d41a35bac7bb99d4f00e76c2fb670ee17/src/repository/Repository.ts#L299-L319).

**Comment by mgibson91** [comment] 2019-10-16 18:55
As @dtmzr mentioned, I experienced the first record getting return even when where conditions weren't met using the following syntax:

`Entity.findOneOrFail({ where: { id: userId } })` (expected this to work from other typeorm experience.

It did however, work after removing the where:

`Entity.findOneOrFail({ id: userId })`

Confusing overloading

**Comment by imnotjames** [comment] 2020-10-07 07:27
duplicate of 2990

**Closed by imnotjames** 2020-10-07 07:27 UTC
Labels: bug, driver: mssql

**Comment by dtmzr** [comment] 2020-10-07 16:46
Hey, @imnotjames the # was missing and therefore was not referenced.

**Comment by imnotjames** [comment] 2020-10-07 17:41
Oops

duplicate of #2990

**Comment by apflieger** [comment] 2020-11-12 20:23
I just upgraded to 0.2.29 but it still happen 😢
