### ISSUE TITLE
Save is not working for ManyToMany relationship

### ISSUE THREAD

**Issue by oyakovVonage** [typeorm/typeorm#4951] opened 2019-10-22 16:17 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16`

Hi,
I'm having an issue when trying to save entity with ManyToMany relationship

My tables:
```sql
CREATE TABLE DB.students (
    student_id integer NOT NULL
);

CREATE TABLE DB.courses (
    course_id integer NOT NULL
);

CREATE TABLE DB.students_to_courses (
    student_id integer NOT NULL,
    course_id integer NOT NULL
);
```

My Entities:
```ts
@Entity('students')
export default class Student extends BaseEntity {
	@PrimaryGeneratedColumn({
		name: 'student_id'
	})
	id: number;

	@ManyToMany(type => Course)
	@JoinTable({
		name: 'students_to_courses',
		joinColumn: { name: 'student_id' },
		inverseJoinColumn: { name: 'course_id' }
	})
	courses: Course[];

	@OneToMany(type => StudentToCourse, stc => stc.studentID)
	studentToCourses: StudentToCourse[];
}
```

```ts
@Entity('courses')
export default class Course extends BaseEntity {
	@PrimaryGeneratedColumn({
		name: 'course_id'
	})
	id: number;
}
```

```ts
@Entity('students_to_courses')
export default class StudentToCourse extends BaseEntity {
	@PrimaryColumn({
		name: 'student_id'
	})
	studentID: number;

	@PrimaryColumn({
		name: 'course_id'
	})
	courseID: number;
}
```

When I run this command:
```ts
await student.save();
```

I'm getting this error:
```
ERROR:  missing FROM-clause entry for table "student_courses_rid"
```

The query that its generating:
```sql
SELECT Student_courses_rid.course_id AS "course_id", Student_courses_rid.student_id AS "student_id"
FROM "public"."courses" "courses" INNER JOIN "public"."students_to_courses" "Student_courses_rid"
ON (Student_courses_rid.student_id = $1 AND Student_courses_rid.course_id = "courses"."course_id")
ORDER BY Student_courses_rid.course_id ASC, Student_courses_rid.student_id ASC
```

Created a demo in [this repository](https://github.com/oyakovVonage/typeorm-bug)

**Comment by borodyadka** [comment] 2019-11-28 11:47
I'm facing the same problem. Related to #1668

**Comment by tomer-amir** [comment] 2019-11-28 12:41
any news about this?

**Comment by jeffreyschultz** [comment] 2020-06-23 01:17
I found a workaround that I described in #6138.

![image](https://user-images.githubusercontent.com/479560/85349918-b66b4480-b4cd-11ea-9f83-e154d7febe02.png)

**Comment by imnotjames** [comment] 2020-10-10 05:00
This looks not just related to but a duplicate of #1668 - anyone want to confirm that is or isn't the case?  Unless told otherwise I'm going to run under the assumption that it's the same issue & close this one.

**Closed by imnotjames** 2020-10-10 05:00 UTC
Labels: bug, driver: postgres

**Comment by imnotjames** [comment] 2020-10-10 05:05
Duplicate of #1668
