### ISSUE TITLE
Column `comment` not working in Postgres

### ISSUE THREAD

**Issue by goldcaddy77** [typeorm/typeorm#5906] opened 2020-04-19 16:11 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20`

**Steps to reproduce or a small repository showing the problem:**

In digging through the Postgres drive and QueryRunner, it appears that column comments are only supported if a column is being changed, not on a new table or added column:

https://github.com/typeorm/typeorm/blob/ee575570c72e7c45b286111e81fe5ee5d89dc021/src/driver/postgres/PostgresQueryRunner.ts#L765

Are column comments supposed to be supported in Postgres?

**Comment by zieglar** [comment] 2020-06-28 13:17
any update?

**Comment by imnotjames** [comment] 2020-10-12 05:52
duplicate of #4359

**Closed by imnotjames** 2020-10-12 05:52 UTC
Labels: bug, driver: postgres
