### ISSUE TITLE
Node v20.6: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by jorenvandeweyer** [typeorm/typeorm#10338] opened 2023-09-06 07:33 UTC
### Issue description

Class extends value undefined is not a constructor or null

### Expected Behavior

Just work like on node 20.5

### Actual Behavior

```
/usr/src/app/node_modules/.pnpm/typeorm@0.3.17_mysql2@3.6.0_pg-query-stream@4.5.3_pg@8.11.3_redis@4.6.8/node_modules/typeorm/connection/Connection.js:12
class Connection extends DataSource_1.DataSource {
                                      ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/typeorm@0.3.17_mysql2@3.6.0_pg-query-stream@4.5.3_pg@8.11.3_redis@4.6.8/node_modules/typeorm/connection/Connection.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/typeorm@0.3.17_mysql2@3.6.0_pg-query-stream@4.5.3_pg@8.11.3_redis@4.6.8/node_modules/typeorm/index.js:142:20)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.6.0
```

### Steps to reproduce

Upgrade to node 20.6

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Docker |
| Node.js version     | 20.6.0  |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by nfour** [comment] 2023-09-06 08:09
Can confirm occuring over weekend pulling with docker `FROM node:20-bullseye`

**Comment by JonasVannieuwenhuijsen** [comment] 2023-09-06 09:36
Same here

**Comment by tylerthecoder** [comment] 2023-09-06 13:35
Experiencing this issue as well. Downgrading fixed for me. Used `node:20-alpine` in docker

**Comment by ThatOneCalculator** [comment] 2023-09-06 18:27
Can seemingly reproduce on `node:latest`

**Comment by mohd-akram** [comment] 2023-09-08 10:12
Experiencing this too. The library is currently broken on Node.js 20.

**Comment by jorenvandeweyer** [comment] 2023-09-08 10:43
You can easily fix this by using node 20.5 @mohd-akram

**Comment by juergenzimmermann** [comment] 2023-09-08 12:20
@jorenvandeweyer Using Node 20.5 is neither a fix nor a workaround. When you are building a Docker image based on a distroless image , i.e. `gcr.io/distroless/nodejs20-debian11:nonroot`, the image won't work because the distroless image is updated to Node 20.6.0 :-(

**Comment by juergenzimmermann** [comment] 2023-09-08 19:50
After updating to Node 20.6.1 the issue is gone.

**Comment by ThatOneCalculator** [comment] 2023-09-08 21:38
Nice, altho #10344 should probably still be merged anyway.

**Comment by jorenvandeweyer** [comment] 2023-09-09 07:31
It seems like it was not a typeorm related bug. 

https://github.com/nodejs/node/issues/49497

**Closed** 2023-09-09 07:32 UTC
Labels: bug, requires triage

**Comment by benwiley4000** [comment] 2024-08-01 21:27
> It seems like it was not a typeorm related bug.
> 
> [nodejs/node#49497](https://github.com/nodejs/node/issues/49497)

Don't think so, I just switched to NodeJS version 20.16 and I still have the issue. It seems to be intermittent on my end, although it happens most of the time.

**Comment by chow5566** [comment] 2024-10-16 02:24
How exactly to solve this problem?
