### ISSUE TITLE
RepositoryNotFoundError thrown in serverless environment, despite entity being registered with connection options.

### ISSUE THREAD

**Issue by robguinness** [typeorm/typeorm#6940] opened 2020-10-20 12:25 UTC
**Issue type:**

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is a difficult-to-reproduce bug, but nonetheless, I will do my best to describe how it manifests for me. There are quite a few other related issues (e.g. #6332, #5676, #5592), each with different use cases but seemingly hitting the same underlying issue.

I am using TypeORM in a serverless environment (Vercel), and I sometimes get `RepositoryNotFoundError` when I try to interact with an entity, even though the entity is *definitely* registered in the connection options, which is why I consider this to be a bug.

After a lot of debugging, this is happening because `connection.hasMetadata()` returns false, which in turn means `connection.findMetadata()` is returning false. This ONLY happens when a connection is reused (i.e. `connectionManager.get(CONNECTION_NAME)`). When using a connection created using `connectionManager.create(..)`, this problem never occurs. For clarity, here is a simplified example how I am setting up the connection:

```ts
import { User } from "./backend/entities/user";

const CONNECTION_NAME = "default";
const databaseName = "demo";
const defaultMongoDbUri = `mongodb://localhost:27017/${databaseName}`;
const options: any = {
  type: "mongodb",
  synchronize: true,
  logging: false,
  migrations: ["src/migration/**/*.ts"],
  subscribers: ["src/subscriber/**/*.ts"],
  cli: {
    entitiesDir: "src/entity",
    migrationsDir: "src/migration",
    subscribersDir: "src/subscriber",
  },
  entities: [User],
  name: CONNECTION_NAME,
  url: defaultMongoDbUri,
};

export default async () => {
  let connection: Connection | undefined;
  const cm = getConnectionManager();
  if (cm.has(CONNECTION_NAME)) {
    connection = cm.get(CONNECTION_NAME);

    if (!connection.isConnected) {
      connection = await connection.connect();
    }
  } else {
    connection = await cm.create({...options,}).connect();
  }

  return connection;
};
```

The error is actually thrown when I try to use the registered entity, e.g.: `await User.findOne({email: "foo@example.com"})`. I am using the Active Record pattern, although I suspect the same would occur when calling `connection.getRepository(User)` when using the Data Mapper pattern.

What I think is happening is that in the serverless enviornment, the connection is cached in memory for some period of time, but the objects from the serverless function that consumes the entity are not necessarily cached. So when `connection.findMetadata(target)` is being called, the comparison `metadata.target === target` evaluates to false because these are two different objects (`metadata.target` being the cached object from the connection and `target` being the newer one created by the serverless function).

In my opinion, a strict equality comparison is too...well...strict for the purposes of `findMetadata()`. I am now using a monkeypatched version of findMetadata that compares on `metadata.target.toString() === target.toString()`, which seems to work OK. In issue #3427, it was suggested to compare on `metadata.target.name === target.name`, but this seems a bit too loose, and actually a PR with this change was reverted back in Feburary (#5486). Arguably, it would be better to compare on something more systematic than `target.toString()`, but perhaps discussion about an actual fix could be saved for later.

My main point is that strict equality is not really a good way to check whether an entity is registered in the connection, since in some environments the target objects stored in connection.entityMetadatas are not the same objects in memory as the imported entity classes.

**Comment by imnotjames** [comment] 2020-10-21 06:40
Wouldn't two entities with the same code but different files & locations then map to the same entity?

> My main point is that strict equality is not really a good way to check whether an entity is registered in the connection, since in some environments the target objects stored in connection.entityMetadatas are not the same objects in memory as the imported entity classes.

I think that's an impossible scenario for us to code against because - effectively - some environments break the rules to allow hot reloading & other performance hacks - and in those cases the entities aren't actually the same and the ORM mappings should be reloaded at that point anyway.

If you've got suggestions on paths forward which include less strict checks please open a PR and we can review it.

**Comment by imnotjames** [comment] 2020-10-21 06:41
Duplicate of #5676

**Closed by imnotjames** 2020-10-21 06:41 UTC

**Comment by robguinness** [comment] 2020-10-21 11:09
> Wouldn't two entities with the same code but different files & locations then map to the same entity?

Yes, they would, and I would think this would be the desired behavior of `Connection.hasMetadata()` and `Connection.findMetadata()`. I don't understand why they need to be the same object in memory (or rather references to the same object).

> I think that's an impossible scenario for us to code against because - effectively - some environments break the rules to allow hot reloading & other performance hacks - and in those cases the entities aren't actually the same and the ORM mappings should be reloaded at that point anyway.

I think the crux of the matter is when you define the two respective entities to be "the same". Do they have to be references to the same object in memory, or can they be equivalent entities, i.e. implementing equivalent entity defintions? The former seems to be overly restrictive and makes it impractical to use TypeORM in some environments (rebuilding the metadata every time you want to reuse a connection is not really feasible), whereas the latter seems (to me at least) to meet the requirements of hasMetadata/findMetadata.

> If you've got suggestions on paths forward which include less strict checks please open a PR and we can review it.

I can do this, but if you could first answer the above question, I would appreciate it. If the maintainers think that I am wrong in my understanding of what hasMetadata/findMetadata is aiming to do, then perhaps the PR is not needed.

**Comment by robguinness** [comment] 2020-10-23 06:49
Hi @imnotjames, any comments regarding above? :-)

**Comment by imnotjames** [comment] 2020-10-23 15:01
> Yes, they would, and I would think this would be the desired behavior of Connection.hasMetadata() and Connection.findMetadata(). I don't understand why they need to be the same object in memory (or rather references to the same object).

Same code, different files can have two different sets of entity metadata.  I can copy paste the same code a hundred times and then point them at different tables with the `@Entity` decorator.

If we could compare them without this and understand that they for sure have equivalent entity definitions.. yeah, we could make that happen.  But right now that's not possible - except by checking that they both reference the same entity.

Even In the scenario of hot reloading, the metadata could be the same but the code may have changed.

**Comment by robguinness** [comment] 2020-10-26 11:45
> Same code, different files can have two different sets of entity metadata. I can copy paste the same code a hundred times and then point them at different tables with the `@Entity` decorator.

When I wrote "equivalent entities, i.e. implementing equivalent entity defintions", I was assuming that the @Entity decorator is part of the entity definition.

Regarding the scenario of hot reloading, what we are doing in our project is rebuilding the metadata always when reusing a connection in local development mode (i.e. process.env.NODE_ENV === 'development'). But we want to avoid this in production mode, as it's quite expensive.
