### ISSUE TITLE
Incorrect data loading from JSON string for column type 'simple-json'. Why?

### ISSUE THREAD

**Issue by MWarCZ** [typeorm/typeorm#5501] opened 2020-02-10 12:52 UTC
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Why are some correct JSON values returned as Object when typeorm loading JSON string (simple-json)?
```ts 
JSON.parse('{"foo": "bar"}') // { foo: 'bar' }
JSON.parse('[ 1, 2, 3]') // [1, 2, 3]
JSON.parse('true') // true => But typeorm return: { }
JSON.parse('123') // 123 => But typeorm return: { }
JSON.parse('"message"') // 'message' => But typeorm return: { }
```
In my project, I noticed this strange behavior.
- Data inside entity is correct before saving.
- Inside database, data is also correct.
- But loaded entity has incorrect data.

_Example - Part of my problem:_
```ts

@Entity()
export class Foo {
  @Column('simple-json')
  returnValue: Json = false
} 

// ...

let foo = await connection.manager.save(new Foo())
// foo => Foo { returnValue: false }
// Inside DB => select 'foo'.'returnValue' from 'foo' => returnValue: "false"
let findFoo = await connection.getRepository(Foo).findOneOrFail()
// findFoo => Foo { returnValue: {} }
```

I looked into typeorm code and I found [explicit test on type Object](https://github.com/typeorm/typeorm/blob/8c67682fa41b8336cd96150baf654adcf5f954b5/src/util/DateUtils.ts#L180) before returning parsed values.

**Why is this behavior chosen?**

**Comment by zhangyy91** [comment] 2020-05-26 06:06
I met the same issue. According to the standards like [RFC 7159](http://www.ietf.org/rfc/rfc7159.txt), [ECMA-404](http://www.ecma-international.org/publications/standards/Ecma-404.htm), [ECMA-262](http://www.ecma-international.org/publications/standards/Ecma-262.htm), any JSON value is valid JSON text, including simple strings and numbers. But current behavior is against the standards and the [official document](https://typeorm.io/#/entities/columns-with-generated-values), 

> simple-json which can store any values which can be stored in database via JSON.stringify


Hope this issue can be fixed quickly.

**Comment by wodka** [comment] 2020-05-26 06:16
The error problem was introduced in pull request https://github.com/typeorm/typeorm/pull/4476

**Comment by zhangyy91** [comment] 2020-05-26 06:29
@wodka Thank you for the information. I just got the pull request and found the cause. I think this issue can be fixed without much effort.  According to the standards and documents, when retrieving simple-json columns, we can just use `JSON.parse()` to get the JSON value, if it fails,  `null` should be returned.

```
static stringToSimpleJson(value: any) {
  try {
    return JSON.parse(value);
  } catch (err) {
    return null;
  }
}
```

**Comment by dapriett** [comment] 2020-07-01 13:34
Greetings - is there a workaround for this issue?

**Closed** 2020-10-10 19:23 UTC
Labels: bug, driver: mariadb, driver: mysql, question
