### ISSUE TITLE
Where clause should error on unknown fields

### ISSUE THREAD

**Issue by glentakahashi** [typeorm/typeorm#5657] opened 2020-03-10 23:50 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Right now if you have an entity A with a relation to B, this will silently drop that part of the where clause and not throw any errors.

```
repo.find({
  where: {
    bId: 123
  }
}
```

It works if you do

```
repo.find({
  where: {
    b: {
      id: 123
    }
  }
}
```

However, this is an easy mistake to make.

I think TypeORM should throw warnings for unknown fields in the where clause and/or update the typings to not allow unknown fields.

**Comment by imnotjames** [comment] 2020-10-12 09:28
Duplicate of #3416

**Closed by imnotjames** 2020-10-12 09:28 UTC
Labels: bug
