### ISSUE TITLE
InsertResult.identifiers all have the same id

### ISSUE THREAD

**Issue by christophmayrhofer** [typeorm/typeorm#3741] opened 2019-03-01 20:13 UTC
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to get the assigned ids for new entries in a requests table:

 let { identifiers } = await createQueryBuilder().insert().into(Request).values(requests).execute()

Expected: 
To get an array with objects having ids corresponding to the ids in the DB.

Actual:
The resulting array has objects that have all the same id even though the ids are different in the DB.
The ids are all the same as the id assigned to the first row.

**Comment by robck** [comment] 2019-03-14 21:50
https://github.com/typeorm/typeorm/issues/2131

**Comment by Kononnable** [comment] 2019-04-20 22:42
Duplicate of #2131

**Closed by Kononnable** 2019-04-20 22:42 UTC
