### ISSUE TITLE
Severe performance issues with MongoDB standard query operations?

### ISSUE THREAD

**Issue by jrista** [typeorm/typeorm#7525] opened 2021-04-01 17:11 UTC
## Issue Description

We have been using TypeORM with both Azure SQL and a cloud MongoDB service for a number of months now. The project we are developing was slated for completion a couple weeks back, however we ran into a number of fairly severe performance issues. Some were just poor initial choices (i.e. running regexes for string replacements when much simpler and significantly faster alternatives were available). Having worked through all of the other performance issues, we've been left with one that has us rather puzzled.

When performing operations against a Mongo collection, such as `findOneAndUpdate` or `findOneAndReplace`, etc. With TypeORM's version of these methods, the total execution time is around 700-1100ms each. At first we thought we may have had a problem with indexing, so we added some indices, which did not seem to impact the performance of these operations at all. We tried with local DBs, remote DBs, with very little to no change in the actual execution time of each operation. That alone was somewhat baffling, as we figured with a local DB running at localhost would have significantly less network latency than a mongodb server hosted in the cloud somewhere. 

We finally dug around into the guts of TypeORM's code, figured out how to get ahold of the underlying MongoDB driver, and used that directly instead of going through TypeORM. The results were dramatic. Execution times dropped to around 30ms at the high end, and as little as 8ms on the low end (for the local DB, remote was more around the 30ms mark). 

This seemed to indicate that the performance bottleneck was not in the DB, as we had originally thought, but in TypeORM itself. Introducing TypeORM added a two to even three orders of magnitude reduction in execution times over using the underlying mongodb driver directly. That is hugely significant for our particular project, which is responsible for processing potentially tens of thousands of messages per job, and each job must run through a multi-stage workflow in a matter of minutes. At 700ms or more, our jobs were operating at a message rate as little as 0.2msg/sec, whereas with direct driver usage, our message rate increased to the 30-60msg/sec range. That is 150-300 times faster when TypeORM is not doing...well, whatever it is doing! 

Our object model is relatively simple. We don't have that many entities, and only a couple of them have any kind of nested child entities (MognoDB), and none of them actually have any relationships with other entities. The entities that actually have exhibited the most significant performance issues are extremely simple, small objects that have 3-4 properties each. We create them, then as the workflow progresses, we update a status property and possibly an error property on each one, for each message we process at each stage of the workflow. Very, very simple stuff, which is why we are so baffled by the massive performance hit of using TypeORM.
 

### Expected Behavior

Execution times of simple operations like `findOneAndUpdate`, etc. complete within a similar timeframe as directly using the mongodb driver directly.

### Actual Behavior

Execution times of simple operations like `findOneAndUpdate` take two to three orders of magnitude more time to run with TypeORM than the underlying mongodb driver. Where the driver may execute on the order of a few low tens of milliseconds, TypeORM increases the execution time to the order of hundreds to thousands of milliseconds. Performance may vary slightly with the underlying driver (likely due to varying network latency), with request times <10ms to maybe 30ms, whereas for any given operation with TypeORM, the execution times are usually quite stable (~695ms, or ~1105ms) fluctuating only slightly with variations in network latency. 

### Steps to Reproduce

1. Create a simple entity as depicted below
2. Create a thousand of these entities
3. Update each of these entities (in any random order, even)

Very basic entity:
```typescript
@Entity('itemprogress')
@Index(['jobId', 'itemId'], { unique: true })
export class ItemProgress {
  @ObjectIdColumn() _id: ObjectID;
  @Column() jobId: ObjectID;
  @Column() itemId: string;
  @Column() status: ItemStatus;
  @Column() details?: any;
  @Column() error?: any;
}

export enum ItemStatus {
  identified = 'IDENTIFIED',
  chunked = 'CHUNKED',
  parsed = 'PARSED',
  staged = 'STAGED',
  published = 'PUBLISHED'
}
```

Basic service:
```typescript
@Injectable()
export class ItemProgressService {
  constructor(
    @InjectRepository(ItemProgress, 'mongo-dev')
    private readonly repo: MongoRepository<ItemProgress>,
  ) {}

  createSlowish(jobId: string, itemId: string) {
    // This is not exactly fast, either...but, we kind of need the full, rich entity that TypeORM gives us in the end...we need this to be faster, too!
    return this.repo.updateOne(
      {
        jobId: new ObjectID(jobId),
        itemId,
      },
      {
        $setOnInsert: {
          jobId: new ObjectID(jobId),
          itemId,
          status: ItemStatus.identified,
        },
      },
      { upsert: true },
    );
  }


  async updateFast(jobId: string, itemId: string, status: Partial<ItemProgress>) {
    const find = { jobId: new ObjectID(jobId), itemId };
    const update = { $set: { ...status } };

    const res = await this.getCollection().findOneAndUpdate(find, update);
    return { // Hacky! Would be nice if TypeORM findOneAndUpdate was fast, so we didn't have to hack this up!
      jobId,
      itemId,
      ...status,
    };
  }

  async updateVerySlow(jobId: string, itemId: string, status: Partial<ItemProgress>) {
    const find = { jobId: new ObjectID(jobId), cardNumber };
    const update = { $set: {...status} };

    return this.repo.findOneAndUpdate(find, update); // This is 2-3x slower than the fast version!
  }

  private getCollection(): Collection<ItemProgress> {
    const client = (this.repo.manager.connection.driver as MongoDriver).queryRunner.databaseConnection;
    return client.db().collection('itemprogress');
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS X 10.15.7  |
| Node.js version     | v14.15.5 |
| Typescript version  | v3.9.7 |
| TypeORM version     | v0.2.32 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment] 2021-07-11 05:16
Pretty sure this is a duplicate of #2381

**Comment by imnotjames** [comment] 2021-07-11 05:16
Duplicate of #2381

**Closed by imnotjames** 2021-07-11 05:16 UTC
Labels: bug, driver: mongodb, requires triage
