### ISSUE TITLE
How to skip foreign key generation？

### ISSUE THREAD

**Issue by zeromake** [typeorm/typeorm#4675] opened 2019-09-01 09:51 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**user.ts:**
``` ts
@Entity({
  name: "users",
})
export default class User {
  @Column()
  public username: string;
  @Column({
    select: false,
  })
  public password: string;
}
```
tag.ts
``` ts
import { Entity, Column, OneToOne, JoinColumn } from "typeorm";
import User from "./user";

@Entity({
  name: "tags",
})
export default class Tag {
  @Column()
  public name: string;

  @Column()
  userId: number;

  @OneToOne(() => User)
  @JoinColumn()
  public user: User;
}
```
**users1567330663459.ts:**
``` ts
class users1567330663459 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `tags` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `userId` int NULL, UNIQUE INDEX `REL_92e67dc508c705dd66c9461557` (`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `tags` ADD CONSTRAINT `FK_92e67dc508c705dd66c94615576` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `tags` DROP FOREIGN KEY `FK_92e67dc508c705dd66c94615576`");
        await queryRunner.query("DROP INDEX `REL_92e67dc508c705dd66c9461557` ON `tags`");
        await queryRunner.query("DROP TABLE `tags`");
        await queryRunner.query("DROP TABLE `users`");
    }
}
```

How to skip foreign key generation？
I just want to keep the code logically model related.

**Comment by thomasrobin94** [comment] 2020-05-25 08:42
+1 same problem

**Comment by motoyasu-yamada-liberapp** [comment] 2020-05-26 12:22
+1 same problem

**Comment by xuangong** [comment] 2020-06-01 10:38
+1 same problem

**Comment by PadraigGalvin** [comment] 2020-07-25 12:41
There is an existing feature request here: https://github.com/typeorm/typeorm/issues/3120

**Comment by imnotjames** [comment] 2020-10-14 05:42
Duplicate of #3120

**Closed by imnotjames** 2020-10-14 05:42 UTC
Labels: comp: migrations, comp: schema sync, driver: mariadb, driver: mysql, question
