### ISSUE TITLE
repository.findOne(entity.constructor) returns an entity even if FindConditions don't exists

### ISSUE THREAD

**Issue by carlosdubus** [typeorm/typeorm#3455] opened 2019-01-18 19:31 UTC
**Issue type:**

[x] question
[x] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I know I should provide User class itself to findOne, but I found myself using obj.constructor to save an entity. Looks like TypeScript skips the type validation of FindConditions\<T\> because T is an {} I think. Nevertheless it shouldn't return an entity that does not match the FindConditions provided. Correct me if I'm wrong. Thanks!
```
import {Entity, PrimaryGeneratedColumn, Column, getManager, createConnection} from "typeorm";

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
}

async function main() {
    await createConnection(); // create connection somehow
    var search = {fieldNotExists: "1"}; // field does not exists on User class
    var user = new User();
    var r = await getRepository<User>(user.constructor).findOne(search);
    console.log(r); // returns first entity of table instead of undefined
}

main();

```

**Comment by vlapo** [comment] 2019-01-18 19:49
Duplicate of https://github.com/typeorm/typeorm/issues/3416. We just discuss about this problem. Unknown fields are stripped from query so result condition is `{}` and it is returned first entity in table.

**Closed by vlapo** 2019-01-18 19:49 UTC
Labels: duplicate
