### ISSUE TITLE
Setting schema option on @Entity messes migrations up

### ISSUE THREAD

**Issue by adrienbarreau** [typeorm/typeorm#6058] opened 2020-05-13 16:44 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^6.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1- Create an entity with the schema option
```ts 
@Entity({ name: 'stuff', schema: 'public' })
```

2- Generate migration using typeorm cli tool.
```shell
typeorm migration:generate YourMigration
```

3- Add a new field to you entity
```ts 
@Column({ nullable: true })
newField: string;
```

4- Generate migration using typeorm cli tool.
```shell
typeorm migration:generate YourOtherMigration
```

**Expected behaviour**: to have a new migration file with only one query that add the newField to the stuff table

**What I have**: a new migration file with the same CREATE TABLE and others queries that are already in the previous migration file..

**Comment by imnotjames** [comment] 2020-10-14 06:15
Duplicate of #5632

**Closed by imnotjames** 2020-10-14 06:15 UTC
Labels: bug, comp: migrations, driver: postgres
