### ISSUE TITLE
TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'

### ISSUE THREAD

**Issue by ghost** [typeorm/typeorm#3194] opened 2018-12-04 07:42 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am trying to build an API with typeorm and type-graphql. The following code should work, but it gives me a strange error: `[at-loader] TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.`

```ts
import { Resolver, Mutation, Query, Arg, Ctx } from "type-graphql";
import { MongoRepository } from "typeorm";
import { InjectRepository } from "typeorm-typedi-extensions";
import { User } from "../entities/user";

@Resolver(of => User)
export class UserResolver {
  constructor(
    @InjectRepository(User) private readonly userRepository: MongoRepository<User>
  ) {}

  @Query(returns => User, { nullable: true })
  userBySlug(@Arg("slug") slug: string) {
    return this.userRepository.findOne({slug});
  }
}
```
It works just fine, if I use `Repository` instead of `MongoRepository`, and I've found a way to circumvent this by calling `createEntityCursor(query)`, but I want to use projections in my queries. The projection object cannot be passed to `createEntityCursor()`, and `find()` & `findOne()` methods raise that `TS2321` error. I've also found [this typescript issue](https://github.com/Microsoft/TypeScript/issues/21592), but I am unsure what to do next. Is there a way to get pass this error?

**Comment by pleerock** [comment] 2019-01-08 07:59
Have no idea. @dverlik did you figure this out?

**Comment by dverlik** [comment] 2019-01-11 13:57
@pleerock Well, I injected both `MongoRepository` and `Repository`. The solution is shitty, but it works.

At some other projects I gave up and moved to MySQL.

**Comment by pleerock** [comment] 2019-01-13 15:34
Im sorry about your experience but glad that you moved to relational database haha. I'll close it, if somebody reproduce this error please provide some example.

**Comment by oDjonathanKrause** [comment] 2019-01-13 23:00
Same _Excessive stack depth comparing types 'T' and 'DeepPartial<T>'_ error with MySQL here.

```
 public async create(obj: T): Promise<T> {
    const connection = await DatabaseProvider.getConnection();
    return await connection.getRepository(this.entity).save(obj);
  }
```

**Comment by pleerock** [comment] 2019-01-14 05:55
@oDjonathanKrause please provide some reproduction

**Comment by oDjonathanKrause** [comment] 2019-01-14 17:31
**Database system/driver:**
[x ] mssql

**TypeORM version:**
[x] latest

**Steps to reproduce the error:**
I was trying to build a Service class to generalize some methods that access the database.

But if the class model its passed by param using it to get the repository and save, The error it's throwed _"Excessive stack depth comparing types 'T' and 'DeepPartial<T>'. [2321]"_.

The workaround was to create an instance of the Model on the constructor the generic class, clone it and pass the attributes of param object to the cloned object before save.

```
export class Service<T>  {
  instanceOfEntity: any;
  constructor(private entity: { new(): T }) { 
    this.instanceOfEntity = new entity;
  }
  
  // Doing by this way I had some problems on save.
  public async create(obj: T): Promise<T> {
    const connection = await DatabaseProvider.getConnection();
    return await connection.getRepository(this.entity).save(obj);
  }

 // workaround
 public async create(obj: T): Promise<T> {
    let newObj = this.clone(this.instanceOfEntity);
    for(let property in obj) {
      newObj[property] = obj[property];
    } 

    const connection = await DatabaseProvider.getConnection();
    return await connection.getRepository(this.entity).save(newObj);
  }

  public clone<T>(instance: T): T {
    const clone = new (instance.constructor as { new (): T })();
    Object.assign(clone, instance);
    return clone;
  }
}

```

**Comment by rewieer** [comment] 2019-03-15 11:14
Same problem

**Comment by MSafter** [comment] 2019-06-14 13:24
Updating ts-node to 8.2.0 solved it for me!

**Comment by Army-U** [comment] 2019-08-29 06:01
Skip this problem temporarily by setting `skipLibCheck: true` in `tsconfig.json`.

**Comment by eugenchio** [comment] 2019-08-29 08:07
The error occurs for me after updating to newest release of TypeScript@3.6.2. With TypeScript@3.5.3 everything works fine.
@Army-U , thanks your suggestion works. But it doesn't seem to be a good solution :(

**Comment by bennyn** [comment] 2019-08-29 08:44
Same error (TS2321) shows up in my application with TypeScript 3.6.2 while using `@nestjs/core` which supports TypeORM. Seems like there is something going on: https://github.com/nestjs/nest/issues/2834

**Comment by guillaume-roy** [comment] 2019-08-29 09:39
We've just downgraded to typescript@3.5.3 to solve the issue.
See : https://github.com/Microsoft/TypeScript/issues/29112

**Comment by rubiin** [comment] 2019-08-30 10:29
Seems like an issue with the latest typescript version, for the time being decided to stick to typescript 3.5.3

**Comment by charlex** [comment] 2019-08-31 19:58
Also seeing this, and will stick to typescript@3.5.3

**Comment by pairmix** [comment] 2019-09-01 09:51
i'm using typescript@3.5.3 but i still get this issue.
````
C:\Data\Projects\nestjs (master -> origin)
λ npm run build

> pairmix@0.0.1 build C:\Data\Projects\nestjs
> tsc -p tsconfig.build.json

error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.

node_modules/typeorm/repository/MongoRepository.d.ts:12:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

12 export declare class MongoRepository<Entity extends ObjectLiteral> extends Repository<Entity> {
                        ~~~~~~~~~~~~~~~


Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pairmix@0.0.1 build: `tsc -p tsconfig.build.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pairmix@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

**Comment by pairmix** [comment] 2019-09-01 10:41
I upgraded to latest versions, error is more precise:
"@nestjs/typeorm": "^6.1.3",
"typescript": "3.6.2",

````
> pairmix@0.0.1 build C:\Data\Projects\nestjs
> tsc -p tsconfig.build.json

error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.

node_modules/typeorm/repository/MongoRepository.d.ts:12:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

12 export declare class MongoRepository<Entity extends ObjectLiteral> extends Repository<Entity> {
                        ~~~~~~~~~~~~~~~

node_modules/typeorm/repository/MongoRepository.d.ts:45:5 - error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.

45     findOne(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>): Promise<Entity | undefined>;
       ~~~~~~~
````

**Comment by lukejagodzinski** [comment] 2019-09-03 00:46
I have the same error. The weird thing is that it shows `MongoRepository` error and I'm not even using MongoDB... I'm using Postgres. Moreover, the weird thing is that it doesn't happen all the time. It started happening after I moved into mono repository. My package that I'm trying to build consists only of the model definitions and migrations. Nothing else. For now I had to use the `skipLibCheck` option.

**Comment by sgronblo** [comment] 2019-09-03 04:30
I'm trying to use FoalTS which includes typeorm and immediately encountered the same `MongoRepository` "Excessive stack depth" issue as well.

**Comment by MichaelHindley** [comment] 2019-09-05 18:58
Same error on 3.6 when using `repository.find()` with postgres, reverting to 3.5 fixes it.

**Comment by bennyn** [comment] 2019-09-05 19:26
@pleerock can you reopen this ticket?

**Comment by eropple** [comment] 2019-09-08 16:42
FWIW, this error does _not_ occur when using `typeorm@next`.

**Comment by bennyn** [comment] 2019-09-09 11:52
> FWIW, this error does not occur when using `typeorm@next`.

I can confirm that the issue seems to be fixed in typeorm v0.3.0-alpha.23 :)

**Comment by pairmix** [comment] 2019-09-09 12:13
Moreover, it seems that typeorm v3 consumes more less memory (divided by 4 in my case !!!).
Great!!!

**Comment by lookfirst** [comment] 2019-09-10 12:27
v0.3.0-alpha.23 aka next, is currently `This branch is 81 commits ahead, 346 commits behind master.`. Any way to get this to work without having to resort to @next?

**Comment by alexmantaut** [comment] 2019-09-23 02:43
@lookfirst does Typescript 3.6.3 fix the issue for you?

**Comment by lookfirst** [comment] 2019-09-23 03:25
@alexmantaut Thanks. While Typeorm is pretty good, I've moved onto a new [ORM library](https://github.com/mikro-orm/mikro-orm) that resolves some of the other TypeORM issues I've found as well, namely around object persistence.

**Comment by fullstackwebdev** [comment] 2019-09-29 03:37
@alexmantaut
typescript 3.6.3 did not fix the issue

**Comment by pwwolf** [comment] 2019-11-06 14:22
I just tried Typescript 3.7.2 to see if it fixed this, and it did not.

**Comment by netpoe** [comment] 2020-03-22 02:25
> @alexmantaut
> typescript 3.6.3 did not fix the issue for me

Me neither, I'm at ^3.8.3

**Comment by imnotjames** [comment] 2020-10-16 04:44
I cannot replicate this.

Can someone create a repository that replicates this problem?

**Comment by peisenmann** [comment] 2021-05-04 20:11
Related to https://github.com/microsoft/TypeScript/issues/34933

**Comment by imnotjames** [comment] 2021-06-25 05:25
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment] 2021-06-25 05:26
Pretty sure this is a typescript issue, though, which was linked.  If you believe it isn't, please create a new issue with a reproducible example.

**Closed by imnotjames** 2021-06-25 05:26 UTC
Labels: bug, driver: mongodb, needs more info

**Comment by S-a-k-s-h-i** [comment] 2021-09-15 04:38
Hello everyone,  getting this error :  
- error TS2321: Excessive stack depth comparing types 'any' and 'FindConditions<T>'.
#11 186.9
#11 186.9 48     return await this.entity.find(relations);
This is the code that is giving error
  public async findWithRelations(relations: any): Promise<T[]> {
    return await this.entity.find(relations);
  }

**Comment by almandoro** [comment] 2021-12-13 18:14
For those, that experience the issue in VSCode and `eslint` / `tsc` works fine:
make sure to choose the workspace version of TS

<kbd>CMD </kbd> + <kbd>P</kbd> : `>Select typescript Version`

![image](https://user-images.githubusercontent.com/49877673/145863517-76edbe3a-32a3-415a-a410-e0a8778f50d3.png)
