### ISSUE TITLE
Duplicate column alias

### ISSUE THREAD

**Issue by awn70** [typeorm/typeorm#1969] opened 2018-04-19 15:19 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The buildColumnAlias function in SelectQueryBuilder tends to return duplicate column alias names. If the columnAliasName is more than 29 chars long you get the table alias and 2 chars from the column name: 
e.g. MyLongTableOrClassName_MyLongColumnName -> MyLongTableOrClassName_MY

**Comment by josephktcheung** [comment] 2018-04-21 01:15
Related to https://github.com/typeorm/typeorm/issues/1785?

**Comment by pleerock** [comment] 2018-04-23 06:09
We are aware about this issue, however its all about Oracle's limitation on alias names. Solution is to use shorter alias when you create a query builder, e.g. createQueryBuilder("shorter") and obviously don't use too long column names.

**Comment by awn70** [comment] 2018-04-23 06:35
@josephktcheung Yes, same problem as #1785 

@pleerock Why don't you use something like string-hash to generate unique alias names. Or the first n chars from the original column name and append a generated hash to make them unique?

**Comment by awn70** [comment] 2018-04-23 08:07
Ok.
I thought about something like this:
```javascript
// original code for hash function from https://github.com/darkskyapp/string-hash
// creates hashes from 0 to 4294967295
function hash( str ) {
    let hash = 5381,
        i = str.length;

    while( i ) {
        hash = ( hash * 33 ) ^ str.charCodeAt( --i );
    }
    return hash >>> 0;
}

function calcAlias( tableName, columnName ) {
    let h = hash( tableName + "." + columnName );
    return columnName.substr( 0, 19 ) + "_" + h;
}

calcAlias( 'MY_LONG_TABLE_NAME', 'MY_VERY_LONG_COLUMN_NAME' );
// -> MY_VERY_LONG_COLUMN_526535556
```
Maybe it helps...

**Comment by wdmcgrory** [comment] 2018-08-26 11:27
I implemented  the hash correction suggested by @awn70, and this appears to take care of my issues anyway. 

Note that i had to replace the long alias for oracle in SelectQueryBuilder, RelationIdLoader, and RawSqlResultsToEntityTransformer

@pleerock, was I just lucky? or have a made substitutions in all the correct places?

**Comment by lostintime** [comment] 2018-08-29 11:14
Just hit the same issue - duplicate select column aliases, caused by long table and field names, and [StringUtils.abbreviate](https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/util/StringUtils.ts#L35-L40) function doesn't help because field names are all in UPPERCASE (ex: `MYLONGFIELDNAME`).

The easiest workaround I found is to set `join.alias` value in `repository.find()` options, ex: 

```typescript
  connection.getRepository(MyEntity).find({
    join: {
      alias: "MA"
    },
    skip: 0,
    take: 30
  })
```
This will still not help you if your column name is longer than `29 - join.alias.length - "_".length`.

Using camelCase column names doesn't work either because oracle treats quoted column names in case-sensitive manner.

Maybe having an optional `alias` field in `@Column` definition options may help, ex: 
```typescript
@Column("number", { name: "MYLONGCOLUMNNAME", alias: "MLCN" })
myLongColumnName!: number
```
Dunno how this may affect all the code.

**Comment by otonielguajardo** [comment] 2019-06-27 04:36
Any update on this?

**Comment by cesc1802** [comment] 2020-04-22 03:35
seem don't have any solution for this issue. i also have the same issue when using it with oracle db

**Comment by eslevy17** [comment] 2020-07-14 18:33
@pleerock

Putting in a vote for this issue as well. This problem has happened with every function I've written with TypeORM, and leads to data corruption just about every time, and is only saved if the database has constraints to protect it. It creates incorrect IDs, overwrites one value with another, and completely screws everything up. It's dangerous to use this ORM in this form. It's not a feature that would be a nice perk, but the difference between having a usable product, or screwing up customer data and getting sued.

If you have long column names, you're going to get corrupt data. The only way around it is if you use createQueryBuilder() every time, use short alias names, and do a manual insert() statement instead of a save(). The syntax is far more verbose, and everyone just has to know to do it that way, and ignore the documentation on TypeORM.io.

Just make the alias names unique. It'll solve this problem and won't destroy the integrity of the data.

**Comment by mohamed-badaoui** [comment] 2020-09-04 10:09
Alias naming is still an issue on typeorm, and NOT only in case of long naming table/column.
Let's take a simple example with 2 tables with a OneToOne cardinality: 
article(#id, category_id., ..) and article_category(#id, ...).
So one article has only one category. 

a findOne will generate alias naming like that :
`Article`.`category_id` AS `Article_category_id`,
`Article_category`.`id` AS `Article_category_id`,

And so an error:
QueryFailedError: Duplicate column name 'Article_category_id'

**Comment by imnotjames** [comment] 2020-10-05 04:10
@mohamed-badaoui that's a separate issue.  Please open a new issue for that.

**Comment by imnotjames** [comment] 2020-10-05 04:10
This has been fixed as of the latest TypeORM version.  As such I'll be closing it.  If you find a regression or any other related issues please open a new issue.  Cheers!

**Closed by imnotjames** 2020-10-05 04:10 UTC
Labels: comp: query builder, driver: oracle
