### ISSUE TITLE
migrations generated by typeorm are not database agnostic

### ISSUE THREAD

**Issue by kulak-at** [typeorm/typeorm#6187] opened 2020-06-03 16:11 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When generating migration files using ORM I would expect them to be database agnostic. Unfortunately, it seems that migration script generates plain SQL queries for the driver that migration happened to be running with. For example it generates SQL with datetime type for `@CreateDateColumn` when generating with sqlite driver which makes migration incompatible with postgresql.

**Comment by imnotjames** [comment] 2020-10-14 06:02
Duplicate of #3607

**Closed by imnotjames** 2020-10-14 06:02 UTC
Labels: bug, comp: migrations, driver: postgres, driver: sqlite
