### ISSUE TITLE
postgres DATE hydrated as DATETIME object

### ISSUE THREAD

**Issue by vance** [typeorm/typeorm#499] opened 2017-05-26 22:57 UTC
Similar to #49 the date string `2017-01-25` is getting converted to a js date object instead of a string formatted as a date. This incorrectly adds timezone information and localizes the time to midnight. 

output from postgres:
`2017-01-25`
expected js value:
`'2017-10-25'`
actual value:
`2017-01-25T00:00:00.000+8000`

**Comment by httpsOmkar** [comment] 2017-05-27 02:31
I guess this is not a bug cause when you you try to save the date into the date object then the  it saves the time explicitly. So you can try to change the date format Try this
```javascript
const yourDateObject = ... || new Date();
const dateFormatter = (date) => {
    var d = new Date(date),
        month = '' + (d.getMonth() + 1),
        day = '' + d.getDate(),
        year = d.getFullYear();

    if (month.length < 2) month = '0' + month;
    if (day.length < 2) day = '0' + day;

    return [year, month, day].join('-');
}
```
Ref: https://jsfiddle.net/abdulrauf6182012/2Frm3/

**Comment by pleerock** [comment] 2017-05-27 07:17
Its bug. As discussed earlier "date" and "time" should be stored and retrieved as strings. only "datetime" should be stored as date object. Fixed and will be released in `0.1.0-alpha.3`

**Closed by pleerock** 2017-05-27 07:17 UTC

**Comment by luchillo17** [comment] 2017-09-17 19:35
Is it fixed? for some reason in latest master commit ba90981dd30dfaf25ebe9b954d37645dc6ca8a64 testing complains with time shifted by 1 day.

Here's the current output:
![image](https://user-images.githubusercontent.com/9698639/30524143-9d86c6aa-9bb3-11e7-95be-16e84069adf7.png)

Ping @pleerock.

**Comment by pleerock** [comment] 2017-09-18 05:10
hmmm I just run this test and it seems its passing okay
