### ISSUE TITLE
[Bug] NODE_ENV doesn't work when schema sync & migration run

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#708] opened 2017-07-26 22:09 UTC
So i have this config:
```json
[
  {
    "type": "postgres",
    "entities": [
      "src/db/entity/*.js"
    ],
    "subscribers": [
      "src/db/subscriber/*.js,"
    ],
    "migrations": [
      "src/db/migration/*.js"
    ],
    "cli": {
      "entitiesDir": "src/db/entity",
      "migrationsDir": "src/db/migration",
      "subscribersDir": "src/db/subscriber"
    },
    "environment": "dev",
    "name": "default",
    "driver": {
      "type": "postgres",
      "host": "localhost",
      "port": 5432,
      "username": "aplicaciones2",
      "password": "thepassword",
      "database": "typeorm-dev"
    },
    "autoSchemaSync": true,
    "logging": {
      "logQueries": true,
      "logSchemaCreation": true
    }
  },
  {
    "type": "postgres",
    "entities": [
      "src/db/entity/*.js"
    ],
    "subscribers": [
      "src/db/subscriber/*.js,"
    ],
    "migrations": [
      "src/db/migration/*.js"
    ],
    "cli": {
      "entitiesDir": "src/db/entity",
      "migrationsDir": "src/db/migration",
      "subscribersDir": "src/db/subscriber"
    },
    "environment": "test",
    "name": "default",
    "driver": {
      "type": "postgres",
      "host": "localhost",
      "port": 5432,
      "username": "aplicaciones2",
      "password": "thepassword",
      "database": "typeorm-test"
    },
    "autoSchemaSync": true,
    "logging": {
      "logQueries": true,
      "logSchemaCreation": true
    }
  }
]
```
As you can see i've put some `environment` variables, however no matter which `NODE_ENV` i put, it still runs the `typeorm schema:sync` in both databases.

Also when i run `typeorm migrations:run` it only runs on the first database regardless of the `NODE_ENV` value.

**Note:** I've run `export NODE_ENV=dev` before and after of each of the commands above, as well as

**Comment by luchillo17** [comment] 2017-07-26 22:21
The culprit is this block of code that doesn't take in account the value of `NODE_ENV`:
https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L46-L53

**Comment by pleerock** [comment] 2017-07-27 09:22
duplicate of #705

**Closed** 2017-07-27 11:07 UTC

**Comment by luchillo17** [comment] 2017-07-27 12:37
Indeed duplicated, shame it's not supported any more, does it mean we need to specify the connection name each time instead of relying on the `NODE_ENV` value?

**Comment by pleerock** [comment] 2017-07-27 12:56
yeah, thats almost same as using `NODE_ENV`. Im sure you aren't using this functionality for production, right? Im assuming you are using it for test environment. For test environment you can create connection from another file

**Comment by pleerock** [comment] 2017-07-27 12:57
Maybe we can add functionality to load config from different files, like `ormconfig.test.json` or `ormconfig.prod.json` where `test` and `prod` are env variables

**Comment by luchillo17** [comment] 2017-07-27 13:18
Well my expectation was to have 2 connections, one for each env like `dev` and `test`, and run for that specific, but also have the `prod` one, with the difference that this one should hold more than one connection, thus making easy to deploy all migrations to all connections when deploying the app.

Basically i wanted to make a multi-connection server using the `createConnections` method spoken about in the [creating-connection](https://typeorm.github.io/connection.html#creating-connection) section of the docs, having JWT tokens hold the name of the connection of the logged user.

So i thought it would work good if i had all my clients server under the 'prod' environment and run each of them through migrations when deploying the code.

I guess i'll have to use gulp tasks to filter the migrations as well as deploying based on the environment, idk if the postfixed env files fit right with my attempt to use multiple connections at once.
