### ISSUE TITLE
Typesafe conditions for query builder

### ISSUE THREAD

**Issue by astashov** [typeorm/typeorm#1553] opened 2018-02-04 22:52 UTC
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Steps to reproduce or a small repository showing the problem:**

Thanks a lot for a great ORM, I love it!
One thing I'm somewhat missing though - for conditions (e.g. in `WHERE` statements) I still have to use strings, which is not typesafe. Would be cool to do somewhat similar to [JOOQ](https://www.jooq.org/doc/3.10/manual/sql-building/sql-statements/select-statement/#N41C21), like instead of:

```ts
const user = await userRepo.findOne({where: {login: "admin@example.com"}});
```

do something like:

```ts
const user = await userRepo.findOne({where: User.columns.login.eq("admin@example.com")})
```

or

```ts
let photos = await connection
  .getRepository(Photo)
  .createQueryBuilder()
  .where(
    Photo.columns.isPublished.eq(true).and(
      Photo.columns.name.eq("My").or(Photo.columns.name.eq("Mishka"))))
  .orderBy(Photo.columns.id, "DESC")
```

And if I e.g. pass some string instead of `true` to `Photo.columns.isPublished.eq`, I'll get a type mismatch error.

Wouldn't need to specify aliases too, they could be inferred from `Column` and `Table` instances, and generated automatically.

What do you think? Or maybe there's a feature like that already available in TypeORM or in progress?

Thanks!

**Comment by pleerock** [comment] 2018-02-05 04:48
The problem that those approaches will only work in very simple cases. QueryBuilder's purpose is not to limit you in what sql query you can build. We cannot have both functionality because sql is very dynamic and type system cannot cover all cases, it even cannot cover half of cases. That's basically the problem of having "type-safe query builder". We probably can implement *another* query builder, maybe even as an extension, but we need a good and working design proposal which cover all possible cases as much as possible. Duplicate of #128

**Comment by astashov** [comment] 2018-02-05 14:11
I see, thanks for the response!

The thing is - it may not cover all the cases, and it could still have an escape path as a regular string, but something, that covers like 95% would be still nice, IMHO.

It even could be a separate package, not inside `typeorm`, probably, which would just convert conditions to strings. There'd be a script, that generates typings from the database schema, then you include it, and use like:

```ts
import {PhotoTable} from "./db.generated"

let photos = await connection
  .getRepository(Photo)
  .createQueryBuilder()
  .where(
    PhotoTable.columns.isPublished.eq(true).and(
      PhotoTable.columns.name.eq("My").or(PhotoTable.columns.name.eq("Mishka"))).toSql())
  .orderBy(PhotoTable.columns.id.toSql(), "DESC")
```

What do you think?

**Comment by pleerock** [comment] 2018-02-05 19:09
TBH I don't find it better then exist query builder, you took a very simple query and it become like this... I imagine what it will look like if query become bigger and complexier

**Comment by ProTip** [comment] 2018-02-05 19:21
Hello,

I'd like to get a sense of the direction @pleerock and other top contributors feel this should go. After reading this and the other issue I'm seeing these two main approaches:

### fluent api
This could work with proxy objects similar to those generated by entity framework. It would require the use of methods like ```.equals()``` etc. 

### linq style
Conditional operator overloading is not available in javascript. This would require utilizing a third party package and/or AOC/JITing code to parse operator expressions and replace them with method calls.

Both seem entirely doable.

**Comment by pleerock** [comment] 2018-02-20 06:26
Let's continue discussion in the same tread #128 We need to make a real design proposal, because currently there are lot of words, but noone telling about how it really should look like.

**Closed by pleerock** 2018-02-20 06:26 UTC
