### ISSUE TITLE
String performance issues with RawSqlResultsForEntityTransformer.transform

### ISSUE THREAD

**Issue by cloutiertyler** [typeorm/typeorm#4201] opened 2019-05-27 19:42 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The function `RawSqlResultsForEntityTransformer.transform` has some pretty significant performance issues when doing simply queries with aliases on columns, for queries with joins no deeper than 3. The issue appears to stem from the use of RegExp to replace the column names in the raw sql results.

I have attached a flamegraph of the performance of our app and you can see that we spend most of our time doing various string manipulations. Happy to contribute to reduce the costs of these functions, but I wanted to know if this is something you guys are aware of. I didn't see anything in the issues.

[v8-3.json.zip](https://github.com/typeorm/typeorm/files/3224837/v8-3.json.zip)

You can drop that file (after unzipping it) in here to see the flamegraph: https://mapbox.github.io/flamebearer/

A lot of it does seem to stem from RegExp of the following form.

![image](https://user-images.githubusercontent.com/6432361/58437149-785ae180-807d-11e9-8427-3ce1e8a78c4e.png)

I believe these are the alias renaming expressions, correct?

**Comment by imnotjames** [comment] 2021-07-02 21:19
Duplicate of #3857

**Closed by imnotjames** 2021-07-02 21:19 UTC
Labels: driver: postgres, needs investigation, performance, question
