### ISSUE TITLE
Show warning message on wrong relation definitions

### ISSUE THREAD

**Issue by hrueger** [typeorm/typeorm#6438] opened 2020-07-21 14:20 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
(probably others, too)

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I just spent a whole afternoon figuring out, why my entities in a relation were saved, but not loaded. The problem was that I had the `ManyToOne` relation on both sides 😅.
It would be very useful if a warning / an error message was printed to the console in this case.

Example problematic code (taken from the example in the docs and modified):
```TypeScript
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import {User} from "./User";

@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    url: string;

    @ManyToOne(type => User, user => user.photos)
    user: User;

}

/// Entity 2 ///

import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import {Photo} from "./Photo";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => Photo, photo => photo.user) // this is supposed to be OneToMany not ManyToOne
    photos: Photo[];

}
```

**Comment by imnotjames** [comment] 2020-07-22 19:52
Are there any cases where this would be a wanted set of code?

Are there any other cases where we'd want to add some assertions as well? (Eg, one-to-one with a mismatch on the other side, or the same with many-to-many?)

**Comment by hrueger** [comment] 2020-07-23 10:10
> Are there any cases where this would be a wanted set of code?

I'm not sure but I don't think so. I couldn't load the relation no matter how I saved it (by adding entity 2 to entity 1 and saving entity 1 nor the other way round).

> Are there any other cases where we'd want to add some assertions as well? (Eg, one-to-one with a mismatch on the other side, or the same with many-to-many?)

Maybe show a warning message if the Entity Classes are not matching?
Example:
```TypeScript
    @ManyToOne(type => Photo, photo => photo.user)  // type is Photo here
    photos: SomeOtherEntity[]; // but not here
```

Could be helpful after copy and paste.

In addition, TypeORM could check for the ManyToOne Relation if the specified type is an array type:
```TypeScript
    @ManyToOne(type => Photo, photo => photo.user)
    photos: Photo[]; // right

    @ManyToOne(type => Photo, photo => photo.user)
    photos: Photo; // wrong
```

However, I think a warning message for the problem mentioned in the very first comment is the most helpful one.

**Comment by imnotjames** [comment] 2021-07-06 02:26
Duplicate of #5995

**Closed by imnotjames** 2021-07-06 02:26 UTC
Labels: driver: sqlite, new feature
