### ISSUE TITLE
Time zones for timestamp columns are incorrectly fetched and persisted in PostgreSQL

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#838] opened 2017-09-08 04:18 UTC
Hello!

I've encountered a strange behavior with `timestamp with time zone` columns in PostgreSQL. It looks like such columns are incorrectly fetched and persisted. I'm going to push the test to demonstrate the problem.

**Comment by slavafomin** [comment] 2017-09-08 04:38
When working through TypeORM entities this problem will not surface, because it looks like it has a symmetrical properties (i.e. two problems negate each other). But this becomes apparent when you insert data to the underlying database directly, e.g. through `psql`. The timestamps returned from TypeORM are actually off by some offset. You could also insert timestamp with `manager.save()` and then query the row directly with `pgsql` to see that persisted value is incorrect as well.

**Comment by pleerock** [comment] 2017-09-08 04:57
Can you provide a short examples of what you have, what you do, what is wrong and what is expected result? Looks like test you have added is passing

**Comment by pleerock** [comment] 2017-09-08 04:58
Ah, no. It says:

```ts
  1) github issues > #838 Time zones for timestamp columns are incorrectly fetched and persisted in PostgreSQL "before all" hook:
     DataTypeNotSupportedError: Data type "timestamp with time zone" is not supported in "mysql" database.
```

for some reason CI shows it as passing 😨

**Comment by pleerock** [comment] 2017-09-08 04:58
You need to enable only posgtres by using `enabledDrivers: ["postgres"]`

**Comment by slavafomin** [comment] 2017-09-08 05:37
The test should be able to explain the problem, but I will also add a step-by-step reproduction scenario:

1. Insert the timestamp `"1989-08-16T10:00:00+03:00"` to the PostgreSQL column with type `timestamp with time zone` directly through, e.g. `psql`.

2. Fetch the entity using ORM and examine the timestamp. It would be off by amount of hours in server's time zone offset.

---

1. Insert the timestamp `"1989-08-16T10:00:00+03:00"` to the PostgreSQL column with type `timestamp with time zone` using ORM.

2. Fetch the timestamp directly through, e.g. `psql` and examine it. Timestamp would be off by amount of hours in server's time zone offset.

--

I've also updated the test as you've suggested.

**Comment by slavafomin** [comment] 2017-09-11 14:16
Hello @pleerock! Has you been able to look into this? I think that severity of this problem is very high, because it could lead to a potential data corruption and business logic issues. I've implemented a workaround for our application, but I would be glad to assist in fixing it in the source.

**Comment by robinsummerhill** [comment] 2017-09-27 14:26
I've looked into this problem and can also reproduce the problem seen by @slavafomin.

The problem is this:

TypeORM adjusts values of 'date' type (Date, 'timestamp', 'timestamp with timezone' etc) to UTC before persisting them to the database [PostgresDriver.ts#293]. It also adjusts back to localtime when hydrating values from the database [PostgresDriver.ts#323]. So as long as we stay in TypeORM-land then everything is fine.

However, this client-side conversion is contrary  to how timestamp fields are expected to be used in Postgres and can cause problems when using other libraries or admin tools that are expecting you to follow the Postgres way.

Generally, `timestamp` (and `timestamp without timezone`) fields are used to store timestamps in localtime and no conversion to/from UTC should be performed by the client or server.

Conversely, `timestamp with timezone` are ALWAYS stored in UTC and Postgres will internally do a conversion to UTC on the supplied value (using it's timezone if specified or defaulting to the server timezone if not).

Because TypeORM is attempting to replicate behaviour that Postgres already does for `timestamp with timezone` fields then you can get into a situation where values look like they have been corrected for DST twice. e.g. For me, in London on BST, I store a time of 1:33pm and it end up in the database as 11:33am even though BST has only 1 hour difference from UTC.

I suggest that the TypeORM Postgres Driver should never try to adjust for UTC but should defer to Postgres. The default field type for dates should be changed to 'timestamp with timezone'. In the case where you really DO want to store local time, then you can by overriding the default column type by using `timestamp without time zone`

I have forked the project and am preparing a PR for this.

**Comment by pleerock** [comment] 2017-09-27 15:00
before continue discussion I would like to ask you @robinsummerhill did you take a look my comments in #839

**Comment by robinsummerhill** [comment] 2017-09-27 15:32
@pleerock I've commented on #839. Just to clarify, TypeORM is handling timezones in a non-standard way when it comes to the Postgres driver. This is fine as long as only TypeORM is reading and writing your data. But it should really handle this using Postgres's (admittedly confusing) timestamp fields in the way they were intended. i.e defer to Postgres to do UTC conversion and don't do it in TypeORM.

**Comment by robinsummerhill** [comment] 2017-09-27 15:44
Of course, any change to the current behaviour is likely to cause problems for people with existing databases. Not sure how to proceed. One possibility would be to leave the default behaviour as it is (fields are 'timestamp without time zone' unless explicitly specified and UTC conversion is done in TypeORM) but change the behaviour of explicit `timestamp with timezone` fields to defer the UTC conversion to Postgres.

**Comment by NoNameProvided** [comment] 2017-09-27 17:40
Encouraging usage of bad implementation is not so good so I would do the opposite. Fix the behavior and add an option to enable the old one.

**Comment by robinsummerhill** [comment] 2017-09-28 09:28
Thinking about this further, TypeORM should not be manipulating times for time zone adjustment at all for any database. A Javascript Date object should follow a straight path through TypeORM from the client to the database driver with no modification. A Javascript Date represents a unique instance in time internally as milliseconds since 1970-01-01T00:00:00Z and timezones do not come into it. It is only when you want to convert a Date to/from a string to show a human that timezones become an issue. Showing dates to users is the domain of the application and TypeORM should not be getting involved.

It also leads to subtle bugs. Consider this case: I have an application server in Boston, US (UTC-5) and another one in London(UTC+0) talking to a database in London(UTC+0). A user in Boston creates a new order in the system at 7:00am local time. This is 07:00-5 (equivalent to 12:00+0). TypeORM adds five hours to this and saves it into the database (12:00-5 or 17:00+0). For the user in Boston, when they want to retrieve this record, the Boston app server subtracts 5 hours and so everything works ok. But for a user in London, the London app server will adjust by zero hours and so will return a time that is incorrect.

Timezones are hard.

**Comment by slavafomin** [comment] 2017-09-29 14:42
Thank you guys for looking into it. I was really busy lately, so I couldn't investigate it further on my own. The explanation of @robinsummerhill makes total sense. And I agree with @NoNameProvided regarding the fix strategy. I think we should add a note in migration guide (this could be added to a changelog). The current version of the library is unstable according to the semver, so we are free to do any breaking changes at this point. It's a responsibility of the end-developer to manually upgrade the unstable dependencies. However, we should definitely warn them and advise some migration strategy. I think the affected fields could be healed by adjusting the value according to the timezone offset which was used (if all clients were using the same timezone offset). However, I'm not sure if it's possible to automatically find all such columns in the database and to update them. Maybe it could be done via some advanced PostgreSQL script, which we could attach to the migration guide.

**Comment by slavafomin** [comment] 2017-09-29 16:40
Actually, I've managed to write a script, which could be used to automatically update all `timestamp with time zone` columns in the specified schema of the database.

It first queries the `information_schema.columns` table, which contains the list of all columns and their respected types and then runs UPDATE statements in a loop to update data for each column.

You can pass schema name, sign and a timezone offset to it.

```sql
CREATE OR REPLACE FUNCTION healTimestamps (i_schema text, i_sign text, i_offset text)
RETURNS VOID
AS $$
DECLARE
  "table_name" text;
  "column_name" text;
  "sql" text;
BEGIN
  SET CONSTRAINTS ALL DEFERRED;
  FOR "table_name", "column_name" IN
    SELECT T."table_name", T."column_name" FROM "information_schema"."columns" T
    WHERE T."data_type" = 'timestamp with time zone' AND T."table_schema" = i_schema
  LOOP
    "sql" = 'UPDATE ' || quote_ident(i_schema) || '.' || quote_ident("table_name") || ' SET ' ||
            quote_ident("column_name") || ' = ' || quote_ident("column_name") || ' ' || i_sign || ' time ''' || i_offset || ''';'
    ;
     -- RAISE NOTICE '%', "sql";
    EXECUTE "sql";
  END LOOP;
END
$$ LANGUAGE plpgsql;

-- Call it: SELECT * FROM healTimestamps('public', '+', '03:00');

```

And a simple test:

```sql
CREATE SCHEMA ht;

CREATE TABLE ht.records (
  id integer PRIMARY KEY NOT NULL,
  date timestamp with time zone DEFAULT now() NOT NULL
);

INSERT INTO ht.records (id) VALUES (1);

SELECT * FROM healTimestamps('ht', '+', '03:00');
```

The only problem with it, is that it could stumble upon some strict constraint, which couldn't be deferred. It looks like PostgreSQL has no option to temporarily disable such checks.

**Comment by shousper** [comment] 2017-11-01 05:22
@pleerock Is there any update on this issue?

**Comment by priithaamer** [comment] 2017-11-03 06:04
Got temporarily around this by setting ‘process.env.TZ’ to ‘UTC’. It is suggested to set this environment variable before launching node process though.

**Comment by dkulchenko** [comment] 2017-11-30 19:14
@pleerock Any updates on this or any help wanted with a fix? This is a critical issue for us :/

**Comment by mwilniewiec** [comment] 2018-02-19 10:02
I also reproduce this issue and all my dates in postgres are wrong.
This kind of code is causing this problem:
https://github.com/typeorm/typeorm/blob/master/src/util/DateUtils.ts#L47-L56
It is creating new Date(...) which is a local time from UTC values.
new Date(Date.UTC(...)) should fix this thing but Im not sure if this is the only problem.

**Comment by Nopik** [comment] 2018-02-19 10:13
@robinsummerhill while it is true that change here will cause problems to existing users, I would say that keeping faulty implementation just because it had bug some time ago is even worse. And the problem is going to grow over time.

The v0.x is there for a reason, and I would suggest that with the upcoming 0.2.0 the changes should be done, with the migration stuff documented.

OR, at least do it in 2 steps: in 0.2.0 introduce a way to fix, with some warns/deprecations about upcoming default behaviour changes, and in 0.3.0 make it default.

**Comment by AlexMesser** [comment] 2018-03-20 16:59
Dates behavior changed in `typeorm@0.2.0-alpha.29`. Please check it via `npm i typeorm@next`

**Comment by pleerock** [comment] 2018-03-27 09:54
Released in master as well, please check and let us know if you still have issues.

**Closed by pleerock** 2018-03-27 09:54 UTC
Labels: needs more info

**Comment by neumartin** [comment] 2021-11-01 00:03
Can I configure a global session timezone with pg at driver level?

**Comment by NoNameProvided** [comment] 2021-11-02 11:42
@neumartin I cannot answer your questions sadly, but I suggest you to open a new issue instead of commenting on years old questions.

**Comment by Horseback-resplendent47** [comment] 2025-02-03 06:48
Here’s what https://stackdev.space/questions/storing-opening-hours-queries-in-a-postgresql-plpgsql-table I was looking for
