### ISSUE TITLE
Nested finds not working properly.

### ISSUE THREAD

**Issue by Yomanz** [typeorm/typeorm#6956] opened 2020-10-21 13:10 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When trying to perform a where on a nested object it's creating an invalid query.

The code
![image](https://user-images.githubusercontent.com/5119107/96723903-1227da80-13a7-11eb-82c7-2e366e665790.png)

The relation on the model the query is being performed on
![image](https://user-images.githubusercontent.com/5119107/96724083-57e4a300-13a7-11eb-883c-50b649bc138b.png)

The invalid query
![image](https://user-images.githubusercontent.com/5119107/96723939-1ce26f80-13a7-11eb-9a7e-daace88e0b5b.png)

It should be performing the `WHERE` on the groupId rather than the serverId.

If I need to give any more information please let me know.

```ts
-- PARAMETERS: ["ee168e43-5f3f-4051-aad9-d30d85870c45",null]
```

I managed to be a messy version of this working with the query builder

![image](https://user-images.githubusercontent.com/5119107/96724238-8498ba80-13a7-11eb-9575-9d1417968e3b.png)

**Comment by imnotjames** [comment] 2020-10-21 15:06
Duplicate of #2707

**Closed by imnotjames** 2020-10-21 15:06 UTC
