### ISSUE TITLE
Where clause on related table does not work

### ISSUE THREAD

**Issue by pburrows** [typeorm/typeorm#2872] opened 2018-10-01 13:24 UTC
**Issue type:**

[ ] question
[x ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a OneToOne relationship between a table called WsUser and WsUserAuthentication. I find that the query generator does not include a WHERE clause at all for this query:

```
this.entities.findOne(WsUser,
            {
                where: {
                    authentication: {
                        googleId: googleId
                    }
                },
                relations: ['authentication']
            });
```

However, this query works as expected and returns the records as expected:

```
this.entities.findOne(WsUserAuthentication,
            {
                where: {
                    googleId: googleId
                },
                relations: ['user']
            });
```

However, there are a lot of places in code where I am expecting to be able to filter on multiple columns from different tables that are joined together. Not all my queries are as easy to reverse as this one.

Do I perhaps need to use `leftJoinAndSelect` instead of relations? The documentation doesn't really mention this, it just says that a join is an "`Extended version of "relations".`"

**Comment by elthrasher** [comment] 2018-10-01 13:52
Try it with `leftJoinAndSelect`. I don't believe `relations` lets you add additional where criteria.

**Comment by pburrows** [comment] 2018-10-03 12:49
Strangely, that didn't work, either.

Maybe it is how I have the model defined? I have the WsUser model defined as:

```
export class WsUser {

    @PrimaryGeneratedColumn({

        name:'userId'
        })
    userId: number;

    
    // bunch of unrelated fields........
    
    
    @OneToOne(() => WsUserAuthentication, WsUserAuthentication => WsUserAuthentication.user)
    authentication: WsUserAuthentication;

}
```


and the WsUserAuthentication model defined as:

```
export class WsUserAuthentication {

    @PrimaryGeneratedColumn({

        name:'userAuthenticationId'
        })
    userAuthenticationId: number;

    @OneToOne(() => WsUser, WsUser => WsUser.authentication, {  nullable:false, })
    @JoinColumn({ name:'userId'})
    user: WsUser | null;

    
    // bunch of unrelated fields
    

    @Column('nvarchar', {
        nullable:true,
        length:100,
        name:'googleId'
        })
    googleId: string | null;
}
```

This is the only 1:1 relationship I have in the database. 
Maybe I defined it wrong?

I think 1:* relationships are working with this sort of query. (not sure)

**Comment by quezak** [comment] 2019-08-21 17:10
> Try it with `leftJoinAndSelect`. I don't believe `relations` lets you add additional where criteria.

@elthrasher can you give an example how to use `leftJoinAndSelect` to achieve the query OP had in mind? I have a similar case and can't figure it out without a `queryBuilder`.

On another note: if `.find({ where: ... })` doesn't allow making queries on related items, why do the typings for `FindConditions` allow to pass a nested query there? Shouldn't it allow only specifying top-level column queries then?

**Comment by elthrasher** [comment] 2019-08-21 20:46
Whoops, didn't realize I had a response here last year.

@quezak I did mean to use `queryBuilder` with `leftJoinAndSelect` for this use case. The latter takes a condition as an optional argument which will wind up producing the sql you're looking for. I don't think there's a way to do this with `find` and `relations`.

For the original query with a query builder, I guess something like this:
```
repo.createQueryBuilder('wsUser')
  .leftJoinAndSelect('wsUser.authentication', 'authentication', 'authentication.googleId = :googleId', {googleId});
``

**Comment by quezak** [comment] 2019-08-21 21:22
Thanks for the reply, I hoped it was possible to do without a query builder. Which justifies my second remark, I wonder why do the typings allow to form such "detailed queries" when it's not supported :)

Just in case someone finds this issue later -- I've tried using such a `queryBuilder` before, and the `condition` in `leftJoin...` is the *join condition*, used for the `JOIN <related_table> ON <condition>` clause. We want to keep the normal join conditions, and add our condition to the `WHERE` clause. Without excessive explanation, the query would be something like this:
```
repo.createQueryBuilder('wsUser')
  .leftJoinAndSelect('wsUser.authentication', 'authentication')
  .where('authenthication.googleId = :googleId', { googleId })
  .getOne();

```

**Comment by elthrasher** [comment] 2019-08-22 01:54
@quezak You should be able to put any arbitrary string in your `where` clause. What result do you get when you try something like the above? Does it throw an error or just not respect your `where`? If the latter, try enabling sql output and see what it generates.

**Comment by quezak** [comment] 2019-08-22 08:44
@elthrasher The query from my previous comment works, I just left it there as the imho correct solution to OP's problem, in case someone comes here from a google search like me :)

I'm just generally wondering why does `find(...)` accept `where: { relatedEntity: { keyOfRelatedEntity: something }}` at all -- since these queries don't work, typescript typings should prohibit such calls.

**Comment by elthrasher** [comment] 2019-08-22 13:32
@quezak That can be answered by examining the types.
```TypeScript
where(where: Brackets | string | ((qb: this) => string) | ObjectLiteral | ObjectLiteral[], parameters?: ObjectLiteral): this;
```
`where` takes a union type, one of the options which is `ObjectLiteral` and the type for `ObjectLiteral` is:
```TypeScript
export interface ObjectLiteral {
    [key: string]: any;
}
```
For this to work the way you expect, we would need to replace `any` with something that more closely matches what is allowed here. Is that possible to do given this is generic across all databases supported? Sounds challenging, but TypeScript has evolved since this type was written so maybe something using `Omit` (requires minor ts upgrade) would serve us better here.

I doubt this is a big priority for core contributors, but they take pull requests.

**Comment by quezak** [comment] 2019-08-22 14:10
@elthrasher I was talking about the `FindConditions<Entity>` passed to the regular `repository.find(...)` method, sorry about the miscommunication. The `where` for query builder does allow you to do complex queries, so it indeed needs a more loose typing. However, if repository's `find` only allows querying the entity's columns, I think it shouldn't accept such a query to begin with.

Here's what `repository.find` accepts (either directly, or in `FindOptions<Entity>.where`):
```typescript
export declare type FindConditions<T> = {
    [P in keyof T]?: FindConditions<T[P]> | FindOperator<FindConditions<T[P]>>;
};
```

For the sake of an example, say you have `Post`s, each created by a related `User` (a many-to-one relation). Assume each user has a `status` field.

**How I understand this issue's title problem:**
 * you want to find posts about `something` made by active users
 * `FindConditions<Post>` allows you to call `postRepository.find({ subject: 'something', user: { status: 'ACTIVE' })`
 * the docs don't say anything about such queries (whether it's supported or not), so if the typings allow that, I'm assuming it will work
 * but: it's not possible to execute such a query with a `repository.find` call after all
 * what's worse: TypeOrm executes just `... WHERE post.subject = 'something'` and silently (!!) ignores the `user` related entity part of the query.

Additional question: is this true for all databases? OP used mssql, I'm using postgres.

What I expected to happen:
 * either such a call should be impossible via static types -- maybe something like `[P in keyof T]?: T[P] extends {} ? never : <current value>` to disallow subqueries for related entities? This might be too restricting, as I don't know the exact usages of `FindConditions` in the codebase.
 * or such a call should be rejected at runtime, or at least a warning should be produced in logs.

**Comment by elthrasher** [comment] 2019-08-22 14:22
@quezak There's also a version of `find` that takes `FindManyOptions` which will eventually drill down to the same `ObjectLiteral` interface. So it's obviously a complex problem to solve with many use cases.

I know this has been brought up before to discuss whether there should be a runtime error, but I think that was rejected on the 0.2.x branch for reasons of backward compatibility. You could check out the 0.3.x branch or maybe get some discussion going on slack. Last I heard 0.3.x was close to ready, but I'm a little out of the loop.

**Comment by alpharder** [comment] 2019-12-16 21:35
There's a workaround for filtering based on relation fields for `findOne()`/`find()` methods that I've discovered recently. The problem with filtering related table fields only exists for `ObjectLiteral`-style `where`, while string conditions work perfectly. 

Assume that we have two entities – `User` and `Role`, user belongs to one role, role has many users:

```typescript
@Entity()
export class User {
  name: string;

  @ManyToOne(() => Role, role => role.users)
  role: Role;
}

@Entity()
export class Role {
  @OneToMany(() => User, user => user.role)
  users: User[];
}
```

Now we can call `findOne()`/`find()` methods of `EntityManager` or repository:

```typescript
roleRepository.find({
  join: { alias: 'roles', innerJoin: { users: 'roles.users' } },
  where: qb => {
    qb.where({ // Filter Role fields
      a: 1,
      b: 2
    }).andWhere('users.name = :userName', { userName: 'John Doe' }); // Filter related field
  }
});
```

You can omit the `join` part if you've marked your relation as an eager one.

**Comment by bestickley** [comment] 2020-03-19 17:17
Thanks so much for the workaround, @alpharder!
What typing would be used for `qb`? I tried QueryBuilder but that did not work.

**Comment by icereval** [comment] 2020-07-17 09:35
`SelectQueryBuilder<Entity>`

**Comment by alpharder** [comment] 2020-09-22 11:40
> Thanks so much for the workaround, @alpharder!
> What typing would be used for `qb`? I tried QueryBuilder but that did not work.

If I remember correctly, it's `SelectQueryBuilder`

**Comment by alpharder** [comment] 2020-09-22 11:41
Also the best workaround is switching to mikro-orm

**Comment by imnotjames** [comment] 2021-06-23 20:35
This seems to be a duplicate of #2707

**Comment by imnotjames** [comment] 2021-06-25 04:35
Pretty sure that's the case, that's how I've read it at least.  Please feel free to re-open if that's incorrect.  Otherwise, please direct all conversation into 2707

**Closed by imnotjames** 2021-06-25 04:35 UTC
Labels: bug, can be closed?, driver: mssql, new feature
