### ISSUE TITLE
UpdateDateColumn not updated as expect when customize transformer is setted.

### ISSUE THREAD

**Issue by cfool** [typeorm/typeorm#7861] opened 2021-07-07 09:28 UTC
## Issue Description
when i set customize transformer for UpdateDateColumn, this column will never update.
### Expected Behavior
the update time column update to latest time when i update some column of entity.

### Actual Behavior
the update time column never update.

```
// include the output in code tags like these!
```

### Steps to Reproduce

```typescript
const fromTransformer = (date) => `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()} ${date.getHour()}:${date.getMinute()}:${date.getSecond()}`

@UpdateDateColumn({ type: 'timestamp', transformer: { from: fromTransformer } })
update_time: string = '';

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   MacOS 11.2.3       |
| Node.js version     | v12.16.1 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

maybe there is a bug in function computeDiffColumns in file `persistence/SubjectChangedColumnsComputer.ts`.

if there is a custom transformer, it should be called when entityValue is initialed. 

```
// current code, maybe wrong ?
const entityValue = column.getEntityValue(subject.entity!);

// currect code ?
const entityValue = column.getEntityValue(subject.entity!, true);

```

### Relevant Database Driver(s)
- [x] `mysql`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by imnotjames** [comment] 2021-07-07 17:06
Duplicate of #7150

**Closed by imnotjames** 2021-07-07 17:06 UTC
Labels: bug, requires triage
