### ISSUE TITLE
Relation ManyToOne and OneToMany always returns null

### ISSUE THREAD

**Issue by wembleyos77** [typeorm/typeorm#8075] opened 2021-08-13 06:10 UTC
### Expected Behavior

```
{
   _id: 3iopvviop434589bbkja,
  name: 'Category',
  parent: {
    _id: 34904903902190290,
   name: 'Parent category'
  }
}
```

### Actual Behavior

```
{
   _id: 3iopvviop434589bbkja,
  name: 'Category',
  parent: null
}
```

### Steps to Reproduce

1.
```typescript
@Entity()
class Category extends BaseEntity {
    @ObjectIdColumn()
    _id: ObjectID;

    @Column()
    @Field(() => String)
    name: string;

    @ManyToOne(type => Category, category => category.parent, { nullable: true })
    parent: Category;
}

export default Category;
```
2. Create entity
```typescript
    async createCategory(@Arg('data') {parent, ...data}: data) {
        const newCategory = Category.create(data);
        newCategory.parent = await Category.findOne(parent);
        return await newCategory.save();
    }
```

And then fetch it:
```typescript
    @Query(() => [Category])
    async getCategories() {
        const result = await Category.find({ relations: ['parent'] });
        return result;
    }
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| macOS    |    11.5      |
| Node.js version     | 7.17.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.34  | 
| MongoDB version     | 3.6.0  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | yes            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by wembleyos77** [comment] 2021-08-14 07:16
Any ideas on this? @imnotjames

**Comment by imnotjames** [comment] 2021-08-14 07:26
I have a good feeling there's an issue that this is a duplicate of because the mongo driver doesn't support joins and silently drops them.

**Comment by imnotjames** [comment] 2021-08-14 07:35
Duplicate of #655

**Closed by imnotjames** 2021-08-14 07:35 UTC
Labels: bug, requires triage
