### ISSUE TITLE
Relational Query Builder giving error when adding to many-to-many relationship

### ISSUE THREAD

**Issue by tnwanna** [typeorm/typeorm#3979] opened 2019-04-11 18:43 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I've been following the repository relations FAQ and other examples here, but it doesn't seem to be working properly when trying to add an item to a many-to-many relationship

```ts
@Entity
class ContentItem
  @PrimaryGeneratedColumn('uuid')
  id: string;

 @ManyToMany(type => Image, image => image.contentItems)
  images: Image[]

 ...

@Entity()
export class Image {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToMany(type => ContentItem, contentItem => contentItem.images)
  @JoinTable()
  contentItems: ContentItem[]

...

await getConnection()
        .createQueryBuilder()
        .relation(Image, "contentItems")
        .of(imageId)
        .add(contentItemId)
```

And the error response
```ts
code: "23502"
column: "image_id"
detail: "Failing row contains (null, null)."
file: "execMain.c"
length: 197
line: "2042"
message: "null value in column "image_id" violates not-null constraint"
name: "QueryFailedError"
parameters: []
query: "INSERT INTO "image_content_item"("image_id", "content_item_id") VALUES (DEFAULT, DEFAULT)"
routine: "ExecConstraints"
schema: "public"
severity: "ERROR"
stacktrace: ["QueryFailedError: null value in column "image_id" violates not-null constraint",…]
table: "image_content_item"
```

For some reason it's not binding the parameters so the insert fails

**Comment by tnwanna** [comment] 2019-04-16 13:50
I think it's similar to #2612 (which isn't properly referencing for some reason)

**Comment by nadrane** [comment] 2019-11-24 20:06
Did you ever come up with a solution to this issue? Or did you have to write a raw query?

**Comment by brunoMaurice** [comment] 2019-11-24 22:49
What about :

```
await getConnection()
        .createQueryBuilder()
        .relation(Image, "contentItems")
        .of(imageEntity)
        .add(contentItemEntity)
```

In some project, I use this syntax but with entity and not direct id. (maybe an still something to fix with the querybuilder but it can be a temporary solution for your case).

**Comment by codymartin** [comment] 2020-07-13 22:26
I have this exact issue too.

**Comment by kauemurakami** [comment] 2021-06-11 01:09
I have this exact issue too.

**Comment by ctkc** [comment] 2021-06-28 17:24
Same issue too

**Comment by imnotjames** [comment] 2021-06-28 19:26
This is a duplicate of #2612 - please direct information there.

**Closed by imnotjames** 2021-06-28 19:26 UTC
Labels: bug, comp: query builder, driver: postgres
