### ISSUE TITLE
Nested relations filtering doesn't work

### ISSUE THREAD

**Issue by trixden** [typeorm/typeorm#3890] opened 2019-03-24 21:28 UTC
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.15` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 2 models

*category.entity.ts*
```typescript
@Entity()
export class BlogCategoryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Index()
  @Column({unique: true})
  alias: string;

  @Column()
  title: string;

  @OneToMany(type => BlogPostEntity, post => post.category)
  posts: BlogPostEntity[]
}
```

*post.entity.js*
```typescript
@Entity()
export class BlogPostEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Index()
  @Column({unique: true})
  alias: string;

  @Column()
  title: string;

  @Column('text')
  description: string;

  @Column({type: 'text', nullable: true})
  text: string;

  @Index()
  @Column()
  isPublished: boolean;

  @Index()
  @Column()
  publishedAt: Date;

  @Column()
  categoryId: number;

  @ManyToOne(type => BlogCategoryEntity, category => category.posts, {eager: true, nullable: false, onDelete: 'CASCADE'})
  @JoinColumn()
  category: BlogCategoryEntity;
}
```

When i filter query by category_id, everything is ok:

```typescript
const [rows, count] = await this.repository.findAndCount({
  skip: query.skip,
  take: query.take,
  where: {
    category: {
      id: 1
    }
  }
});
```

But, filter works only by primary nested field. Filtering by other fields don't work:

```typescript
const [rows, count] = await this.repository.findAndCount({
  skip: query.skip,
  take: query.take,
  where: {
    category: {
      alias: 'test'
    }
  }
});
```

```sql
SELECT
  "BlogPostEntity"."id" AS "BlogPostEntity_id",
  "BlogPostEntity"."alias" AS "BlogPostEntity_alias",
  "BlogPostEntity"."title" AS "BlogPostEntity_title",
  "BlogPostEntity"."description" AS "BlogPostEntity_description",
  "BlogPostEntity"."text" AS "BlogPostEntity_text",
  "BlogPostEntity"."isPublished" AS "BlogPostEntity_isPublished",
  "BlogPostEntity"."publishedAt" AS "BlogPostEntity_publishedAt",
  "BlogPostEntity"."categoryId" AS "BlogPostEntity_categoryId",
  "BlogPostEntity_category"."id" AS "BlogPostEntity_category_id",
  "BlogPostEntity_category"."alias" AS "BlogPostEntity_category_alias",
  "BlogPostEntity_category"."title" AS "BlogPostEntity_category_title"
FROM "blog_post_entity" "BlogPostEntity"
LEFT JOIN "blog_category_entity" "BlogPostEntity_category"
  ON "BlogPostEntity_category"."id"="BlogPostEntity"."categoryId"
WHERE "BlogPostEntity"."categoryId" = ? -- PARAMETERS: [null]
```

Are there options to implement this?

**Comment by Flash619** [comment] 2019-05-29 14:21
@trixden Did you find any way around this yet? I just ran into this exact issue today and so far have not found a clean work around.

**Comment by trixden** [comment] 2019-06-07 19:15
@Flash619 I found a way around the typeorm and use sequelize 5

**Comment by anitricks** [comment] 2019-06-07 19:57
@trixden do u mind sharing your code on how you did it?

**Comment by trixden** [comment] 2019-06-07 20:39
@anitricks I'm not sure you understood me correctly. I stopped using typeorm. sequelize 5 fully supports typescript. And sequelize is not a bug warehouse.

**Comment by anitricks** [comment] 2019-06-07 21:04
@trixden haha no I understood you correctly. I was just asking if you could share how did you accomplish nested relations in sequelize. Like a snippet

**Comment by trixden** [comment] 2019-06-07 21:29
@anitricks Ohh. It's simple:
```javascript
sequelize.mainModel.findOne({
  where: {
    field: 'value' // FIrst level relation filtering
  },
  include: [{
    model: sequelize.subModel,
    as: 'subPost',
    where: {
      field: 'value' // Second level relation filtering
    },
    // Need more includes?
    include: {
      model: sequelize.subSubModel,
      as: 'subPost',
      where: {
        field: 'value' // Third level relation filtering
      }
    }
  }]
});
```
It's not detailed example. As well as it's not correct topic to demonstrate another library (despite the fact that I doubt that anyone besides us is reading this). But the essence is clear. Documentation will help you understand how to use it in detail.

**Comment by Flash619** [comment] 2019-06-10 03:47
It would be nice to see a solution that works with TypeORM. I would hate to replace an ORM in a production app just to get this working. So far I've had to avoid any nested where statements. If anything its actually produced some cleaner code, but it would be nice to have to omit certain records without added API endpoints/resolvers for each unique case.

**Comment by haschu** [comment] 2019-06-11 13:29
I guess this is more a feature request than a bug, because TypeORM doesn't seems to support nested where conditions, or am I wrong?

I can't find anything in the docs.

**Comment by hector-chauran** [comment] 2019-07-15 16:03
You can always use the [query builder](https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#inner-and-left-joins).

```typescript
const [rows, count] = await this.repository.manager.createQueryBuilder('post')
    .innerJoinAndSelect('post.category', 'category')
    .where('category.alias = :alias', { alias: 'test' })
    .getManyAndCount();
```

```sql
SELECT
    "post"."id" AS "post_id",
    "post"."alias" AS "post_alias",
    "post"."title" AS "post_title",
    "post"."description" AS "post_description",
    "post"."text" AS "post_text",
    "post"."isPublished" AS "post_isPublished",
    "post"."publishedAt" AS "post_publishedAt",
    "post"."categoryId" AS "post_categoryId",
    "category"."id" AS "category_id",
    "category"."alias" AS "category_alias",
    "category"."title" AS "category_title"
FROM "blog_post_entity" "post"
INNER JOIN "blog_category_entity" "category"
    ON "category"."id"="post"."categoryId"
WHERE "category"."alias" = $1
-- PARAMETERS: ["test"]
```

**Comment by frieck** [comment] 2019-08-08 14:47
So, Typeorm supports or not nested relations filtering??
Having the same problem here, but it is not clear if this is a bug (and will be fixed) or this is a desired feature...

**Comment by haschu** [comment] 2019-08-08 15:16
@frieck It depends on whether you want to use `FindOptions` or `QueryBuilder`. As for `QueryBuilder`,  since you're able to build any query you like, you can filter nested relations as deep as you want. Using `FindOptions`, this is currently not supported :/

I submitted a feature request for this (#4280), but unfortunately there isn't much feedback yet.

As this feature was also crucial for my team, we started to implement a TypeOrm extension wrapper, that also supports nested relation filtering using `FindOptions`. We're going to publish it here on GitHub (see also: #534) as soon as we can find some time - which is hopefully very soon :).

**Comment by frieck** [comment] 2019-08-08 15:38
@haschu That feature is absolutely crucial! Even if `QueryBuilder` can be used to build the most complex queries (and we use it alot!) some times it lacks for simplicity, and I believe the `FindOptions` were built for that simplicity. 

Would be glad if I can take a look in your extension wrapper! I have no idea on how does it works...

Is there any workaround to fix that, or maybe we can just wait for your feature request to be released, or even your wrapper?

**Comment by haschu** [comment] 2019-08-08 16:52
I don't think there is a workaround - we actually did implement a custom `Entity` and `Repository` with custom `FindOptions` to achieve this feature. Our extension is currently tied to in-house code, hence I cannot share it for now, but I'll do my best to outsource the essentials into a standalone project soon.

Currently, the active TypeORM development is kind of on hold - but it sure will going on (#3267)
I strongly believe that eventually those feature are going to be implemented into TypeORM, we just have to wait a bit :)

**Comment by Mr-Cool** [comment] 2019-08-22 17:16
Oddly enough, nested relations filtering works when using findOne.

**Comment by trixden** [comment] 2019-08-22 17:50
@haschu, we can always use the query builder. But, this is "TypeORM", and not "TypeQueryBuilder")

**Comment by haschu** [comment] 2019-08-27 13:23
@trixden Sure, you are right, you can always use `QueryBuilder` :). But I don't really get your point here.

**Comment by rangelfinal** [comment] 2020-01-07 14:27
Shouldn't typeorm at least throw an error if nested wheres will not be supported by Repository?  
Having this weird behavior where options are just silently ignored when trying to use nested filters may cause all sorts of problems (Mainly devs wasting a lot of time) and even loss of data

**Comment by reinoute** [comment] 2020-01-22 22:12
> Shouldn't typeorm at least throw an error if nested wheres will not be supported by Repository?
> Having this weird behavior where options are just silently ignored when trying to use nested filters may cause all sorts of problems (Mainly devs wasting a lot of time) and even loss of data

<-- Dev who wasted a lot of hours on this

**Comment by dev-mraj** [comment] 2020-01-27 14:07
any better solution then this? so far i got this yet.

const caseUsers: CaseUser[] = await CaseUser.getRepository().find({
            relations: ['case'],
            where: (qb: SelectQueryBuilder<CaseUser>) => {
                qb.where({
                    type: 'user',
                }).andWhere('case.status!=:closed', {closed: 'closed'});
            },
            join: {
                alias: 'user',
                innerJoin: {
                    case: 'user.case',
                },
            },
        });

**Comment by dev-mraj** [comment] 2020-01-27 14:09
we don't want to use query-builder and finder both at same time..

both ways should provide maximum flexibility, so people can prefer their choice of method.  and i don't want querybuilder to be used at same places and finder at some.

so typeorm please support nested relations inside finder and other more features too.

**Comment by fan-tom** [comment] 2020-01-30 08:35
Also, QueryBuilder approach if fully untyped, so, instead of compile-time error when you try to filter string field by comparing with number, you get runtime error when query is executed

**Comment by JSilversun** [comment] 2020-03-04 19:26
This feature is really important, please include it

**Comment by aeskov** [comment] 2020-03-13 11:24
Yes, need to include =(

**Comment by DoctorVoid** [comment] 2020-03-22 11:11
We need this!

**Comment by csakbalint** [comment] 2020-03-25 10:46
We still need this!

**Comment by CyriacBr** [comment] 2020-03-25 10:49
I suggest everyone struggling here with either this missing feature or TypeORM overall to take a look at [mikro-orm](https://github.com/mikro-orm/mikro-orm). It's just a way better ORM with a active maintainer.

**Comment by Wolven531** [comment] 2020-03-26 16:24
> I suggest everyone struggling here with either this missing feature or TypeORM overall to take a look at [mikro-orm](https://github.com/mikro-orm/mikro-orm). It's just a way better ORM with a active maintainer.

I'm look to transition one of our API apps from NestJS + Sequelize to NestJS + TypeORM; we're considering all ORM options available. Some of our other code already has TypeORM in place, and when combined with the utility of https://www.npmjs.com/package/typeorm-model-generator, TypeORM seems to be a real problem solver for our current lackluster usage of Sequelize in the app I'm looking to transition.

That being said, I'm concerned w/ everything I'm reading in the comments in the TypeORM repo about sustainability. Looking at mikro-orm (per @CyriacBr ), though it seems interesting:

* [mikro-orm](https://github.com/mikro-orm/mikro-orm) has ~800 commits in ~24 months (around 33 per month, or 1 a day avg) since Mar 2018
* [TypeORM](https://github.com/typeorm/typeorm) has ~4200 commits in ~48 months (around 88 per month, or 3 a day avg) since Feb 2016
* [Sequelize](https://github.com/sequelize/sequelize) has ~8600 commits in ~120 months (around 72 per month, or 2.5 a day avg) since Jul 2010

Our concern w/ Sequelize is that it's a bit dated, and working w/ TypeScript by using `sequelize-typescript` feels like a bit of a kludge, despite the fact that nested relations filtering works pretty much out of box.

Unfortunately, it appears mikro is a bit too green for us to rely on in a production environment.

We're going to go ahead w/ TypeORM based on the framework ease of use and the model generator tool previously mentioned. Additionally, w/ the hope that nested relations filtering will work in the near future since there's **_a lot of demand_** for it.

Thought I'd share some of our discovery/debate process for anyone else looking into these options and seeking guidance.

**Comment by CyriacBr** [comment] 2020-03-26 18:59
@Wolven531 Mikro-orm has an entity generator. And it's built-in: https://mikro-orm.io/docs/entity-generator.  
I don't think it's a good metric to compare the number of commits, especially given they didn't start at the same time. Rather, you should look for provided features first, then stability and maintainability. TypeORM may have more "niche" features, as it is older, however Mikro-orm is just better at everything else.

**Comment by a7urag** [comment] 2020-04-11 13:37
I was able to achieve nested where filtering using `createQueryBuilder`.
Here's the example to get courses where the user has not registered as of now.
PS: _CourseUser_ = course registration table

`const qb = await getRepository(Course).createQueryBuilder('course');
  return qb
    .where(
      `allowEnroll = :allowEnroll AND isActive = :isActive AND id NOT IN ${qb
        .subQuery()
        .select('cu.courseId')
        .from(CourseUser, 'cu')
        .where('cu.userId = :userId and cu.status <> :status', {
          userId,
          status: CourseStatus.COMPLETE,
        })
        .getQuery()}`,
      { isActive: true, allowEnroll: true },
    )
    .getMany();`

**Comment by winay39** [comment] 2020-04-16 21:28
For me it's not working with primary key as well? Am I doing something wrong? However I have primary key on two fields.

**Comment by avin-kavish** [comment] 2020-04-24 06:22
@Wolven531 yeah you can't compare libraries with commits, because newer libraries always (well, hopefully)s build on the knowledge of the existing libraries, so fewer commits are needed to get there.

**Comment by hereisnaman** [comment] 2020-06-27 23:08
We need this, please implement it.

**Comment by gsusI** [comment] 2020-07-12 19:19
The docu

> > Shouldn't typeorm at least throw an error if nested wheres will not be supported by Repository?
> > Having this weird behavior where options are just silently ignored when trying to use nested filters may cause all sorts of problems (Mainly devs wasting a lot of time) and even loss of data
> 
> <-- Dev who wasted a lot of hours on this. The documentation implies it's possible to use nested queries.

How can the [documentation](https://typeorm.io/#/find-options) say this if it's not possible, @pleerock 

```
Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined. Example:

userRepository.find({ where: { name: { first: "Timber", last: "Saw" } } });
```

**Comment by atlaning** [comment] 2020-07-25 04:10
Still an issue, frustrating that the data to filter is returned in the find but can't be filtered on. Have to setup query builder but just not as elegant. I suppose it's a nice to have... but it'd be real nice to have hah.

**Comment by avin-kavish** [comment] 2020-07-25 08:55
This is when I realized the solution to the ORM problem is not to attempt to fix or create various different versions of JS/TS libraries but to write backends in C# that has enterprise-grade ORM solutions. (or Java, if that's your taste)

**Comment by vic3king** [comment] 2020-08-25 13:48
We still need this feature ✊🏽

**Comment by Schular** [comment] 2020-09-03 12:21
In my case by making the nesting as a string was working:

So let's say instead of:
```
const result = await this.repository.findOne({
      where: { input: { name } }
});
```
you write like this to work:
```
const result = await this.repository.findOne({
      where: { 'input.name': name }
});
```

**Comment by ForeshadowRU** [comment] 2020-09-16 09:46
We still need this feature ✊🏽

**Comment by chriswall-aa** [comment] 2020-09-17 11:32
@gsusI I'm experiencing the same issue with filtering nested relations but but wanted to address your comment about embedded entities - the docs define embedded entities not as relations through other tables but pseudo-relationships at code level. See here https://typeorm.io/#/embedded-entities

I'm not saying this is good or bad - the terminology is misleading imo

**Comment by Silventino** [comment] 2020-10-02 01:07
We still need this feature ✊🏽

**Comment by wesleyfeitosa** [comment] 2020-10-02 14:19
is anyone really looking at this?
...
We still need this feature ✊🏽

**Comment by rgiovani** [comment] 2020-10-02 14:36
@Schular in your case works because u are not using relations, isn't?

**Comment by gauthiersoyelcapitan** [comment] 2020-10-08 21:29
We still need this feature ✊🏽

**Comment by haschu** [comment] 2020-10-09 06:55
@imnotjames This isn't a bug but a missing feature. See #4280 🙂

**Comment by imnotjames** [comment] 2020-10-09 07:05
I automatically added labels based in the first post of the issue

**Comment by imnotjames** [comment] 2020-10-15 21:54
I tested this a few different ways.  This is supported already and this issue is a duplicate of a previous issue.

**Comment by imnotjames** [comment] 2020-10-15 21:54
Duplicate of #2707

**Closed by imnotjames** 2020-10-15 21:54 UTC
Labels: bug, comp: find options

**Comment by vash72** [comment] 2020-10-16 12:02
> 
> 
> I tested this a few different ways. This is supported already and this issue is a duplicate of a previous issue.

Maybe i'm in wrong but for me ins't supported


```
 const result = await repository.find({
      where: {
        // job: { name: 'Pulizia stoviglie' }
      },
      relations: ['job']
    });

    Logger.debug(result);

--> [
  {
    "id": "d65dfbd3-c0ce-4a1f-a190-dee060c2dc8f",
    "jobId": "4f3754d9-07d6-49be-8787-0fa7dbebedf5",
    "shiftId": "b5dc4ef8-6f54-4c88-b5e9-bf2ed1acac57",
    "job": {
      "createdAt": "2020-10-12T10:34:57.878Z",
      "updatedAt": "2020-10-13T09:19:23.922Z",
      "deletedAt": null,
      "id": "4f3754d9-07d6-49be-8787-0fa7dbebedf5",
      "name": "Pulizia stoviglie",
      "colorId": 5
    }
  }
]
```
if i try with nested where

```
 const result = await repository.find({
      where: {
         job: { name: 'Pulizia stoviglie' }
      },
      relations: ['job']
    });

    Logger.debug(result);

-->[]

```

**Comment by nicobytes** [comment] 2020-11-09 21:53
Find with embedded entities doest work when runs SQL query, TypeORM take the obj like an id no like the embedded entity's attribute.

```
appointmentsCoachesRepo.find({
      relations: ['appointment'],
      where: {
        appointment: {
          status: 'pending'
        }
      },
    });
```

In the log:

![Screen Shot 2020-11-09 at 5 46 41 PM](https://user-images.githubusercontent.com/7611944/98600113-7279b000-22b3-11eb-82ce-18662919b709.png)

In the `WHERE "AppointmentsCoaches"."appointmentId" = $1` therefore return `[]`

cc @vash72 @imnotjames 

Note: I'm using the version `0.2.29`

**Comment by YEMEAC** [comment] 2021-05-03 09:07
still not working.

**Comment by huybkdn23** [comment] 2021-05-24 04:33
Still not working now, we still need this feature

**Comment by pundarikas** [comment] 2021-05-29 10:46
Not working.

**Comment by arayik-yervandyan** [comment] 2021-06-16 16:34
Still not working . version ^7.1.5

**Comment by Yuri-Ribeiro** [comment] 2021-06-23 12:58
Still not working.

**Comment by imnotjames** [comment] 2021-06-23 18:19
Still a duplicate of #2707
