### ISSUE TITLE
The website isn't working

### ISSUE THREAD

**Issue by rafaelqm** [typeorm/typeorm#7551] opened 2021-04-08 13:22 UTC
## Documentation Issue
When you open the https://typeorm.io/, the page return blank, looking to the console there is this error:
```
Failed to load resource: the server responded with a status of 404 ()
index.js:8 Uncaught ReferenceError: VueI18n is not defined
    at index.js:8
```

**Comment by simeon-zh** [comment] 2021-04-08 13:30
Change <src="https://unpkg.com/vue-i18n/dist/vue-i18n.js"> to <src="https://unpkg.com/vue-i18n@8">
You're welcome

**Comment by simeon-zh** [comment] 2021-04-08 13:31
Change <src="https://unpkg.com/vue-i18n/dist/vue-i18n.js"> to <src="https://unpkg.com/vue-i18n@8">

**Comment by tomasalles** [comment] 2021-04-08 13:34
Yes, got the same problem

**Comment by orhasson-dev** [comment] 2021-04-08 14:08
Thanks.
I already opened this issue on StackOverflow.

https://stackoverflow.com/questions/67004020/typeorms-documentation-not-avaliable?noredirect=1#comment118439112_67004020

You can work with:

https://orkhan.gitbook.io/typeorm/

For now.

Thanks,

Or Hasson

**Comment by angelxmoreno** [comment] 2021-04-08 16:20
duplicate of #7546
seems to be up now. this should be closed.

**Comment by rafaelqm** [comment] 2021-04-08 18:37
It's working now.

**Closed** 2021-04-08 18:37 UTC
Labels: documentation, requires triage
