### ISSUE TITLE
Default CLI To Load ENV from ENV

### ISSUE THREAD

**Issue by jspizziri** [typeorm/typeorm#5386] opened 2020-01-20 20:11 UTC
**Issue type:**

[x] feature request

**Database system/driver:**

[x] `cli`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

As I commented in https://github.com/typeorm/typeorm/issues/4288#issuecomment-576413173, IMHO, it'd be a better design to default load the ENV from the actual ENV, and if someone wanted to explicitly load from a file require an argument for the path to that file. We're in the age of containerization and env should always be properly set in the container before application boot.

**Comment by imnotjames** [comment] 2020-10-07 03:01
Closing as a duplicate of #3567

**Closed by imnotjames** 2020-10-07 03:01 UTC
Labels: new feature
