### ISSUE TITLE
support cordova sqlite concurrency

### ISSUE THREAD

**Issue by jacobg** [typeorm/typeorm#4076] opened 2019-05-03 01:21 UTC
**Issue type:**

[ ] question
[X] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[X] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Currently, the cordova driver (based on abstract sqlite) uses one shared connection and unsupported sql transaction statements (#4075). Each of those approaches can independently cause errors and potential data corruption

This issue is to track either enabling official support for concurrency, or enforcing non-concurrency of requests by using a queue. Here are some other related issues:
- #1884 
- https://github.com/xpbrew/cordova-sqlite-storage/issues/864

**Comment by imnotjames** [comment] 2020-10-04 20:35
Going to mark this as a duplicate of #1884  and close it.

Enabling official "concurrency" won't really do much here because we don't do pooling yet and if we're doing it for cordova we might as well for all of them.

**Closed by imnotjames** 2020-10-04 20:35 UTC
Labels: driver: cordova
