### ISSUE TITLE
OneToMany and ManyToOne relationship issue

### ISSUE THREAD

**Issue by LidorBenYosef** [typeorm/typeorm#6711] opened 2020-09-13 08:43 UTC
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey guys.
I'm having a problem in creating two entities with oneToMany and ManyToOne relationships between them.
These are my entities :
```
@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => User, user => user.photos)
    user: User;
}
```
```
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];
}
```
I tried to create a user and 3 photos that have relationship between them :
```
(async () => {
    const conn = await createConnection(typeOrmConfig);
    console.log('PG connected.');
    const photoRepo =await conn.getRepository(Photo)
    const userRepo = await conn.getRepository(User);
    let user1 = new User();
    user1.name = 'Matt';
    user1 = await userRepo.save(user1); 

    let photo1 = new Photo();
    photo1.name = "wallpaper"
    photo1.user = user1
    let photo2 = new Photo();
    photo2.name = "zanzibar"
    photo2.user = user1
    let photo3 = new Photo();
    photo3.name = "beach"
    photo3.user = user1

    await photoRepo.save(photo1)
    await photoRepo.save(photo2)
    await photoRepo.save(photo3)
    // Close connection
    await conn.close();    
})();
```
but whenever i try to print the users and photo , i cant see any relationship field between them(can't see photos in user/ user in each photo):
```  
const conn = await createConnection(typeOrmConfig);
console.log('PG connected.');
const photoRepo =await conn.getRepository(Photo)
const userRepo = await conn.getRepository(User);
console.log(await photoRepo.find())
console.log(await userRepo.find())
await conn.close();    
```
output : 
```
[
  Photo { id: 1, name: 'wallpaper' },
  Photo { id: 2, name: 'Zanzibar' },
  Photo { id: 3, name: 'beach' }
]
[
  User { id: 1, name: 'Matt' }
]
```
I tried to access user.photos but its undefined
same when trying to access photo.user .
Any idea how to solve this?

**Comment by kaito3desuyo** [comment] 2020-09-13 09:27
```
@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()         <-- add
    user_id: number; <-- add

    @Column()
    name: string;

    @ManyToOne(type => User, user => user.photos)
    @JoinColumn({name: 'user_id'}) <-- add
    user: User;
}
```

**Comment by LidorBenYosef** [comment] 2020-09-13 11:22
> ```
> @Entity()
> export class Photo {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @Column()        <-- add
>     user_id: number; <-- add
> 
>     @Column()
>     name: string;
> 
>     @ManyToOne(type => User, user => user.photos)
>     @JoinColumn({name: 'user_id'}) <-- add
>     user: User;
> }
> ```

Still cant access user directly from a photo or photos directly from a user...
just the ID

**Comment by LidorBenYosef** [comment] 2020-09-14 10:14
Any more ideas

**Comment by fgallardograzio** [comment] 2020-09-20 22:36
Relations aren't loaded automatically unless they're set as [eager](https://typeorm.io/#/eager-and-lazy-relations).
To load them manually you need to specify the relations you want to resolve in the find options ([docs](https://typeorm.io/#/many-to-one-one-to-many-relations)).

```typescript
const userRepository = connection.getRepository(User);
const users = await userRepository.find({ relations: ["photos"] });

// or from inverse side

const photoRepository = connection.getRepository(Photo);
const photos = await photoRepository.find({ relations: ["user"] });
//                                        -----------------------
//                                         this is what you need
```

Note that kaito3desuyo's suggestion is not needed for the above to work. However it is a useful trick that allows you to access the id of the related user for a photo (in case you need just that for some use case) without the performance penalty of joining tables and querying for the related fields.

**Comment by imnotjames** [comment] 2020-10-10 09:13
Looks like this was answered and is not a bug in TypeORM.  As such, I'll be closing this out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Closed by imnotjames** 2020-10-10 09:13 UTC
Labels: bug, driver: postgres
