### ISSUE TITLE
mysql loadTables "ORDER BY ORDINAL_POSITION" maybe?

### ISSUE THREAD

**Issue by RickCole21** [typeorm/typeorm#6044] opened 2020-05-11 07:35 UTC
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (0.2.24)

**Steps to reproduce or a small repository showing the problem:**

get table informations by using `connection.createQueryRunner().getTables(tablePath)`

and what I got is columns order by column name by default, and I find code [here](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L1206).

can you guys add options that can return columns ORDER BY ORDINAL_POSITION? 

thanks😁.

**Comment by imnotjames** [comment] 2020-10-17 15:56
Instead of via the query this should be done as a new metadata property into the table column & the table column should sort it.  That way you can do this across all drivers.

**Comment by imnotjames** [comment] 2020-10-17 15:57
However, right now we don't take the ordinal position into account for any of the table column pieces - so even if we di dthat ordering it wouldn't mean things would be in the correct order.

**Comment by AlexMesser** [comment] 2022-04-16 13:33
Duplicate of #541

**Closed by AlexMesser** 2022-04-16 13:33 UTC
Labels: new feature, driver: mysql, driver: mariadb
