### ISSUE TITLE
Migration generation always includes enums

### ISSUE THREAD

**Issue by edevil** [typeorm/typeorm#2959] opened 2018-10-22 09:37 UTC
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.8`

**Steps to reproduce or a small repository showing the problem:**

I have an enum field in my schema:
```ts
export enum SocialType {
  Google,
  Twitter,
}

@Entity()
@Index(["type", "clientId"], { unique: true })
export class SocialLogin {
  @PrimaryColumn("enum", {
    enum: SocialType,
  })
  public type: SocialType;

  @ManyToOne(type => User, user => user.socialLogins, {
    onDelete: "CASCADE",
    primary: true,
  })
  public user: User;

  @CreateDateColumn()
  public createdAt: Date;

  @UpdateDateColumn()
  public updatedAt: Date;

  @Column("text")
  public clientId: string;
}
```

When I try to generate a migration it always includes code to drop/create this enum, even when nothing has changed:

```
import {MigrationInterface, QueryRunner} from "typeorm";

export class teste121540200901636 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "card" ADD "searchVector" tsvector`);
        await queryRunner.query(`DROP INDEX "IDX_02e8e506a27b04322a98dc893a"`);
        await queryRunner.query(`ALTER TYPE "social_login_type_enum" RENAME TO "social_login_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "social_login_type_enum" AS ENUM('Google', 'Twitter', '0', '1')`);
        await queryRunner.query(`ALTER TABLE "social_login" ALTER COLUMN "type" TYPE "social_login_type_enum" USING "type"::"text"::"social_login_type_enum"`);
        await queryRunner.query(`DROP TYPE "social_login_type_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_02e8e506a27b04322a98dc893a" ON "social_login"  ("type", "clientId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_02e8e506a27b04322a98dc893a"`);
        await queryRunner.query(`CREATE TYPE "social_login_type_enum_old" AS ENUM('Google', 'Twitter', '0', '1')`);
        await queryRunner.query(`ALTER TABLE "social_login" ALTER COLUMN "type" TYPE "social_login_type_enum_old" USING "type"::"text"::"social_login_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "social_login_type_enum"`);
        await queryRunner.query(`ALTER TYPE "social_login_type_enum_old" RENAME TO "social_login_type_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_02e8e506a27b04322a98dc893a" ON "social_login"  ("type", "clientId") `);
        await queryRunner.query(`ALTER TABLE "card" DROP COLUMN "searchVector"`);
    }

}
```

**Comment by matthieuproucelle** [comment] 2019-02-28 14:43
I think it's fixed by https://github.com/typeorm/typeorm/pull/3594

**Closed** 2019-02-28 21:58 UTC
Labels: bug, comp: migrations

**Comment by vjfuenzalida** [comment] 2021-07-28 23:58
I have the same problem in MySQL, I even deleted all my migrations and generated a unique migration (lets call it M1) to represent the current state of my entities, but after running that migration (M1), if I run `typeorm schema:log`, the same `ALTER TABLE <tablename> CHANGE <columnname> <columnname> enum (...) NULL`.
Even if I generate a second migration (M2) for those changes (that aren't really changes) and I run it, the same output is returned by `typeorm schema:log`.
Any ideas of the cause of this? could it be related to mysql2 or the definition I have in my entity?
