### ISSUE TITLE
"Connection terminated unexpectedly" and "Client has encountered a connection error and is not queryable"

### ISSUE THREAD

**Issue by seriousManual** [typeorm/typeorm#5223] opened 2019-12-11 14:51 UTC
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.20` (or put your version here)

Hello,
I'm seeing the problem that at one point in a Google Cloud function environment Typeorm looses the database connection to Postgres "Connection terminated unexpectedly".
That by itselfs is probably not that big of an issue because as I understand it Typeorm automatically reconnects when the connection has been lost. (I confirmed this in local tests where I simply shut down the database server, watching the application recovering on its own)

My problem is that this does not happen in our production environment.
After seeing the "Connection terminated unexpectedly" error the connection continues to fail with the error "Client has encountered a connection error and is not queryable".

Can you point me to some approach to handling this failing connection?
How can I detect this condition and how can I reconnect?
Maybe there's some configuration that is missing?

**Comment by GopherJ** [comment] 2020-03-26 12:56
same problem

**Comment by stavalfi** [comment] 2020-07-01 10:17
any update?

**Comment by AlexSun98** [comment] 2020-07-15 08:45
same!

**Comment by imnotjames** [comment] 2020-10-06 06:08
Pretty sure this is a duplicate of #5112

**Closed by imnotjames** 2020-10-06 06:08 UTC
Labels: driver: postgres, question
