### ISSUE TITLE
Error: Cyclic dependency "t" in Android release build

### ISSUE THREAD

**Issue by joris1995** [typeorm/typeorm#4266] opened 2019-06-10 15:16 UTC
**Issue type:**

[X] question
[X] bug report?
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am developing a react-native app where I have several entities referenced to each other with one-to-many, many-to-one and many-to-many relations. In debug, everything works smooth and fine. Data is stored as I need, and when fetching data, the database gives me back everything I expect. I see no flaws in the data.

However, in release version, I keep on getting a really cryptic error message when adding an entity that contains multiple nullable many-to-many relations with other objects: 

`I/ReactNativeJS: { [Error: Cyclic dependency: "t"] line: 583, column: 2036, sourceURL: 'index.android.bundle' }
`

Also, when starting my app, the debugger console gives me this:
![Schermafbeelding 2019-06-10 om 17 14 06](https://user-images.githubusercontent.com/44894683/59205427-306eab00-8ba3-11e9-9c5b-65f48f28a844.png)

It seems to be warning me about cyclic import, but this is react-native, not a normal JS app. It also seems to be unrelated to typeORM, but if I scroll up I can also see a massive amount of cycle warnings from inside TypeORM. Maybe those are related to this issue?

I have been struggling with this all week. I already tried replacing all my many-to-many relations with container objects on the entity that contained multiple many-to-many's, but I keep on getting the same error.

With most errors in typeORM, the error gives me a clear hint about where to look for the problem. This one does not. Also, looking up the error in your documentation (or on google) does not result in any useful information as well. I'm completely in the dark here.

I would like to ask you the following:
- Is this a bug in TypeORM React-Native or in my code?
- If it is a bug in my code, would you please be so kind to document what is causing it and how to solve it?

Any help would be highly appreciated

**Comment by Kononnable** [comment] 2019-06-22 17:22
Didn't use react native, so I might have just some guidance, not the exact steps to get rid of the problem.

- Is it just warnings or errors? Does the code work or is it broken in release build?
- You can disable mangling/minification to get better error messages.
- As for the cyclic dependencies you can specify your relations like `@OneToMany("EntityName")`, but this will require do disable changing of class names during your build stage

**Comment by andreasrueedlinger** [comment] 2019-06-24 19:06
I am/was experiencing the same with electron and angular when using optimization for the production build.
The problem is that the TerserPlugin/UglifyJS mangles the classes and typeorm depends on the class names (name property of the function in JS). If you skip this step in your build then it should work fine again.
For angular-cli there is however no nice solution except disabling optimization. Angular team does not seem to be willing in enabling granular optimization properties, see this issue: https://github.com/angular/angular-cli/issues/3861
You can use this workaround here: https://github.com/keenondrums/angular-builder-custom-terser-options, but it works only for angular versions < 8

@typeorm team: maybe it is worth an enhancement to make the framework code working also for uglified builds?

**Comment by fgomescg** [comment] 2019-07-26 16:38
Same problem here...
React-native Project with Typescript.
When build a realease App this problem  appears.
To temporary fix, insert minify=false in build.gradle.

**Comment by fgomescg** [comment] 2019-07-26 19:07
Hi friend... i found a solution.
Problably your entities have a Circular Dependency.
Use [https://github.com/pahen/madge](https://github.com/pahen/madge) and fix dependencies in your project.

**Comment by JamesDelfini** [comment] 2020-09-09 20:00
> I disregarded using `repository.save()` and uses the [Query Builder as Insert function](https://typeorm.io/#/insert-query-builder) which everything works perfectly. [As stated above as reference,](https://github.com/typeorm/typeorm/issues/4526) confirming many of issues has been posted with exactly the same resolution of the issue. In development this issue would not occur to me, however after post-build(using webpack) running it will show **Circular/Cylic Dependency**.
> 
> TypeORM is designed to use `@Decorator` to wire relation entities together, and it was the exactly the cause of it due to the `repository.save()` are loading up the Relational Entities during the insertion. The behavior of the Circular Dependencies is due to the ES Module is not supported yet, there are a lot of related blog post explaining it more detailed.

Reference and the resolution similar issue and it worked for me, #4190.

**Comment by imnotjames** [comment] 2020-10-05 14:54
Looks like this has been resolved in a few different ways.  I'll be closing it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Closed by imnotjames** 2020-10-05 14:54 UTC
