### ISSUE TITLE
Virtual Column

### ISSUE THREAD

**Issue by grzegorzCieslik95** [typeorm/typeorm#4891] opened 2019-10-10 14:00 UTC
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,
Do you have any idea to create a virtual column?

example
```ts

@Entity('Users')
export default class User extends Base {

    public static build(data: any): User {
        const user: User = new User();
        user.id = data.id;
        user.Name = data.name;

        return user;
    }
    @Column()
    public id?: number;

    @Column()
    public Name: string;

    @Column()
    public email?: string;
}
``` 
In this case, I have column `Name` and `id` in my database, and email should be a virtual column. When I need find all of the column I use 
```ts
 getConnection().getMetadata('Users').ownColumns
```

and I need an email column here with type `Virtual` or similar.

Do you have any idea?

**Comment by leonardofalk** [comment] 2019-10-11 12:29
Virtual columns can be made by simply not wrapping them with typeorm decorators:

```ts
@Entity('users')
class User extends BaseEntity {
  @Column()
  email: string

  @Column()
  encrypted_password: string

  password: string

  @BeforeInsert()
  encryptPassword() {
    this.encrypted_password = bcrypt(this.password)
    this.password = null
  }
}

// then ...

const user = User.create({ email: 'example@example.com', password: '123456' })
await user.save()

console.log(user)
// { email: 'example@example.com', encrypted_password: /* hashed password */ }
```

**Comment by Sornii** [comment] 2020-02-20 12:29
Sorry to not answer your original question, but I can't stand on a bad decision. Sr. @grzegorzCieslik95, I think you misunderstood the point of builders. I'd recommend you to not do what you've done in your code. You should use builders only in case if the constructor of the User is restrict in receiving id and name. Something like this:

`
class User {
  id: string;
  name: string;
  constructor(id: string, name: string) {
    this.id = id;
    this.name = name;
  }
}

class UserBuilder {
  private id: string = 'n/a';
  private name: string = 'n/a';

  withId(id: string) {
    this.id = id;
    return this;
  }

  withName(name: string) {
    this.name = name;
    return this;
  }

  build() {
    return new User(this.id, this.name);
  }
}

class Main {
    main() {
      const user: User = new UserBuilder().withId('aa').withName('bb').build();
      const userWithoutName: User = new UserBuilder().withId('aa').build();

      console.log(user);
      console.log(userWithoutName);
    }
}

new Main().main();
`

**Comment by imnotjames** [comment] 2020-10-06 07:16
Duplicate of #2498

**Closed by imnotjames** 2020-10-06 07:16 UTC
Labels: driver: postgres, question
