### ISSUE TITLE
Same table column with reference for two foreign key of different tables

### ISSUE THREAD

**Issue by paipeco** [typeorm/typeorm#3035] opened 2018-11-02 20:37 UTC
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**-- Create table**
create table LINE(id   NUMBER not null, name VARCHAR2(30) not null);
alter table LINE add constraint LINE_PK primary key (ID);
create table MODEL(id NUMBER not null, line_id NUMBER not null, name VARCHAR2(30) not null);
alter table MODEL add constraint MODEL_PK primary key (LINE_ID, ID);
alter table MODEL add constraint MODEL_LINE_FK foreign key (LINE_ID) references LINE (ID);
create table PRODUCT(id NUMBER not null, line_id NUMBER, model_id NUMBER, name VARCHAR2(50) not null);
alter table PRODUCT add constraint PRODUCT_PK primary key (ID);
alter table PRODUCT add constraint PRODUCT_LINE_FK foreign key (LINE_ID) references LINE (ID);
alter table PRODUCT add constraint PRODUCT_MODEL_FK foreign key (LINE_ID, MODEL_ID) references MODEL (LINE_ID, ID);

**-- Insert records**
insert into LINE (id, name) values (1, 'Line 1');
insert into MODEL (id, line_id, name) values (1, 1, 'Model 1');
insert into PRODUCT (id, line_id, model_id, name) values (1, 1, null, 'Product 1 - Only Line without Model');
insert into PRODUCT (id, line_id, model_id, name) values (2, 1, 1, 'Product 1 - With Model');
commit;

**Entities**
```
// Line.ts
import { Entity, PrimaryColumn, Column } from "typeorm";

@Entity({ name: "LINE" })
export class Line {
    @PrimaryColumn({ name: "ID" })
    id: number;

    @Column({ name: "NAME" })
    name: string;
}

```

```
// Model.ts
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from "typeorm";
import { Line } from "./Line";

@Entity({ name: "MODEL" })
export class Model {
    @PrimaryColumn({ name: "ID" })
    id: number;

    @Column({ name: "NAME" })
    name: string;

    @ManyToOne((type) => Line, { primary: true })
    @JoinColumn({ name: "LINE_ID" })
    line: Line;
}
```

```
// Product.ts
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from "typeorm";
import { Line } from "./Line";
import { Model } from "./Model";

@Entity({ name: "PRODUCT" })
export class Product {
    @PrimaryColumn({ name: "ID" })
    id: number;

    @Column({ name: "NAME" })
    name: string;

    @ManyToOne((type) => Line)
    @JoinColumn({ name: "LINE_ID" })
    line: Line;

    @ManyToOne((type) => Model)
    @JoinColumn([ { name: "LINE_ID", referencedColumnName: "line" }, { name: "MODEL_ID", referencedColumnName: "id" } ])
    model: Model;
}
```

```
// file Controller.ts
import { Request, Response } from "express";
import { getRepository } from "typeorm";
import { Product } from "../../model/entity/test/Product";

export class Controller {
    public async getAllLines(req: Request, res: Response) {
        try {
            let lines = await getRepository(Product)
                .createQueryBuilder("pro")
                .leftJoinAndSelect("pro.line", "line")
                .leftJoinAndSelect("pro.model", "model")
                .getMany();

            res.json(lines);
        } catch (err) {
        }
    }
}
```

**get this error**
```
Error: ORA-00904: "LINE"."LINE"."ID": invalid identifier errorNum: 904, offset: 330
this query...
SELECT "pro"."ID" AS "pro_ID"
       ,"pro"."NAME" AS "pro_NAME"
       ,"pro"."LINE_ID" AS "pro_LINE_ID"
       ,"pro"."MODEL_ID" AS "pro_MODEL_ID"
       ,"line"."ID" AS "line_ID"
       ,"line"."NAME" AS "line_NAME"
       ,"model"."ID" AS "model_ID"
       ,"model"."NAME" AS "model_NAME"
       ,"model"."LINE_ID" AS "model_LINE_ID"
  FROM "PRODUCT" "pro"
  LEFT JOIN "LINE" "line"
    ON line.line.id = "pro"."LINE_ID" <--error join line.line.id-->
  LEFT JOIN "MODEL" "model"
    ON "model"."LINE_ID" = "pro"."LINE_ID"
   AND "model"."ID" = "pro"."MODEL_ID"
```

**Comment by Kononnable** [comment] 2018-12-08 19:14
@paipeco  Did you resolve your issue?

**Comment by paipeco** [comment] 2018-12-11 17:56
Hi @Kononnable.

I decided to do a duplicate column mapping with a different attribute name.
In one of them I used a decorator @ManyToOne and another just an @Column decorator.
I also created a false attribute to set the value with an @AfterLoad function.

in Product.ts looks like this:
```
// Product.ts
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn, AfterLoad, getRepository } from "typeorm";
import { Line } from "./Line";
import { Model } from "./Model";

@Entity({ name: "PRODUCT" })
export class Product {
    @PrimaryColumn({ name: "ID" })
    id: number;

    @Column({ name: "NAME" })
    name: string;

    @Column({ name: "LINE_ID" })
    lineId: number;
    // fake object
    line: Line;

    @ManyToOne((type) => Model)
    @JoinColumn([ { name: "LINE_ID", referencedColumnName: "line" }, { name: "MODEL_ID", referencedColumnName: "id" } ])
    model: Model;

    // set line object
    @AfterLoad()
    async afterLoad() {
        this.line = await getRepository(Line).findOne(this.lineId);
        delete this.lineId;
    }
}
```

My controller class:
```
// Controller.ts
...
let products = await getRepository(Product)
        .createQueryBuilder("pro")
        .leftJoinAndSelect("pro.model", "model")
        .leftJoinAndSelect("model.line", "line")
        .getMany();
...
```
It's working, but in unnormalized way!
Do you have any idea?

**Comment by pleerock** [comment] 2019-01-04 14:34
Can you try to change following:

```ts
    @ManyToOne((type) => Model)
    @JoinColumn([ { name: "LINE_ID", referencedColumnName: "line" }, { name: "MODEL_ID", referencedColumnName: "id" } ])
    model: Model;
```

to: 

```ts
    @ManyToOne((type) => Model)
    @JoinColumn([ { name: "LINE_ID", referencedColumnName: "LINE_ID" }, { name: "MODEL_ID", referencedColumnName: "id" } ])
    model: Model;
```

?

**Comment by alfonsoal1983** [comment] 2019-03-29 10:13
Hi, I know where the problem is. I'm going to paste an example, an example:

`
@Entity({name: 'Cars'})
export class Cars {

    @PrimaryColumn({name: 'CARID'})
    carId: string;

    @Column({name: 'DESCRIPTION'})
    description: string;

    @OneToMany(type => Tires, tire => tire.car)
    tires?: Tires[];
}

@Entity({name: 'Bikes'})
export class Bikes {

    @PrimaryColumn({name: 'BIKEID'})
    bikeId: string;

    @Column({name: 'DESCRIPTION'})
    description: string;

    @OneToMany(type => Tires, tire => tire.bike)
    tires?: Tires[];
}

@Entity({name: 'Tires'})
export class Tires {

    @PrimaryColumn({name: 'id'})
    id: string;

    @Column({name: 'DESCRIPTION'})
    description: string;
	
    @ManyToOne(type => Bikes, bike => bike.tires)
    @JoinColumn({name: 'VEHICLEID', referencedColumnName: 'bikeId'})
    bike?: Bikes;

    @ManyToOne(type => Cars, car => car.tires)
    @JoinColumn({name: 'VEHICLEID', referencedColumnName: 'carId'})
    car?: Cars;
}

await getRepository(Tires)
	.createQueryBuilder("tires")
	.leftJoinAndSelect("tires.car", "car")
	.leftJoinAndSelect("tires.bike", "bike")
	.getMany();


SELECT "tires"."id" AS "tires_id", "tires"."DESCRIPTION" AS "tires_DESCRIPTION", etc...
FROM "Tires" "tires"
LEFT JOIN "Bikes" "bike" ON bike.carId="tires"."VEHICLEID" <-- This is the problem
LEFT JOIN "Cars" "car" ON "car"."CARID"="tires"."VEHICLEID"
`

When a column is a foreign key of two tables and the reference id of those tables is not the same, it does not create the query well.

If you try this:
`
@JoinColumn({name: 'VEHICLEID', referencedColumnName: 'CARID'})
`
It throws this error:
Referenced column CARID was not found in entity Cars

**Comment by imnotjames** [comment] 2020-10-10 09:54
Duplicate of #1668

**Closed by imnotjames** 2020-10-10 09:54 UTC
Labels: bug, driver: oracle, driver: postgres, new feature, question
