### ISSUE TITLE
Add point in time option for queries in temporal table

### ISSUE THREAD

**Issue by pierreis** [typeorm/typeorm#6737] opened 2020-09-18 07:42 UTC
**Issue type:**

[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[X] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

Several database engines among the ones supported by TypeORM do support point-in-time queries for database-versioned tables. Specifically:

- CockroachDB supports `AS OF SYSTEM TIME [time]` clause in `SELECT`, which enables both point in time queries, but also follower-reads:

    - https://www.cockroachlabs.com/docs/stable/follower-reads.html

    - https://www.cockroachlabs.com/docs/stable/as-of-system-time.html

- MSSQL / Azure SQL do support various versions, including `AS OF`, `FROM ... TO`, `BETWEEN ... AND` or `CONTAINED IN`:

    - https://docs.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-ver15

    - https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver15

- Oracle does support _flashback queries_, including the `AS OF` clause:

    - https://docs.oracle.com/cd/B19306_01/B14251_01/adfns_flashback.htm#ADFNS1008

It would be great to see support for this landing in TypeORM. As a first step,  I would suggest adding a `asOf: Date` optional parameter to `FindOptions` as well as `FindManyOptions`. Down the road, this option can be extended to accept additional settings for more complex MSSQL / Oracle conditions.

**Comment by imnotjames** [comment] 2021-06-25 05:47
Duplicate of #4646

**Closed by imnotjames** 2021-06-25 05:47 UTC
Labels: driver: cockroachdb, driver: mssql, driver: oracle, new feature
