### ISSUE TITLE
Changing a Varchar Column in Postgres Always Results in Column Recreation

### ISSUE THREAD

**Issue by adamlarsonlee** [typeorm/typeorm#9255] opened 2022-08-01 20:46 UTC
## Issue Description

In Postgres, when a column type is specified as varchar, any change to that column results in a drop/add of the column which incurs data loss. For example, let's say a table was created as follows:

```typescript
import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class testCreateTable1700000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'test_table',
        columns: [
          {
            name: 'id',
            type: 'int',
            isPrimary: true,
          },
          {
            name: 'something',
            type: 'varchar',
            length: '18',
            isNullable: false,
          },
        ],
      })
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('test_table');
  }
}

```

Later if we change the column like so (make it nullable):

```typescript
import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class testChangeColumn1800000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'varchar',
        length: '18',
        isNullable: true,
      })
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'varchar',
        length: '18',
        isNullable: false,
      })
    );
  }
}
```

It will result in the column being dropped and recreated. The reason for this is that [one of the things that triggers column recreation is a change in type](https://github.com/typeorm/typeorm/blob/486f8c582170dbadbd875e00d09d26359b2fd8be/src/driver/postgres/PostgresQueryRunner.ts#L791):

```typescript
if (oldColumn.type !== newColumn.type
            || oldColumn.length !== newColumn.length
            || newColumn.isArray !== oldColumn.isArray
            || (!oldColumn.generatedType && newColumn.generatedType === "STORED")
            || (oldColumn.asExpression !== newColumn.asExpression && newColumn.generatedType === "STORED")) {
            // To avoid data conversion, we just recreate column
            await this.dropColumn(table, oldColumn);
            await this.addColumn(table, newColumn);
```

When the table is loaded the column has a type of character varying, not varchar. This means the types of the migration and the existing table are mismatched and the column is recreated.

### Expected Behavior

The table column is not recreated if the type is specified as varchar.

### Actual Behavior

The table column is dropped and recreated even though we aren't changing the column length, resulting in data loss.

```
query: ALTER TABLE "test_table" DROP COLUMN "something"
query: ALTER TABLE "test_table" ADD "something" varchar(18)
```

### Steps to Reproduce

1. Create a table with a varchar column (not nullable)
2. Change the column in a way that should not result in recreation (make it nullable)
3. The second migration will cause the column to be dropped and recreated, resulting in data loss

```typescript
import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class testCreateTable1700000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'test_table',
        columns: [
          {
            name: 'id',
            type: 'int',
            isPrimary: true,
          },
          {
            name: 'something',
            type: 'varchar',
            length: '18',
            isNullable: false,
          },
        ],
      })
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('test_table');
  }
}
```

```typescript
import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class testChangeColumn1800000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'varchar',
        length: '18',
        isNullable: true,
      })
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      'test_table',
      'something',
      new TableColumn({
        name: 'something',
        type: 'varchar',
        length: '18',
        isNullable: false,
      })
    );
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.5.4  | 
| TypeORM version     | 2.4.5 | 

Note: This problem looks to exist in the current version of TypeORM as well.

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by joaogn** [comment] 2022-08-08 15:03
It happening with me today too, I'm writing the query directly in the migration.
``` await queryRunner.query(`ALTER TABLE test_table ALTER COLUMN something DROP NOT NULL;`) ```

**Comment by adamlarsonlee** [comment] 2022-08-08 15:30
@joaogn If you create your column as `character varying` instead of `varchar` it will work as you expect I believe.

**Comment by Alex-Bond** [comment] 2022-08-17 21:03
Also started to experience this problem after upgrading to the latest version.

**Comment by AlexMesser** [comment] 2022-09-03 15:00
Duplicate of #3357

**Closed by AlexMesser** 2022-09-03 15:00 UTC
Labels: bug, requires triage
